/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import StringDiagrams.Interpretation

/-!
# The nilHecke category as a presented linear category

M. Khovanov, A. Lauda, *A diagrammatic approach to categorification of quantum groups I*,
arXiv:0803.4121v2, §2.2, Example 3.

The nilHecke ring `NH_n` is the endomorphism ring of `n` strands in the linear monoidal
category with one strand colour, generated by a dot and a crossing, subject to

* `ψ² = 0` (a double crossing vanishes),
* `ψ₁ψ₂ψ₁ = ψ₂ψ₁ψ₂` (braid relation),
* `x_a ψ_a − ψ_a x_{a+1} = 1` and `ψ_a x_a − x_{a+1} ψ_a = 1` (dot slides),

together with the interchange law, which accounts for far commutativity. The comparison with
the nilHecke ring `Categorification.NilHecke.nilHecke k n` (a subalgebra of
`End_k(k[x_1, …, x_n])`) is in `Categorification.Diagrams.NilHecke.Comparison`.

## Conventions

Strands are numbered from `0`: `ψ k n a` is the crossing of strands `a` and `a + 1` among `n`
and `x k n a` is a dot on strand `a` (the paper's `∂_{a+1}` and `x_{a+1}`, and the
`NilHecke.dd k n a`, `NilHecke.mulX k n a` of `Categorification.Algebra.NilHecke`). Products in
`End` are composition of operators (`f * g = g ≫ f`: `g` is drawn below `f`), as for
operators on polynomials.

## Main definitions

* `sig`, `pres k`, `NH k`, `strands n`: the signature, the presentation over a commutative
  ring `k`, the presented category and the object of `n` strands.
* `x k n a`, `ψ k n a : End ((pres k).obj (strands n))`: a dot and a crossing at a symbolic
  position in a symbolic width (zero when out of range).
-/

noncomputable section

namespace Categorification.NilHecke.Diagram

open CategoryTheory StringDiagrams

/-- The generators: a dot and a crossing. -/
inductive Gen
  | dot
  | cross
  deriving DecidableEq

/-- Number of strands at the bottom (and top) of a generator. -/
def Gen.arity : Gen → ℕ
  | .dot => 1
  | .cross => 2

/-- The nilHecke signature: one region, one colour, a dot and a crossing (both even). -/
def sig : Signature where
  Region := Unit
  Colour := Unit
  colourSrc _ := ()
  colourTgt _ := ()
  Gen := Gen
  dom g := List.replicate g.arity ()
  cod g := List.replicate g.arity ()
  left _ := ()
  right _ := ()

instance : Subsingleton sig.Region := inferInstanceAs (Subsingleton Unit)

/-- `n` strands. -/
def strands (n : ℕ) : Obj sig := ⟨(), List.replicate n ()⟩

@[simp] theorem strands_word_length (n : ℕ) : (strands n).word.length = n := by
  simp [strands]

theorem list_unit_ext {l₁ l₂ : List Unit} (h : l₁.length = l₂.length) : l₁ = l₂ := by
  induction l₁ generalizing l₂ with
  | nil => cases l₂ with
    | nil => rfl
    | cons _ _ => simp at h
  | cons a l ih => cases l₂ with
    | nil => simp at h
    | cons b l₂ => rw [ih (by simpa using h)]

/-- Words in the single colour are determined by their length. -/
@[simp] theorem word_eq_iff {l₁ l₂ : List sig.Colour} : l₁ = l₂ ↔ l₁.length = l₂.length :=
  ⟨congrArg List.length, list_unit_ext⟩

theorem obj_ext {a b : Obj sig} (h : a.word.length = b.word.length) : a = b :=
  Obj.ext (Subsingleton.elim (α := Unit) _ _) (list_unit_ext h)

/-- Every object is `strands` of its width. -/
theorem eq_strands (a : Obj sig) : a = strands a.word.length :=
  obj_ext (by simp)

theorem layer_ext {L₁ L₂ : Layer sig} (hl : L₁.left.length = L₂.left.length)
    (hg : L₁.gen = L₂.gen) (hr : L₁.right.length = L₂.right.length) : L₁ = L₂ :=
  Layer.ext (Subsingleton.elim (α := Unit) _ _) (list_unit_ext hl) hg (list_unit_ext hr)

@[simp] theorem sig_dom_length (g : Gen) : (sig.dom g).length = g.arity := by
  simp [sig]

@[simp] theorem sig_cod_length (g : Gen) : (sig.cod g).length = g.arity := by
  simp [sig]

/-- Every layer preserves the number of strands. -/
theorem layer_cod_length (L : Layer sig) : L.cod.word.length = L.dom.word.length := by
  simp

/-- The generator `g` with `i` strands to its left, in a diagram on `n` strands. -/
def lay (n i : ℕ) (g : Gen) : Layer sig :=
  ⟨(), List.replicate i (), g, List.replicate (n - i - g.arity) ()⟩

theorem lay_valid (n i : ℕ) (g : Gen) : (lay n i g).Valid := Layer.valid_of_subsingleton _

theorem lay_dom {n i : ℕ} {g : Gen} (h : i + g.arity ≤ n) : (lay n i g).dom = strands n :=
  obj_ext (by simp [lay, Layer.dom, strands, sig]; omega)

theorem lay_cod {n i : ℕ} {g : Gen} (h : i + g.arity ≤ n) : (lay n i g).cod = strands n :=
  obj_ext (by simp [lay, Layer.cod, strands, sig]; omega)

/-- The layer `lay n i g` as an endomorphism of `n` strands in the free 2-category. -/
def dlay {n i : ℕ} {g : Gen} (h : i + g.arity ≤ n) : strands n ⟶ strands n :=
  Diagram.layer (lay n i g) (lay_valid n i g) (lay_dom h) (lay_cod h)

@[simp] theorem layers_dlay {n i : ℕ} {g : Gen} (h : i + g.arity ≤ n) :
    Diagram.layers (dlay h) = [lay n i g] := rfl

/-! ## The presentation -/

/-- The defining relations (besides interchange). -/
inductive Rel
  | crossSq
  | braid
  | slideA
  | slideB

/-- Width of the defining relations. -/
def Rel.width : Rel → ℕ
  | .crossSq => 2
  | .braid => 3
  | .slideA => 2
  | .slideB => 2

variable (k : Type*) [CommRing k]

open LinDiagram in
/-- The defining relations, in the free 2-category (`f ≫ g` means `f` below `g`; in `End`,
`f ≫ g = g * f`):
* `crossSq` (`ψ₀ ψ₀ = 0`): `ψ₀ ≫ ψ₀`;
* `braid` (`ψ₀ ψ₁ ψ₀ = ψ₁ ψ₀ ψ₁`): `ψ₀ ≫ ψ₁ ≫ ψ₀ - ψ₁ ≫ ψ₀ ≫ ψ₁`;
* `slideA` (`x₀ ψ₀ - ψ₀ x₁ = 1`): `ψ₀ ≫ x₀ - x₁ ≫ ψ₀ - 1`;
* `slideB` (`ψ₀ x₀ - x₁ ψ₀ = 1`): `x₀ ≫ ψ₀ - ψ₀ ≫ x₁ - 1`. -/
def relation : (r : Rel) → LinDiagram k (strands r.width) (strands r.width)
  | .crossSq =>
      of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide))
  | .braid =>
      of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .cross) (i := 1) (by decide) ≫
          dlay (g := .cross) (i := 0) (by decide)) -
        of (dlay (g := .cross) (i := 1) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide) ≫
          dlay (g := .cross) (i := 1) (by decide))
  | .slideA =>
      of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .dot) (i := 0) (by decide)) -
        of (dlay (g := .dot) (i := 1) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide)) -
        of (𝟙 _)
  | .slideB =>
      of (dlay (g := .dot) (i := 0) (by decide) ≫ dlay (g := .cross) (i := 0) (by decide)) -
        of (dlay (g := .cross) (i := 0) (by decide) ≫ dlay (g := .dot) (i := 1) (by decide)) -
        of (𝟙 _)

/-- The nilHecke presentation over `k`. -/
def pres : Presentation sig k where
  Rel := Rel
  dom r := strands r.width
  cod r := strands r.width
  rel := relation k

/-- The nilHecke category over `k`: its endomorphism ring of `n` strands is `NH_n`
(`Categorification.NilHecke.Diagram.endEquiv`). -/
abbrev NH : Type _ := (pres k).Presented

/-- A dot on strand `i` of `n` (zero if `i ≥ n`). -/
def x (n i : ℕ) : End ((pres k).obj (strands n)) :=
  if h : i < n then (pres k).diag (dlay (g := .dot) h) else 0

/-- The crossing of strands `i` and `i + 1` of `n` (zero if `i + 1 ≥ n`). -/
def ψ (n i : ℕ) : End ((pres k).obj (strands n)) :=
  if h : i + 1 < n then (pres k).diag (dlay (g := .cross) h) else 0

theorem x_def {n i : ℕ} (h : i < n) : x k n i = (pres k).diag (dlay (g := .dot) h) := dif_pos h

theorem ψ_def {n i : ℕ} (h : i + 1 < n) : ψ k n i = (pres k).diag (dlay (g := .cross) h) :=
  dif_pos h

theorem x_of_le {n i : ℕ} (h : n ≤ i) : x k n i = 0 := dif_neg (by omega)

theorem ψ_of_le {n i : ℕ} (h : n ≤ i + 1) : ψ k n i = 0 := dif_neg (by omega)

end Categorification.NilHecke.Diagram

end
