/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Diagrams.NilHecke.Dots
import Categorification.Diagrams.NilHecke.PolyRep
import Categorification.KLR.Examples.NilHecke
import StringDiagrams.Generation

/-!
# The diagrammatic nilHecke ring is the nilHecke ring

M. Khovanov, A. Lauda, *A diagrammatic approach to categorification of quantum groups I*,
arXiv:0803.4121v2, §2.2, Example 3: the nilHecke ring `NH_n` is the subring of
`End(k[x_1, …, x_n])` generated by the multiplications by `x_a` and the divided differences
`∂_a`, and is described diagrammatically by dots and crossings on `n` strands subject to the
nilHecke relations.

This file compares the endomorphism ring of `n` strands in the presented category `NH k` of
`Categorification.Diagrams.NilHecke.Basic` (only the square, braid and two dot slide relations
are imposed, far commutativity being the interchange law) with the nilHecke ring
`Categorification.NilHecke.nilHecke k n` of `Categorification.Algebra.NilHecke`, for every
`n` (including `n = 0, 1`) over every integral domain `k` (the paper: `k = ℤ`).

## Main results

* `fromNH k n : nilHecke k n →ₐ[k] End ((pres k).obj (strands n))`, sending `mulX k n a ↦ x k n a`
  and `dd k n j ↦ ψ k n j` (from the presentation `KLR.NilHecke.lift` of `NH_n`).
* `realize_fromNH_comp_rename` : the polynomial representation `realize k n` of the diagrammatic
  category, restricted to `k[x_0, …, x_{n-1}] ⊆ k[x_0, x_1, …]`, recovers the defining action of
  `NH_n`; hence `fromNH_injective`.
* `fromNH_surjective` : every endomorphism of `n` strands is a combination of composites of dot
  and crossing layers (`StringDiagrams.Presentation.hom_induction_layers`).
* `endEquiv k n : End ((pres k).obj (strands n)) ≃ₐ[k] nilHecke k n`, the headline algebra
  isomorphism, with `endEquiv_x`, `endEquiv_ψ`, `endEquiv_dots`, and the compatibility
  `rename_comp_endEquiv` with the polynomial representation.
* `realize_injective` : the polynomial representation of the diagrammatic nilHecke category is
  faithful on `n` strands.
* `basis k n ρ hρ` : the basis `{ψ_{ρ w} x^u}` of the diagrammatic endomorphism ring,
  transported from `KLR.NilHecke.basis` (KL I, Theorem 2.5 for `ν = n i`).
-/

noncomputable section

namespace Categorification.NilHecke.Diagram

open CategoryTheory StringDiagrams MvPolynomial Equiv TypeA

variable (k : Type*) [CommRing k]

/-! ## The nilHecke relations, as a family -/

/-- The dots and crossings on `n` strands satisfy the defining relations of `NH_n` (KL I §2.2,
Example 3), in the form required by the presentation `KLR.NilHecke.lift`. -/
theorem isNilHeckeFamily (n : ℕ) :
    KLR.NilHecke.IsNilHeckeFamily n (fun a : Fin n => x k n a) (ψ k n) where
  x_comm a b := x_mul_x_comm k n a b
  d_x_comm _ _ h₁ h₂ := (x_mul_ψ_comm k h₁ h₂).symm
  d_comm _ _ h := ψ_mul_ψ_comm k h
  d_sq := ψ_mul_ψ k n
  braid := ψ_braid k n
  x_d_sub _ h := x_mul_ψ_sub_ψ_mul_x k h
  d_x_sub _ h := ψ_mul_x_sub_x_mul_ψ k h
  d_zero _ h := ψ_of_le k h

/-- Polynomials in `x_0, …, x_{n-1}` as polynomials in all the variables. -/
abbrev ιPoly (n : ℕ) : MvPolynomial (Fin n) k →ₗ[k] MvPolynomial ℕ k :=
  (rename (Fin.val : Fin n → ℕ)).toLinearMap

theorem ιPoly_injective (n : ℕ) : Function.Injective (ιPoly k n) :=
  rename_injective _ Fin.val_injective

/-- Retyping a diagram along equalities of its ends. -/
theorem diag_cast {a b a' b' : Obj sig} (f : a ⟶ b) (ha : a = a') (hb : b = b') :
    (pres k).diag (Diagram.cast f ha hb) =
      eqToHom (congrArg (pres k).obj ha.symm) ≫ (pres k).diag f ≫
        eqToHom (congrArg (pres k).obj hb) := by
  subst ha hb; simp

/-! ## The comparison map -/

variable [IsDomain k]

/-- The comparison map `NH_n → End(n strands)`, `x_a ↦ x_a`, `∂_j ↦ ψ_j`. -/
def fromNH (n : ℕ) : nilHecke k n →ₐ[k] End ((pres k).obj (strands n)) :=
  KLR.NilHecke.lift (isNilHeckeFamily k n)

@[simp] theorem fromNH_mulX (n : ℕ) (a : Fin n) :
    fromNH k n ⟨mulX k n a, mulX_mem a⟩ = x k n a :=
  KLR.NilHecke.lift_mulX _ a

@[simp] theorem fromNH_dd (n j : ℕ) : fromNH k n ⟨dd k n j, dd_mem j⟩ = ψ k n j :=
  KLR.NilHecke.lift_dd _ j

theorem realize_fromNH_mulX_comp_rename (n : ℕ) (a : Fin n) :
    realize k n (fromNH k n ⟨mulX k n a, mulX_mem a⟩) ∘ₗ ιPoly k n =
      ιPoly k n ∘ₗ mulX k n a := by
  rw [fromNH_mulX, realize_x k a.isLt]
  refine LinearMap.ext fun f => ?_
  simp

theorem realize_fromNH_dd_comp_rename (n j : ℕ) :
    realize k n (fromNH k n ⟨dd k n j, dd_mem j⟩) ∘ₗ ιPoly k n = ιPoly k n ∘ₗ dd k n j := by
  rw [fromNH_dd]
  by_cases hj : j + 1 < n
  · rw [realize_ψ k hj, dd_of_lt hj]
    refine LinearMap.ext fun f => ?_
    simp only [LinearMap.comp_apply, AlgHom.toLinearMap_apply]
    have hne : (⟨j, by omega⟩ : Fin n) ≠ ⟨j + 1, hj⟩ := by simp [Fin.ext_iff]
    rw [rename_ddiff (k := k) Fin.val_injective hne f]
  · rw [ψ_of_le k (by omega), dd_eq_zero (by omega), map_zero, LinearMap.zero_comp,
      LinearMap.comp_zero]

/-- **Compatibility with the polynomial representation.** On polynomials in the first `n`
variables, the polynomial representation of the image of `a ∈ NH_n` is the defining action of
`a`. -/
theorem realize_fromNH_comp_rename (n : ℕ) (a : nilHecke k n) :
    realize k n (fromNH k n a) ∘ₗ ιPoly k n = ιPoly k n ∘ₗ (a : Module.End k _) := by
  obtain ⟨T, hT⟩ := a
  induction hT using Algebra.adjoin_induction with
  | mem T h =>
    rcases h with ⟨a, rfl⟩ | ⟨j, rfl⟩
    · exact realize_fromNH_mulX_comp_rename k n a
    · exact realize_fromNH_dd_comp_rename k n j
  | algebraMap r =>
    have e := (fromNH k n).commutes r
    have e' := (realize k n).commutes r
    refine (congrArg (fun F => realize k n F ∘ₗ ιPoly k n) e).trans ?_
    rw [e']
    refine LinearMap.ext fun f => ?_
    simp [Algebra.algebraMap_eq_smul_one]
  | add T U hT hU ihT ihU =>
    have e := map_add (fromNH k n) ⟨T, hT⟩ ⟨U, hU⟩
    refine (congrArg (fun F => realize k n F ∘ₗ ιPoly k n) e).trans ?_
    rw [map_add, LinearMap.add_comp, ihT, ihU, ← LinearMap.comp_add]
  | mul T U hT hU ihT ihU =>
    have e := map_mul (fromNH k n) ⟨T, hT⟩ ⟨U, hU⟩
    refine (congrArg (fun F => realize k n F ∘ₗ ιPoly k n) e).trans ?_
    rw [map_mul, Module.End.mul_eq_comp, LinearMap.comp_assoc, ihU, ← LinearMap.comp_assoc, ihT,
      LinearMap.comp_assoc]
    rfl

theorem fromNH_injective (n : ℕ) : Function.Injective (fromNH k n) := by
  refine (injective_iff_map_eq_zero _).2 fun a ha => ?_
  have h := realize_fromNH_comp_rename k n a
  rw [ha, map_zero, LinearMap.zero_comp] at h
  refine Subtype.ext (LinearMap.ext fun f => ?_)
  apply ιPoly_injective k n
  have := LinearMap.congr_fun h f
  simp only [LinearMap.zero_apply, LinearMap.comp_apply] at this
  rw [← this, ZeroMemClass.coe_zero, LinearMap.zero_apply, map_zero]

/-! ## Surjectivity: diagrams are generated by dots and crossings -/

/-- The induction predicate for surjectivity: morphisms between objects of different widths
vanish, and endomorphisms of `n` strands lie in the image of `fromNH k n`. -/
def InImage (n : ℕ) {a b : Obj sig} (g : (pres k).obj a ⟶ (pres k).obj b) : Prop :=
  (a.word.length ≠ b.word.length → g = 0) ∧
    ∀ (ha : a = strands n) (hb : b = strands n),
      eqToHom (congrArg (pres k).obj ha.symm) ≫ g ≫ eqToHom (congrArg (pres k).obj hb) ∈
        (fromNH k n).range

theorem inImage_layer (n : ℕ) (L : Layer sig) (hv : L.Valid) :
    InImage k n ((pres k).diag (Diagram.ofLayer L hv)) := by
  refine ⟨fun hne => absurd (layer_cod_length L).symm hne, fun ha hb => ?_⟩
  have hlen : L.left.length + L.gen.arity + L.right.length = n := by
    have := congrArg (fun o : Obj sig => o.word.length) ha
    simpa [Layer.dom, Nat.add_assoc] using this
  rw [← diag_cast _ _ ha hb]
  rcases hg : L.gen with _ | _
  · rw [hg] at hlen
    refine ⟨⟨mulX k n ⟨L.left.length, by simp [Gen.arity] at hlen; omega⟩, mulX_mem _⟩,
      (fromNH_mulX k n _).trans ?_⟩
    rw [x_def k (by simp [Gen.arity] at hlen; omega)]
    apply Presentation.diag_eq_of_layers_eq
    simp only [layers_dlay, Diagram.layers_cast, Diagram.layers_ofLayer, List.cons.injEq,
      and_true]
    refine layer_ext ?_ ?_ ?_ <;> simp [lay, hg, Gen.arity] at hlen ⊢
    omega
  · rw [hg] at hlen
    refine ⟨⟨dd k n L.left.length, dd_mem _⟩, (fromNH_dd k n _).trans ?_⟩
    rw [ψ_def k (by simp [Gen.arity] at hlen; omega)]
    apply Presentation.diag_eq_of_layers_eq
    simp only [layers_dlay, Diagram.layers_cast, Diagram.layers_ofLayer, List.cons.injEq,
      and_true]
    refine layer_ext ?_ ?_ ?_ <;> simp [lay, hg, Gen.arity] at hlen ⊢
    omega

theorem inImage (n : ℕ) {a b : Obj sig} (g : (pres k).obj a ⟶ (pres k).obj b) :
    InImage k n g := by
  induction g using (pres k).hom_induction_layers with
  | nil h =>
    refine ⟨fun hne => absurd (congrArg (fun o : Obj sig => o.word.length) h) hne,
      fun ha hb => ?_⟩
    subst ha hb
    simp only [eqToHom_refl, Presentation.diag_id, Category.id_comp]
    exact (fromNH k n).range.one_mem
  | layer L hv => exact inImage_layer k n L hv
  | comp f g hf hg =>
    rename_i a b c
    refine ⟨fun hne => ?_, fun ha hc => ?_⟩
    · by_cases hab : a.word.length = b.word.length
      · rw [hg.1 (fun h => hne (hab.trans h)), Limits.comp_zero]
      · rw [hf.1 hab, Limits.zero_comp]
    · by_cases hb : b.word.length = n
      · have hb' : b = strands n := obj_ext (by simpa using hb)
        have e : eqToHom (congrArg (pres k).obj ha.symm) ≫ (f ≫ g) ≫
            eqToHom (congrArg (pres k).obj hc) =
            (eqToHom (congrArg (pres k).obj ha.symm) ≫ f ≫ eqToHom (congrArg (pres k).obj hb')) ≫
              (eqToHom (congrArg (pres k).obj hb'.symm) ≫ g ≫
                eqToHom (congrArg (pres k).obj hc)) := by
          simp
        rw [e]
        exact (fromNH k n).range.mul_mem (hg.2 hb' hc) (hf.2 ha hb')
      · have hf0 : f = 0 := hf.1 (by rw [ha]; simpa using Ne.symm hb)
        simp only [hf0, Limits.zero_comp, Limits.comp_zero]
        exact (fromNH k n).range.zero_mem
  | zero =>
    refine ⟨fun _ => rfl, fun ha hb => ?_⟩
    rw [Limits.zero_comp, Limits.comp_zero]
    exact (fromNH k n).range.zero_mem
  | add f g hf hg =>
    refine ⟨fun hne => by rw [hf.1 hne, hg.1 hne, add_zero], fun ha hb => ?_⟩
    rw [Preadditive.add_comp, Preadditive.comp_add]
    exact (fromNH k n).range.add_mem (hf.2 ha hb) (hg.2 ha hb)
  | smul r f hf =>
    refine ⟨fun hne => by rw [hf.1 hne, smul_zero], fun ha hb => ?_⟩
    rw [Linear.smul_comp, Linear.comp_smul]
    exact (fromNH k n).range.smul_mem (hf.2 ha hb) r

theorem fromNH_surjective (n : ℕ) : Function.Surjective (fromNH k n) := by
  intro f
  obtain ⟨a, ha⟩ := (inImage k n f).2 rfl rfl
  exact ⟨a, by simpa using ha⟩

/-! ## The isomorphism -/

/-- **The diagrammatic nilHecke ring is the nilHecke ring** (KL I, arXiv:0803.4121v2, §2.2,
Example 3). Over an integral domain `k`, the endomorphism algebra of `n` strands in the
presented nilHecke category (dots and crossings modulo the square, braid and dot slide
relations and the interchange law) is isomorphic to `NH_n ⊆ End_k(k[x_1, …, x_n])`, via
`x k n a ↦ mulX k n a` (multiplication by `x_a`) and `ψ k n j ↦ dd k n j` (the divided
difference `∂_j`), for every `n`. -/
def endEquiv (n : ℕ) : End ((pres k).obj (strands n)) ≃ₐ[k] nilHecke k n :=
  (AlgEquiv.ofBijective (fromNH k n) ⟨fromNH_injective k n, fromNH_surjective k n⟩).symm

@[simp] theorem endEquiv_symm_apply (n : ℕ) (a : nilHecke k n) :
    (endEquiv k n).symm a = fromNH k n a := rfl

theorem endEquiv_x {n i : ℕ} (h : i < n) :
    endEquiv k n (x k n i) = ⟨mulX k n ⟨i, h⟩, mulX_mem _⟩ := by
  rw [← AlgEquiv.eq_symm_apply, endEquiv_symm_apply, fromNH_mulX]

theorem endEquiv_ψ (n j : ℕ) : endEquiv k n (ψ k n j) = ⟨dd k n j, dd_mem j⟩ := by
  rw [← AlgEquiv.eq_symm_apply, endEquiv_symm_apply, fromNH_dd]

/-- On polynomials in the first `n` variables, an endomorphism of `n` strands acts through the
polynomial representation as its image in `NH_n` does. -/
theorem rename_comp_endEquiv (n : ℕ) (f : End ((pres k).obj (strands n))) :
    ιPoly k n ∘ₗ (endEquiv k n f : Module.End k _) = realize k n f ∘ₗ ιPoly k n := by
  conv_rhs => rw [← (endEquiv k n).symm_apply_apply f, endEquiv_symm_apply]
  rw [realize_fromNH_comp_rename]

/-- **Faithfulness** of the polynomial representation of the diagrammatic nilHecke category on
`n` strands. -/
theorem realize_injective (n : ℕ) : Function.Injective (realize k n) := by
  intro f g h
  apply (endEquiv k n).injective
  refine Subtype.ext (LinearMap.ext fun p => ιPoly_injective k n ?_)
  have := LinearMap.congr_fun ((rename_comp_endEquiv k n f).trans
    ((congrArg (· ∘ₗ ιPoly k n) h).trans (rename_comp_endEquiv k n g).symm)) p
  simpa using this

/-! ## Polynomials and words -/

/-- `NH_n`-polynomials go to polynomials in the dots. -/
theorem fromNH_mulPoly (n : ℕ) (p : MvPolynomial (Fin n) k) :
    fromNH k n ⟨mulPoly k n p, mulPoly_mem p⟩ = dots k n (rename Fin.val p) := by
  have : (fromNH k n).comp ((mulPoly k n).codRestrict (nilHecke k n) mulPoly_mem) =
      (dots k n).comp (rename Fin.val) :=
    MvPolynomial.algHom_ext fun a => by
      simp only [AlgHom.comp_apply, rename_X, dots_X]
      exact fromNH_mulX k n a
  exact DFunLike.congr_fun this p

theorem endEquiv_dots (n : ℕ) (p : MvPolynomial (Fin n) k) :
    endEquiv k n (dots k n (rename Fin.val p)) = ⟨mulPoly k n p, mulPoly_mem p⟩ := by
  rw [← AlgEquiv.eq_symm_apply, endEquiv_symm_apply, fromNH_mulPoly]

variable {k} in
/-- The crossings along a word: `ψ_ρ = ψ_{ρ₀} ψ_{ρ₁} ⋯`. -/
def ψw (n : ℕ) (ρ : List ℕ) : End ((pres k).obj (strands n)) := (ρ.map (ψ k n)).prod

theorem fromNH_ddw (n : ℕ) (ρ : List ℕ) :
    fromNH k n ⟨ddw ρ, ddw_mem ρ⟩ = ψw n ρ := by
  induction ρ with
  | nil => exact map_one _
  | cons j ρ ih =>
    have e : (⟨ddw (j :: ρ), ddw_mem _⟩ : nilHecke k n) = ⟨dd k n j, dd_mem j⟩ * ⟨ddw ρ, ddw_mem ρ⟩ :=
      Subtype.ext (ddw_cons j ρ)
    rw [e, map_mul, fromNH_dd, ih, ψw, ψw, List.map_cons, List.prod_cons]

theorem endEquiv_ψw (n : ℕ) (ρ : List ℕ) : endEquiv k n (ψw n ρ) = ⟨ddw ρ, ddw_mem ρ⟩ := by
  rw [← AlgEquiv.eq_symm_apply, endEquiv_symm_apply, fromNH_ddw]

/-! ## The basis -/

/-- **KL I, Theorem 2.5 for `ν = n i`, diagrammatically**: for any choice `ρ` of reduced words,
`{ψ_{ρ w} x^u}` (`w ∈ S_n`, `u ∈ ℕ^n`; crossings above dots) is a `k`-basis of the endomorphism
ring of `n` strands in the diagrammatic nilHecke category. -/
def basis (n : ℕ) (ρ : Perm (Fin n) → List ℕ)
    (hρ : ∀ w, IsReduced n (ρ w) ∧ wordProd n (ρ w) = w) :
    Basis (Perm (Fin n) × (Fin n →₀ ℕ)) k (End ((pres k).obj (strands n))) :=
  (KLR.NilHecke.basis n ρ hρ).map (endEquiv k n).symm.toLinearEquiv

theorem basis_apply (n : ℕ) (ρ : Perm (Fin n) → List ℕ)
    (hρ : ∀ w, IsReduced n (ρ w) ∧ wordProd n (ρ w) = w) (b : Perm (Fin n) × (Fin n →₀ ℕ)) :
    basis k n ρ hρ b = ψw n (ρ b.1) * dots k n (rename Fin.val (monomial b.2 1)) := by
  have e : KLR.NilHecke.basis (k := k) n ρ hρ b =
      ⟨ddw (ρ b.1), ddw_mem _⟩ * ⟨mulPoly k n (monomial b.2 1), mulPoly_mem _⟩ :=
    Subtype.ext (KLR.NilHecke.basis_apply n ρ hρ b)
  rw [basis, Basis.map_apply, AlgEquiv.toLinearEquiv_apply, e, map_mul, endEquiv_symm_apply,
    endEquiv_symm_apply, fromNH_ddw, fromNH_mulPoly]

end Categorification.NilHecke.Diagram

end
