/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.DividedDifference
import Categorification.Diagrams.NilHecke.Relations
import StringDiagrams.Tactic.WordRw

/-!
# Polynomials in the dots and the polynomial slide

The dots `x k n i` on the strands of `n` pairwise commute, so polynomials can be placed on the
strands: `dots k n : MvPolynomial ℕ k →ₐ[k] End ((pres k).obj (strands n))` sends `X i` to the
dot on strand `i` (and to `0` if `i ≥ n`). Sliding a polynomial through a crossing produces the
divided difference: for all widths `n`, all positions `i` with `i + 1 < n`, and all polynomials
`f`,

* `ψ_mul_dots`: `ψ_i · f = (s_i f) · ψ_i + ∂_i f`;
* `dots_mul_ψ`: `f · ψ_i = ψ_i · (s_i f) + ∂_i f`,

where `s_i f = rename (swap i (i + 1)) f` exchanges `X i` and `X (i + 1)` and
`∂_i = Categorification.ddiff i (i + 1)` is the divided difference operator of
`Categorification.Algebra.DividedDifference`. Products are composition of operators (`f * g`
is `g` followed by `f`, i.e. `g` drawn below `f`). This is the diagrammatic form of the
nilHecke action on polynomials (KL I, arXiv:0803.4121v2, §2.2, Example 3; indices shifted to
start at `0`). For `f = X i` and `f = X (i + 1)` these are the dot slide relations
`ψ_mul_x_sub_x_mul_ψ` and `x_mul_ψ_sub_ψ_mul_x`. The proof is a diagrammatic computation from
the defining relations, valid over any commutative ring.

## Main declarations

* `dots k n`, `dots_X`, `dots_C`, `dots_mul_comm`.
* `ψ_mul_dots_X`: the generator case.
* `ψ_mul_dots`, `dots_mul_ψ`: the polynomial slide in both directions.
* `ψ_mul_dots_of_rename_eq`: `s_i`-invariant polynomials commute with `ψ_i`.
* `ψ_mul_dots_mul_ψ`, `ψ_mul_dots_mul_ψ'`: `ψ_i f ψ_i = (∂_i f) ψ_i = ψ_i (∂_i f)`.
-/

noncomputable section

namespace Categorification.NilHecke.Diagram

open CategoryTheory StringDiagrams MvPolynomial Equiv

variable (k : Type*) [CommRing k]

/-! ### Polynomials in the dots -/

/-- The subalgebra of `End ((pres k).obj (strands n))` generated by the dots. -/
abbrev dotAlg (n : ℕ) : Subalgebra k (End ((pres k).obj (strands n))) :=
  Algebra.adjoin k (Set.range (x k n))

/-- The dots commute, so they generate a commutative subalgebra. -/
instance dotAlg.instCommRing (n : ℕ) : CommRing (dotAlg k n) :=
  Algebra.adjoinCommRingOfComm k (by
    rintro _ ⟨i, rfl⟩ _ ⟨j, rfl⟩
    exact x_mul_x_comm k n i j)

/-- Polynomials in the dots: `X i` is sent to the dot `x k n i` on strand `i`. -/
def dots (n : ℕ) : MvPolynomial ℕ k →ₐ[k] End ((pres k).obj (strands n)) :=
  (dotAlg k n).val.comp
    (aeval fun i => (⟨x k n i, Algebra.subset_adjoin ⟨i, rfl⟩⟩ : dotAlg k n))

@[simp] theorem dots_X (n i : ℕ) : dots k n (X i) = x k n i := by
  simp [dots]

@[simp] theorem dots_C (n : ℕ) (r : k) : dots k n (C r) = algebraMap k _ r :=
  (dots k n).commutes r

theorem dots_mul_comm (n : ℕ) (f g : MvPolynomial ℕ k) :
    dots k n f * dots k n g = dots k n g * dots k n f := by
  rw [← map_mul, mul_comm, map_mul]

/-! ### The generator cases -/

private theorem succ_ne (i : ℕ) : i ≠ i + 1 := by omega

theorem ψ_mul_x_self {n i : ℕ} (h : i + 1 < n) :
    ψ k n i * x k n i = x k n (i + 1) * ψ k n i + 1 :=
  sub_eq_iff_eq_add'.mp (ψ_mul_x_sub_x_mul_ψ k h)

theorem ψ_mul_x_succ {n i : ℕ} (h : i + 1 < n) :
    ψ k n i * x k n (i + 1) = x k n i * ψ k n i - 1 := by
  rw [← x_mul_ψ_sub_ψ_mul_x k h, sub_sub_cancel]

theorem ψ_mul_x_of_ne {n i j : ℕ} (h : j ≠ i) (h' : j ≠ i + 1) :
    ψ k n i * x k n j = x k n j * ψ k n i :=
  (x_mul_ψ_comm k h h').symm

/-- The polynomial slide for a single variable. -/
theorem ψ_mul_dots_X {n i : ℕ} (h : i + 1 < n) (j : ℕ) :
    ψ k n i * x k n j =
      dots k n (rename (swap i (i + 1)) (X j)) * ψ k n i +
        dots k n (ddiff i (i + 1) (X j)) := by
  rcases (show j = i ∨ j = i + 1 ∨ (j ≠ i ∧ j ≠ i + 1) by omega) with rfl | rfl | ⟨h₁, h₂⟩
  · simp [ψ_mul_x_self k h, ddiff_X_left (succ_ne j)]
  · simp [ψ_mul_x_succ k h, ddiff_X_right (succ_ne i), sub_eq_add_neg]
  · simp [swap_apply_of_ne_of_ne h₁ h₂, ddiff_X_of_ne (succ_ne i) h₁ h₂, ψ_mul_x_of_ne k h₁ h₂]

/-! ### The polynomial slide -/

/-- Sliding a polynomial up through a crossing: `ψ_i f = (s_i f) ψ_i + ∂_i f`. -/
theorem ψ_mul_dots {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ k) :
    ψ k n i * dots k n f =
      dots k n (rename (swap i (i + 1)) f) * ψ k n i + dots k n (ddiff i (i + 1) f) := by
  induction f using MvPolynomial.induction_on with
  | C r =>
    rw [rename_C, ddiff_C (succ_ne i), map_zero, add_zero, dots_C, Algebra.commutes]
  | add p q hp hq =>
    simp only [map_add, mul_add, add_mul, hp, hq]
    abel
  | mul_X p j hp =>
    simp only [map_mul, ddiff_mul (succ_ne i), map_add, dots_X]
    word_rw [hp, ψ_mul_dots_X k h j]
    abel

/-- Sliding a polynomial down through a crossing: `f ψ_i = ψ_i (s_i f) + ∂_i f`. -/
theorem dots_mul_ψ {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ k) :
    dots k n f * ψ k n i =
      ψ k n i * dots k n (rename (swap i (i + 1)) f) + dots k n (ddiff i (i + 1) f) := by
  rw [ψ_mul_dots k h, rename_swap_rename_swap, ddiff_rename_swap (succ_ne i), map_neg]
  abel

/-- Polynomials invariant under `s_i` commute with the crossing `ψ_i`. -/
theorem ψ_mul_dots_of_rename_eq {n i : ℕ} (h : i + 1 < n) {f : MvPolynomial ℕ k}
    (hf : rename (swap i (i + 1)) f = f) : ψ k n i * dots k n f = dots k n f * ψ k n i := by
  rw [ψ_mul_dots k h, hf, ddiff_eq_zero_of_rename_eq (succ_ne i) hf, map_zero, add_zero]

/-- `ψ_i f ψ_i = (∂_i f) ψ_i`. -/
theorem ψ_mul_dots_mul_ψ {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ k) :
    ψ k n i * dots k n f * ψ k n i = dots k n (ddiff i (i + 1) f) * ψ k n i := by
  word_rw [ψ_mul_dots k h, ψ_mul_ψ]

/-- `ψ_i f ψ_i = ψ_i (∂_i f)`. -/
theorem ψ_mul_dots_mul_ψ' {n i : ℕ} (h : i + 1 < n) (f : MvPolynomial ℕ k) :
    ψ k n i * dots k n f * ψ k n i = ψ k n i * dots k n (ddiff i (i + 1) f) := by
  word_rw [dots_mul_ψ k h, ψ_mul_ψ]

end Categorification.NilHecke.Diagram

end
