/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.TwoRep.QIntField
import Categorification.TwoRep.WordBounded
import Mathlib.Algebra.Polynomial.Laurent
import Mathlib.Algebra.Module.LocalizedModule.Basic
import Mathlib.RingTheory.Localization.Basic

/-!
# Two-sided integer sequences, quantum-integer torsion, and positivity

Linear algebra for removing the boundedness hypothesis (BB_w) from S. Cautis, A. D. Lauda,
*Implicit structure in 2-representations of quantum groups*, arXiv:1111.1431v3, §3
(Proposition 3.9 `prop:lradj`).

The graded dimensions `d ↦ dim Hom(X, Z⟨d⟩)` of a pair of 1-morphisms form a two-sided sequence;
in general nothing bounds them below. Instead of Laurent series we use the module `Seq = (ℤ → ℚ)`
over the ring `R₀ = ℚ[T, T⁻¹]` of Laurent polynomials, `T` acting by the shift
`(T • s) d = s (d - 1)`.

* `qi0 m ∈ R₀` is the quantum integer `[m] = T^{m-1} + T^{m-3} + ⋯ + T^{1-m}` (`[-m] = -[m]`);
  `ev : R₀ →+* ℚ((q))` is injective and sends `qi0 m` to `qIntZ qL m`
  (`ev_injective`, `ev_qi0`), which transports the `q`-integer identities of `QIntField.lean`.
* `qS` is the submonoid generated by the `[n]`, `n ≥ 1`; `Rq = R₀[qS⁻¹]` (`Localization`) is a ring
  in which every `[m]`, `m ≠ 0`, is a unit (`isUnit_qiR`), and `MSeq = Seq[qS⁻¹]` (`LocalizedModule`).
  A sequence maps to zero in `MSeq` iff it is killed by an element of `qS` (`exists_smul_eq_zero`).
* **Positivity (`eq_zero_of_smul_eq_zero`)**: the elements of `qS` are nonzero Laurent polynomials
  with nonnegative coefficients; so if `f • s = 0` with `f ∈ qS` and `s` is nonnegative on a
  half-line `d ≤ d₀`, then `s = 0`.
-/

noncomputable section

namespace Categorification.TwoRep.Tors

open LaurentPolynomial Finset

/-- The ring `ℚ[T, T⁻¹]`. -/
abbrev R₀ := LaurentPolynomial ℚ

/-! ## Quantum integers in `ℚ[T, T⁻¹]` -/

/-- `[n] = ∑_{j<n} T^{n-1-2j}` for `n : ℕ`. -/
def qiN (n : ℕ) : R₀ := ∑ j ∈ range n, T ((n : ℤ) - 1 - 2 * (j : ℤ))

/-- The quantum integer `[m]`, `m ∈ ℤ`, with `[-m] = -[m]`. -/
def qi0 (m : ℤ) : R₀ := if 0 ≤ m then qiN m.toNat else -qiN (-m).toNat

theorem qi0_natCast (n : ℕ) : qi0 n = qiN n := by simp [qi0]

theorem qi0_neg (m : ℤ) : qi0 (-m) = -qi0 m := by
  rcases lt_trichotomy m 0 with h | rfl | h
  · simp only [qi0, show ¬ 0 ≤ m by omega, show 0 ≤ -m by omega, ite_true, ite_false, neg_neg]
  · simp [qi0, qiN]
  · simp only [qi0, show 0 ≤ m by omega, show ¬ 0 ≤ -m by omega, ite_true, ite_false, neg_neg]

/-- The reflected sum: `∑_{j<n} T^{-(n-1-2j)} = [n]`. -/
theorem qiN_reflect (n : ℕ) : ∑ j ∈ range n, (T (-((n : ℤ) - 1 - 2 * (j : ℤ))) : R₀) = qiN n := by
  rw [qiN, ← sum_range_reflect]
  refine sum_congr rfl fun j hj => ?_
  rw [mem_range] at hj
  congr 1
  rw [Nat.cast_sub (by omega), Nat.cast_sub (by omega)]
  push_cast; ring

/-! ## The embedding into `ℚ((q))` -/

/-- `q` as a unit of `ℚ((q))`. -/
def qU : LSerˣ := Units.mk0 qL isGenericParam_q.ne_zero

/-- Evaluation `T ↦ q`, `ℚ[T, T⁻¹] → ℚ((q))`. -/
def ev : R₀ →+* LSer := LaurentPolynomial.eval₂ HahnSeries.C qU

theorem ev_T (n : ℤ) : ev (T n) = qL ^ n := by
  rw [ev, eval₂_T, Units.val_zpow_eq_zpow_val]; rfl

theorem coeff_ev (f : R₀) (d : ℤ) : (ev f).coeff d = f.coeff d := by
  induction f using AddMonoidAlgebra.induction_linear with
  | zero => simp
  | add f g hf hg => rw [map_add, HahnSeries.coeff_add, hf, hg]; rfl
  | single n c =>
    have hC : ev (C c) = HahnSeries.C c := eval₂_C _ _ c
    rw [show (AddMonoidAlgebra.single n c : R₀) = C c * T n from single_eq_C_mul_T c n, map_mul,
      hC, ev_T, qL_zpow, HahnSeries.C_apply, HahnSeries.single_mul_single, zero_add, mul_one,
      ← single_eq_C_mul_T, AddMonoidAlgebra.coeff_single, Finsupp.single_apply]
    by_cases h : n = d
    · subst h; simp
    · rw [HahnSeries.coeff_single_of_ne (Ne.symm h)]; simp [h]

theorem ev_injective : Function.Injective ev := by
  intro f g h
  ext d
  rw [← coeff_ev f d, ← coeff_ev g d, h]

theorem ev_qiN (n : ℕ) : ev (qiN n) = qIntZ qL n := by
  rw [qiN, map_sum, ← sum_zpow_eq_qIntZ isGenericParam_q n]
  exact sum_congr rfl fun j _ => ev_T _

theorem ev_qi0 (m : ℤ) : ev (qi0 m) = qIntZ qL m := by
  rcases le_or_gt 0 m with h | h
  · simp only [qi0, h, ↓reduceIte]; rw [ev_qiN, Int.toNat_of_nonneg h]
  · simp only [qi0, show ¬ (0 ≤ m) by omega, ↓reduceIte]
    rw [map_neg, ev_qiN, Int.toNat_of_nonneg (by omega), qIntZ_neg,
      neg_neg]

/-- `[a + 1][b + 1] - [a][b] = [a + b + 1]` for a generic parameter. -/
theorem qIntZ_add_one_mul {K : Type*} [Field K] {q : K} (hq : IsGenericParam q) (a b : ℤ) :
    qIntZ q (a + 1) * qIntZ q (b + 1) - qIntZ q a * qIntZ q b = qIntZ q (a + b + 1) := by
  have hq0 := hq.ne_zero
  have hd := hq.sub_inv_ne_zero
  simp only [qIntZ]
  rw [div_mul_div_comm, div_mul_div_comm, ← sub_div, div_eq_div_iff (mul_ne_zero hd hd) hd]
  simp only [zpow_add₀ hq0, zpow_neg, zpow_one, neg_add]
  have ha : q ^ a ≠ 0 := zpow_ne_zero _ hq0
  have hb : q ^ b ≠ 0 := zpow_ne_zero _ hq0
  field_simp
  ring

/-- **`∑_{i<n} [μ + 2i] = [n][μ + n - 1]`** in `ℚ[T, T⁻¹]`. -/
theorem sum_qi0 (μ : ℤ) (n : ℕ) :
    ∑ i ∈ range n, qi0 (μ + 2 * i) = qi0 n * qi0 (μ + n - 1) := by
  apply ev_injective
  rw [map_sum, map_mul, ev_qi0, ev_qi0]
  simp only [ev_qi0]
  induction n with
  | zero => simp [qIntZ]
  | succ n ih =>
    rw [sum_range_succ, ih]
    have := qIntZ_add_one_mul isGenericParam_q (n : ℤ) (μ + n - 1)
    rw [show (n : ℤ) + (μ + n - 1) + 1 = μ + 2 * n by ring] at this
    push_cast
    rw [show μ + ((n : ℤ) + 1) - 1 = μ + n - 1 + 1 by ring]
    linear_combination -this

theorem qi0_ne_zero {m : ℤ} (hm : m ≠ 0) : qi0 m ≠ 0 := by
  intro h
  apply qIntZ_ne_zero isGenericParam_q hm
  rw [← ev_qi0, h, map_zero]

/-! ## The localization -/

/-- The submonoid of `ℚ[T, T⁻¹]` generated by the quantum integers `[n]`, `n ≥ 1`. -/
def qS : Submonoid R₀ := Submonoid.closure (Set.range fun n : ℕ => qi0 (n + 1))

/-- `ℚ[T, T⁻¹]` with all quantum integers inverted. (A type synonym of `Localization qS`
carrying only the instances below, so that every semiring structure on it comes from
`CommRing`.) -/
def Rq : Type := Localization qS

instance : CommRing Rq := inferInstanceAs (CommRing (Localization qS))
instance : Algebra R₀ Rq := inferInstanceAs (Algebra R₀ (Localization qS))
instance : IsLocalization qS Rq := inferInstanceAs (IsLocalization qS (Localization qS))

/-- The image of `[m]` in `Rq`. -/
def qiR (m : ℤ) : Rq := algebraMap R₀ Rq (qi0 m)

theorem qi0_mem_qS {m : ℤ} (hm : 0 < m) : qi0 m ∈ qS := by
  refine Submonoid.subset_closure ⟨(m - 1).toNat, ?_⟩
  simp only
  congr 1; omega

theorem isUnit_qiR {m : ℤ} (hm : m ≠ 0) : IsUnit (qiR m) := by
  rcases lt_or_gt_of_ne hm with h | h
  · rw [qiR, show m = -(-m) by ring, qi0_neg, map_neg]
    exact (IsLocalization.map_units Rq (⟨qi0 (-m), qi0_mem_qS (by omega)⟩ : qS)).neg
  · exact IsLocalization.map_units Rq (⟨qi0 m, qi0_mem_qS h⟩ : qS)

theorem qiR_neg (m : ℤ) : qiR (-m) = -qiR m := by rw [qiR, qi0_neg, map_neg]; rfl

theorem sum_qiR (μ : ℤ) (n : ℕ) :
    ∑ i ∈ range n, qiR (μ + 2 * i) = qiR n * qiR (μ + n - 1) := by
  simp only [qiR, ← map_sum, ← map_mul, sum_qi0]

/-! ## Nonnegative coefficients -/

/-- All coefficients are `≥ 0`. -/
def Nonneg (f : R₀) : Prop := ∀ n, 0 ≤ f.coeff n

theorem nonneg_T (n : ℤ) : Nonneg (T n) := by
  intro d
  rw [T, AddMonoidAlgebra.coeff_single, Finsupp.single_apply]
  split_ifs <;> norm_num

theorem Nonneg.add {f g : R₀} (hf : Nonneg f) (hg : Nonneg g) : Nonneg (f + g) := fun n => by
  rw [AddMonoidAlgebra.coeff_add, Finsupp.add_apply]; exact add_nonneg (hf n) (hg n)

theorem Nonneg.mul {f g : R₀} (hf : Nonneg f) (hg : Nonneg g) : Nonneg (f * g) := fun n => by
  classical
  rw [AddMonoidAlgebra.coeff_mul]
  unfold Finsupp.sum
  refine Finset.sum_nonneg fun a _ => Finset.sum_nonneg fun b _ => ?_
  dsimp only
  split_ifs
  · exact mul_nonneg (hf a) (hg b)
  · exact le_rfl

theorem nonneg_qiN (n : ℕ) : Nonneg (qiN n) := by
  rw [qiN]
  induction (range n) using Finset.induction_on with
  | empty => intro d; simp
  | insert a s ha ih => rw [sum_insert ha]; exact (nonneg_T _).add ih

theorem nonneg_of_mem_qS {f : R₀} (hf : f ∈ qS) : Nonneg f ∧ f ≠ 0 := by
  induction hf using Submonoid.closure_induction with
  | mem f hf =>
    obtain ⟨n, rfl⟩ := hf
    show Nonneg (qi0 ((n : ℤ) + 1)) ∧ qi0 ((n : ℤ) + 1) ≠ 0
    refine ⟨?_, qi0_ne_zero (by omega)⟩
    have := qi0_natCast (n + 1)
    push_cast at this
    rw [this]; exact nonneg_qiN _
  | one => exact ⟨fun d => by rw [← T_zero, ]; exact nonneg_T 0 d, one_ne_zero⟩
  | mul f g _ _ hf hg => exact ⟨hf.1.mul hg.1, mul_ne_zero hf.2 hg.2⟩

/-! ## Two-sided sequences -/

/-- Two-sided rational sequences. -/
def Seq := ℤ → ℚ

instance : AddCommGroup Seq := inferInstanceAs (AddCommGroup (ℤ → ℚ))
instance : Module ℚ Seq := inferInstanceAs (Module ℚ (ℤ → ℚ))

theorem seq_sum_apply {ι : Type*} (t : Finset ι) (g : ι → Seq) (d : ℤ) :
    (∑ i ∈ t, g i) d = ∑ i ∈ t, g i d := by
  classical
  induction t using Finset.induction_on with
  | empty => rfl
  | insert a t ha ih => rw [sum_insert ha, sum_insert ha, ← ih]; rfl

/-- The shift `(sh n s) d = s (d - n)`. -/
def sh (n : ℤ) : Module.End ℚ Seq where
  toFun s d := s (d - n)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The shifts as a monoid homomorphism. -/
def shHom : Multiplicative ℤ →* Module.End ℚ Seq where
  toFun n := sh n.toAdd
  map_one' := by
    apply LinearMap.ext; intro s; funext d
    show s (d - 0) = s d
    rw [sub_zero]
  map_mul' a b := by
    apply LinearMap.ext; intro s; funext d
    change s (d - Multiplicative.toAdd (a * b)) =
      s (d - Multiplicative.toAdd a - Multiplicative.toAdd b)
    rw [toAdd_mul]; congr 1; ring

/-- The action of `ℚ[T, T⁻¹]` on sequences. -/
def act : R₀ →ₐ[ℚ] Module.End ℚ Seq := AddMonoidAlgebra.lift ℚ (Module.End ℚ Seq) ℤ shHom

instance : Module R₀ Seq := Module.compHom Seq act.toRingHom

theorem smul_def (f : R₀) (s : Seq) : f • s = act f s := rfl

theorem smul_apply (f : R₀) (s : Seq) (d : ℤ) :
    (f • s) d = f.coeff.sum fun n c => c * s (d - n) := by
  rw [smul_def, act, AddMonoidAlgebra.lift_apply, Finsupp.sum, LinearMap.sum_apply, Finsupp.sum]
  rw [seq_sum_apply]
  rfl

theorem T_smul_apply (n : ℤ) (s : Seq) (d : ℤ) : ((T n : R₀) • s) d = s (d - n) := by
  rw [smul_apply, T, AddMonoidAlgebra.coeff_single, Finsupp.sum_single_index (by simp), one_mul]

/-! ## Positivity -/

/-- **Positivity**: a sequence killed by a nonzero Laurent polynomial with nonnegative coefficients
and nonnegative on a half-line `d ≤ d₀` is zero. -/
theorem eq_zero_of_smul_eq_zero_of_nonneg {f : R₀} (hf : Nonneg f) (hf0 : f ≠ 0) {s : Seq}
    (hs : f • s = 0) {d₀ : ℤ} (hpos : ∀ d, d ≤ d₀ → 0 ≤ s d) : s = 0 := by
  have hsupp : f.coeff.support.Nonempty := by
    rw [Finsupp.support_nonempty_iff]
    intro h; apply hf0; ext n; rw [h]; rfl
  set i₀ := f.coeff.support.min' hsupp with hi₀
  have hi₀mem : i₀ ∈ f.coeff.support := Finset.min'_mem _ _
  have hle : ∀ n ∈ f.coeff.support, i₀ ≤ n := fun n hn => Finset.min'_le _ _ hn
  have hfi₀ : f.coeff i₀ ≠ 0 := Finsupp.mem_support_iff.1 hi₀mem
  have heq : ∀ d, ∑ n ∈ f.coeff.support, f.coeff n * s (d - n) = 0 := by
    intro d
    have := congrFun hs d
    rw [smul_apply, Finsupp.sum] at this
    exact this
  -- vanishing on the half-line
  have h1 : ∀ e, e ≤ d₀ → s e = 0 := by
    intro e he
    have hterm := (Finset.sum_eq_zero_iff_of_nonneg (fun n hn =>
      mul_nonneg (hf n) (hpos _ (by have := hle n hn; omega)))).1 (heq (e + i₀)) i₀ hi₀mem
    rw [show e + i₀ - i₀ = e by ring] at hterm
    exact (mul_eq_zero.1 hterm).resolve_left hfi₀
  -- upward induction
  have h2 : ∀ k : ℕ, ∀ e, e ≤ d₀ + k → s e = 0 := by
    intro k
    induction k with
    | zero => intro e he; exact h1 e (by simpa using he)
    | succ k ih =>
      intro e he
      by_cases he' : e ≤ d₀ + k
      · exact ih e he'
      have h := heq (e + i₀)
      rw [Finset.sum_eq_single i₀ (fun n hn hne => by
        rw [ih _ (by have := hle n hn; have : i₀ ≠ n := Ne.symm hne; push_cast at he ⊢; omega),
          mul_zero]) (fun h => absurd hi₀mem h), show e + i₀ - i₀ = e by ring] at h
      exact (mul_eq_zero.1 h).resolve_left hfi₀
  funext e
  exact h2 (e - d₀).toNat e (by omega)

/-! ## The localized sequences -/

/-- Sequences with all quantum integers inverted. -/
abbrev MSeq := LocalizedModule qS Seq

instance : Module Rq MSeq := inferInstanceAs (Module (Localization qS) (LocalizedModule qS Seq))
instance : IsScalarTower R₀ Rq MSeq :=
  inferInstanceAs (IsScalarTower R₀ (Localization qS) (LocalizedModule qS Seq))

/-- The localization map `Seq → MSeq`. -/
abbrev toM : Seq →ₗ[R₀] MSeq := LocalizedModule.mkLinearMap qS Seq

/-- A sequence maps to zero in `MSeq` iff it is killed by an element of `qS`. -/
theorem exists_smul_eq_zero {s : Seq} (h : toM s = 0) : ∃ f ∈ qS, f • s = 0 := by
  have h' : toM s = toM 0 := by rw [h, map_zero]
  obtain ⟨c, hc⟩ := IsLocalizedModule.exists_of_eq (S := qS) (f := toM) h'
  exact ⟨c, c.2, by rw [← Submonoid.smul_def]; simpa using hc⟩

/-- **Positivity for torsion**: a sequence that maps to zero in `MSeq` and is nonnegative on a
half-line `d ≤ d₀` is zero. -/
theorem eq_zero_of_toM_eq_zero {s : Seq} (h : toM s = 0) {d₀ : ℤ} (hpos : ∀ d, d ≤ d₀ → 0 ≤ s d) :
    s = 0 := by
  obtain ⟨f, hf, hfs⟩ := exists_smul_eq_zero h
  exact eq_zero_of_smul_eq_zero_of_nonneg (nonneg_of_mem_qS hf).1 (nonneg_of_mem_qS hf).2 hfs hpos

end Categorification.TwoRep.Tors
