import Categorification.Algebra.AugmentationQuotient
import Categorification.Algebra.BalancedTensor
import Categorification.Algebra.CoactionGrading
import Categorification.Algebra.Coinvariant
import Categorification.Algebra.CoinvariantGraded
import Categorification.Algebra.DividedDifference
import Categorification.Algebra.ExternalTensor
import Categorification.Algebra.Graded.Dimension
import Categorification.Algebra.Graded.Duality
import Categorification.Algebra.Graded.G0
import Categorification.Algebra.Graded.G0Basis
import Categorification.Algebra.Graded.GeomSeries
import Categorification.Algebra.Graded.HomForm
import Categorification.Algebra.Graded.HomogeneousBasis
import Categorification.Algebra.Graded.Idempotent
import Categorification.Algebra.Graded.IdempotentSplitting
import Categorification.Algebra.Graded.IdempotentSplittingK0
import Categorification.Algebra.Graded.K0
import Categorification.Algebra.Graded.KrullSchmidt
import Categorification.Algebra.Graded.KrullSchmidtUnique
import Categorification.Algebra.Graded.Module
import Categorification.Algebra.Graded.ProjectiveCover
import Categorification.Algebra.Graded.Quotient
import Categorification.Algebra.Graded.Simple
import Categorification.Algebra.Graded.Tensor
import Categorification.Algebra.Graded.TensorGdim
import Categorification.Algebra.IdempotentEquiv
import Categorification.Algebra.NilHecke
import Categorification.Algebra.NilHeckeIdempotent
import Categorification.Algebra.NilHeckeKato
import Categorification.Algebra.NilHeckeParabolic
import Categorification.Algebra.NilHeckeSimple
import Categorification.Algebra.NilHeckeSplitting
import Categorification.Algebra.ParabolicSymmetricFree
import Categorification.Algebra.PermExpansion
import Categorification.Algebra.SymmetricFree
import Categorification.Diagrams.KL3.Basic
import Categorification.Diagrams.KL3.BubbleSlides
import Categorification.Diagrams.KL3.BubbleSlidesAll
import Categorification.Diagrams.KL3.BubbleSlidesEq
import Categorification.Diagrams.KL3.BubbleSlidesProp
import Categorification.Diagrams.KL3.Bubbles
import Categorification.Diagrams.KL3.Cyclic
import Categorification.Diagrams.KL3.Grading
import Categorification.Diagrams.KL3.Grassmannian
import Categorification.Diagrams.KL3.MixedR3
import Categorification.Diagrams.KL3.MixedR3Sl2
import Categorification.Diagrams.KL3.MoreBubbleSlides
import Categorification.Diagrams.KL3.NestedCups
import Categorification.Diagrams.KL3.Pitchfork
import Categorification.Diagrams.KL3.Presentation
import Categorification.Diagrams.KL3.Relations
import Categorification.Diagrams.KL3.Rewriting
import Categorification.Diagrams.KL3.SlideCalculus
import Categorification.Diagrams.KL3.Upward
import Categorification.Diagrams.KLR.Basic
import Categorification.Diagrams.KLR.Comparison
import Categorification.Diagrams.KLR.DiagR
import Categorification.Diagrams.KLR.KL1
import Categorification.Diagrams.KLR.MatEnd
import Categorification.Diagrams.KLR.Soundness
import Categorification.Diagrams.NilHecke.Basic
import Categorification.Diagrams.NilHecke.Comparison
import Categorification.Diagrams.NilHecke.Dots
import Categorification.Diagrams.NilHecke.LongestElement
import Categorification.Diagrams.NilHecke.PolyRep
import Categorification.Diagrams.NilHecke.Relations
import Categorification.KLR.BarDivided
import Categorification.KLR.BarGamma
import Categorification.KLR.BarK0
import Categorification.KLR.Basic
import Categorification.KLR.BasisTheorem
import Categorification.KLR.Center
import Categorification.KLR.CenterFree
import Categorification.KLR.Concat
import Categorification.KLR.ConcatAssoc
import Categorification.KLR.Cor215
import Categorification.KLR.Cor319
import Categorification.KLR.Crystal.Cor312
import Categorification.KLR.Crystal.CrystalOps
import Categorification.KLR.Crystal.Delta
import Categorification.KLR.Crystal.GradedBridge
import Categorification.KLR.Crystal.IndDecomp
import Categorification.KLR.Crystal.IndNilpotent
import Categorification.KLR.Crystal.Kleshchev
import Categorification.KLR.Crystal.Lemma39
import Categorification.KLR.Crystal.SimpleTensor
import Categorification.KLR.Crystal.Socle
import Categorification.KLR.Crystal.Thm317
import Categorification.KLR.Crystal.Thm317Graded
import Categorification.KLR.Crystal.Tops
import Categorification.KLR.DividedPowerCharacters
import Categorification.KLR.DividedPowerDecomposition
import Categorification.KLR.DividedPowerIdempotents
import Categorification.KLR.DividedPowerK0
import Categorification.KLR.Examples.Idempotents
import Categorification.KLR.Examples.NilHecke
import Categorification.KLR.Examples.NonInteracting
import Categorification.KLR.Examples.Small
import Categorification.KLR.Examples.TwoStrands
import Categorification.KLR.ExtTensorK0
import Categorification.KLR.Filtration
import Categorification.KLR.Frobenius
import Categorification.KLR.Gamma
import Categorification.KLR.GradedBasis
import Categorification.KLR.GradedFree
import Categorification.KLR.GradedModules
import Categorification.KLR.Grading
import Categorification.KLR.GradingFlip
import Categorification.KLR.Induction
import Categorification.KLR.InductionAlgebra
import Categorification.KLR.InductionFree
import Categorification.KLR.K0Algebra
import Categorification.KLR.K0Free
import Categorification.KLR.KL1
import Categorification.KLR.KL1Basis
import Categorification.KLR.KL2.Datum
import Categorification.KLR.KL2.Gamma2
import Categorification.KLR.KL2.K0Free2
import Categorification.KLR.KL2.K0Relations
import Categorification.KLR.KL2.NilHeckeBlocks
import Categorification.KLR.KL2.NilHeckeFamily
import Categorification.KLR.KL2.OrthSum
import Categorification.KLR.KL2.Prop318KL2
import Categorification.KLR.KL2.Prop320KL2
import Categorification.KLR.KL2.Prop34KL2
import Categorification.KLR.KL2.Serre
import Categorification.KLR.KL2.SerreMaps
import Categorification.KLR.KL2.SerreSeq
import Categorification.KLR.KL2.Theorem8
import Categorification.KLR.Mackey
import Categorification.KLR.MackeyRes
import Categorification.KLR.NilHeckeBlockSplitting
import Categorification.KLR.Pairing
import Categorification.KLR.PolNu
import Categorification.KLR.PolyRep.Defs
import Categorification.KLR.PolyRep.Independence
import Categorification.KLR.PolyRep.Sound
import Categorification.KLR.Prop213
import Categorification.KLR.Prop318
import Categorification.KLR.Prop32
import Categorification.KLR.Prop320
import Categorification.KLR.Prop32Mult
import Categorification.KLR.Prop33
import Categorification.KLR.Prop34
import Categorification.KLR.ResK0
import Categorification.KLR.ResProjGraded
import Categorification.KLR.Restriction
import Categorification.KLR.Simple
import Categorification.KLR.SimpleNilHecke
import Categorification.KLR.Spanning
import Categorification.KLR.SymGdim
import Categorification.KLR.Symmetries
import Categorification.KLR.Theorem11
import Categorification.QuantumGroup.Bar
import Categorification.QuantumGroup.Cartan
import Categorification.QuantumGroup.Coproduct
import Categorification.QuantumGroup.CoproductF
import Categorification.QuantumGroup.CoproductWords
import Categorification.QuantumGroup.DividedPowers
import Categorification.QuantumGroup.Form
import Categorification.QuantumGroup.FormDivided
import Categorification.QuantumGroup.FormWords
import Categorification.QuantumGroup.Grading
import Categorification.QuantumGroup.KLSpecialization
import Categorification.QuantumGroup.PreF
import Categorification.QuantumGroup.QBinomial
import Categorification.QuantumGroup.Radical
import Categorification.QuantumGroup.Serre
import Categorification.QuantumGroup.SerreDivided
import Categorification.QuantumGroup.TwistedMonoidAlgebra
import Categorification.QuantumGroup.UDotAlgebra
import Categorification.QuantumGroup.UDotBlock
import Categorification.QuantumGroup.UDotForm
import Categorification.QuantumGroup.UDotIntegral
import Categorification.QuantumGroup.UDotKL3
import Categorification.QuantumGroup.UDotModel
import Categorification.QuantumGroup.UDotOmega
import Categorification.QuantumGroup.UDotPairing
import Categorification.QuantumGroup.UDotSemilinear
import Categorification.QuantumGroup.UDotSerre
import Categorification.QuantumGroup.UDotSerreF
import Categorification.QuantumGroup.UDotSymm
import Categorification.QuantumGroup.UDotWords
import Categorification.TypeA.Basic
import Categorification.TypeA.DoubleCoset
import Categorification.TypeA.Inversions
import Categorification.TypeA.Length
import Categorification.TypeA.Matsumoto
import Categorification.TypeA.NormalForm
import Categorification.TypeA.Parabolic
/-!
# Categorification

Lean 4 formalizations of results in categorification.
-/
