/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Flag.Esymm
import Categorification.Algebra.Coinvariant

/-!
# The Borel model of the cohomology of partial flag varieties

Let `V` be a finite set of `N` variables and `lab : V → J` a labelling of the variables by
blocks. The *Borel ring* of `lab` is

  `BorelRing k lab = k[V]^{G_lab} / (Sym⁺)`,

the invariants of the Young subgroup `G_lab` of label-preserving permutations modulo the ideal
of `k[V]^{G_lab}` generated by the symmetric polynomials (in all `N` variables) without constant
term. When `V = {1, …, N}` and the blocks are the intervals `(k_{j-1}, k_j]` of a sequence
`0 = k_0 ≤ k_1 ≤ ⋯ ≤ k_n = N`, this is Borel's presentation of `H^*(Fl(k), k)` (KL III,
arXiv:0807.3250v1, §5.1). Its comparison with the generators-and-relations presentation (5.2)
of KL III is `Categorification.Flag.hEquiv` (`Categorification.Flag.Cohomology`).

The Chern classes of the tautological quotient bundles are the classes `xB k lab j α` of the
elementary symmetric polynomials `e_α` of the variables of block `j` (KL III's `x(k)_{j,α}`),
and the *dual generators* `x̄(k)_{j,α}` (KL III eq. (5.5)) are the classes `xbarB k lab j α` of
`e_α` of the variables outside block `j`.

## Main results

* `Flag.BorelRing k lab`, `Flag.borelIdeal k lab`.
* `Flag.borelIdeal_eq_span_esymm` : `Sym⁺` is generated by `e_1, …, e_N` in `k[V]^{G_lab}`.
* `Flag.sum_xB_mul_xbarB` : KL III eq. (5.7), `∑_{f ≤ α} x_{j,f} x̄_{j,α-f} = δ_{α,0}`.
* `Flag.refineHom` : for a refinement `lab'` of `lab`, the map `BorelRing k lab → BorelRing k lab'`
  induced by `k[V]^{G_lab} ⊆ k[V]^{G_lab'}` (pullback along the forgetful map of flag varieties).
* `Flag.borelCongr`, `Flag.borelEquivOfCard` : the Borel ring only depends on the block sizes.
* `Flag.finrank_borelRing` : `dim_k BorelRing k lab · ∏_j (N_j)! = N!` (`N_j` the block sizes),
  i.e. the dimension is the multinomial coefficient `N! / ∏_j N_j!`.

The rank is computed from the parabolic Artin theorem (`exists_labelBasis`: `k[V]` is free of
rank `∏_j N_j!` over `k[V]^{G_lab}`) and `dim_k k[V]/(Sym⁺) = N!` (`finrank_coinv`): tensoring the
free module down gives `k[V]/(Sym⁺) ≅ (k[V]^{G_lab}/(Sym⁺))^{∏_j N_j!}` (`quotLinearEquiv`).
-/

noncomputable section

namespace Categorification.Flag

open MvPolynomial Equiv
open Finset (univ)

section Module

variable {k : Type*} [Field k] {P : Type*} [CommRing P] [Algebra k P]

/-- For `P` free over a subalgebra `A` with basis `b`, `y ∈ J P` iff all coordinates of `y` lie
in `J`. -/
theorem mem_map_val_iff (A : Subalgebra k P) {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Basis ι A P) (J : Ideal A) (y : P) :
    y ∈ J.map A.val ↔ ∀ i, b.equivFun y i ∈ J := by
  constructor
  · intro hy
    refine Submodule.span_induction (p := fun y _ => ∀ i, b.equivFun y i ∈ J) ?_ ?_ ?_ ?_ hy
    · rintro _ ⟨j, hj, rfl⟩ i
      have : A.val j = j • (1 : P) := by rw [Algebra.smul_def, mul_one]; rfl
      rw [this, LinearEquiv.map_smul]
      exact J.mul_mem_right (b.equivFun 1 i) hj
    · simp
    · intro x y _ _ hx hy i
      rw [map_add, Pi.add_apply]
      exact J.add_mem (hx i) (hy i)
    · intro p x _ hx i
      have hx' : p • x = ∑ i', b.equivFun x i' • (p * b i') := by
        conv_lhs => rw [← b.sum_equivFun x]
        rw [smul_eq_mul, Finset.mul_sum]
        refine Finset.sum_congr rfl fun i' _ => ?_
        rw [mul_smul_comm]
      rw [hx', map_sum, Finset.sum_apply]
      refine J.sum_mem fun i' _ => ?_
      rw [LinearEquiv.map_smul]
      exact J.mul_mem_right (b.equivFun (p * b i') i) (hx i')
  · intro h
    rw [← b.sum_equivFun y]
    refine Ideal.sum_mem _ fun i _ => ?_
    rw [Subalgebra.smul_def]
    exact Ideal.mul_mem_right _ _ (Ideal.mem_map_of_mem _ (h i))

/-- For `P` free over a subalgebra `A` with basis indexed by `ι`, `P / J P ≅ (A / J)^ι`. -/
noncomputable def quotLinearEquiv (A : Subalgebra k P) {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Basis ι A P) (J : Ideal A) :
    (P ⧸ (J.map A.val).restrictScalars k) ≃ₗ[k] (ι → A ⧸ J.restrictScalars k) := by
  let e : P ≃ₗ[k] (ι → A) := b.equivFun.restrictScalars k
  have hN : ((J.map A.val).restrictScalars k).map e.toLinearMap =
      Submodule.pi Set.univ (fun _ => J.restrictScalars k) := by
    ext x
    rw [Submodule.mem_map_equiv, Submodule.restrictScalars_mem, mem_map_val_iff A b]
    change (∀ i, b.equivFun (b.equivFun.symm x) i ∈ J) ↔ _
    rw [LinearEquiv.apply_symm_apply]
    simp [Submodule.mem_pi]
  exact (Submodule.Quotient.equiv _ _ e hN).trans (Submodule.quotientPi _)

/-- Variant of `quotLinearEquiv` with `A / J` replaced by any `B` with a surjection `A → B` of
kernel `J`. -/
noncomputable def quotLinearEquiv' (A : Subalgebra k P) {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : Basis ι A P) (J : Ideal A) {B : Type*} [CommRing B] [Algebra k B] (q : A →ₐ[k] B)
    (hq : Function.Surjective q) (hker : RingHom.ker q = J) :
    (P ⧸ (J.map A.val).restrictScalars k) ≃ₗ[k] (ι → B) := by
  have hker' : J.restrictScalars k = LinearMap.ker q.toLinearMap := by
    ext a
    rw [Submodule.restrictScalars_mem, LinearMap.mem_ker, ← hker, RingHom.mem_ker]
    rfl
  exact (quotLinearEquiv A b J).trans (LinearEquiv.piCongrRight fun _ =>
    (Submodule.quotEquivOfEq _ _ hker').trans (q.toLinearMap.quotKerEquivOfSurjective hq))

end Module

variable (k : Type*) [Field k] {V : Type*} {J : Type*}

/-- The symmetric polynomials in all the variables `V` without constant term. -/
def symPlus [Fintype V] : Set (MvPolynomial V k) := {s | s.IsSymmetric ∧ constantCoeff s = 0}

variable {k}

theorem esymm_succ_mem_symPlus [Fintype V] (r : ℕ) : esymm V k (r + 1) ∈ symPlus k :=
  ⟨esymm_isSymmetric _ _ _, by rw [← setEsymm_univ]; exact constantCoeff_setEsymm_succ _ _⟩

theorem mem_labelInvariants_of_isSymmetric (lab : V → J) {s : MvPolynomial V k}
    (hs : s.IsSymmetric) : s ∈ labelInvariants k lab := fun g _ => hs g

/-- A polynomial without constant term in elements without constant term has no constant
term. -/
theorem constantCoeff_aeval_eq_zero {n : ℕ} (f : Fin n → MvPolynomial V k)
    (hf : ∀ i, constantCoeff (f i) = 0) {Q : MvPolynomial (Fin n) k} (hQ : constantCoeff Q = 0) :
    constantCoeff (aeval f Q) = 0 :=
  aeval_mem_of_constantCoeff_eq_zero (RingHom.ker (constantCoeff : MvPolynomial V k →+* k)) f hf hQ

/-- A symmetric polynomial without constant term, as a combination of `e_1, …, e_N` with
coefficients in any subalgebra containing the `e_r`: it lies in the ideal they generate. -/
theorem symPlus_mem_span [Fintype V] {A : Subalgebra k (MvPolynomial V k)} (hA : ∀ r, esymm V k (r + 1) ∈ A)
    {s : MvPolynomial V k} (hs : s ∈ symPlus k) (hsA : s ∈ A) :
    (⟨s, hsA⟩ : A) ∈ Ideal.span (Set.range fun r : ℕ => (⟨esymm V k (r + 1), hA r⟩ : A)) := by
  set E := Ideal.span (Set.range fun r : ℕ => (⟨esymm V k (r + 1), hA r⟩ : A))
  obtain ⟨Q, hQ⟩ := esymmAlgHom_surjective k (σ := V) (n := Fintype.card V) le_rfl ⟨s, hs.1⟩
  set f : Fin (Fintype.card V) → MvPolynomial V k := fun i => esymm V k (i + 1)
  have hsQ : s = aeval f Q := by rw [← esymmAlgHom_apply, hQ]
  set c := constantCoeff Q
  have hf0 : ∀ i, constantCoeff (f i) = 0 := fun i => (esymm_succ_mem_symPlus (k := k) i).2
  have hc : c = 0 := by
    have h1 : s = C c + aeval f (Q - C c) := by rw [map_sub, aeval_C, algebraMap_eq, ← hsQ]; ring
    have h2 := congrArg constantCoeff h1
    rw [hs.2, map_add, constantCoeff_C,
      constantCoeff_aeval_eq_zero f hf0 (by simp [c]), add_zero] at h2
    exact h2.symm
  have hQ0 : constantCoeff Q = 0 := hc
  set g : Fin (Fintype.card V) → A := fun i => ⟨esymm V k (i + 1), hA i⟩
  have hmem : aeval g Q ∈ E :=
    aeval_mem_of_constantCoeff_eq_zero E g (fun i => Ideal.subset_span ⟨i, rfl⟩) hQ0
  convert hmem using 1
  apply Subtype.ext
  change s = A.val (aeval g Q)
  rw [hsQ]
  rw [← AlgHom.comp_apply, MvPolynomial.comp_aeval]
  rfl

/-! ### The Borel ring -/

variable (k) [Fintype V]

/-- The ideal of the Young invariants generated by the symmetric polynomials without constant
term. -/
def borelIdeal (lab : V → J) : Ideal (labelInvariants k lab) :=
  Ideal.span {a | (a : MvPolynomial V k) ∈ symPlus k}

/-- **The Borel ring** `k[V]^{G_lab} / (Sym⁺)`. -/
def BorelRing (lab : V → J) : Type _ := labelInvariants k lab ⧸ borelIdeal k lab

instance (lab : V → J) : CommRing (BorelRing k lab) := Ideal.Quotient.commRing _

instance (lab : V → J) : Algebra k (BorelRing k lab) := Ideal.Quotient.algebra _

/-- The quotient map `k[V]^{G_lab} → BorelRing k lab`. -/
def mkB (lab : V → J) : labelInvariants k lab →ₐ[k] BorelRing k lab := Ideal.Quotient.mkₐ k _

variable {k} in
theorem mkB_surjective (lab : V → J) : Function.Surjective (mkB k lab) :=
  Ideal.Quotient.mkₐ_surjective k _

variable {k} in
theorem mkB_eq_zero_iff {lab : V → J} {a : labelInvariants k lab} :
    mkB k lab a = 0 ↔ a ∈ borelIdeal k lab :=
  Ideal.Quotient.eq_zero_iff_mem

variable {k} in
theorem mkB_eq_mkB_iff {lab : V → J} {a b : labelInvariants k lab} :
    mkB k lab a = mkB k lab b ↔ a - b ∈ borelIdeal k lab :=
  Ideal.Quotient.eq

/-- `e_r` of all variables, as a Young invariant. -/
def esymmElt (lab : V → J) (r : ℕ) : labelInvariants k lab :=
  ⟨esymm V k r, mem_labelInvariants_of_isSymmetric lab (esymm_isSymmetric _ _ _)⟩

variable {k}

/-- `Sym⁺ k[V]^{G_lab}` is generated by `e_1, e_2, …`. -/
theorem borelIdeal_eq_span_esymm (lab : V → J) :
    borelIdeal k lab = Ideal.span (Set.range fun r : ℕ => esymmElt k lab (r + 1)) := by
  refine le_antisymm (Ideal.span_le.2 ?_) (Ideal.span_le.2 ?_)
  · rintro ⟨s, hsA⟩ hs
    exact symPlus_mem_span (fun r => (esymmElt k lab (r + 1)).2) hs hsA
  · rintro _ ⟨r, rfl⟩
    exact Ideal.subset_span (esymm_succ_mem_symPlus r)

theorem esymmElt_succ_mem (lab : V → J) (r : ℕ) : esymmElt k lab (r + 1) ∈ borelIdeal k lab :=
  Ideal.subset_span (esymm_succ_mem_symPlus r)

/-! ### Generators and dual generators -/

section Generators

variable [DecidableEq J] (k) (lab : V → J)

/-- `e_r` of the variables of block `j`, as a Young invariant. -/
def blockElt (j : J) (r : ℕ) : labelInvariants k lab :=
  ⟨setEsymm (labSet lab (· = j)) r, setEsymm_labSet_mem lab _ r⟩

/-- `e_r` of the variables outside block `j`, as a Young invariant. -/
def dualElt (j : J) (r : ℕ) : labelInvariants k lab :=
  ⟨setEsymm (labSet lab (· ≠ j)) r, setEsymm_labSet_mem lab _ r⟩

/-- **The generator `x(k)_{j,α}`** (KL III §5.1): the class of `e_α(block j)`. -/
noncomputable def xB (j : J) (α : ℕ) : BorelRing k lab := mkB k lab (blockElt k lab j α)

/-- **The dual generator `x̄(k)_{j,α}`** (KL III eq. (5.5)): the class of `e_α` of the variables
outside block `j`. -/
noncomputable def xbarB (j : J) (α : ℕ) : BorelRing k lab := mkB k lab (dualElt k lab j α)

variable {k lab}

@[simp] theorem xB_zero (j : J) : xB k lab j 0 = 1 := by
  rw [xB, ← map_one (mkB k lab)]
  congr 1
  exact Subtype.ext (setEsymm_zero _)

@[simp] theorem xbarB_zero (j : J) : xbarB k lab j 0 = 1 := by
  rw [xbarB, ← map_one (mkB k lab)]
  congr 1
  exact Subtype.ext (setEsymm_zero _)

/-- KL III eq. (5.4): `x(k)_{j,α} = 0` for `α` larger than the size of block `j`. -/
theorem xB_eq_zero {j : J} {α : ℕ} (h : (labSet lab (· = j)).card < α) : xB k lab j α = 0 := by
  rw [xB, ← map_zero (mkB k lab)]
  congr 1
  exact Subtype.ext (setEsymm_eq_zero h)

theorem labSet_disjoint (j : J) : Disjoint (labSet lab (· = j)) (labSet lab (· ≠ j)) := by
  rw [Finset.disjoint_left]
  intro v h1 h2
  simp only [mem_labSet] at h1 h2
  exact h2 h1

theorem labSet_union [DecidableEq V] (j : J) : labSet lab (· = j) ∪ labSet lab (· ≠ j) = univ := by
  ext v
  simp only [Finset.mem_union, mem_labSet, Finset.mem_univ, iff_true]
  exact em _

set_option synthInstance.maxHeartbeats 200000 in
/-- **KL III eq. (5.7)**: `∑_{f=0}^{α} x(k)_{j,f} x̄(k)_{j,α-f} = δ_{α,0}`. -/
theorem sum_xB_mul_xbarB [DecidableEq V] (j : J) (α : ℕ) :
    ∑ f ∈ Finset.range (α + 1), xB k lab j f * xbarB k lab j (α - f) = if α = 0 then 1 else 0 := by
  have key : ∑ f ∈ Finset.range (α + 1), blockElt k lab j f * dualElt k lab j (α - f) =
      esymmElt k lab α := by
    apply Subtype.ext
    simp only [AddSubmonoidClass.coe_finset_sum, MulMemClass.coe_mul, blockElt, dualElt, esymmElt]
    rw [← setEsymm_univ, ← labSet_union (lab := lab) j, setEsymm_union (labSet_disjoint j),
      Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk]
  simp only [xB, xbarB, ← map_mul, ← map_sum, key]
  rcases α with _ | r
  · rw [if_pos rfl, ← map_one (mkB k lab)]
    congr 1
    exact Subtype.ext (esymm_zero _ _)
  · rw [if_neg (Nat.succ_ne_zero r), mkB_eq_zero_iff]
    exact esymmElt_succ_mem lab r

end Generators

/-! ### Refinements: forgetful maps -/

section Refine

variable {J' : Type*}

/-- `lab'` refines `lab`: variables with the same `lab'`-label have the same `lab`-label. Then
`G_{lab'} ⊆ G_lab`, and the flag variety of `lab'` maps to that of `lab`. -/
def Refines (lab' : V → J') (lab : V → J) : Prop := ∀ v w, lab' v = lab' w → lab v = lab w

variable (k)

omit [Fintype V] in
theorem labelInvariants_mono {lab : V → J} {lab' : V → J'} (h : Refines lab' lab) :
    labelInvariants k lab ≤ labelInvariants k lab' := by
  intro f hf g hg
  refine hf g (funext fun v => h (g v) v (congrFun hg v))

/-- **The forgetful map** `BorelRing k lab → BorelRing k lab'` for a refinement `lab'` of `lab`
(pullback `p^*` along `Fl(lab') → Fl(lab)`; KL III §5.1.1). -/
noncomputable def refineHom {lab : V → J} {lab' : V → J'} (h : Refines lab' lab) :
    BorelRing k lab →ₐ[k] BorelRing k lab' :=
  Ideal.quotientMapₐ (borelIdeal k lab') (Subalgebra.inclusion (labelInvariants_mono k h))
    (Ideal.span_le.2 fun _ ha => Ideal.subset_span ha)

variable {k}

theorem refineHom_mk {lab : V → J} {lab' : V → J'} (h : Refines lab' lab)
    (a : labelInvariants k lab) (b : labelInvariants k lab') (hab : (a : MvPolynomial V k) = b) :
    refineHom k h (mkB k lab a) = mkB k lab' b := by
  change mkB k lab' (Subalgebra.inclusion (labelInvariants_mono k h) a) = _
  congr 1
  exact Subtype.ext hab

end Refine

/-! ### Transport along relabellings of the variables -/

section Congr

variable {V' : Type*} [Fintype V'] {lab : V → J} {lab' : V' → J}

omit [Fintype V] [Fintype V'] in
theorem rename_mem_labelInvariants (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v)
    {f : MvPolynomial V k} (hf : f ∈ labelInvariants k lab) :
    rename e f ∈ labelInvariants k lab' := by
  intro g hg
  have hg' : lab ∘ (e.trans (g.trans e.symm)) = lab := by
    funext v
    simp only [Function.comp_apply, Equiv.trans_apply]
    rw [← h, Equiv.apply_symm_apply, ← h v]
    exact congrFun hg (e v)
  have h1 := hf _ hg'
  rw [rename_rename]
  have : (⇑g ∘ ⇑e) = ⇑e ∘ ⇑(e.trans (g.trans e.symm)) := by
    funext v; simp
  rw [this, ← rename_rename, h1]

theorem rename_mem_symPlus (e : V ≃ V') {s : MvPolynomial V k} (hs : s ∈ symPlus k) :
    rename e s ∈ symPlus k := by
  refine ⟨fun σ => ?_, by rw [constantCoeff_rename, hs.2]⟩
  rw [rename_rename]
  have : (⇑σ ∘ ⇑e) = ⇑e ∘ ⇑(e.trans (σ.trans e.symm)) := by
    funext v; simp
  rw [this, ← rename_rename, hs.1]

variable (k)

/-- The Young invariants of `lab` and `lab'` are isomorphic via renaming along `e`, if `e`
preserves labels. -/
noncomputable def invCongr (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v) :
    labelInvariants k lab ≃ₐ[k] labelInvariants k lab' :=
  have h' : ∀ v', lab (e.symm v') = lab' v' := fun v' => by rw [← h, Equiv.apply_symm_apply]
  AlgEquiv.ofAlgHom
    (((rename e).comp (labelInvariants k lab).val).codRestrict _
      fun f => rename_mem_labelInvariants e h f.2)
    (((rename e.symm).comp (labelInvariants k lab').val).codRestrict _
      fun f => rename_mem_labelInvariants e.symm h' f.2)
    (by ext f; simp [rename_rename])
    (by ext f; simp [rename_rename])

omit [Fintype V] [Fintype V'] in
theorem invCongr_apply_coe (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v) (a : labelInvariants k lab) :
    (invCongr k e h a : MvPolynomial V' k) = rename e a := rfl

/-- **The Borel ring only depends on the labelled set of variables up to isomorphism.** -/
noncomputable def borelCongr (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v) :
    BorelRing k lab ≃ₐ[k] BorelRing k lab' :=
  Ideal.quotientEquivAlg (borelIdeal k lab) (borelIdeal k lab') (invCongr k e h) <| by
    rw [borelIdeal, borelIdeal, Ideal.map_span]
    congr 1
    ext b
    constructor
    · intro hb
      refine ⟨(invCongr k e h).symm b, ?_, by simp⟩
      change rename e.symm (b : MvPolynomial V' k) ∈ symPlus k
      exact rename_mem_symPlus e.symm hb
    · rintro ⟨a, ha, rfl⟩
      exact rename_mem_symPlus e ha

theorem borelCongr_mk (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v) (a : labelInvariants k lab)
    (b : labelInvariants k lab') (hab : rename e (a : MvPolynomial V k) = b) :
    borelCongr k e h (mkB k lab a) = mkB k lab' b := by
  change mkB k lab' (invCongr k e h a) = _
  congr 1
  exact Subtype.ext hab

theorem map_labSet (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v) (p : J → Prop) [DecidablePred p] :
    (labSet lab p).map e.toEmbedding = labSet lab' p := by
  ext v'
  rw [Finset.mem_map_equiv, mem_labSet, mem_labSet, ← h, Equiv.apply_symm_apply]

variable [DecidableEq J]

@[simp] theorem borelCongr_xB (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v) (j : J) (α : ℕ) :
    borelCongr k e h (xB k lab j α) = xB k lab' j α := by
  refine borelCongr_mk k e h _ _ ?_
  change rename e.toEmbedding _ = _
  rw [blockElt, rename_setEsymm, map_labSet e h]
  rfl

@[simp] theorem borelCongr_xbarB (e : V ≃ V') (h : ∀ v, lab' (e v) = lab v) (j : J) (α : ℕ) :
    borelCongr k e h (xbarB k lab j α) = xbarB k lab' j α := by
  refine borelCongr_mk k e h _ _ ?_
  change rename e.toEmbedding _ = _
  rw [dualElt, rename_setEsymm, map_labSet e h]
  rfl

/-- **The Borel ring only depends on the block sizes.** -/
noncomputable def borelEquivOfCard (lab : V → J) (lab' : V' → J)
    (hc : ∀ j, Fintype.card {v // lab v = j} = Fintype.card {v' // lab' v' = j}) :
    BorelRing k lab ≃ₐ[k] BorelRing k lab' :=
  borelCongr k (Equiv.ofFiberEquiv fun j => Fintype.equivOfCardEq (hc j))
    (Equiv.ofFiberEquiv_map _)

@[simp] theorem borelEquivOfCard_xB (lab : V → J) (lab' : V' → J)
    (hc : ∀ j, Fintype.card {v // lab v = j} = Fintype.card {v' // lab' v' = j}) (j : J) (α : ℕ) :
    borelEquivOfCard k lab lab' hc (xB k lab j α) = xB k lab' j α :=
  borelCongr_xB k _ _ j α

@[simp] theorem borelEquivOfCard_xbarB (lab : V → J) (lab' : V' → J)
    (hc : ∀ j, Fintype.card {v // lab v = j} = Fintype.card {v' // lab' v' = j}) (j : J) (α : ℕ) :
    borelEquivOfCard k lab lab' hc (xbarB k lab j α) = xbarB k lab' j α :=
  borelCongr_xbarB k _ _ j α

end Congr

/-! ### The dimension -/

section Rank

variable (k) [DecidableEq V]

/-- The ideal of `k[V]` generated by `Sym⁺`. -/
noncomputable abbrev symPlusIdeal : Ideal (MvPolynomial V k) := Ideal.span (symPlus k)

/-- `k[V] / (Sym⁺) ≅ L_N` (the coinvariant algebra of `Categorification.Coinv`). -/
noncomputable def coinvEquiv :
    (MvPolynomial V k ⧸ (symPlusIdeal k (V := V)).restrictScalars k) ≃ₗ[k]
      Coinv k (Fintype.card V) := by
  let e := renameEquiv k (Fintype.equivFin V)
  refine Submodule.Quotient.equiv _ _ e.toLinearEquiv ?_
  have hmap : Ideal.map e (symPlusIdeal k (V := V)) = coinvIdeal k (Fintype.card V) := by
    rw [symPlusIdeal, Ideal.map_span, coinvIdeal]
    congr 1
    ext s
    constructor
    · rintro ⟨t, ht, rfl⟩
      obtain ⟨h1, h2⟩ := rename_mem_symPlus (k := k) (Fintype.equivFin V) ht
      exact ⟨h1, h2⟩
    · intro hs
      refine ⟨rename (Fintype.equivFin V).symm s,
        rename_mem_symPlus (Fintype.equivFin V).symm ⟨hs.1, hs.2⟩, ?_⟩
      simp [e, rename_rename]
  ext x
  simp only [Submodule.mem_map, Submodule.restrictScalars_mem, coinvSub, ← hmap,
    Ideal.mem_map_of_equiv]
  rfl

omit [DecidableEq V] in
theorem finrank_quot_symPlus :
    Module.finrank k (MvPolynomial V k ⧸ (symPlusIdeal k (V := V)).restrictScalars k) =
      (Fintype.card V).factorial := by
  rw [(coinvEquiv k).finrank_eq, finrank_coinv]

instance : FiniteDimensional k (MvPolynomial V k ⧸ (symPlusIdeal k (V := V)).restrictScalars k) :=
  LinearEquiv.finiteDimensional (coinvEquiv k).symm

omit [DecidableEq V] in
theorem borelIdeal_map_val (lab : V → J) :
    (borelIdeal k lab).map (labelInvariants k lab).val = symPlusIdeal k := by
  rw [borelIdeal, Ideal.map_span]
  congr 1
  ext s
  constructor
  · rintro ⟨a, ha, rfl⟩
    exact ha
  · intro hs
    exact ⟨⟨s, mem_labelInvariants_of_isSymmetric lab hs.1⟩, hs, rfl⟩

variable [DecidableEq J]

set_option synthInstance.maxHeartbeats 200000 in
/-- `k[V] / (Sym⁺) ≅ (BorelRing k lab)^ι` with `|ι| = |G_lab|`. -/
theorem exists_quot_equiv_pi (lab : V → J) :
    ∃ (ι : Type) (_ : Fintype ι), Nonempty ι ∧
      Fintype.card ι = ∏ j ∈ univ.image lab, (Fintype.card {v // lab v = j}).factorial ∧
      Nonempty ((MvPolynomial V k ⧸ (symPlusIdeal k (V := V)).restrictScalars k) ≃ₗ[k]
        (ι → BorelRing k lab)) := by
  obtain ⟨ι, _, hcard, ⟨b⟩⟩ := exists_labelBasis k lab
  classical
  have e := quotLinearEquiv' (labelInvariants k lab) b (borelIdeal k lab) (mkB k lab)
    (mkB_surjective lab) (Ideal.mk_ker)
  rw [borelIdeal_map_val] at e
  refine ⟨ι, inferInstance, ?_, by rw [hcard, DomMulAct.stabilizer_card'], ⟨e⟩⟩
  rw [← Fintype.card_pos_iff, hcard]
  exact Fintype.card_pos_iff.2 ⟨⟨1, rfl⟩⟩

set_option synthInstance.maxHeartbeats 200000 in
instance (lab : V → J) : FiniteDimensional k (BorelRing k lab) := by
  obtain ⟨ι, _, ⟨i₀⟩, -, ⟨e⟩⟩ := exists_quot_equiv_pi k lab
  haveI : FiniteDimensional k (ι → BorelRing k lab) := LinearEquiv.finiteDimensional e
  exact Module.Finite.of_surjective (LinearMap.proj i₀) fun x => ⟨fun _ => x, rfl⟩

set_option synthInstance.maxHeartbeats 200000 in
/-- **The dimension of the Borel ring**: `dim_k BorelRing k lab · ∏_j N_j! = N!`, where
`N_j = |lab⁻¹(j)|` and `N = |V|`. -/
theorem finrank_borelRing (lab : V → J) :
    Module.finrank k (BorelRing k lab) *
        ∏ j ∈ univ.image lab, (Fintype.card {v // lab v = j}).factorial =
      (Fintype.card V).factorial := by
  obtain ⟨ι, _, -, hcard, ⟨e⟩⟩ := exists_quot_equiv_pi k lab
  have h1 := e.finrank_eq
  rw [finrank_quot_symPlus, Module.finrank_pi_fintype, Finset.sum_const, Finset.card_univ,
    smul_eq_mul, hcard] at h1
  rw [h1, mul_comm]

end Rank

end Categorification.Flag

end
