/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Flag.YoungInvariants
import Categorification.Flag.Borel

/-!
# The cohomology rings `H_k` of partial flag varieties (KL III §5.1)

Khovanov–Lauda III, arXiv:0807.3250v1, §5.1 (TeX `sln-2008-ArXiv.tex`, subsection
"Cohomology of n-step varieties"). For a sequence `0 = k_0 ≤ k_1 ≤ ⋯ ≤ k_n = N` put
`d_j = k_j - k_{j-1}` (the paper's blocks are indexed `1, …, n`; ours are `j : Fin n`). The
cohomology ring of the component `Fl(k)` of the variety of `n`-step flags in `ℂ^N` is presented
in KL III eq. (5.2) as

  `H_k = (⊗_j k[x_{j,1}, …, x_{j,d_j}]) / I_{k,N}`,  `deg x_{j,α} = 2α`,

where `I_{k,N}` is generated by the homogeneous terms of positive degree of
`∏_j (1 + x_{j,1} t + ⋯ + x_{j,d_j} t^{d_j}) = 1` (eq. (5.3)), with the conventions
`x_{j,0} = 1`, `x_{j,α} = 0` for `α > d_j` (eq. (5.4)).

We formalize this presentation for block sizes `d : Fin n → ℕ` as `Flag.H k d`: the generator
`x_{j,α}` (`1 ≤ α ≤ d_j`) is the variable `⟨j, α - 1⟩ : Gen d` of `k[Gen d]`, and `Flag.xgen`
implements the conventions (5.4).

## Main results

* `Flag.H k d`, `Flag.x k d j α` (the paper's `x(k)_{j,α}`), `Flag.xbar k d j α` (the dual
  generators `x̄(k)_{j,α}` of eq. (5.5)).
* `Flag.map_totalSeries_mkH` : eq. (5.3) holds in `H k d`.
* `Flag.sum_x_mul_xbar` : eq. (5.7), `∑_{f=0}^{α} x_{j,f} x̄_{j,α-f} = δ_{α,0}`.
* `Flag.relIdeal_isHomogeneous` : `I_{k,N}` is homogeneous for `deg x_{j,α} = α` (KL III's
  degree is twice this), so `H k d` is graded.
* **Borel presentation** (`Flag.hEquiv`): over a field,
  `H k d ≃ₐ k[Gen d]^{S_{d_0} × ⋯ × S_{d_{n-1}}} / (Sym⁺)`, sending `x_{j,α}` to the class of
  `e_α` of the variables of block `j` and `x̄_{j,α}` to the class of `e_α` of the variables
  outside block `j` (`hEquiv_x`, `hEquiv_xbar`). It is built from the fundamental theorem for
  Young subgroups (`Flag.youngEquiv`) and the identity `∏_j ∏_{v ∈ block j} (1 + x_v t) =
  ∏_v (1 + x_v t)`, which identifies the relations (5.3) with `e_r(x_1, …, x_N)`, `r ≥ 1`.
* `Flag.finrank_H` : `dim_k H k d = N! / ∏_j d_j!` (the multinomial coefficient).
* `Flag.borelEquivH` : for any labelling `lab : V → Fin n` of a finite set of variables,
  `BorelRing k lab ≃ₐ H k (block sizes of lab)`.
-/

noncomputable section

namespace Categorification.Flag

open MvPolynomial
open Finset (univ range)

universe u

section Presentation

variable (k : Type u) [CommRing k] {n : ℕ} (d : Fin n → ℕ)

/-! ### The presentation (5.2) -/

/-- The generator `x_{j,α}` of KL III (5.2), with `x_{j,0} = 1` and `x_{j,α} = 0` for
`α > d_j` (eq. (5.4)). -/
def xgen (j : Fin n) (α : ℕ) : MvPolynomial (Gen d) k :=
  if α = 0 then 1 else if h : α - 1 < d j then X ⟨j, ⟨α - 1, h⟩⟩ else 0

/-- The total Chern class of block `j`: `1 + x_{j,1} t + ⋯ + x_{j,d_j} t^{d_j}`. -/
def blockSeries (j : Fin n) : Polynomial (MvPolynomial (Gen d) k) :=
  ∑ α ∈ range (d j + 1), Polynomial.C (xgen k d j α) * Polynomial.X ^ α

/-- The left-hand side of eq. (5.3), `∏_j (1 + x_{j,1} t + ⋯ + x_{j,d_j} t^{d_j})`. -/
def totalSeries : Polynomial (MvPolynomial (Gen d) k) := ∏ j, blockSeries k d j

/-- The homogeneous term of degree `r` of eq. (5.3). -/
def relPoly (r : ℕ) : MvPolynomial (Gen d) k := (totalSeries k d).coeff r

/-- **The ideal `I_{k,N}`** generated by the homogeneous terms of positive degree of (5.3). -/
def relIdeal : Ideal (MvPolynomial (Gen d) k) :=
  Ideal.span (Set.range fun r : ℕ => relPoly k d (r + 1))

/-- **The ring `H_k` of KL III eq. (5.2)**, for block sizes `d_j = k_j - k_{j-1}`. -/
def H : Type u := MvPolynomial (Gen d) k ⧸ relIdeal k d

instance : CommRing (H k d) := Ideal.Quotient.commRing _

instance : Algebra k (H k d) := Ideal.Quotient.algebra _

/-- The quotient map `k[x_{j,α}] → H_k`. -/
def mkH : MvPolynomial (Gen d) k →ₐ[k] H k d := Ideal.Quotient.mkₐ k _

theorem mkH_surjective : Function.Surjective (mkH k d) := Ideal.Quotient.mkₐ_surjective k _

/-- The generator `x(k)_{j,α} ∈ H_k`. -/
def x (j : Fin n) (α : ℕ) : H k d := mkH k d (xgen k d j α)

/-- The product of the total Chern classes of all blocks except `j` (KL III eq. (5.5)). -/
def dualSeries (j : Fin n) : Polynomial (MvPolynomial (Gen d) k) :=
  ∏ j' ∈ univ.erase j, blockSeries k d j'

/-- **The dual generator `x̄(k)_{j,α}`** (KL III eq. (5.5)): the homogeneous term of degree `α`
of `∏_{j' ≠ j} (1 + x_{j',1} t + ⋯)`. -/
def xbar (j : Fin n) (α : ℕ) : H k d := mkH k d ((dualSeries k d j).coeff α)

variable {k d}

@[simp] theorem xgen_zero (j : Fin n) : xgen k d j 0 = 1 := by simp [xgen]

theorem xgen_eq_zero {j : Fin n} {α : ℕ} (h : d j < α) : xgen k d j α = 0 := by
  rw [xgen, if_neg (by omega), dif_neg (by omega)]

theorem xgen_succ {j : Fin n} {a : ℕ} (h : a < d j) : xgen k d j (a + 1) = X ⟨j, ⟨a, h⟩⟩ := by
  rw [xgen, if_neg (Nat.succ_ne_zero a), dif_pos (by omega)]
  rfl

theorem coeff_blockSeries (j : Fin n) (α : ℕ) : (blockSeries k d j).coeff α = xgen k d j α := by
  rw [blockSeries, Polynomial.finset_sum_coeff]
  simp only [Polynomial.coeff_C_mul_X_pow]
  rw [Finset.sum_ite_eq]
  split_ifs with h
  · rfl
  · rw [xgen_eq_zero (by simp at h; omega)]

@[simp] theorem x_zero (j : Fin n) : x k d j 0 = 1 := by simp [x]

/-- KL III eq. (5.4). -/
theorem x_eq_zero {j : Fin n} {α : ℕ} (h : d j < α) : x k d j α = 0 := by
  rw [x, xgen_eq_zero h, map_zero]

theorem relPoly_mem (r : ℕ) : relPoly k d (r + 1) ∈ relIdeal k d := Ideal.subset_span ⟨r, rfl⟩

theorem coeff_zero_blockSeries (j : Fin n) : (blockSeries k d j).coeff 0 = 1 := by
  rw [coeff_blockSeries, xgen_zero]

/-- **KL III eq. (5.3) holds in `H_k`**: `∏_j (1 + x_{j,1} t + ⋯ + x_{j,d_j} t^{d_j}) = 1`. -/
theorem map_totalSeries_mkH : (totalSeries k d).map (mkH k d).toRingHom = 1 := by
  ext r
  rw [Polynomial.coeff_map, Polynomial.coeff_one]
  rcases r with _ | r
  · rw [totalSeries, Polynomial.coeff_zero_prod]
    simp [coeff_zero_blockSeries]
  · rw [if_neg (Nat.succ_ne_zero r)]
    exact Ideal.Quotient.eq_zero_iff_mem.2 (relPoly_mem r)

theorem blockSeries_mul_dualSeries (j : Fin n) :
    blockSeries k d j * dualSeries k d j = totalSeries k d := by
  rw [dualSeries, totalSeries, Finset.mul_prod_erase _ _ (Finset.mem_univ j)]

/-- **KL III eq. (5.7)**: `∑_{f=0}^{α} x(k)_{j,f} x̄(k)_{j,α-f} = δ_{α,0}`. -/
theorem sum_x_mul_xbar (j : Fin n) (α : ℕ) :
    ∑ f ∈ range (α + 1), x k d j f * xbar k d j (α - f) = if α = 0 then 1 else 0 := by
  have h := congrArg (fun p => (p.map (mkH k d).toRingHom).coeff α) (blockSeries_mul_dualSeries (k := k) (d := d) j)
  simp only [Polynomial.map_mul, map_totalSeries_mkH, Polynomial.coeff_one] at h
  rw [Polynomial.coeff_mul, Finset.Nat.sum_antidiagonal_eq_sum_range_succ_mk] at h
  simp only [Polynomial.coeff_map, coeff_blockSeries, AlgHom.toRingHom_eq_coe,
    RingHom.coe_coe] at h
  rw [← h]
  simp only [x, xbar]

/-! ### Grading -/

/-- The weight `deg x_{j,α} = α` (KL III's cohomological degree is `2α`). -/
def genWeight : Gen d → ℕ := fun v => v.2 + 1

/-- A polynomial in `t` whose `t^r`-coefficient is weighted homogeneous of degree `r`. -/
def GradedSeries (p : Polynomial (MvPolynomial (Gen d) k)) : Prop :=
  ∀ r, IsWeightedHomogeneous (genWeight (d := d)) (p.coeff r) r

theorem GradedSeries.mul {p q : Polynomial (MvPolynomial (Gen d) k)} (hp : GradedSeries p)
    (hq : GradedSeries q) : GradedSeries (p * q) := by
  intro r
  rw [Polynomial.coeff_mul]
  refine IsWeightedHomogeneous.sum _ _ _ fun ab hab => ?_
  rw [← Finset.mem_antidiagonal.1 hab]
  exact (hp ab.1).mul (hq ab.2)

theorem gradedSeries_one : GradedSeries (1 : Polynomial (MvPolynomial (Gen d) k)) := by
  intro r
  rw [Polynomial.coeff_one]
  split_ifs with h
  · subst h; exact isWeightedHomogeneous_one _ _
  · exact isWeightedHomogeneous_zero _ _ _

theorem xgen_isWeightedHomogeneous (j : Fin n) (α : ℕ) :
    IsWeightedHomogeneous (genWeight (d := d)) (xgen k d j α) α := by
  rcases α with _ | a
  · rw [xgen_zero]; exact isWeightedHomogeneous_one _ _
  · by_cases h : a < d j
    · rw [xgen_succ h]
      exact isWeightedHomogeneous_X _ _ _
    · rw [xgen_eq_zero (by omega)]; exact isWeightedHomogeneous_zero _ _ _

theorem gradedSeries_blockSeries (j : Fin n) : GradedSeries (blockSeries k d j) := by
  intro r
  rw [coeff_blockSeries]
  exact xgen_isWeightedHomogeneous j r

theorem gradedSeries_totalSeries : GradedSeries (totalSeries k d) :=
  Finset.prod_induction _ GradedSeries (fun _ _ => GradedSeries.mul) gradedSeries_one
    fun j _ => gradedSeries_blockSeries j

/-- The relations (5.3) are homogeneous: `relPoly r` has degree `r` (`deg x_{j,α} = α`). -/
theorem relPoly_isWeightedHomogeneous (r : ℕ) :
    IsWeightedHomogeneous (genWeight (d := d)) (relPoly k d r) r :=
  gradedSeries_totalSeries r

attribute [local instance] weightedGradedAlgebra in
/-- **`H_k` is graded**: `I_{k,N}` is a homogeneous ideal for `deg x_{j,α} = α`. -/
theorem relIdeal_isHomogeneous :
    (relIdeal k d).IsHomogeneous (weightedHomogeneousSubmodule k (genWeight (d := d))) := by
  refine Ideal.homogeneous_span _ _ ?_
  rintro _ ⟨r, rfl⟩
  exact ⟨r + 1, (mem_weightedHomogeneousSubmodule _ _ _ _).2 (relPoly_isWeightedHomogeneous _)⟩

/-! ### The Borel presentation -/

section Borel

theorem card_labSet_sigma (j : Fin n) :
    (labSet (Sigma.fst : Gen d → Fin n) (· = j)).card = d j := by
  rw [← map_sigmaMk_univ d j, Finset.card_map, Finset.card_univ, Fintype.card_fin]

theorem card_fibre_sigma (j : Fin n) : Fintype.card {v : Gen d // v.1 = j} = d j := by
  rw [Fintype.card_subtype]
  exact card_labSet_sigma j

theorem youngHom_xgen (j : Fin n) (α : ℕ) :
    youngHom k d (xgen k d j α) = setEsymm (labSet (Sigma.fst : Gen d → Fin n) (· = j)) α := by
  rcases α with _ | a
  · rw [xgen_zero, map_one, setEsymm_zero]
  · by_cases h : a < d j
    · rw [xgen_succ h, youngHom_X, blockEsymm_eq_setEsymm]
    · rw [xgen_eq_zero (by omega), map_zero, setEsymm_eq_zero]
      rw [card_labSet_sigma]; omega

theorem map_blockSeries (j : Fin n) :
    (blockSeries k d j).map (youngHom k d).toRingHom =
      esSeries (labSet (Sigma.fst : Gen d → Fin n) (· = j)) := by
  ext α
  rw [Polynomial.coeff_map, coeff_blockSeries, coeff_esSeries, AlgHom.toRingHom_eq_coe,
    RingHom.coe_coe, youngHom_xgen]

theorem prod_esSeries_blocks :
    ∏ j, esSeries (k := k) (labSet (Sigma.fst : Gen d → Fin n) (· = j)) =
      esSeries (univ : Finset (Gen d)) := by
  simp only [esSeries]
  exact Finset.prod_fiberwise univ Sigma.fst _

theorem map_totalSeries :
    (totalSeries k d).map (youngHom k d).toRingHom = esSeries (univ : Finset (Gen d)) := by
  rw [totalSeries, Polynomial.map_prod]
  simp only [map_blockSeries]
  exact prod_esSeries_blocks

/-- The relation `relPoly r` maps to `e_r(x_1, …, x_N)` under `x_{j,α} ↦ e_α(block j)`. -/
theorem youngHom_relPoly (r : ℕ) : youngHom k d (relPoly k d r) = esymm (Gen d) k r := by
  have h := congrArg (fun p => p.coeff r) (map_totalSeries (k := k) (d := d))
  simp only [Polynomial.coeff_map, coeff_esSeries, setEsymm_univ, AlgHom.toRingHom_eq_coe,
    RingHom.coe_coe] at h
  exact h

theorem esSeries_ne_zero [Nontrivial k] (s : Finset (Gen d)) : esSeries (k := k) s ≠ 0 := by
  intro h
  have := congrArg (fun p => p.coeff 0) h
  simp only [coeff_esSeries, setEsymm_zero, Polynomial.coeff_zero] at this
  exact one_ne_zero this

theorem map_dualSeries [IsDomain k] (j : Fin n) :
    (dualSeries k d j).map (youngHom k d).toRingHom =
      esSeries (labSet (Sigma.fst : Gen d → Fin n) (· ≠ j)) := by
  apply mul_left_cancel₀ (esSeries_ne_zero (labSet (Sigma.fst : Gen d → Fin n) (· = j)))
  conv_lhs => rw [← map_blockSeries, ← Polynomial.map_mul, blockSeries_mul_dualSeries,
    map_totalSeries, ← labSet_union (lab := (Sigma.fst : Gen d → Fin n)) j]
  exact esSeries_union (labSet_disjoint j)

theorem youngHom_coeff_dualSeries [IsDomain k] (j : Fin n) (α : ℕ) :
    youngHom k d ((dualSeries k d j).coeff α) =
      setEsymm (labSet (Sigma.fst : Gen d → Fin n) (· ≠ j)) α := by
  have h := congrArg (fun p => p.coeff α) (map_dualSeries (k := k) (d := d) j)
  simp only [Polynomial.coeff_map, coeff_esSeries, AlgHom.toRingHom_eq_coe,
    RingHom.coe_coe] at h
  exact h

end Borel

end Presentation

section BorelField

variable {K : Type u} [Field K] {n : ℕ} {d : Fin n → ℕ}

theorem borelIdeal_eq_map_relIdeal :
    borelIdeal K (Sigma.fst : Gen d → Fin n) = (relIdeal K d).map (youngEquiv K d) := by
  rw [borelIdeal_eq_span_esymm, relIdeal, Ideal.map_span, ← Set.range_comp]
  refine congrArg Ideal.span (congrArg Set.range (funext fun r => ?_))
  apply Subtype.ext
  simp only [Function.comp_apply, youngEquiv_apply_coe, youngHom_relPoly]
  rfl

variable (K d)

/-- **The Borel presentation of `H_k`** (KL III §5.1 / eq. (5.2)):
`H_k ≃ₐ k[x_1, …, x_N]^{S_{d_0} × ⋯ × S_{d_{n-1}}} / (Sym⁺)`. -/
def hEquiv : H K d ≃ₐ[K] BorelRing K (Sigma.fst : Gen d → Fin n) :=
  Ideal.quotientEquivAlg (relIdeal K d) (borelIdeal K (Sigma.fst : Gen d → Fin n))
    (youngEquiv K d) borelIdeal_eq_map_relIdeal

variable {K d}

theorem hEquiv_mkH (F : MvPolynomial (Gen d) K) :
    hEquiv K d (mkH K d F) = mkB K _ (youngEquiv K d F) := rfl

@[simp] theorem hEquiv_x (j : Fin n) (α : ℕ) :
    hEquiv K d (x K d j α) = xB K (Sigma.fst : Gen d → Fin n) j α := by
  rw [x, hEquiv_mkH, xB]
  congr 1
  apply Subtype.ext
  rw [youngEquiv_apply_coe, youngHom_xgen]
  rfl

@[simp] theorem hEquiv_xbar (j : Fin n) (α : ℕ) :
    hEquiv K d (xbar K d j α) = xbarB K (Sigma.fst : Gen d → Fin n) j α := by
  rw [xbar, hEquiv_mkH, xbarB]
  congr 1
  apply Subtype.ext
  rw [youngEquiv_apply_coe, youngHom_coeff_dualSeries]
  rfl

instance : FiniteDimensional K (H K d) :=
  LinearEquiv.finiteDimensional (hEquiv K d).toLinearEquiv.symm

/-- **`dim_k H_k` is the multinomial coefficient** `N! / ∏_j d_j!`, `N = ∑_j d_j` (the Euler
characteristic of `Fl(k)`). -/
theorem finrank_H : Module.finrank K (H K d) = Nat.multinomial univ d := by
  have h := finrank_borelRing K (Sigma.fst : Gen d → Fin n)
  rw [← (hEquiv K d).toLinearEquiv.finrank_eq, Fintype.card_sigma] at h
  simp only [Fintype.card_fin, card_fibre_sigma] at h
  have hprod : ∏ j ∈ univ.image (Sigma.fst : Gen d → Fin n), (d j).factorial =
      ∏ j, (d j).factorial := by
    refine Finset.prod_subset (Finset.subset_univ _) fun j _ hj => ?_
    have : d j = 0 := by
      by_contra h0
      exact hj (Finset.mem_image.2 ⟨⟨j, ⟨0, Nat.pos_of_ne_zero h0⟩⟩, Finset.mem_univ _, rfl⟩)
    rw [this, Nat.factorial_zero]
  rw [hprod, ← Nat.multinomial_spec, mul_comm] at h
  exact Nat.eq_of_mul_eq_mul_left (Finset.prod_pos fun j _ => Nat.factorial_pos _) h

/-- For any labelled finite set of variables `lab : V → Fin n`, the Borel ring of `lab` is the
ring `H_k` of the block sizes of `lab`. -/
def borelEquivH {V : Type*} [Fintype V] (lab : V → Fin n) :
    BorelRing K lab ≃ₐ[K] H K (fun j => Fintype.card {v // lab v = j}) :=
  (borelEquivOfCard K lab (Sigma.fst : Gen (fun j => Fintype.card {v // lab v = j}) → Fin n)
    fun j => (card_fibre_sigma (d := fun j => Fintype.card {v // lab v = j}) j).symm).trans (hEquiv K _).symm

@[simp] theorem borelEquivH_xB {V : Type*} [Fintype V] (lab : V → Fin n) (j : Fin n) (α : ℕ) :
    borelEquivH lab (xB K lab j α) = x K _ j α := by
  rw [borelEquivH, AlgEquiv.trans_apply, borelEquivOfCard_xB, AlgEquiv.symm_apply_eq, hEquiv_x]

@[simp] theorem borelEquivH_xbarB {V : Type*} [Fintype V] (lab : V → Fin n) (j : Fin n)
    (α : ℕ) : borelEquivH lab (xbarB K lab j α) = xbar K _ j α := by
  rw [borelEquivH, AlgEquiv.trans_apply, borelEquivOfCard_xbarB, AlgEquiv.symm_apply_eq,
    hEquiv_xbar]

end BorelField

end Categorification.Flag

end
