/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Flag.Cups

/-!
# Freeness of `H_{k^{+i}}` over `H_k` and over `H_{+_i k}`

Khovanov–Lauda III, arXiv:0807.3250v1, §5.1.1 (TeX `sln-2008-ArXiv.tex`, subsubsection "Flag
varieties for the action of `E_i` and `F_i`"): `H_{k^{+i}}` is generated over `H_k` by `ξ_i`,
subject to the single relation `∏_{v ∈ block i+1} (ξ_i - x_v) = 0`; equivalently it is a free
`H_k`-module with basis `1, ξ_i, …, ξ_i^{k_{i+1}-k_i-1}` (the fibre of `Fl(k^{+i}) → Fl(k)` is a
projective space `ℙ^{k_{i+1}-k_i-1}`). Symmetrically it is free over `H_{+_i k}` with basis
`1, ξ_i, …, ξ_i^{k_i-k_{i-1}}`.

We keep the Borel model of `Categorification.Flag.Bimodule`: `lab : V → J`, the variable `v₀`,
`M = BorelRing k (splitLab lab v₀)` (`= H_{k^{+i}}`), `R = BorelRing k lab` (`= H_k`, acting through
`pR`) and `R' = BorelRing k (moveLab lab v₀ j')` (`= H_{+_i k}`, acting through `pL`).

## Main results

* `Flag.adjoin_xB` : for a finite set of labels, the Borel ring is generated by the classes
  `x_{j,α}` (from the fundamental theorem for Young subgroups, `Flag.youngHom_range`).
* `Flag.finrank_split` : `dim_k M = b · dim_k R`, `b` the size of the block of `v₀`.
* `Flag.basisR` : the basis `ξ^a`, `a < b`, of `M` over `R` (via `pR`);
  `Flag.basisL` : the basis `ξ^a`, `a < b'`, of `M` over `R'` (via `pL`), `b'` the size of the block
  of `v₀` in `moveLab lab v₀ j'`.
* `Flag.trace_pow` (abstract), `Flag.trR_xi_pow`, `Flag.trL_xi_pow` : the *Frobenius traces*
  `tr : M → R`, the coordinate of `ξ^{b-1}`, satisfy
  `tr(ξ^a) = (-1)^{a+1-b} x̄_{a+1-b}` (and `0` for `a + 1 < b`), where `x̄` are the dual generators
  (KL III eq. (5.5)) of the block of `v₀`. These are the values of the caps of KL III
  Definition 6.1, eqs. (6.4), (6.5).
* `Flag.eBasisRight`, `Flag.eBasisLeft` : the corresponding statements for a composition `d`
  (`ERing`, `eRight`, `eLeft`): `H_{k^{+i}}` is free over `H_k` with basis `ξ^a`,
  `a < d_{i+1}`, and over `H_{+_i k}` with basis `ξ^a`, `a < d_i + 1`.

## Proof of freeness

`M` is generated over `R` by `ξ` (`adjoin_xB` and eqs. (5.28), (5.29), `xB_split_eq_sum`) and `ξ`
satisfies the monic relation `∑_{f ≤ b} (-ξ)^f x_{b-f} = 0` (`split_monic`), so the `ξ^a`,
`a < b`, span. The dimension count `dim M = b · dim R` (from `finrank_borelRing`) then forces
linear independence.
-/

noncomputable section

namespace Categorification.Flag

open MvPolynomial
open Finset (univ range antidiagonal)

/-! ### Generation of the Borel ring by the `x_{j,α}` -/

section Generation

variable (k : Type*) [Field k] {V : Type*} [Fintype V] {J : Type*} [Fintype J] [DecidableEq J]

omit [Fintype V] [Fintype J] [DecidableEq J] in
theorem labelInvariants_comp_of_injective {J₂ : Type*} {e : J → J₂} (he : Function.Injective e)
    (lab : V → J) : labelInvariants k (e ∘ lab) = labelInvariants k lab := by
  ext f
  simp only [mem_labelInvariants]
  refine forall_congr' fun g => ?_
  have : (e ∘ lab) ∘ ⇑g = e ∘ lab ↔ lab ∘ ⇑g = lab :=
    ⟨fun h => funext fun v => he (congrFun h v), fun h => by rw [Function.comp_assoc, h]⟩
  rw [this]

omit [DecidableEq J] in
/-- **The Young invariants are generated by the block elementary symmetric polynomials**, for any
labelling by a finite set of labels. -/
theorem labelInvariants_le_adjoin [DecidableEq J] (lab : V → J) :
    labelInvariants k lab ≤ Algebra.adjoin k
      (Set.range fun p : J × ℕ => setEsymm (k := k) (labSet lab (· = p.1)) p.2) := by
  classical
  intro f hf
  set eJ := Fintype.equivFin J
  set lab₂ : V → Fin (Fintype.card J) := eJ ∘ lab with hlab₂
  set d : Fin (Fintype.card J) → ℕ := fun j => Fintype.card {v // lab₂ v = j}
  have hc : ∀ j, Fintype.card {v // lab₂ v = j} = Fintype.card {w : Gen d // w.1 = j} :=
    fun j => (card_fibre_sigma (d := d) j).symm
  let eV : V ≃ Gen d := Equiv.ofFiberEquiv fun j => Fintype.equivOfCardEq (hc j)
  have heV : ∀ v, (eV v).1 = lab₂ v := fun v => Equiv.ofFiberEquiv_map _ v
  have hf₂ : f ∈ labelInvariants k lab₂ := by
    rw [hlab₂, labelInvariants_comp_of_injective k eJ.injective]; exact hf
  have hf₃ : rename eV f ∈ labelInvariants k (Sigma.fst : Gen d → Fin (Fintype.card J)) :=
    rename_mem_labelInvariants eV heV hf₂
  rw [← youngHom_range] at hf₃
  obtain ⟨F, hF⟩ := hf₃
  change youngHom k d F = _ at hF
  have hfeq : f = rename eV.symm (youngHom k d F) := by
    rw [hF, rename_rename]; simp
  rw [hfeq]
  have hmem : youngHom k d F ∈
      Algebra.adjoin k (Set.range fun v : Gen d => blockEsymm k d v.1 (v.2 + 1)) := by
    rw [Algebra.adjoin_range_eq_range_aeval]; exact ⟨F, rfl⟩
  have hmap := (Subalgebra.mem_map (f := rename eV.symm)).2 ⟨_, hmem, rfl⟩
  rw [AlgHom.map_adjoin] at hmap
  refine Algebra.adjoin_mono ?_ hmap
  rintro _ ⟨_, ⟨v, rfl⟩, rfl⟩
  refine ⟨(eJ.symm v.1, v.2 + 1), ?_⟩
  have h1 : ∀ w : Gen d, lab₂ (eV.symm w) = (Sigma.fst : Gen d → _) w := fun w => by
    rw [← heV, Equiv.apply_symm_apply]
  have h2 : labSet lab₂ (· = v.1) = labSet lab (· = eJ.symm v.1) := by
    ext w
    simp only [mem_labSet, hlab₂, Function.comp_apply, Equiv.eq_symm_apply]
  show setEsymm (labSet lab (· = eJ.symm v.1)) (v.2 + 1) =
    rename eV.symm.toEmbedding (blockEsymm k d v.1 (v.2 + 1))
  rw [blockEsymm_eq_setEsymm, rename_setEsymm, map_labSet eV.symm h1, h2]

omit [DecidableEq J] in
/-- **The Borel ring is generated by the classes `x_{j,α}`** (for a finite set of labels). -/
theorem adjoin_xB [DecidableEq J] (lab : V → J) :
    Algebra.adjoin k (Set.range fun p : J × ℕ => xB k lab p.1 p.2) = ⊤ := by
  rw [eq_top_iff]
  rintro z -
  obtain ⟨a, rfl⟩ := mkB_surjective lab z
  have h1 := labelInvariants_le_adjoin k lab a.2
  have h2 : a ∈ Algebra.adjoin k (Set.range fun p : J × ℕ => blockElt k lab p.1 p.2) := by
    have hmap : (Algebra.adjoin k (Set.range fun p : J × ℕ => blockElt k lab p.1 p.2)).map
        (labelInvariants k lab).val = Algebra.adjoin k
          (Set.range fun p : J × ℕ => setEsymm (k := k) (labSet lab (· = p.1)) p.2) := by
      rw [AlgHom.map_adjoin, ← Set.range_comp]
      rfl
    rw [← hmap] at h1
    obtain ⟨b, hb, hba⟩ := Subalgebra.mem_map.1 h1
    rwa [Subtype.val_injective hba] at hb
  have h3 := (Subalgebra.mem_map (f := mkB k lab)).2 ⟨a, h2, rfl⟩
  rw [AlgHom.map_adjoin, ← Set.range_comp] at h3
  exact h3

end Generation

/-! ### Dimension count -/

section Dimension

variable (k : Type*) [Field k] {V : Type*} [Fintype V] [DecidableEq V] {J : Type*}
  [Fintype J] [DecidableEq J]

omit [DecidableEq V] in
theorem card_fibre_eq_card_labSet {J' : Type*} [DecidableEq J'] (lab : V → J') (j : J') :
    Fintype.card {v // lab v = j} = (labSet lab (· = j)).card := by
  classical
  rw [Fintype.card_subtype]
  rfl

omit [DecidableEq V] in
theorem prod_image_factorial (lab : V → J) :
    ∏ j ∈ univ.image lab, (Fintype.card {v // lab v = j}).factorial =
      ∏ j, (Fintype.card {v // lab v = j}).factorial := by
  refine Finset.prod_subset (Finset.subset_univ _) fun j _ hj => ?_
  have : Fintype.card {v // lab v = j} = 0 :=
    Fintype.card_eq_zero_iff.2 ⟨fun ⟨v, hv⟩ => hj (Finset.mem_image.2 ⟨v, Finset.mem_univ _, hv⟩)⟩
  rw [this, Nat.factorial_zero]

/-- The size of the block of `v₀`. -/
abbrev blockCard {J' : Type*} [DecidableEq J'] (lab : V → J') (v₀ : V) : ℕ := (labSet lab (· = lab v₀)).card

omit [DecidableEq V] in
theorem mem_block {J' : Type*} [DecidableEq J'] (lab : V → J') (v₀ : V) : v₀ ∈ labSet lab (· = lab v₀) := by
  simp

omit [DecidableEq V] in
theorem blockCard_pos {J' : Type*} [DecidableEq J'] (lab : V → J') (v₀ : V) : 0 < blockCard lab v₀ :=
  Finset.card_pos.2 ⟨v₀, mem_block lab v₀⟩

omit [Fintype J] in
theorem card_split_some (lab : V → J) (v₀ : V) (j : J) :
    (labSet (splitLab lab v₀) (· = some j)).card =
      (labSet lab (· = j)).card - if j = lab v₀ then 1 else 0 := by
  rw [labSet_split_some]
  split_ifs with h
  · subst h
    exact Finset.card_erase_of_mem (mem_block lab v₀)
  · rw [Finset.erase_eq_of_not_mem (by simp [Ne.symm h]), Nat.sub_zero]

omit [Fintype J] in
theorem labSet_split_none (lab : V → J) (v₀ : V) :
    labSet (splitLab lab v₀) (· = none) = {v₀} := by
  ext v
  simp only [mem_labSet, Finset.mem_singleton]
  exact splitLab_eq_none

theorem prod_factorial_split (lab : V → J) (v₀ : V) :
    ∏ j, (Fintype.card {v // lab v = j}).factorial =
      blockCard lab v₀ * ∏ o, (Fintype.card {v // splitLab lab v₀ v = o}).factorial := by
  rw [Fintype.prod_option]
  simp only [card_fibre_eq_card_labSet, labSet_split_none, Finset.card_singleton,
    Nat.factorial_one, one_mul, card_split_some]
  rw [← Finset.mul_prod_erase univ _ (Finset.mem_univ (lab v₀)),
    ← Finset.mul_prod_erase univ _ (Finset.mem_univ (lab v₀)), if_pos rfl, ← mul_assoc,
    Nat.mul_factorial_pred (blockCard_pos lab v₀).ne']
  congr 1
  refine Finset.prod_congr rfl fun j hj => ?_
  rw [if_neg (Finset.ne_of_mem_erase hj), Nat.sub_zero]

set_option synthInstance.maxHeartbeats 200000 in
/-- **`dim_k H_{k^{+i}} = b · dim_k H_k`**, `b` the size of the block of `v₀`. -/
theorem finrank_split (lab : V → J) (v₀ : V) :
    Module.finrank k (BorelRing k (splitLab lab v₀)) =
      blockCard lab v₀ * Module.finrank k (BorelRing k lab) := by
  have h1 := finrank_borelRing k lab
  have h2 := finrank_borelRing k (splitLab lab v₀)
  rw [prod_image_factorial] at h1 h2
  rw [prod_factorial_split lab v₀] at h1
  have hpos : 0 < ∏ o, (Fintype.card {v // splitLab lab v₀ v = o}).factorial :=
    Finset.prod_pos fun _ _ => Nat.factorial_pos _
  refine Nat.eq_of_mul_eq_mul_right hpos ?_
  rw [h2, ← h1]
  ring

end Dimension

/-! ### The abstract Frobenius trace -/

section Trace

variable {R M : Type*} [CommRing R] [CommRing M] [Algebra R M]

theorem neg_one_pow_mul_neg_one_pow' {A : Type*} [CommRing A] {b g c : ℕ} (hb : g ≤ b)
    (hc : g ≤ c) : ((-1 : A) ^ (b - g)) * (-1) ^ (c - g) = (-1) ^ (b + c) := by
  rw [show b + c = (b - g + (c - g)) + 2 * g by omega, pow_add, pow_add, pow_mul]
  simp

/-- **The Frobenius trace.** Let `M` be free over `R` with basis `ξ^a`, `a < b`, where `ξ` satisfies
the monic relation `∑_{f ≤ b} (-ξ)^f x_{b-f} = 0`, and let `x̄` be the inverse series of `x`
(`∑_{f ≤ α} x_f x̄_{α-f} = δ_{α,0}`, `x_0 = 1`, `x_r = 0` for `r > b`). Then the coordinate of
`ξ^{b-1}` satisfies `tr(ξ^a) = (-1)^{a+1-b} x̄_{a+1-b}` for `a + 1 ≥ b` and `tr(ξ^a) = 0`
otherwise. -/
theorem trace_pow {b : ℕ} (hb : 0 < b) (B : Basis (Fin b) R M) (ξ : M)
    (hB : ∀ a, B a = ξ ^ (a : ℕ)) (x xbar : ℕ → R) (hx0 : x 0 = 1)
    (hxz : ∀ r, b < r → x r = 0)
    (hinv : ∀ α, ∑ f ∈ range (α + 1), x f * xbar (α - f) = if α = 0 then 1 else 0)
    (hrel : ∑ f ∈ range (b + 1), (-ξ) ^ f * algebraMap R M (x (b - f)) = 0) (a : ℕ) :
    B.coord ⟨b - 1, by omega⟩ (ξ ^ a) =
      if b ≤ a + 1 then (-1) ^ (a + 1 - b) * xbar (a + 1 - b) else 0 := by
  set τ : ℕ → R := fun a => B.coord ⟨b - 1, by omega⟩ (ξ ^ a) with hτ
  set T : ℕ → R := fun a => if b ≤ a + 1 then (-1) ^ (a + 1 - b) * xbar (a + 1 - b) else 0
    with hT
  have hxbar0 : xbar 0 = 1 := by simpa [hx0] using hinv 0
  -- values on the basis
  have hbase : ∀ a, a < b → τ a = T a := by
    intro a ha
    simp only [hτ, hT]
    rw [show ξ ^ a = B ⟨a, ha⟩ from (hB ⟨a, ha⟩).symm, Basis.coord_apply, Basis.repr_self,
      Finsupp.single_apply]
    by_cases h : a = b - 1
    · rw [if_pos (Fin.ext h), if_pos (by omega), show a + 1 - b = 0 by omega, pow_zero,
        one_mul, hxbar0]
    · rw [if_neg (fun h' => h (congrArg Fin.val h')), if_neg (by omega)]
  -- the recursion satisfied by `τ`
  have hrecτ : ∀ n, ∑ f ∈ range (b + 1), (-1) ^ f * x (b - f) * τ (f + n) = 0 := by
    intro n
    have h := congrArg (fun m => B.coord ⟨b - 1, by omega⟩ (m * ξ ^ n)) hrel
    simp only [zero_mul, map_zero, Finset.sum_mul, map_sum] at h
    rw [← h]
    refine Finset.sum_congr rfl fun f _ => ?_
    have : (-ξ) ^ f * algebraMap R M (x (b - f)) * ξ ^ n =
        ((-1) ^ f * x (b - f)) • ξ ^ (f + n) := by
      rw [Algebra.smul_def, neg_pow, map_mul, map_pow, map_neg, map_one, pow_add]
      ring
    rw [this, LinearMap.map_smul, smul_eq_mul]
  -- the recursion satisfied by `T`
  have hrecT : ∀ n, ∑ f ∈ range (b + 1), (-1) ^ f * x (b - f) * T (f + n) = 0 := by
    intro n
    rw [← Finset.sum_range_reflect]
    have hterm : ∀ g ∈ range (b + 1), (-1) ^ (b + 1 - 1 - g) * x (b - (b + 1 - 1 - g)) *
        T (b + 1 - 1 - g + n) =
        (-1) ^ (b + (n + 1)) * (if g ≤ n + 1 then x g * xbar (n + 1 - g) else 0) := by
      intro g hg
      have hg' : g ≤ b := Nat.lt_succ_iff.1 (Finset.mem_range.1 hg)
      simp only [hT, Nat.add_sub_cancel]
      rw [show b - (b - g) = g by omega]
      by_cases h : g ≤ n + 1
      · rw [if_pos (by omega), if_pos h, show b - g + n + 1 - b = n + 1 - g by omega]
        have := neg_one_pow_mul_neg_one_pow' (A := R) hg' h
        linear_combination (x g * xbar (n + 1 - g)) * this
      · rw [if_neg (by omega), if_neg h, mul_zero, mul_zero]
    rw [Finset.sum_congr rfl hterm, ← Finset.mul_sum]
    set G : ℕ → R := fun g => if g ≤ n + 1 then x g * xbar (n + 1 - g) else 0 with hG
    have hsum1 : ∑ g ∈ range (b + 1), G g = ∑ g ∈ range (b + n + 2), G g :=
      Finset.sum_subset (Finset.range_subset.2 (by omega)) fun g _ hg => by
        simp only [Finset.mem_range, not_lt] at hg
        simp only [hG, hxz g (by omega), zero_mul, ite_self]
    have hsum2 : ∑ g ∈ range (n + 1 + 1), x g * xbar (n + 1 - g) =
        ∑ g ∈ range (b + n + 2), G g := by
      rw [← Finset.sum_subset (Finset.range_subset.2 (show n + 1 + 1 ≤ b + n + 2 by omega))
        fun g _ hg => by
          simp only [Finset.mem_range, not_lt] at hg
          simp only [hG, if_neg (show ¬ g ≤ n + 1 by omega)]]
      exact Finset.sum_congr rfl fun g hg => by
        simp only [hG, if_pos (Nat.lt_succ_iff.1 (Finset.mem_range.1 hg))]
    rw [hsum1, ← hsum2, hinv (n + 1), if_neg (Nat.succ_ne_zero n), mul_zero]
  have key : ∀ a, τ a = T a := by
    intro a
    induction a using Nat.strong_induction_on with
    | _ a ih =>
      by_cases ha : a < b
      · exact hbase a ha
      · obtain ⟨n, rfl⟩ : ∃ n, a = b + n := ⟨a - b, by omega⟩
        have e1 := hrecτ n
        have e2 := hrecT n
        rw [Finset.sum_range_succ] at e1 e2
        have hs : ∑ f ∈ range b, (-1) ^ f * x (b - f) * τ (f + n) =
            ∑ f ∈ range b, (-1) ^ f * x (b - f) * T (f + n) :=
          Finset.sum_congr rfl fun f hf => by
            rw [ih (f + n) (by simp only [Finset.mem_range] at hf; omega)]
        rw [hs, Nat.sub_self, hx0, mul_one] at e1
        rw [Nat.sub_self, hx0, mul_one] at e2
        have h3 : (-1 : R) ^ b * τ (b + n) = (-1) ^ b * T (b + n) := by
          linear_combination e1 - e2
        exact (isUnit_one.neg.pow b).mul_left_cancel h3
  exact key a

end Trace

/-- A basis of `M` over `R` from the elementary forms of linear independence and spanning. -/
def basisOfElem {R M : Type*} [CommRing R] [CommRing M] [Algebra R M] {ι : Type*} [Fintype ι]
    (v : ι → M) (hind : ∀ c : ι → R, ∑ a, algebraMap R M (c a) * v a = 0 → c = 0)
    (hspan : ∀ m, ∃ c : ι → R, ∑ a, algebraMap R M (c a) * v a = m) : Basis ι R M :=
  Basis.mk (v := v)
    (Fintype.linearIndependent_iff.2 fun g hg i => by
      have := hind g (by simpa only [Algebra.smul_def] using hg)
      rw [this, Pi.zero_apply])
    (fun m _ => by
      obtain ⟨c, hc⟩ := hspan m
      rw [Submodule.mem_span_range_iff_exists_fun]
      exact ⟨c, by simpa only [Algebra.smul_def] using hc⟩)

theorem basisOfElem_apply {R M : Type*} [CommRing R] [CommRing M] [Algebra R M] {ι : Type*}
    [Fintype ι] (v : ι → M) (hind : ∀ c : ι → R, ∑ a, algebraMap R M (c a) * v a = 0 → c = 0)
    (hspan : ∀ m, ∃ c : ι → R, ∑ a, algebraMap R M (c a) * v a = m) (a : ι) :
    basisOfElem v hind hspan a = v a :=
  Basis.mk_apply _ _ a

/-! ### Freeness of `H_{k^{+i}}` over `H_k` -/

section Free

variable (k : Type*) [Field k] {V : Type*} [Fintype V] [DecidableEq V] {J : Type*} [Fintype J]
  [DecidableEq J]

omit [Fintype V] [DecidableEq V] in
theorem X_mem_of_singleton {J' : Type*} {S : V → J'} {v₀ : V} (hv : ∀ w, S w = S v₀ → w = v₀) :
    (X v₀ : MvPolynomial V k) ∈ labelInvariants k S := by
  intro g hg
  have : g v₀ = v₀ := hv _ (congrFun hg v₀)
  rw [rename_X, this]

/-- The class of `x_{v₀}` in the Borel ring of a labelling in which `v₀` is alone in its block. -/
def xiS {J' : Type*} (S : V → J') (v₀ : V) (hv : ∀ w, S w = S v₀ → w = v₀) : BorelRing k S :=
  mkB k S ⟨X v₀, X_mem_of_singleton k hv⟩

omit [Fintype V] [Fintype J] [DecidableEq J] in
theorem splitLab_singleton (lab : V → J) (v₀ : V) :
    ∀ w, splitLab lab v₀ w = splitLab lab v₀ v₀ → w = v₀ :=
  fun _ h => splitLab_eq_none.1 (h.trans splitLab_self)

omit [Fintype J] [DecidableEq J] in
theorem xi_eq_xiS (lab : V → J) (v₀ : V) :
    xi k lab v₀ = xiS k (splitLab lab v₀) v₀ (splitLab_singleton lab v₀) := rfl

variable {k}

omit [Fintype J] in
/-- **The monic relation** `∑_{f ≤ b} (-ξ)^f p_1^* x(k)_{j,b-f} = 0`, `j` the block of `v₀` of size
`b` (the characteristic polynomial `∏_{v ∈ block j} (t - x_v)` evaluated at `ξ = x_{v₀}`). -/
theorem split_monic (lab : V → J) (v₀ : V) :
    ∑ f ∈ range (blockCard lab v₀ + 1), (-xi k lab v₀) ^ f *
      pR k lab v₀ (xB k lab (lab v₀) (blockCard lab v₀ - f)) = 0 := by
  rw [← xB_split_eq_sum]
  apply xB_eq_zero
  rw [card_split_some, if_pos rfl]
  have := blockCard_pos lab v₀
  simp only [blockCard] at this ⊢
  omega

variable (k) in
/-- `H_{k^{+i}}` as an `H_k`-algebra via `p_1^*`. -/
def rightAlgebra (lab : V → J) (v₀ : V) :
    Algebra (BorelRing k lab) (BorelRing k (splitLab lab v₀)) :=
  (pR k lab v₀).toRingHom.toAlgebra

section Span

attribute [local instance] rightAlgebra

omit [Fintype J] [DecidableEq J] in
theorem algebraMap_right (lab : V → J) (v₀ : V) (r : BorelRing k lab) :
    algebraMap (BorelRing k lab) (BorelRing k (splitLab lab v₀)) r = pR k lab v₀ r := rfl

omit [Fintype J] [DecidableEq J] in
theorem smul_right (lab : V → J) (v₀ : V) (r : BorelRing k lab)
    (m : BorelRing k (splitLab lab v₀)) : r • m = pR k lab v₀ r * m := Algebra.smul_def r m

omit [Fintype J] in
theorem split_span_aux (lab : V → J) (v₀ : V) :
    ∃ P : Subalgebra k (BorelRing k (splitLab lab v₀)),
      (∀ m ∈ P, m ∈ Submodule.span (BorelRing k lab)
        (Set.range fun a : Fin (blockCard lab v₀) => xi k lab v₀ ^ (a : ℕ))) ∧
      xi k lab v₀ ∈ P ∧ ∀ r, pR k lab v₀ r ∈ P := by
  set b := blockCard lab v₀ with hbdef
  have hb := blockCard_pos lab v₀
  set ξ := xi k lab v₀
  set Q := Submodule.span (BorelRing k lab) (Set.range fun a : Fin b => ξ ^ (a : ℕ)) with hQ
  have hpow : ∀ a < b, ξ ^ a ∈ Q := fun a ha => Submodule.subset_span ⟨⟨a, ha⟩, rfl⟩
  have hsmul : ∀ (r : BorelRing k lab) (m), m ∈ Q → pR k lab v₀ r * m ∈ Q := fun r m hm => by
    rw [← smul_right]; exact Submodule.smul_mem _ _ hm
  -- `ξ^b ∈ Q`
  have hξb : ξ ^ b ∈ Q := by
    have hrel : ∑ f ∈ range (b + 1), (-ξ) ^ f * pR k lab v₀ (xB k lab (lab v₀) (b - f)) = 0 :=
      split_monic lab v₀
    rw [Finset.sum_range_succ, Nat.sub_self, xB_zero, map_one, mul_one,
      ← eq_neg_iff_add_eq_zero] at hrel
    have h1 : (-ξ) ^ b ∈ Q := by
      rw [show (-ξ) ^ b = -∑ f ∈ range b, (-ξ) ^ f * pR k lab v₀ (xB k lab (lab v₀) (b - f)) by
        rw [hrel, neg_neg]]
      refine Submodule.neg_mem _ (Submodule.sum_mem _ fun f hf => ?_)
      have : (-ξ) ^ f * pR k lab v₀ (xB k lab (lab v₀) (b - f)) =
          pR k lab v₀ ((-1) ^ f * xB k lab (lab v₀) (b - f)) * ξ ^ f := by
        rw [map_mul, map_pow, map_neg, map_one, neg_pow]; ring
      rw [this]
      exact hsmul _ _ (hpow f (Finset.mem_range.1 hf))
    have : ξ ^ b = pR k lab v₀ ((-1) ^ b) * (-ξ) ^ b := by
      rw [map_pow, map_neg, map_one, ← mul_pow]; simp
    rw [this]
    exact hsmul _ _ h1
  have hξ : ∀ m ∈ Q, ξ * m ∈ Q := by
    intro m hm
    induction hm using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨a, rfl⟩ := hx
      rw [← pow_succ']
      by_cases ha : (a : ℕ) + 1 < b
      · exact hpow _ ha
      · rw [show (a : ℕ) + 1 = b by omega]; exact hξb
    | zero => rw [mul_zero]; exact Submodule.zero_mem _
    | add x y _ _ hx hy => rw [mul_add]; exact Submodule.add_mem _ hx hy
    | smul r x _ hx => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hx
  have hmulpow : ∀ (n : ℕ) (m), m ∈ Q → m * ξ ^ n ∈ Q := by
    intro n
    induction n with
    | zero => intro m hm; simpa using hm
    | succ n ih => intro m hm; rw [pow_succ', mul_left_comm]; exact hξ _ (ih m hm)
  have hmul : ∀ m m', m ∈ Q → m' ∈ Q → m * m' ∈ Q := by
    intro m m' hm hm'
    induction hm' using Submodule.span_induction with
    | mem x hx => obtain ⟨a, rfl⟩ := hx; exact hmulpow _ _ hm
    | zero => rw [mul_zero]; exact Submodule.zero_mem _
    | add x y _ _ hx hy => rw [mul_add]; exact Submodule.add_mem _ hx hy
    | smul r x _ hx => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hx
  have hone : (1 : BorelRing k (splitLab lab v₀)) ∈ Q := by
    simpa using hpow 0 hb
  have hR : ∀ r, pR k lab v₀ r ∈ Q := fun r => by simpa using hsmul r 1 hone
  refine ⟨{ carrier := Q
            mul_mem' := fun {a b} ha hb => hmul a b ha hb
            add_mem' := fun {a b} ha hb => Submodule.add_mem _ ha hb
            algebraMap_mem' := fun c => by
              rw [← (pR k lab v₀).commutes c]; exact hR _ }, fun m hm => hm, ?_, hR⟩
  simpa using hξ 1 hone

theorem split_span (lab : V → J) (v₀ : V) (m : BorelRing k (splitLab lab v₀)) :
    ∃ c : Fin (blockCard lab v₀) → BorelRing k lab,
      ∑ a, pR k lab v₀ (c a) * xi k lab v₀ ^ (a : ℕ) = m := by
  obtain ⟨P, hPQ, hξ, hR⟩ := split_span_aux (k := k) lab v₀
  have htop : Algebra.adjoin k (Set.range fun p : Option J × ℕ => xB k (splitLab lab v₀) p.1 p.2)
      ≤ P := by
    rw [Algebra.adjoin_le_iff]
    rintro _ ⟨⟨o, α⟩, rfl⟩
    show xB k (splitLab lab v₀) o α ∈ P
    rcases o with _ | j
    · -- the block `{v₀}`
      rcases α with _ | _ | α
      · rw [xB_zero]; exact P.one_mem
      · have : xB k (splitLab lab v₀) none 1 = xi k lab v₀ := by
          rw [xB, xi]
          congr 1
          apply Subtype.ext
          change setEsymm (labSet (splitLab lab v₀) (· = none)) 1 = X v₀
          rw [labSet_split_none]
          simp [setEsymm, Finset.powersetCard_one]
        rw [this]; exact hξ
      · rw [xB_eq_zero (by rw [labSet_split_none, Finset.card_singleton]; omega)]
        exact P.zero_mem
    · by_cases hj : j = lab v₀
      · subst hj
        rw [xB_split_eq_sum]
        exact P.sum_mem fun f _ => P.mul_mem (P.pow_mem (P.neg_mem hξ) _) (hR _)
      · rw [← pR_xB k j hj]; exact hR _
  have hm : m ∈ P := by
    rw [adjoin_xB, top_le_iff] at htop
    rw [htop]; exact Algebra.mem_top
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun _).1 (hPQ m hm)
  exact ⟨c, by simpa only [smul_right] using hc⟩

end Span

set_option synthInstance.maxHeartbeats 200000 in
theorem split_indep (lab : V → J) (v₀ : V) (c : Fin (blockCard lab v₀) → BorelRing k lab)
    (hc : ∑ a, pR k lab v₀ (c a) * xi k lab v₀ ^ (a : ℕ) = 0) : c = 0 := by
  let ψ : (Fin (blockCard lab v₀) → BorelRing k lab) →ₗ[k] BorelRing k (splitLab lab v₀) :=
    { toFun := fun c => ∑ a, pR k lab v₀ (c a) * xi k lab v₀ ^ (a : ℕ)
      map_add' := fun c c' => by
        simp only [Pi.add_apply, map_add, add_mul, Finset.sum_add_distrib]
      map_smul' := fun t c => by
        simp only [Pi.smul_apply, map_smul, smul_mul_assoc, RingHom.id_apply, Finset.smul_sum] }
  have hsurj : Function.Surjective ψ := fun m => split_span lab v₀ m
  have hdim : Module.finrank k (Fin (blockCard lab v₀) → BorelRing k lab) =
      Module.finrank k (BorelRing k (splitLab lab v₀)) := by
    rw [Module.finrank_pi_fintype, Finset.sum_const, Finset.card_univ, Fintype.card_fin,
      smul_eq_mul, finrank_split]
  have hinj := (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hdim).2 hsurj
  exact hinj (by rw [map_zero]; exact hc)

variable (k) in
/-- **`H_{k^{+i}}` is free over `H_k`** (via `p_1^*`) with basis `1, ξ, …, ξ^{b-1}`, `b` the size of
the block of `v₀` (KL III: `k_{i+1} - k_i`). -/
def basisR (lab : V → J) (v₀ : V) :
    @Basis (Fin (blockCard lab v₀)) (BorelRing k lab) (BorelRing k (splitLab lab v₀)) _ _
      (rightAlgebra k lab v₀).toModule :=
  letI := rightAlgebra k lab v₀
  basisOfElem (fun a : Fin (blockCard lab v₀) => xi k lab v₀ ^ (a : ℕ))
    (split_indep lab v₀) (split_span lab v₀)

theorem basisR_apply (lab : V → J) (v₀ : V) (a : Fin (blockCard lab v₀)) :
    basisR k lab v₀ a = xi k lab v₀ ^ (a : ℕ) :=
  letI := rightAlgebra k lab v₀
  basisOfElem_apply _ _ _ a

/-! ### Freeness of `H_{k^{+i}}` over `H_{+_i k}` -/

omit [Fintype V] [Fintype J] [DecidableEq J] in
theorem splitLab_moveLab (lab : V → J) (v₀ : V) (j' : J) :
    splitLab lab v₀ = splitLab (moveLab lab v₀ j') v₀ := by
  funext v
  by_cases hv : v = v₀
  · subst hv; simp
  · rw [splitLab_of_ne hv, splitLab_of_ne hv, moveLab, Function.update_of_ne hv]

omit [Fintype V] [Fintype J] [DecidableEq J] in
@[simp] theorem moveLab_self (lab : V → J) (v₀ : V) (j' : J) : moveLab lab v₀ j' v₀ = j' :=
  Function.update_self _ _ _

/-- The three freeness facts, for any labelling `S` equal to `splitLab lab v₀` (used to transport
them to `pL`). -/
theorem free_core (lab : V → J) (v₀ : V) (S : V → Option J) (hS : S = splitLab lab v₀)
    (h : Refines S lab) (hv : ∀ w, S w = S v₀ → w = v₀) :
    (∀ c : Fin (blockCard lab v₀) → BorelRing k lab,
      ∑ a, refineHom k h (c a) * xiS k S v₀ hv ^ (a : ℕ) = 0 → c = 0) ∧
    (∀ m : BorelRing k S, ∃ c : Fin (blockCard lab v₀) → BorelRing k lab,
      ∑ a, refineHom k h (c a) * xiS k S v₀ hv ^ (a : ℕ) = m) ∧
    ∑ f ∈ range (blockCard lab v₀ + 1), (-xiS k S v₀ hv) ^ f *
      refineHom k h (xB k lab (lab v₀) (blockCard lab v₀ - f)) = 0 := by
  subst hS
  exact ⟨split_indep lab v₀, split_span lab v₀, split_monic lab v₀⟩

/-- The size of block `j'` after moving `v₀` into it (KL III: `k_i - k_{i-1} + 1`). -/
abbrev blockCardL (lab : V → J) (v₀ : V) (j' : J) : ℕ := (labSet (moveLab lab v₀ j') (· = j')).card

omit [Fintype J] in
theorem blockCardL_eq (lab : V → J) (v₀ : V) (j' : J) :
    blockCardL lab v₀ j' = blockCard (moveLab lab v₀ j') v₀ := by
  rw [blockCardL, blockCard, moveLab_self]

theorem free_coreL (lab : V → J) (v₀ : V) (j' : J) :
    (∀ c : Fin (blockCardL lab v₀ j') → BorelRing k (moveLab lab v₀ j'),
      ∑ a, pL k lab v₀ j' (c a) * xi k lab v₀ ^ (a : ℕ) = 0 → c = 0) ∧
    (∀ m : BorelRing k (splitLab lab v₀), ∃ c : Fin (blockCardL lab v₀ j') →
      BorelRing k (moveLab lab v₀ j'), ∑ a, pL k lab v₀ j' (c a) * xi k lab v₀ ^ (a : ℕ) = m) ∧
    ∑ f ∈ range (blockCardL lab v₀ j' + 1), (-xi k lab v₀) ^ f *
      pL k lab v₀ j' (xB k (moveLab lab v₀ j') j' (blockCardL lab v₀ j' - f)) = 0 := by
  have H := free_core (k := k) (moveLab lab v₀ j') v₀ (splitLab lab v₀)
    (splitLab_moveLab lab v₀ j') (refines_splitLab_move lab v₀ j') (splitLab_singleton lab v₀)
  rw [blockCardL_eq]
  rw [moveLab_self] at H
  exact H

variable (k) in
/-- **`H_{k^{+i}}` is free over `H_{+_i k}`** (via `p_2^*`) with basis `1, ξ, …, ξ^{b'-1}`, `b'` the
size of block `j'` after moving `v₀` into it (KL III: `k_i - k_{i-1} + 1`). -/
def basisL (lab : V → J) (v₀ : V) (j' : J) :
    @Basis (Fin (blockCardL lab v₀ j')) (BorelRing k (moveLab lab v₀ j'))
      (BorelRing k (splitLab lab v₀)) _ _ (midAlgebra k lab v₀ j').toModule :=
  letI := midAlgebra k lab v₀ j'
  basisOfElem (fun a : Fin (blockCardL lab v₀ j') => xi k lab v₀ ^ (a : ℕ))
    (free_coreL lab v₀ j').1 (free_coreL lab v₀ j').2.1

theorem basisL_apply (lab : V → J) (v₀ : V) (j' : J) (a : Fin (blockCardL lab v₀ j')) :
    basisL k lab v₀ j' a = xi k lab v₀ ^ (a : ℕ) :=
  letI := midAlgebra k lab v₀ j'
  basisOfElem_apply _ _ _ a

end Free

/-! ### The Frobenius traces -/

section Traces

variable (k : Type*) [Field k] {V : Type*} [Fintype V] [DecidableEq V] {J : Type*} [Fintype J]
  [DecidableEq J]

/-- **The Frobenius trace `tr : H_{k^{+i}} → H_k`**: the coordinate of `ξ^{b-1}` in the basis
`basisR` (`b` the size of the block of `v₀`; `ξ^{b-1}` is the class of a point in the fibre
`ℙ^{b-1}`). -/
def trR (lab : V → J) (v₀ : V) : BorelRing k (splitLab lab v₀) →+ BorelRing k lab :=
  letI := rightAlgebra k lab v₀
  ((basisR k lab v₀).coord ⟨blockCard lab v₀ - 1, by
    have := blockCard_pos lab v₀; omega⟩).toAddMonoidHom

/-- **The Frobenius trace `tr : H_{k^{+i}} → H_{+_i k}`**: the coordinate of `ξ^{b'-1}` in the
basis `basisL`. -/
def trL (lab : V → J) (v₀ : V) (j' : J) :
    BorelRing k (splitLab lab v₀) →+ BorelRing k (moveLab lab v₀ j') :=
  letI := midAlgebra k lab v₀ j'
  ((basisL k lab v₀ j').coord ⟨blockCardL lab v₀ j' - 1, by
    have : 0 < blockCardL lab v₀ j' := by
      rw [blockCardL_eq]; exact blockCard_pos _ _
    omega⟩).toAddMonoidHom

variable {k}

/-- `tr` is `H_k`-linear. -/
theorem trR_pR_mul (lab : V → J) (v₀ : V) (r : BorelRing k lab)
    (m : BorelRing k (splitLab lab v₀)) : trR k lab v₀ (pR k lab v₀ r * m) = r * trR k lab v₀ m := by
  letI := rightAlgebra k lab v₀
  change Basis.coord _ _ _ = r * Basis.coord _ _ _
  rw [← smul_right, LinearMap.map_smul, smul_eq_mul]

/-- `tr` is `H_{+_i k}`-linear. -/
theorem trL_pL_mul (lab : V → J) (v₀ : V) (j' : J) (r : BorelRing k (moveLab lab v₀ j'))
    (m : BorelRing k (splitLab lab v₀)) :
    trL k lab v₀ j' (pL k lab v₀ j' r * m) = r * trL k lab v₀ j' m := by
  letI := midAlgebra k lab v₀ j'
  change Basis.coord _ _ _ = r * Basis.coord _ _ _
  rw [← algebraMap_mid, ← Algebra.smul_def, LinearMap.map_smul, smul_eq_mul]

/-- **The trace of `ξ^a` over `H_k`** (the values of the cap of KL III Definition 6.1, eq. (6.4)):
`tr(ξ^a) = (-1)^{a+1-b} x̄(k)_{j,a+1-b}` for `a + 1 ≥ b` and `0` otherwise, where `j` is the block
of `v₀` (KL III's `i + 1`) and `b` its size (`k_{i+1} - k_i`). -/
theorem trR_xi_pow (lab : V → J) (v₀ : V) (a : ℕ) :
    trR k lab v₀ (xi k lab v₀ ^ a) = if blockCard lab v₀ ≤ a + 1 then
      (-1) ^ (a + 1 - blockCard lab v₀) * xbarB k lab (lab v₀) (a + 1 - blockCard lab v₀)
      else 0 := by
  letI := rightAlgebra k lab v₀
  exact trace_pow (blockCard_pos lab v₀) (basisR k lab v₀) (xi k lab v₀) (basisR_apply lab v₀)
    (xB k lab (lab v₀)) (xbarB k lab (lab v₀)) (xB_zero _) (fun _ hr => xB_eq_zero hr)
    (sum_xB_mul_xbarB _) (split_monic lab v₀) a

/-- **The trace of `ξ^a` over `H_{+_i k}`** (the values of the cap of KL III Definition 6.1,
eq. (6.5)): `tr(ξ^a) = (-1)^{a+1-b'} x̄(+_i k)_{j',a+1-b'}` for `a + 1 ≥ b'` and `0` otherwise,
where `j'` is the block receiving `v₀` (KL III's `i`) and `b'` its new size
(`k_i - k_{i-1} + 1`). -/
theorem trL_xi_pow (lab : V → J) (v₀ : V) (j' : J) (a : ℕ) :
    trL k lab v₀ j' (xi k lab v₀ ^ a) = if blockCardL lab v₀ j' ≤ a + 1 then
      (-1) ^ (a + 1 - blockCardL lab v₀ j') *
        xbarB k (moveLab lab v₀ j') j' (a + 1 - blockCardL lab v₀ j')
      else 0 := by
  letI := midAlgebra k lab v₀ j'
  have hb : 0 < blockCardL lab v₀ j' := by rw [blockCardL_eq]; exact blockCard_pos _ _
  exact trace_pow hb (basisL k lab v₀ j') (xi k lab v₀) (basisL_apply lab v₀ j')
    (xB k (moveLab lab v₀ j') j') (xbarB k (moveLab lab v₀ j') j') (xB_zero _)
    (fun _ hr => xB_eq_zero hr) (sum_xB_mul_xbarB _) (free_coreL lab v₀ j').2.2 a

end Traces

/-! ### Compositions -/

section Composition

variable {K : Type*} [Field K] {m : ℕ}

theorem blockCard_movedVar (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ) :
    blockCard (Sigma.fst : Gen d → Fin (m + 1)) (movedVar i d h) = d i.succ :=
  card_labSet_sigma i.succ

theorem blockCardL_movedVar (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ) :
    blockCardL (Sigma.fst : Gen d → Fin (m + 1)) (movedVar i d h) i.castSucc =
      d i.castSucc + 1 := by
  rw [blockCardL, ← card_fibre_eq_card_labSet, card_moveLab, raise, if_pos rfl]

variable (K) in
/-- `H_{k^{+i}}` as an `H_k`-algebra via `p_1^*` (`eRight`). -/
def eRightAlgebra (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ) :
    Algebra (H K d) (ERing K i d h) :=
  (eRight K i d h).toRingHom.toAlgebra

variable (K) in
/-- `H_{k^{+i}}` as an `H_{+_i k}`-algebra via `p_2^*` (`eLeft`). -/
def eLeftAlgebra (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ) :
    Algebra (H K (raise i d)) (ERing K i d h) :=
  (eLeft K i d h).toRingHom.toAlgebra

variable (K) in
/-- **KL III §5.1.1: `H_{k^{+i}}` is a free `H_k`-module with basis `1, ξ_i, …, ξ_i^{d_{i+1}-1}`**
(`d_{i+1} = k_{i+1} - k_i`), `H_k` acting through `p_1^*`. -/
def eBasisRight (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ) :
    @Basis (Fin (d i.succ)) (H K d) (ERing K i d h) _ _ (eRightAlgebra K i d h).toModule :=
  letI := eRightAlgebra K i d h
  (basisOfElem (fun a : Fin (blockCard (Sigma.fst : Gen d → Fin (m + 1)) (movedVar i d h)) =>
      eXi K i d h ^ (a : ℕ))
    (fun c hc => by
      have := split_indep (k := K) _ (movedVar i d h) (fun a => hEquiv K d (c a)) hc
      funext a
      exact (hEquiv K d).injective ((congrFun this a).trans (map_zero _).symm))
    (fun x => by
      obtain ⟨c, hc⟩ := split_span (k := K) _ (movedVar i d h) x
      refine ⟨fun a => (hEquiv K d).symm (c a), ?_⟩
      rw [← hc]
      refine Finset.sum_congr rfl fun a _ => ?_
      change pR K _ _ (hEquiv K d ((hEquiv K d).symm (c a))) * _ = _
      rw [AlgEquiv.apply_symm_apply]
      rfl)).reindex (finCongr (blockCard_movedVar i d h))

theorem eBasisRight_apply (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ)
    (a : Fin (d i.succ)) : eBasisRight K i d h a = eXi K i d h ^ (a : ℕ) := by
  letI := eRightAlgebra K i d h
  rw [eBasisRight, Basis.reindex_apply, basisOfElem_apply]
  rfl

variable (K) in
/-- **KL III §5.1.1: `H_{k^{+i}}` is a free `H_{+_i k}`-module with basis `1, ξ_i, …, ξ_i^{d_i}`**
(`d_i + 1 = k_i - k_{i-1} + 1`, the size of block `i` of `+_i k`), `H_{+_i k}` acting through
`p_2^*`. -/
def eBasisLeft (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ) :
    @Basis (Fin (d i.castSucc + 1)) (H K (raise i d)) (ERing K i d h) _ _
      (eLeftAlgebra K i d h).toModule :=
  letI := eLeftAlgebra K i d h
  (basisOfElem (fun a : Fin (blockCardL (Sigma.fst : Gen d → Fin (m + 1)) (movedVar i d h)
      i.castSucc) => eXi K i d h ^ (a : ℕ))
    (fun c hc => by
      have := (free_coreL (k := K) _ (movedVar i d h) i.castSucc).1
        (fun a => (borelEquivH' K _ (raise i d) (card_moveLab i d h)).symm (c a)) hc
      funext a
      exact (borelEquivH' K _ (raise i d) (card_moveLab i d h)).symm.injective
        ((congrFun this a).trans (map_zero _).symm))
    (fun x => by
      obtain ⟨c, hc⟩ := (free_coreL (k := K) _ (movedVar i d h) i.castSucc).2.1 x
      refine ⟨fun a => borelEquivH' K _ (raise i d) (card_moveLab i d h) (c a), ?_⟩
      rw [← hc]
      refine Finset.sum_congr rfl fun a _ => ?_
      change pL K _ _ _ ((borelEquivH' K _ (raise i d) (card_moveLab i d h)).symm
        (borelEquivH' K _ (raise i d) (card_moveLab i d h) (c a))) * _ = _
      rw [AlgEquiv.symm_apply_apply]
      rfl)).reindex (finCongr (blockCardL_movedVar i d h))

theorem eBasisLeft_apply (i : Fin m) (d : Fin (m + 1) → ℕ) (h : 0 < d i.succ)
    (a : Fin (d i.castSucc + 1)) : eBasisLeft K i d h a = eXi K i d h ^ (a : ℕ) := by
  letI := eLeftAlgebra K i d h
  rw [eBasisLeft, Basis.reindex_apply, basisOfElem_apply]
  rfl

end Composition

end Categorification.Flag

end
