/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Flag.GammaCyclic

/-!
# Curls on the path model (KL III Definition 3.1 iv), Proposition 6.3)

KL III, arXiv:0807.3250v1, Definition 3.1, item iv), first display (the curl relations;
`Categorification.KL3.Diagram.Rel.curlR`, `curlL`), the fake bubbles of eq. `eq_infinite_Grass`
(`Categorification.KL3.Diagram.cwL`, `ccwL`), and Proposition 6.3 (the `sl₂` relations hold for
`Γ_N`, by Lauda's computation, arXiv:0803.3652).

## Main results

* `stepE_ext_one` : a bimodule map out of `Γ(E_i) ⊗ Y` which commutes with the suffix is
  determined by its value at `1` (`Γ(E_i)` is generated by the images of the two outer rings,
  `eXi_eq_sub`, `mem_outerSpan`).
* `crossU_same_xiR_pow`, `crossU_same_xiL_pow` : the upward crossing of two strands of the same
  colour on powers of one dot (the divided differences `∂ x₁^g`, `∂ x₀^g`).
* **The right curl** (`curlRW_eq`): `Γ_N(curlR)` on `E_i ⊗ Y` is multiplication by
  `-∑_{f=0}^{-n} ξ^{-n-f} Ψ_f`, `n = ⟨i, λ⟩`, `Ψ_f = (-1)^f ∑_{u+v=f} x_{i+1,u} x̄_{i,v}` in the
  region `λ` to the right of the strand (`0` if `n > 0`).
* **The left curl** (`curlLW_eq`): `Γ_N(curlL)` is multiplication by `∑_{g=0}^{n} Φ_g ξ^{n-g}`,
  `Φ_g = (-1)^g ∑_{u+v=g} x_{i,u} x̄_{i+1,v}` in the region `λ` to the left (`0` if `n < 0`).

`Ψ_f` and `Φ_g` are `Γ_N` of the clockwise and counterclockwise bubbles of degree `2f`, `2g`
(real or fake); this, and the comparison with the right-hand sides `curlRHS`, `curlLHS` of
Definition 3.1, is `Categorification.KL3.Diagram.Signed.GammaFlagBubble`.
-/

noncomputable section

open scoped TensorProduct

namespace Categorification.Flag

universe u

variable {K : Type u} [Field K] {m : ℕ}


/-! ### A triangular reindexing -/

theorem sum_triangle {M : Type*} [AddCommMonoid M] (F : ℕ → ℕ → M) (d : ℕ) :
    ∑ g ∈ Finset.range (d + 1), ∑ a ∈ Finset.range g, F g a =
      ∑ a ∈ Finset.range d, ∑ f ∈ Finset.range (d - a), F (a + 1 + f) a := by
  induction d with
  | zero => simp
  | succ d ih =>
    rw [Finset.sum_range_succ, ih]
    have h1 : ∀ a ∈ Finset.range (d + 1), ∑ f ∈ Finset.range (d + 1 - a), F (a + 1 + f) a =
        ∑ f ∈ Finset.range (d - a), F (a + 1 + f) a + F (d + 1) a := by
      intro a ha
      have ha' := Finset.mem_range.1 ha
      rw [show d + 1 - a = d - a + 1 by omega, Finset.sum_range_succ,
        show a + 1 + (d - a) = d + 1 by omega]
    rw [Finset.sum_congr rfl h1, Finset.sum_add_distrib, Finset.sum_range_succ
      (fun a => ∑ f ∈ Finset.range (d - a), F (a + 1 + f) a), Nat.sub_self, Finset.sum_range_zero,
      add_zero]

/-! ### Single strands are cyclic bimodules -/

section Cyclic

variable (c : Fin m) {r s : Comp m} (h : StepR (true, c) r s)

/-- **The dot is a difference of outer elements**: `ξ = p_1^* x_{c+1,1} - p_2^* x_{c+1,1}`. -/
theorem eXi_eq_sub : (eXi K c r h.2 : ERing K c r h.2) =
    eRight K c r h.2 (x K r c.succ 1) - eLeft K c r h.2 (x K (raise c r) c.succ 1) := by
  rw [eRight_x, eLeft_x, if_pos rfl, if_neg (castSucc_ne_succ' c).symm, xB_zero, mul_one, add_zero,
    add_sub_cancel_left]

/-- `ξ` through the actions of the step bimodule. -/
theorem stepE_xi_eq :
    xiStep K (true, c) r s h =
      (stepB K (true, c) r s h).right (x K r c.succ 1) -
        (stepB K (true, c) r s h).left (x K s c.succ 1) := by
  have e1 : ((stepB K (true, c) r s h).right (x K r c.succ 1) : ERing K c r h.2) =
      eRight K c r h.2 (x K r c.succ 1) := rfl
  have e2 : ((stepB K (true, c) r s h).left (x K s c.succ 1) : ERing K c r h.2) =
      eLeft K c r h.2 (hCast K h.1.symm (x K s c.succ 1)) := rfl
  rw [e1, e2, hCast_x]
  exact eXi_eq_sub (K := K) c h

/-- The additive span of the products of outer elements. -/
def outerSpan : AddSubgroup (stepB K (true, c) r s h).T :=
  AddSubgroup.closure {z | ∃ a b, z = (stepB K (true, c) r s h).left a *
    (stepB K (true, c) r s h).right b}

theorem outerSpan_mul_left (a : H K s) (z) (hz : z ∈ outerSpan (K := K) c h) :
    (stepB K (true, c) r s h).left a * z ∈ outerSpan (K := K) c h := by
  induction hz using AddSubgroup.closure_induction with
  | mem z hz =>
    obtain ⟨a', b, rfl⟩ := hz
    exact AddSubgroup.subset_closure ⟨a * a', b, by rw [map_mul, mul_assoc]⟩
  | one => rw [mul_zero]; exact AddSubgroup.zero_mem _
  | mul z z' _ _ h1 h2 => rw [mul_add]; exact AddSubgroup.add_mem _ h1 h2
  | inv z _ h1 => rw [mul_neg]; exact AddSubgroup.neg_mem _ h1

theorem outerSpan_mul_right (b : H K r) (z) (hz : z ∈ outerSpan (K := K) c h) :
    (stepB K (true, c) r s h).right b * z ∈ outerSpan (K := K) c h := by
  induction hz using AddSubgroup.closure_induction with
  | mem z hz =>
    obtain ⟨a, b', rfl⟩ := hz
    exact AddSubgroup.subset_closure ⟨a, b * b', by rw [map_mul]; ring⟩
  | one => rw [mul_zero]; exact AddSubgroup.zero_mem _
  | mul z z' _ _ h1 h2 => rw [mul_add]; exact AddSubgroup.add_mem _ h1 h2
  | inv z _ h1 => rw [mul_neg]; exact AddSubgroup.neg_mem _ h1

/-- **`Γ(E_c)` is generated by its two outer rings**: every element is a sum of products
`p_2^* a · p_1^* b`. -/
theorem mem_outerSpan (z : (stepB K (true, c) r s h).T) : z ∈ outerSpan (K := K) c h := by
  obtain ⟨n, co, rfl⟩ := stepE_spanned (K := K) c h z
  refine AddSubgroup.sum_mem _ fun a _ => outerSpan_mul_right c h _ _ ?_
  have hξ : ∀ z ∈ outerSpan (K := K) c h,
      xiStep K (true, c) r s h * z ∈ outerSpan (K := K) c h := by
    intro z hz
    rw [stepE_xi_eq c h, sub_mul]
    exact AddSubgroup.sub_mem _ (outerSpan_mul_right c h _ _ hz) (outerSpan_mul_left c h _ _ hz)
  induction (a : ℕ) with
  | zero =>
    rw [pow_zero]
    exact AddSubgroup.subset_closure ⟨1, 1, by rw [map_one, map_one, one_mul]⟩
  | succ k ih =>
    rw [pow_succ']
    exact hξ _ ih

/-- **Maps out of `Γ(E_c) ⊗ Y` commuting with the suffix are determined by their value at `1`.** -/
theorem stepE_ext_one {E : Type u} [CommRing E] {Y : BRing (H K r) E} {N : BRing (H K s) E}
    (φ ψ : BHom ((stepB K (true, c) r s h).tensor Y) N) (u : Y.T → N.T)
    (hφ : ∀ w z, φ (BRing.tmul _ _ 1 w * z) = u w * φ z)
    (hψ : ∀ w z, ψ (BRing.tmul _ _ 1 w * z) = u w * ψ z) (h1 : φ 1 = ψ 1) : φ = ψ := by
  refine BHom.ext_tensor fun e y => ?_
  have key : ∀ e ∈ outerSpan (K := K) c h, φ (BRing.tmul _ Y e y) = ψ (BRing.tmul _ Y e y) := by
    intro e he
    induction he using AddSubgroup.closure_induction with
    | mem z hz =>
      obtain ⟨a, b, rfl⟩ := hz
      have e1 : BRing.tmul (stepB K (true, c) r s h) Y ((stepB K (true, c) r s h).left a *
          (stepB K (true, c) r s h).right b) y =
          ((stepB K (true, c) r s h).tensor Y).left a * (BRing.tmul _ _ 1 (Y.left b * y) * 1) := by
        rw [mul_one, BRing.tensor_left, ← BRing.tmul_balance, mul_one, BRing.tmul_mul_tmul,
          one_mul]
      rw [e1, BHom.map_left, BHom.map_left, hφ, hψ, h1]
    | one => rw [BRing.zero_tmul, BHom.map_zero, BHom.map_zero]
    | mul z z' _ _ h1 h2 => rw [BRing.add_tmul, BHom.map_add, BHom.map_add, h1, h2]
    | inv z _ h1 => rw [BRing.neg_tmul, BHom.map_neg, BHom.map_neg, h1]
  exact key e (mem_outerSpan c h e)

end Cyclic

/-! ### The upward crossing of equal colours on powers of the right dot -/

section SameColour

variable (c : Fin m) {t r₁ r₂ r₁' : Comp m} (h₁ : StepR (true, c) r₁ t)
  (h₂ : StepR (true, c) r₂ r₁) (h₁' : StepR (true, c) r₁' t) (h₂' : StepR (true, c) r₂ r₁')

theorem tauU_same_xiR_pow (g : ℕ) :
    tauU K c c h₁ h₂ h₁' h₂' (BRing.tmul _ _ 1 (eXi K c r₂ h₂.2 ^ g)) =
      BRing.tmul _ _ 1 (eXi K c r₂ h₂'.2 ^ g) := by
  induction g with
  | zero =>
    simp only [pow_zero]
    rw [← BRing.one_eq, ← BRing.one_eq, tauU_one, if_pos rfl]
  | succ g ih =>
    have := BHom.congr_apply (tauU_xiR (K := K) c c h₁ h₂ h₁' h₂')
      (BRing.tmul _ _ 1 (eXi K c r₂ h₂.2 ^ g))
    rw [BHom.comp_apply, BHom.comp_apply, BHom.mulB_apply, BHom.mulB_apply, BRing.tmul_mul_tmul,
      one_mul, ih, BRing.tmul_mul_tmul, one_mul] at this
    rw [pow_succ', this, ← pow_succ']

/-- For equal colours, `ψ(1 ⊗ ξ^g) = -∑_{a < g} ξ'^a ⊗ ξ'^{g-1-a}` (the divided difference
`∂_{x₀x₁} x₁^g`). -/
theorem crossU_same_xiR_pow (g : ℕ) :
    crossU K c c h₁ h₂ h₁' h₂' (BRing.tmul _ _ 1 (eXi K c r₂ h₂.2 ^ g)) =
      -∑ a ∈ Finset.range g, BRing.tmul (stepB K (true, c) r₁' t h₁') (stepB K (true, c) r₂ r₁' h₂')
        (eXi K c r₁' h₁'.2 ^ a) (eXi K c r₂ h₂'.2 ^ (g - 1 - a)) := by
  induction g with
  | zero =>
    rw [pow_zero, ← BRing.one_eq, crossU_one, if_pos rfl, Finset.sum_range_zero, neg_zero]
  | succ g ih =>
    have := BHom.congr_apply (crossU_xiR (K := K) c c h₁ h₂ h₁' h₂')
      (BRing.tmul _ _ 1 (eXi K c r₂ h₂.2 ^ g))
    rw [BHom.comp_apply, BHom.sub_apply, BHom.comp_apply, BHom.mulB_apply, BHom.mulB_apply,
      BRing.tmul_mul_tmul, one_mul, ih, tauU_same_xiR_pow c h₁ h₂ h₁' h₂' g, ← pow_succ'] at this
    rw [this, Finset.sum_range_succ', mul_neg, Finset.mul_sum, neg_add, sub_eq_add_neg]
    congr 2
    · refine Finset.sum_congr rfl fun a ha => ?_
      rw [BRing.tmul_mul_tmul, one_mul, ← pow_succ', show g + 1 - 1 - (a + 1) = g - 1 - a by omega]

end SameColour

/-! ### The upward crossing of equal colours on powers of the left dot -/

section SameColourL

variable (c : Fin m) {t r₁ r₂ r₁' : Comp m} (h₁ : StepR (true, c) r₁ t)
  (h₂ : StepR (true, c) r₂ r₁) (h₁' : StepR (true, c) r₁' t) (h₂' : StepR (true, c) r₂ r₁')

theorem tauU_same_xiL_pow (g : ℕ) :
    tauU K c c h₁ h₂ h₁' h₂' (BRing.tmul _ _ (eXi K c r₁ h₁.2 ^ g) 1) =
      BRing.tmul _ _ (eXi K c r₁' h₁'.2 ^ g) 1 := by
  induction g with
  | zero =>
    simp only [pow_zero]
    rw [← BRing.one_eq, ← BRing.one_eq, tauU_one, if_pos rfl]
  | succ g ih =>
    have := BHom.congr_apply (tauU_xiL (K := K) c c h₁ h₂ h₁' h₂')
      (BRing.tmul _ _ (eXi K c r₁ h₁.2 ^ g) 1)
    rw [BHom.comp_apply, BHom.comp_apply, BHom.mulB_apply, BHom.mulB_apply, BRing.tmul_mul_tmul,
      mul_one, ih, BRing.tmul_mul_tmul, mul_one] at this
    rw [pow_succ', this, ← pow_succ']

/-- For equal colours, `ψ(ξ^g ⊗ 1) = ∑_{a < g} ξ'^a ⊗ ξ'^{g-1-a}` (the divided difference
`∂_{x₀x₁} x₀^g`). -/
theorem crossU_same_xiL_pow (g : ℕ) :
    crossU K c c h₁ h₂ h₁' h₂' (BRing.tmul _ _ (eXi K c r₁ h₁.2 ^ g) 1) =
      ∑ a ∈ Finset.range g, BRing.tmul (stepB K (true, c) r₁' t h₁') (stepB K (true, c) r₂ r₁' h₂')
        (eXi K c r₁' h₁'.2 ^ a) (eXi K c r₂ h₂'.2 ^ (g - 1 - a)) := by
  induction g with
  | zero =>
    rw [pow_zero, ← BRing.one_eq, crossU_one, if_pos rfl, Finset.sum_range_zero]
  | succ g ih =>
    have := BHom.congr_apply (crossU_xiL (K := K) c c h₁ h₂ h₁' h₂')
      (BRing.tmul _ _ (eXi K c r₁ h₁.2 ^ g) 1)
    rw [BHom.comp_apply, BHom.add_apply, BHom.comp_apply, BHom.mulB_apply, BHom.mulB_apply,
      BRing.tmul_mul_tmul, mul_one, ih, tauU_same_xiL_pow c h₁ h₂ h₁' h₂' g, ← pow_succ'] at this
    rw [this, Finset.sum_range_succ, Finset.mul_sum]
    refine (add_comm _ _).trans ?_
    congr 1
    · refine Finset.sum_congr rfl fun a ha => ?_
      have ha' := Finset.mem_range.1 ha
      rw [BRing.tmul_mul_tmul, one_mul, ← pow_succ', show g + 1 - 1 - a = g - 1 - a + 1 by omega]
    · rw [Nat.add_sub_cancel, Nat.sub_self, pow_zero]

end SameColourL

/-! ### The right curl -/

section CurlR

variable (i : Fin m) {q r s : Comp m} (h : StepR (true, i) r s) (hq : StepR (true, i) q r)
  {E : Type u} [CommRing E] (Y : BRing (H K r) E)

variable (K) in
/-- **`Γ_N` of the right curl** `curlR i λ` (KL III Definition 3.1 iv); `Categorification.KL3.
Diagram.curlR`), on `E_i ⊗ Y`, `λ = r` the region to the right of `E_i`: the cup `1 → E_i F_i`
on the right, the upward crossing of the two `E_i`, the cap `E_i F_i → 1` on the right. -/
def curlRW : BHom ((stepB K (true, i) r s h).tensor Y) ((stepB K (true, i) r s h).tensor Y) :=
  (BHom.whiskerLeft (stepB K (true, i) r s h) (capEFW K i hq (hq : StepR (false, i) r q) Y)).comp
  ((locTwo (crossU K i i h hq h hq) ((stepB K (false, i) r q hq).tensor Y)).comp
    (BHom.whiskerLeft (stepB K (true, i) r s h) (cupEFW K i hq (hq : StepR (false, i) r q) Y)))

/-- `curlR` commutes with the suffix. -/
theorem curlRW_mul (w : Y.T) (z) :
    curlRW K i h hq Y (BRing.tmul (stepB K (true, i) r s h) Y 1 w * z) =
      BRing.tmul (stepB K (true, i) r s h) Y 1 w * curlRW K i h hq Y z := by
  simp only [curlRW, BHom.comp_apply]
  rw [whiskerLeft_mul_right _ _ _ _ (cupEFW_mul i _ _ Y w), locTwo_mul_suffix' _ _ _,
    whiskerLeft_mul_right _ _ _ _ (capEFW_mul i _ _ Y w)]

/-- The coefficients of `curlR(1 ⊗ y)`. -/
def curlCoeff (a : ℕ) : H K r :=
  ∑ f ∈ Finset.range (dEF i hq - a), (-1) ^ (dEF i hq - a - 1 - f) *
    x K r i.succ (dEF i hq - a - 1 - f) *
      capEFP K i hq (hq : StepR (false, i) r q) (BRing.tmul _ _ (eXi K i q hq.2 ^ f) 1)

/-- **The right curl at `1 ⊗ y`**: `curlR(1 ⊗ y) = -∑_{a < d} ξ^a ⊗ C_a y` (`curlCoeff`). -/
theorem curlRW_one (y : Y.T) :
    curlRW K i h hq Y (BRing.tmul _ _ 1 y) =
      -∑ a ∈ Finset.range (dEF i hq), BRing.tmul (stepB K (true, i) r s h) Y (eXi K i r h.2 ^ a)
        (Y.left (curlCoeff i hq a) * y) := by
  simp only [curlRW, BHom.comp_apply, BHom.whiskerLeft_tmul]
  rw [cupEFW_apply'' i _ _ Y y, BRing.tmul_sum, BHom.map_sum, BHom.map_sum]
  have hterm : ∀ g, BHom.whiskerLeft (stepB K (true, i) r s h)
      (capEFW K i hq (hq : StepR (false, i) r q) Y)
      (locTwo (crossU K i i h hq h hq) ((stepB K (false, i) r q hq).tensor Y)
        (BRing.tmul (stepB K (true, i) r s h) _ 1 ((-1) ^ (dEF i hq - g) *
          BRing.tmul (stepB K (true, i) q r hq) ((stepB K (false, i) r q hq).tensor Y)
            (eXi K i q hq.2 ^ g) (BRing.tmul (stepB K (false, i) r q hq) Y 1
              (Y.left (x K r i.succ (dEF i hq - g)) * y))))) =
      (-1) ^ (dEF i hq - g) * -∑ a ∈ Finset.range g,
        BRing.tmul (stepB K (true, i) r s h) Y (eXi K i r h.2 ^ a)
          (Y.left (capEFP K i hq (hq : StepR (false, i) r q)
            (BRing.tmul _ _ (eXi K i q hq.2 ^ (g - 1 - a)) 1)) *
              (Y.left (x K r i.succ (dEF i hq - g)) * y)) := by
    intro g
    rw [tmul_neg_one_pow_mul, BHom.map_neg_one_pow_mul, BHom.map_neg_one_pow_mul, locTwo_tmul,
      crossU_same_xiR_pow, BRing.neg_tmul, BHom.map_neg, BHom.map_neg, BRing.sum_tmul,
      BHom.map_sum, BHom.map_sum]
    congr 2
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [BRing.assoc_hom_tmul, BHom.whiskerLeft_tmul, capEFW_tmul]
  rw [Finset.sum_congr rfl fun g _ => hterm g]
  have e1 : ∀ g, (-1) ^ (dEF i hq - g) * -∑ a ∈ Finset.range g,
      BRing.tmul (stepB K (true, i) r s h) Y (eXi K i r h.2 ^ a)
        (Y.left (capEFP K i hq (hq : StepR (false, i) r q)
          (BRing.tmul _ _ (eXi K i q hq.2 ^ (g - 1 - a)) 1)) *
            (Y.left (x K r i.succ (dEF i hq - g)) * y)) =
      -∑ a ∈ Finset.range g, BRing.tmul (stepB K (true, i) r s h) Y (eXi K i r h.2 ^ a)
        (Y.left ((-1) ^ (dEF i hq - g) * x K r i.succ (dEF i hq - g) *
          capEFP K i hq (hq : StepR (false, i) r q)
            (BRing.tmul _ _ (eXi K i q hq.2 ^ (g - 1 - a)) 1)) * y) := by
    intro g
    rw [mul_neg, Finset.mul_sum]
    congr 1
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [← tmul_neg_one_pow_mul]
    congr 1
    rw [map_mul, map_mul, map_pow, map_neg, map_one]
    ring
  rw [Finset.sum_congr rfl fun g _ => e1 g, Finset.sum_neg_distrib, sum_triangle]
  congr 1
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [curlCoeff, map_sum, Finset.sum_mul, BRing.tmul_sum]
  refine Finset.sum_congr rfl fun f _ => ?_
  rw [show dEF i hq - (a + 1 + f) = dEF i hq - a - 1 - f by omega,
    show a + 1 + f - 1 - a = f by omega]

/-- **The coefficients of the curl are clockwise bubbles**: for `a < d`,
`C_a = Ψ_{r_{i+1} - r_i - a} = (-1)^N ∑_{u+v=N} x_{i+1,u} x̄_{i,v}` if `r_i + a ≤ r_{i+1}`, and `0`
otherwise (`r` the region to the right of the strand). -/
theorem curlCoeff_eq (a : ℕ) (ha : a < dEF i hq) :
    curlCoeff i hq a = if r i.castSucc + a ≤ r i.succ then
      bubbleSeq (x K r i.succ) (xbar K r i.castSucc) (r i.succ - r i.castSucc - a) else 0 := by
  have hd : dEF i hq = r i.succ := by rw [dEF_eq, ← hq.1, raise_succ]
  have hqi : q i.castSucc + 1 = r i.castSucc := by rw [← hq.1, raise_castSucc]
  set d' := dEF i hq - a - 1 with hd'
  have hrange : dEF i hq - a = d' + 1 := by omega
  let x' : ℕ → H K r := fun β => if β ≤ d' then x K r i.succ β else 0
  have key := conv_trace_sum x' (xbar K r i.castSucc) (q i.castSucc + 1) d' 0
    (fun β hβ => by simp only [x', if_neg (show ¬ β ≤ d' by omega)])
  unfold curlCoeff
  rw [hrange]
  have hterm : ∀ f ∈ Finset.range (d' + 1), (-1) ^ (d' + 1 - 1 - f) * x K r i.succ (d' + 1 - 1 - f) *
      capEFP K i hq (hq : StepR (false, i) r q) (BRing.tmul _ _ (eXi K i q hq.2 ^ f) 1) =
      (-1) ^ (d' - f) * x' (d' - f) * (if q i.castSucc + 1 ≤ 0 + f + 1 then
        (-1) ^ (0 + f + 1 - (q i.castSucc + 1)) * xbar K r i.castSucc (0 + f + 1 - (q i.castSucc + 1))
        else 0) := by
    intro f hf
    have hf' := Finset.mem_range.1 hf
    rw [capEFP_xi_pow_one i hq, Nat.add_sub_cancel, zero_add]
    simp only [x', if_pos (show d' - f ≤ d' by omega)]
  rw [Finset.sum_congr rfl hterm, key, zero_add]
  by_cases hc : r i.castSucc + a ≤ r i.succ
  · rw [if_pos (by omega), if_pos hc, bubbleSeq, show d' + 1 - (q i.castSucc + 1) =
      r i.succ - r i.castSucc - a by omega]
    congr 1
    refine Finset.sum_congr rfl fun p hp => ?_
    have := Finset.antidiagonal.fst_le hp
    simp only [x', if_pos (show p.1 ≤ d' by omega)]
  · rw [if_neg (by omega), if_neg hc]

/-- **KL III Definition 3.1 iv), right curl, on the path model** (Proposition 6.3): for the
region `r` to the right of `E_i` (`n = ⟨i, λ⟩ = r_i - r_{i+1}`), `Γ_N(curlR)` is multiplication by
`-∑_{f=0}^{-n} ξ^{-n-f} ⊗ Ψ_f`, i.e. `-∑_f (E_i with -n - f dots) · Ψ_f`, where
`Ψ_f = (-1)^f ∑_{u+v=f} x_{i+1,u} x̄_{i,v}` is `Γ_N` of the clockwise bubble of degree `2f` in the
region `r` (real or fake, `Categorification.KL3.Diagram.Signed.cwLH_eq`), acting on the right of
`E_i`; the sum is empty (and the curl is `0`) if `n > 0`. -/
theorem curlRW_eq :
    curlRW K i h hq Y = if r i.castSucc ≤ r i.succ then
      BHom.mulB (-∑ f ∈ Finset.range (r i.succ - r i.castSucc + 1),
        BRing.tmul (stepB K (true, i) r s h) Y (eXi K i r h.2 ^ (r i.succ - r i.castSucc - f))
          (Y.left (bubbleSeq (x K r i.succ) (xbar K r i.castSucc) f)))
      else 0 := by
  have hd : dEF i hq = r i.succ := by rw [dEF_eq, ← hq.1, raise_succ]
  have hqi : q i.castSucc + 1 = r i.castSucc := by rw [← hq.1, raise_castSucc]
  refine stepE_ext_one i h _ _ (fun w => BRing.tmul _ _ 1 w) (curlRW_mul i h hq Y) (fun w z => ?_)
    ?_
  · split_ifs
    · rw [BHom.mulB_apply, BHom.mulB_apply, mul_left_comm]
    · rw [BHom.zero_apply, BHom.zero_apply, mul_zero]
  · rw [BRing.one_eq, curlRW_one]
    split_ifs with hc
    · rw [BHom.mulB_apply, ← BRing.one_eq, mul_one]
      congr 1
      conv_rhs => rw [← Finset.sum_range_reflect]
      have hsub : Finset.range (r i.succ - r i.castSucc + 1) ⊆ Finset.range (dEF i hq) :=
        Finset.range_subset.2 (by omega)
      rw [← Finset.sum_subset hsub (fun a ha hna => by
        have h1 := Finset.mem_range.1 ha
        have h2 : ¬ a < r i.succ - r i.castSucc + 1 := fun h' => hna (Finset.mem_range.2 h')
        rw [curlCoeff_eq i hq a h1, if_neg (by omega), map_zero, zero_mul, BRing.tmul_zero])]
      refine Finset.sum_congr rfl fun a ha => ?_
      have ha' := Finset.mem_range.1 ha
      rw [curlCoeff_eq i hq a (by omega), if_pos (by omega), mul_one,
        show r i.succ - r i.castSucc - (r i.succ - r i.castSucc + 1 - 1 - a) = a by omega,
        show r i.succ - r i.castSucc + 1 - 1 - a = r i.succ - r i.castSucc - a by omega]
    · rw [BHom.zero_apply, ← neg_zero]
      congr 1
      refine Finset.sum_eq_zero fun a ha => ?_
      rw [curlCoeff_eq i hq a (Finset.mem_range.1 ha), if_neg (by omega), map_zero, zero_mul,
        BRing.tmul_zero]

end CurlR

/-! ### The left curl -/

section CurlL

variable (i : Fin m) {r s s' : Comp m} (h : StepR (true, i) r s) (hs : StepR (true, i) s s')
  {E : Type u} [CommRing E] (Y : BRing (H K r) E)

variable (K) in
/-- **`Γ_N` of the left curl** `curlL i μ` (KL III Definition 3.1 iv);
`Categorification.KL3.Diagram.curlL`), on `E_i ⊗ Y`, `λ = s` the region to the left of `E_i`:
the cup `1 → F_i E_i` on the left, the upward crossing of the two `E_i`, the cap `F_i E_i → 1`
on the left. -/
def curlLW : BHom ((stepB K (true, i) r s h).tensor Y) ((stepB K (true, i) r s h).tensor Y) :=
  (capFEW K i hs (hs : StepR (false, i) s' s) ((stepB K (true, i) r s h).tensor Y)).comp
  ((BHom.whiskerLeft (stepB K (false, i) s' s hs) (locTwo (crossU K i i hs h hs h) Y)).comp
    (cupFEW K i hs (hs : StepR (false, i) s' s) ((stepB K (true, i) r s h).tensor Y)))

/-- `curlL` commutes with the suffix. -/
theorem curlLW_mul (w : Y.T) (z) :
    curlLW K i h hs Y (BRing.tmul (stepB K (true, i) r s h) Y 1 w * z) =
      BRing.tmul (stepB K (true, i) r s h) Y 1 w * curlLW K i h hs Y z := by
  simp only [curlLW, BHom.comp_apply]
  rw [cupFEW_mul, whiskerLeft_mul_right _ _ _ _ (locTwo_mul_suffix' _ _ _), capFEW_mul]

/-- The coefficients of `curlL(1 ⊗ y)`. -/
def curlLCoeff (b : ℕ) : H K s :=
  ∑ f ∈ Finset.range (dFE i hs - b), (-1) ^ (dFE i hs - b - 1 - f) *
    x K s i.castSucc (dFE i hs - b - 1 - f) *
      capFEP K i hs (hs : StepR (false, i) s' s) (BRing.tmul _ _ 1 (eXi K i s hs.2 ^ f))

/-- **The left curl at `1 ⊗ y`**: `curlL(1 ⊗ y) = ∑_{b < d} C_b ξ^b ⊗ y` (`curlLCoeff`). -/
theorem curlLW_one (y : Y.T) :
    curlLW K i h hs Y (BRing.tmul _ _ 1 y) =
      ∑ b ∈ Finset.range (dFE i hs), BRing.tmul (stepB K (true, i) r s h) Y
        ((stepB K (true, i) r s h).left (curlLCoeff i hs b) * xiStep K (true, i) r s h ^ b) y := by
  simp only [curlLW, BHom.comp_apply]
  rw [cupFEW_apply', BHom.map_sum, BHom.map_sum]
  have hterm : ∀ g, capFEW K i hs (hs : StepR (false, i) s' s) ((stepB K (true, i) r s h).tensor Y)
      (BHom.whiskerLeft (stepB K (false, i) s' s hs) (locTwo (crossU K i i hs h hs h) Y)
        (BRing.tmul (stepB K (false, i) s' s hs) _
          ((-1) ^ (dFE i hs - g) * xsFE i hs (dFE i hs - g) : ERing K i s hs.2)
          (BRing.tmul (stepB K (true, i) s s' hs) _ (eXi K i s hs.2 ^ g)
            (BRing.tmul (stepB K (true, i) r s h) Y 1 y)))) =
      ∑ a ∈ Finset.range g, BRing.tmul (stepB K (true, i) r s h) Y
        ((stepB K (true, i) r s h).left ((-1) ^ (dFE i hs - g) * x K s i.castSucc (dFE i hs - g) *
          capFEP K i hs (hs : StepR (false, i) s' s) (BRing.tmul _ _ 1 (eXi K i s hs.2 ^ a))) *
            xiStep K (true, i) r s h ^ (g - 1 - a)) y := by
    intro g
    rw [BHom.whiskerLeft_tmul, locTwo_tmul, crossU_same_xiL_pow, BRing.sum_tmul, BHom.map_sum,
      BRing.tmul_sum, BHom.map_sum]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [BRing.assoc_hom_tmul, capFEW_tmul, BRing.tensor_left, BRing.tmul_mul_tmul, one_mul]
    congr 2
    rw [← capFEP_left, BRing.tensor_left, BRing.tmul_mul_tmul, mul_one, one_mul, map_mul,
      map_pow, map_neg, map_one, Fst_left_x i hs hs]
  rw [Finset.sum_congr rfl fun g _ => hterm g]
  rw [Finset.sum_congr rfl fun g _ => (Finset.sum_range_reflect _ g).symm, sum_triangle]
  refine Finset.sum_congr rfl fun b _ => ?_
  rw [curlLCoeff, map_sum, Finset.sum_mul, BRing.sum_tmul]
  refine Finset.sum_congr rfl fun f _ => ?_
  rw [show b + 1 + f - 1 - (b + 1 + f - 1 - b) = b by omega,
    show b + 1 + f - 1 - b = f by omega, show dFE i hs - (b + 1 + f) = dFE i hs - b - 1 - f by omega]

/-- **The coefficients of the left curl are counterclockwise bubbles**: for `b < d`,
`C_b = Φ_{s_i - s_{i+1} - b} = (-1)^N ∑_{u+v=N} x_{i,u} x̄_{i+1,v}` if `s_{i+1} + b ≤ s_i`, and `0`
otherwise (`s` the region to the left of the strand). -/
theorem curlLCoeff_eq (b : ℕ) (hb : b < dFE i hs) :
    curlLCoeff i hs b = if s i.succ + b ≤ s i.castSucc then
      bubbleSeq (x K s i.castSucc) (xbar K s i.succ) (s i.castSucc - s i.succ - b) else 0 := by
  have hd : dFE i hs = s i.castSucc := dFE_eq i hs
  have hs1 := hs.2
  set d' := dFE i hs - b - 1 with hd'
  have hrange : dFE i hs - b = d' + 1 := by omega
  let x' : ℕ → H K s := fun β => if β ≤ d' then x K s i.castSucc β else 0
  have key := conv_trace_sum x' (xbar K s i.succ) (s i.succ) d' 0
    (fun β hβ => by simp only [x', if_neg (show ¬ β ≤ d' by omega)])
  unfold curlLCoeff
  rw [hrange]
  have hterm : ∀ f ∈ Finset.range (d' + 1), (-1) ^ (d' + 1 - 1 - f) * x K s i.castSucc (d' + 1 - 1 - f) *
      capFEP K i hs (hs : StepR (false, i) s' s) (BRing.tmul _ _ 1 (eXi K i s hs.2 ^ f)) =
      (-1) ^ (d' - f) * x' (d' - f) * (if s i.succ ≤ 0 + f + 1 then
        (-1) ^ (0 + f + 1 - s i.succ) * xbar K s i.succ (0 + f + 1 - s i.succ) else 0) := by
    intro f hf
    have hf' := Finset.mem_range.1 hf
    rw [capFEP_one_xi_pow i hs, Nat.add_sub_cancel, zero_add]
    simp only [x', if_pos (show d' - f ≤ d' by omega)]
  rw [Finset.sum_congr rfl hterm, key, zero_add]
  by_cases hc : s i.succ + b ≤ s i.castSucc
  · rw [if_pos (by omega), if_pos hc, bubbleSeq, show d' + 1 - s i.succ =
      s i.castSucc - s i.succ - b by omega]
    congr 1
    refine Finset.sum_congr rfl fun p hp => ?_
    have := Finset.antidiagonal.fst_le hp
    simp only [x', if_pos (show p.1 ≤ d' by omega)]
  · rw [if_neg (by omega), if_neg hc]

/-- **KL III Definition 3.1 iv), left curl, on the path model** (Proposition 6.3): for the region
`s` to the left of `E_i` (`n = ⟨i, λ⟩ = s_i - s_{i+1}`), `Γ_N(curlL)` is multiplication by
`∑_{g=0}^{n} Φ_g ξ^{n-g} ⊗ 1`, i.e. `∑_g Φ_g · (E_i with n - g dots)`, where
`Φ_g = (-1)^g ∑_{u+v=g} x_{i,u} x̄_{i+1,v}` is `Γ_N` of the counterclockwise bubble of degree
`2g` in the region `s` (real or fake), acting on the left of `E_i`; the curl is `0` if `n < 0`. -/
theorem curlLW_eq :
    curlLW K i h hs Y = if s i.succ ≤ s i.castSucc then
      BHom.mulB (∑ g ∈ Finset.range (s i.castSucc - s i.succ + 1),
        BRing.tmul (stepB K (true, i) r s h) Y
          ((stepB K (true, i) r s h).left (bubbleSeq (x K s i.castSucc) (xbar K s i.succ) g) *
            xiStep K (true, i) r s h ^ (s i.castSucc - s i.succ - g)) 1)
      else 0 := by
  have hd : dFE i hs = s i.castSucc := dFE_eq i hs
  have hs1 := hs.2
  refine stepE_ext_one i h _ _ (fun w => BRing.tmul _ _ 1 w) (curlLW_mul i h hs Y) (fun w z => ?_)
    ?_
  · split_ifs
    · rw [BHom.mulB_apply, BHom.mulB_apply, mul_left_comm]
    · rw [BHom.zero_apply, BHom.zero_apply, mul_zero]
  · rw [BRing.one_eq, curlLW_one]
    split_ifs with hc
    · rw [BHom.mulB_apply, ← BRing.one_eq, mul_one]
      conv_rhs => rw [← Finset.sum_range_reflect]
      have hsub : Finset.range (s i.castSucc - s i.succ + 1) ⊆ Finset.range (dFE i hs) :=
        Finset.range_subset.2 (by omega)
      rw [← Finset.sum_subset hsub (fun a ha hna => by
        have h1 := Finset.mem_range.1 ha
        have h2 : ¬ a < s i.castSucc - s i.succ + 1 := fun h' => hna (Finset.mem_range.2 h')
        rw [curlLCoeff_eq i hs a h1, if_neg (by omega), map_zero, zero_mul, BRing.zero_tmul])]
      refine Finset.sum_congr rfl fun a ha => ?_
      have ha' := Finset.mem_range.1 ha
      rw [curlLCoeff_eq i hs a (by omega), if_pos (by omega),
        show s i.castSucc - s i.succ - (s i.castSucc - s i.succ + 1 - 1 - a) = a by omega,
        show s i.castSucc - s i.succ + 1 - 1 - a = s i.castSucc - s i.succ - a by omega]
    · rw [BHom.zero_apply]
      refine Finset.sum_eq_zero fun a ha => ?_
      rw [curlLCoeff_eq i hs a (Finset.mem_range.1 ha), if_neg (by omega), map_zero, zero_mul,
        BRing.zero_tmul]

end CurlL

end Categorification.Flag

end
