/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.QuantumGroup.Radical

/-!
# Quantum integers, divided powers and the integral form `_𝒜 f`

Lusztig, *Introduction to quantum groups*, 1.3.1 (quantum integers and factorials) and
1.4.7 (divided powers `θ_i^{(a)} = θ_i^a / [a]_i^!` and the `𝒜 = ℤ[v, v⁻¹]`-form `_𝒜 f`);
Khovanov–Lauda, arXiv:0803.4121v2, §1 and §3.1 ("Define `_𝒜 f` as the `ℤ[q,q⁻¹]`-subalgebra
generated by the divided powers `θ_i^{(a)}`").

## Main definitions

* `qint t n = [n]_t = t^{n-1} + t^{n-3} + ⋯ + t^{1-n}` and `qfact t n = [n]_t^!`;
* `PreF.vi dot v i = v_i = v^{i·i/2}`;
* `PreF.dpow dot v i a = θ_i^{(a)} = ([a]_{v_i}^!)⁻¹ θ_i^a` in `'f` (over a field `K`), and
  its image `PreF.dpowF` in `f`;
* `laurentEval v : ℤ[T, T⁻¹] →+* K`, `T ↦ v`;
* `PreF.Af dot v c`, the integral form `_𝒜 f ⊆ f`: the subring of `f` generated by the
  divided powers and `v^{±1}`, i.e. the `ℤ[v, v⁻¹]`-subalgebra generated by the divided powers
  (`PreF.laurentEval_smul_mem_Af`).

`qint_ne_zero` shows `[n]_t ≠ 0` for `n > 0` when `t` has infinite order; so over `ℚ(v)` the
divided powers are honest (see `Categorification.QuantumGroup.KLSpecialization`).
-/

noncomputable section

namespace Categorification.QuantumGroup

open Finset

/-! ### Quantum integers -/

section QInt

variable {K : Type*} [CommRing K]

/-- The quantum integer `[n]_t = t^{1-n}(1 + t² + ⋯ + t^{2(n-1)}) = t^{n-1} + t^{n-3} + ⋯ + t^{1-n}`
(Lusztig 1.3.1; see `qint_eq_sum`). -/
def qint (t : Kˣ) (n : ℕ) : K :=
  ((t ^ (1 - (n : ℤ)) : Kˣ) : K) * ∑ k ∈ range n, ((t : K) ^ 2) ^ k

/-- The quantum factorial `[n]_t^! = [1]_t [2]_t ⋯ [n]_t`. -/
def qfact (t : Kˣ) (n : ℕ) : K := ∏ m ∈ range n, qint t (m + 1)

theorem qint_eq_sum (t : Kˣ) (n : ℕ) :
    qint t n = ∑ k ∈ range n, ((t ^ ((n : ℤ) - 1 - 2 * k) : Kˣ) : K) := by
  rw [qint, mul_sum, ← sum_range_reflect]
  refine sum_congr rfl fun k hk => ?_
  rw [mem_range] at hk
  rw [← pow_mul, ← Units.val_pow_eq_pow_val, ← Units.val_mul, ← zpow_natCast, ← zpow_add]
  congr 2
  push_cast [Nat.sub_sub, Nat.cast_sub (by omega : 1 + k ≤ n)]
  ring

@[simp] theorem qint_zero (t : Kˣ) : qint t 0 = 0 := by simp [qint]

@[simp] theorem qint_one (t : Kˣ) : qint t 1 = 1 := by simp [qint]

theorem qint_two (t : Kˣ) : qint t 2 = (t : K) + ((t⁻¹ : Kˣ) : K) := by
  rw [qint_eq_sum]
  simp [sum_range_succ]

@[simp] theorem qfact_zero (t : Kˣ) : qfact t 0 = 1 := by simp [qfact]

theorem qfact_succ (t : Kˣ) (n : ℕ) : qfact t (n + 1) = qfact t n * qint t (n + 1) := by
  simp [qfact, prod_range_succ]

@[simp] theorem qfact_one (t : Kˣ) : qfact t 1 = 1 := by simp [qfact]

/-- `[n]_t ≠ 0` for `n > 0` if `t` has infinite order (e.g. `t = v^m` in `ℚ(v)`, `m ≠ 0`). -/
theorem qint_ne_zero {K : Type*} [Field K] {t : Kˣ} (ht : ∀ m : ℕ, 0 < m → t ^ m ≠ 1)
    {n : ℕ} (hn : 0 < n) : qint t n ≠ 0 := by
  refine mul_ne_zero (Units.ne_zero _) fun hs => ?_
  have h := geom_sum_mul ((t : K) ^ 2) n
  rw [hs, zero_mul, eq_comm, sub_eq_zero, ← pow_mul, ← Units.val_pow_eq_pow_val] at h
  exact ht (2 * n) (by omega) (Units.ext h)

theorem qfact_ne_zero {K : Type*} [Field K] {t : Kˣ} (ht : ∀ m : ℕ, 0 < m → t ^ m ≠ 1)
    (n : ℕ) : qfact t n ≠ 0 :=
  prod_ne_zero_iff.2 fun m _ => qint_ne_zero ht (Nat.succ_pos m)

end QInt

/-! ### Laurent polynomials in `v` -/

section Laurent

variable {K : Type*} [CommRing K]

/-- Evaluation `ℤ[T, T⁻¹] → K`, `T ↦ v`; its image is the subring `ℤ[v, v⁻¹] ⊆ K`. -/
def laurentEval (v : Kˣ) : LaurentPolynomial ℤ →+* K :=
  (AddMonoidAlgebra.lift ℤ ℤ K ((Units.coeHom K).comp (zpowersHom Kˣ v))).toRingHom

theorem laurentEval_T (v : Kˣ) (n : ℤ) :
    laurentEval v (LaurentPolynomial.T n) = ((v ^ n : Kˣ) : K) := by
  change AddMonoidAlgebra.lift ℤ ℤ K ((Units.coeHom K).comp (zpowersHom Kˣ v))
    (Finsupp.single n 1) = _
  rw [AddMonoidAlgebra.lift_single, one_smul]
  rfl

end Laurent

/-! ### Divided powers and `_𝒜 f` -/

namespace PreF

variable {I : Type*} {K : Type*} [Field K] (dot : I → I → ℤ) (v : Kˣ)

/-- `v_i = v^{i·i/2}` (Lusztig 1.1.2). -/
def vi (i : I) : Kˣ := v ^ (dot i i / 2)

/-- The divided power `θ_i^{(a)} = θ_i^a / [a]_{v_i}^!` in `'f` (Lusztig 1.4.1). -/
def dpow (i : I) (a : ℕ) : PreF K I := (qfact (vi dot v i) a)⁻¹ • θ i ^ a

variable {dot v}

@[simp] theorem dpow_zero (i : I) : dpow dot v i 0 = 1 := by simp [dpow]

@[simp] theorem dpow_one (i : I) : dpow dot v i 1 = θ i := by simp [dpow]

theorem qfact_smul_dpow {i : I} {a : ℕ} (h : qfact (vi dot v i) a ≠ 0) :
    qfact (vi dot v i) a • dpow dot v i a = θ i ^ a := by
  rw [dpow, smul_smul, mul_inv_cancel₀ h, one_smul]

variable (dot v) (c : I → K)

/-- The divided power `θ_i^{(a)}` in `f`. -/
def dpowF (i : I) (a : ℕ) : F dot v c := π dot v c (dpow dot v i a)

/-- The integral form `_𝒜 f` (Lusztig 1.4.7; KL I §1, §3.1): the subring of `f` generated by
the divided powers `θ_i^{(a)}` and `v^{±1}`. It is the `ℤ[v, v⁻¹]`-subalgebra generated by the
divided powers (`laurentEval_mem_Af`, `laurentEval_smul_mem_Af`). -/
def Af : Subring (F dot v c) :=
  Subring.closure (Set.range (fun p : I × ℕ => dpowF dot v c p.1 p.2) ∪
    {algebraMap K (F dot v c) (v : K), algebraMap K (F dot v c) ((v⁻¹ : Kˣ) : K)})

variable {dot v c}

theorem dpowF_mem_Af (i : I) (a : ℕ) : dpowF dot v c i a ∈ Af dot v c :=
  Subring.subset_closure (Or.inl ⟨(i, a), rfl⟩)

theorem π_θ_mem_Af (i : I) : π dot v c (θ i) ∈ Af dot v c := by
  simpa [dpowF] using dpowF_mem_Af (dot := dot) (v := v) (c := c) i 1

theorem algebraMap_zpow_mem_Af (n : ℤ) :
    algebraMap K (F dot v c) ((v ^ n : Kˣ) : K) ∈ Af dot v c := by
  have hv : algebraMap K (F dot v c) (v : K) ∈ Af dot v c :=
    Subring.subset_closure (Or.inr (Or.inl rfl))
  have hv' : algebraMap K (F dot v c) ((v⁻¹ : Kˣ) : K) ∈ Af dot v c :=
    Subring.subset_closure (Or.inr (Or.inr rfl))
  induction n using Int.induction_on with
  | hz => simp only [zpow_zero, Units.val_one, map_one]; exact Subring.one_mem _
  | hp n ih =>
    rw [zpow_add_one, Units.val_mul, map_mul]
    exact Subring.mul_mem _ ih hv
  | hn n ih =>
    rw [sub_eq_add_neg, zpow_add, zpow_neg_one, Units.val_mul, map_mul]
    exact Subring.mul_mem _ ih hv'

/-- `ℤ[v, v⁻¹] · 1 ⊆ _𝒜 f`. -/
theorem laurentEval_mem_Af (p : LaurentPolynomial ℤ) :
    algebraMap K (F dot v c) (laurentEval v p) ∈ Af dot v c := by
  induction p using Finsupp.induction_linear with
  | zero => simp only [map_zero]; exact Subring.zero_mem _
  | add p q hp hq => rw [map_add, map_add]; exact Subring.add_mem _ hp hq
  | single n m =>
    have : (Finsupp.single n m : LaurentPolynomial ℤ) = m • LaurentPolynomial.T n := by
      rw [LaurentPolynomial.T, Finsupp.smul_single, smul_eq_mul, mul_one]
    rw [this, map_zsmul, map_zsmul, laurentEval_T]
    exact Subring.zsmul_mem _ (algebraMap_zpow_mem_Af n) m

/-- `_𝒜 f` is a `ℤ[v, v⁻¹]`-submodule of `f`. -/
theorem laurentEval_smul_mem_Af (p : LaurentPolynomial ℤ) {x : F dot v c}
    (hx : x ∈ Af dot v c) : laurentEval v p • x ∈ Af dot v c := by
  rw [Algebra.smul_def]
  exact Subring.mul_mem _ (laurentEval_mem_Af p) hx

end PreF

end Categorification.QuantumGroup

end
