/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.QuantumGroup.Bar
import Categorification.QuantumGroup.UDotNondeg

/-!
# The quantum Gabber–Kac theorem: one canonical statement

Lusztig, *Introduction to quantum groups*, **Theorem 33.1.3(a)** (the quantum Gabber–Kac
theorem): for a Cartan datum `(I, ·)`, the radical `ℐ` of the symmetric bilinear form `( , )` on
the free algebra `'f` over `ℚ(v)` (Lusztig 1.2.3, normalised by
`(θ_i, θ_j) = δ_{ij} (1 - v_i^{-2})⁻¹`, `v_i = v^{i·i/2}`) is the two-sided ideal generated by
the quantum Serre elements (Lusztig 1.4.3). It is proved in
`Categorification.QuantumGroup.GabberKacBridge` (`CartanDatum.quantumGabberKac`), from the
quantum Gabber–Kac theorem of the `LieLean` library; this file only states it and derives the
other forms.

Several consumers assume it in slightly different forms:

* KL I (`KLR.KLGamma.theorem_1_1`, `gammaIntEquiv`, …): `PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c`
  (Lusztig's normalisation at `v = vQ`, with the simply-laced list of Serre elements);
* KL II (`KLR.KL2Gamma.theorem_8`, …): `C.GabberKac vQ C.c`;
* KL III Prop. 2.5 (`UDot.KL3.formNondeg`, `UDot.KL3.prop_2_5`):
  `radK C qK (cK C) ≤ Jf C qK`, i.e. at `v = q⁻¹` with KL III's normalisation
  `(θ_i, θ_i) = (1 - q_i²)⁻¹` and the ideal generated by KL III's divided-power Serre elements;
  and, in the simply-laced case, `PreF.GabberKac C.dot qK⁻¹ (cK C)`.

This file defines the single canonical statement `CartanDatum.QuantumGabberKac C` (Lusztig's
normalisation, over `ℚ(v)` with `v = vQ`), and proves that it implies every form above, via

* **change of variables** (`CartanDatum.GabberKac.map`): a ring automorphism `σ` of `K`
  transports the form, the radical and the Serre ideal at `(v, c)` to those at `(σ v, σ ∘ c)`
  (through the `σ`-semilinear map `PreF.bar σ` fixing all words); used with `barQ : v ↦ v⁻¹`;
* **rescaling** (`CartanDatum.GabberKac.rescale`): replacing `c i = (θ_i, θ_i)` by
  `μ_i c_i` for units `μ_i` does not change the radical, because the form at `μ c` is the form at
  `c` precomposed with the grading automorphism `θ_i ↦ μ_i θ_i` (`PreF.form_rescale`);
* **Serre element bookkeeping**: Lusztig's iterated commutators `PreF.serreSeq` versus KL III's
  divided-power elements `PreF.serreDiv` (`UDot.radK_le_Jf_of_cartanGabberKac`, general Cartan
  datum), and versus the simply-laced list `PreF.serreSet` (`CartanDatum.GabberKac.toPreF`).

The converse inclusion `Serre ideal ⊆ ℐ` is proved in the library (Lusztig 1.4.3):
`CartanDatum.span_serreSet_le_radical`, `PreF.span_serre_le_radical`, `UDot.Jf_le_radical`.

## Main results

* `CartanDatum.QuantumGabberKac C` — the canonical statement (Lusztig 33.1.3(a)).
* `CartanDatum.QuantumGabberKac.gabberKac` — KL II's form `C.GabberKac vQ C.c`.
* `CartanDatum.QuantumGabberKac.gabberKac_vQ`, `…gabberKac_vQ_inv` — Gabber–Kac at `v = vQ^{±1}`
  for *any* nonzero normalisation `c`.
* `UDot.KL3.radK_le_Jf_of_quantumGabberKac` — KL III's hypothesis `ℐ ⊆ Jf`.
* `UDot.KL3.gabberKac_of_quantumGabberKac` — `PreF.GabberKac C.dot qK⁻¹ (cK C)` for simply-laced
  `C` (all `i · i = 2` and `i · j ∈ {0, -1}` for `i ≠ j`).
* `UDot.KL3.formNondeg_of_quantumGabberKac`, `UDot.KL3.prop_2_5_of_quantumGabberKac` — KL III
  Prop. 2.5 from the canonical statement.

The KL I and KL II wrappers are in `Categorification.QuantumGroup.GabberKacConsumers`, and the
KL III bijectivity wrappers (`KL3.Diagram.gammaUA'_bijective_of_quantumGabberKac`) in
`Categorification.QuantumGroup.GabberKacKL3Diagrams`.
-/

noncomputable section

namespace Categorification.QuantumGroup

open scoped Classical

namespace PreF

section Transport

variable {I : Type*} {K : Type*} [CommRing K] {dot : I → I → ℤ}

/-! ### Change of variables along a ring endomorphism -/

/-- A ring endomorphism with `σ v = w` sends `v ^ n` to `w ^ n`. -/
theorem val_zpow_of_map (σ : K →+* K) {v w : Kˣ} (hw : σ (v : K) = (w : K)) (n : ℤ) :
    σ ((v ^ n : Kˣ) : K) = ((w ^ n : Kˣ) : K) := by
  have hu : Units.map (σ : K →* K) v = w := Units.ext hw
  have e : σ ((v ^ n : Kˣ) : K) = ((Units.map (σ : K →* K) (v ^ n) : Kˣ) : K) := rfl
  rw [e, map_zpow, hu]

/-- The twisted derivations are compatible with `bar σ`: `d_k^{(σ v)} ∘ bar σ = bar σ ∘ d_k^{(v)}`. -/
theorem d_bar_eq (σ : K →+* K) {v w : Kˣ} (hw : σ (v : K) = (w : K)) (k : I) (x : PreF K I) :
    d dot w k (bar σ x) = bar σ (d dot v k x) := by
  induction x using induction_linear with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy, map_add, map_add]
  | smul_word u r =>
    rw [bar_smul, map_smul, map_smul, bar_smul]
    congr 1
    rw [bar_word]
    induction u using FreeMonoid.inductionOn' with
    | one => rw [word_one, d_one, d_one, map_zero]
    | of_mul j u ih =>
      rw [d_word_of_mul, d_word_of_mul, map_add, bar_smul, map_mul, bar_θ, ← ih,
        val_zpow_of_map σ hw]
      split_ifs <;> simp [bar_word]

/-- **Transport of the form along a ring endomorphism** `σ` of `K`: with `σ v = w` and
`σ ∘ c = c'`, `(bar σ x, bar σ y)_{w, c'} = σ (x, y)_{v, c}`. -/
theorem form_bar_bar (σ : K →+* K) {v w : Kˣ} (hw : σ (v : K) = (w : K)) {c c' : I → K}
    (hc : ∀ i, σ (c i) = c' i) (x y : PreF K I) :
    form dot w c' (bar σ x) (bar σ y) = σ (form dot v c x y) := by
  induction x using induction_linear with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx']
  | smul_word u r =>
    rw [bar_smul, bar_word, map_smul, LinearMap.smul_apply, smul_eq_mul, map_smul,
      LinearMap.smul_apply, smul_eq_mul, map_mul]
    congr 1
    induction u using FreeMonoid.inductionOn' generalizing y with
    | one => rw [word_one, form_one, form_one, counit_bar]
    | of_mul k u ih =>
      rw [word_of_mul, form_θ_mul, form_θ_mul, map_mul, hc, d_bar_eq σ hw, ih]

/-- `bar σ` sends Lusztig's Serre elements at `v` to those at `w = σ v`. -/
theorem bar_serreSeq (σ : K →+* K) {v w : Kˣ} (hw : σ (v : K) = (w : K)) (i j : I) (m : ℕ) :
    bar σ (serreSeq dot v i j m) = serreSeq dot w i j m := by
  induction m with
  | zero => exact bar_θ σ j
  | succ m ih =>
    rw [serreSeq_succ, serreSeq_succ, map_sub, map_mul, bar_smul, map_mul, bar_θ, ih,
      val_zpow_of_map σ hw]

/-- `bar σ ∘ bar τ = id` when `σ ∘ τ = id`. -/
theorem bar_bar_of_leftInverse (σ τ : K →+* K) (h : ∀ a, σ (τ a) = a) (x : PreF K I) :
    bar σ (bar τ x) = x := by
  induction x using induction_linear with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy]
  | smul_word w r => rw [bar_smul, bar_smul, bar_word, bar_word, h]

/-! ### Rescaling the normalisation -/

/-- The grading automorphism `θ_i ↦ μ_i θ_i` of `'f` (it multiplies `'f_ν` by
`∏ μ_i^{ν_i}`). -/
def rescale (μ : I → Kˣ) : PreF K I →ₐ[K] PreF K I :=
  MonoidAlgebra.lift K (PreF K I) (FreeMonoid I)
    (FreeMonoid.lift fun i => ((μ i : K) • θ i : PreF K I))

theorem rescale_θ (μ : I → Kˣ) (i : I) : rescale μ (θ i : PreF K I) = (μ i : K) • θ i := by
  simp [rescale, θ, word, MonoidAlgebra.lift_single]

theorem rescale_word_of_mul (μ : I → Kˣ) (i : I) (u : FreeMonoid I) :
    rescale μ (word (FreeMonoid.of i * u) : PreF K I) =
      (μ i : K) • (θ i * rescale μ (word u)) := by
  rw [word_of_mul, map_mul, rescale_θ, smul_mul_assoc]

/-- **Rescaling the form**: if `c' i = μ_i c i` then `(x, y)_{c'} = (rescale μ x, y)_c`. -/
theorem form_rescale {v : Kˣ} {c c' : I → K} (μ : I → Kˣ) (hc : ∀ i, c' i = μ i * c i)
    (x y : PreF K I) : form dot v c' x y = form dot v c (rescale μ x) y := by
  induction x using induction_linear with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx']
  | smul_word u r =>
    rw [map_smul, LinearMap.smul_apply, map_smul, map_smul, LinearMap.smul_apply]
    congr 1
    induction u using FreeMonoid.inductionOn' generalizing y with
    | one => rw [word_one, map_one (rescale μ), form_one, form_one]
    | of_mul k u ih =>
      rw [rescale_word_of_mul, map_smul, LinearMap.smul_apply, word_of_mul, form_θ_mul,
        form_θ_mul, ih, hc, smul_eq_mul]
      ring

theorem rescale_inv_rescale (μ : I → Kˣ) (x : PreF K I) :
    rescale μ⁻¹ (rescale μ x) = x := by
  induction x using induction_linear with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy]
  | smul_word u r =>
    rw [map_smul, map_smul]
    congr 1
    induction u using FreeMonoid.inductionOn' with
    | one => rw [word_one, map_one, map_one]
    | of_mul k u ih =>
      rw [rescale_word_of_mul, map_smul, map_mul, rescale_θ, ih, smul_mul_assoc, smul_smul,
        word_of_mul, Pi.inv_apply, ← Units.val_mul, mul_inv_cancel, Units.val_one, one_smul]

/-- The grading automorphism scales each Serre element (which is homogeneous). -/
theorem rescale_serreSeq (μ : I → Kˣ) {v : Kˣ} (i j : I) (m : ℕ) :
    ∃ a : K, rescale μ (serreSeq dot v i j m) = a • serreSeq dot v i j m := by
  induction m with
  | zero => exact ⟨μ j, rescale_θ μ j⟩
  | succ m ih =>
    obtain ⟨a, ha⟩ := ih
    refine ⟨(μ i : K) * a, ?_⟩
    rw [serreSeq_succ, map_sub, map_mul, map_smul, map_mul, ha, rescale_θ]
    simp only [smul_sub, smul_mul_assoc, mul_smul_comm, smul_smul]
    rw [mul_comm (((v ^ (dot j i + m * dot i i) : Kˣ) : K)), mul_comm a (μ i : K)]

end Transport

end PreF

namespace CartanDatum

variable {I : Type*} (C : CartanDatum I)

section Transport

variable {K : Type*} [CommRing K]

open PreF

/-- A ring endomorphism of `'f` sending each Serre element at `v` into the two-sided ideal
generated by the Serre elements at `w` maps the first ideal into the second. -/
theorem map_mem_span_serreSet (f : PreF K I →+* PreF K I) {v w : Kˣ}
    (hf : ∀ i j, i ≠ j →
      f (serreSeq C.dot v i j (C.serreN i j)) ∈ TwoSidedIdeal.span (C.serreSet w))
    {x : PreF K I} (hx : x ∈ TwoSidedIdeal.span (C.serreSet v)) :
    f x ∈ TwoSidedIdeal.span (C.serreSet w) := by
  induction hx using TwoSidedIdeal.span_induction with
  | mem x h =>
    obtain ⟨i, j, hij, rfl⟩ := h
    exact hf i j hij
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ ha hb => rw [map_add]; exact add_mem ha hb
  | neg x _ ha => rw [map_neg]; exact neg_mem ha
  | left_absorb a x _ ha => rw [map_mul]; exact TwoSidedIdeal.mul_mem_left _ _ _ ha
  | right_absorb b x _ ha => rw [map_mul]; exact TwoSidedIdeal.mul_mem_right _ _ _ ha

/-- **Change of variables for Gabber–Kac.** Let `σ` be a ring automorphism of `K` (given with
its inverse `τ`), `σ v = w` and `σ ∘ c = c'`. Then Gabber–Kac at `(v, c)` implies Gabber–Kac at
`(w, c')`. (Used with the bar involution `barQ : v ↦ v⁻¹` of `ℚ(v)`.) -/
theorem GabberKac.map {v w : Kˣ} {c c' : I → K} (σ τ : K →+* K) (hστ : ∀ a, σ (τ a) = a)
    (hτσ : ∀ a, τ (σ a) = a) (hw : σ (v : K) = (w : K)) (hc : ∀ i, σ (c i) = c' i)
    (h : C.GabberKac v c) : C.GabberKac w c' := by
  refine le_antisymm (fun x hx => ?_) (C.span_serreSet_le_radical w c')
  have hx' : bar τ x ∈ radical C.dot v c := fun y => by
    have e := form_bar_bar (dot := C.dot) σ hw hc (bar τ x) y
    rw [bar_bar_of_leftInverse σ τ hστ, hx] at e
    have e' := congrArg τ e
    rwa [hτσ, map_zero, eq_comm] at e'
  rw [h, TwoSidedIdeal.mem_asIdeal] at hx'
  rw [TwoSidedIdeal.mem_asIdeal, ← bar_bar_of_leftInverse σ τ hστ x]
  refine C.map_mem_span_serreSet (bar σ) (fun i j hij => ?_) hx'
  rw [bar_serreSeq σ hw]
  exact TwoSidedIdeal.subset_span ⟨i, j, hij, rfl⟩

/-- **Rescaling for Gabber–Kac.** If `c' i = μ_i c i` with units `μ_i`, Gabber–Kac at `(v, c)`
implies Gabber–Kac at `(v, c')`: the radical does not depend on the (unit) normalisation. -/
theorem GabberKac.rescale {v : Kˣ} {c c' : I → K} (μ : I → Kˣ) (hc : ∀ i, c' i = μ i * c i)
    (h : C.GabberKac v c) : C.GabberKac v c' := by
  refine le_antisymm (fun x hx => ?_) (C.span_serreSet_le_radical v c')
  have hx' : PreF.rescale μ x ∈ radical C.dot v c := fun y => by
    rw [← form_rescale μ hc]; exact hx y
  rw [h, TwoSidedIdeal.mem_asIdeal] at hx'
  rw [TwoSidedIdeal.mem_asIdeal, ← rescale_inv_rescale μ x]
  refine C.map_mem_span_serreSet (PreF.rescale μ⁻¹).toRingHom (fun i j hij => ?_) hx'
  obtain ⟨a, ha⟩ := rescale_serreSeq (dot := C.dot) (v := v) μ⁻¹ i j (C.serreN i j)
  rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, ha, Algebra.smul_def]
  exact TwoSidedIdeal.mul_mem_left _ _ _ (TwoSidedIdeal.subset_span ⟨i, j, hij, rfl⟩)

/-- For a simply-laced Cartan datum (`i · i = 2`, and `i · j ∈ {0, -1}` for `i ≠ j`), the
Cartan-datum form `CartanDatum.GabberKac` of the statement implies the simply-laced form
`PreF.GabberKac` (whose list of Serre elements only covers `i · j ∈ {0, -1}`). -/
theorem GabberKac.toPreF (hsl : ∀ i, C.dot i i = 2)
    (h01 : ∀ i j, i ≠ j → C.dot i j = 0 ∨ C.dot i j = -1) {v : Kˣ} {c : I → K}
    (h : C.GabberKac v c) : PreF.GabberKac C.dot v c := by
  refine le_antisymm ?_ (PreF.span_serre_le_radical C.symm hsl)
  rw [GabberKac] at h
  rw [h]
  intro x hx
  rw [TwoSidedIdeal.mem_asIdeal] at hx ⊢
  have hsub : C.serreSet v ⊆ PreF.serreSet C.dot v := by
    rintro _ ⟨i, j, hij, rfl⟩
    rcases h01 i j hij with h0 | h1
    · left
      refine ⟨i, j, hij, h0, ?_⟩
      have hN : C.serreN i j = 1 := by simp [serreN, h0]
      rw [hN, PreF.serreSeq_one i j (by rw [C.symm]; exact h0)]
    · right
      refine ⟨i, j, hij, h1, ?_⟩
      have hN : C.serreN i j = 2 := by simp [serreN, h1, hsl i]
      rw [hN, PreF.serreSeq_two i j (hsl i) (by rw [C.symm]; exact h1)]
  exact TwoSidedIdeal.span_mono hsub hx

end Transport

/-! ### The canonical statement -/

/-- **The quantum Gabber–Kac theorem (Lusztig, *Introduction to quantum groups*, Theorem
33.1.3(a)); proved in `CartanDatum.quantumGabberKac`
(`Categorification.QuantumGroup.GabberKacBridge`).** For the Cartan datum `C`, over
`ℚ(v) = RatFunc ℚ` with `v = vQ` and Lusztig's normalisation
`(θ_i, θ_j) = δ_{ij} (1 - v_i^{-2})⁻¹`, `v_i = v^{i·i/2}` (Lusztig 1.2.3(a); `CartanDatum.c`),
the radical `ℐ` of the bilinear form `( , )` on `'f` (Lusztig 1.2.4) is the two-sided ideal
generated by the quantum Serre elements
`Σ_{r+s = 1 - ⟨i, j'⟩} (-1)^r θ_i^{(r)} θ_j θ_i^{(s)}`, `i ≠ j` (Lusztig 1.4.3; here in the
iterated-commutator form `PreF.serreSeq`, which is `[N]_{v_i}^!` times Lusztig's divided-power
element `PreF.serreDiv` by `PreF.serreSeq_eq_qfact_smul_serreDiv`, so both generate the same ideal
over `ℚ(v)`).

The inclusion `⊇` is proved (`CartanDatum.span_serreSet_le_radical`, Lusztig 1.4.3; also
`UDot.Jf_le_radical` for KL III's divided-power Serre ideal). This proposition is the single
hypothesis from which every other form of Gabber–Kac used in the library follows
(`QuantumGabberKac.gabberKac`, `…gabberKac_vQ`, `…gabberKac_vQ_inv`,
`UDot.KL3.radK_le_Jf_of_quantumGabberKac`, `UDot.KL3.gabberKac_of_quantumGabberKac`, and the
KL I form in `Categorification.QuantumGroup.GabberKacConsumers`). -/
def QuantumGabberKac : Prop := C.GabberKac vQ C.c

variable {C}

namespace QuantumGabberKac

/-- The canonical statement is KL II's hypothesis `C.GabberKac vQ C.c` (KL II, Theorem 8). -/
theorem gabberKac (h : C.QuantumGabberKac) : C.GabberKac vQ C.c := h

/-- Gabber–Kac at `v = vQ` for **any** nonzero normalisation `c` of `(θ_i, θ_i)`. -/
theorem gabberKac_vQ (h : C.QuantumGabberKac) {c : I → RatFunc ℚ} (hc : ∀ i, c i ≠ 0) :
    C.GabberKac vQ c :=
  GabberKac.rescale C (fun i => Units.mk0 (c i / C.c i) (div_ne_zero (hc i) (C.c_ne_zero i)))
    (fun i => by simp [div_mul_cancel₀ _ (C.c_ne_zero i)]) h

/-- Gabber–Kac at `v = vQ⁻¹` with the bar-transported normalisation `c̄_i = (1 - v^{i·i})⁻¹`
(the image of Lusztig's under `barQ : v ↦ v⁻¹`). -/
theorem gabberKac_vQ_inv_barQ (h : C.QuantumGabberKac) :
    C.GabberKac vQ⁻¹ (fun i => barQ (C.c i)) :=
  GabberKac.map C barQ barQ barQ_barQ barQ_barQ barQ_vQ (fun _ => rfl) h

/-- Gabber–Kac at `v = vQ⁻¹` for **any** nonzero normalisation `c` of `(θ_i, θ_i)`. -/
theorem gabberKac_vQ_inv (h : C.QuantumGabberKac) {c : I → RatFunc ℚ} (hc : ∀ i, c i ≠ 0) :
    C.GabberKac vQ⁻¹ c := by
  have hb : ∀ i, barQ (C.c i) ≠ 0 := fun i hi =>
    C.c_ne_zero i (by rw [← barQ_barQ (C.c i), hi, map_zero])
  exact GabberKac.rescale C
    (fun i => Units.mk0 (c i / barQ (C.c i)) (div_ne_zero (hc i) (hb i)))
    (fun i => by simp [div_mul_cancel₀ _ (hb i)]) h.gabberKac_vQ_inv_barQ

end QuantumGabberKac

end CartanDatum

/-! ### KL III: the inclusion `ℐ ⊆ Jf` and Proposition 2.5 -/

namespace UDot

open PreF

variable {I : Type*} {K : Type*} [Field K] {C : CartanDatum I} {q : Kˣ} {c : I → K}

/-- For an arbitrary Cartan datum, Gabber–Kac at `v = q⁻¹` (`CartanDatum.GabberKac`) implies
KL III's inclusion `ℐ ⊆ Jf` (the ideal generated by KL III's divided-power Serre elements).
Generalises `UDot.radK_le_Jf_of_gabberKac` (simply-laced). -/
theorem radK_le_Jf_of_cartanGabberKac (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1)
    (hGK : C.GabberKac q⁻¹ c) : radK C q c ≤ Jf C q := by
  intro x hx
  have hx' : x ∈ radical C.dot q⁻¹ c := hx
  rw [hGK, TwoSidedIdeal.mem_asIdeal] at hx'
  clear hx
  have hqf : ∀ i N, qfact (vi C.dot q⁻¹ i) N ≠ 0 := fun i N => by
    rw [vi, inv_zpow', zpow_neg, qfact_inv]
    exact qfact_vi_ne_zero C q hq i _
  induction hx' using TwoSidedIdeal.span_induction with
  | mem x h =>
    obtain ⟨i, j, hij, rfl⟩ := h
    rw [serreSeq_eq_qfact_smul_serreDiv C.symm i j (C.dot_self_even i) (C.two_mul_dot_eq hij)
      (hqf i _), serreDiv_inv]
    refine Submodule.smul_mem _ _ ?_
    simpa using mul_serreDiv_mul_mem_Jf (C := C) (q := q) hij 1 1
  | zero => exact Submodule.zero_mem _
  | add x y _ _ ha hb => exact add_mem ha hb
  | neg x _ ha => exact neg_mem ha
  | left_absorb a x _ ha => exact Jf_mul_left ha a
  | right_absorb b x _ ha => exact Jf_mul_right ha b

namespace KL3

theorem cK_eq_barQ (C : CartanDatum I) (i : I) : cK C i = barQ (C.c i) := by
  rw [cK_eq_lusztigC, CartanDatum.c, lusztigC, lusztigC, map_inv₀, map_sub, map_one,
    PreF.val_zpow_of_map barQ barQ_vQ]

/-- The canonical statement at KL III's parameters: Gabber–Kac at `v = q⁻¹` with KL III's
normalisation `(θ_i, θ_i) = (1 - q_i²)⁻¹`. -/
theorem gabberKac_cK_of_quantumGabberKac {C : CartanDatum I} (h : C.QuantumGabberKac) :
    C.GabberKac qK⁻¹ (cK C) := by
  have := h.gabberKac_vQ_inv_barQ
  rwa [show (fun i => barQ (C.c i)) = cK C from funext fun i => (cK_eq_barQ C i).symm] at this

/-- **KL III's Gabber–Kac hypothesis** `ℐ ⊆ Jf` (used in `UDot.KL3.formNondeg`,
`UDot.KL3.prop_2_5`) follows from the canonical statement, for every Cartan datum. -/
theorem radK_le_Jf_of_quantumGabberKac {C : CartanDatum I} (h : C.QuantumGabberKac) :
    radK C qK (cK C) ≤ Jf C qK :=
  radK_le_Jf_of_cartanGabberKac hqK (gabberKac_cK_of_quantumGabberKac h)

/-- The simply-laced statement `PreF.GabberKac C.dot qK⁻¹ (cK C)` (the hypothesis of
`UDot.KL3.formNondeg_of_gabberKac`) follows from the canonical statement when `C` is
simply-laced in the strict sense (`i · i = 2`, and `i · j ∈ {0, -1}` for `i ≠ j`). The second
condition is needed: `PreF.serreSet` lists only the Serre elements with `i · j ∈ {0, -1}`. -/
theorem gabberKac_of_quantumGabberKac {C : CartanDatum I} (hsl : ∀ i, C.dot i i = 2)
    (h01 : ∀ i j, i ≠ j → C.dot i j = 0 ∨ C.dot i j = -1) (h : C.QuantumGabberKac) :
    PreF.GabberKac C.dot qK⁻¹ (cK C) :=
  (gabberKac_cK_of_quantumGabberKac h).toPreF C hsl h01

variable {X Y : Type*} [AddCommGroup X] [AddCommGroup Y] (RD : RootDatum C X Y)

/-- **Khovanov–Lauda III, Proposition 2.5 for `( , )`** (arXiv:0807.3250v1, §2.1.3), for an
arbitrary Cartan datum, from the canonical quantum Gabber–Kac statement (Lusztig 33.1.3(a)). -/
theorem formNondeg_of_quantumGabberKac (h : C.QuantumGabberKac) : FormNondeg RD :=
  formNondeg RD (radK_le_Jf_of_quantumGabberKac h)

/-- **Khovanov–Lauda III, Proposition 2.5** (arXiv:0807.3250v1, §2.1.3): both `( , )` and
`⟨ , ⟩` are nondegenerate on `U̇`, from the canonical quantum Gabber–Kac statement. -/
theorem prop_2_5_of_quantumGabberKac (h : C.QuantumGabberKac) :
    FormNondeg RD ∧ ∀ x, (∀ y, sform RD x y = 0) → x = 0 :=
  prop_2_5 RD (radK_le_Jf_of_quantumGabberKac h)

end KL3

end UDot

end Categorification.QuantumGroup

end
