/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.QuantumGroup.UDotSerre

/-!
# Root data, the blocks `U̇ 1_λ`, and the bilinear form on them

Khovanov–Lauda III, arXiv:0807.3250v1, §2.1.1 (root datum), §2.1.3 (`U̇`, Proposition 2.2).

* `UDot.RootDatum C X Y` — a root datum `(Y, X, ⟨,⟩, …)` of type `(I, ·)`: free finitely
  generated abelian groups `X`, `Y`, a perfect pairing `⟨,⟩ : Y × X → ℤ` and maps
  `I → X`, `i ↦ i_X`, `I → Y`, `i ↦ i` with `⟨i, j_X⟩ = 2 (i·j)/(i·i)`. (The maps `I → X`,
  `I → Y` are then automatically injective: `UDot.RootDatum.iX_injective`.)
* `UDot.U1 RD q λ = U̇ 1_λ` — the quotient of the free algebra `'U 1_λ` on the signed letters
  by the relations of `U̇` (KL III eqs. (2.2)–(2.4) and the quantum Serre relations; see
  `Categorification.QuantumGroup.UDotSerre`).
* The action of `U` on `U̇ 1_λ` by left multiplication: `UDot.Egen RD q λ (ε, i)` is left
  multiplication by `E_{εi}` and `UDot.Kact RD q λ μ` by `K_μ` (`μ ∈ Y`), which acts on
  `1_ν U̇ 1_λ` by `q^{⟨μ, ν⟩}`. `UDot.oneL RD q λ ν` is left multiplication by `1_ν`.
* `UDot.rhoBar RD q λ (ε, i) = q_i⁻¹ K̃_{-εi} E_{-εi}` — left multiplication by
  `ρ̄(E_{εi})`, where `ρ̄ = ψρψ` (KL III §2.1.2: `ρ̄(E_i) = q_i⁻¹ K̃_{-i} F_i`,
  `ρ̄(F_i) = q_i⁻¹ K̃_i E_i`, `ρ̄(K_μ) = K_μ`, `K̃_{±i} = K_{±(i·i/2) i}`).
* `UDot.formU RD q c λ` — the bilinear form on `U̇ 1_λ`.

## Main results (KL III Proposition 2.2, for one block `U̇ 1_λ`)

* `UDot.formU_E_left` — (iii) for `u = E_{±i}`: `(E_{εi} x, y) = (x, ρ̄(E_{εi}) y)`;
* `UDot.formU_K_left` — (iii) for `u = K_μ`: `(K_μ x, y) = (x, K_μ y)`;
* `UDot.formU_oneL` — (ii): `(1_ν x, 1_{ν'} y) = 0` for `ν ≠ ν'`;
* `UDot.formU_posF` — (iv): `(x⁺ 1_λ, x'⁺ 1_λ) = (x, x')` for `x, x' ∈ 'f`;
* `UDot.formU_symm` — (v);
* `UDot.formU_unique` — uniqueness: a bilinear form on `U̇ 1_λ` with (iii) for `E_{±i}`, (iv) and
  (v) is `formU`.

Since `U` is generated by the `E_i, F_i, K_μ` and `ρ̄` is an anti-automorphism, (iii) for
these generators is equivalent to (iii) for all `u ∈ U`. Property (iv) is stated for `x, x'` in
the free algebra `'f` (the form on `f` is induced from `'f`); this avoids using that `f → U̇ 1_λ`
is well defined, which would require the quantum Gabber–Kac theorem.

Throughout, `q ∈ Kˣ` is not a root of unity (`hq`); KL III's case is `K = ℚ(q)`.
-/

noncomputable section

namespace Categorification.QuantumGroup

open scoped Classical
open PreF

namespace UDot

variable {I : Type*} {K : Type*} [Field K]

/-! ### Root data -/

/-- A root datum of type `(I, ·)` (KL III §2.1.1; Lusztig 2.2.1): free finitely generated
abelian groups `X`, `Y` with a perfect pairing `⟨,⟩ : Y × X → ℤ`, and maps `I → X`
(`i ↦ i_X`), `I → Y` (`i ↦ i`) with `⟨i, j_X⟩ = 2 (i·j)/(i·i)`. -/
structure RootDatum (C : CartanDatum I) (X Y : Type*) [AddCommGroup X] [AddCommGroup Y] where
  /-- The pairing `⟨,⟩ : Y × X → ℤ`. -/
  pair : Y →+ X →+ ℤ
  /-- Perfectness: `Y ≅ Hom(X, ℤ)`. -/
  perfect_left : Function.Bijective pair
  /-- Perfectness: `X ≅ Hom(Y, ℤ)`. -/
  perfect_right : Function.Bijective pair.flip
  free_X : Module.Free ℤ X
  finite_X : Module.Finite ℤ X
  free_Y : Module.Free ℤ Y
  finite_Y : Module.Finite ℤ Y
  /-- `i ↦ i_X`. -/
  iX : I → X
  /-- `i ↦ i ∈ Y`. -/
  iY : I → Y
  pair_iY_iX : ∀ i j, pair (iY i) (iX j) = 2 * C.dot i j / C.dot i i

namespace RootDatum

variable {C : CartanDatum I} {X Y : Type*} [AddCommGroup X] [AddCommGroup Y]
  (RD : RootDatum C X Y)

theorem pair_iY_iX_eq_A (i j : I) : RD.pair (RD.iY i) (RD.iX j) = A C i j := RD.pair_iY_iX i j

theorem pair_iY_iX_self (i : I) : RD.pair (RD.iY i) (RD.iX i) = 2 := by
  rw [pair_iY_iX_eq_A, A_self]

/-- The map `I → X` is injective. -/
theorem iX_injective : Function.Injective RD.iX := by
  intro i j h
  by_contra hij
  have h1 := RD.pair_iY_iX_self i
  rw [h, pair_iY_iX_eq_A] at h1
  have := C.dot_nonpos i j hij
  have h2 := di_mul_A C i j
  have := di_pos C i
  nlinarith

/-- The map `I → Y` is injective. -/
theorem iY_injective : Function.Injective RD.iY := by
  intro i j h
  by_contra hij
  have h1 := RD.pair_iY_iX_self j
  rw [← h, pair_iY_iX_eq_A] at h1
  have := C.dot_nonpos i j hij
  have h2 := di_mul_A C i j
  have := di_pos C i
  nlinarith

/-- The weight `w_X = Σ_k ε_k (i_k)_X ∈ X` of a signed sequence (KL III eq. (2.11)). -/
def wX (t : List (Bool × I)) : X := (t.map fun l => sgn l.1 • RD.iX l.2).sum

@[simp] theorem wX_nil : RD.wX [] = 0 := rfl

@[simp] theorem wX_cons (l : Bool × I) (t : List (Bool × I)) :
    RD.wX (l :: t) = sgn l.1 • RD.iX l.2 + RD.wX t := by simp [wX]

@[simp] theorem wX_append (t t' : List (Bool × I)) : RD.wX (t ++ t') = RD.wX t + RD.wX t' := by
  simp [wX]

theorem pair_wX (i : I) (t : List (Bool × I)) : RD.pair (RD.iY i) (RD.wX t) = aS C i t := by
  induction t with
  | nil => simp
  | cons l t ih => rw [wX_cons, map_add, map_zsmul, ih, aS_cons, pair_iY_iX_eq_A, smul_eq_mul]

/-- `ellOf λ i = ⟨i, λ⟩`. -/
def ellOf (lam : X) : I → ℤ := fun i => RD.pair (RD.iY i) lam

theorem wl_ellOf (lam : X) (t : List (Bool × I)) (i : I) :
    wl C (RD.ellOf lam) t i = RD.pair (RD.iY i) (lam + RD.wX t) := by
  rw [wl, ellOf, map_add, pair_wX]

/-- `wX` only depends on `posMS` and `negMS`. -/
theorem wX_eq (t : List (Bool × I)) :
    RD.wX t = ((posMS t).map RD.iX).sum - ((negMS t).map RD.iX).sum := by
  induction t with
  | nil => simp
  | cons l t ih =>
    obtain ⟨b, i⟩ := l
    cases b <;> simp [ih] <;> abel

end RootDatum

variable {C : CartanDatum I} {X Y : Type*} [AddCommGroup X] [AddCommGroup Y]
  (RD : RootDatum C X Y) (q : Kˣ)

/-! ### `X`-graded pieces of `'U 1_λ` -/

variable (K) in
/-- The span of the `E_w` with `w_X = μ`. -/
def FX (μ : X) : Submodule K (Free K I) := supp {w : FreeMonoid (Bool × I) | RD.wX w.toList = μ}

theorem ew_mem_FX (t : List (Bool × I)) : (ew t : Free K I) ∈ FX K RD (RD.wX t) :=
  word_mem_supp (by simp)

theorem Fg_le_FX (P N : Multiset I) :
    Fg I K P N ≤ FX K RD ((P.map RD.iX).sum - (N.map RD.iX).sum) := by
  intro x hx
  refine supp_mono (fun w hw => ?_) hx
  simp only [Set.mem_setOf_eq] at hw ⊢
  rw [RD.wX_eq, hw.1, hw.2]

/-- The diagonal operator `E_w ↦ g(w_X) E_w`. -/
def diagX (g : X → K) : Free K I →ₗ[K] Free K I :=
  linLift fun w => g (RD.wX w.toList) • ew w.toList

theorem diagX_ew (g : X → K) (t : List (Bool × I)) :
    diagX RD g (ew t) = g (RD.wX t) • (ew t : Free K I) := by
  rw [diagX, ew, linLift_word, FreeMonoid.toList_ofList]; rfl

theorem diagX_of_mem_FX (g : X → K) {μ : X} {x : Free K I} (hx : x ∈ FX K RD μ) :
    diagX RD g x = g μ • x := by
  refine eqOn_supp (diagX RD g) (g μ • LinearMap.id) (fun w hw => ?_) x hx
  simp only [Set.mem_setOf_eq] at hw
  rw [word_eq_ew, diagX_ew, hw]; rfl

variable (c : I → K)

theorem relSet_homogeneous (lam : X) {z : Free K I} (hz : z ∈ relSet C q (RD.ellOf lam)) :
    ∃ μ, z ∈ FX K RD μ := by
  rcases hz with ⟨a, b, i, j, rfl⟩ | ⟨a, b, i, j, hij, rfl | rfl⟩
  · refine ⟨RD.wX (a ++ (true, i) :: (false, j) :: b), ?_⟩
    rw [ew_mul_commRel_mul]
    refine sub_mem (sub_mem (ew_mem_FX RD _) ?_) ?_
    · have := ew_mem_FX (K := K) RD (a ++ (false, j) :: (true, i) :: b)
      convert this using 2
      simp; abel
    · split_ifs with h
      · subst h
        refine Submodule.smul_mem _ _ ?_
        have := ew_mem_FX (K := K) RD (a ++ b)
        convert this using 2
        simp
      · simp
  · exact ⟨_, Fg_le_FX RD _ _ (Fg_mul (Fg_mul (ew_mem_Fg a)
      (posF_mem_Fg (serreKL_mem_grade (C := C) (q := q) i j))) (ew_mem_Fg b))⟩
  · exact ⟨_, Fg_le_FX RD _ _ (Fg_mul (Fg_mul (ew_mem_Fg a)
      (negF_mem_Fg (serreKL_mem_grade (C := C) (q := q) i j))) (ew_mem_Fg b))⟩

theorem diagX_Lrel (lam : X) (g : X → K) : Lrel C q (RD.ellOf lam) ≤
    (Lrel C q (RD.ellOf lam)).comap (diagX RD g) := by
  rw [Lrel, Submodule.span_le]
  intro z hz
  obtain ⟨μ, hμ⟩ := relSet_homogeneous RD q lam hz
  simp only [SetLike.mem_coe, Submodule.mem_comap]
  rw [diagX_of_mem_FX RD g hμ]
  exact Submodule.smul_mem _ _ (Submodule.subset_span hz)

theorem mulLeft_Lrel (ℓ : I → ℤ) (l : Bool × I) : Lrel C q ℓ ≤
    (Lrel C q ℓ).comap (LinearMap.mulLeft K (ew [l] : Free K I)) := by
  rw [Lrel, Submodule.span_le]
  intro z hz
  simp only [SetLike.mem_coe, Submodule.mem_comap, LinearMap.mulLeft_apply]
  refine Submodule.subset_span ?_
  rcases hz with ⟨a, b, i, j, rfl⟩ | ⟨a, b, i, j, hij, rfl | rfl⟩
  · exact Or.inl ⟨l :: a, b, i, j, by rw [ew_cons l a, mul_assoc, mul_assoc, mul_assoc]⟩
  · exact Or.inr ⟨l :: a, b, i, j, hij, Or.inl (by rw [ew_cons l a, mul_assoc, mul_assoc,
      mul_assoc])⟩
  · exact Or.inr ⟨l :: a, b, i, j, hij, Or.inr (by rw [ew_cons l a, mul_assoc, mul_assoc,
      mul_assoc])⟩

/-! ### The blocks `U̇ 1_λ` -/

/-- `U̇ 1_λ`: the free algebra on the signed letters modulo the relations of `U̇` at right
weight `λ` (KL III §2.1.3). -/
abbrev U1 (lam : X) := Free K I ⧸ Lrel C q (RD.ellOf lam)

/-- The quotient map `'U 1_λ → U̇ 1_λ`, `E_w ↦ E_w 1_λ`. -/
def mk (lam : X) : Free K I →ₗ[K] U1 RD q lam := (Lrel C q (RD.ellOf lam)).mkQ

theorem mk_surjective (lam : X) : Function.Surjective (mk RD q lam) :=
  Submodule.mkQ_surjective _

theorem mk_eq_zero (lam : X) {z : Free K I} (hz : z ∈ Lrel C q (RD.ellOf lam)) :
    mk RD q lam z = 0 := (Submodule.Quotient.mk_eq_zero _).2 hz

/-- Left multiplication by `E_{εi}` on `U̇ 1_λ`. -/
def Egen (lam : X) (l : Bool × I) : Module.End K (U1 RD q lam) :=
  (Lrel C q (RD.ellOf lam)).mapQ _ (LinearMap.mulLeft K (ew [l])) (mulLeft_Lrel q _ l)

/-- Left multiplication by `K_μ` (`μ ∈ Y`) on `'U 1_λ`: `E_t 1_λ ↦ q^{⟨μ, λ + t_X⟩} E_t 1_λ`. -/
def KactF (lam : X) (μ : Y) : Free K I →ₗ[K] Free K I :=
  diagX RD fun ν => qp q (RD.pair μ (lam + ν))

/-- Left multiplication by `K_μ` (`μ ∈ Y`) on `U̇ 1_λ`. -/
def Kact (lam : X) (μ : Y) : Module.End K (U1 RD q lam) :=
  (Lrel C q (RD.ellOf lam)).mapQ _ (KactF RD q lam μ) (diagX_Lrel RD q lam _)

/-- Left multiplication by the idempotent `1_ν` on `U̇ 1_λ`. -/
def oneL (lam ν : X) : Module.End K (U1 RD q lam) :=
  (Lrel C q (RD.ellOf lam)).mapQ _ (diagX RD fun ν' => if lam + ν' = ν then 1 else 0)
    (diagX_Lrel RD q lam _)

/-- Left multiplication by `ρ̄(E_{εi}) = q_i⁻¹ K̃_{-εi} E_{-εi}` on `U̇ 1_λ` (KL III §2.1.2). -/
def rhoBar (lam : X) (l : Bool × I) : Module.End K (U1 RD q lam) :=
  (((qi C q l.2)⁻¹ : Kˣ) : K) •
    (Kact RD q lam (-(sgn l.1 * di C l.2) • RD.iY l.2) ∘ₗ Egen RD q lam (!l.1, l.2))

theorem Egen_mk (lam : X) (l : Bool × I) (z : Free K I) :
    Egen RD q lam l (mk RD q lam z) = mk RD q lam (ew [l] * z) := rfl

theorem Kact_mk_ew (lam : X) (μ : Y) (t : List (Bool × I)) :
    Kact RD q lam μ (mk RD q lam (ew t)) = qp q (RD.pair μ (lam + RD.wX t)) • mk RD q lam (ew t) := by
  change mk RD q lam (KactF RD q lam μ (ew t)) = _
  rw [KactF, diagX_ew, map_smul]

theorem oneL_mk_ew (lam ν : X) (t : List (Bool × I)) :
    oneL RD q lam ν (mk RD q lam (ew t)) = if lam + RD.wX t = ν then mk RD q lam (ew t) else 0 := by
  change mk RD q lam (diagX RD _ (ew t)) = _
  rw [diagX_ew, map_smul]
  split_ifs <;> simp

theorem pair_zsmul (k : ℤ) (y : Y) (x : X) : RD.pair (k • y) x = k * RD.pair y x := by
  rw [RD.pair.map_zsmul, AddMonoidHom.coe_smul, Pi.smul_apply, smul_eq_mul]

theorem rhoBar_mk (lam : X) (l : Bool × I) (z : Free K I) :
    rhoBar RD q lam l (mk RD q lam z) = mk RD q lam (rhoE C q (RD.ellOf lam) l z) := by
  induction z using Free.induction with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy, map_add, map_add]
  | smul_ew t r =>
    obtain ⟨b, i⟩ := l
    simp only [map_smul]
    congr 1
    rw [rhoBar, LinearMap.smul_apply, LinearMap.comp_apply, Egen_mk, ← ew_cons, Kact_mk_ew,
      smul_smul, rhoE_ew, LinearMap.map_smul]
    congr 1
    have hq1 : (((qi C q i)⁻¹ : Kˣ) : K) = qp q (-di C i) := by rw [qi, ← zpow_neg]; rfl
    rw [hq1, ← qp_add, RD.wl_ellOf]
    congr 1
    dsimp only
    rw [pair_zsmul, RD.wX_cons, add_left_comm, map_add, map_zsmul, RD.pair_iY_iX_self]
    simp only [sgn_not, smul_eq_mul]
    have := sgn_mul_self b
    linear_combination ((2 : ℤ) * di C i) * this

/-! ### The bilinear form on `U̇ 1_λ` -/

variable {q} in
/-- The relation `(E_iF_j - F_jE_i) E_b 1_λ = δ_{ij} [⟨i, λ + b_X⟩]_i E_b 1_λ` in `U̇ 1_λ`
(KL III eq. (2.4)), with an arbitrary prefix. -/
theorem mk_comm (lam : X) (a b : List (Bool × I)) (i j : I) :
    mk RD q lam (ew (a ++ (true, i) :: (false, j) :: b)) =
      mk RD q lam (ew (a ++ (false, j) :: (true, i) :: b)) +
        (if j = i then qbr (qi C q i) (wl C (RD.ellOf lam) b i) else 0) • mk RD q lam (ew (a ++ b)) := by
  have h := mk_eq_zero RD q lam (Submodule.subset_span (Or.inl ⟨a, b, i, j, rfl⟩))
  rw [ew_mul_commRel_mul, map_sub, map_sub, map_smul] at h
  rw [← sub_eq_zero, ← h]; abel

variable (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1)

/-- **The bilinear form `( , )` on `U̇ 1_λ`** (KL III Proposition 2.2), induced from the form
`UDot.B` on `'U 1_λ`, which kills the relations (`UDot.B_Lrel_left`, `UDot.B_Lrel_right`). -/
def formU (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) (lam : X) :
    U1 RD q lam →ₗ[K] U1 RD q lam →ₗ[K] K :=
  (Lrel C q (RD.ellOf lam)).liftQ
    ((Lrel C q (RD.ellOf lam)).liftQ (B C q c (RD.ellOf lam)).flip (fun y hy =>
      LinearMap.ext fun x => B_Lrel_right hq _ x hy)).flip
    (fun x hx => LinearMap.ext fun y => by
      obtain ⟨y, rfl⟩ := Submodule.mkQ_surjective _ y
      exact B_Lrel_left hq _ hx y)

theorem formU_mk (lam : X) (x y : Free K I) :
    formU RD q c hq lam (mk RD q lam x) (mk RD q lam y) = B C q c (RD.ellOf lam) x y := rfl

/-- Two bilinear forms on `U̇ 1_λ` agreeing on the `E_s 1_λ, E_t 1_λ` agree. -/
theorem U1_bilin_ext {lam : X} {F G : U1 RD q lam →ₗ[K] U1 RD q lam →ₗ[K] K}
    (h : ∀ s t, F (mk RD q lam (ew s)) (mk RD q lam (ew t)) =
      G (mk RD q lam (ew s)) (mk RD q lam (ew t))) : F = G := by
  refine Submodule.linearMap_qext _ (Free.lhom_ext fun s => ?_)
  refine Submodule.linearMap_qext _ (Free.lhom_ext fun t => ?_)
  exact h s t

/-- **KL III Prop. 2.2 (iii)** for `u = E_{±i}`: `(E_{εi} x, y) = (x, ρ̄(E_{εi}) y)`. -/
theorem formU_E_left (lam : X) (l : Bool × I) (x y : U1 RD q lam) :
    formU RD q c hq lam (Egen RD q lam l x) y = formU RD q c hq lam x (rhoBar RD q lam l y) := by
  obtain ⟨x, rfl⟩ := mk_surjective RD q lam x
  obtain ⟨y, rfl⟩ := mk_surjective RD q lam y
  rw [Egen_mk, rhoBar_mk, formU_mk, formU_mk, B_ew_mul_left]
  rfl

/-- **KL III Prop. 2.2 (iii)** for `u = K_μ`: `(K_μ x, y) = (x, K_μ y)` (`ρ̄(K_μ) = K_μ`). -/
theorem formU_K_left (lam : X) (μ : Y) (x y : U1 RD q lam) :
    formU RD q c hq lam (Kact RD q lam μ x) y = formU RD q c hq lam x (Kact RD q lam μ y) := by
  have : (formU RD q c hq lam) ∘ₗ Kact RD q lam μ = (formU RD q c hq lam).compl₂ (Kact RD q lam μ) := by
    refine U1_bilin_ext RD q fun s t => ?_
    simp only [LinearMap.comp_apply, LinearMap.compl₂_apply, Kact_mk_ew, map_smul,
      LinearMap.smul_apply, smul_eq_mul, formU_mk]
    by_cases hb : Balanced s t
    · rw [RD.wX_eq, RD.wX_eq]
      congr 3
      have := congrArg (fun ν => (ν.map RD.iX).sum) hb
      simp only [Multiset.map_add, Multiset.sum_add] at this
      congr 1
      rw [sub_eq_sub_iff_add_eq_add, this]
    · rw [B_eq_zero_of_not_balanced _ hb]; simp
  exact LinearMap.congr_fun (LinearMap.congr_fun this x) y

/-- **KL III Prop. 2.2 (ii)** (left weights): `(1_ν x 1_λ, 1_{ν'} y 1_λ) = 0` for `ν ≠ ν'`. -/
theorem formU_oneL (lam : X) {ν ν' : X} (h : ν ≠ ν') (x y : U1 RD q lam) :
    formU RD q c hq lam (oneL RD q lam ν x) (oneL RD q lam ν' y) = 0 := by
  have : (formU RD q c hq lam).compl₁₂ (oneL RD q lam ν) (oneL RD q lam ν') = 0 := by
    refine U1_bilin_ext RD q fun s t => ?_
    simp only [LinearMap.compl₁₂_apply, oneL_mk_ew, LinearMap.zero_apply]
    split_ifs with h1 h2
    · rw [formU_mk, B_eq_zero_of_not_balanced]
      intro hb
      refine h ?_
      rw [← h1, ← h2, RD.wX_eq, RD.wX_eq]
      have := congrArg (fun ν => (ν.map RD.iX).sum) hb
      simp only [Multiset.map_add, Multiset.sum_add] at this
      congr 1
      rw [sub_eq_sub_iff_add_eq_add, this]
    all_goals simp
  exact LinearMap.congr_fun (LinearMap.congr_fun this x) y

/-- **KL III Prop. 2.2 (iv)**: `(x⁺ 1_λ, x'⁺ 1_λ) = (x, x')` for `x, x' ∈ 'f`. -/
theorem formU_posF (lam : X) (x x' : PreF K I) :
    formU RD q c hq lam (mk RD q lam (posF x)) (mk RD q lam (posF x')) = fF C q c x x' := by
  rw [formU_mk, B_posF_posF]

/-- **KL III Prop. 2.2 (v)**: the form on `U̇ 1_λ` is symmetric. -/
theorem formU_symm (lam : X) (x y : U1 RD q lam) :
    formU RD q c hq lam x y = formU RD q c hq lam y x := by
  obtain ⟨x, rfl⟩ := mk_surjective RD q lam x
  obtain ⟨y, rfl⟩ := mk_surjective RD q lam y
  rw [formU_mk, formU_mk, B_symm]

/-! ### Uniqueness -/

section Unique

variable {RD q c} {lam : X} {B' : U1 RD q lam →ₗ[K] U1 RD q lam →ₗ[K] K}
  (h3 : ∀ l x y, B' (Egen RD q lam l x) y = B' x (rhoBar RD q lam l y))
  (h4 : ∀ x x', B' (mk RD q lam (posF x)) (mk RD q lam (posF x')) = fF C q c x x')
  (h5 : ∀ x y, B' x y = B' y x)

include h3 in
theorem unique_move (a : List (Bool × I)) (Z z : Free K I) :
    B' (mk RD q lam (ew a * Z)) (mk RD q lam z) =
      B' (mk RD q lam Z) (mk RD q lam (R C q (RD.ellOf lam) a z)) := by
  induction a generalizing z with
  | nil => simp [R]
  | cons l a ih =>
    rw [ew_cons, mul_assoc, ← Egen_mk, h3, rhoBar_mk, ih]
    rfl

include h3 h4 h5 in
theorem unique_normal (c' b : List I) :
    B' (mk RD q lam 1) (mk RD q lam (ew (negW c' ++ posW b))) =
      qp q (rcx C (RD.ellOf lam) (negW c')) *
        fF C q c (word (FreeMonoid.ofList b)) (word (FreeMonoid.ofList c'.reverse)) := by
  rw [h5, ew_append, unique_move h3, ← ew_nil,
    R_of_mem_Fg _ _ (ew_mem_Fg ([] : List (Bool × I))), map_smul, map_smul, smul_eq_mul, ρW_negW,
    ew_nil, mul_one]
  simp only [posMS_nil, negMS_nil, msA_zero, add_zero, sub_zero]
  congr 1
  have e1 : ew (posW b) = posF (word (FreeMonoid.ofList b) : PreF K I) := by
    rw [posF_word, FreeMonoid.toList_ofList]
  have e2 : ew (posW c'.reverse) = posF (word (FreeMonoid.ofList c'.reverse) : PreF K I) := by
    rw [posF_word, FreeMonoid.toList_ofList]
  rw [e1, e2, h4]

include h3 h4 h5 in
theorem unique_one (w : List (Bool × I)) :
    B' (mk RD q lam 1) (mk RD q lam (ew w)) =
      formU RD q c hq lam (mk RD q lam 1) (mk RD q lam (ew w)) := by
  induction w using normal_induction with
  | hN c' b =>
    rw [unique_normal h3 h4 h5, unique_normal (formU_E_left RD q c hq lam)
      (formU_posF RD q c hq lam) (formU_symm RD q c hq lam)]
  | hS a i j b h1 h2 =>
    rw [mk_comm, map_add, map_add, map_smul, map_smul, h1, h2]

include h3 h4 h5 in
/-- **KL III Prop. 2.2, uniqueness** (for one block `U̇ 1_λ`): a bilinear form on `U̇ 1_λ`
satisfying (iii) for the generators `E_{±i}`, (iv) and (v) is `formU`. -/
theorem formU_unique : B' = formU RD q c hq lam := by
  refine U1_bilin_ext RD q fun s t => ?_
  have hs : ∀ (F : U1 RD q lam →ₗ[K] U1 RD q lam →ₗ[K] K)
      (hF : ∀ l x y, F (Egen RD q lam l x) y = F x (rhoBar RD q lam l y)),
      F (mk RD q lam (ew s)) (mk RD q lam (ew t)) =
        F (mk RD q lam 1) (mk RD q lam (R C q (RD.ellOf lam) s (ew t))) := by
    intro F hF
    have := unique_move hF s 1 (ew t)
    rwa [mul_one] at this
  rw [hs B' h3, hs _ (formU_E_left RD q c hq lam)]
  generalize R C q (RD.ellOf lam) s (ew t) = z
  induction z using Free.induction with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, map_add, hx, hy]
  | smul_ew w r => rw [map_smul, map_smul, map_smul, unique_one hq h3 h4 h5]

end Unique

end UDot

end Categorification.QuantumGroup

end
