/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.QuantumGroup.UDotAlgebra

/-!
# The integral form `_𝒜 U̇`

Khovanov–Lauda III, arXiv:0807.3250v1, §2.1.3 and §2.1.4: `_𝒜 U̇` is the
`ℤ[q, q⁻¹]`-subalgebra of `U̇` generated by the products of divided powers
`E_i^{(a)} 1_λ`, `F_i^{(a)} 1_λ`, where `E_{εi}^{(a)} = E_{εi}^a / [a]_i^!` (eq. (2.14)).

A *divided powers signed sequence* (dpss) `i = (ε₁i₁^{(a₁)}, …, εₘiₘ^{(aₘ)})` (eq. (2.13)) is
recorded as a list `d : List (Bool × I × ℕ)`; `UDot.dpW d = E_{ε₁i₁}^{(a₁)} ⋯ E_{εₘiₘ}^{(aₘ)}`
and `UDot.E1dp d λ = E_i 1_λ ∈ U̇` (eq. (2.17)), with left weight `λ + Σ_r ε_r a_r (i_r)_X`.

## Main results

* `UDot.AUD RD q` — `_𝒜 U̇`, the (non-unital) subring of `U̇` generated by the elements
  `q^n E_i 1_λ` for dpss `i`;
* `UDot.E1dp_mul_E1dp` — `(E_i 1_μ)(E_j 1_λ) = δ_{μ, λ + |j|_X} E_{ij} 1_λ`;
* `UDot.qpow_smul_mem_AUD` — `_𝒜 U̇` is stable under multiplication by `q^{±1}`, so it is a
  `ℤ[q, q⁻¹]`-subalgebra;
* `UDot.one_mem_AUD`, `UDot.E1_mem_AUD`, `UDot.E1dp_mem_AUD` — it contains the `1_λ`, the
  `E_t 1_λ` (so it spans `U̇` over `K`) and the `E_i 1_λ` for dpss `i`.
-/

noncomputable section

namespace Categorification.QuantumGroup

open scoped Classical
open PreF

namespace UDot

variable {I : Type*} {K : Type*} [Field K]
variable {C : CartanDatum I} {X Y : Type*} [AddCommGroup X] [AddCommGroup Y]
  (RD : RootDatum C X Y) (q : Kˣ)

variable (C) in
/-- The divided power `E_{εi}^{(a)} = E_{εi}^a / [a]_i^!` in the free algebra (KL III (2.14)). -/
def dpE (x : Bool × I × ℕ) : Free K I :=
  (qfact (qi C q x.2.1) x.2.2)⁻¹ • ew (List.replicate x.2.2 (x.1, x.2.1))

variable (C) in
/-- `E_{ε₁i₁}^{(a₁)} ⋯ E_{εₘiₘ}^{(aₘ)}` for a dpss (KL III (2.16)). -/
def dpW (d : List (Bool × I × ℕ)) : Free K I := (d.map (dpE C q)).prod

/-- The weight `Σ_r ε_r a_r (i_r)_X` of a dpss. -/
def wdp (d : List (Bool × I × ℕ)) : X := (d.map fun x => (sgn x.1 * x.2.2) • RD.iX x.2.1).sum

theorem FX_mul {μ ν : X} {x y : Free K I} (hx : x ∈ FX K RD μ) (hy : y ∈ FX K RD ν) :
    x * y ∈ FX K RD (μ + ν) := by
  refine supp_mul_mem (fun u hu w hw => ?_) hx hy
  simp only [Set.mem_setOf_eq, FreeMonoid.toList_mul, RD.wX_append] at hu hw ⊢
  rw [hu, hw]

theorem wX_replicate (b : Bool) (i : I) (a : ℕ) :
    RD.wX (List.replicate a (b, i)) = (sgn b * a) • RD.iX i := by
  induction a with
  | zero => simp
  | succ a ih =>
    rw [List.replicate_succ, RD.wX_cons, ih]
    push_cast
    rw [mul_add, add_smul, mul_one, add_comm]

theorem dpE_mem_FX (x : Bool × I × ℕ) :
    dpE C q x ∈ FX K RD ((sgn x.1 * x.2.2) • RD.iX x.2.1) := by
  refine Submodule.smul_mem _ _ ?_
  rw [← wX_replicate]
  exact ew_mem_FX RD _

theorem dpW_mem_FX (d : List (Bool × I × ℕ)) : dpW C q d ∈ FX K RD (wdp RD d) := by
  induction d with
  | nil => exact ew_mem_FX (K := K) RD []
  | cons x d ih =>
    rw [dpW, List.map_cons, List.prod_cons]
    have := FX_mul RD (dpE_mem_FX RD q x) ih
    simpa [wdp] using this

theorem dpW_append (d d' : List (Bool × I × ℕ)) :
    dpW C q (d ++ d') = dpW C q d * dpW C q d' := by
  rw [dpW, dpW, dpW, List.map_append, List.prod_append]

/-- `E_i 1_λ ∈ U̇` for a dpss `i` (KL III (2.17)). -/
def E1dp (d : List (Bool × I × ℕ)) (lam : X) : UD RD q := ofB RD q lam (mk RD q lam (dpW C q d))

/-- `(E_i 1_μ)(E_j 1_λ) = δ_{μ, λ + |j|_X} E_{ij} 1_λ` for dpss `i`, `j`. -/
theorem E1dp_mul_E1dp (d d' : List (Bool × I × ℕ)) (mu lam : X) :
    E1dp RD q d mu * E1dp RD q d' lam =
      if lam + wdp RD d' = mu then E1dp RD q (d ++ d') lam else 0 := by
  rw [E1dp, E1dp, ofB_mul_ofB, mulU_mk, projF, diagX_of_mem_FX RD _ (dpW_mem_FX RD q d')]
  split_ifs
  · rw [one_smul, ← dpW_append]; rfl
  · simp

/-- The generators `q^n E_i 1_λ` of `_𝒜 U̇`. -/
def AUDgen : Set (UD RD q) :=
  {x | ∃ (n : ℤ) (d : List (Bool × I × ℕ)) (lam : X), x = qp q n • E1dp RD q d lam}

/-- **The integral form `_𝒜 U̇`** (KL III §2.1.3): the subring of `U̇` generated by the
`q^n E_i 1_λ`, `i` a dpss. -/
def AUD : NonUnitalSubring (UD RD q) := NonUnitalSubring.closure (AUDgen RD q)

theorem gen_mem_AUD (n : ℤ) (d : List (Bool × I × ℕ)) (lam : X) :
    qp q n • E1dp RD q d lam ∈ AUD RD q :=
  NonUnitalSubring.subset_closure ⟨n, d, lam, rfl⟩

theorem E1dp_mem_AUD (d : List (Bool × I × ℕ)) (lam : X) : E1dp RD q d lam ∈ AUD RD q := by
  simpa using gen_mem_AUD RD q 0 d lam

/-- `1_λ ∈ _𝒜 U̇`. -/
theorem one_mem_AUD (lam : X) : one RD q lam ∈ AUD RD q := E1dp_mem_AUD RD q [] lam

theorem dpE_one (b : Bool) (i : I) : dpE C q (b, i, 1) = ew [(b, i)] := by
  simp [dpE, qfact]

/-- `E_t 1_λ ∈ _𝒜 U̇` for every signed sequence `t`; in particular `_𝒜 U̇` spans `U̇`. -/
theorem E1_mem_AUD (t : List (Bool × I)) (lam : X) : E1 RD q t lam ∈ AUD RD q := by
  have : dpW C q (t.map fun l => (l.1, l.2, 1)) = (ew t : Free K I) := by
    induction t with
    | nil => rfl
    | cons l t ih =>
      rw [List.map_cons, ← List.singleton_append, dpW_append, ih, ew_cons]
      simp [dpW, dpE_one]
  have h := E1dp_mem_AUD RD q (t.map fun l => (l.1, l.2, 1)) lam
  rwa [E1dp, this] at h

/-- `_𝒜 U̇` is stable under `q^n`, `n ∈ ℤ`: it is a `ℤ[q, q⁻¹]`-subalgebra. -/
theorem qpow_smul_mem_AUD (n : ℤ) {x : UD RD q} (hx : x ∈ AUD RD q) : qp q n • x ∈ AUD RD q := by
  induction hx using NonUnitalSubring.closure_induction with
  | mem x hx =>
    obtain ⟨m, d, lam, rfl⟩ := hx
    rw [smul_smul, ← qp_add]
    exact gen_mem_AUD RD q _ d lam
  | zero => rw [smul_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [smul_add]; exact add_mem hx hy
  | neg x _ hx => rw [smul_neg]; exact neg_mem hx
  | mul x y _ hy' hx _ => rw [← smul_mul_assoc]; exact mul_mem hx hy'

end UDot

end Categorification.QuantumGroup

end
