/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.QuantumGroup.UDotAlgebra

/-!
# The bilinear form on `U̇` (KL III Proposition 2.2)

Khovanov–Lauda III, arXiv:0807.3250v1, §2.1.3, Proposition 2.2 (after Lusztig 26.1.1):
there exists a unique pairing `( , ) : U̇ × U̇ → ℚ(q)` such that

* (i) `( , )` is bilinear;
* (ii) `(1_{λ₁} x 1_{λ₂}, 1_{λ₁'} y 1_{λ₂'}) = 0` unless `λ₁ = λ₁'` and `λ₂ = λ₂'`;
* (iii) `(ux, y) = (x, ρ̄(u) y)` for `u ∈ U`;
* (iv) `(x 1_λ, x' 1_λ) = (x, x')` for `x, x' ∈ f ≅ U⁺`;
* (v) `(x, y) = (y, x)`.

(The PDF-to-text rendering of (iii) drops the bar: the TeX source has `\overline{\rho}`.)

## Formalisation

`U̇ = ⊕_λ U̇ 1_λ` is `UDot.UD RD q` (`Categorification.QuantumGroup.UDotAlgebra`), and the form is
`UDot.formUD RD q c hq`, assembled from the forms `UDot.formU` on the blocks. The ring is any
field `K` with `q ∈ Kˣ` not a root of unity, and `c i = (θ_i, θ_i)` is arbitrary (KL III:
`K = ℚ(q)`, `c i = (1 - q_i²)⁻¹`; see `UDot.KL3`).

* (i) is built into the type (`UD →ₗ[K] UD →ₗ[K] K`);
* (ii) is stated with `UDot.idem λ₁ λ₂ x = 1_{λ₁} x 1_{λ₂}` (`UDot.idem_eq`);
* (iii) is stated for the generators `u = E_{±i}` (`UDot.UE`) and `u = K_μ` (`UDot.UK`), with
  `ρ̄(E_{εi}) = q_i⁻¹ K̃_{-εi} E_{-εi}` (`UDot.Urho`) and `ρ̄(K_μ) = K_μ`; as `U` is generated by
  these and `ρ̄` is an anti-automorphism, this is equivalent to (iii) for all `u ∈ U`;
* (iv) is stated for `x, x' ∈ 'f` (the form on `f` is induced from that on `'f`);
* (v) is `UDot.formUD_symm`.

## Main results

* `UDot.IsKLPairing` — the conditions (ii)–(v);
* `UDot.formUD_isKLPairing` — `formUD` satisfies them (existence);
* `UDot.eq_formUD_of_isKLPairing` — uniqueness;
* **`UDot.prop_2_2`** — `∃! B, IsKLPairing B`.
-/

noncomputable section

namespace Categorification.QuantumGroup

open scoped Classical
open PreF

namespace UDot

variable {I : Type*} {K : Type*} [Field K]
variable {C : CartanDatum I} {X Y : Type*} [AddCommGroup X] [AddCommGroup Y]
  (RD : RootDatum C X Y) (q : Kˣ) (c : I → K)

/-! ### The action of `U` on `U̇` -/

/-- The blockwise operator `⊕_λ f_λ` on `U̇ = ⊕_λ U̇ 1_λ`. -/
def blockMap (f : ∀ lam, U1 RD q lam →ₗ[K] U1 RD q lam) : UD RD q →ₗ[K] UD RD q :=
  DFinsupp.mapRange.linearMap f

theorem blockMap_ofB (f : ∀ lam, U1 RD q lam →ₗ[K] U1 RD q lam) (lam : X) (z : U1 RD q lam) :
    blockMap RD q f (ofB RD q lam z) = ofB RD q lam (f lam z) := by
  change DFinsupp.mapRange (fun i x => f i x) (fun i => map_zero (f i)) (DFinsupp.single lam z) =
    DFinsupp.single lam (f lam z)
  exact DFinsupp.mapRange_single

theorem compB_blockMap (f : ∀ lam, U1 RD q lam →ₗ[K] U1 RD q lam) (lam : X) (x : UD RD q) :
    compB RD q lam (blockMap RD q f x) = f lam (compB RD q lam x) := by
  change (DFinsupp.mapRange (fun i x => f i x) (fun i => map_zero (f i)) x) lam = f lam (x lam)
  exact DFinsupp.mapRange_apply _ _ _ _

/-- Left multiplication by `E_{εi} ∈ U` on `U̇`. -/
def UE (l : Bool × I) : UD RD q →ₗ[K] UD RD q := blockMap RD q fun lam => Egen RD q lam l

/-- Left multiplication by `K_μ ∈ U` (`μ ∈ Y`) on `U̇`. -/
def UK (μ : Y) : UD RD q →ₗ[K] UD RD q := blockMap RD q fun lam => Kact RD q lam μ

/-- Left multiplication by `ρ̄(E_{εi}) = q_i⁻¹ K̃_{-εi} E_{-εi} ∈ U` on `U̇`. -/
def Urho (l : Bool × I) : UD RD q →ₗ[K] UD RD q := blockMap RD q fun lam => rhoBar RD q lam l

theorem UE_E1 (l : Bool × I) (t : List (Bool × I)) (lam : X) :
    UE RD q l (E1 RD q t lam) = E1 RD q (l :: t) lam := by
  rw [UE, E1, blockMap_ofB, Egen_mk, ← ew_cons]; rfl

/-! ### The form -/

variable (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1)

/-- **The bilinear form `( , )` on `U̇`** (KL III Proposition 2.2):
`(x, y) = Σ_λ (x 1_λ, y 1_λ)`. -/
def formUD : UD RD q →ₗ[K] UD RD q →ₗ[K] K :=
  DirectSum.toModule K X _ fun lam => (formU RD q c hq lam).compl₂ (compB RD q lam)

theorem formUD_ofB (lam : X) (x : U1 RD q lam) (y : UD RD q) :
    formUD RD q c hq (ofB RD q lam x) y = formU RD q c hq lam x (compB RD q lam y) := by
  rw [formUD, ofB, DirectSum.toModule_lof, LinearMap.compl₂_apply]

theorem formUD_ofB_ofB (lam : X) (x y : U1 RD q lam) :
    formUD RD q c hq (ofB RD q lam x) (ofB RD q lam y) = formU RD q c hq lam x y := by
  rw [formUD_ofB, compB_ofB_self]

theorem formUD_ofB_ofB_ne {lam lam' : X} (h : lam' ≠ lam) (x : U1 RD q lam) (y : U1 RD q lam') :
    formUD RD q c hq (ofB RD q lam x) (ofB RD q lam' y) = 0 := by
  rw [formUD_ofB, compB_ofB_ne RD q h, map_zero]

theorem formUD_E1_E1 (s t : List (Bool × I)) (lam lam' : X) :
    formUD RD q c hq (E1 RD q s lam) (E1 RD q t lam') =
      if lam = lam' then B C q c (RD.ellOf lam) (ew s) (ew t) else 0 := by
  split_ifs with h
  · subst h; rw [E1, E1, formUD_ofB_ofB, formU_mk]
  · rw [E1, E1, formUD_ofB_ofB_ne RD q c hq (Ne.symm h)]

/-- Bilinear forms on `U̇` agreeing on the `E_s 1_λ, E_t 1_λ'` agree. -/
theorem UD_bilin_ext {F G : UD RD q →ₗ[K] UD RD q →ₗ[K] K}
    (h : ∀ s t lam lam', F (E1 RD q s lam) (E1 RD q t lam') = G (E1 RD q s lam) (E1 RD q t lam')) :
    F = G := by
  refine LinearMap.ext fun x => ?_
  induction x using E1_induction with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy]
  | smul_E1 r s lam =>
    rw [map_smul, map_smul]
    congr 1
    refine LinearMap.ext fun y => ?_
    induction y using E1_induction with
    | zero => simp
    | add x y hx hy => rw [map_add, map_add, hx, hy]
    | smul_E1 r' t lam' => rw [map_smul, map_smul, h]

theorem wX_eq_of_balanced {s t : List (Bool × I)} (h : Balanced s t) : RD.wX s = RD.wX t := by
  rw [RD.wX_eq, RD.wX_eq]
  have := congrArg (fun ν => (ν.map RD.iX).sum) h
  simp only [Multiset.map_add, Multiset.sum_add] at this
  rw [sub_eq_sub_iff_add_eq_add, this]

/-! ### Proposition 2.2 -/

/-- The conditions (ii)–(v) of KL III Proposition 2.2 on a bilinear form on `U̇` (condition (i)
is built into the type). -/
structure IsKLPairing (F : UD RD q →ₗ[K] UD RD q →ₗ[K] K) : Prop where
  /-- (ii) `(1_{λ₁} x 1_{λ₂}, 1_{λ₁'} y 1_{λ₂'}) = 0` unless `λ₁ = λ₁'` and `λ₂ = λ₂'`. -/
  weight : ∀ (lam1 lam2 lam1' lam2' : X) (x y : UD RD q), ¬ (lam1 = lam1' ∧ lam2 = lam2') →
    F (idem RD q lam1 lam2 x) (idem RD q lam1' lam2' y) = 0
  /-- (iii) for `u = E_{±i}`: `(E_{εi} x, y) = (x, ρ̄(E_{εi}) y)`. -/
  rho_E : ∀ (l : Bool × I) (x y : UD RD q), F (UE RD q l x) y = F x (Urho RD q l y)
  /-- (iii) for `u = K_μ`: `(K_μ x, y) = (x, K_μ y)`. -/
  rho_K : ∀ (μ : Y) (x y : UD RD q), F (UK RD q μ x) y = F x (UK RD q μ y)
  /-- (iv) `(x⁺ 1_λ, x'⁺ 1_λ) = (x, x')` for `x, x' ∈ 'f`. -/
  posF : ∀ (lam : X) (x x' : PreF K I),
    F (ofB RD q lam (mk RD q lam (posF x))) (ofB RD q lam (mk RD q lam (posF x'))) = fF C q c x x'
  /-- (v) symmetry. -/
  symm : ∀ x y : UD RD q, F x y = F y x

theorem formUD_weight (lam1 lam2 lam1' lam2' : X) (x y : UD RD q)
    (h : ¬ (lam1 = lam1' ∧ lam2 = lam2')) :
    formUD RD q c hq (idem RD q lam1 lam2 x) (idem RD q lam1' lam2' y) = 0 := by
  have : (formUD RD q c hq).compl₁₂ (idem RD q lam1 lam2) (idem RD q lam1' lam2') = 0 := by
    refine UD_bilin_ext RD q fun s t lam lam' => ?_
    simp only [LinearMap.compl₁₂_apply, idem_E1, LinearMap.zero_apply]
    split_ifs with h1 h2
    · rw [formUD_E1_E1]
      split_ifs with h3
      · refine B_eq_zero_of_not_balanced _ fun hb => h ⟨?_, ?_⟩
        · rw [← h1.2, ← h2.2, h3, wX_eq_of_balanced RD hb]
        · rw [← h1.1, ← h2.1, h3]
      · rfl
    all_goals simp
  exact LinearMap.congr_fun (LinearMap.congr_fun this x) y

theorem formUD_rho_E (l : Bool × I) (x y : UD RD q) :
    formUD RD q c hq (UE RD q l x) y = formUD RD q c hq x (Urho RD q l y) := by
  induction x using UD_induction with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx']
  | ofB lam z =>
    rw [UE, blockMap_ofB, formUD_ofB, formUD_ofB, formU_E_left, Urho, compB_blockMap]

theorem formUD_rho_K (μ : Y) (x y : UD RD q) :
    formUD RD q c hq (UK RD q μ x) y = formUD RD q c hq x (UK RD q μ y) := by
  induction x using UD_induction with
  | zero => simp
  | add x x' hx hx' => simp only [map_add, LinearMap.add_apply, hx, hx']
  | ofB lam z =>
    rw [UK, blockMap_ofB, formUD_ofB, formUD_ofB, formU_K_left, compB_blockMap]

theorem formUD_posF (lam : X) (x x' : PreF K I) :
    formUD RD q c hq (ofB RD q lam (mk RD q lam (posF x))) (ofB RD q lam (mk RD q lam (posF x'))) =
      fF C q c x x' := by
  rw [formUD_ofB_ofB, formU_posF]

/-- **KL III Prop. 2.2 (v)**: the form on `U̇` is symmetric. -/
theorem formUD_symm (x y : UD RD q) : formUD RD q c hq x y = formUD RD q c hq y x := by
  have : (formUD RD q c hq).flip = formUD RD q c hq := by
    refine UD_bilin_ext RD q fun s t lam lam' => ?_
    rw [LinearMap.flip_apply, formUD_E1_E1, formUD_E1_E1]
    split_ifs with h1 h2 h2
    · subst h1; rw [B_symm]
    · exact absurd h1.symm h2
    · exact absurd h2.symm h1
    · rfl
  have h := LinearMap.congr_fun (LinearMap.congr_fun this y) x
  rw [LinearMap.flip_apply] at h
  exact h

/-- **KL III Proposition 2.2, existence**: `formUD` satisfies (i)–(v). -/
theorem formUD_isKLPairing : IsKLPairing RD q c (formUD RD q c hq) where
  weight := formUD_weight RD q c hq
  rho_E := formUD_rho_E RD q c hq
  rho_K := formUD_rho_K RD q c hq
  posF := formUD_posF RD q c hq
  symm := formUD_symm RD q c hq

/-- **KL III Proposition 2.2, uniqueness**. -/
theorem eq_formUD_of_isKLPairing {F : UD RD q →ₗ[K] UD RD q →ₗ[K] K} (hF : IsKLPairing RD q c F) :
    F = formUD RD q c hq := by
  refine UD_bilin_ext RD q fun s t lam lam' => ?_
  by_cases h : lam = lam'
  · subst h
    -- restrict to the block `U̇ 1_λ`
    have hB := formU_unique (RD := RD) (q := q) (c := c) (lam := lam) hq
      (B' := F.compl₁₂ (ofB RD q lam) (ofB RD q lam))
      (fun l x y => by
        simp only [LinearMap.compl₁₂_apply]
        have := hF.rho_E l (ofB RD q lam x) (ofB RD q lam y)
        rwa [UE, blockMap_ofB, Urho, blockMap_ofB] at this)
      (fun x x' => by simp only [LinearMap.compl₁₂_apply]; exact hF.posF lam x x')
      (fun x y => by simp only [LinearMap.compl₁₂_apply]; exact hF.symm _ _)
    have := LinearMap.congr_fun (LinearMap.congr_fun hB (mk RD q lam (ew s))) (mk RD q lam (ew t))
    simp only [LinearMap.compl₁₂_apply] at this
    rw [E1, E1, this, formUD_ofB_ofB]
  · have e1 : E1 RD q s lam = idem RD q (lam + RD.wX s) lam (E1 RD q s lam) := by
      rw [idem_E1, if_pos ⟨rfl, rfl⟩]
    have e2 : E1 RD q t lam' = idem RD q (lam' + RD.wX t) lam' (E1 RD q t lam') := by
      rw [idem_E1, if_pos ⟨rfl, rfl⟩]
    rw [e1, e2, hF.weight _ _ _ _ _ _ (fun h' => h h'.2),
      formUD_weight RD q c hq _ _ _ _ _ _ (fun h' => h h'.2)]

/-- **Khovanov–Lauda III, Proposition 2.2** (after Lusztig 26.1.1): there is a unique bilinear
pairing `( , )` on `U̇` with properties (ii)–(v) (property (i), bilinearity, being built into
the type). -/
theorem prop_2_2 (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) : ∃! F : UD RD q →ₗ[K] UD RD q →ₗ[K] K, IsKLPairing RD q c F :=
  ⟨formUD RD q c hq, formUD_isKLPairing RD q c hq,
    fun _ hF => eq_formUD_of_isKLPairing RD q c hq hF⟩

end UDot

end Categorification.QuantumGroup

end
