/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.QuantumGroup.UDotSymm

/-!
# The quantum Serre elements and the quantum derivations

Khovanov–Lauda III, arXiv:0807.3250v1, §2.1.1, relation (v) of `U`:
`Σ_{a+b = -⟨i, j_X⟩ + 1} (-1)^a E_i^{(a)} E_j E_i^{(b)} = 0` (and likewise for `F`), with the
divided powers `E_i^{(a)} = E_i^a / [a]_i^!` taken in `q_i`. The corresponding element of `'f`
is `UDot.serreKL C q i j`; it is the reversal of Lusztig's `PreF.serreDiv` (1.4.3), and equal
to it up to the sign `(-1)^N`.

We show that the quantum derivations `D_i^{(n)}` of `Categorification.QuantumGroup.UDotModel`
kill the Serre elements (`UDot.D_serreDiv`): `(q_i - q_i⁻¹) D_i^{(n)} = q_i^n d_i - q_i^{-n} d̄_i`
for the twisted derivations `d_i` of `'f` at `v = q⁻¹` and `v = q` (`UDot.D_eq_d`), and both
kill Lusztig's Serre element (Lusztig 1.4.3; `Categorification.QuantumGroup.Serre`). Hence the
two-sided ideal `UDot.Jf` of `'f` generated by the Serre elements is stable under every
`D_i^{(n)}`, and it lies in the radical of the form (`UDot.Jf_le_radical`).

Throughout, `q` is assumed not to be a root of unity (`hq`).
-/

noncomputable section

namespace Categorification.QuantumGroup

open scoped Classical
open PreF Finset

namespace UDot

variable {I : Type*} {K : Type*} [Field K] (C : CartanDatum I) (q : Kˣ)

/-! ### Divided powers at `q` and `q⁻¹` -/

theorem qint_inv (t : Kˣ) (n : ℕ) : qint t⁻¹ n = qint t n := by
  rw [qint_eq_sum, qint_eq_sum, ← sum_range_reflect]
  refine sum_congr rfl fun k hk => ?_
  rw [mem_range] at hk
  rw [inv_zpow']
  congr 2
  push_cast [Nat.sub_sub, Nat.cast_sub (by omega : 1 + k ≤ n)]
  ring

theorem qfact_inv (t : Kˣ) (n : ℕ) : qfact t⁻¹ n = qfact t n := by
  simp [qfact, qint_inv]

theorem dpow_inv (i : I) (a : ℕ) : dpow C.dot q⁻¹ i a = dpow C.dot q i a := by
  rw [dpow, dpow, vi, vi, inv_zpow', zpow_neg, qfact_inv]

theorem serreDiv_inv (i j : I) (N : ℕ) : serreDiv C.dot q⁻¹ i j N = serreDiv C.dot q i j N := by
  simp only [serreDiv, dpow_inv]

/-! ### KL III's Serre element -/

/-- KL III's Serre element `Σ_{a+b=N} (-1)^a θ_i^{(a)} θ_j θ_i^{(b)}`, `N = 1 - ⟨i, j_X⟩`
(KL III §2.1.1, relation (v)). -/
def serreKL (i j : I) : PreF K I :=
  ∑ p ∈ antidiagonal (C.serreN i j), ((-1 : K) ^ p.1) • (dpow C.dot q i p.1 * θ j * dpow C.dot q i p.2)

theorem rev_θ_pow (i : I) (a : ℕ) : rev ((θ i : PreF K I) ^ a) = θ i ^ a := by
  induction a with
  | zero => rw [pow_zero, rev_one]
  | succ a ih => rw [pow_succ, rev_mul, rev_θ, ih, ← pow_succ', pow_succ]

theorem rev_dpow (i : I) (a : ℕ) : rev (dpow C.dot q i a) = dpow C.dot q i a := by
  rw [dpow, map_smul, rev_θ_pow]

/-- KL III's Serre element is the reversal of Lusztig's. -/
theorem rev_serreDiv (i j : I) : rev (serreDiv C.dot q i j (C.serreN i j)) = serreKL C q i j := by
  rw [serreDiv, serreKL, map_sum, ← Finset.Nat.sum_antidiagonal_swap]
  refine sum_congr rfl fun p _ => ?_
  rw [map_smul, rev_mul, rev_mul, rev_dpow, rev_dpow, rev_θ, mul_assoc]
  rfl

theorem rev_serreKL (i j : I) : rev (serreKL C q i j) = serreDiv C.dot q i j (C.serreN i j) := by
  rw [← rev_serreDiv, rev_rev]

/-- KL III's Serre element is `(-1)^N` times Lusztig's. -/
theorem serreKL_eq (i j : I) :
    serreKL C q i j = ((-1 : K) ^ C.serreN i j) • serreDiv C.dot q i j (C.serreN i j) := by
  rw [serreKL, serreDiv, smul_sum]
  refine sum_congr rfl fun p hp => ?_
  rw [mem_antidiagonal] at hp
  rw [smul_smul, ← hp, pow_add]
  congr 1
  rw [mul_assoc, ← pow_add, ← two_mul, pow_mul, neg_one_sq, one_pow, mul_one]

theorem serreDiv_mem_grade (i j : I) (N : ℕ) :
    serreDiv C.dot q i j N ∈ grade K (j ::ₘ Multiset.replicate N i) := by
  rw [serreDiv]
  refine Submodule.sum_mem _ fun p hp => Submodule.smul_mem _ _ ?_
  rw [mem_antidiagonal] at hp
  have hd : ∀ a, dpow C.dot q i a ∈ grade K (Multiset.replicate a i) := by
    intro a
    refine Submodule.smul_mem _ _ ?_
    induction a with
    | zero => rw [pow_zero, Multiset.replicate_zero]; exact SetLike.GradedOne.one_mem
    | succ a ih =>
      rw [pow_succ, Multiset.replicate_succ, ← Multiset.singleton_add, add_comm]
      exact SetLike.mul_mem_graded ih (θ_mem_grade i)
  have e : j ::ₘ Multiset.replicate N i =
      Multiset.replicate p.1 i + {j} + Multiset.replicate p.2 i := by
    rw [← hp, Multiset.replicate_add, ← Multiset.singleton_add]; abel
  rw [e]
  exact SetLike.mul_mem_graded (SetLike.mul_mem_graded (hd _) (θ_mem_grade j)) (hd _)

/-! ### The twisted derivations kill the Serre elements -/

variable {C q}

theorem d_serreSeq_eq_zero (v : Kˣ) {i j : I} (hij : i ≠ j) (k : I) :
    d C.dot v k (serreSeq C.dot v i j (C.serreN i j) : PreF K I) = 0 := by
  obtain ⟨M, hM⟩ : ∃ M, C.serreN i j = M + 1 := ⟨C.serreN i j - 1, by
    have := C.one_le_serreN hij; omega⟩
  have hN := C.two_mul_dot_eq hij
  rw [hM] at hN ⊢
  by_cases hki : i = k
  · subst hki
    rw [d_serreSeq_left i j hij, serreβ_eq_zero C.symm i j hN, zero_smul]
  · by_cases hkj : j = k
    · subst hkj; exact d_serreSeq_right C.symm i j hij M
    · exact d_serreSeq_of_ne i j k hki hkj _

theorem d_serreDiv_eq_zero (v : Kˣ) {i j : I} (hij : i ≠ j)
    (hqf : qfact (vi C.dot v i) (C.serreN i j) ≠ 0) (k : I) :
    d C.dot v k (serreDiv C.dot v i j (C.serreN i j) : PreF K I) = 0 := by
  have h := d_serreSeq_eq_zero (C := C) v hij k
  rw [serreSeq_eq_qfact_smul_serreDiv C.symm i j (C.dot_self_even i) (C.two_mul_dot_eq hij) hqf,
    map_smul] at h
  exact (smul_eq_zero.1 h).resolve_left hqf

theorem qbr_mul (t : Kˣ) (ht : (t : K) - ((t⁻¹ : Kˣ) : K) ≠ 0) (n : ℤ) :
    ((t : K) - ((t⁻¹ : Kˣ) : K)) * qbr t n = ((t ^ n : Kˣ) : K) - ((t ^ (-n) : Kˣ) : K) := by
  rw [qbr, mul_div_cancel₀ _ ht]

theorem qi_zpow_sub_A (i j : I) (n : ℤ) :
    (((qi C q i) ^ (n - A C i j) : Kˣ) : K) =
      (((qi C q i) ^ n : Kˣ) : K) * ((q⁻¹ ^ C.dot j i : Kˣ) : K) := by
  rw [← Units.val_mul]
  congr 1
  simp only [qi, ← zpow_mul, inv_zpow', ← zpow_add]
  congr 1
  rw [C.symm j i, ← di_mul_A]
  ring

theorem qi_zpow_neg_sub_A (i j : I) (n : ℤ) :
    (((qi C q i) ^ (-(n - A C i j)) : Kˣ) : K) =
      (((qi C q i) ^ (-n) : Kˣ) : K) * ((q ^ C.dot j i : Kˣ) : K) := by
  rw [← Units.val_mul]
  congr 1
  simp only [qi, ← zpow_mul, ← zpow_add]
  congr 1
  rw [C.symm j i, ← di_mul_A]
  ring

/-- `(q_i - q_i⁻¹) D_i^{(n)} = q_i^n d_i^{(v = q⁻¹)} - q_i^{-n} d_i^{(v = q)}` on words. -/
theorem D_eq_d_word (i : I) (ht : ((qi C q i : Kˣ) : K) - ((qi C q i)⁻¹ : Kˣ) ≠ 0)
    (w : FreeMonoid I) (n : ℤ) :
    (((qi C q i : Kˣ) : K) - ((qi C q i)⁻¹ : Kˣ)) • D C q i n (word w) =
      (((qi C q i) ^ n : Kˣ) : K) • d C.dot q⁻¹ i (word w) -
        (((qi C q i) ^ (-n) : Kˣ) : K) • d C.dot q i (word w) := by
  induction w using FreeMonoid.inductionOn' generalizing n with
  | one => simp
  | mul_of j u ih =>
    rw [D_word_of_mul, d_word_of_mul, d_word_of_mul, smul_add, ← mul_smul_comm, ih (n - A C i j),
      qi_zpow_sub_A, qi_zpow_neg_sub_A]
    have hq' := qbr_mul (qi C q i) ht n
    split_ifs
    · rw [smul_smul, hq']
      simp only [mul_sub, mul_smul_comm, smul_add, smul_smul, mul_comm]
      module
    · simp only [mul_sub, mul_smul_comm, smul_add, smul_smul, mul_comm, smul_zero, zero_add]

/-- `(q_i - q_i⁻¹) D_i^{(n)} = q_i^n d_i^{(v = q⁻¹)} - q_i^{-n} d_i^{(v = q)}`. -/
theorem D_eq_d (i : I) (ht : ((qi C q i : Kˣ) : K) - ((qi C q i)⁻¹ : Kˣ) ≠ 0) (n : ℤ)
    (x : PreF K I) :
    (((qi C q i : Kˣ) : K) - ((qi C q i)⁻¹ : Kˣ)) • D C q i n x =
      (((qi C q i) ^ n : Kˣ) : K) • d C.dot q⁻¹ i x -
        (((qi C q i) ^ (-n) : Kˣ) : K) • d C.dot q i x := by
  induction x using induction_linear with
  | zero => simp
  | add x y hx hy => simp only [map_add, smul_add, hx, hy]; abel
  | smul_word w r =>
    simp only [map_smul]
    rw [smul_comm, D_eq_d_word i ht, smul_sub, smul_comm r, smul_comm r]

/-! ### `q` not a root of unity -/

variable (q) in
theorem zpow_ne_one_of_hq (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) {n : ℤ} (hn : n ≠ 0) : q ^ n ≠ 1 := by
  rcases Int.eq_nat_or_neg n with ⟨m, rfl | rfl⟩
  · rw [zpow_natCast]; exact hq m (by omega)
  · rw [zpow_neg, zpow_natCast, Ne, inv_eq_one]; exact hq m (by omega)

variable (C q) in
theorem qfact_vi_ne_zero (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) (i : I) (a : ℕ) :
    qfact (vi C.dot q i) a ≠ 0 := by
  refine Categorification.QuantumGroup.qfact_ne_zero (fun m hm => ?_) a
  rw [vi, ← zpow_natCast, ← zpow_mul]
  refine zpow_ne_one_of_hq q hq (mul_ne_zero ?_ (by exact_mod_cast hm.ne'))
  have := di_pos C i
  unfold di at this; omega

variable (C q) in
theorem qi_sub_inv_ne_zero (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) (i : I) :
    ((qi C q i : Kˣ) : K) - ((qi C q i)⁻¹ : Kˣ) ≠ 0 := by
  rw [sub_ne_zero, Ne, Units.eq_iff, ← mul_eq_one_iff_eq_inv, qi, ← zpow_add]
  refine zpow_ne_one_of_hq q hq ?_
  have := di_pos C i; omega

/-! ### The quantum derivations kill the Serre elements -/

variable (C q) in
theorem D_serreDiv (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) (k : I) (n : ℤ) {i j : I} (hij : i ≠ j) :
    D C q k n (serreDiv C.dot q i j (C.serreN i j)) = 0 := by
  have h := D_eq_d k (qi_sub_inv_ne_zero C q hq k) n (serreDiv C.dot q i j (C.serreN i j))
  have h1 : d C.dot q k (serreDiv C.dot q i j (C.serreN i j) : PreF K I) = 0 :=
    d_serreDiv_eq_zero q hij (qfact_vi_ne_zero C q hq i _) k
  have h2 : d C.dot q⁻¹ k (serreDiv C.dot q i j (C.serreN i j) : PreF K I) = 0 := by
    rw [← serreDiv_inv]
    refine d_serreDiv_eq_zero q⁻¹ hij ?_ k
    rw [vi, inv_zpow', zpow_neg, qfact_inv]
    exact qfact_vi_ne_zero C q hq i _
  rw [h1, h2, smul_zero, smul_zero, sub_zero] at h
  exact (smul_eq_zero.1 h).resolve_left (qi_sub_inv_ne_zero C q hq k)

/-! ### The ideal generated by the Serre elements -/

variable (C q) in
/-- The two-sided ideal of `'f` generated by Lusztig's Serre elements (as a subspace). -/
def Jf : Submodule K (PreF K I) :=
  Submodule.span K {z | ∃ (a b : FreeMonoid I) (i j : I), i ≠ j ∧
    z = word a * serreDiv C.dot q i j (C.serreN i j) * word b}

theorem mul_serreDiv_mul_mem_Jf {i j : I} (hij : i ≠ j) (x y : PreF K I) :
    x * serreDiv C.dot q i j (C.serreN i j) * y ∈ Jf C q := by
  induction x using induction_linear with
  | zero => simp
  | add x x' hx hx' => rw [add_mul, add_mul]; exact add_mem hx hx'
  | smul_word a r =>
    rw [smul_mul_assoc, smul_mul_assoc]
    refine Submodule.smul_mem _ _ ?_
    induction y using induction_linear with
    | zero => simp
    | add y y' hy hy' => rw [mul_add]; exact add_mem hy hy'
    | smul_word b s =>
      rw [mul_smul_comm]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨a, b, i, j, hij, rfl⟩)

theorem Jf_mul_right {x : PreF K I} (hx : x ∈ Jf C q) (y : PreF K I) : x * y ∈ Jf C q := by
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨a, b, i, j, hij, rfl⟩ := hz
    rw [mul_assoc]; exact mul_serreDiv_mul_mem_Jf hij _ _
  | zero => simp
  | add x x' _ _ hx hx' => rw [add_mul]; exact add_mem hx hx'
  | smul r x _ hx => rw [smul_mul_assoc]; exact Submodule.smul_mem _ _ hx

theorem Jf_mul_left {x : PreF K I} (hx : x ∈ Jf C q) (y : PreF K I) : y * x ∈ Jf C q := by
  induction hx using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨a, b, i, j, hij, rfl⟩ := hz
    rw [← mul_assoc, ← mul_assoc]; exact mul_serreDiv_mul_mem_Jf hij _ _
  | zero => simp
  | add x x' _ _ hx hx' => rw [mul_add]; exact add_mem hx hx'
  | smul r x _ hx => rw [mul_smul_comm]; exact Submodule.smul_mem _ _ hx

theorem D_mem_Jf (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) (k : I) (n : ℤ) {x : PreF K I}
    (hx : x ∈ Jf C q) : D C q k n x ∈ Jf C q := by
  induction hx using Submodule.span_induction generalizing n with
  | mem z hz =>
    obtain ⟨a, b, i, j, hij, rfl⟩ := hz
    rw [mul_assoc, D_word_mul, D_mul_of_mem_grade k _ (serreDiv_mem_grade C q i j _),
      D_serreDiv C q hq k _ hij, zero_mul, zero_add, ← mul_assoc, ← mul_assoc]
    exact add_mem (mul_serreDiv_mul_mem_Jf hij _ _) (mul_serreDiv_mul_mem_Jf hij _ _)
  | zero => simp
  | add x x' _ _ hx hx' => rw [map_add]; exact add_mem (hx n) (hx' n)
  | smul r x _ hx => rw [map_smul]; exact Submodule.smul_mem _ _ (hx n)

/-- The Serre ideal lies in the radical of the form on `'f` (Lusztig 1.4.3). -/
theorem Jf_le_radical (hq : ∀ n : ℕ, 0 < n → q ^ n ≠ 1) (c : I → K) :
    Jf C q ≤ (radical C.dot q⁻¹ c).restrictScalars K := by
  rw [Jf, Submodule.span_le]
  rintro _ ⟨a, b, i, j, hij, rfl⟩
  have h : serreDiv C.dot q i j (C.serreN i j) ∈ radical C.dot q⁻¹ c := by
    rw [← serreDiv_inv]
    refine serreDiv_mem_radical c C.symm hij (C.dot_self_even i) (C.one_le_serreN hij)
      (C.two_mul_dot_eq hij) ?_
    rw [vi, inv_zpow', zpow_neg, qfact_inv]
    exact qfact_vi_ne_zero C q hq i _
  exact Ideal.mul_mem_right _ _ (Ideal.mul_mem_left _ _ h)

end UDot

end Categorification.QuantumGroup

end
