/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.Crystal.Kleshchev

/-!
# Dots act nilpotently on induced modules

Khovanov–Lauda I (arXiv:0803.4121v2), §3.2 works with graded finite-dimensional modules, on
which the dots `x_a` automatically act nilpotently (`KLRAlgebra.smulNilpotent_x_of_graded`). The
ungraded crystal lemmas of `Categorification.KLR.Crystal` assume this nilpotency; to iterate
induction (e.g. `f̃_i M = hd Ind (M ⊠ L(i))`, KL I Lemma 3.9) we need that it is preserved by
induction.

## Main results

* `KLRAlgebra.smulNilpotent_ind` : if the dots `x_a ⊗ 1`, `1 ⊗ x_b` act nilpotently on an
  `R(μ) ⊗ R(ν')`-module `V`, then all dots of `R(μ + ν')` act nilpotently on `Ind V`.
* `KLRAlgebra.smulNilpotent_ind_extTensor` : the case `V = N ⊠ W`.

## Proof

For a polynomial `g` in the dots, `g(x) (1_{μ,ν'} ⊗ y) = 1_{μ,ν'} ⊗ T_g y` where `T_g` lies in the
commutative algebra generated by the dots of `V` and `T_g - g(0)` is nilpotent
(`exists_pol_smul_tmul_oneConcat`). For symmetric `g` (central in `R(μ + ν')`, by the basis
theorem) with `g(0) = 0` this shows that `g(x)` acts nilpotently on `Ind V`. Finally each `x_a`
is a root of `∏_b (T - x_b) = ∑_j (-1)^j e_j(x) T^{m - j}`, whose non-leading coefficients
`e_j(x)`, `j > 0`, act nilpotently; so `x_a` acts nilpotently.
-/

noncomputable section

namespace Categorification.KLR

open Equiv MvPolynomial TypeA MulOpposite
open scoped TensorProduct

variable {I : Type*} [DecidableEq I]

namespace KLRAlgebra

variable {K : Type*} [Field K] {Q : I → I → MvPolynomial (Fin 2) K} {μ ν' : Multiset I}

/-! ### Dots and `1_{μ,ν'}` -/

section DotTensor

variable (Q) in
/-- The element `x_a ⊗ 1` or `1 ⊗ x_b` of `R(μ) ⊗ R(ν')` corresponding to the dot on the strand
`c` of `R(μ + ν')`. -/
def dotTensor (c : Fin (Multiset.card (μ + ν'))) : TensorKLR Q μ ν' :=
  Sum.elim (fun a => (x a ⊗ₜ[K] 1 : TensorKLR Q μ ν')) (fun b => (1 ⊗ₜ[K] x b : TensorKLR Q μ ν'))
    ((blockEquiv (Seq.card_add' μ ν')).symm c)

theorem x_mul_oneConcat_eq_concat (c : Fin (Multiset.card (μ + ν'))) :
    (x c * oneConcat Q μ ν' : KLRAlgebra K Q (μ + ν')) = concat Q μ ν' (dotTensor Q c) := by
  obtain ⟨d, rfl⟩ := (blockEquiv (Seq.card_add' μ ν')).surjective c
  cases d with
  | inl a =>
    simp only [dotTensor, Equiv.symm_apply_apply, Sum.elim_inl]
    rw [concat_x_tmul_one]; rfl
  | inr b =>
    simp only [dotTensor, Equiv.symm_apply_apply, Sum.elim_inr]
    rw [concat_one_tmul_x]; rfl

theorem dotTensor_commute (c c' : Fin (Multiset.card (μ + ν'))) :
    Commute (dotTensor Q c) (dotTensor Q c') := by
  unfold dotTensor
  rcases (blockEquiv (Seq.card_add' μ ν')).symm c with a | b <;>
    rcases (blockEquiv (Seq.card_add' μ ν')).symm c' with a' | b' <;>
    simp only [Sum.elim_inl, Sum.elim_inr, Commute, SemiconjBy,
      Algebra.TensorProduct.tmul_mul_tmul, one_mul, mul_one, x_mul_x]

end DotTensor

/-! ### Polynomials in the dots on `Ind V` -/

section IndPol

variable {V : Type*} [AddCommGroup V] [Module K V] [Module (TensorKLR Q μ ν') V]
  [IsScalarTower K (TensorKLR Q μ ν') V]

variable (Q μ ν' V) in
/-- The commutative algebra of operators on `V` generated by the dots. -/
abbrev indDotAlg : Subalgebra K (Module.End K V) :=
  Algebra.adjoin K (Set.range fun c : Fin (Multiset.card (μ + ν')) =>
    Algebra.lsmul K K V (dotTensor Q c))

theorem indDotAlg_commute {T T' : Module.End K V} (hT : T ∈ indDotAlg Q μ ν' V)
    (hT' : T' ∈ indDotAlg Q μ ν' V) : Commute T T' := by
  refine Algebra.commute_of_mem_adjoin_of_forall_mem_commute hT' ?_
  rintro _ ⟨c, rfl⟩
  refine (Algebra.commute_of_mem_adjoin_of_forall_mem_commute hT ?_).symm
  rintro _ ⟨c', rfl⟩
  exact (dotTensor_commute (Q := Q) c c').map (Algebra.lsmul K K V)

omit [IsScalarTower K (TensorKLR Q μ ν') V] in
theorem x_smul_tmul_oneConcat (c : Fin (Multiset.card (μ + ν'))) (y : V) :
    (x c : KLRAlgebra K Q (μ + ν')) • (BalancedTensor.tmul oneConcatSubBimod y : Ind Q μ ν' V) =
      BalancedTensor.tmul oneConcatSubBimod (dotTensor Q c • y) := by
  have h1 : (oneConcat Q μ ν' : KLRAlgebra K Q (μ + ν')) •
      (BalancedTensor.tmul oneConcatSubBimod y : Ind Q μ ν' V) =
        BalancedTensor.tmul oneConcatSubBimod y :=
    smul_tmul_oneConcat oneConcatSubBimod y
  rw [← h1, smul_smul, x_mul_oneConcat_eq_concat, concat_smul_tmul_oneConcat]

variable (hnil : ∀ c : Fin (Multiset.card (μ + ν')),
  IsNilpotent (Algebra.lsmul K K V (dotTensor Q c)))

include hnil in
/-- `g(x) (1 ⊗ y) = 1 ⊗ T_g y` with `T_g` in the algebra generated by the dots and
`T_g - g(0)` nilpotent. -/
theorem exists_pol_smul_tmul_oneConcat (g : MvPolynomial (Fin (Multiset.card (μ + ν'))) K) :
    ∃ T ∈ indDotAlg Q μ ν' V,
      (∀ y : V, (pol g : KLRAlgebra K Q (μ + ν')) •
        (BalancedTensor.tmul oneConcatSubBimod y : Ind Q μ ν' V) =
          BalancedTensor.tmul oneConcatSubBimod (T y)) ∧
      IsNilpotent (T - algebraMap K (Module.End K V) (constantCoeff g)) := by
  induction g using MvPolynomial.induction_on with
  | C r =>
    refine ⟨algebraMap K _ r, Subalgebra.algebraMap_mem _ r, fun y => ?_, ?_⟩
    · rw [← MvPolynomial.algebraMap_eq, AlgHom.commutes, algebraMap_smul,
        Module.algebraMap_end_apply, BalancedTensor.tmul_smul]
    · rw [constantCoeff_C, sub_self]; exact IsNilpotent.zero
  | add g h hg hh =>
    obtain ⟨T, hT, hTy, hTn⟩ := hg
    obtain ⟨T', hT', hTy', hTn'⟩ := hh
    refine ⟨T + T', Subalgebra.add_mem _ hT hT', fun y => ?_, ?_⟩
    · rw [map_add, add_smul, hTy, hTy', LinearMap.add_apply, BalancedTensor.tmul_add]
    · have : T + T' - algebraMap K (Module.End K V) (constantCoeff (g + h)) =
          (T - algebraMap K _ (constantCoeff g)) + (T' - algebraMap K _ (constantCoeff h)) := by
        rw [map_add, map_add]; abel
      rw [this]
      refine Commute.isNilpotent_add ?_ hTn hTn'
      exact indDotAlg_commute (Subalgebra.sub_mem _ hT (Subalgebra.algebraMap_mem _ _))
        (Subalgebra.sub_mem _ hT' (Subalgebra.algebraMap_mem _ _))
  | mul_X g c hg =>
    obtain ⟨T, hT, hTy, -⟩ := hg
    have hD : Algebra.lsmul K K V (dotTensor Q c) ∈ indDotAlg Q μ ν' V :=
      Algebra.subset_adjoin ⟨c, rfl⟩
    refine ⟨T * Algebra.lsmul K K V (dotTensor Q c), Subalgebra.mul_mem _ hT hD,
      fun y => ?_, ?_⟩
    · rw [map_mul, pol_X, mul_smul, x_smul_tmul_oneConcat, hTy]; rfl
    · rw [map_mul, constantCoeff_X, mul_zero, map_zero, sub_zero]
      exact (indDotAlg_commute hT hD).isNilpotent_mul_right (hnil c)

variable {P : I → I → MvPolynomial (Fin 2) K}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0)

include hnil hPQ hP in
/-- A symmetric polynomial without constant term in the dots acts nilpotently on `Ind V`. -/
theorem isNilpotent_pol_ind {g : MvPolynomial (Fin (Multiset.card (μ + ν'))) K}
    (hg : g.IsSymmetric) (hg0 : constantCoeff g = 0) :
    IsNilpotent (Algebra.lsmul K K (Ind Q μ ν' V) (pol g : KLRAlgebra K Q (μ + ν'))) := by
  obtain ⟨T, -, hTy, ⟨N, hN⟩⟩ := exists_pol_smul_tmul_oneConcat hnil g
  rw [hg0, map_zero, sub_zero] at hN
  refine ⟨N, LinearMap.ext fun z => ?_⟩
  rw [← map_pow, LinearMap.zero_apply]
  show (pol g : KLRAlgebra K Q (μ + ν')) ^ N • z = 0
  have hc : ∀ r : KLRAlgebra K Q (μ + ν'), Commute ((pol g : KLRAlgebra K Q (μ + ν')) ^ N) r :=
    fun r => (commute_pol_of_isSymmetric hPQ hP hg r).pow_left N
  have hgen : ∀ (m : ℕ) (y : V), (pol g : KLRAlgebra K Q (μ + ν')) ^ m •
      (BalancedTensor.tmul oneConcatSubBimod y : Ind Q μ ν' V) =
        BalancedTensor.tmul oneConcatSubBimod ((T ^ m) y) := by
    intro m
    induction m with
    | zero => intro y; rw [pow_zero, pow_zero, one_smul, Module.End.one_apply]
    | succ m ih =>
      intro y
      rw [pow_succ, mul_smul, hTy, ih, pow_succ, Module.End.mul_apply]
  induction z using BalancedTensor.induction_on with
  | zero => rw [smul_zero]
  | tmul r y =>
    rw [← smul_tmul_oneConcat, smul_smul, (hc r).eq, mul_smul, hgen, hN,
      LinearMap.zero_apply, BalancedTensor.tmul_zero, smul_zero]
  | add z z' hz hz' => rw [smul_add, hz, hz', add_zero]

include hnil hPQ hP in
/-- **The dots act nilpotently on `Ind V`** if the dots `x_a ⊗ 1`, `1 ⊗ x_b` act nilpotently on
`V`. -/
theorem smulNilpotent_ind (a : Fin (Multiset.card (μ + ν'))) :
    SmulNilpotent (x a : KLRAlgebra K Q (μ + ν')) (Ind Q μ ν' V) := by
  let ρ : MvPolynomial (Fin (Multiset.card (μ + ν'))) K →ₐ[K] Module.End K (Ind Q μ ν' V) :=
    (Algebra.lsmul K K (Ind Q μ ν' V)).comp (pol (k := K) (Q := Q) (ν := μ + ν'))
  have hρ : ∀ p, ρ p = Algebra.lsmul K K _ (pol p : KLRAlgebra K Q (μ + ν')) := fun _ => rfl
  -- Vieta: `∑_j e_j(x) (-x_a)^{m - j} = ∏_b (x_b - x_a) = 0`
  have hvieta : ∑ j ∈ Finset.range (Multiset.card (μ + ν') + 1),
      esymm (Fin (Multiset.card (μ + ν'))) K j * (-(X a : MvPolynomial (Fin (Multiset.card (μ + ν'))) K)) ^ (Multiset.card (μ + ν') - j) = 0 := by
    have h := congrArg (Polynomial.eval (-(X a : MvPolynomial (Fin (Multiset.card (μ + ν'))) K)))
      (MvPolynomial.prod_C_add_X_eq_sum_esymm K (Fin (Multiset.card (μ + ν'))))
    rw [Polynomial.eval_prod, Polynomial.eval_finset_sum, Fintype.card_fin] at h
    simp only [Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_pow, Polynomial.eval_X,
      Polynomial.eval_add] at h
    rw [← h]
    exact Finset.prod_eq_zero (Finset.mem_univ a) (by rw [neg_add_cancel])
  have hsplit := Finset.sum_range_succ' (fun j => esymm (Fin (Multiset.card (μ + ν'))) K j *
    (-(X a : MvPolynomial (Fin (Multiset.card (μ + ν'))) K)) ^ (Multiset.card (μ + ν') - j)) (Multiset.card (μ + ν'))
  rw [hvieta, esymm_zero, one_mul, Nat.sub_zero] at hsplit
  have hA : ρ ((-(X a : MvPolynomial (Fin (Multiset.card (μ + ν'))) K)) ^ Multiset.card (μ + ν')) =
      -ρ (∑ j ∈ Finset.range (Multiset.card (μ + ν')), esymm (Fin (Multiset.card (μ + ν'))) K (j + 1) *
        (-(X a : MvPolynomial (Fin (Multiset.card (μ + ν'))) K)) ^ (Multiset.card (μ + ν') - (j + 1))) := by
    rw [← map_neg, eq_neg_of_add_eq_zero_right hsplit.symm]
  have hnilA : IsNilpotent (ρ ((-(X a : MvPolynomial (Fin (Multiset.card (μ + ν'))) K)) ^ Multiset.card (μ + ν'))) := by
    rw [hA, map_sum]
    refine (Commute.isNilpotent_sum (fun j _ => ?_) (fun j j' _ _ =>
      (Commute.all _ _).map ρ)).neg
    rw [map_mul]
    refine ((Commute.all _ _).map ρ).isNilpotent_mul_left ?_
    rw [hρ]
    exact isNilpotent_pol_ind hnil hPQ hP (esymm_isSymmetric _ _ _)
      (constantCoeff_esymm_succ _ j)
  rw [map_pow, map_neg] at hnilA
  have h1 : IsNilpotent (ρ (X a)) := by
    have := (IsNilpotent.of_pow hnilA).neg
    rwa [neg_neg] at this
  rw [hρ, pol_X] at h1
  exact (smulNilpotent_iff_isNilpotent (K := K)).2 h1

end IndPol

section ExtTensorNil

variable {P : I → I → MvPolynomial (Fin 2) K}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0)
  {N : Type*} [AddCommGroup N] [Module K N] [Module (KLRAlgebra K Q μ) N]
  [IsScalarTower K (KLRAlgebra K Q μ) N]
  {W : Type*} [AddCommGroup W] [Module K W] [Module (KLRAlgebra K Q ν') W]
  [IsScalarTower K (KLRAlgebra K Q ν') W]

theorem isNilpotent_dotTensor_extTensor
    (hN : ∀ a, SmulNilpotent (x a : KLRAlgebra K Q μ) N)
    (hW : ∀ b, SmulNilpotent (x b : KLRAlgebra K Q ν') W) (c : Fin (Multiset.card (μ + ν'))) :
    IsNilpotent (Algebra.lsmul K K (ExtTensor K N W) (dotTensor Q c)) := by
  unfold dotTensor
  rcases (blockEquiv (Seq.card_add' μ ν')).symm c with a | b
  · obtain ⟨r, hr⟩ := hN a
    refine ⟨r, LinearMap.ext fun y => ?_⟩
    rw [← map_pow, LinearMap.zero_apply]
    show ((x a : KLRAlgebra K Q μ) ⊗ₜ[K] (1 : KLRAlgebra K Q ν')) ^ r • y = 0
    rw [Algebra.TensorProduct.tmul_pow, one_pow]
    exact tmul_smul_extTensor_eq_zero hr 1 y
  · obtain ⟨r, hr⟩ := hW b
    refine ⟨r, LinearMap.ext fun y => ?_⟩
    rw [← map_pow, LinearMap.zero_apply]
    show ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] (x b : KLRAlgebra K Q ν')) ^ r • y = 0
    rw [Algebra.TensorProduct.tmul_pow, one_pow]
    induction y using ExtTensor.induction_on with
    | zero => rw [smul_zero]
    | tmul v w => rw [ExtTensor.smul_tmul, hr, ExtTensor.tmul_zero]
    | add y y' hy hy' => rw [smul_add, hy, hy', add_zero]

include hPQ hP in
/-- **The dots act nilpotently on `Ind (N ⊠ W)`** if they act nilpotently on `N` and on `W`. -/
theorem smulNilpotent_ind_extTensor (hN : ∀ a, SmulNilpotent (x a : KLRAlgebra K Q μ) N)
    (hW : ∀ b, SmulNilpotent (x b : KLRAlgebra K Q ν') W) (a : Fin (Multiset.card (μ + ν'))) :
    SmulNilpotent (x a : KLRAlgebra K Q (μ + ν')) (Ind Q μ ν' (ExtTensor K N W)) :=
  smulNilpotent_ind (isNilpotent_dotTensor_extTensor hN hW) hPQ hP a

end ExtTensorNil

end KLRAlgebra

end Categorification.KLR
