/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.Crystal.Lemma313
import Categorification.KLR.Crystal.Cor312
import Categorification.KLR.NilHeckeBlockSplitting

/-!
# KL I, Lemma 3.14: the socle of `e_i^n M`

Khovanov–Lauda I (arXiv:0803.4121v2), §3.2, **Lemma 3.14** (TeX lines 2220–2223; Kleshchev's
book, Lemma 5.2.2):

> For an irreducible `M ∈ R(ν)-mod` the socle of `e_i^n M` is isomorphic to
> `(ẽ_i^n M)^{⊕ [n]!} {-n(n-1)/2}`.

We prove the ungraded statement, over any field `K`, for finite-dimensional `M` with nilpotent
dots, `Q` satisfying the hypotheses of the basis theorem, and `0 ≤ n ≤ ε_i(M)` (for `n > ε_i(M)`
both sides vanish: `e_i^n M = 0`, `KLRAlgebra.nontrivial_resSub_iff`). Here `ν = μ + ν'` with
all labels of `ν'` equal to `i`, `n = card ν'`, and `e_i^n M` is `Δ_{i^n} M = 1_{μ,ν'} M` viewed
as an `R(μ)`-module (`KLRAlgebra.ResLeft`). Let `S` be the socle of the
`R(μ) ⊗ R(ν')`-module `Δ_{i^n} M` (simple by Proposition 3.10, `≅ ẽ_i^n M ⊠ L(i^n)` by
Lemma 3.13).

## Main results

* `KLRAlgebra.resLeftSocle` : the socle of `e_i^n M`, the sum of its simple `R(μ)`-submodules.
* `KLRAlgebra.lemma_3_14` (**KL I, Lemma 3.14**, ungraded): `soc(e_i^n M) = S` as subspaces of
  `M`, and `soc(e_i^n M) ≅ (ẽ_i^n M)^{⊕ n!}` as `R(μ)`-modules.

## Proof

The inclusion `S ⊆ soc(e_i^n M)` holds since `S ≅ ẽ_i^n M ⊠ L(i^n)` is a sum of `n! = dim L(i^n)`
copies of `ẽ_i^n M` as an `R(μ)`-module. Conversely let `W = soc(e_i^n M)`.

1. `W` is stable under `1 ⊗ R(ν')`, which acts by `R(μ)`-endomorphisms; so it is an
   `R(μ) ⊗ R(ν')`-submodule of `Δ_{i^n} M`.
2. **`Sym⁺` of the last `n` dots acts by zero on `W`.** The elementary symmetric polynomial
   `e_r(x_1, …, x_m)` in all dots is central in `R(μ + ν')` (`polNu_mem_center`) and nilpotent,
   hence zero on the simple module `M`. On `Δ M` it acts as
   `∑_{a + b = r} e_a(x_1, …, x_{m'}) ⊗ e_b(x_{m'+1}, …, x_m)`, and `e_a(x_1, …, x_{m'})` (`a > 0`)
   is central and nilpotent in `R(μ)`, hence zero on every simple `R(μ)`-module, hence on `W`.
   So `1 ⊗ e_r` kills `W`, and `Sym⁺ = (e_1, …, e_n)` (`coinvIdeal_eq_span_esymm`).
3. Hence the map `HW(W) ⊠ L(i^n) → W` of `Categorification.KLR.Crystal.SimpleTensor` is defined.
   `HW(W)` is a semisimple `R(μ)`-module (a submodule of `W`); for a simple `U ⊆ HW(W)` the
   image of the simple module `U ⊠ L(i^n)` is a simple submodule of `Δ_{i^n} M`, hence equals
   `S` (Proposition 3.10). So `HW(W) ⊆ S`.
4. In `R(ν') ≅ NH_n`, `1` lies in the two-sided ideal generated by `e_n = x^δ ψ_{w_0}` (the
   splitting `e_{n'} = ∑_j A_j e_{n'+1} B_j` of `Categorification.KLR.NilHeckeBlockSplitting`,
   iterated), and `ψ_{w_0} W ⊆ HW(W) ⊆ S`. Hence `W ⊆ S`.

Step 2 is where the argument uses that `M` is simple; it replaces the use of Kato's theorem in
Kleshchev's book. The grading shift `{-n(n-1)/2}` of the paper is not formalized here.
-/

noncomputable section

namespace Categorification.KLR

open Equiv MvPolynomial TypeA MulOpposite Categorification.NilHecke
open scoped TensorProduct

universe u

variable {I : Type u} [DecidableEq I]

/-! ### Elementary symmetric polynomials of two blocks of variables -/

section Esymm

variable {K : Type*} [CommRing K] {σ τ : Type*}

/-- `e_r(x_v : v ∈ s)`, the elementary symmetric polynomial in the variables of `s`. -/
def esymmOn (s : Finset σ) (r : ℕ) : MvPolynomial σ K :=
  ∑ t ∈ s.powersetCard r, ∏ v ∈ t, X v

/-- The generating polynomial `∏_{v ∈ s} (1 + x_v t)`. -/
def esSeriesOn (s : Finset σ) : Polynomial (MvPolynomial σ K) :=
  ∏ v ∈ s, (1 + Polynomial.C (X v) * Polynomial.X)

theorem coeff_esSeriesOn (s : Finset σ) (r : ℕ) :
    (esSeriesOn (K := K) s).coeff r = esymmOn s r := by
  classical
  unfold esSeriesOn esymmOn
  rw [Finset.prod_one_add, Polynomial.finset_sum_coeff, Finset.powersetCard_eq_filter,
    Finset.sum_filter]
  refine Finset.sum_congr rfl fun t _ => ?_
  rw [Finset.prod_mul_distrib, Finset.prod_const, ← map_prod, Polynomial.coeff_C_mul_X_pow]
  by_cases h : t.card = r
  · rw [if_pos h.symm, if_pos h]
  · rw [if_neg (Ne.symm h), if_neg h]

/-- `e_r(s ⊔ t) = ∑_{a + b = r} e_a(s) e_b(t)`. -/
theorem esymmOn_union [DecidableEq σ] {s t : Finset σ} (h : Disjoint s t) (r : ℕ) :
    esymmOn (K := K) (s ∪ t) r =
      ∑ p ∈ Finset.antidiagonal r, esymmOn s p.1 * esymmOn t p.2 := by
  have hs : esSeriesOn (K := K) (s ∪ t) = esSeriesOn s * esSeriesOn t := Finset.prod_union h
  rw [← coeff_esSeriesOn, hs, Polynomial.coeff_mul]
  simp only [coeff_esSeriesOn]

theorem rename_esymmOn (f : σ → τ) (hf : Function.Injective f) (s : Finset σ) (r : ℕ) :
    rename f (esymmOn (K := K) s r) = esymmOn (s.map ⟨f, hf⟩) r := by
  simp only [esymmOn, map_sum, map_prod, rename_X, Finset.powersetCard_map, Finset.sum_map]
  refine Finset.sum_congr rfl fun t _ => ?_
  change _ = ∏ v ∈ t.map ⟨f, hf⟩, X v
  rw [Finset.prod_map]
  rfl

theorem esymm_eq_esymmOn [Fintype σ] (r : ℕ) :
    esymm σ K r = esymmOn (Finset.univ : Finset σ) r := rfl

omit [DecidableEq I] in
theorem posL_injective (μ ν' : Multiset I) : Function.Injective (Seq.posL (ν := μ) ν') :=
  fun a b h => Fin.ext (by simpa using congrArg Fin.val h)

omit [DecidableEq I] in
theorem posR_injective (μ ν' : Multiset I) : Function.Injective (Seq.posR (ν' := ν') μ) :=
  fun a b h => Fin.ext (by have := congrArg Fin.val h; simp only [Seq.posR_val] at this; omega)

omit [DecidableEq I] in
/-- **Splitting `e_r` of all dots**: `e_r(x_1, …, x_m) = ∑_{a + b = r} e_a(x_1, …, x_{m'})
e_b(x_{m'+1}, …, x_m)`, `m' = card μ`, `m = card (μ + ν')`. -/
theorem esymm_add_split (μ ν' : Multiset I) (r : ℕ) :
    esymm (Fin (Multiset.card (μ + ν'))) K r =
      ∑ p ∈ Finset.antidiagonal r,
        rename (Seq.posL ν') (esymm (Fin (Multiset.card μ)) K p.1) *
          rename (Seq.posR μ) (esymm (Fin (Multiset.card ν')) K p.2) := by
  classical
  have hcard := Multiset.card_add μ ν'
  have hu : (Finset.univ : Finset (Fin (Multiset.card (μ + ν')))) =
      Finset.univ.map ⟨_, posL_injective μ ν'⟩ ∪ Finset.univ.map ⟨_, posR_injective μ ν'⟩ := by
    ext c
    simp only [Finset.mem_univ, Finset.mem_union, Finset.mem_map, Function.Embedding.coeFn_mk,
      true_and, true_iff]
    by_cases hc : (c : ℕ) < Multiset.card μ
    · exact Or.inl ⟨⟨c, hc⟩, Fin.ext rfl⟩
    · have := c.2
      exact Or.inr ⟨⟨c - Multiset.card μ, by omega⟩, Fin.ext (by simp only [Seq.posR_val]; omega)⟩
  have hd : Disjoint (Finset.univ.map ⟨_, posL_injective μ ν'⟩)
      (Finset.univ.map ⟨_, posR_injective μ ν'⟩) := by
    rw [Finset.disjoint_left]
    intro c h1 h2
    simp only [Finset.mem_map, Finset.mem_univ, true_and, Function.Embedding.coeFn_mk] at h1 h2
    obtain ⟨a, rfl⟩ := h1
    obtain ⟨b, hb⟩ := h2
    have := congrArg Fin.val hb
    simp only [Seq.posR_val, Seq.posL_val] at this
    have := a.2
    omega
  rw [esymm_eq_esymmOn, hu, esymmOn_union hd]
  refine Finset.sum_congr rfl fun p _ => ?_
  rw [esymm_eq_esymmOn, esymm_eq_esymmOn, rename_esymmOn _ (posL_injective μ ν'),
    rename_esymmOn _ (posR_injective μ ν')]

end Esymm

/-! ### Nilpotency of polynomials in nilpotent commuting dots -/

section Nil

variable {K : Type*} [Field K] {A : Type*} [Ring A] [Algebra K A] {V : Type*} [AddCommGroup V]
  [Module A V] [Module K V] [IsScalarTower K A V] {m : ℕ}

/-- If the images of the variables act nilpotently, so do all polynomials without constant
term. -/
theorem smulNilpotent_of_mem_span_X (ρ : MvPolynomial (Fin m) K →ₐ[K] A)
    (hX : ∀ a, SmulNilpotent (ρ (X a)) V) {p : MvPolynomial (Fin m) K}
    (hp : p ∈ Ideal.span (Set.range (X : Fin m → MvPolynomial (Fin m) K))) :
    SmulNilpotent (ρ p) V := by
  rw [smulNilpotent_iff_isNilpotent (K := K)]
  let ρ' := (Algebra.lsmul K K V).comp ρ
  change IsNilpotent (ρ' p)
  induction hp using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨b, rfl⟩ := hy
    exact (smulNilpotent_iff_isNilpotent (K := K) (A := A) (M := V)).1 (hX b)
  | zero => rw [map_zero]; exact IsNilpotent.zero
  | add y z _ _ hy hz =>
    rw [map_add]
    exact ((Commute.all y z).map ρ').isNilpotent_add hy hz
  | smul r y _ hy =>
    rw [smul_eq_mul, map_mul]
    exact ((Commute.all r y).map ρ').isNilpotent_mul_right hy

theorem esymm_succ_mem_span_X (r : ℕ) :
    esymm (Fin m) K (r + 1) ∈ Ideal.span (Set.range (X : Fin m → MvPolynomial (Fin m) K)) := by
  rw [show (Set.range (X : Fin m → MvPolynomial (Fin m) K)) = X '' Set.univ by
    rw [Set.image_univ], MvPolynomial.mem_ideal_span_X_image]
  intro d hd
  by_contra hcon
  push_neg at hcon
  have hd0 : d = 0 := Finsupp.ext fun b => hcon b (Set.mem_univ b)
  rw [hd0, MvPolynomial.mem_support_iff, ← MvPolynomial.constantCoeff_eq,
    constantCoeff_esymm_succ] at hd
  exact hd rfl

end Nil

namespace KLRAlgebra

variable {K : Type u} [Field K] {Q : I → I → MvPolynomial (Fin 2) K}

/-! ### The socle of `e_{i^n} M` -/

section Socle

variable {μ ν' : Multiset I}
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]

variable (Q μ ν' M) in
/-- **The socle of `e_{i^n} M`**: the sum of all simple `R(μ)`-submodules of
`e_{i^n} M = ResLeft Q μ ν' M`. -/
def resLeftSocle : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M) :=
  ⨆ U ∈ {U : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M) |
    IsSimpleModule (KLRAlgebra K Q μ) U}, U

theorem le_resLeftSocle (U : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M))
    (hU : IsSimpleModule (KLRAlgebra K Q μ) U) : U ≤ resLeftSocle Q μ ν' M :=
  le_iSup₂ (f := fun (U : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M)) _ => U) U hU

theorem resLeftSocle_le {X : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M)}
    (h : ∀ U : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M),
      IsSimpleModule (KLRAlgebra K Q μ) U → U ≤ X) : resLeftSocle Q μ ν' M ≤ X :=
  iSup₂_le fun U hU => h U hU

instance isSemisimpleModule_resLeftSocle :
    IsSemisimpleModule (KLRAlgebra K Q μ) (resLeftSocle Q μ ν' M) :=
  isSemisimpleModule_biSup_of_isSemisimpleModule_submodule (fun U hU => by
    haveI : IsSimpleModule (KLRAlgebra K Q μ) U := hU
    infer_instance)

/-- The socle is stable under `R(μ)`-endomorphisms. -/
theorem map_mem_resLeftSocle (φ : ResLeft Q μ ν' M →ₗ[KLRAlgebra K Q μ] ResLeft Q μ ν' M)
    {v : ResLeft Q μ ν' M} (hv : v ∈ resLeftSocle Q μ ν' M) : φ v ∈ resLeftSocle Q μ ν' M := by
  suffices h : resLeftSocle Q μ ν' M ≤ (resLeftSocle Q μ ν' M).comap φ from h hv
  refine resLeftSocle_le fun U hU u hu => ?_
  let f := φ.comp U.subtype
  rcases LinearMap.injective_or_eq_zero f with hf | hf
  · haveI : IsSimpleModule (KLRAlgebra K Q μ) (LinearMap.range f) :=
      IsSimpleModule.congr (LinearEquiv.ofInjective f hf).symm
    rw [Submodule.mem_comap]
    exact le_resLeftSocle _ this ⟨⟨u, hu⟩, rfl⟩
  · have h0 : φ u = 0 := LinearMap.congr_fun hf ⟨u, hu⟩
    rw [Submodule.mem_comap, h0]
    exact zero_mem _

/-- A central element of `R(μ)` acting nilpotently on `e_{i^n} M` kills its socle. -/
theorem smul_eq_zero_of_mem_resLeftSocle {c : KLRAlgebra K Q μ} (hc : ∀ a, Commute c a)
    (hn : SmulNilpotent c (ResLeft Q μ ν' M)) {v : ResLeft Q μ ν' M}
    (hv : v ∈ resLeftSocle Q μ ν' M) : c • v = 0 := by
  let Z : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M) :=
    { carrier := {v | c • v = 0}
      add_mem' := fun ha hb => by
        simp only [Set.mem_setOf_eq, smul_add] at *; rw [ha, hb, add_zero]
      zero_mem' := smul_zero c
      smul_mem' := fun a v hv => by
        simp only [Set.mem_setOf_eq] at *
        rw [smul_smul, (hc a).eq, mul_smul, hv, smul_zero] }
  have h : resLeftSocle Q μ ν' M ≤ Z := resLeftSocle_le fun U hU u hu => by
    haveI : IsSimpleModule (KLRAlgebra K Q μ) U := hU
    have hnU : SmulNilpotent c U := by
      obtain ⟨N, hN⟩ := hn
      exact ⟨N, fun w => Subtype.ext (by rw [Submodule.coe_smul, hN, ZeroMemClass.coe_zero])⟩
    have := smul_eq_zero_of_smulNilpotent (M := U) hc hnU ⟨u, hu⟩
    exact congrArg Subtype.val this
  exact h hv

/-- `v ↦ (1 ⊗ b) v`, an `R(μ)`-endomorphism of `e_{i^n} M`. -/
def oneTmulEnd (b : KLRAlgebra K Q ν') :
    ResLeft Q μ ν' M →ₗ[KLRAlgebra K Q μ] ResLeft Q μ ν' M where
  toFun v := ResLeft.ofRes (((1 : KLRAlgebra K Q μ) ⊗ₜ[K] b : TensorKLR Q μ ν') • ResLeft.toRes v)
  map_add' v w := by
    show ResLeft.ofRes (_ • (ResLeft.toRes v + ResLeft.toRes w)) = _
    rw [smul_add]; rfl
  map_smul' a v := by
    show ResLeft.ofRes (((1 : KLRAlgebra K Q μ) ⊗ₜ[K] b : TensorKLR Q μ ν') •
        ((a ⊗ₜ[K] (1 : KLRAlgebra K Q ν') : TensorKLR Q μ ν') • ResLeft.toRes v)) =
      ResLeft.ofRes ((a ⊗ₜ[K] (1 : KLRAlgebra K Q ν') : TensorKLR Q μ ν') •
        (((1 : KLRAlgebra K Q μ) ⊗ₜ[K] b : TensorKLR Q μ ν') • ResLeft.toRes v))
    rw [smul_smul, smul_smul, tmul_one_mul_one_tmul]

variable (Q μ ν' M) in
/-- The socle of `e_{i^n} M` as an `R(μ) ⊗ R(ν')`-submodule of `Δ M`. -/
def resSocleT : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M) where
  carrier := {v | ResLeft.ofRes v ∈ resLeftSocle Q μ ν' M}
  add_mem' ha hb := (resLeftSocle Q μ ν' M).add_mem ha hb
  zero_mem' := (resLeftSocle Q μ ν' M).zero_mem
  smul_mem' t v hv := by
    induction t using TensorProduct.induction_on with
    | zero => rw [zero_smul]; exact (resLeftSocle Q μ ν' M).zero_mem
    | tmul a b =>
      have h1 : ((a ⊗ₜ[K] b : TensorKLR Q μ ν') • v) =
          (a ⊗ₜ[K] (1 : KLRAlgebra K Q ν') : TensorKLR Q μ ν') •
            (((1 : KLRAlgebra K Q μ) ⊗ₜ[K] b : TensorKLR Q μ ν') • v) := by
        rw [smul_smul, Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul]
      rw [h1]
      exact (resLeftSocle Q μ ν' M).smul_mem a (map_mem_resLeftSocle (oneTmulEnd b) hv)
    | add s t hs ht => rw [add_smul]; exact (resLeftSocle Q μ ν' M).add_mem hs ht

theorem mem_resSocleT {v : ResSub Q μ ν' M} :
    v ∈ resSocleT Q μ ν' M ↔ ResLeft.ofRes v ∈ resLeftSocle Q μ ν' M := Iff.rfl

end Socle

/-! ### `Sym⁺` of the last `n` dots kills the socle -/

section Main

variable {i : I} {μ ν' : Multiset I} (hν' : ∀ a ∈ ν', a = i)
  {P : I → I → MvPolynomial (Fin 2) K}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0)
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]
  (hnil : ∀ a, SmulNilpotent (x a : KLRAlgebra K Q (μ + ν')) M)

include hnil in
/-- `e_{r+1}(x_1, …, x_{m'})` acts nilpotently on `e_{i^n} M`. -/
theorem smulNilpotent_resLeft_esymm (r : ℕ) :
    SmulNilpotent (pol (esymm (Fin (Multiset.card μ)) K (r + 1)) : KLRAlgebra K Q μ)
      (ResLeft Q μ ν' M) := by
  refine smulNilpotent_of_mem_span_X (K := K) (pol (k := K) (Q := Q) (ν := μ)) (fun a => ?_)
    (esymm_succ_mem_span_X r)
  rw [pol_X]
  obtain ⟨N, hN⟩ := smulNilpotent_resSub_left a (hnil (Seq.posL ν' a))
  refine ⟨N, fun v => resLeft_toRes_injective ?_⟩
  rw [resLeft_toRes_smul, resLeft_toRes_zero, ← one_pow N, ← Algebra.TensorProduct.tmul_pow]
  exact hN _

include hPQ hP hnil in
/-- `e_{r+1}` of all dots acts by zero on the simple module `M` (central and nilpotent). -/
theorem esymm_smul_eq_zero [IsSimpleModule (KLRAlgebra K Q (μ + ν')) M] (r : ℕ) (v : M) :
    (pol (esymm (Fin (Multiset.card (μ + ν'))) K (r + 1)) : KLRAlgebra K Q (μ + ν')) • v = 0 :=
  smul_eq_zero_of_smulNilpotent
    (fun a => commute_pol_of_isSymmetric hPQ hP (esymm_isSymmetric _ _ _) a)
    (smulNilpotent_of_mem_span_X (K := K) (pol (k := K) (Q := Q) (ν := μ + ν'))
      (fun a => by rw [pol_X]; exact hnil a) (esymm_succ_mem_span_X r)) v

include hPQ hP hnil in
/-- **`1 ⊗ e_{r+1}(x_{m'+1}, …, x_m)` kills the socle of `e_{i^n} M`.** -/
theorem one_tmul_esymm_smul_eq_zero [IsSimpleModule (KLRAlgebra K Q (μ + ν')) M] (r : ℕ)
    {v : ResSub Q μ ν' M} (hv : v ∈ resSocleT Q μ ν' M) :
    ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] pol (esymm (Fin (Multiset.card ν')) K (r + 1)) :
      TensorKLR Q μ ν') • v = 0 := by
  have hexp : ((∑ p ∈ Finset.antidiagonal (r + 1),
      (pol (esymm (Fin (Multiset.card μ)) K p.1) ⊗ₜ[K]
        pol (esymm (Fin (Multiset.card ν')) K p.2) : TensorKLR Q μ ν')) • v :
          ResSub Q μ ν' M) = 0 := by
    apply Subtype.ext
    rw [coe_resSub_smul, ZeroMemClass.coe_zero, map_sum]
    simp_rw [concat_pol_tmul_pol]
    rw [← Finset.sum_mul, ← map_sum, ← esymm_add_split μ ν' (r + 1), mul_smul,
      mem_fixSub.1 v.2]
    exact esymm_smul_eq_zero hPQ hP hnil r _
  rw [Finset.sum_smul, Finset.sum_eq_single ((0 : ℕ), r + 1)] at hexp
  · rwa [esymm_zero, map_one] at hexp
  · rintro ⟨a, b⟩ hab hne
    rw [Finset.mem_antidiagonal] at hab
    rcases a with _ | a
    · rw [zero_add] at hab
      exact (hne (Prod.ext rfl hab)).elim
    rw [show (pol (esymm (Fin (Multiset.card μ)) K (a + 1)) ⊗ₜ[K]
        pol (esymm (Fin (Multiset.card ν')) K b) : TensorKLR Q μ ν') =
        (pol (esymm (Fin (Multiset.card μ)) K (a + 1)) ⊗ₜ[K] (1 : KLRAlgebra K Q ν')) *
          ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] pol (esymm (Fin (Multiset.card ν')) K b)) by
        rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, one_mul], mul_smul]
    have hw : ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] pol (esymm (Fin (Multiset.card ν')) K b) :
        TensorKLR Q μ ν') • v ∈ resSocleT Q μ ν' M := (resSocleT Q μ ν' M).smul_mem _ hv
    exact smul_eq_zero_of_mem_resLeftSocle
      (fun c => commute_pol_of_isSymmetric hPQ hP (esymm_isSymmetric _ _ _) c)
      (smulNilpotent_resLeft_esymm hnil a) hw
  · intro h
    exact absurd (Finset.mem_antidiagonal.2 (zero_add _)) h

include hPQ hP hnil in
/-- **`Sym⁺` of the second factor acts by zero on the socle of `e_{i^n} M`.** -/
theorem one_tmul_pol_smul_resSocleT [IsSimpleModule (KLRAlgebra K Q (μ + ν')) M] :
    ∀ p ∈ coinvIdeal K (Multiset.card ν'), ∀ v : resSocleT Q μ ν' M,
      ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] pol p : TensorKLR Q μ ν') • v = 0 := by
  let J : Ideal (MvPolynomial (Fin (Multiset.card ν')) K) :=
    { carrier := {p | ∀ v ∈ resSocleT Q μ ν' M,
        ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] pol p : TensorKLR Q μ ν') • v = 0}
      add_mem' := fun {p q} hp hq v hv => by
        rw [map_add, TensorProduct.tmul_add, add_smul, hp v hv, hq v hv, add_zero]
      zero_mem' := fun v _ => by rw [map_zero, TensorProduct.tmul_zero, zero_smul]
      smul_mem' := fun c {p} hp v hv => by
        show ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] pol (c * p) : TensorKLR Q μ ν') • v = 0
        rw [map_mul, ← one_mul (1 : KLRAlgebra K Q μ), ← Algebra.TensorProduct.tmul_mul_tmul,
          mul_smul, hp v hv, smul_zero] }
  have hle : coinvIdeal K (Multiset.card ν') ≤ J := by
    rw [coinvIdeal_eq_span_esymm, Ideal.span_le]
    rintro _ ⟨r, rfl⟩ v hv
    exact one_tmul_esymm_smul_eq_zero hPQ hP hnil r hv
  intro p hp v
  exact Subtype.ext (hle hp v v.2)

/-! ### `HW(W) ⊆ S` -/

variable (Q μ ν' M) in
/-- The highest weight vectors of the socle of `e_{i^n} M`, an `R(μ)`-submodule. -/
def hwSocle : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M) where
  carrier := {v | v ∈ resLeftSocle Q μ ν' M ∧ ∀ j : ℕ,
    ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] ψ j : TensorKLR Q μ ν') • ResLeft.toRes v = 0}
  add_mem' ha hb := ⟨(resLeftSocle Q μ ν' M).add_mem ha.1 hb.1, fun j => by
    rw [resLeft_toRes_add, smul_add, ha.2 j, hb.2 j, add_zero]⟩
  zero_mem' := ⟨(resLeftSocle Q μ ν' M).zero_mem, fun j => by
    rw [resLeft_toRes_zero, smul_zero]⟩
  smul_mem' a v hv := ⟨(resLeftSocle Q μ ν' M).smul_mem a hv.1, fun j => by
    rw [resLeft_toRes_smul, smul_smul, ← tmul_one_mul_one_tmul, mul_smul, hv.2 j, smul_zero]⟩

theorem hwSocle_le : hwSocle Q μ ν' M ≤ resLeftSocle Q μ ν' M := fun _ hv => hv.1

/-- A submodule `U` of the highest weight vectors of `W`, mapped into the highest weight space
`HW(W)` of the `R(μ) ⊗ R(ν')`-module `W`. -/
def hwSocleToHW (U : Submodule (KLRAlgebra K Q μ) (hwSocle Q μ ν' M)) :
    U →ₗ[KLRAlgebra K Q μ] HWSpace Q μ ν' (resSocleT Q μ ν' M) where
  toFun u := ⟨⟨ResLeft.toRes ((u : hwSocle Q μ ν' M) : ResLeft Q μ ν' M),
      (u : hwSocle Q μ ν' M).2.1⟩,
    fun j => Subtype.ext ((u : hwSocle Q μ ν' M).2.2 j)⟩
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

set_option synthInstance.maxHeartbeats 400000 in
set_option maxHeartbeats 1000000 in
include hν' hPQ hP hnil in
/-- **The highest weight vectors of the socle of `e_{i^n} M` lie in `S`.** -/
theorem hwSocle_mem [FiniteDimensional K M] [IsSimpleModule (KLRAlgebra K Q (μ + ν')) M]
    (hle : Multiset.card ν' ≤ epsI Q (μ + ν') i M)
    (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M)) [IsSimpleModule (TensorKLR Q μ ν') S]
    {v : ResLeft Q μ ν' M} (hv : v ∈ hwSocle Q μ ν' M) : ResLeft.toRes v ∈ S := by
  haveI : IsSemisimpleModule (KLRAlgebra K Q μ) (hwSocle Q μ ν' M) :=
    IsSemisimpleModule.of_injective (Submodule.inclusion hwSocle_le)
      (Submodule.inclusion_injective _)
  let Pm : Submodule (KLRAlgebra K Q μ) (hwSocle Q μ ν' M) :=
    { carrier := {h | ResLeft.toRes (h : ResLeft Q μ ν' M) ∈ S}
      add_mem' := fun ha hb => S.add_mem ha hb
      zero_mem' := S.zero_mem
      smul_mem' := fun a _ hh => S.smul_mem (a ⊗ₜ[K] (1 : KLRAlgebra K Q ν')) hh }
  have htop : ⊤ ≤ Pm := by
    rw [← IsSemisimpleModule.sSup_simples_eq_top (KLRAlgebra K Q μ) (hwSocle Q μ ν' M)]
    refine sSup_le fun U' hU' => ?_
    haveI : IsSimpleModule (KLRAlgebra K Q μ) U' := hU'
    have hsym := one_tmul_pol_smul_resSocleT hPQ hP hnil (M := M)
    let g : ExtTensor K U' (KLRRep hν' Q) →ₗ[TensorKLR Q μ ν'] ResSub Q μ ν' M :=
      (resSocleT Q μ ν' M).subtype.comp ((hwMap hν' hsym).comp
        (ExtTensor.map (hwSocleToHW U')
          (LinearMap.id : KLRRep hν' Q →ₗ[KLRAlgebra K Q ν'] KLRRep hν' Q)))
    have hg : ∀ u : U', g (ExtTensor.tmul u (lMk hν' Q 1)) =
        ResLeft.toRes ((u : hwSocle Q μ ν' M) : ResLeft Q μ ν' M) := by
      intro u
      simp only [g, LinearMap.comp_apply, ExtTensor.map_tmul, Submodule.coe_subtype,
        LinearMap.id_apply]
      rw [hwMap_tmul_one]
      rfl
    haveI := isSimpleModule_extTensor (K := K) (Q := Q) (μ := μ) hν' (V := U')
    have hinj : Function.Injective g := by
      refine (LinearMap.injective_or_eq_zero g).resolve_right fun h0 => ?_
      haveI := IsSimpleModule.nontrivial (KLRAlgebra K Q μ) U'
      obtain ⟨u, hu⟩ := exists_ne (0 : U')
      have h1 := LinearMap.congr_fun h0 (ExtTensor.tmul u (lMk hν' Q 1))
      rw [hg, LinearMap.zero_apply] at h1
      exact hu (Subtype.ext (Subtype.ext h1))
    haveI : IsSimpleModule (TensorKLR Q μ ν') (LinearMap.range g) :=
      IsSimpleModule.congr (LinearEquiv.ofInjective g hinj).symm
    have hR : LinearMap.range g = S := prop_3_10_socle hν' hPQ hP hnil hle _ _
    intro h' hh'
    show _ ∈ S
    rw [← hR, ← hg ⟨h', hh'⟩]
    exact LinearMap.mem_range_self g _
  exact htop (Submodule.mem_top (x := (⟨v, hv⟩ : hwSocle Q μ ν' M)))

/-! ### `W ⊆ S` -/

include hν' hPQ hP hnil in
/-- **The socle of `e_{i^n} M` is contained in `S`**: `1 ∈ R(ν') ≅ NH_n` lies in the two-sided
ideal generated by `e_n = x^δ ψ_{w_0}`, and `ψ_{w_0} W ⊆ HW(W) ⊆ S`. -/
theorem resSocleT_le [FiniteDimensional K M] [IsSimpleModule (KLRAlgebra K Q (μ + ν')) M]
    (hle : Multiset.card ν' ≤ epsI Q (μ + ν') i M)
    (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M)) [IsSimpleModule (TensorKLR Q μ ν') S] :
    resSocleT Q μ ν' M ≤ S := by
  set N := Multiset.card ν' with hN
  let Z : AddSubmonoid (KLRAlgebra K Q ν') :=
    { carrier := {r | ∀ w ∈ resSocleT Q μ ν' M,
        ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] r : TensorKLR Q μ ν') • w ∈ S}
      add_mem' := fun ha hb w hw => by
        rw [TensorProduct.tmul_add, add_smul]; exact S.add_mem (ha w hw) (hb w hw)
      zero_mem' := fun w _ => by rw [TensorProduct.tmul_zero, zero_smul]; exact S.zero_mem }
  have hZl : ∀ r s, r ∈ Z → s * r ∈ Z := fun r s hr w hw => by
    show ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] (s * r) : TensorKLR Q μ ν') • w ∈ S
    rw [← one_mul (1 : KLRAlgebra K Q μ), ← Algebra.TensorProduct.tmul_mul_tmul, mul_smul]
    exact S.smul_mem _ (hr w hw)
  have hZr : ∀ r s, r ∈ Z → r * s ∈ Z := fun r s hr w hw => by
    show ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] (r * s) : TensorKLR Q μ ν') • w ∈ S
    rw [← one_mul (1 : KLRAlgebra K Q μ), ← Algebra.TensorProduct.tmul_mul_tmul, mul_smul]
    exact hr _ ((resSocleT Q μ ν' M).smul_mem _ hw)
  letI := Seq.uniqueOfForall hν'
  set t0 : Seq ν' := default
  have hconst : ∀ p n, IsConstOn t0 p n := fun _ _ a b _ _ _ _ =>
    (hν' _ (t0.mem a)).trans (hν' _ (t0.mem b)).symm
  -- `e_n ∈ Z`
  have htop : (blockIdem t0 0 N : KLRAlgebra K Q ν') ∈ Z := by
    intro w hw
    rw [blockIdem, blockElt, e_eq_one_of_forall hν' Q t0, mul_one,
      ← one_mul (1 : KLRAlgebra K Q μ), ← Algebra.TensorProduct.tmul_mul_tmul, mul_smul]
    refine S.smul_mem _ ?_
    have hw' : ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] ψw (blockWord 0 N) : TensorKLR Q μ ν') • w ∈
        resSocleT Q μ ν' M := (resSocleT Q μ ν' M).smul_mem _ hw
    have hmem : (⟨_, hw'⟩ : resSocleT Q μ ν' M) ∈ hwSub Q μ ν' (resSocleT Q μ ν' M) := by
      intro j
      apply Subtype.ext
      rw [Submodule.coe_smul, ZeroMemClass.coe_zero]
      show ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] ψ j : TensorKLR Q μ ν') •
        (((1 : KLRAlgebra K Q μ) ⊗ₜ[K] ψw (blockWord 0 N) : TensorKLR Q μ ν') • w) = 0
      rw [smul_smul, Algebra.TensorProduct.tmul_mul_tmul, mul_one]
      have h1 : (ψ j * ψw (blockWord 0 N) : KLRAlgebra K Q ν') = ψw (j :: blockWord 0 N) := by
        simp only [ψw, List.map_cons, List.prod_cons]
      rw [h1, ψw_eq_zero_of_choose_lt hν' Q (by
        simp only [blockWord, List.length_cons, List.length_map, length_w0Word, hN]; omega),
        TensorProduct.tmul_zero, zero_smul]
    exact hwSocle_mem hν' hPQ hP hnil hle S (v := ResLeft.ofRes _)
      ⟨hw', fun j => congrArg Subtype.val (hmem j)⟩
  -- `e_{n'+1} ∈ Z → e_{n'} ∈ Z`
  have hstep : ∀ n, n + 1 ≤ N → (blockIdem t0 0 (n + 1) : KLRAlgebra K Q ν') ∈ Z →
      (blockIdem t0 0 n : KLRAlgebra K Q ν') ∈ Z := by
    intro n hn hZ
    have hpn : 0 + (n + 1) ≤ Multiset.card ν' := by omega
    have hsum := sum_blockA_mul_blockB (k := K) (Q := Q) hpn (hconst 0 (n + 1))
    have hid := isIdempotentElem_blockIdem (k := K) (Q := Q)
      (show 0 + n ≤ Multiset.card ν' by omega) (hconst 0 n)
    rw [← hid.eq, ← hsum, Finset.sum_mul_sum]
    refine sum_mem fun j _ => sum_mem fun j' _ => ?_
    rw [mul_assoc, ← mul_assoc (blockB K Q t0 hpn (j : ℕ)),
      blockB_mul_blockA hpn (hconst 0 (n + 1)) (Nat.lt_succ_iff.1 j.2) (Nat.lt_succ_iff.1 j'.2)]
    split_ifs
    · exact hZl _ _ (hZr _ _ hZ)
    · rw [zero_mul, mul_zero]; exact Z.zero_mem
  have hall : ∀ d, d ≤ N → (blockIdem t0 0 (N - d) : KLRAlgebra K Q ν') ∈ Z := by
    intro d
    induction d with
    | zero => intro _; rw [Nat.sub_zero]; exact htop
    | succ d ih =>
      intro hd
      refine hstep _ (by omega) ?_
      rw [show N - (d + 1) + 1 = N - d by omega]
      exact ih (by omega)
  have h0 := hall N le_rfl
  rw [Nat.sub_self, blockIdem, blockElt_zero, one_mul, e_eq_one_of_forall hν' Q t0] at h0
  intro v hv
  have := h0 v hv
  rwa [← Algebra.TensorProduct.one_def, one_smul] at this

/-! ### `S` as an `R(μ)`-module -/

/-- An `R(μ) ⊗ R(ν')`-submodule of `Δ M`, as an `R(μ)`-submodule of `e_{i^n} M`. -/
def resLeftSub (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M)) :
    Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M) where
  carrier := {v | ResLeft.toRes v ∈ S}
  add_mem' ha hb := S.add_mem ha hb
  zero_mem' := S.zero_mem
  smul_mem' a _ hv := S.smul_mem (a ⊗ₜ[K] (1 : KLRAlgebra K Q ν')) hv

section ExtPi

variable {V : Type*} [AddCommGroup V] [Module K V] {L : Type*} [AddCommGroup L] [Module K L]
  {N : ℕ}

/-- `V ⊠ L ≅ V^{⊕ N}` for a basis of `L` indexed by `Fin N` (`K`-linear). -/
def extTensorPi (b : Basis (Fin N) K L) : ExtTensor K V L ≃ₗ[K] (Fin N → V) :=
  ExtTensor.equivTensor ≪≫ₗ TensorProduct.equivFinsuppOfBasisRight b ≪≫ₗ
    Finsupp.linearEquivFunOnFinite K V (Fin N)

theorem extTensorPi_tmul (b : Basis (Fin N) K L) (v : V) (ℓ : L) (j : Fin N) :
    extTensorPi b (ExtTensor.tmul v ℓ) j = b.repr ℓ j • v := by
  simp only [extTensorPi, LinearEquiv.trans_apply, Finsupp.linearEquivFunOnFinite_apply]
  exact TensorProduct.equivFinsuppOfBasisRight_apply_tmul_apply b v ℓ j

/-- `V ⊠ L ≅ V^{⊕ N}` is `R(μ)`-linear. -/
theorem extTensorPi_smul [Module (KLRAlgebra K Q μ) V] [IsScalarTower K (KLRAlgebra K Q μ) V]
    [Module (KLRAlgebra K Q ν') L] [IsScalarTower K (KLRAlgebra K Q ν') L]
    (b : Basis (Fin N) K L) (a : KLRAlgebra K Q μ) (y : ExtTensor K V L) :
    extTensorPi b ((a ⊗ₜ[K] (1 : KLRAlgebra K Q ν') : TensorKLR Q μ ν') • y) =
      a • extTensorPi b y := by
  induction y using ExtTensor.induction_on with
  | zero => rw [smul_zero, map_zero, smul_zero]
  | tmul v ℓ =>
    funext j
    rw [ExtTensor.smul_tmul, one_smul, Pi.smul_apply, extTensorPi_tmul, extTensorPi_tmul,
      smul_algebra_smul_comm]
  | add y y' hy hy' => rw [smul_add, map_add, hy, hy', map_add, smul_add]

end ExtPi

/-- `S ≅ E ⊠ L` with `dim L = N` gives `S ≅ E^{⊕ N}` as `R(μ)`-modules. -/
def resLeftSubEquiv (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M)) {E : Type*}
    [AddCommGroup E] [Module K E] [Module (KLRAlgebra K Q μ) E]
    [IsScalarTower K (KLRAlgebra K Q μ) E] {L : Type*} [AddCommGroup L] [Module K L]
    [Module (KLRAlgebra K Q ν') L] [IsScalarTower K (KLRAlgebra K Q ν') L] {N : ℕ}
    (e : S ≃ₗ[TensorKLR Q μ ν'] ExtTensor K E L) (b : Basis (Fin N) K L) :
    resLeftSub S ≃ₗ[KLRAlgebra K Q μ] (Fin N → E) where
  toFun v := extTensorPi b (e ⟨ResLeft.toRes (v : ResLeft Q μ ν' M), v.2⟩)
  invFun f := ⟨ResLeft.ofRes ((e.symm ((extTensorPi b).symm f) : S) : ResSub Q μ ν' M),
    (e.symm ((extTensorPi b).symm f)).2⟩
  map_add' v w := by rw [← map_add, ← map_add]; rfl
  map_smul' a v := by rw [RingHom.id_apply, ← extTensorPi_smul (μ := μ) (ν' := ν'), ← map_smul]; rfl
  left_inv v := Subtype.ext (by
    show ResLeft.ofRes ((e.symm ((extTensorPi b).symm ((extTensorPi b)
      (e ⟨ResLeft.toRes (v : ResLeft Q μ ν' M), v.2⟩))) : S) : ResSub Q μ ν' M) = v
    rw [LinearEquiv.symm_apply_apply, LinearEquiv.symm_apply_apply]
    rfl)
  right_inv f := by
    show extTensorPi b (e (e.symm ((extTensorPi b).symm f))) = f
    rw [LinearEquiv.apply_symm_apply, LinearEquiv.apply_symm_apply]

/-! ### Lemma 3.14 -/

include hν' hPQ hP hnil in
/-- **KL I, Lemma 3.14** (ungraded): for `M` irreducible (finite-dimensional, nilpotent dots) and
`n = card ν' ≤ ε_i(M)`, let `S` be the socle of `Δ_{i^n} M` (its unique simple
`R(μ) ⊗ R(ν')`-submodule, `prop_3_10_socle`). Then the socle of `e_i^n M` (the sum of its simple
`R(μ)`-submodules) is `S`, and it is isomorphic to `(ẽ_i^n M)^{⊕ n!}`. -/
theorem lemma_3_14 [FiniteDimensional K M] [IsSimpleModule (KLRAlgebra K Q (μ + ν')) M]
    (hle : Multiset.card ν' ≤ epsI Q (μ + ν') i M)
    (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M)) [IsSimpleModule (TensorKLR Q μ ν') S] :
    resLeftSocle Q μ ν' M = resLeftSub S ∧
      Nonempty (resLeftSub S ≃ₗ[KLRAlgebra K Q μ] (Fin (Multiset.card ν').factorial →
        (KLRMod.eIter i μ (Multiset.card ν')
          ((KLRMod.of (Q := Q) (ν := μ + ν') M).cast (add_replicate_eq hν'))).carrier)) := by
  obtain ⟨e⟩ := lemma_3_13_soc hPQ hP hν' hnil hle S
  obtain ⟨eHW⟩ := lemma_3_13_hw hPQ hP hν' hnil hle S
  have hfin : Module.finrank K (KLRRep hν' Q) = (Multiset.card ν').factorial := by
    rw [← (KLRRep.of hν' Q).finrank_eq, finrank_coinv]
  haveI : Module.Finite K (KLRRep hν' Q) :=
    Module.finite_of_finrank_pos (by rw [hfin]; exact Nat.factorial_pos _)
  let Φ := resLeftSubEquiv S e (Module.finBasisOfFinrankEq K (KLRRep hν' Q) hfin)
  refine ⟨le_antisymm ?_ ?_, ⟨Φ⟩⟩
  · intro v hv
    exact resSocleT_le hν' hPQ hP hnil hle S (show ResLeft.toRes v ∈ resSocleT Q μ ν' M from hv)
  · have hnilS : ∀ b, SmulNilpotent ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] x b : TensorKLR Q μ ν') S :=
      fun b => smulNilpotent_submodule S (smulNilpotent_resSub b (hnil _))
    haveI : FiniteDimensional K S := finiteDimensional_submodule' S
    haveI : IsSimpleModule (KLRAlgebra K Q μ) (HWSpace Q μ ν' S) :=
      isSimpleModule_hwSpace hν' hPQ hP hnilS
    haveI : IsSimpleModule (KLRAlgebra K Q μ) (KLRMod.eIter i μ (Multiset.card ν')
        ((KLRMod.of (Q := Q) (ν := μ + ν') M).cast (add_replicate_eq hν'))).carrier :=
      IsSimpleModule.congr (R := KLRAlgebra K Q μ) (N := HWSpace Q μ ν' S) eHW.symm
    haveI : IsSemisimpleModule (KLRAlgebra K Q μ) (resLeftSub S) := IsSemisimpleModule.congr Φ
    intro v hv
    have htop : (⟨v, hv⟩ : resLeftSub S) ∈ (⊤ : Submodule (KLRAlgebra K Q μ) (resLeftSub S)) :=
      Submodule.mem_top
    rw [← IsSemisimpleModule.sSup_simples_eq_top (KLRAlgebra K Q μ) (resLeftSub S)] at htop
    have hle' : sSup {U' : Submodule (KLRAlgebra K Q μ) (resLeftSub S) |
        IsSimpleModule (KLRAlgebra K Q μ) U'} ≤
          (resLeftSocle Q μ ν' M).comap (resLeftSub S).subtype := sSup_le fun U' hU' => by
      haveI : IsSimpleModule (KLRAlgebra K Q μ) U' := hU'
      intro u hu
      rw [Submodule.mem_comap]
      let f := (resLeftSub S).subtype.comp U'.subtype
      have hf : Function.Injective f :=
        (Submodule.injective_subtype _).comp (Submodule.injective_subtype _)
      haveI : IsSimpleModule (KLRAlgebra K Q μ) (LinearMap.range f) :=
        IsSimpleModule.congr (LinearEquiv.ofInjective f hf).symm
      exact le_resLeftSocle _ this ⟨⟨u, hu⟩, rfl⟩
    exact hle' htop

end Main

end KLRAlgebra

end Categorification.KLR

end
