/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.Crystal.Lemma314
import Categorification.KLR.Crystal.GradedBridge
import Categorification.KLR.ResProjGraded
import Categorification.QuantumGroup.DividedPowers
import Categorification.KLR.DividedPowerK0

/-!
# KL I, Lemma 3.14 with gradings

Khovanov–Lauda I (arXiv:0803.4121v2), §3.2, **Lemma 3.14** (TeX lines 2218–2220):

> For an irreducible `M ∈ R(ν)-mod` the socle of `e_i^n M` is isomorphic to
> `ẽ_i^n M^{⊕ [n]!} {-n(n-1)/2}`.

Here `[n]! = [1][2]⋯[n]`, `[m] = (q^m - q^{-m})/(q - q^{-1})`, and for a Laurent polynomial
`f = ∑ f_a q^a`, `N^{⊕ f}` is the direct sum over `a` of `f_a` copies of `N{a}` (KL I §2.2,
TeX lines 703–708); `N{a}` is `N` with the grading shifted up by `a`. Just before the lemma the
paper says: "isomorphisms of simple modules are allowed to be homogeneous (not necessarily
degree-preserving)".

The ungraded statement is `KLRAlgebra.lemma_3_14` (`Categorification.KLR.Crystal.Lemma314`):
`soc(e_i^n M) = S` for the socle `S` of `Δ_{i^n} M = 1_{μ,ν'} M` (its unique simple
`R(μ) ⊗ R(ν')`-submodule), and `S ≅ (ẽ_i^n M)^{⊕ n!}`. Here `ν = μ + ν'`, all labels of `ν'` are
`i`, `n = card ν'`. The isomorphism comes from `S ≅ HW(S) ⊠ L(i^n)`, `v ⊗ [p] ↦ p(x) v`
(`KLRAlgebra.hwEquiv`), with `HW(S) ≅ ẽ_i^n M` the vectors of `S` killed by the crossings of the
second factor (Lemma 3.13, `KLRAlgebra.lemma_3_13_hw`), and a basis of `L(i^n) = k[x]/(Sym⁺)`.

## The graded statement

Let `M` be a graded simple `R(μ + ν')`-module (grading `ℳ`; any grading datum with dots of
positive degree, `hG`). We prove:

* `KLRAlgebra.isHomogeneous_of_isSimpleModule` : **the socle `S` of `Δ_{i^n} M` is a graded
  submodule**. A minimal nonzero homogeneous submodule `T` of `Δ_{i^n} M` is graded simple, hence
  simple (`Graded.IsGradedSimple.isSimpleModule`), hence equal to `S` by the uniqueness of simple
  submodules (Proposition 3.10, `KLRAlgebra.prop_3_10_socle`). Hence `soc(e_i^n M) = S` and
  `HW(S) ≅ ẽ_i^n M` are graded, with the gradings induced from `M`.
* `KLRAlgebra.lemma_3_14_graded` (**KL I, Lemma 3.14, graded**): an isomorphism of graded
  `R(μ)`-modules
  `soc(e_i^n M) ≅ ⊕_{u ∈ Staircase n} HW(S){d · |u|}`,
  `d = deg x_{i}` (`G.degX i`), `|u| = ∑_a u_a`, the sum over the staircase exponents
  `0 ≤ u_a ≤ a` of Artin's basis `x^u` of `L(i^n)` (`coinvBasis`); the summand `u` is
  `(1 ⊗ x^u) HW(S)`. Since `HW(S) ≅ ẽ_i^n M`, this is `ẽ_i^n M^{⊕ f}` with
  `f = ∑_u q^{d|u|} = ∏_{a=1}^{n} (1 + q^d + ⋯ + q^{d(a-1)})` (`KLRAlgebra.stairPoly_eq_prod`),
  the graded dimension of `L(i^n)`.
* `KLRAlgebra.gdimPoly_socle` : `gdim soc(e_i^n M) = f · gdim HW(S)`.
* For KL I's grading (`d = i · i = 2`, `KLRAlgebra.stairPoly_two`):
  `f = q^{n(n-1)/2} [n]!` (`QuantumGroup.qfact` at `q`), so
  `soc(e_i^n M) ≅ HW(S)^{⊕ q^{n(n-1)/2} [n]!} = (HW(S){n(n-1)})^{⊕ [n]!}{-n(n-1)/2}`
  (`KLRAlgebra.gdimPoly_socle_kl`).

## Relation to the printed statement

The printed shift `{-n(n-1)/2}` refers to a particular grading on `ẽ_i^n M`, which the paper
defines only up to isomorphism of simple modules, and such isomorphisms are allowed to be
homogeneous of any degree. With `ẽ_i^n M` realized as the highest weight space `HW(S)` (graded as
a subspace of `M`), the correct shift is `{+n(n-1)/2}`: `L(i^n)` is generated by `[1]` in degree
`0` and lives in degrees `0, 2, …, n(n-1)`. With `ẽ_i^n M` realized as the top summand
`(1 ⊗ x^δ) HW(S) ≅ HW(S){n(n-1)}` (`x^δ = x_2 x_3^2 ⋯ x_n^{n-1}`, the summand `u = topStair n`),
the shift is the printed `{-n(n-1)/2}`. Both normalizations are the same statement up to an
overall grading shift of `ẽ_i^n M`, which is all that the paper's conventions determine. The
multiplicity `f` in the statement is `[n]!` up to this shift, and it is exactly the graded
dimension of `L(i^n)`.

(A small erratum nearby: TeX line 738 says that `L(i^m)` is "nonzero in degrees
`0, 2, …, m(m-1)/2`"; with `deg x = 2` the top degree of `k[x_1, …, x_m]/(Sym⁺)` is `m(m-1)`,
twice the number of inversions of the longest element.)
-/

noncomputable section

namespace Categorification.KLR

open Graded DirectSum MvPolynomial TypeA
open scoped TensorProduct

universe u

variable {I : Type u} [DecidableEq I]

namespace KLRAlgebra

variable {K : Type u} [Field K] {Q : I → I → MvPolynomial (Fin 2) K} (G : GradingDatum Q)

/-! ### Gradings on `Δ M` -/

section ResSubGrading

variable {μ ν' : Multiset I}
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]
  (ℳ : ℤ → Submodule K M) [Decomposition ℳ] [SetLike.GradedSMul (G.grade (μ + ν')) ℳ]

/-- The grading of `Δ M = 1_{μ,ν'} M` induced by a grading of `M`. (The grading datum `G` is
recorded to make the graded structure an instance.) -/
@[nolint unusedArguments]
def resSubGrading (_G : GradingDatum Q) : ℤ → Submodule K (ResSub Q μ ν' M) :=
  comap ℳ (fixSub K M (oneConcat Q μ ν')).subtype

omit [Decomposition ℳ] [SetLike.GradedSMul (G.grade (μ + ν')) ℳ] in
@[simp] theorem mem_resSubGrading {d : ℤ} {v : ResSub Q μ ν' M} :
    v ∈ resSubGrading ℳ G d ↔ (v : M) ∈ ℳ d := Iff.rfl

theorem isInternal_resSubGrading : IsInternal (resSubGrading ℳ G (μ := μ) (ν' := ν')) :=
  isInternal_comap ℳ _ Subtype.val_injective fun v d =>
    ⟨⟨_, by
      have hv : oneConcat Q μ ν' • (fixSub K M (oneConcat Q μ ν')).subtype v =
          (fixSub K M (oneConcat Q μ ν')).subtype v := mem_fixSub.1 v.2
      rw [mem_fixSub, ← decompose_smul_of_mem_zero ℳ (G.oneConcat_mem_grade (ν := μ) (ν' := ν')),
        hv]⟩, rfl⟩

instance : Decomposition (resSubGrading ℳ G (μ := μ) (ν' := ν')) :=
  (isInternal_resSubGrading G ℳ).chooseDecomposition

instance : SetLike.GradedSMul (tensorGrading (G.grade μ) (G.grade ν'))
    (resSubGrading ℳ G (μ := μ) (ν' := ν')) where
  smul_mem _ _ t v ht hv := by
    rw [mem_resSubGrading, coe_resSub_smul]
    exact SetLike.GradedSMul.smul_mem (A := G.grade (μ + ν')) (G.concat_mem_grade ht) hv

end ResSubGrading

/-! ### The socle of `Δ_{i^n} M` is homogeneous -/

section Homogeneous

variable {A : Type*} [Ring A] [Algebra K A]
  {V : Type*} [AddCommGroup V] [Module K V] [Module A V] [IsScalarTower K A V]
  {𝒱 : ℤ → Submodule K V} [Decomposition 𝒱]

/-- A homogeneous submodule of a homogeneous submodule is homogeneous. -/
theorem isHomogeneous_map_subtype {T : Submodule A V} (hT : T.IsHomogeneous 𝒱)
    {p : Submodule A T}
    (hp : letI := submoduleDecomposition 𝒱 hT; p.IsHomogeneous (submodule 𝒱 T)) :
    (p.map T.subtype).IsHomogeneous 𝒱 := by
  letI := submoduleDecomposition 𝒱 hT
  intro d x hx
  obtain ⟨y, hy, rfl⟩ := Submodule.mem_map.1 hx
  have h := decompose_map (R := A) (ℳ := submodule 𝒱 T) (𝒩 := 𝒱) (f := T.subtype)
    (fun _ _ h => h) y d
  rw [h]
  exact Submodule.mem_map_of_mem (hp d hy)

/-- **A minimal nonzero homogeneous submodule of a finite-dimensional graded module is simple.** -/
theorem exists_isHomogeneous_isSimpleModule (𝒜 : ℤ → Submodule K A) [GradedAlgebra 𝒜]
    [SetLike.GradedSMul 𝒜 𝒱] [FiniteDimensional K V] [Nontrivial V] :
    ∃ T : Submodule A V, T.IsHomogeneous 𝒱 ∧ IsSimpleModule A T := by
  classical
  let Hs : Set (Submodule A V) := {T | T.IsHomogeneous 𝒱 ∧ T ≠ ⊥}
  have htop : (⊤ : Submodule A V).IsHomogeneous 𝒱 := fun _ _ _ => Submodule.mem_top
  have hne : Hs.Nonempty := ⟨⊤, htop, top_ne_bot⟩
  obtain ⟨T, ⟨hT, hT0⟩, hmin⟩ :=
    (measure fun T : Submodule A V => Module.finrank K T).wf.has_min Hs hne
  refine ⟨T, hT, ?_⟩
  letI := submoduleDecomposition 𝒱 hT
  haveI : Nontrivial T := Submodule.nontrivial_iff_ne_bot.2 hT0
  haveI : FiniteDimensional K T := finiteDimensional_submodule' T
  have hgs : IsGradedSimple 𝒜 (submodule 𝒱 T) := by
    refine ⟨inferInstance, fun p hp => ?_⟩
    by_cases hp0 : p = ⊥
    · exact Or.inl hp0
    right
    have hmap : (p.map T.subtype).IsHomogeneous 𝒱 := isHomogeneous_map_subtype hT hp
    have hmap0 : p.map T.subtype ≠ ⊥ := by
      intro h
      apply hp0
      rw [← Submodule.map_bot T.subtype] at h
      exact Submodule.map_injective_of_injective T.injective_subtype h
    have hle : Module.finrank K T ≤ Module.finrank K (p.map T.subtype) :=
      not_lt.1 (hmin _ ⟨hmap, hmap0⟩)
    have hfr : Module.finrank K (p.map T.subtype) = Module.finrank K p :=
      ((Submodule.equivMapOfInjective _ T.injective_subtype p).restrictScalars K).symm.finrank_eq
    have h1 : Module.finrank K (p.restrictScalars K) ≤ Module.finrank K T :=
      Submodule.finrank_le _
    have h2 : Module.finrank K (p.restrictScalars K) = Module.finrank K p := rfl
    rw [← Submodule.restrictScalars_eq_top_iff K]
    apply Submodule.eq_top_of_finrank_eq
    exact le_antisymm h1 (by rw [h2, ← hfr]; exact hle)
  exact hgs.isSimpleModule

end Homogeneous

section SocleHomogeneous

variable {i : I} {μ ν' : Multiset I} (hν' : ∀ a ∈ ν', a = i)
  {P : I → I → MvPolynomial (Fin 2) K}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0)
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]
  (ℳ : ℤ → Submodule K M) [Decomposition ℳ] [SetLike.GradedSMul (G.grade (μ + ν')) ℳ]
  (hnil : ∀ a, SmulNilpotent (x a : KLRAlgebra K Q (μ + ν')) M)

include hν' hPQ hP hnil in
/-- **The socle of `Δ_{i^n} M` is homogeneous** (for a graded simple `M`, `n ≤ ε_i(M)`). -/
theorem isHomogeneous_of_isSimpleModule [FiniteDimensional K M]
    [IsSimpleModule (KLRAlgebra K Q (μ + ν')) M]
    (hle : Multiset.card ν' ≤ epsI Q (μ + ν') i M)
    (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M)) [IsSimpleModule (TensorKLR Q μ ν') S] :
    S.IsHomogeneous (resSubGrading ℳ G) := by
  haveI : Nontrivial (ResSub Q μ ν' M) := by
    haveI := IsSimpleModule.nontrivial (TensorKLR Q μ ν') S
    obtain ⟨⟨v, hv⟩, hv0⟩ := exists_ne (0 : S)
    exact ⟨⟨v, 0, fun h => hv0 (Subtype.ext h)⟩⟩
  obtain ⟨T, hT, hTs⟩ := exists_isHomogeneous_isSimpleModule (A := TensorKLR Q μ ν')
    (𝒱 := resSubGrading ℳ G (μ := μ) (ν' := ν')) (tensorGrading (G.grade μ) (G.grade ν'))
  have hST : S = T := prop_3_10_socle hν' hPQ hP hnil hle S T
  rw [hST]
  exact hT

end SocleHomogeneous

/-! ### Graded dimension of `L(i^n)` -/

section StairPoly

theorem T_sum_eq_prod {ι : Type*} (s : Finset ι) (f : ι → ℤ) :
    (LaurentPolynomial.T (∑ a ∈ s, f a) : LaurentPolynomial ℤ) =
      ∏ a ∈ s, LaurentPolynomial.T (f a) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp [LaurentPolynomial.T_zero]
  | @insert a s ha ih => rw [Finset.sum_insert ha, Finset.prod_insert ha, LaurentPolynomial.T_add, ih]

/-- `∑_{u ∈ Staircase n} q^{d |u|}`, the graded dimension of `L(i^n) = k[x_1, …, x_n]/(Sym⁺)` when
`deg x_a = d` (Artin's basis `x^u`, `0 ≤ u_a ≤ a`). -/
def stairPoly (n : ℕ) (d : ℤ) : LaurentPolynomial ℤ :=
  ∑ u : Staircase n, LaurentPolynomial.T (d * ∑ a, (u.1 a : ℤ))

/-- `∑_u q^{d |u|} = ∏_{a=1}^{n} (1 + q^d + ⋯ + q^{d(a-1)})`. -/
theorem stairPoly_eq_prod (n : ℕ) (d : ℤ) :
    stairPoly n d = ∏ a : Fin n, ∑ c ∈ Finset.range (a + 1), LaurentPolynomial.T (d * c) := by
  classical
  rw [Finset.prod_univ_sum]
  have hmem : ∀ u : Fin n → ℕ,
      u ∈ Fintype.piFinset (fun a : Fin n => Finset.range (a + 1)) ↔ ∀ a : Fin n, u a ≤ a := by
    intro u
    simp only [Fintype.mem_piFinset, Finset.mem_range, Nat.lt_succ_iff]
  rw [Finset.sum_subtype _ hmem, stairPoly]
  refine Finset.sum_congr rfl fun u _ => ?_
  rw [Finset.mul_sum, T_sum_eq_prod]

theorem sum_range_T_two (m : ℕ) :
    ∑ c ∈ Finset.range (m + 1), (LaurentPolynomial.T (2 * c) : LaurentPolynomial ℤ) =
      LaurentPolynomial.T (m : ℤ) * QuantumGroup.qint qUnitLP (m + 1) := by
  rw [QuantumGroup.qint, ← mul_assoc, val_qUnitLP_zpow, ← LaurentPolynomial.T_add]
  have hm : (m : ℤ) + (1 - ((m + 1 : ℕ) : ℤ)) = 0 := by push_cast; ring
  rw [hm, LaurentPolynomial.T_zero, one_mul]
  refine Finset.sum_congr rfl fun c _ => ?_
  show _ = ((LaurentPolynomial.T 1 : LaurentPolynomial ℤ) ^ 2) ^ c
  rw [← pow_mul, LaurentPolynomial.T_pow]
  push_cast
  ring_nf

/-- For `d = 2` (KL I's grading), `∑_u q^{2|u|} = q^{n(n-1)/2} [n]!`. -/
theorem stairPoly_two (n : ℕ) :
    stairPoly n 2 = LaurentPolynomial.T ((n.choose 2 : ℕ) : ℤ) * QuantumGroup.qfact qUnitLP n := by
  rw [stairPoly_eq_prod, QuantumGroup.qfact, Fin.prod_univ_eq_prod_range
    (fun a => ∑ c ∈ Finset.range (a + 1), (LaurentPolynomial.T (2 * c) : LaurentPolynomial ℤ)) n]
  simp only [sum_range_T_two]
  rw [Finset.prod_mul_distrib, ← T_sum_eq_prod, ← Nat.cast_sum, Finset.sum_range_id,
    Nat.choose_two_right]

end StairPoly

/-! ### Gradings on the socle and on the highest weight space -/

section HWGrading

variable {μ ν' : Multiset I}
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]
  (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M))

/-- The inclusion `soc(e_i^n M) = S → M`. -/
def socVal : resLeftSub S →ₗ[K] M where
  toFun v := ((ResLeft.toRes (v : ResLeft Q μ ν' M) : ResSub Q μ ν' M) : M)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

theorem socVal_injective : Function.Injective (socVal S) := fun _ _ h =>
  Subtype.ext (Subtype.ext h)

/-- **The highest weight space `HW(S)` as an `R(μ)`-submodule of `e_i^n M`**: the vectors of `S`
killed by all crossings `1 ⊗ ψ_j` of the second factor (`R(μ)`-isomorphic to `HWSpace Q μ ν' S`,
`hwLeftEquiv`). -/
def hwLeft : Submodule (KLRAlgebra K Q μ) (ResLeft Q μ ν' M) where
  carrier := {v | ResLeft.toRes v ∈ S ∧
    ∀ j : ℕ, ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] ψ j : TensorKLR Q μ ν') • ResLeft.toRes v = 0}
  add_mem' {v w} hv hw := ⟨S.add_mem hv.1 hw.1, fun j => by
    rw [resLeft_toRes_add, smul_add, hv.2 j, hw.2 j, add_zero]⟩
  zero_mem' := ⟨S.zero_mem, fun j => by rw [resLeft_toRes_zero, smul_zero]⟩
  smul_mem' a v hv := ⟨by rw [resLeft_toRes_smul]; exact S.smul_mem _ hv.1, fun j => by
    rw [resLeft_toRes_smul, smul_smul, ← tmul_one_mul_one_tmul, mul_smul, hv.2 j, smul_zero]⟩

/-- `HW(S) ≅ hwLeft S` as `R(μ)`-modules. -/
def hwLeftEquiv : HWSpace Q μ ν' S ≃ₗ[KLRAlgebra K Q μ] hwLeft S where
  toFun v := ⟨ResLeft.ofRes ((v : S) : ResSub Q μ ν' M), (v : S).2, fun j =>
    congrArg Subtype.val (v.2 j)⟩
  invFun w := ⟨⟨ResLeft.toRes (w : ResLeft Q μ ν' M), w.2.1⟩, fun j => Subtype.ext (w.2.2 j)⟩
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  left_inv _ := rfl
  right_inv _ := rfl

/-- The inclusion `HW(S) → M`. -/
def hwVal : hwLeft S →ₗ[K] M where
  toFun v := ((ResLeft.toRes (v : ResLeft Q μ ν' M) : ResSub Q μ ν' M) : M)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

theorem hwVal_injective : Function.Injective (hwVal S) := fun _ _ h =>
  Subtype.ext (Subtype.ext h)

variable (ℳ : ℤ → Submodule K M)

/-- **The grading of `soc(e_i^n M) = S`**, induced from `M`. -/
def socGrading : ℤ → Submodule K (resLeftSub S) := fun d => (ℳ d).comap (socVal S)

/-- **The grading of `HW(S) ≅ ẽ_i^n M`**, induced from `M`. -/
def hwGrading : ℤ → Submodule K (hwLeft S) := fun d => (ℳ d).comap (hwVal S)

@[simp] theorem mem_socGrading {d : ℤ} {v : resLeftSub S} :
    v ∈ socGrading S ℳ d ↔ socVal S v ∈ ℳ d := Iff.rfl

@[simp] theorem mem_hwGrading {d : ℤ} {v : hwLeft S} :
    v ∈ hwGrading S ℳ d ↔ hwVal S v ∈ ℳ d := Iff.rfl

end HWGrading

section OneTmulψ

variable {i : I} {μ ν' : Multiset I} (hν' : ∀ a ∈ ν', a = i)

/-- `1 ⊗ ψ_j` is homogeneous in `R(μ) ⊗ R(ν')` (all labels of `ν'` are equal). -/
theorem one_tmul_ψ_mem_tensorGrading (j : ℕ) :
    ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] (ψ j : KLRAlgebra K Q ν') : TensorKLR Q μ ν') ∈
      tensorGrading (G.grade μ) (G.grade ν') (G.dψ j (Seq.constSeq hν')) := by
  have h1 : (ψ j : KLRAlgebra K Q ν') ∈ G.grade ν' (G.dψ j (Seq.constSeq hν')) := by
    have := G.ψ_mul_e_mem_grade' (ν := ν') j (Seq.constSeq hν')
    rwa [e_eq_one_of_forall hν', mul_one] at this
  simpa using tmul_mem_tensorGrading (SetLike.GradedOne.one_mem (A := G.grade μ)) h1

end OneTmulψ

section HWDecomposition

variable {i : I} {μ ν' : Multiset I} (hν' : ∀ a ∈ ν', a = i)
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]
  (ℳ : ℤ → Submodule K M) [Decomposition ℳ] [SetLike.GradedSMul (G.grade (μ + ν')) ℳ]
  (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M))
  (hS : S.IsHomogeneous (resSubGrading ℳ G))

include hS

/-- Homogeneous components of an element of `S`, computed in `M`. -/
theorem decompose_val_mem (s : ResSub Q μ ν' M)
    (hs : s ∈ S) (d : ℤ) : ∃ s' ∈ S, (s' : M) = decompose ℳ (s : M) d := by
  refine ⟨decompose (resSubGrading ℳ G) s d, hS d hs, ?_⟩
  exact (decompose_map (R := K) (ℳ := resSubGrading ℳ G) (𝒩 := ℳ)
    (f := (fixSub K M (oneConcat Q μ ν')).subtype) (fun _ _ h => h) s d).symm

theorem isInternal_socGrading : IsInternal (socGrading S ℳ) :=
  show IsInternal (comap ℳ (socVal S)) from
  isInternal_comap ℳ _ (socVal_injective S) fun v d => by
    obtain ⟨s', hs', he⟩ := decompose_val_mem G ℳ S hS (ResLeft.toRes (v : ResLeft Q μ ν' M)) v.2 d
    exact ⟨⟨ResLeft.ofRes s', hs'⟩, he⟩

include hν' in
theorem hwGrading_range (v : hwLeft S) (d : ℤ) :
    (decompose ℳ (hwVal S v) d : M) ∈ LinearMap.range (hwVal S) := by
  set s : ResSub Q μ ν' M := ResLeft.toRes (v : ResLeft Q μ ν' M) with hs
  set c : ResSub Q μ ν' M := (decompose (resSubGrading ℳ G) s d : ResSub Q μ ν' M) with hc
  have hcM : (c : M) = decompose ℳ (hwVal S v) d :=
    (decompose_map (R := K) (ℳ := resSubGrading ℳ G) (𝒩 := ℳ)
      (f := (fixSub K M (oneConcat Q μ ν')).subtype) (fun _ _ h => h) s d).symm
  have hcS : c ∈ S := hS d v.2.1
  have hcHW : ∀ j : ℕ, ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] ψ j : TensorKLR Q μ ν') • c = 0 := by
    intro j
    have h := decompose_smul_of_mem_left (𝒜 := tensorGrading (G.grade μ) (G.grade ν'))
      (ℳ := resSubGrading ℳ G) (one_tmul_ψ_mem_tensorGrading G hν' j) s
      (d + G.dψ j (Seq.constSeq hν'))
    rw [add_sub_cancel_right, v.2.2 j, decompose_zero, zero_apply, ZeroMemClass.coe_zero] at h
    exact h.symm
  exact ⟨⟨ResLeft.ofRes c, hcS, hcHW⟩, hcM⟩

include hν' in
theorem isInternal_hwGrading : IsInternal (hwGrading S ℳ) :=
  show IsInternal (comap ℳ (hwVal S)) from
  isInternal_comap ℳ (hwVal S) (hwVal_injective S) (hwGrading_range G hν' ℳ S hS)

end HWDecomposition

/-! ### `V ⊠ L ≅ V^{⊕ ι}` for a basis of `L` -/

section ExtPiIdx

variable {V : Type*} [AddCommGroup V] [Module K V] {L : Type*} [AddCommGroup L] [Module K L]
  {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- `V ⊠ L ≅ V^{⊕ ι}` for a basis of `L` indexed by `ι` (`K`-linear). -/
def extTensorPiIdx (b : Basis ι K L) : ExtTensor K V L ≃ₗ[K] (ι → V) :=
  ExtTensor.equivTensor ≪≫ₗ TensorProduct.equivFinsuppOfBasisRight b ≪≫ₗ
    Finsupp.linearEquivFunOnFinite K V ι

theorem extTensorPiIdx_tmul (b : Basis ι K L) (v : V) (ℓ : L) (j : ι) :
    extTensorPiIdx b (ExtTensor.tmul v ℓ) j = b.repr ℓ j • v := by
  simp only [extTensorPiIdx, LinearEquiv.trans_apply, Finsupp.linearEquivFunOnFinite_apply]
  exact TensorProduct.equivFinsuppOfBasisRight_apply_tmul_apply b v ℓ j

theorem extTensorPiIdx_symm_apply (b : Basis ι K L) (g : ι → V) :
    (extTensorPiIdx b).symm g = ∑ u, ExtTensor.tmul (g u) (b u) := by
  rw [LinearEquiv.symm_apply_eq]
  funext j
  rw [map_sum, Finset.sum_apply, Finset.sum_eq_single j]
  · rw [extTensorPiIdx_tmul, Basis.repr_self, Finsupp.single_eq_same, one_smul]
  · intro u _ hu
    rw [extTensorPiIdx_tmul, Basis.repr_self, Finsupp.single_eq_of_ne hu, zero_smul]
  · intro h
    exact absurd (Finset.mem_univ j) h

end ExtPiIdx

/-! ### Lemma 3.14, graded -/

section Main

variable {i : I} {μ ν' : Multiset I} (hν' : ∀ a ∈ ν', a = i)
  {P : I → I → MvPolynomial (Fin 2) K}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0)
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]
  (ℳ : ℤ → Submodule K M) [Decomposition ℳ] [SetLike.GradedSMul (G.grade (μ + ν')) ℳ]
  (hnil : ∀ a, SmulNilpotent (x a : KLRAlgebra K Q (μ + ν')) M)
  (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M))

/-- The staircase monomial `x^u = ∏_a x_a^{u_a}`. -/
abbrev stair (u : Staircase (Multiset.card ν')) : MvPolynomial (Fin (Multiset.card ν')) K :=
  ∏ a, X a ^ u.1 a

include hν' in
/-- `x^u ∈ R(ν')` is homogeneous of degree `deg(x_i) · |u|`. -/
theorem pol_stair_mem_grade (u : Staircase (Multiset.card ν')) :
    (pol (stair u) : KLRAlgebra K Q ν') ∈ G.grade ν' (G.degX i * ∑ a, (u.1 a : ℤ)) := by
  have hlbl : ∀ a, (Seq.constSeq hν').lbl a = i := fun a => hν' _ (Seq.mem _ a)
  have hw : (stair u : MvPolynomial (Fin (Multiset.card ν')) K).IsWeightedHomogeneous
      (fun a => G.degX ((Seq.constSeq hν').lbl a)) (∑ a, (u.1 a : ℤ) * G.degX i) := by
    refine IsWeightedHomogeneous.prod _ _ _ fun a _ => ?_
    have := (isWeightedHomogeneous_X K (fun a => G.degX ((Seq.constSeq hν').lbl a)) a).pow (u.1 a)
    rwa [hlbl, nsmul_eq_mul] at this
  have h := G.pol_mul_e_mem_grade (Seq.constSeq hν') hw
  rwa [e_eq_one_of_forall hν', mul_one, ← Finset.sum_mul, mul_comm] at h

/-- The basis `[x^u]` of `L(i^n)` (Artin's staircase basis). -/
def stairBasis : Basis (Staircase (Multiset.card ν')) K (KLRRep hν' Q) :=
  (coinvBasis K (Multiset.card ν')).map (KLRRep.of hν' Q)

omit [DecidableEq I] in
theorem stairBasis_apply (u : Staircase (Multiset.card ν')) :
    stairBasis hν' (Q := Q) u = lMk hν' Q (stair u) := by
  rw [stairBasis, Basis.map_apply, coinvBasis_apply]
  rfl

variable {S}

/-- `S ≅ soc(e_i^n M) = resLeftSub S` as vector spaces. -/
def sToSoc : S ≃ₗ[K] resLeftSub S where
  toFun s := ⟨ResLeft.ofRes (s : ResSub Q μ ν' M), s.2⟩
  invFun v := ⟨ResLeft.toRes (v : ResLeft Q μ ν' M), v.2⟩
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  left_inv _ := rfl
  right_inv _ := rfl

include hnil in
theorem hnilS : ∀ b, SmulNilpotent ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] x b : TensorKLR Q μ ν') S :=
  fun b => smulNilpotent_submodule S (smulNilpotent_resSub b (hnil _))

theorem socVal_smul (a : KLRAlgebra K Q μ) (v : resLeftSub S) :
    socVal S (a • v) = concat Q μ ν' (a ⊗ₜ[K] (1 : KLRAlgebra K Q ν')) • socVal S v := rfl

theorem hwVal_smul (a : KLRAlgebra K Q μ) (v : hwLeft S) :
    hwVal S (a • v) = concat Q μ ν' (a ⊗ₜ[K] (1 : KLRAlgebra K Q ν')) • hwVal S v := rfl

variable [IsSimpleModule (TensorKLR Q μ ν') S]

/-- The map `(v_u)_u ↦ ∑_u (1 ⊗ x^u) v_u` of the decomposition `soc(e_i^n M) ≅ ⊕_u HW(S)`. -/
def socFun (g : Staircase (Multiset.card ν') → hwLeft S) : resLeftSub S :=
  sToSoc (hwEquiv hν' hPQ hP (hnilS (S := S) hnil)
    ((extTensorPiIdx (stairBasis hν' (Q := Q))).symm fun u => (hwLeftEquiv S).symm (g u)))

/-- The inverse of `socFun`. -/
def socInv (v : resLeftSub S) : Staircase (Multiset.card ν') → hwLeft S := fun u =>
  hwLeftEquiv S (extTensorPiIdx (stairBasis hν' (Q := Q))
    ((hwEquiv hν' hPQ hP (hnilS (S := S) hnil)).symm (sToSoc.symm v)) u)

theorem socInv_socFun (g : Staircase (Multiset.card ν') → hwLeft S) :
    socInv hν' hPQ hP hnil (socFun hν' hPQ hP hnil g) = g := by
  funext u
  simp only [socInv, socFun, LinearEquiv.symm_apply_apply, LinearEquiv.apply_symm_apply]

theorem socFun_socInv (v : resLeftSub S) :
    socFun hν' hPQ hP hnil (socInv hν' hPQ hP hnil v) = v := by
  simp only [socInv, socFun, LinearEquiv.symm_apply_apply, LinearEquiv.apply_symm_apply]

theorem socVal_socFun (g : Staircase (Multiset.card ν') → hwLeft S) :
    socVal S (socFun hν' hPQ hP hnil g) =
      ∑ u, concat Q μ ν' ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] (pol (stair u) : KLRAlgebra K Q ν')) •
        hwVal S (g u) := by
  rw [socFun, extTensorPiIdx_symm_apply, map_sum]
  simp only [stairBasis_apply, hwEquiv_tmul]
  show (((∑ u, ((1 : KLRAlgebra K Q μ) ⊗ₜ[K] pol (stair u) : TensorKLR Q μ ν') •
      ((hwLeftEquiv S).symm (g u) : S) : S) : ResSub Q μ ν' M) : M) = _
  rw [Submodule.coe_sum, Submodule.coe_sum]
  refine Finset.sum_congr rfl fun u _ => ?_
  rw [Submodule.coe_smul, coe_resSub_smul]
  rfl

/-- **The decomposition `soc(e_i^n M) ≅ ⊕_u HW(S)`**, `(v_u)_u ↦ ∑_u (1 ⊗ x^u) v_u`, as an
isomorphism of `R(μ)`-modules. -/
def socEquiv : (Staircase (Multiset.card ν') → hwLeft S) ≃ₗ[KLRAlgebra K Q μ] resLeftSub S where
  toFun := socFun hν' hPQ hP hnil
  invFun := socInv hν' hPQ hP hnil
  map_add' g g' := by
    apply socVal_injective S
    rw [LinearMap.map_add, socVal_socFun, socVal_socFun, socVal_socFun, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun u _ => ?_
    rw [Pi.add_apply, LinearMap.map_add, smul_add]
  map_smul' a g := by
    apply socVal_injective S
    rw [RingHom.id_apply, socVal_smul, socVal_socFun, socVal_socFun, Finset.smul_sum]
    refine Finset.sum_congr rfl fun u _ => ?_
    rw [Pi.smul_apply, hwVal_smul, smul_smul, smul_smul, ← concat_mul, ← concat_mul,
      tmul_one_mul_one_tmul]
  left_inv := socInv_socFun hν' hPQ hP hnil
  right_inv := socFun_socInv hν' hPQ hP hnil

variable (hS : S.IsHomogeneous (resSubGrading ℳ G))

/-- **KL I, Lemma 3.14 (graded), the isomorphism**: `soc(e_i^n M) ≅ ⊕_u HW(S){deg(x_i) |u|}` as
graded `R(μ)`-modules, for the gradings induced from `M`. -/
def socGradedEquiv :
    piGrading (fun u : Staircase (Multiset.card ν') =>
        shift (hwGrading S ℳ) (G.degX i * ∑ a, (u.1 a : ℤ))) ≃ᵍ[KLRAlgebra K Q μ]
      socGrading S ℳ :=
  letI : Decomposition (hwGrading S ℳ) := (isInternal_hwGrading G hν' ℳ S hS).chooseDecomposition
  letI : Decomposition (socGrading S ℳ) := (isInternal_socGrading G ℳ S hS).chooseDecomposition
  GradedEquiv.ofPreserves (socEquiv hν' hPQ hP hnil) fun D g hg => by
    show socVal S (socFun hν' hPQ hP hnil g) ∈ ℳ D
    rw [socVal_socFun]
    refine Submodule.sum_mem _ fun u _ => ?_
    have hu : hwVal S (g u) ∈ ℳ (D - G.degX i * ∑ a, (u.1 a : ℤ)) := hg u
    have hc := G.concat_mem_grade (ν := μ) (ν' := ν') (tmul_mem_tensorGrading
      (SetLike.GradedOne.one_mem (A := G.grade μ)) (pol_stair_mem_grade G hν' u))
    have h := SetLike.GradedSMul.smul_mem (A := G.grade (μ + ν')) hc hu
    rwa [vadd_eq_add, zero_add, add_sub_cancel] at h

end Main

/-! ### Graded dimensions -/

section Gdim

variable {ι : Type*} [Fintype ι] [DecidableEq ι] {N : ι → Type*} [∀ t, AddCommGroup (N t)]
  [∀ t, Module K (N t)]

/-- The degree-`d` part of a finite product grading. -/
def piGradingEquiv (𝒩 : ∀ t, ℤ → Submodule K (N t)) (d : ℤ) :
    piGrading 𝒩 d ≃ₗ[K] ∀ t, 𝒩 t d where
  toFun x t := ⟨(x : ∀ t, N t) t, x.2 t⟩
  invFun y := ⟨fun t => y t, fun t => (y t).2⟩
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  left_inv _ := rfl
  right_inv _ := rfl

/-- `gdim (⊕_t N_t) = ∑_t gdim N_t`. -/
theorem gdimPoly_piGrading [∀ t, FiniteDimensional K (N t)] (𝒩 : ∀ t, ℤ → Submodule K (N t))
    [∀ t, Decomposition (𝒩 t)] : gdimPoly (piGrading 𝒩) = ∑ t, gdimPoly (𝒩 t) := by
  ext d
  rw [gdimPoly_apply, Finsupp.finset_sum_apply]
  simp only [gdimPoly_apply]
  rw [← Nat.cast_sum, (piGradingEquiv 𝒩 d).finrank_eq, Module.finrank_pi_fintype]

end Gdim

section Headline

variable {i : I} {μ ν' : Multiset I} (hν' : ∀ a ∈ ν', a = i)
  {P : I → I → MvPolynomial (Fin 2) K}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0)
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K Q (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K Q (μ + ν')) M]
  (ℳ : ℤ → Submodule K M) [Decomposition ℳ] [SetLike.GradedSMul (G.grade (μ + ν')) ℳ]
  (S : Submodule (TensorKLR Q μ ν') (ResSub Q μ ν' M))

include hν' in
/-- `gdim soc(e_i^n M) = (∑_u q^{deg(x_i)|u|}) · gdim HW(S)` from the graded isomorphism. -/
theorem gdimPoly_socle_of_equiv [FiniteDimensional K M] (hS : S.IsHomogeneous (resSubGrading ℳ G))
    (f : piGrading (fun u : Staircase (Multiset.card ν') =>
        shift (hwGrading S ℳ) (G.degX i * ∑ a, (u.1 a : ℤ))) ≃ᵍ[KLRAlgebra K Q μ]
      socGrading S ℳ) :
    gdimPoly (socGrading S ℳ) = stairPoly (Multiset.card ν') (G.degX i) * gdimPoly (hwGrading S ℳ) := by
  letI : Decomposition (hwGrading S ℳ) := (isInternal_hwGrading G hν' ℳ S hS).chooseDecomposition
  haveI : FiniteDimensional K (ResLeft Q μ ν' M) :=
    inferInstanceAs (FiniteDimensional K (ResSub Q μ ν' M))
  haveI : FiniteDimensional K (hwLeft S) := finiteDimensional_submodule' (hwLeft S)
  rw [← gdimPoly_congr f, gdimPoly_piGrading, stairPoly, Finset.sum_mul]
  refine Finset.sum_congr rfl fun u _ => ?_
  exact gdimPoly_shift (hwGrading S ℳ) _

include hν' hPQ hP in
/-- **KL I, Lemma 3.14, graded.** Let `M` be a graded simple `R(μ + ν')`-module (all labels of `ν'`
equal to `i`, `n = card ν' ≤ ε_i(M)`, dots of positive degree) and `S` the socle of
`Δ_{i^n} M = 1_{μ,ν'} M`. Then, with the gradings induced from `M`:
1. `soc(e_i^n M) = S` (the ungraded Lemma 3.14);
2. `S` is a homogeneous submodule;
3. `soc(e_i^n M) ≅ ⊕_{u ∈ Staircase n} HW(S){deg(x_i) · |u|}` as graded `R(μ)`-modules;
4. `HW(S) ≅ ẽ_i^n M` as `R(μ)`-modules (Lemma 3.13);
5. `gdim soc(e_i^n M) = (∑_u q^{deg(x_i)|u|}) · gdim HW(S)`, where
   `∑_u q^{d|u|} = ∏_{a=1}^{n} (1 + q^d + ⋯ + q^{d(a-1)})` (`stairPoly_eq_prod`) is the graded
   dimension of `L(i^n)`; for KL I's grading this is `q^{n(n-1)/2} [n]!` (`gdimPoly_socle_kl`). -/
theorem lemma_3_14_graded (hG : ∀ a, 0 < G.degX a) (hM : IsGradedSimple (G.grade (μ + ν')) ℳ)
    (hle : Multiset.card ν' ≤ epsI Q (μ + ν') i M) [IsSimpleModule (TensorKLR Q μ ν') S] :
    resLeftSocle Q μ ν' M = resLeftSub S ∧
    S.IsHomogeneous (resSubGrading ℳ G) ∧
    Nonempty (piGrading (fun u : Staircase (Multiset.card ν') =>
        shift (hwGrading S ℳ) (G.degX i * ∑ a, (u.1 a : ℤ))) ≃ᵍ[KLRAlgebra K Q μ]
      socGrading S ℳ) ∧
    Nonempty (hwLeft S ≃ₗ[KLRAlgebra K Q μ] (KLRMod.eIter i μ (Multiset.card ν')
      ((KLRMod.of (Q := Q) (ν := μ + ν') M).cast (add_replicate_eq hν'))).carrier) ∧
    gdimPoly (socGrading S ℳ) =
      stairPoly (Multiset.card ν') (G.degX i) * gdimPoly (hwGrading S ℳ) := by
  obtain ⟨hfd, hsimple, hnil⟩ := crystal_hypotheses_of_isGradedSimple G hG ℳ hPQ hP hM
  haveI := hfd
  haveI := hsimple
  have hS := isHomogeneous_of_isSimpleModule G hν' hPQ hP ℳ hnil hle S
  have f := socGradedEquiv G hν' hPQ hP ℳ hnil hS (S := S)
  obtain ⟨e⟩ := lemma_3_13_hw hPQ hP hν' hnil hle S
  exact ⟨(lemma_3_14 hν' hPQ hP hnil hle S).1, hS, ⟨f⟩, ⟨(hwLeftEquiv S).symm.trans e⟩,
    gdimPoly_socle_of_equiv G hν' ℳ S hS f⟩

end Headline

section KL

variable (Γ : SimpleGraph I) [DecidableRel Γ.Adj] {i : I} {μ ν' : Multiset I}
  (hν' : ∀ a ∈ ν', a = i)
  {M : Type u} [AddCommGroup M] [Module K M] [Module (KLRAlgebra K (klQ (k := K) Γ) (μ + ν')) M]
  [IsScalarTower K (KLRAlgebra K (klQ (k := K) Γ) (μ + ν')) M]
  (ℳ : ℤ → Submodule K M) [Decomposition ℳ]
  [SetLike.GradedSMul ((klGradingDatum K Γ).grade (μ + ν')) ℳ]
  (S : Submodule (TensorKLR (klQ (k := K) Γ) μ ν') (ResSub (klQ (k := K) Γ) μ ν' M))

include hν' in
/-- **KL I, Lemma 3.14, graded, for KL I's grading** (`deg x_i = 2`): with `N = n(n-1)/2`,
`gdim soc(e_i^n M) = q^{N} [n]! · gdim HW(S) = q^{-N} [n]! · gdim (HW(S){n(n-1)})`, i.e.
`soc(e_i^n M) ≅ ẽ^{⊕ [n]!}{-n(n-1)/2}` with `ẽ = HW(S){n(n-1)}` (the top summand
`(1 ⊗ x^δ) HW(S)` of the decomposition), which is the printed formula. -/
theorem gdimPoly_socle_kl (hM : IsGradedSimple ((klGradingDatum K Γ).grade (μ + ν')) ℳ)
    (hle : Multiset.card ν' ≤ epsI (klQ (k := K) Γ) (μ + ν') i M)
    [IsSimpleModule (TensorKLR (klQ (k := K) Γ) μ ν') S] :
    gdimPoly (socGrading S ℳ) =
        LaurentPolynomial.T (((Multiset.card ν').choose 2 : ℕ) : ℤ) *
          QuantumGroup.qfact qUnitLP (Multiset.card ν') * gdimPoly (hwGrading S ℳ) ∧
      gdimPoly (socGrading S ℳ) =
        LaurentPolynomial.T (-(((Multiset.card ν').choose 2 : ℕ) : ℤ)) *
          QuantumGroup.qfact qUnitLP (Multiset.card ν') *
            gdimPoly (shift (hwGrading S ℳ) (2 * (((Multiset.card ν').choose 2 : ℕ) : ℤ))) := by
  obtain ⟨-, -, -, -, h⟩ := lemma_3_14_graded (klGradingDatum K Γ) hν'
    (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec) (fun a b _ => KL1.klP_ne_zero _ a b) ℳ S
    KL1.klGradingDatum_degX_pos hM hle
  have h2 : (klGradingDatum K Γ).degX i = 2 := rfl
  rw [h2, stairPoly_two] at h
  refine ⟨h, ?_⟩
  obtain ⟨hfd, -, hnil⟩ := crystal_hypotheses_of_isGradedSimple (klGradingDatum K Γ)
    KL1.klGradingDatum_degX_pos ℳ (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec)
    (fun a b _ => KL1.klP_ne_zero _ a b) hM
  haveI := hfd
  have hS := (lemma_3_14_graded (klGradingDatum K Γ) hν'
    (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec) (fun a b _ => KL1.klP_ne_zero _ a b) ℳ S
    KL1.klGradingDatum_degX_pos hM hle).2.1
  letI : Decomposition (hwGrading S ℳ) :=
    (isInternal_hwGrading (klGradingDatum K Γ) hν' ℳ S hS).chooseDecomposition
  haveI : FiniteDimensional K (ResLeft (klQ (k := K) Γ) μ ν' M) :=
    inferInstanceAs (FiniteDimensional K (ResSub (klQ (k := K) Γ) μ ν' M))
  haveI : FiniteDimensional K (hwLeft S) := finiteDimensional_submodule' (hwLeft S)
  rw [h, gdimPoly_shift]
  set N : ℤ := (((Multiset.card ν').choose 2 : ℕ) : ℤ)
  have hT : (LaurentPolynomial.T (-N) : LaurentPolynomial ℤ) * LaurentPolynomial.T (2 * N) =
      LaurentPolynomial.T N := by
    rw [← LaurentPolynomial.T_add]
    congr 1
    ring
  rw [← hT]
  ring

end KL

end KLRAlgebra

end Categorification.KLR

end
