/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.NilHecke
import Categorification.KLR.Examples.Small

/-!
# `R(m i)` is the nilHecke ring

M. Khovanov, A. Lauda, *A diagrammatic approach to categorification of quantum groups I*,
arXiv:0803.4121v2, §2.2 ("Examples"), item 3).

For `ν = m i` the only sequence is `i^m`, all strands carry the label `i`, and the defining
relations of `R(m i)` are those of the nilHecke ring `NH_m` (`NilHecke.nilHecke k m`, the
subalgebra of `End_k(k[x_1, …, x_m])` generated by the multiplications by `x_a` and the divided
differences `∂_a`). The isomorphism sends `1_{i^m} ↦ 1`, the dot `x_a ↦ x_a` and the crossing
`ψ_a ↦ ∂_a`. It is surjective since generators go to generators, and injective by the
faithfulness of the polynomial representation (KL I, Corollary 2.6).

## Main results

* `KLRAlgebra.equivOfForall` : when all labels of `ν` are equal, `R(ν)` does not depend on the
  data `Q` (no relation involving `Q` applies).
* `KLRAlgebra.nilHeckeEquiv` : **KL I §2.2, Example 3.** `R(m i) ≃ₐ[k] NH_m`, over any
  integral domain `k` (the paper: `k = ℤ`) and for arbitrary data `Q`, with
  `nilHeckeEquiv_e`, `nilHeckeEquiv_x`, `nilHeckeEquiv_ψ`.
* `NilHecke.basis` : for any choice `ρ` of reduced words, `{∂_{ρ w} x^u}` (`w ∈ S_m`,
  `u ∈ ℕ^m`) is a `k`-basis of `NH_m` (the case `ν = m i` of KL I, Theorem 2.5);
  `NilHecke.basisPerm` is the same basis written with `∂_w` (`NilHecke.ddPerm`), which does
  not depend on the reduced word (`NilHecke.ddw_eq_ddPerm`).
* `NilHecke.lift` : `NH_m` is presented by the relations listed in KL I §2.2, Example 3 (see
  `Categorification.Algebra.NilHecke`): any family of elements of a `k`-algebra satisfying
  them defines a unique algebra map out of `NH_m`.
-/

namespace Categorification.KLR

open MvPolynomial Equiv TypeA NilHecke PolyRep

variable {I : Type*} [DecidableEq I] {k : Type*} [CommRing k]

namespace KLRAlgebra

/-! ### Independence of `Q` -/

section equivOfForall

variable {ν : Multiset I} {i : I} (hν : ∀ a ∈ ν, a = i)

omit [DecidableEq I] in
include hν in
theorem Seq.lbl_eq_of_forall (t : Seq ν) (a b : Fin (Multiset.card ν)) : t.lbl a = t.lbl b :=
  (hν _ (t.mem a)).trans (hν _ (t.mem b)).symm

variable (Q Q' : I → I → MvPolynomial (Fin 2) k)

/-- The identity on generators, `R(ν)` for `Q` to `R(ν)` for `Q'`, when all labels are
equal. -/
private noncomputable def liftQ : KLRAlgebra k Q ν →ₐ[k] KLRAlgebra k Q' ν :=
  RingQuot.liftAlgHom k ⟨mk k Q' ν, fun a b h => by
    cases h with
    | idem_mul s t => exact rel (Rel.idem_mul s t)
    | idem_sum => exact rel Rel.idem_sum
    | dot_idem a t => exact rel (Rel.dot_idem a t)
    | cross_idem j t => exact rel (Rel.cross_idem j t)
    | cross_zero j h => exact rel (Rel.cross_zero j h)
    | dot_dot a b => exact rel (Rel.dot_dot a b)
    | cross_cross j l h => exact rel (Rel.cross_cross j l h)
    | dot_cross a j h₁ h₂ => exact rel (Rel.dot_cross a j h₁ h₂)
    | dot_cross_left j h t => exact rel (Rel.dot_cross_left j h t)
    | dot_cross_right j h t => exact rel (Rel.dot_cross_right j h t)
    | cross_sq j h t =>
      have hl := Seq.lbl_eq_of_forall hν t ⟨j, by omega⟩ ⟨j + 1, h⟩
      have := rel (Q := Q') (Rel.cross_sq j h t)
      rw [if_pos hl] at this ⊢
      exact this
    | braid j h t =>
      have hl : ¬ (t.lbl ⟨j, by omega⟩ = t.lbl ⟨j + 2, h⟩ ∧
          t.lbl ⟨j, by omega⟩ ≠ t.lbl ⟨j + 1, by omega⟩) :=
        fun c => c.2 (Seq.lbl_eq_of_forall hν t _ _)
      have := rel (Q := Q') (Rel.braid j h t)
      rw [if_neg hl] at this ⊢
      exact this⟩

private theorem liftQ_mk (a : FreeAlgebra k (Gen ν)) :
    liftQ hν Q Q' (mk k Q ν a) = mk k Q' ν a :=
  RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _

private theorem liftQ_liftQ :
    (liftQ hν Q' Q).comp (liftQ hν Q Q') = AlgHom.id k (KLRAlgebra k Q ν) :=
  algHom_ext (fun _ => by simp [e, liftQ_mk]) (fun _ => by simp [x, liftQ_mk])
    (fun _ => by simp [ψ, liftQ_mk])

/-- If all labels of `ν` are equal, `R(ν)` does not depend on the data `Q`: the identity on
the generators `e`, `x`, `ψ` is an isomorphism. -/
noncomputable def equivOfForall : KLRAlgebra k Q ν ≃ₐ[k] KLRAlgebra k Q' ν :=
  AlgEquiv.ofAlgHom (liftQ hν Q Q') (liftQ hν Q' Q) (liftQ_liftQ hν Q' Q) (liftQ_liftQ hν Q Q')

@[simp] theorem equivOfForall_e (t : Seq ν) : equivOfForall hν Q Q' (e t) = e t := liftQ_mk _ _ _ _
@[simp] theorem equivOfForall_x (a : Fin (Multiset.card ν)) :
    equivOfForall hν Q Q' (x a) = x a := liftQ_mk _ _ _ _
@[simp] theorem equivOfForall_ψ (j : ℕ) : equivOfForall hν Q Q' (ψ j) = ψ j := liftQ_mk _ _ _ _

end equivOfForall

/-! ### The map to `NH_m` -/

section toNH

variable {ν : Multiset I} {i : I} (hν : ∀ a ∈ ν, a = i)

local notation "n" => Multiset.card ν

/-- The constant data `Q = P = 1`. -/
private noncomputable abbrev one₂ : I → I → MvPolynomial (Fin 2) k := fun _ _ => 1

omit [DecidableEq I] in
private theorem hPQ_one : ∀ a b : I, a ≠ b →
    (one₂ : I → I → MvPolynomial (Fin 2) k) a b = one₂ b a * rename ![1, 0] (one₂ a b) := by
  intro a b _; simp

attribute [local instance] Seq.uniqueOfForall in
/-- The identification `Pol_ν = k[x_1, …, x_n]` (`Seq ν` is a singleton). -/
private noncomputable def polEquiv : Pol k ν ≃ₗ[k] MvPolynomial (Fin n) k :=
  @LinearEquiv.funUnique (Seq ν) k _ (Seq.uniqueOfForall hν) _ _ _

variable (Q : I → I → MvPolynomial (Fin 2) k)

/-- The action of `R(ν)` on `k[x_1, …, x_n]` (all labels equal): the polynomial
representation for the data `P = Q = 1`, transported along `equivOfForall`. -/
noncomputable def toNH : KLRAlgebra k Q ν →ₐ[k] Module.End k (MvPolynomial (Fin n) k) :=
  ((polEquiv hν).algConj k).toAlgHom.comp
    ((polyRep (hPQ_one (k := k))).comp (equivOfForall hν Q one₂).toAlgHom)

private theorem toNH_apply (r : KLRAlgebra k Q ν) (f : MvPolynomial (Fin n) k) :
    toNH hν Q r f = polyRep (hPQ_one (k := k)) (equivOfForall hν Q one₂ r) (fun _ => f)
      (Seq.uniqueOfForall hν).default := rfl

@[simp] theorem toNH_e (t : Seq ν) : toNH hν Q (e t) = 1 := by
  refine LinearMap.ext fun f => ?_
  rw [toNH_apply, equivOfForall_e, polyRep_e, opE_apply,
    if_pos (@Subsingleton.elim _ (Seq.uniqueOfForall hν).instSubsingleton _ _)]
  rfl

@[simp] theorem toNH_x (a : Fin n) : toNH hν Q (x a) = mulX k n a := by
  refine LinearMap.ext fun f => ?_
  rw [toNH_apply, equivOfForall_x, polyRep_x, opX_apply, mulX_apply]

@[simp] theorem toNH_ψ (j : ℕ) : toNH hν Q (ψ j) = dd k n j := by
  refine LinearMap.ext fun f => ?_
  rw [toNH_apply, equivOfForall_ψ, polyRep_ψ]
  by_cases h : j + 1 < n
  · rw [opΨ_apply _ j h, dd_of_lt h, crossComp, if_pos (Seq.lbl_eq_of_forall hν _ _ _)]
  · rw [opΨ_eq_zero _ (by omega), dd_eq_zero (by omega)]; rfl

@[simp] theorem toNH_pol (p : MvPolynomial (Fin n) k) : toNH hν Q (pol p) = mulPoly k n p := by
  have : (toNH hν Q).comp (pol (k := k) (Q := Q) (ν := ν)) = mulPoly k n := by
    apply MvPolynomial.algHom_ext
    intro a
    rw [AlgHom.comp_apply, pol_X, toNH_x]; rfl
  exact DFunLike.congr_fun this p

@[simp] theorem toNH_ψw (ρ : List ℕ) : toNH hν Q (ψw ρ) = ddw ρ := by
  induction ρ with
  | nil => simp
  | cons j ρ ih => rw [ψw_cons, map_mul, ih, toNH_ψ, ddw_cons]

theorem toNH_injective [IsDomain k] : Function.Injective (toNH hν Q) :=
  ((polEquiv hν).algConj k).injective.comp
    ((polyRep_injective _ fun _ _ _ => one_ne_zero).comp (equivOfForall hν Q one₂).injective)

theorem range_toNH : (toNH hν Q).range = nilHecke k n := by
  apply le_antisymm
  · rintro _ ⟨r, rfl⟩
    have hr : r ∈ Algebra.adjoin k (Set.range (e (k := k) (Q := Q) (ν := ν)) ∪ Set.range x ∪
        Set.range ψ) := by rw [adjoin_gens]; trivial
    have : toNH hν Q r ∈ (Algebra.adjoin k (Set.range (e (k := k) (Q := Q) (ν := ν)) ∪
        Set.range x ∪ Set.range ψ)).map (toNH hν Q) := Subalgebra.mem_map.2 ⟨r, hr, rfl⟩
    rw [← Algebra.adjoin_image] at this
    refine Algebra.adjoin_le ?_ this
    rintro _ ⟨s, (⟨⟨t, rfl⟩ | ⟨a, rfl⟩⟩ | ⟨j, rfl⟩), rfl⟩
    · rw [toNH_e]; exact one_mem _
    · rw [toNH_x]; exact mulX_mem a
    · rw [toNH_ψ]; exact dd_mem j
  · refine Algebra.adjoin_le ?_
    rintro _ (⟨a, rfl⟩ | ⟨j, rfl⟩)
    · exact ⟨x a, toNH_x hν Q a⟩
    · exact ⟨ψ j, toNH_ψ hν Q j⟩

/-- **KL I §2.2, Example 3** (all labels equal to `i`): `R(ν) ≅ NH_n`, `n = card ν`,
sending `e ↦ 1`, `x_a ↦ x_a`, `ψ_j ↦ ∂_j`. -/
noncomputable def nilHeckeEquivOfForall [IsDomain k] :
    KLRAlgebra k Q ν ≃ₐ[k] nilHecke k n :=
  (AlgEquiv.ofInjective (toNH hν Q) (toNH_injective hν Q)).trans
    (Subalgebra.equivOfEq _ _ (range_toNH hν Q))

@[simp] theorem coe_nilHeckeEquivOfForall [IsDomain k] (r : KLRAlgebra k Q ν) :
    (nilHeckeEquivOfForall hν Q r : Module.End k (MvPolynomial (Fin n) k)) = toNH hν Q r :=
  rfl

end toNH

/-! ### `R(m i) ≅ NH_m` -/

section replicate

variable [IsDomain k] (Q : I → I → MvPolynomial (Fin 2) k) (i : I) (m : ℕ)

omit [DecidableEq I] [IsDomain k] in
theorem forall_mem_replicate : ∀ a ∈ Multiset.replicate m i, a = i :=
  fun _ h => Multiset.eq_of_mem_replicate h

/-- **KL I §2.2, Example 3**: `R(m i) ≅ NH_m`, over any integral domain `k` (the paper:
`k = ℤ`) and for arbitrary data `Q`. The idempotent `1_{i^m}` goes to `1`, the dot `x_a` to
multiplication by `x_a`, and the crossing `ψ_a` to the divided difference `∂_a`. -/
noncomputable def nilHeckeEquiv : KLRAlgebra k Q (Multiset.replicate m i) ≃ₐ[k] nilHecke k m :=
  (nilHeckeEquivOfForall (forall_mem_replicate i m) Q).trans
    (congrRank (Multiset.card_replicate m i))

@[simp] theorem nilHeckeEquiv_e (t : Seq (Multiset.replicate m i)) :
    nilHeckeEquiv Q i m (e t) = 1 := by
  have : nilHeckeEquivOfForall (forall_mem_replicate i m) Q (e t) = 1 :=
    Subtype.ext (toNH_e _ Q t)
  rw [nilHeckeEquiv, AlgEquiv.trans_apply, this, map_one]

@[simp] theorem nilHeckeEquiv_x (a : Fin (Multiset.card (Multiset.replicate m i))) :
    nilHeckeEquiv Q i m (x a) =
      ⟨mulX k m (Fin.cast (Multiset.card_replicate m i) a), mulX_mem _⟩ := by
  rw [nilHeckeEquiv, AlgEquiv.trans_apply, ← congrRank_mulX]
  congr 1
  exact Subtype.ext (toNH_x _ Q a)

@[simp] theorem nilHeckeEquiv_ψ (j : ℕ) :
    nilHeckeEquiv Q i m (ψ j) = ⟨dd k m j, dd_mem j⟩ := by
  rw [nilHeckeEquiv, AlgEquiv.trans_apply, ← congrRank_dd (Multiset.card_replicate m i)]
  congr 1
  exact Subtype.ext (toNH_ψ _ Q j)

end replicate

end KLRAlgebra

/-! ### The basis `{∂_w x^u}` of `NH_m` -/

namespace NilHecke

open KLRAlgebra

variable [IsDomain k]

/-- The family `∂_{ρ w} x^u` in `NH_m`. -/
noncomputable def stdElt (m : ℕ) (ρ : Perm (Fin m) → List ℕ)
    (b : Perm (Fin m) × (Fin m →₀ ℕ)) : nilHecke k m :=
  ⟨ddw (ρ b.1) * mulPoly k m (monomial b.2 1), mul_mem (ddw_mem _) (mulPoly_mem _)⟩

/-- The basis statement at rank `card ν`, for `ν` over a one-point label set. -/
private theorem stdElt_basis_aux (ν : Multiset Unit)
    (ρ : Perm (Fin (Multiset.card ν)) → List ℕ)
    (hρ : ∀ w, IsReduced (Multiset.card ν) (ρ w) ∧ wordProd (Multiset.card ν) (ρ w) = w) :
    LinearIndependent k (stdElt (k := k) (Multiset.card ν) ρ) ∧
      Submodule.span k (Set.range (stdElt (k := k) (Multiset.card ν) ρ)) = ⊤ := by
  have hν : ∀ a ∈ ν, a = () := fun _ _ => rfl
  letI : Unique (Seq ν) := Seq.uniqueOfForall hν
  let Q₀ : Unit → Unit → MvPolynomial (Fin 2) k := fun _ _ => 1
  have hPQ : ∀ a b : Unit, a ≠ b → Q₀ a b = Q₀ b a * rename ![1, 0] (Q₀ a b) :=
    fun a b h => absurd (Subsingleton.elim a b) h
  let B := ((KLRAlgebra.basis (ν := ν) hPQ (fun _ _ _ => one_ne_zero) ρ hρ).map
    (nilHeckeEquivOfForall hν Q₀).toLinearEquiv).reindex (Equiv.uniqueProd _ (Seq ν))
  have hB : ⇑B = stdElt (k := k) (Multiset.card ν) ρ := by
    funext b
    apply Subtype.ext
    rw [Basis.reindex_apply, Basis.map_apply, AlgEquiv.toLinearEquiv_apply,
      KLRAlgebra.basis_apply, coe_nilHeckeEquivOfForall, map_mul, map_mul, toNH_ψw, toNH_pol,
      toNH_e, mul_one]
    rfl
  exact ⟨hB ▸ B.linearIndependent, hB ▸ B.span_eq⟩

/-- **KL I, Theorem 2.5 for `ν = m i`**: for any choice `ρ` of reduced words, the elements
`∂_{ρ w} x^u` (`w ∈ S_m`, `u ∈ ℕ^m`) are linearly independent in `NH_m` … -/
theorem linearIndependent_stdElt (m : ℕ) (ρ : Perm (Fin m) → List ℕ)
    (hρ : ∀ w, IsReduced m (ρ w) ∧ wordProd m (ρ w) = w) :
    LinearIndependent k (stdElt (k := k) m ρ) := by
  obtain ⟨ν, rfl⟩ : ∃ ν : Multiset Unit, Multiset.card ν = m :=
    ⟨Multiset.replicate m (), Multiset.card_replicate m ()⟩
  exact (stdElt_basis_aux ν ρ hρ).1

/-- … and span `NH_m`. -/
theorem span_stdElt (m : ℕ) (ρ : Perm (Fin m) → List ℕ)
    (hρ : ∀ w, IsReduced m (ρ w) ∧ wordProd m (ρ w) = w) :
    Submodule.span k (Set.range (stdElt (k := k) m ρ)) = ⊤ := by
  obtain ⟨ν, rfl⟩ : ∃ ν : Multiset Unit, Multiset.card ν = m :=
    ⟨Multiset.replicate m (), Multiset.card_replicate m ()⟩
  exact (stdElt_basis_aux ν ρ hρ).2

/-- **KL I §2.2, Example 3 / Theorem 2.5**: for any choice `ρ` of reduced words, `{∂_{ρ w} x^u}`
(`w ∈ S_m`, `u ∈ ℕ^m`) is a `k`-basis of the nilHecke ring `NH_m`. -/
noncomputable def basis (m : ℕ) (ρ : Perm (Fin m) → List ℕ)
    (hρ : ∀ w, IsReduced m (ρ w) ∧ wordProd m (ρ w) = w) :
    Basis (Perm (Fin m) × (Fin m →₀ ℕ)) k (nilHecke k m) :=
  Basis.mk (linearIndependent_stdElt m ρ hρ) (span_stdElt m ρ hρ).ge

theorem basis_apply (m : ℕ) (ρ : Perm (Fin m) → List ℕ)
    (hρ : ∀ w, IsReduced m (ρ w) ∧ wordProd m (ρ w) = w) (b : Perm (Fin m) × (Fin m →₀ ℕ)) :
    (basis (k := k) m ρ hρ b : Module.End k (MvPolynomial (Fin m) k)) =
      ddw (ρ b.1) * mulPoly k m (monomial b.2 1) := by
  simp [basis, stdElt]

/-- The basis `{∂_w x^u}` of `NH_m`, with `∂_w = ddPerm k m w` (independent of the reduced
word, `ddw_eq_ddPerm`). -/
noncomputable def basisPerm (m : ℕ) : Basis (Perm (Fin m) × (Fin m →₀ ℕ)) k (nilHecke k m) :=
  basis m (canWord m) fun w => ⟨isReduced_canWord m w, wordProd_canWord m w⟩

theorem basisPerm_apply (m : ℕ) (b : Perm (Fin m) × (Fin m →₀ ℕ)) :
    (basisPerm (k := k) m b : Module.End k (MvPolynomial (Fin m) k)) =
      ddPerm k m b.1 * mulPoly k m (monomial b.2 1) :=
  basis_apply m _ _ b

/-! ### `NH_m` is presented by the nilHecke relations -/

section lift

variable {B : Type*} [Ring B] [Algebra k B]

/-- A family `(x_a, ∂_j)` in a `k`-algebra satisfying the defining relations of `NH_m` listed
in KL I §2.2, Example 3 (zero-indexed; `∂_j` is required to vanish for `j + 1 ≥ m`, matching
`NilHecke.dd`). -/
structure IsNilHeckeFamily (m : ℕ) (X' : Fin m → B) (D : ℕ → B) : Prop where
  x_comm : ∀ a b, X' a * X' b = X' b * X' a
  d_x_comm : ∀ (j : ℕ) (a : Fin m), a.val ≠ j → a.val ≠ j + 1 → D j * X' a = X' a * D j
  d_comm : ∀ j l, j + 1 < l → D j * D l = D l * D j
  d_sq : ∀ j, D j * D j = 0
  braid : ∀ j, D j * D (j + 1) * D j = D (j + 1) * D j * D (j + 1)
  x_d_sub : ∀ j (h : j + 1 < m), X' ⟨j, by omega⟩ * D j - D j * X' ⟨j + 1, h⟩ = 1
  d_x_sub : ∀ j (h : j + 1 < m), D j * X' ⟨j, by omega⟩ - X' ⟨j + 1, h⟩ * D j = 1
  d_zero : ∀ j, m ≤ j + 1 → D j = 0

omit [IsDomain k] in
/-- The generators of `NH_m` satisfy the defining relations. -/
theorem isNilHeckeFamily_gens (m : ℕ) :
    IsNilHeckeFamily (B := Module.End k (MvPolynomial (Fin m) k)) m (mulX k m) (dd k m) where
  x_comm := mulX_mul_mulX
  d_x_comm := dd_mul_mulX
  d_comm _ _ h := dd_mul_dd h
  d_sq := dd_mul_self
  braid := dd_braid
  x_d_sub _ h := mulX_dd_sub_dd_mulX h
  d_x_sub _ h := dd_mulX_sub_mulX_dd h
  d_zero _ h := dd_eq_zero h

variable {m : ℕ} {X' : Fin m → B} {D : ℕ → B} (hF : IsNilHeckeFamily m X' D)

private abbrev νm (m : ℕ) : Multiset Unit := Multiset.replicate m ()

private noncomputable abbrev Q₁ : Unit → Unit → MvPolynomial (Fin 2) k := fun _ _ => 1

private theorem card_νm (m : ℕ) : Multiset.card (νm m) = m := Multiset.card_replicate m ()

private noncomputable def genB (X' : Fin m → B) (D : ℕ → B) : Gen (νm m) → B
  | .idem _ => 1
  | .dot a => X' (Fin.cast (card_νm m) a)
  | .cross j => D j

omit [IsDomain k] in
include hF in
private theorem genB_rel ⦃a b : FreeAlgebra k (Gen (νm m))⦄ (h : Rel k Q₁ (νm m) a b) :
    FreeAlgebra.lift k (genB X' D) a = FreeAlgebra.lift k (genB X' D) b := by
  haveI : Unique (Seq (νm m)) := Seq.uniqueOfForall (i := ()) fun _ _ => rfl
  have hl : ∀ (t : Seq (νm m)) (a b : Fin (Multiset.card (νm m))), t.lbl a = t.lbl b :=
    fun _ _ _ => rfl
  cases h with
  | idem_mul s t =>
    rw [if_pos (Subsingleton.elim s t)]; simp [fe, genB]
  | idem_sum => simp [fe, genB]
  | dot_idem a t => simp [fe, fx, genB]
  | cross_idem j t => simp [fe, fψ, genB]
  | cross_zero j h =>
    simp only [fψ, FreeAlgebra.lift_ι_apply, genB, map_zero]
    exact hF.d_zero j (by rw [card_νm] at h; exact h)
  | dot_dot a b => simp only [fx, map_mul, FreeAlgebra.lift_ι_apply, genB]; exact hF.x_comm _ _
  | cross_cross j l h =>
    simp only [fψ, map_mul, FreeAlgebra.lift_ι_apply, genB]; exact hF.d_comm j l h
  | dot_cross a j h₁ h₂ =>
    simp only [fx, fψ, map_mul, FreeAlgebra.lift_ι_apply, genB]
    exact (hF.d_x_comm j _ h₁ h₂).symm
  | dot_cross_left j h t =>
    rw [if_pos (hl t _ _)]
    simp only [fx, fψ, fe, map_mul, map_sub, FreeAlgebra.lift_ι_apply, genB, mul_one]
    exact hF.x_d_sub j (by rw [card_νm] at h; exact h)
  | dot_cross_right j h t =>
    rw [if_pos (hl t _ _)]
    simp only [fx, fψ, fe, map_mul, map_sub, FreeAlgebra.lift_ι_apply, genB, mul_one]
    exact hF.d_x_sub j (by rw [card_νm] at h; exact h)
  | cross_sq j h t =>
    rw [if_pos (hl t _ _)]
    simp only [fψ, fe, map_mul, FreeAlgebra.lift_ι_apply, genB, mul_one, map_zero]
    exact hF.d_sq j
  | braid j h t =>
    rw [if_neg (fun c => c.2 (hl t _ _))]
    simp only [fψ, fe, map_mul, map_sub, FreeAlgebra.lift_ι_apply, genB, mul_one, map_zero]
    exact sub_eq_zero.2 (hF.braid j)

/-- The algebra map out of `R(m i)` (labels in a one-point set) determined by a nilHecke
family. -/
private noncomputable def liftR : KLRAlgebra k Q₁ (νm m) →ₐ[k] B :=
  RingQuot.liftAlgHom k ⟨FreeAlgebra.lift k (genB X' D), fun _ _ h => genB_rel hF h⟩

omit [IsDomain k] in
private theorem liftR_mk (a : FreeAlgebra k (Gen (νm m))) :
    liftR hF (mk k Q₁ (νm m) a) = FreeAlgebra.lift k (genB X' D) a :=
  RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _

/-- **`NH_m` is presented by the relations of KL I §2.2, Example 3**: a family `(x_a, ∂_j)` in a
`k`-algebra `B` satisfying them defines an algebra map `NH_m → B` (`lift_mulX`, `lift_dd`),
which is unique (`algHom_ext`). -/
noncomputable def lift : nilHecke k m →ₐ[k] B :=
  (liftR hF).comp (KLRAlgebra.nilHeckeEquiv Q₁ () m).symm.toAlgHom

@[simp] theorem lift_mulX (a : Fin m) : lift hF ⟨mulX k m a, mulX_mem a⟩ = X' a := by
  have : (KLRAlgebra.nilHeckeEquiv Q₁ () m).symm ⟨mulX k m a, mulX_mem a⟩ =
      x (Fin.cast (card_νm m).symm a) := by
    rw [AlgEquiv.symm_apply_eq, nilHeckeEquiv_x]; rfl
  rw [lift, AlgHom.comp_apply, AlgEquiv.toAlgHom_eq_coe, AlgHom.coe_coe, this, x, liftR_mk,
    FreeAlgebra.lift_ι_apply]
  rfl

@[simp] theorem lift_dd (j : ℕ) : lift hF ⟨dd k m j, dd_mem j⟩ = D j := by
  have : (KLRAlgebra.nilHeckeEquiv Q₁ () m).symm ⟨dd k m j, dd_mem j⟩ = ψ j := by
    rw [AlgEquiv.symm_apply_eq, nilHeckeEquiv_ψ]
  rw [lift, AlgHom.comp_apply, AlgEquiv.toAlgHom_eq_coe, AlgHom.coe_coe, this, ψ, liftR_mk,
    FreeAlgebra.lift_ι_apply]
  rfl

/-- Algebra maps out of `NH_m` are determined by the images of the `x_a` and `∂_j`. -/
theorem algHom_ext {f g : nilHecke k m →ₐ[k] B}
    (hx : ∀ a, f ⟨mulX k m a, mulX_mem a⟩ = g ⟨mulX k m a, mulX_mem a⟩)
    (hd : ∀ j, f ⟨dd k m j, dd_mem j⟩ = g ⟨dd k m j, dd_mem j⟩) : f = g := by
  set E := KLRAlgebra.nilHeckeEquiv (k := k) Q₁ () m
  have : f.comp E.toAlgHom = g.comp E.toAlgHom := by
    refine KLRAlgebra.algHom_ext (fun t => ?_) (fun a => ?_) (fun j => ?_)
    · simp [E]
    · simp only [AlgHom.comp_apply, AlgEquiv.toAlgHom_eq_coe, AlgHom.coe_coe, E,
        nilHeckeEquiv_x, hx]
    · simp only [AlgHom.comp_apply, AlgEquiv.toAlgHom_eq_coe, AlgHom.coe_coe, E,
        nilHeckeEquiv_ψ, hd]
  ext z
  obtain ⟨r, rfl⟩ := E.surjective z
  exact DFunLike.congr_fun this r

end lift

end NilHecke

end Categorification.KLR
