/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.KL1Basis

/-!
# Examples of KLR algebras: zero and one strand

M. Khovanov, A. Lauda, *A diagrammatic approach to categorification of quantum groups I*,
arXiv:0803.4121v2, §2.2 ("Examples"), items 1) and 2).

* `KLRAlgebra.zeroEquiv` : **Example 1.** `R(0) ≅ k` (the paper: `R(0) = ℤ`, the unit being
  the empty diagram).
* `KLRAlgebra.singleEquiv` : **Example 2.** `R(i) ≅ k[x]`, the variable corresponding to the
  dot `x_{1,i}` (the paper: `R(i) ≅ ℤ[x_{1,i}]`).

Both hold over any commutative ring `k` and for arbitrary data `Q` (on at most one strand no
relation involving `Q` applies). We also record some general tools used for the other
examples: `KLRAlgebra.algHom_ext` (algebra maps out of `R(ν)` are determined by the
generators), `KLRAlgebra.adjoin_gens` (`R(ν)` is generated by `e i`, `x a`, `ψ j`), and
`Seq.uniqueOfForall` (`Seq ν` is a singleton when all labels are equal).
-/

namespace Categorification.KLR

open MvPolynomial

variable {I : Type*} [DecidableEq I] {k : Type*} [CommRing k]
  {Q : I → I → MvPolynomial (Fin 2) k}

/-! ### General tools -/

omit [DecidableEq I] in
/-- For pairwise commuting arguments in a commutative algebra, `ncEval` is `aeval`. -/
theorem ncEval_eq_aeval {B : Type*} [CommRing B] [Algebra k B] {n : ℕ} (y : Fin n → B)
    (p : MvPolynomial (Fin n) k) : ncEval y p = aeval y p := by
  simp only [ncEval, aeval_def, eval₂, List.prod_ofFn]
  refine Finsupp.sum_congr fun s _ => ?_
  rw [Finsupp.prod_fintype _ _ (fun _ => pow_zero _)]

namespace Seq

/-- If all labels of `ν` equal `i`, then `Seq ν` is a singleton, `{i i ⋯ i}`. -/
def uniqueOfForall {ν : Multiset I} {i : I} (hν : ∀ a ∈ ν, a = i) : Unique (Seq ν) where
  default := ⟨fun _ => i, by
    rw [Multiset.map_const', Finset.card_val, Finset.card_univ, Fintype.card_fin]
    exact (Multiset.eq_replicate_card.2 hν).symm⟩
  uniq t := Subtype.ext (funext fun a => hν _ (t.mem a))

/-- `Seq 0` is a singleton (the empty sequence). -/
instance uniqueZero : Unique (Seq (0 : Multiset I)) where
  default := ⟨Fin.elim0, by simp⟩
  uniq t := Subtype.ext (funext fun a => a.elim0)

end Seq

namespace KLRAlgebra

variable {ν : Multiset I}

/-- Two algebra maps out of `R(ν)` agreeing on the generators `e i`, `x a`, `ψ j` are equal. -/
theorem algHom_ext {B : Type*} [Semiring B] [Algebra k B] {f g : KLRAlgebra k Q ν →ₐ[k] B}
    (he : ∀ i, f (e i) = g (e i)) (hx : ∀ a, f (x a) = g (x a)) (hψ : ∀ j, f (ψ j) = g (ψ j)) :
    f = g := by
  apply RingQuot.ringQuot_ext'
  apply FreeAlgebra.hom_ext
  funext gen
  simp only [Function.comp_apply, AlgHom.comp_toLinearMap, LinearMap.coe_comp,
    AlgHom.toLinearMap_apply]
  cases gen with
  | idem i => exact he i
  | dot a => exact hx a
  | cross j => exact hψ j

/-- `R(ν)` is generated as a `k`-algebra by the `e i`, `x a` and `ψ j`. -/
theorem adjoin_gens :
    Algebra.adjoin k (Set.range (e (k := k) (Q := Q) (ν := ν)) ∪ Set.range x ∪ Set.range ψ) =
      ⊤ := by
  rw [eq_top_iff]
  rintro r -
  obtain ⟨a, rfl⟩ := mk_surjective (k := k) (Q := Q) (ν := ν) r
  induction a using FreeAlgebra.induction with
  | grade0 c => rw [AlgHom.commutes]; exact Subalgebra.algebraMap_mem _ c
  | grade1 g =>
    apply Algebra.subset_adjoin
    cases g with
    | idem i => exact Or.inl (Or.inl ⟨i, rfl⟩)
    | dot a => exact Or.inl (Or.inr ⟨a, rfl⟩)
    | cross j => exact Or.inr ⟨j, rfl⟩
  | mul a b ha hb => rw [map_mul]; exact mul_mem ha hb
  | add a b ha hb => rw [map_add]; exact add_mem ha hb

/-- An algebra map out of `R(ν)` takes values in a subalgebra `S` as soon as the generators
do. -/
theorem mem_of_gens {B : Type*} [Semiring B] [Algebra k B] (f : KLRAlgebra k Q ν →ₐ[k] B)
    (S : Subalgebra k B) (he : ∀ i, f (e i) ∈ S) (hx : ∀ a, f (x a) ∈ S) (hψ : ∀ j, f (ψ j) ∈ S)
    (r : KLRAlgebra k Q ν) : f r ∈ S := by
  obtain ⟨a, rfl⟩ := mk_surjective (k := k) (Q := Q) (ν := ν) r
  induction a using FreeAlgebra.induction with
  | grade0 c => rw [AlgHom.commutes, AlgHom.commutes]; exact Subalgebra.algebraMap_mem _ c
  | grade1 g =>
    cases g with
    | idem i => exact he i
    | dot a => exact hx a
    | cross j => exact hψ j
  | mul a b ha hb => rw [map_mul, map_mul]; exact mul_mem ha hb
  | add a b ha hb => rw [map_add, map_add]; exact add_mem ha hb

/-- If `Seq ν` is a singleton, its idempotent is the unit. -/
theorem e_eq_one [Unique (Seq ν)] (i : Seq ν) : (e i : KLRAlgebra k Q ν) = 1 := by
  rw [← sum_e (k := k) (Q := Q) (ν := ν), Fintype.sum_unique, Subsingleton.elim i default]

/-! ### Example 1: `R(0) ≅ k` -/

section zero

/-- The values of the generators of `R(0)` in `k`. -/
private noncomputable def gen0 : Gen (0 : Multiset I) → k
  | .idem _ => 1
  | .dot a => a.elim0
  | .cross _ => 0

variable (k Q) in
private noncomputable def toBase0 : KLRAlgebra k Q (0 : Multiset I) →ₐ[k] k :=
  RingQuot.liftAlgHom k ⟨FreeAlgebra.lift k gen0, fun a b h => by
    cases h with
    | idem_mul i j =>
      rw [if_pos (Subsingleton.elim i j)]; simp [fe, gen0]
    | idem_sum => simp [fe, gen0]
    | dot_idem a _ => exact a.elim0
    | cross_idem j i => simp [fe, fψ, gen0]
    | cross_zero j h => simp [fψ, gen0]
    | dot_dot a _ => exact a.elim0
    | cross_cross j l h => simp [fψ, gen0]
    | dot_cross a _ _ _ => exact a.elim0
    | dot_cross_left j h => exact absurd h (by simp)
    | dot_cross_right j h => exact absurd h (by simp)
    | cross_sq j h => exact absurd h (by simp)
    | braid j h => exact absurd h (by simp)⟩

private theorem toBase0_mk (a : FreeAlgebra k (Gen (0 : Multiset I))) :
    toBase0 k Q (mk k Q 0 a) = FreeAlgebra.lift k gen0 a :=
  RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _

private theorem toBase0_e (i : Seq (0 : Multiset I)) : toBase0 k Q (e i) = 1 := by
  rw [e, toBase0_mk, FreeAlgebra.lift_ι_apply]; rfl

private theorem toBase0_ψ (j : ℕ) : toBase0 k Q (ψ j : KLRAlgebra k Q (0 : Multiset I)) = 0 := by
  rw [ψ, toBase0_mk, FreeAlgebra.lift_ι_apply]; rfl

variable (k Q I) in
/-- **KL I §2.2, Example 1**: `R(0) ≅ k`, the unit (the empty diagram) corresponding to `1`.
(The paper: `R(0) = ℤ`.) -/
noncomputable def zeroEquiv : KLRAlgebra k Q (0 : Multiset I) ≃ₐ[k] k :=
  AlgEquiv.ofAlgHom (toBase0 k Q) (Algebra.ofId k _)
    (AlgHom.ext fun c => by simp; rfl)
    (algHom_ext
      (fun i => by rw [AlgHom.comp_apply, toBase0_e, map_one, AlgHom.id_apply, e_eq_one])
      (fun a => a.elim0)
      (fun j => by
        rw [AlgHom.comp_apply, toBase0_ψ, map_zero, AlgHom.id_apply, ψ_eq_zero j (by simp)]))

theorem zeroEquiv_symm_apply (c : k) :
    (zeroEquiv I k Q).symm c = algebraMap k (KLRAlgebra k Q (0 : Multiset I)) c := rfl

end zero

/-! ### Example 2: `R(i) ≅ k[x]` -/

section single

variable (i : I)

/-- The values of the generators of `R(i)` in `k[x]`. -/
private noncomputable def gen1 : Gen ({i} : Multiset I) → Polynomial k
  | .idem _ => 1
  | .dot _ => Polynomial.X
  | .cross _ => 0

instance : Unique (Seq ({i} : Multiset I)) :=
  Seq.uniqueOfForall (i := i) fun _ h => Multiset.mem_singleton.1 h

variable (k Q) in
private noncomputable def toPoly1 : KLRAlgebra k Q ({i} : Multiset I) →ₐ[k] Polynomial k :=
  RingQuot.liftAlgHom k ⟨FreeAlgebra.lift k (gen1 i), fun a b h => by
    cases h with
    | idem_mul s t =>
      rw [if_pos (Subsingleton.elim s t)]; simp [fe, gen1]
    | idem_sum => simp [fe, gen1]
    | dot_idem a t => simp [fe, fx, gen1]
    | cross_idem j t => simp [fe, fψ, gen1]
    | cross_zero j h => simp [fψ, gen1]
    | dot_dot a b => simp [fx, gen1]
    | cross_cross j l h => simp [fψ, gen1]
    | dot_cross a j _ _ => simp [fx, fψ, gen1]
    | dot_cross_left j h => exact absurd h (by simp)
    | dot_cross_right j h => exact absurd h (by simp)
    | cross_sq j h => exact absurd h (by simp)
    | braid j h => exact absurd h (by simp)⟩

private theorem toPoly1_mk (a : FreeAlgebra k (Gen ({i} : Multiset I))) :
    toPoly1 k Q i (mk k Q {i} a) = FreeAlgebra.lift k (gen1 i) a :=
  RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _

private theorem toPoly1_e (t : Seq ({i} : Multiset I)) : toPoly1 k Q i (e t) = 1 := by
  rw [e, toPoly1_mk, FreeAlgebra.lift_ι_apply]; rfl

private theorem toPoly1_x (a : Fin 1) : toPoly1 k Q i (x a) = Polynomial.X := by
  rw [x, toPoly1_mk, FreeAlgebra.lift_ι_apply]; rfl

private theorem toPoly1_ψ (j : ℕ) :
    toPoly1 k Q i (ψ j : KLRAlgebra k Q ({i} : Multiset I)) = 0 := by
  rw [ψ, toPoly1_mk, FreeAlgebra.lift_ι_apply]; rfl

variable (k Q) in
/-- **KL I §2.2, Example 2**: `R(i) ≅ k[x]`, the dot `x_{1,i}` on the single strand
corresponding to the variable. (The paper: `R(i) ≅ ℤ[x_{1,i}]`.) -/
noncomputable def singleEquiv : KLRAlgebra k Q ({i} : Multiset I) ≃ₐ[k] Polynomial k :=
  AlgEquiv.ofAlgHom (toPoly1 k Q i) (Polynomial.aeval (x ⟨0, by simp⟩))
    (Polynomial.algHom_ext (by
      rw [AlgHom.comp_apply, Polynomial.aeval_X, toPoly1_x, AlgHom.id_apply]))
    (algHom_ext
      (fun t => by rw [AlgHom.comp_apply, toPoly1_e, map_one, AlgHom.id_apply, e_eq_one])
      (fun a => by
        rw [AlgHom.comp_apply, toPoly1_x, Polynomial.aeval_X, AlgHom.id_apply]
        congr 1; ext
        have := a.isLt
        simp only [Multiset.card_singleton] at this
        simp only [Fin.val_zero]; omega)
      (fun j => by
        rw [AlgHom.comp_apply, toPoly1_ψ, map_zero, AlgHom.id_apply, ψ_eq_zero j (by simp)]))

@[simp] theorem singleEquiv_x (a : Fin 1) :
    singleEquiv k Q i (x a) = Polynomial.X := toPoly1_x i a

@[simp] theorem singleEquiv_e (t : Seq ({i} : Multiset I)) :
    singleEquiv k Q i (e t) = 1 := toPoly1_e i t

theorem singleEquiv_symm_X :
    (singleEquiv k Q i).symm Polynomial.X = x ⟨0, by simp⟩ := by
  show Polynomial.aeval _ _ = _
  rw [Polynomial.aeval_X]

end single

end KLRAlgebra

end Categorification.KLR
