/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.Coinvariant
import Categorification.Algebra.NilHecke
import Categorification.Algebra.Graded.Quotient

/-!
# The grading of the coinvariant algebra `L_m`

Khovanov–Lauda I (arXiv:0803.4121v2), §2.2: `L_m = k[x_1, …, x_m] / (Sym⁺)` is a graded
`NH_m`-module. We grade `k[x_1, …, x_m]` by `deg x_a = c` for a fixed integer `c` (`c = 2` in KL I,
`c = i · i` in KL II), so that the multiplications by `x_a` have degree `c` and the divided
differences `∂_j` have degree `-c`:

* `constGrade k m c` : the grading of `k[x]` with all variables of degree `c` (a graded algebra);
* `decompose_constGrade_mem_coinvIdeal` : the ideal `(Sym⁺)` is homogeneous (it is generated by
  the homogeneous elementary symmetric polynomials);
* `coinvGrading k m c` : the induced grading of `L_m` (a `Decomposition`);
* `mul_mem_constGrade_X`, `dd_mem_constGrade` : `x_a` raises and `∂_j` lowers the degree by `c`.
-/

namespace Categorification

open MvPolynomial Equiv DirectSum Graded

variable {k : Type*} [Field k] {m : ℕ}

/-! ### Divided differences are homogeneous of degree `-1` -/

section Homogeneous

variable {σ : Type*} [DecidableEq σ] {a b : σ}

private theorem degree_erase_erase' (hab : a ≠ b) (s : σ →₀ ℕ) :
    ((s.erase a).erase b).degree + s a + s b = s.degree := by
  conv_rhs => rw [← erase_add_single hab s]
  rw [Finsupp.degree_add, Finsupp.degree_add, Finsupp.degree_single, Finsupp.degree_single]

omit [DecidableEq σ] in
private theorem isHomogeneous_ddiffMonomial_aux' (r : MvPolynomial σ k) {e : ℕ}
    (hr : r.IsHomogeneous e) (p q : ℕ) :
    (r * ∑ t ∈ Finset.range (p - q), X a ^ (q + t) * X b ^ (p - 1 - t)).IsHomogeneous
      (e + (p + q - 1)) := by
  refine hr.mul (IsHomogeneous.sum _ _ _ fun t ht => ?_)
  rw [Finset.mem_range] at ht
  have := (isHomogeneous_X_pow (R := k) a (q + t)).mul (isHomogeneous_X_pow (R := k) b (p - 1 - t))
  convert this using 1
  omega

private theorem isHomogeneous_ddiffMonomial' (hab : a ≠ b) (s : σ →₀ ℕ) {d : ℕ}
    (hs : s.degree = d + 1) : (ddiffMonomial (k := k) a b s).IsHomogeneous d := by
  have hdeg := degree_erase_erase' hab s
  have hr : (monomial ((s.erase a).erase b) (1 : k)).IsHomogeneous
      ((s.erase a).erase b).degree := isHomogeneous_monomial _ rfl
  unfold ddiffMonomial
  simp only
  split_ifs with h
  · by_cases hp : s b < s a
    · have := isHomogeneous_ddiffMonomial_aux' (a := a) (b := b) _ hr (s a) (s b)
      convert this using 1
      omega
    · rw [show s a - s b = 0 by omega, Finset.range_zero, Finset.sum_empty, mul_zero]
      exact isHomogeneous_zero _ _ _
  · have := isHomogeneous_ddiffMonomial_aux' (a := a) (b := b) _ hr (s b) (s a)
    convert this.neg using 1
    omega

end Homogeneous

/-! ### The grading with all variables of degree `c` -/

variable (k m) in
/-- The grading of `k[x_1, …, x_m]` with `deg x_a = c` for all `a`. -/
def constGrade (c : ℤ) : ℤ → Submodule k (MvPolynomial (Fin m) k) :=
  weightedHomogeneousSubmodule k (fun _ : Fin m => c)

noncomputable instance (c : ℤ) : GradedAlgebra (constGrade k m c) :=
  weightedGradedAlgebra k (fun _ : Fin m => c)

theorem mem_constGrade {c d : ℤ} {p : MvPolynomial (Fin m) k} :
    p ∈ constGrade k m c d ↔ p.IsWeightedHomogeneous (fun _ => c) d :=
  mem_weightedHomogeneousSubmodule _ _ _ _

theorem weight_const (c : ℤ) (s : Fin m →₀ ℕ) :
    Finsupp.weight (fun _ : Fin m => c) s = c * (s.degree : ℤ) := by
  rw [Finsupp.weight_apply, Finsupp.sum, Finsupp.degree, Nat.cast_sum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [nsmul_eq_mul, mul_comm]

theorem mem_constGrade_of_isHomogeneous (c : ℤ) {p : MvPolynomial (Fin m) k} {D : ℕ}
    (hp : p.IsHomogeneous D) : p ∈ constGrade k m c (c * D) := by
  rw [mem_constGrade]
  intro s hs
  have := hp hs
  rw [weight_const, Finsupp.degree_eq_weight_one]
  exact congrArg (fun n : ℕ => c * (n : ℤ)) this

theorem X_mem_constGrade (c : ℤ) (a : Fin m) : (X a : MvPolynomial (Fin m) k) ∈ constGrade k m c c :=
  (mem_constGrade).2 (isWeightedHomogeneous_X k _ a)

theorem mul_mem_constGrade_X {c e : ℤ} (a : Fin m) {p : MvPolynomial (Fin m) k}
    (hp : p ∈ constGrade k m c e) : X a * p ∈ constGrade k m c (c + e) :=
  (mem_constGrade).2 (((mem_constGrade).1 (X_mem_constGrade c a)).mul ((mem_constGrade).1 hp))

theorem mul_mem_constGrade {c e f : ℤ} {p q : MvPolynomial (Fin m) k}
    (hp : p ∈ constGrade k m c e) (hq : q ∈ constGrade k m c f) : p * q ∈ constGrade k m c (e + f) :=
  (mem_constGrade).2 (((mem_constGrade).1 hp).mul ((mem_constGrade).1 hq))

/-- `(Sym⁺)` is homogeneous for `constGrade`. -/
theorem decompose_constGrade_mem_coinvIdeal (c : ℤ) (d : ℤ) {p : MvPolynomial (Fin m) k}
    (hp : p ∈ coinvIdeal k m) : (decompose (constGrade k m c) p d : MvPolynomial (Fin m) k) ∈
      coinvIdeal k m := by
  have hhom := Ideal.homogeneous_span (constGrade k m c)
    (Set.range fun r : Fin m => esymm (Fin m) k (r + 1)) (by
      rintro _ ⟨r, rfl⟩
      exact ⟨_, mem_constGrade_of_isHomogeneous c (esymm_isHomogeneous _ _)⟩)
  rw [coinvIdeal_eq_span_esymm] at hp ⊢
  exact hhom d hp

/-- Divided differences lower the degree by `c`. -/
theorem ddiff_mem_constGrade {c e : ℤ} {a b : Fin m} (hab : a ≠ b) {p : MvPolynomial (Fin m) k}
    (hp : p ∈ constGrade k m c e) : ddiff a b p ∈ constGrade k m c (e - c) := by
  rw [p.as_sum, map_sum]
  refine Submodule.sum_mem _ fun s hs => ?_
  have hw : Finsupp.weight (fun _ => c) s = e := (mem_constGrade.1 hp) (mem_support_iff.1 hs)
  rw [weight_const] at hw
  have hc : (monomial s (coeff s p) : MvPolynomial (Fin m) k) = coeff s p • monomial s 1 := by
    rw [smul_monomial, smul_eq_mul, mul_one]
  rw [hc, map_smul]
  refine Submodule.smul_mem _ _ ?_
  by_cases h0 : s.degree = 0
  · have : s = 0 := by
      rw [Finsupp.degree_eq_zero_iff] at h0
      exact h0
    subst this
    rw [← C_apply, ddiff_C hab]
    exact zero_mem _
  · obtain ⟨D, hD⟩ := Nat.exists_eq_succ_of_ne_zero h0
    rw [ddiff_monomial_one]
    have := mem_constGrade_of_isHomogeneous (k := k) c
      (isHomogeneous_ddiffMonomial' (k := k) hab s hD)
    convert this using 2
    rw [← hw, hD]
    push_cast
    ring

/-- `∂_j` lowers the degree by `c` (it is zero if `j + 1 ≥ m`). -/
theorem dd_mem_constGrade {c e : ℤ} (j : ℕ) {p : MvPolynomial (Fin m) k}
    (hp : p ∈ constGrade k m c e) : NilHecke.dd k m j p ∈ constGrade k m c (e - c) := by
  by_cases h : j + 1 < m
  · rw [NilHecke.dd_of_lt h]
    exact ddiff_mem_constGrade (fun e => by simp [Fin.ext_iff] at e) hp
  · rw [NilHecke.dd_eq_zero (by omega), LinearMap.zero_apply]
    exact zero_mem _

/-! ### The grading of `L_m` -/

variable (k m) in
/-- The grading of `L_m = k[x] / (Sym⁺)` induced by `deg x_a = c`. -/
noncomputable def coinvGrading (c : ℤ) : ℤ → Submodule k (Coinv k m) :=
  quotGrading (constGrade k m c) (coinvSub k m)

noncomputable instance (c : ℤ) : Decomposition (coinvGrading k m c) :=
  quotDecomposition (constGrade k m c) (coinvSub k m)
    fun d _ hx => decompose_constGrade_mem_coinvIdeal c d hx

end Categorification
