/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.SymmetricFree
import Categorification.Algebra.AugmentationQuotient

/-!
# The coinvariant algebra `k[x_1, …, x_m] / (Sym⁺)`

Khovanov–Lauda I (arXiv:0803.4121v2), §2.2 (TeX lines 733–760) considers the quotient `L_m` of
`k[x_1, …, x_m]` by the ideal generated by the symmetric polynomials without constant term (the
cohomology ring of the full flag variety). This file sets up its elementary structure over a
field `k`:

* `coinvIdeal k m` : the ideal generated by `Sym⁺`; it is generated by the elementary symmetric
  polynomials `e_1, …, e_m` (`coinvIdeal_eq_span_esymm`) and is homogeneous
  (`homogeneousComponent_mem_coinvIdeal`);
* `Coinv k m = k[x] / coinvIdeal` as a `k`-vector space, with basis the classes of the staircase
  monomials `∏ x_a ^ u_a`, `u_a ≤ a` (`coinvBasis`, from Artin's theorem), so
  `dim_k Coinv k m = m!` (`finrank_coinv`);
* every homogeneous polynomial of degree `> m(m-1)/2` lies in `coinvIdeal`
  (`mem_coinvIdeal_of_isHomogeneous`), and `x_a ^ m ∈ coinvIdeal` (`X_pow_mem_coinvIdeal`).

Variables are zero-indexed: the paper's `x_a` is `X ⟨a - 1, _⟩`.
-/

namespace Categorification

open MvPolynomial

variable (k : Type*) [Field k]

/-- The symmetric polynomials without constant term. -/
def symPlusSet (m : ℕ) : Set (MvPolynomial (Fin m) k) :=
  {s | s.IsSymmetric ∧ constantCoeff s = 0}

/-- The ideal of `k[x_1, …, x_m]` generated by the symmetric polynomials without constant term. -/
noncomputable def coinvIdeal (m : ℕ) : Ideal (MvPolynomial (Fin m) k) :=
  Ideal.span (symPlusSet k m)

/-- `coinvIdeal` as a `k`-subspace. -/
noncomputable def coinvSub (m : ℕ) : Submodule k (MvPolynomial (Fin m) k) :=
  (coinvIdeal k m).restrictScalars k

/-- **The coinvariant algebra** `L_m = k[x_1, …, x_m] / (Sym⁺)` (KL I §2.2), as a `k`-vector
space. -/
abbrev Coinv (m : ℕ) : Type _ := MvPolynomial (Fin m) k ⧸ coinvSub k m

variable {k}

theorem mem_coinvSub {m : ℕ} {p : MvPolynomial (Fin m) k} : p ∈ coinvSub k m ↔ p ∈ coinvIdeal k m :=
  Iff.rfl

/-! ### Generators -/

theorem esymm_isHomogeneous (σ : Type*) [Fintype σ] (n : ℕ) :
    (esymm σ k n).IsHomogeneous n := by
  rw [esymm_eq_sum_subtype]
  refine IsHomogeneous.sum _ _ _ fun t _ => ?_
  have := IsHomogeneous.prod (t : Finset σ) (fun i => (X i : MvPolynomial σ k)) (fun _ => 1)
    (fun i _ => isHomogeneous_X k i)
  simpa [t.2] using this

theorem constantCoeff_esymm_succ (σ : Type*) [Fintype σ] (r : ℕ) :
    constantCoeff (esymm σ k (r + 1)) = 0 := by
  rw [constantCoeff_eq]
  exact (esymm_isHomogeneous σ (r + 1)).coeff_eq_zero (by simp)

theorem esymm_succ_mem_coinvIdeal (m r : ℕ) : esymm (Fin m) k (r + 1) ∈ coinvIdeal k m :=
  Ideal.subset_span ⟨esymm_isSymmetric _ _ _, constantCoeff_esymm_succ _ r⟩

/-- A polynomial without constant term, evaluated at elements of an ideal `J`, lies in `J`. -/
theorem aeval_mem_of_constantCoeff_eq_zero {n : ℕ} {R : Type*} [CommRing R] [Algebra k R]
    (J : Ideal R) (f : Fin n → R) (hf : ∀ i, f i ∈ J) {Q : MvPolynomial (Fin n) k}
    (hQ : constantCoeff Q = 0) : aeval f Q ∈ J := by
  classical
  rw [Q.as_sum, map_sum]
  refine J.sum_mem fun d hd => ?_
  have hd0 : d ≠ 0 := by
    rintro rfl
    rw [mem_support_iff, ← constantCoeff_eq, hQ] at hd
    exact hd rfl
  obtain ⟨i, hi⟩ : ∃ i, d i ≠ 0 := by
    obtain ⟨i, hi⟩ := Finsupp.ne_iff.1 hd0
    exact ⟨i, by simpa using hi⟩
  have hd' : d = (d - Finsupp.single i 1) + Finsupp.single i 1 := by
    rw [tsub_add_cancel_of_le]
    rw [Finsupp.single_le_iff]
    omega
  rw [hd', monomial_add_single, pow_one, map_mul, aeval_X]
  exact J.mul_mem_left _ (hf i)

theorem coinvIdeal_eq_span_esymm (m : ℕ) :
    coinvIdeal k m = Ideal.span (Set.range fun r : Fin m => esymm (Fin m) k (r + 1)) := by
  set J := Ideal.span (Set.range fun r : Fin m => esymm (Fin m) k (r + 1))
  refine le_antisymm (Ideal.span_le.2 ?_) (Ideal.span_le.2 ?_)
  · rintro s ⟨hs, hs0⟩
    obtain ⟨P, hP⟩ := (esymmAlgHom_fin_bijective k m).2 ⟨s, hs⟩
    have hsP : s = aeval (fun i : Fin m => esymm (Fin m) k (i + 1)) P := by
      rw [← esymmAlgHom_apply, hP]
    have hgen : ∀ i : Fin m, esymm (Fin m) k (i + 1) ∈ J := fun i =>
      Ideal.subset_span ⟨i, rfl⟩
    have hJ : ∀ j ∈ J, constantCoeff j = 0 := by
      intro j hj
      refine Submodule.span_induction (p := fun j _ => constantCoeff j = 0) ?_ ?_ ?_ ?_ hj
      · rintro _ ⟨i, rfl⟩; exact constantCoeff_esymm_succ _ _
      · simp
      · intro x y _ _ hx hy; rw [map_add, hx, hy, add_zero]
      · intro a x _ hx; rw [smul_eq_mul, map_mul, hx, mul_zero]
    set c := constantCoeff P
    have hsplit : s = C c + aeval (fun i : Fin m => esymm (Fin m) k (i + 1)) (P - C c) := by
      rw [map_sub, aeval_C, algebraMap_eq, ← hsP]; ring
    have hmem : aeval (fun i : Fin m => esymm (Fin m) k (i + 1)) (P - C c) ∈ J :=
      aeval_mem_of_constantCoeff_eq_zero J _ hgen (by simp [c])
    have hc : c = 0 := by
      have := congrArg constantCoeff hsplit
      rw [hs0, map_add, constantCoeff_C, hJ _ hmem, add_zero] at this
      exact this.symm
    convert hmem using 1
    rw [hsplit, hc, C_0, zero_add]
  · rintro _ ⟨r, rfl⟩
    exact esymm_succ_mem_coinvIdeal m r

/-! ### Homogeneity -/

attribute [local instance] MvPolynomial.gradedAlgebra in
/-- `coinvIdeal` is a homogeneous ideal. -/
theorem homogeneousComponent_mem_coinvIdeal {m : ℕ} (d : ℕ) {p : MvPolynomial (Fin m) k}
    (hp : p ∈ coinvIdeal k m) : homogeneousComponent d p ∈ coinvIdeal k m := by
  have hhom := Ideal.homogeneous_span (homogeneousSubmodule (Fin m) k)
    (Set.range fun r : Fin m => esymm (Fin m) k (r + 1)) (by
      rintro _ ⟨r, rfl⟩
      exact ⟨(r : ℕ) + 1, (mem_homogeneousSubmodule _ _).2 (esymm_isHomogeneous _ _)⟩)
  rw [coinvIdeal_eq_span_esymm] at hp ⊢
  have := hhom d hp
  rwa [← decomposition.decompose'_apply]

/-! ### The coinvariant algebra as an augmentation quotient -/

variable (k) in
/-- The augmentation (constant term) of the symmetric polynomials. -/
noncomputable def symAug (m : ℕ) : symmetricSubalgebra (Fin m) k →ₐ[k] k :=
  (MvPolynomial.aeval fun _ => (0 : k)).comp (symmetricSubalgebra (Fin m) k).val

theorem symAug_apply {m : ℕ} (s : symmetricSubalgebra (Fin m) k) :
    symAug k m s = constantCoeff (s : MvPolynomial (Fin m) k) := by
  simp [symAug, MvPolynomial.coe_aeval_eq_eval, MvPolynomial.eval_zero]

theorem coinvSub_eq_augSubmodule (m : ℕ) :
    coinvSub k m = augSubmodule (MvPolynomial (Fin m) k) (symAug k m) := by
  ext x
  rw [mem_coinvSub]
  constructor
  · intro hx
    induction hx using Submodule.span_induction with
    | mem s hs =>
      have : s = (⟨s, hs.1⟩ : symmetricSubalgebra (Fin m) k) • (1 : MvPolynomial (Fin m) k) := by
        rw [Subalgebra.smul_def, smul_eq_mul, mul_one]
      rw [this]
      exact smul_mem_augSubmodule (by rw [symAug_apply]; exact hs.2) _
    | zero => exact zero_mem _
    | add y z _ _ hy hz => exact add_mem hy hz
    | smul a y _ hy =>
      rw [smul_eq_mul]
      refine augSubmodule_induction (p := fun y => a * y ∈ _) hy ?_ ?_
      · intro z hz r
        have e1 : a * (z • r) = z • (a * r) := by
          show a * ((z : MvPolynomial (Fin m) k) * r) = (z : MvPolynomial (Fin m) k) * (a * r)
          ring
        rw [e1]
        exact smul_mem_augSubmodule hz _
      · intro y y' hy hy'
        rw [mul_add]
        exact add_mem hy hy'
  · intro hx
    refine augSubmodule_induction hx ?_ ?_
    · intro z hz r
      show (z : MvPolynomial (Fin m) k) * r ∈ coinvIdeal k m
      exact Ideal.mul_mem_right _ _
        (Ideal.subset_span ⟨z.2, by rw [← symAug_apply]; exact hz⟩)
    · intro y y' hy hy'
      exact add_mem hy hy'

/-- Staircase exponent vectors: `u a ≤ a`. -/
abbrev Staircase (m : ℕ) : Type := {u : Fin m → ℕ // ∀ a : Fin m, u a ≤ a}

variable (k) in
/-- **The staircase basis of `L_m`**: the classes of `∏_a x_a ^ u_a`, `u_a ≤ a`, form a basis of
`k[x_1, …, x_m] / (Sym⁺)` (Artin's theorem). -/
noncomputable def coinvBasis (m : ℕ) : Basis (Staircase m) k (Coinv k m) :=
  (augQuotBasis (symmetricBasis k m) (symAug k m)).map
    (Submodule.quotEquivOfEq _ _ (coinvSub_eq_augSubmodule m).symm)

@[simp] theorem coinvBasis_apply (m : ℕ) (u : Staircase m) :
    coinvBasis k m u = Submodule.Quotient.mk (∏ a, X a ^ u.1 a) := by
  simp [coinvBasis]

/-- **`dim_k L_m = m!`** (KL I §2.2). -/
theorem finrank_coinv (m : ℕ) : Module.finrank k (Coinv k m) = m.factorial := by
  rw [Module.finrank_eq_card_basis (coinvBasis k m), card_staircase]

instance (m : ℕ) : FiniteDimensional k (Coinv k m) := Module.Finite.of_basis (coinvBasis k m)

/-! ### Degrees -/

theorem staircase_sum_le (m : ℕ) (u : Staircase m) : ∑ a, u.1 a ≤ m.choose 2 := by
  calc ∑ a, u.1 a ≤ ∑ a : Fin m, (a : ℕ) := Finset.sum_le_sum fun a _ => u.2 a
    _ = m.choose 2 := by
      rw [Fin.sum_univ_eq_sum_range (fun i => i) m, Finset.sum_range_id, Nat.choose_two_right]

theorem isHomogeneous_stair (m : ℕ) (u : Fin m → ℕ) :
    (∏ a, X a ^ u a : MvPolynomial (Fin m) k).IsHomogeneous (∑ a, u a) :=
  IsHomogeneous.prod _ _ _ fun a _ => isHomogeneous_X_pow a (u a)

/-- **Degree bound**: every homogeneous polynomial of degree `> m(m-1)/2` lies in `coinvIdeal`
(`L_m` vanishes above degree `m(m-1)/2`). -/
theorem mem_coinvIdeal_of_isHomogeneous {m d : ℕ} {p : MvPolynomial (Fin m) k}
    (hp : p.IsHomogeneous d) (hd : m.choose 2 < d) : p ∈ coinvIdeal k m := by
  classical
  set b := coinvBasis k m
  set c := b.repr (Submodule.Quotient.mk p)
  have hmem : p - ∑ u, c u • (∏ a, X a ^ u.1 a) ∈ coinvSub k m := by
    rw [← Submodule.Quotient.eq]
    have : (Submodule.Quotient.mk (∑ u, c u • ∏ a, X a ^ u.1 a) : Coinv k m) =
        ∑ u, c u • b u := by
      rw [← Submodule.mkQ_apply, map_sum]
      simp only [map_smul, Submodule.mkQ_apply, coinvBasis_apply, b]
    rw [this]
    exact (b.sum_repr _).symm
  have h := homogeneousComponent_mem_coinvIdeal d hmem
  rw [map_sub, map_sum] at h
  simp only [map_smul] at h
  rw [homogeneousComponent_of_mem ((mem_homogeneousSubmodule _ _).2 hp), if_pos rfl] at h
  rwa [Finset.sum_eq_zero fun u _ => by
    rw [homogeneousComponent_of_mem ((mem_homogeneousSubmodule _ _).2 (isHomogeneous_stair m u.1)),
      if_neg (by have := staircase_sum_le m u; omega), smul_zero], sub_zero] at h

/-- **`x_a ^ m ∈ (Sym⁺)`**: each `x_a` is a root of `∏_b (t - x_b) = ∑_r (-1)^r e_r t^{m - r}`. -/
theorem X_pow_mem_coinvIdeal {m : ℕ} (a : Fin m) : (X a : MvPolynomial (Fin m) k) ^ m ∈ coinvIdeal k m := by
  set y : MvPolynomial (Fin m) k := X a
  have hv := congrArg (Polynomial.eval (-y)) (prod_C_add_X_eq_sum_esymm k (Fin m))
  simp only [Polynomial.eval_prod, Polynomial.eval_add, Polynomial.eval_X, Polynomial.eval_C,
    Polynomial.eval_finset_sum, Polynomial.eval_mul, Polynomial.eval_pow, Fintype.card_fin] at hv
  rw [Finset.prod_eq_zero (Finset.mem_univ a) (by simp [y]), Finset.sum_range_succ', esymm_zero,
    one_mul, Nat.sub_zero] at hv
  have hmem : (-y) ^ m ∈ coinvIdeal k m := by
    rw [eq_neg_of_add_eq_zero_right hv.symm]
    refine (coinvIdeal k m).neg_mem_iff.2 (Ideal.sum_mem _ fun j _ => ?_)
    exact Ideal.mul_mem_right _ _ (esymm_succ_mem_coinvIdeal m j)
  rw [neg_pow] at hmem
  have := Ideal.mul_mem_left _ ((-1) ^ m) hmem
  rwa [← mul_assoc, ← mul_pow, neg_one_mul, neg_neg, one_pow, one_mul] at this

/-- The inductive step: `e_r(x_0, …, x_{n-1}) ≡ (-x_n)^r` modulo `(Sym⁺)` in `n + 1` variables. -/
theorem rename_esymm_sub_mem (n r : ℕ) :
    rename Fin.castSucc (esymm (Fin n) k r) - (-X (Fin.last n)) ^ r ∈ coinvIdeal k (n + 1) := by
  induction r with
  | zero => simp
  | succ r ih =>
    have h := esymm_succ_castSucc (k := k) n r
    have : rename Fin.castSucc (esymm (Fin n) k (r + 1)) - (-X (Fin.last n)) ^ (r + 1) =
        esymm (Fin (n + 1)) k (r + 1) - X (Fin.last n) *
          (rename Fin.castSucc (esymm (Fin n) k r) - (-X (Fin.last n)) ^ r) := by
      rw [h]; ring
    rw [this]
    exact sub_mem (esymm_succ_mem_coinvIdeal _ r) (Ideal.mul_mem_left _ _ ih)

/-- If `s ∈ (Sym⁺)` in `n` variables, then `s(x_0, …, x_{n-1}) x_n^n ∈ (Sym⁺)` in `n + 1`
variables. -/
theorem rename_mul_pow_mem_coinvIdeal {n : ℕ} {s : MvPolynomial (Fin n) k}
    (hs : s ∈ coinvIdeal k n) :
    rename Fin.castSucc s * X (Fin.last n) ^ n ∈ coinvIdeal k (n + 1) := by
  rw [coinvIdeal_eq_span_esymm] at hs
  induction hs using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨r, rfl⟩ := hx
    have h1 := Ideal.mul_mem_right (X (Fin.last n) ^ n) _ (rename_esymm_sub_mem (k := k) n (r + 1))
    have h2 : (-X (Fin.last n) : MvPolynomial (Fin (n + 1)) k) ^ ((r : ℕ) + 1) *
        X (Fin.last n) ^ n ∈ coinvIdeal k (n + 1) := by
      have := Ideal.mul_mem_left (coinvIdeal k (n + 1))
        ((-1) ^ ((r : ℕ) + 1) * X (Fin.last n) ^ (r : ℕ)) (X_pow_mem_coinvIdeal (k := k) (Fin.last n))
      convert this using 1
      rw [neg_pow]; ring
    have := add_mem h1 h2
    rwa [sub_mul, sub_add_cancel] at this
  | zero => simp
  | add x y _ _ hx hy => rw [map_add, add_mul]; exact add_mem hx hy
  | smul a x _ hx => rw [smul_eq_mul, map_mul, mul_assoc]; exact Ideal.mul_mem_left _ _ hx

/-! ### Multiplication operators on `L_m` -/

variable (k) in
/-- Multiplication by a polynomial `p` on `L_m`. -/
noncomputable def coinvMul {m : ℕ} (p : MvPolynomial (Fin m) k) : Module.End k (Coinv k m) :=
  (coinvSub k m).mapQ (coinvSub k m) (LinearMap.mulLeft k p)
    fun _ hq => Ideal.mul_mem_left _ p hq

@[simp] theorem coinvMul_mk {m : ℕ} (p q : MvPolynomial (Fin m) k) :
    coinvMul k p (Submodule.Quotient.mk q) = Submodule.Quotient.mk (p * q) := rfl

theorem coinvMul_mul {m : ℕ} (p q : MvPolynomial (Fin m) k) :
    coinvMul k (p * q) = coinvMul k p * coinvMul k q := by
  ext x
  simp [mul_assoc]

theorem coinvMul_pow {m : ℕ} (p : MvPolynomial (Fin m) k) (j : ℕ) :
    coinvMul k (p ^ j) = coinvMul k p ^ j := by
  induction j with
  | zero =>
    ext x
    simp
  | succ j ih => rw [pow_succ, coinvMul_mul, ih, pow_succ]

theorem coinvMul_eq_zero {m : ℕ} {p : MvPolynomial (Fin m) k} (hp : p ∈ coinvIdeal k m) :
    coinvMul k p = 0 := by
  ext x
  simp only [LinearMap.coe_comp, Function.comp_apply, Submodule.mkQ_apply, coinvMul_mk,
    LinearMap.zero_comp, LinearMap.zero_apply, Submodule.Quotient.mk_eq_zero]
  exact Ideal.mul_mem_right _ _ hp

/-! ### From `n` to `n + 1` variables -/

variable (k) in
/-- The map `ι : L_n → L_{n+1}`, `[g] ↦ [g(x_0, …, x_{n-1}) · x_n^n]` (well defined by
`rename_mul_pow_mem_coinvIdeal`). -/
noncomputable def coinvInc (n : ℕ) : Coinv k n →ₗ[k] Coinv k (n + 1) :=
  (coinvSub k n).liftQ ((coinvSub k (n + 1)).mkQ ∘ₗ LinearMap.mulRight k (X (Fin.last n) ^ n) ∘ₗ
      (rename Fin.castSucc : MvPolynomial (Fin n) k →ₐ[k] MvPolynomial (Fin (n + 1)) k).toLinearMap)
    (fun g hg => by
      rw [LinearMap.mem_ker]
      exact (Submodule.Quotient.mk_eq_zero _).2 (rename_mul_pow_mem_coinvIdeal hg))

@[simp] theorem coinvInc_mk (n : ℕ) (g : MvPolynomial (Fin n) k) :
    coinvInc k n (Submodule.Quotient.mk g) =
      Submodule.Quotient.mk (rename Fin.castSucc g * X (Fin.last n) ^ n) := rfl

theorem coinvBasis_snoc (n : ℕ) (v : Staircase n) (j : Fin (n + 1)) :
    coinvBasis k (n + 1) (staircaseSnoc v j) = Submodule.Quotient.mk
      (rename Fin.castSucc (∏ a, X a ^ v.1 a) * X (Fin.last n) ^ (j : ℕ)) := by
  rw [coinvBasis_apply]
  congr 1
  exact stairMonomial_snoc v j

theorem coinvInc_basis (n : ℕ) (v : Staircase n) :
    coinvInc k n (coinvBasis k n v) = coinvBasis k (n + 1) (staircaseSnoc v (Fin.last n)) := by
  rw [coinvBasis_apply, coinvInc_mk, coinvBasis_snoc, Fin.val_last]

theorem coinvMul_last_pow_basis (n : ℕ) (v : Staircase n) (j : Fin (n + 1)) (i : ℕ)
    (h : (j : ℕ) + i ≤ n) :
    coinvMul k (X (Fin.last n) ^ i) (coinvBasis k (n + 1) (staircaseSnoc v j)) =
      coinvBasis k (n + 1) (staircaseSnoc v ⟨j + i, by omega⟩) := by
  rw [coinvBasis_snoc, coinvBasis_snoc, coinvMul_mk]
  congr 1
  simp only [pow_add]
  ring

theorem coinvMul_castSucc_coinvInc (n : ℕ) (a : Fin n) (w : Coinv k n) :
    coinvMul k (X a.castSucc) (coinvInc k n w) = coinvInc k n (coinvMul k (X a) w) := by
  obtain ⟨g, rfl⟩ := Submodule.Quotient.mk_surjective _ w
  rw [coinvInc_mk, coinvMul_mk, coinvMul_mk, coinvInc_mk, map_mul, rename_X, mul_assoc]

theorem staircaseSnoc_injective (n : ℕ) :
    Function.Injective fun p : Staircase n × Fin (n + 1) => staircaseSnoc p.1 p.2 := by
  intro p q h
  have := congrArg (staircaseSplit n) h
  simpa using this

section Jordan

variable (n : ℕ)

/-- `x_n^{n+1} = 0` on `L_{n+1}`. -/
theorem coinvMul_last_pow_eq_zero : coinvMul k (X (Fin.last n)) ^ (n + 1) = 0 := by
  rw [← coinvMul_pow]
  exact coinvMul_eq_zero (X_pow_mem_coinvIdeal (Fin.last n))

/-- The image of `x_n^n` contains the classes `[x^v x_n^n]`. -/
theorem span_le_range_pow :
    Submodule.span k (Set.range fun v : Staircase n => coinvBasis k (n + 1) (staircaseSnoc v (Fin.last n)))
      ≤ LinearMap.range (coinvMul k (X (Fin.last n)) ^ n) := by
  rw [Submodule.span_le]
  rintro _ ⟨v, rfl⟩
  refine ⟨coinvBasis k (n + 1) (staircaseSnoc v 0), ?_⟩
  rw [← coinvMul_pow, coinvMul_last_pow_basis n v 0 n (by simp)]
  congr 2
  ext
  simp

theorem span_le_range :
    Submodule.span k (Set.range fun p : Staircase n × Fin n =>
      coinvBasis k (n + 1) (staircaseSnoc p.1 p.2.succ))
      ≤ LinearMap.range (coinvMul k (X (Fin.last n))) := by
  rw [Submodule.span_le]
  rintro _ ⟨⟨v, j⟩, rfl⟩
  refine ⟨coinvBasis k (n + 1) (staircaseSnoc v j.castSucc), ?_⟩
  have := coinvMul_last_pow_basis (k := k) n v j.castSucc 1 (by simp; omega)
  rw [pow_one] at this
  rw [this]
  congr 2

theorem linearIndependent_snoc_last :
    LinearIndependent k fun v : Staircase n => coinvBasis k (n + 1) (staircaseSnoc v (Fin.last n)) :=
  (coinvBasis k (n + 1)).linearIndependent.comp _ fun v w h =>
    congrArg Prod.fst (staircaseSnoc_injective n (a₁ := (v, Fin.last n)) (a₂ := (w, Fin.last n)) h)

theorem linearIndependent_snoc_succ :
    LinearIndependent k fun p : Staircase n × Fin n =>
      coinvBasis k (n + 1) (staircaseSnoc p.1 p.2.succ) :=
  (coinvBasis k (n + 1)).linearIndependent.comp _ fun p q h => by
    have := staircaseSnoc_injective n (a₁ := (p.1, p.2.succ)) (a₂ := (q.1, q.2.succ)) h
    simp only [Prod.mk.injEq, Fin.succ_inj] at this
    exact Prod.ext this.1 this.2

/-- The key dimension count behind the Jordan form of `x_n` on `L_{n+1}`. -/
theorem ker_eq_range_pow_and_finrank :
    LinearMap.ker (coinvMul k (X (Fin.last n))) = LinearMap.range (coinvMul k (X (Fin.last n)) ^ n) ∧
      LinearMap.range (coinvMul k (X (Fin.last n)) ^ n) =
        Submodule.span k (Set.range fun v : Staircase n =>
          coinvBasis k (n + 1) (staircaseSnoc v (Fin.last n))) ∧
      Module.finrank k (LinearMap.ker (coinvMul k (X (Fin.last n)))) = n.factorial := by
  set T := coinvMul k (X (Fin.last n))
  set S2 := Submodule.span k (Set.range fun v : Staircase n =>
    coinvBasis k (n + 1) (staircaseSnoc v (Fin.last n)))
  have h2 : Module.finrank k S2 = n.factorial := by
    rw [finrank_span_eq_card (linearIndependent_snoc_last n), card_staircase]
  have h1 : Module.finrank k (Submodule.span k (Set.range fun p : Staircase n × Fin n =>
      coinvBasis k (n + 1) (staircaseSnoc p.1 p.2.succ))) = n.factorial * n := by
    rw [finrank_span_eq_card (linearIndependent_snoc_succ n), Fintype.card_prod, card_staircase,
      Fintype.card_fin]
  have hrank := LinearMap.finrank_range_add_finrank_ker T
  rw [finrank_coinv] at hrank
  have hr1 : n.factorial * n ≤ Module.finrank k (LinearMap.range T) :=
    h1 ▸ Submodule.finrank_mono (span_le_range n)
  have hker : Module.finrank k (LinearMap.ker T) ≤ n.factorial := by
    have : (n + 1).factorial = n.factorial * n + n.factorial := by
      rw [Nat.factorial_succ]; ring
    omega
  have hle : LinearMap.range (T ^ n) ≤ LinearMap.ker T := by
    rintro _ ⟨x, rfl⟩
    rw [LinearMap.mem_ker, ← Module.End.mul_apply, ← pow_succ', coinvMul_last_pow_eq_zero]
    rfl
  have hr2 : n.factorial ≤ Module.finrank k (LinearMap.range (T ^ n)) :=
    h2 ▸ Submodule.finrank_mono (span_le_range_pow n)
  have hr2' := Submodule.finrank_mono hle
  have e1 : LinearMap.range (T ^ n) = LinearMap.ker T :=
    Submodule.eq_of_le_of_finrank_eq hle (by omega)
  have e2 : S2 = LinearMap.range (T ^ n) :=
    Submodule.eq_of_le_of_finrank_eq (span_le_range_pow n) (by omega)
  exact ⟨e1.symm, e2.symm, by omega⟩

/-- **KL I, Lemma 2.1 (Jordan blocks)**: on `L_{n+1}`, the kernel of `x_n` (the last variable)
equals the image of `x_n^n`. Together with `x_n^{n+1} = 0` (`coinvMul_last_pow_eq_zero`) this says
that all Jordan blocks of the nilpotent operator `x_n` have size exactly `n + 1`. -/
theorem ker_coinvMul_last :
    LinearMap.ker (coinvMul k (X (Fin.last n))) =
      LinearMap.range (coinvMul k (X (Fin.last n)) ^ n) :=
  (ker_eq_range_pow_and_finrank n).1

/-- The number of Jordan blocks of `x_n` on `L_{n+1}` is `n! = dim L_{n+1} / (n + 1)`. -/
theorem finrank_ker_coinvMul_last :
    Module.finrank k (LinearMap.ker (coinvMul k (X (Fin.last n)))) = n.factorial :=
  (ker_eq_range_pow_and_finrank n).2.2

theorem range_coinvInc : LinearMap.range (coinvInc k n) = LinearMap.ker (coinvMul k (X (Fin.last n))) := by
  rw [(ker_eq_range_pow_and_finrank n).1, (ker_eq_range_pow_and_finrank n).2.1,
    LinearMap.range_eq_map, ← (coinvBasis k n).span_eq, Submodule.map_span, ← Set.range_comp]
  congr 1
  ext x
  simp only [Set.mem_range, Function.comp_apply, coinvInc_basis]

theorem coinvInc_injective : Function.Injective (coinvInc k n) := by
  have h := LinearMap.finrank_range_add_finrank_ker (coinvInc k n)
  rw [range_coinvInc, finrank_ker_coinvMul_last, finrank_coinv] at h
  have : LinearMap.ker (coinvInc k n) = ⊥ :=
    Submodule.finrank_eq_zero.1 (by omega)
  exact LinearMap.ker_eq_bot.1 this

end Jordan

/-! ### The socle: the common kernel of `x_1, …, x_m` -/

/-- The staircase vector `u_a = a`, giving the top-degree monomial `∏_a x_a^a`. -/
def topStair (m : ℕ) : Staircase m := ⟨fun a => a, fun _ => le_rfl⟩

variable (k) in
/-- The class of `∏_a x_a^a` in `L_m`, of top degree `m(m-1)/2`. -/
noncomputable def coinvTop (m : ℕ) : Coinv k m := coinvBasis k m (topStair m)

theorem coinvTop_ne_zero (m : ℕ) : coinvTop k m ≠ 0 := (coinvBasis k m).ne_zero _

theorem staircaseSnoc_topStair (n : ℕ) : staircaseSnoc (topStair n) (Fin.last n) = topStair (n + 1) := by
  apply Subtype.ext
  funext a
  refine Fin.lastCases ?_ (fun b => ?_) a
  · simp [staircaseSnoc, topStair]
  · simp [staircaseSnoc, topStair]

theorem coinvInc_top (n : ℕ) : coinvInc k n (coinvTop k n) = coinvTop k (n + 1) := by
  rw [coinvTop, coinvInc_basis, staircaseSnoc_topStair]
  rfl

theorem coinvMul_X_top {m : ℕ} (a : Fin m) : coinvMul k (X a) (coinvTop k m) = 0 := by
  rw [coinvTop, coinvBasis_apply, coinvMul_mk, Submodule.Quotient.mk_eq_zero]
  refine mem_coinvIdeal_of_isHomogeneous (d := 1 + ∑ b : Fin m, (b : ℕ))
    ((isHomogeneous_X k a).mul (isHomogeneous_stair m _)) ?_
  have := staircase_sum_le m (topStair m)
  have h : ∑ b : Fin m, (topStair m).1 b = m.choose 2 := by
    simp only [topStair]
    rw [Fin.sum_univ_eq_sum_range (fun i => i) m, Finset.sum_range_id, Nat.choose_two_right]
  simp only [topStair] at h
  omega

variable (k) in
/-- The common kernel of the operators `x_1, …, x_m` on `L_m`. -/
noncomputable def coinvSocle (m : ℕ) : Submodule k (Coinv k m) :=
  ⨅ a : Fin m, LinearMap.ker (coinvMul k (X a))

theorem mem_coinvSocle {m : ℕ} {v : Coinv k m} :
    v ∈ coinvSocle k m ↔ ∀ a, coinvMul k (X a) v = 0 := by
  simp [coinvSocle, Submodule.mem_iInf]

/-- **KL I, Lemma 2.1 (socle)**: the common `0`-eigenspace of `x_1, …, x_m` on `L_m` is the line
spanned by the class of the top-degree monomial `∏_a x_a^a`. -/
theorem coinvSocle_eq (m : ℕ) : coinvSocle k m = k ∙ coinvTop k m := by
  refine le_antisymm ?_ ?_
  · induction m with
    | zero =>
      intro v _
      have h1 : Module.finrank k (k ∙ coinvTop k 0) = Module.finrank k (Coinv k 0) := by
        rw [finrank_span_singleton (coinvTop_ne_zero 0), finrank_coinv, Nat.factorial_zero]
      rw [Submodule.eq_top_of_finrank_eq h1]
      trivial
    | succ n ih =>
      intro v hv
      rw [mem_coinvSocle] at hv
      have hker : v ∈ LinearMap.range (coinvInc k n) := by
        rw [range_coinvInc, LinearMap.mem_ker]
        exact hv (Fin.last n)
      obtain ⟨w, rfl⟩ := hker
      have hw : w ∈ coinvSocle k n := by
        rw [mem_coinvSocle]
        intro a
        apply coinvInc_injective n
        rw [← coinvMul_castSucc_coinvInc, hv, map_zero]
      obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.1 (ih hw)
      rw [map_smul, coinvInc_top]
      exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)
  · rw [Submodule.span_le]
    rintro _ rfl
    exact mem_coinvSocle.2 fun a => coinvMul_X_top a

theorem finrank_coinvSocle (m : ℕ) : Module.finrank k (coinvSocle k m) = 1 := by
  rw [coinvSocle_eq, finrank_span_singleton (coinvTop_ne_zero m)]

end Categorification
