/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.DividedDifference
import Categorification.TypeA.Matsumoto

/-!
# The nilHecke ring

M. Khovanov, A. Lauda, *A diagrammatic approach to categorification of quantum groups I*,
arXiv:0803.4121v2, §2.2, Example 3.

The nilHecke ring `NH_m` is the subring of `End(k[x_1, …, x_m])` generated by the operators
of multiplication by `x_1, …, x_m` and the divided difference operators
`∂_a f = (f - s_a f) / (x_a - x_{a+1})`, `1 ≤ a ≤ m - 1`. KL I works over `k = ℤ` (so
`End` means endomorphisms of the abelian group); we allow any commutative ring `k` and take
`k`-linear endomorphisms.

Positions are zero-indexed: the paper's `x_a` is `mulX ⟨a - 1, _⟩` and the paper's `∂_a`
is `dd (a - 1)`. As for the crossings of the KLR algebra, `dd j` is defined for every
`j : ℕ` and is zero when `j + 1 ≥ m`.

## Main definitions

* `NilHecke.mulX a`, `NilHecke.mulPoly p` : multiplication by `x_a`, by a polynomial `p`;
* `NilHecke.dd j` : the divided difference `∂_j`;
* `NilHecke.nilHecke k m` : the nilHecke ring `NH_m`, as a `k`-subalgebra of
  `Module.End k (MvPolynomial (Fin m) k)`;
* `NilHecke.ddw ρ` : `∂_ρ = ∂_{ρ₀} ∂_{ρ₁} ⋯` for a word `ρ`, and `NilHecke.ddPerm w` : `∂_w`.

## Main results

* The defining relations of `NH_m` listed in KL I §2.2, Example 3: `mulX_mul_mulX`,
  `dd_mul_mulX`, `dd_mul_dd`, `dd_mul_self`, `dd_braid`, `mulX_dd_sub_dd_mulX`,
  `dd_mulX_sub_mulX_dd`.
* `ddw_eq_of_isReduced` : `∂_w` does not depend on the choice of a reduced word for `w`
  (KL I §2.2, Example 3), via Matsumoto's theorem `TypeA.braidEquiv_of_isReduced`.

The isomorphism `R(m i) ≅ NH_m` and the basis `{∂_w x^u}` of `NH_m` are in
`Categorification.KLR.Examples.NilHecke`.
-/

namespace Categorification.NilHecke

open MvPolynomial Equiv TypeA

variable (k : Type*) [CommRing k] (m : ℕ)

/-- Multiplication by a polynomial, as an algebra map `k[x_1, …, x_m] → End(k[x_1, …, x_m])`. -/
noncomputable def mulPoly : MvPolynomial (Fin m) k →ₐ[k] Module.End k (MvPolynomial (Fin m) k) :=
  Algebra.lmul k _

/-- Multiplication by the variable `x_a` (zero-indexed). -/
noncomputable def mulX (a : Fin m) : Module.End k (MvPolynomial (Fin m) k) :=
  mulPoly k m (X a)

/-- The divided difference operator `∂_j = ∂_{x_j, x_{j+1}}` (zero-indexed); zero if
`j + 1 ≥ m`. -/
noncomputable def dd (j : ℕ) : Module.End k (MvPolynomial (Fin m) k) :=
  if h : j + 1 < m then ddiff ⟨j, by omega⟩ ⟨j + 1, h⟩ else 0

/-- **The nilHecke ring** `NH_m` (KL I §2.2, Example 3): the subalgebra of
`End_k(k[x_1, …, x_m])` generated by the multiplications by `x_a` and the divided differences
`∂_j`. -/
noncomputable def nilHecke : Subalgebra k (Module.End k (MvPolynomial (Fin m) k)) :=
  Algebra.adjoin k (Set.range (mulX k m) ∪ Set.range (dd k m))

variable {k m}

@[simp] theorem mulPoly_apply (p f : MvPolynomial (Fin m) k) : mulPoly k m p f = p * f := rfl

@[simp] theorem mulX_apply (a : Fin m) (f : MvPolynomial (Fin m) k) : mulX k m a f = X a * f :=
  rfl

theorem mulPoly_X (a : Fin m) : mulPoly k m (X a) = mulX k m a := rfl

theorem dd_of_lt {j : ℕ} (h : j + 1 < m) :
    dd k m j = ddiff ⟨j, by omega⟩ ⟨j + 1, h⟩ := dif_pos h

theorem dd_eq_zero {j : ℕ} (h : m ≤ j + 1) : dd k m j = 0 := dif_neg (by omega)

/-! ### Membership in `NH_m` -/

theorem mulX_mem (a : Fin m) : mulX k m a ∈ nilHecke k m :=
  Algebra.subset_adjoin (Or.inl ⟨a, rfl⟩)

theorem dd_mem (j : ℕ) : dd k m j ∈ nilHecke k m :=
  Algebra.subset_adjoin (Or.inr ⟨j, rfl⟩)

theorem mulPoly_mem (p : MvPolynomial (Fin m) k) : mulPoly k m p ∈ nilHecke k m := by
  induction p using MvPolynomial.induction_on with
  | C a => rw [algHom_C]; exact Subalgebra.algebraMap_mem _ a
  | add p q hp hq => rw [map_add]; exact add_mem hp hq
  | mul_X p a hp => rw [map_mul]; exact mul_mem hp (mulX_mem a)

/-! ### The defining relations (KL I §2.2, Example 3) -/

private theorem ne_of_val {a b : Fin m} (h : a.val ≠ b.val) : a ≠ b := fun e => h (e ▸ rfl)

/-- `x_a x_b = x_b x_a`. -/
theorem mulX_mul_mulX (a b : Fin m) : mulX k m a * mulX k m b = mulX k m b * mulX k m a := by
  rw [← mulPoly_X, ← mulPoly_X, ← map_mul, ← map_mul, mul_comm]

/-- `∂_j x_a = x_a ∂_j` unless `a ∈ {j, j + 1}` (the paper states it for `|a - b| > 1` in its
one-indexed notation, which is a special case). -/
theorem dd_mul_mulX (j : ℕ) (a : Fin m) (h₁ : a.val ≠ j) (h₂ : a.val ≠ j + 1) :
    dd k m j * mulX k m a = mulX k m a * dd k m j := by
  by_cases h : j + 1 < m
  · rw [dd_of_lt h]
    refine LinearMap.ext fun f => ?_
    simp only [Module.End.mul_apply, mulX_apply]
    refine ddiff_mul_of_rename_eq (ne_of_val (by simp)) ?_ f
    rw [rename_X, swap_apply_of_ne_of_ne (ne_of_val h₁) (ne_of_val h₂)]
  · rw [dd_eq_zero (by omega), zero_mul, mul_zero]

/-- `∂_j ∂_l = ∂_l ∂_j` for `j + 1 < l`. -/
theorem dd_mul_dd {j l : ℕ} (hjl : j + 1 < l) : dd k m j * dd k m l = dd k m l * dd k m j := by
  by_cases h : l + 1 < m
  · rw [dd_of_lt h, dd_of_lt (show j + 1 < m by omega)]
    refine LinearMap.ext fun f => ?_
    simp only [Module.End.mul_apply]
    exact ddiff_ddiff_comm (ne_of_val (by simp)) (ne_of_val (by simp))
      (ne_of_val (by simp only; omega)) (ne_of_val (by simp only; omega))
      (ne_of_val (by simp only; omega)) (ne_of_val (by simp only; omega)) f
  · rw [dd_eq_zero (show m ≤ l + 1 by omega), zero_mul, mul_zero]

/-- `∂_j² = 0`. -/
theorem dd_mul_self (j : ℕ) : dd k m j * dd k m j = 0 := by
  by_cases h : j + 1 < m
  · rw [dd_of_lt h]
    refine LinearMap.ext fun f => ?_
    simp only [Module.End.mul_apply, LinearMap.zero_apply]
    exact ddiff_ddiff (by simp [Fin.ext_iff]) f
  · rw [dd_eq_zero (by omega), zero_mul]

/-- The nilHecke braid relation `∂_j ∂_{j+1} ∂_j = ∂_{j+1} ∂_j ∂_{j+1}`. -/
theorem dd_braid (j : ℕ) :
    dd k m j * dd k m (j + 1) * dd k m j = dd k m (j + 1) * dd k m j * dd k m (j + 1) := by
  by_cases h : j + 2 < m
  · rw [dd_of_lt (show j + 1 < m by omega), dd_of_lt (show j + 1 + 1 < m by omega)]
    refine LinearMap.ext fun f => ?_
    simp only [Module.End.mul_apply]
    exact ddiff_braid (ne_of_val (by simp)) (ne_of_val (by simp))
      (ne_of_val (by simp only; omega)) f
  · rw [dd_eq_zero (show m ≤ j + 1 + 1 by omega), mul_zero, zero_mul, zero_mul]

/-- `x_j ∂_j - ∂_j x_{j+1} = 1`. -/
theorem mulX_dd_sub_dd_mulX {j : ℕ} (h : j + 1 < m) :
    mulX k m ⟨j, by omega⟩ * dd k m j - dd k m j * mulX k m ⟨j + 1, h⟩ = 1 := by
  rw [dd_of_lt h]
  have hne : (⟨j, by omega⟩ : Fin m) ≠ ⟨j + 1, h⟩ := by simp [Fin.ext_iff]
  refine LinearMap.ext fun f => ?_
  simp only [LinearMap.sub_apply, Module.End.mul_apply, mulX_apply, Module.End.one_apply]
  rw [ddiff_mul hne, ddiff_X_right hne, rename_X, swap_apply_right]
  ring

/-- `∂_j x_j - x_{j+1} ∂_j = 1`. -/
theorem dd_mulX_sub_mulX_dd {j : ℕ} (h : j + 1 < m) :
    dd k m j * mulX k m ⟨j, by omega⟩ - mulX k m ⟨j + 1, h⟩ * dd k m j = 1 := by
  rw [dd_of_lt h]
  have hne : (⟨j, by omega⟩ : Fin m) ≠ ⟨j + 1, h⟩ := by simp [Fin.ext_iff]
  refine LinearMap.ext fun f => ?_
  simp only [LinearMap.sub_apply, Module.End.mul_apply, mulX_apply, Module.End.one_apply]
  rw [ddiff_mul hne, ddiff_X_left hne, rename_X, swap_apply_left]
  ring

/-! ### `∂_w` -/

/-- `∂_ρ = ∂_{ρ₀} ∂_{ρ₁} ⋯` for a word `ρ`. -/
noncomputable def ddw (ρ : List ℕ) : Module.End k (MvPolynomial (Fin m) k) :=
  (ρ.map (dd k m)).prod

@[simp] theorem ddw_nil : ddw (k := k) (m := m) [] = 1 := rfl

@[simp] theorem ddw_cons (j : ℕ) (ρ : List ℕ) :
    ddw (k := k) (m := m) (j :: ρ) = dd k m j * ddw ρ := by simp [ddw]

@[simp] theorem ddw_append (ρ σ : List ℕ) :
    ddw (k := k) (m := m) (ρ ++ σ) = ddw ρ * ddw σ := by simp [ddw]

theorem ddw_mem (ρ : List ℕ) : ddw (k := k) (m := m) ρ ∈ nilHecke k m := by
  induction ρ with
  | nil => exact one_mem _
  | cons j ρ ih => rw [ddw_cons]; exact mul_mem (dd_mem j) ih

/-- `∂_ρ` is invariant under braid moves. -/
theorem ddw_eq_of_braidEquiv {ρ σ : List ℕ} (h : BraidEquiv ρ σ) :
    ddw (k := k) (m := m) ρ = ddw σ := by
  refine h.eq_of_step (f := ddw) fun ρ σ hs => ?_
  cases hs with
  | comm α β h =>
    simp only [ddw_append, ddw_cons, ddw_nil, mul_one]
    rw [dd_mul_dd h]
  | braid α β a =>
    have e := congrArg (fun z => ddw α * z * ddw β) (dd_braid (k := k) (m := m) a)
    simp only [ddw_append, ddw_cons, ddw_nil, mul_one, mul_assoc] at e ⊢
    exact e

/-- **KL I §2.2, Example 3**: `∂_w = ∂_{a_1} ⋯ ∂_{a_r}` does not depend on the choice of the
reduced word `s_{a_1} ⋯ s_{a_r}` of `w`. -/
theorem ddw_eq_of_isReduced {ρ σ : List ℕ} (hρ : IsReduced m ρ) (hσ : IsReduced m σ)
    (h : wordProd m ρ = wordProd m σ) : ddw (k := k) (m := m) ρ = ddw σ :=
  ddw_eq_of_braidEquiv (braidEquiv_of_isReduced hρ hσ h)

variable (k m) in
/-- `∂_w` for a permutation `w ∈ S_m`, computed along the canonical reduced word
`TypeA.canWord`; by `ddw_eq_ddPerm` any reduced word gives the same operator. -/
noncomputable def ddPerm (w : Perm (Fin m)) : Module.End k (MvPolynomial (Fin m) k) :=
  ddw (canWord m w)

theorem ddw_eq_ddPerm {ρ : List ℕ} (hρ : IsReduced m ρ) :
    ddw (k := k) (m := m) ρ = ddPerm k m (wordProd m ρ) :=
  ddw_eq_of_isReduced hρ (isReduced_canWord m _) (wordProd_canWord m _).symm

theorem ddPerm_mem (w : Perm (Fin m)) : ddPerm k m w ∈ nilHecke k m := ddw_mem _

/-! ### Transport along an equality of ranks -/

/-- `NH_n ≅ NH_{n'}` for `n = n'`. -/
noncomputable def congrRank {n n' : ℕ} (h : n = n') : nilHecke k n ≃ₐ[k] nilHecke k n' := by
  subst h; exact AlgEquiv.refl

theorem congrRank_mulX {n n' : ℕ} (h : n = n') (a : Fin n) :
    congrRank h ⟨mulX k n a, mulX_mem a⟩ = ⟨mulX k n' (Fin.cast h a), mulX_mem _⟩ := by
  subst h; rfl

theorem congrRank_dd {n n' : ℕ} (h : n = n') (j : ℕ) :
    congrRank (k := k) h ⟨dd k n j, dd_mem j⟩ = ⟨dd k n' j, dd_mem j⟩ := by
  subst h; rfl

end Categorification.NilHecke
