/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.Coinvariant
import Categorification.Algebra.NilHeckeIdempotent

/-!
# The irreducible representation `L_m` of the nilHecke ring

Khovanov–Lauda I (arXiv:0803.4121v2), §2.2 (TeX lines 733–760): the quotient `L_m` of
`k[x_1, …, x_m]` by the ideal generated by the symmetric polynomials without constant term is a
representation of the nilHecke ring `NH_m`, irreducible over a field `k`, and

> **Lemma 2.1.** The common `0`-eigenspace of the operators `x_1, …, x_m` on
> `L(i^m) ≅ Ind(L)` is exactly `1 ⊗ L`. All Jordan blocks of `x_m` on `L(i^m)` are of size `m`.

Here we work with `NH_m = nilHecke k m ⊆ End_k(k[x])` over a field `k`, and `L_m = Coinv k m`
(`Categorification.Algebra.Coinvariant`).

## Main results

* `NilHecke.nhAct` and the `Module (nilHecke k m) (Coinv k m)` instance: `NH_m` acts on `L_m`
  (every element of `NH_m` preserves the ideal `(Sym⁺)`, `nilHecke_stable`).
* `NilHecke.isSimpleModule_coinv` : **`L_m` is an irreducible `NH_m`-module.**
* `Categorification.finrank_coinv` : `dim L_m = m!`.
* `NilHecke.coinvSocle_eq_span_xDelta` : **Lemma 2.1, first part**: the common `0`-eigenspace of
  `x_1, …, x_m` on `L_m` is the line spanned by the class of `x^δ = x_1^{m-1} x_2^{m-2} ⋯ x_{m-1}`;
  this is the image of `1 ⊗ L` under `Ind(L) ≅ L_m`, since `1 ⊗ L` is killed by all `x_a` and
  `∂_{w_0} x^δ = 1` (`nhAct_ddw_w0Word_xDelta`). (Also `Categorification.coinvSocle_eq`: the same
  line is spanned by `∏_a x_a^{a-1}`.)
* `Categorification.coinvMul_last_pow_eq_zero`, `Categorification.ker_coinvMul_last` : **Lemma 2.1,
  second part**: `x_m^m = 0` and `ker x_m = im x_m^{m-1}` on `L_m`, i.e. all Jordan blocks of `x_m`
  have size exactly `m`; there are `(m-1)!` of them (`finrank_ker_coinvMul_last`).
-/

namespace Categorification.NilHecke

open MvPolynomial Equiv TypeA

variable {k : Type*} [Field k] {m : ℕ}

/-! ### `NH_m` preserves `(Sym⁺)` -/

theorem ddiff_mem_coinvIdeal {a b : Fin m} (hab : a ≠ b) {p : MvPolynomial (Fin m) k}
    (hp : p ∈ coinvIdeal k m) : ddiff a b p ∈ coinvIdeal k m := by
  induction hp using Submodule.span_induction with
  | mem s hs =>
    rw [ddiff_eq_zero_of_rename_eq hab (hs.1 (swap a b))]
    exact zero_mem _
  | zero => rw [map_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
  | smul c y hy ih =>
    rw [smul_eq_mul, ddiff_mul hab]
    exact add_mem (Ideal.mul_mem_left _ _ hy) (Ideal.mul_mem_left _ _ ih)

theorem dd_mem_coinvIdeal (j : ℕ) {p : MvPolynomial (Fin m) k} (hp : p ∈ coinvIdeal k m) :
    dd k m j p ∈ coinvIdeal k m := by
  by_cases h : j + 1 < m
  · rw [dd_of_lt h]
    exact ddiff_mem_coinvIdeal (fun e => by simp [Fin.ext_iff] at e) hp
  · rw [dd_eq_zero (by omega), LinearMap.zero_apply]
    exact zero_mem _

/-- Every element of `NH_m` preserves the ideal generated by `Sym⁺`. -/
theorem nilHecke_stable {T : Module.End k (MvPolynomial (Fin m) k)} (hT : T ∈ nilHecke k m)
    {p : MvPolynomial (Fin m) k} (hp : p ∈ coinvIdeal k m) : T p ∈ coinvIdeal k m := by
  induction hT using Algebra.adjoin_induction generalizing p with
  | mem y hy =>
    rcases hy with ⟨a, rfl⟩ | ⟨j, rfl⟩
    · exact Ideal.mul_mem_left _ _ hp
    · exact dd_mem_coinvIdeal j hp
  | algebraMap r =>
    rw [Module.algebraMap_end_apply]
    exact Submodule.smul_of_tower_mem _ r hp
  | add x y _ _ hx hy => rw [LinearMap.add_apply]; exact add_mem (hx hp) (hy hp)
  | mul x y _ _ hx hy => rw [Module.End.mul_apply]; exact hx (hy hp)

/-! ### The action of `NH_m` on `L_m` -/

variable (k m) in
/-- The action of `NH_m` on `L_m = k[x] / (Sym⁺)`. -/
noncomputable def nhAct : nilHecke k m →ₐ[k] Module.End k (Coinv k m) where
  toFun T := (coinvSub k m).mapQ (coinvSub k m) (T : Module.End k (MvPolynomial (Fin m) k))
    fun _ hp => nilHecke_stable T.2 hp
  map_one' := by ext; simp
  map_mul' T T' := by ext; simp
  map_zero' := by ext; simp
  map_add' T T' := by ext; simp
  commutes' c := by ext; simp [Module.algebraMap_end_apply]

@[simp] theorem nhAct_mk (T : nilHecke k m) (p : MvPolynomial (Fin m) k) :
    nhAct k m T (Submodule.Quotient.mk p) =
      Submodule.Quotient.mk ((T : Module.End k (MvPolynomial (Fin m) k)) p) := rfl

theorem nhAct_mulX (a : Fin m) : nhAct k m ⟨mulX k m a, mulX_mem a⟩ = coinvMul k (X a) := by
  ext; rfl

theorem nhAct_mulPoly (p : MvPolynomial (Fin m) k) :
    nhAct k m ⟨mulPoly k m p, mulPoly_mem p⟩ = coinvMul k p := by
  ext; rfl

variable (k m) in
/-- `L_m` regarded as a module over `NH_m` (a type synonym for `Coinv k m`). -/
def NHRep : Type _ := Coinv k m

noncomputable instance : AddCommGroup (NHRep k m) := inferInstanceAs (AddCommGroup (Coinv k m))
noncomputable instance : Module k (NHRep k m) := inferInstanceAs (Module k (Coinv k m))
instance : FiniteDimensional k (NHRep k m) := inferInstanceAs (FiniteDimensional k (Coinv k m))

variable (k m) in
/-- The identification `L_m = NHRep k m`. -/
def NHRep.of : Coinv k m ≃ₗ[k] NHRep k m := LinearEquiv.refl k _

/-- `L_m` as a module over `NH_m`. -/
noncomputable instance : Module (nilHecke k m) (NHRep k m) :=
  Module.compHom (Coinv k m) (nhAct k m).toRingHom

theorem nilHecke_smul_def (T : nilHecke k m) (v : Coinv k m) :
    T • NHRep.of k m v = NHRep.of k m (nhAct k m T v) := rfl

instance : IsScalarTower k (nilHecke k m) (NHRep k m) where
  smul_assoc c T v := by
    show nhAct k m (c • T) v = c • nhAct k m T v
    rw [show nhAct k m (c • T) = c • nhAct k m T from (nhAct k m).toLinearMap.map_smul c T,
      LinearMap.smul_apply]

/-! ### Words in commuting nilpotent operators -/

/-- If all products of more than `D` of the operators `T i` vanish, every nonzero `T`-stable subset
contains a nonzero common null vector. -/
theorem exists_ne_zero_forall_eq_zero {R V ι : Type*} [Semiring R] [AddCommMonoid V] [Module R V]
    (T : ι → Module.End R V) (D : ℕ) (hD : ∀ ρ : List ι, D < ρ.length → (ρ.map T).prod = 0)
    (P : Set V) (hP : ∀ i, ∀ v ∈ P, T i v ∈ P) {v₀ : V} (hv₀ : v₀ ∈ P) (hne : v₀ ≠ 0) :
    ∃ v ∈ P, v ≠ 0 ∧ ∀ i, T i v = 0 := by
  classical
  have hQ : ∃ n, ∀ ρ : List ι, ρ.length = n + 1 → (ρ.map T).prod v₀ = 0 :=
    ⟨D, fun ρ hρ => by rw [hD ρ (by omega), LinearMap.zero_apply]⟩
  have hPρ : ∀ ρ : List ι, (ρ.map T).prod v₀ ∈ P := by
    intro ρ
    induction ρ with
    | nil => simpa using hv₀
    | cons i ρ ih => rw [List.map_cons, List.prod_cons, Module.End.mul_apply]; exact hP i _ ih
  obtain ⟨ρ, hρlen, hρ⟩ : ∃ ρ : List ι, ρ.length = Nat.find hQ ∧ (ρ.map T).prod v₀ ≠ 0 := by
    rcases h : Nat.find hQ with _ | n
    · exact ⟨[], rfl, by simpa using hne⟩
    · have := Nat.find_min hQ (show n < Nat.find hQ by omega)
      push_neg at this
      obtain ⟨ρ, hρ, hne'⟩ := this
      exact ⟨ρ, hρ, hne'⟩
  refine ⟨_, hPρ ρ, hρ, fun i => ?_⟩
  have := Nat.find_spec hQ (i :: ρ) (by simp [hρlen])
  rwa [List.map_cons, List.prod_cons, Module.End.mul_apply] at this

theorem coinvMul_one : coinvMul k (1 : MvPolynomial (Fin m) k) = 1 := by
  ext; simp

theorem prod_map_coinvMul (ρ : List (Fin m)) :
    (ρ.map fun a => coinvMul k (X a : MvPolynomial (Fin m) k)).prod =
      coinvMul k (ρ.map fun a => (X a : MvPolynomial (Fin m) k)).prod := by
  induction ρ with
  | nil => simp [coinvMul_one]
  | cons a ρ ih => simp [ih, coinvMul_mul]

theorem isHomogeneous_prod_map_X (ρ : List (Fin m)) :
    ((ρ.map fun a => (X a : MvPolynomial (Fin m) k)).prod).IsHomogeneous ρ.length := by
  induction ρ with
  | nil => simpa using isHomogeneous_one (Fin m) k
  | cons a ρ ih =>
    rw [List.map_cons, List.prod_cons, List.length_cons, add_comm]
    exact (isHomogeneous_X k a).mul ih

/-- Products of more than `m(m-1)/2` of the operators `x_a` vanish on `L_m`. -/
theorem prod_map_coinvMul_eq_zero {ρ : List (Fin m)} (hρ : m.choose 2 < ρ.length) :
    (ρ.map fun a => coinvMul k (X a : MvPolynomial (Fin m) k)).prod = 0 := by
  rw [prod_map_coinvMul]
  exact coinvMul_eq_zero (mem_coinvIdeal_of_isHomogeneous (isHomogeneous_prod_map_X ρ) hρ)

/-! ### `x^δ` and `∂_{w_0}` -/

theorem sum_sub_one_sub (m : ℕ) : ∑ a : Fin m, (m - 1 - (a : ℕ)) = m.choose 2 := by
  rw [Fin.sum_univ_eq_sum_range (fun i => m - 1 - i) m]
  have : ∑ i ∈ Finset.range m, (m - 1 - i) = ∑ i ∈ Finset.range m, i := by
    rw [← Finset.sum_range_reflect]
    refine Finset.sum_congr rfl fun i hi => ?_
    have := Finset.mem_range.1 hi
    omega
  rw [this, Finset.sum_range_id, Nat.choose_two_right]

theorem isHomogeneous_xDelta_self : (xDelta (k := k) (m := m) m).IsHomogeneous (m.choose 2) := by
  rw [← sum_sub_one_sub m]
  exact IsHomogeneous.prod _ _ _ fun a _ => isHomogeneous_X_pow a _

theorem coinvMul_X_xDelta (a : Fin m) :
    coinvMul k (X a) (Submodule.Quotient.mk (xDelta (k := k) (m := m) m)) = 0 := by
  rw [coinvMul_mk, Submodule.Quotient.mk_eq_zero]
  exact mem_coinvIdeal_of_isHomogeneous ((isHomogeneous_X k a).mul isHomogeneous_xDelta_self)
    (by omega)

/-- `∂_{w_0} [x^δ] = [1]` in `L_m`. -/
theorem nhAct_ddw_w0Word_xDelta :
    nhAct k m ⟨ddw (w0Word m), ddw_mem _⟩ (Submodule.Quotient.mk (xDelta m)) =
      Submodule.Quotient.mk 1 := by
  rw [nhAct_mk]
  exact congrArg _ ddw_w0Word_xDelta

theorem one_not_mem_coinvIdeal : (1 : MvPolynomial (Fin m) k) ∉ coinvIdeal k m := by
  intro h
  have hJ : ∀ j ∈ coinvIdeal k m, constantCoeff j = 0 := by
    intro j hj
    induction hj using Submodule.span_induction with
    | mem s hs => exact hs.2
    | zero => simp
    | add x y _ _ hx hy => rw [map_add, hx, hy, add_zero]
    | smul a x _ hx => rw [smul_eq_mul, map_mul, hx, mul_zero]
  simpa using hJ 1 h

theorem mk_one_ne_zero : (Submodule.Quotient.mk 1 : Coinv k m) ≠ 0 := by
  rw [Ne, Submodule.Quotient.mk_eq_zero]
  exact one_not_mem_coinvIdeal

theorem mk_xDelta_ne_zero : (Submodule.Quotient.mk (xDelta m) : Coinv k m) ≠ 0 := by
  intro h
  apply mk_one_ne_zero (k := k) (m := m)
  rw [← nhAct_ddw_w0Word_xDelta, h, map_zero]

/-- **KL I, Lemma 2.1 (first part)**: the common `0`-eigenspace of `x_1, …, x_m` on `L_m` is the
line spanned by the class of `x^δ = x_1^{m-1} x_2^{m-2} ⋯ x_{m-1}` (the image of `1 ⊗ L` under
`Ind(L) ≅ L_m`). -/
theorem coinvSocle_eq_span_xDelta :
    coinvSocle k m = k ∙ (Submodule.Quotient.mk (xDelta m) : Coinv k m) := by
  symm
  apply Submodule.eq_of_le_of_finrank_eq
  · rw [Submodule.span_le]
    rintro _ rfl
    exact mem_coinvSocle.2 coinvMul_X_xDelta
  · rw [finrank_coinvSocle, finrank_span_singleton mk_xDelta_ne_zero]

/-! ### Irreducibility -/

instance : Nontrivial (Coinv k m) :=
  Module.nontrivial_of_finrank_pos (R := k) (by rw [finrank_coinv]; exact Nat.factorial_pos m)

/-- **`L_m` is an irreducible `NH_m`-module** (KL I §2.2): any nonzero submodule contains a
nonzero common null vector of the `x_a`, which is a multiple of `[x^δ]`, and
`∂_{w_0} [x^δ] = [1]` generates `L_m`. -/
theorem isSimpleModule_coinv : IsSimpleModule (nilHecke k m) (NHRep k m) := by
  haveI : Nontrivial (NHRep k m) := inferInstanceAs (Nontrivial (Coinv k m))
  refine { eq_bot_or_eq_top := fun N => ?_ }
  by_cases hN : N = ⊥
  · exact Or.inl hN
  right
  obtain ⟨v₀, hv₀, hne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hN
  obtain ⟨v, hv, hv0, hvx⟩ := exists_ne_zero_forall_eq_zero
    (fun a : Fin m => coinvMul k (X a : MvPolynomial (Fin m) k)) (m.choose 2)
    (fun ρ hρ => prod_map_coinvMul_eq_zero hρ) {w : Coinv k m | NHRep.of k m w ∈ N}
    (fun a w hw => by
      show NHRep.of k m (coinvMul k (X a) w) ∈ N
      rw [← nhAct_mulX, ← nilHecke_smul_def]
      exact N.smul_mem _ hw) hv₀ hne
  have hsoc : v ∈ coinvSocle k m := mem_coinvSocle.2 hvx
  rw [coinvSocle_eq_span_xDelta] at hsoc
  obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.1 hsoc
  have hc : c ≠ 0 := by rintro rfl; exact hv0 (zero_smul _ _)
  have hδ : NHRep.of k m (Submodule.Quotient.mk (xDelta m)) ∈ N := by
    have := Submodule.smul_of_tower_mem N c⁻¹ (show NHRep.of k m (c • _) ∈ N from hv)
    rwa [← map_smul, smul_smul, inv_mul_cancel₀ hc, one_smul] at this
  have h1 : NHRep.of k m (Submodule.Quotient.mk 1) ∈ N := by
    have := N.smul_mem ⟨ddw (w0Word m), ddw_mem _⟩ hδ
    rwa [nilHecke_smul_def, nhAct_ddw_w0Word_xDelta] at this
  rw [eq_top_iff]
  intro w _
  obtain ⟨p, rfl⟩ := Submodule.Quotient.mk_surjective _ ((NHRep.of k m).symm w)
  have := N.smul_mem ⟨mulPoly k m p, mulPoly_mem p⟩ h1
  rwa [nilHecke_smul_def, nhAct_mulPoly, coinvMul_mk, mul_one] at this

end Categorification.NilHecke
