/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.NilHeckeParabolic

/-!
# Kato's theorem for the nilHecke algebra

Khovanov–Lauda I (arXiv:0803.4121v2), §3.2, **Proposition 3.11** (TeX lines 2168–2181), the
nilHecke analogue of Kato's theorem (Kleshchev, *Linear and projective representations of
symmetric groups*, §4.3, whose Lemma 4.3.1 is replaced by KL I Lemma 2.1). Let `μ` be a
composition of `n` and let `NH_μ ⊆ NH_n` be the parabolic nilHecke subalgebra
(`NilHecke.ParNH k n μ`, `Categorification.Algebra.NilHeckeParabolic`).

> (1) `L(i^n)` is the only graded irreducible `NH_n`-module up to isomorphism and shift.
> (2) All composition factors of `Res^n_μ L(i^n)` are isomorphic to
> `L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})` up to shift, and `soc(Res^n_μ L(i^n))` is irreducible.
> (3) `soc(Res^n_{n-1} L(i^n)) ≅ L(i^{n-1})` up to a grading shift.

We work over a field `k`, with `L_n = NHRep k n = k[x] / (Sym⁺)` and with the `NH_μ`-module
`L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})` realised as the Young coinvariant algebra
`L_μ = YoungRep k n μ = k[x] / (Sym_μ⁺)`.

## Main results

* `NilHecke.youngSocleEquiv` : **`soc(Res^n_μ L_n) ≅ L_μ`** as `NH_μ`-modules, via
  `[p] ↦ [p g_μ]` with `g_μ = ∏_a x_a^{n - e(a)}` (`e(a)` the end of the block of `a`), a
  homogeneous polynomial of degree `∑_a (n - e(a))`: this is the grading shift.
  Together with `NilHecke.sSup_simple_eq_nhSocle` (the socle, i.e. the sum of all simple
  submodules, is the simple module generated by `[x^δ]`) this is the socle part of (2).
* `NilHecke.isSimpleModule_youngRep` : `L_μ` is a simple `NH_μ`-module.
* `NilHecke.nonempty_linearEquiv_youngRep` : **every simple `NH_μ`-module on which the `x_a`
  act nilpotently is isomorphic to `L_μ`** (for `μ = (n)` this is the ungraded content of (1)).
* `NilHecke.nonempty_linearEquiv_youngRep_subquotient` : **(2), composition factors**: every
  simple subquotient of `Res^n_μ L_n` is isomorphic to `L_μ`.
* `NilHecke.resNH_socle`, `NilHecke.resSocleEquiv` : **(3)**: the socle of `Res^n_{n-1} L_n`
  (restriction to the
  subalgebra `NH_{n-1}` generated by `x_0, …, x_{n-2}`, `∂_0, …, ∂_{n-3}`) is irreducible, and
  it is isomorphic, as an `NH_{n-1}`-module, to `L_{(n-1,1)} = k[x]/(Sym_{n-1}⁺, x_{n-1})`,
  i.e. to `L(i^{n-1}) ⊗ L(i)` restricted to `NH_{n-1}`.

## Proof

Every nonzero submodule contains a nonzero common null vector of the `x_a`, which is a multiple
of `[x^δ]` by KL I Lemma 2.1, so the submodule `S` generated by `[x^δ]` is the unique simple
submodule. For the identification, `∂_{w_0^μ}(x^δ) = g_μ` (`ddw_parWord_xDelta`, computed block
by block from `∂_{w_0}(x^δ) = 1`), so `[g_μ] ∈ S`; the invariants `s ∈ Sym_μ⁺` act on the simple
module `S` by `NH_μ`-endomorphisms killing `[x^δ]`, hence by zero (Schur), so
`[p] ↦ [p g_μ]` is a well-defined `NH_μ`-map `L_μ → S`, onto as `S` is simple. It is injective
since it maps the `|S_μ| = dim L_μ` block-staircase monomials to distinct (reversed) staircase
monomials, which are linearly independent in `L_n` by Artin's theorem.
-/

namespace Categorification.NilHecke

open MvPolynomial Equiv TypeA

variable {k : Type*} [Field k] {n : ℕ}

/-! ### Monomials -/

/-- The monomial `x^e = ∏_a x_a^{e a}`. -/
noncomputable def monoX (e : Fin n → ℕ) : MvPolynomial (Fin n) k := ∏ a, X a ^ e a

theorem monoX_mul (e f : Fin n → ℕ) :
    (monoX e * monoX f : MvPolynomial (Fin n) k) = monoX (fun a => e a + f a) := by
  simp only [monoX, ← Finset.prod_mul_distrib, pow_add]

theorem monoX_congr {e f : Fin n → ℕ} (h : ∀ a, e a = f a) :
    (monoX e : MvPolynomial (Fin n) k) = monoX f := by
  rw [funext h]

theorem monoX_eq_one {e : Fin n → ℕ} (h : ∀ a, e a = 0) :
    (monoX e : MvPolynomial (Fin n) k) = 1 := by
  simp [monoX, h]

theorem monoX_single {c : ℕ} (hc : c < n) :
    (monoX (fun a : Fin n => if (a : ℕ) = c then 1 else 0) : MvPolynomial (Fin n) k) =
      X ⟨c, hc⟩ := by
  rw [monoX, Finset.prod_eq_single (⟨c, hc⟩ : Fin n)
    (fun b _ hb => by rw [if_neg (fun h => hb (Fin.ext h)), pow_zero]) (by simp)]
  simp

theorem rename_swap_monoX {j : ℕ} (h : j + 1 < n) {e : Fin n → ℕ}
    (he : e ⟨j, by omega⟩ = e ⟨j + 1, h⟩) :
    rename (swap (⟨j, by omega⟩ : Fin n) ⟨j + 1, h⟩) (monoX e : MvPolynomial (Fin n) k) =
      monoX e := by
  apply rename_swap_prod_pow
  intro c
  rcases eq_or_ne c ⟨j, by omega⟩ with rfl | h1
  · rw [swap_apply_left]; exact he.symm
  rcases eq_or_ne c ⟨j + 1, h⟩ with rfl | h2
  · rw [swap_apply_right]; exact he
  rw [swap_apply_of_ne_of_ne h1 h2]

theorem xDelta_eq_monoX : xDelta (k := k) (m := n) n = monoX (fun a => n - 1 - a) := rfl

/-! ### `∂_{w_0}` on a block -/

/-- The reduced word `w0Word m` of the longest element of `S_m`, shifted to the block
`[p, p + m)`. -/
def parW0 (p m : ℕ) : List ℕ := (w0Word m).map (p + ·)

theorem mem_parW0 {p m j : ℕ} (h : j ∈ parW0 p m) : p ≤ j ∧ j + 1 < p + m := by
  obtain ⟨j', hj', rfl⟩ := List.mem_map.1 h
  have := lt_of_mem_w0Word hj'
  omega

theorem parW0_succ (p m : ℕ) : parW0 p (m + 1) = (List.range m).map (p + ·) ++ parW0 p m := by
  simp [parW0, w0Word_succ]

/-- `x_p x_{p+1} ⋯ x_{p+m-1}`. -/
noncomputable def parPre (p m : ℕ) : MvPolynomial (Fin n) k :=
  monoX (fun a => if p ≤ (a : ℕ) ∧ (a : ℕ) < p + m then 1 else 0)

/-- `x_p^{m-1} x_{p+1}^{m-2} ⋯ x_{p+m-2}`, the `x^δ` of the block `[p, p + m)`. -/
noncomputable def parDeltaOff (p m : ℕ) : MvPolynomial (Fin n) k :=
  monoX (fun a => if p ≤ (a : ℕ) then p + m - 1 - a else 0)

theorem parPre_succ {p m : ℕ} (h : p + m < n) :
    (parPre p (m + 1) : MvPolynomial (Fin n) k) = parPre p m * X ⟨p + m, h⟩ := by
  rw [parPre, parPre, ← monoX_single h, monoX_mul]
  exact monoX_congr fun a => by split_ifs <;> omega

theorem rename_swap_parPre {p m j : ℕ} (h : j + 1 < n) (hj : (p ≤ j ∧ j + 1 < p + m) ∨ p + m ≤ j) :
    rename (swap (⟨j, by omega⟩ : Fin n) ⟨j + 1, h⟩) (parPre p m : MvPolynomial (Fin n) k) =
      parPre p m :=
  rename_swap_monoX h (by (try simp only [Fin.val_mk]); split_ifs <;> omega)

theorem ddw_range_parPre {p m : ℕ} (h : p + m < n) :
    ddw (k := k) (m := n) ((List.range m).map (p + ·)) (parPre p m) = 1 := by
  induction m with
  | zero => exact monoX_eq_one fun a => by split_ifs <;> omega
  | succ m ih =>
    have hne : (⟨p + m, by omega⟩ : Fin n) ≠ ⟨p + m + 1, by omega⟩ := by simp [Fin.ext_iff]
    rw [List.range_succ, List.map_append, ddw_append, List.map_singleton, ddw_cons, ddw_nil,
      mul_one, Module.End.mul_apply, parPre_succ (by omega), dd_of_lt (show p + m + 1 < n by omega),
      ddiff_mul_of_rename_eq hne (rename_swap_parPre _ (Or.inr le_rfl)), ddiff_X_left hne, mul_one,
      ih (by omega)]

theorem parDeltaOff_succ (p m : ℕ) :
    (parDeltaOff p (m + 1) : MvPolynomial (Fin n) k) = parPre p m * parDeltaOff p m := by
  rw [parDeltaOff, parPre, parDeltaOff, monoX_mul]
  exact monoX_congr fun a => by split_ifs <;> omega

/-- `∂_{w_0}` of the block `[p, p + m)` maps its `x^δ` to `1`. -/
theorem ddw_parW0_parDeltaOff {p m : ℕ} (h : p + m ≤ n) :
    ddw (k := k) (m := n) (parW0 p m) (parDeltaOff p m) = 1 := by
  induction m with
  | zero => exact monoX_eq_one fun a => by split_ifs <;> omega
  | succ m ih =>
    rw [parW0_succ, ddw_append, Module.End.mul_apply, parDeltaOff_succ,
      ddw_mul_of_forall (fun j hj h' => rename_swap_parPre h' (Or.inl (mem_parW0 hj))),
      ih (by omega), mul_one, ddw_range_parPre (by omega)]

/-! ### `∂_{w_0^μ}` for a composition -/

/-- The concatenation of the words `parW0` of the blocks of `μ` (starting at position `p`): a
reduced word of the longest element of the Young subgroup. -/
def parWord : ℕ → List ℕ → List ℕ
  | _, [] => []
  | p, m :: μ => parW0 p m ++ parWord (p + m) μ

theorem mem_parWord {p : ℕ} {μ : List ℕ} {j : ℕ} (h : j ∈ parWord p μ) :
    p ≤ j ∧ j + 1 < p + μ.sum ∧ blockEnd p μ (j + 1) = blockEnd p μ j := by
  induction μ generalizing p with
  | nil => simp [parWord] at h
  | cons m μ ih =>
    rw [parWord, List.mem_append] at h
    rcases h with h | h
    · obtain ⟨h1, h2⟩ := mem_parW0 h
      refine ⟨h1, by simp only [List.sum_cons]; omega, ?_⟩
      simp only [blockEnd]
      split_ifs <;> omega
    · obtain ⟨h1, h2, h3⟩ := ih h
      refine ⟨by omega, by simp only [List.sum_cons]; omega, ?_⟩
      simp only [blockEnd]
      rw [if_neg (by omega), if_neg (by omega)]
      exact h3

/-- The product of the `x^δ`'s of the blocks of `μ` (starting at position `p`). -/
noncomputable def parDelta (p : ℕ) (μ : List ℕ) : MvPolynomial (Fin n) k :=
  monoX (fun a => if p ≤ (a : ℕ) then blockEnd p μ a - 1 - a else 0)

theorem parDelta_nil (p : ℕ) : (parDelta p [] : MvPolynomial (Fin n) k) = 1 :=
  monoX_eq_one fun a => by simp only [blockEnd]; split_ifs <;> omega

theorem parDelta_cons (p m : ℕ) (μ : List ℕ) :
    (parDelta p (m :: μ) : MvPolynomial (Fin n) k) = parDeltaOff p m * parDelta (p + m) μ := by
  rw [parDelta, parDeltaOff, parDelta, monoX_mul]
  exact monoX_congr fun a => by simp only [blockEnd]; split_ifs <;> omega

theorem ddw_parWord_parDelta {p : ℕ} {μ : List ℕ} (h : p + μ.sum ≤ n) :
    ddw (k := k) (m := n) (parWord p μ) (parDelta p μ) = 1 := by
  induction μ generalizing p with
  | nil => rw [parWord, parDelta_nil, ddw_nil, Module.End.one_apply]
  | cons m μ ih =>
    simp only [List.sum_cons] at h
    rw [parWord, ddw_append, Module.End.mul_apply, parDelta_cons,
      ddw_mul_of_forall (g := parDeltaOff p m) (fun j hj h' => rename_swap_monoX
        (e := fun a : Fin n => if p ≤ (a : ℕ) then p + m - 1 - a else 0) h' (by
        have := (mem_parWord hj).1
        (try simp only [Fin.val_mk]); split_ifs <;> omega)),
      ih (by omega), mul_one, ddw_parW0_parDeltaOff (by omega)]

/-! ### The polynomial `g_μ` -/

variable (k) in
/-- `g_μ = ∏_a x_a^{n - e(a)}`, `e(a)` the end of the block of `a`; `x^δ = x^{δ_μ} g_μ`. -/
noncomputable def parG (μ : List ℕ) : MvPolynomial (Fin n) k :=
  monoX (fun a => n - blockEnd 0 μ a)

theorem parDelta_mul_parG {μ : List ℕ} (hn : μ.sum = n) :
    (parDelta 0 μ * parG k μ : MvPolynomial (Fin n) k) = xDelta n := by
  rw [parDelta, parG, monoX_mul, xDelta_eq_monoX]
  refine monoX_congr fun a => ?_
  have h1 := lt_blockEnd 0 μ a
  have h2 := blockEnd_le (p := 0) (μ := μ) (a := a) (by omega)
  simp only [zero_le, if_true]
  omega

theorem parG_mem_labelInvariants (μ : List ℕ) :
    parG k μ ∈ labelInvariants k (compLab (n := n) μ) := by
  intro σ hσ
  rw [parG, monoX, map_prod]
  simp only [map_pow, rename_X]
  refine Fintype.prod_equiv σ _ _ fun a => ?_
  have := congrFun hσ a
  simp only [Function.comp_apply, compLab] at this
  rw [this]

theorem parWord_mem_compD {μ : List ℕ} {j : ℕ} (hj : j ∈ parWord 0 μ) : j ∈ compD μ :=
  (mem_parWord hj).2.2

/-- `∂_{w_0^μ}(x^δ) = g_μ`. -/
theorem ddw_parWord_xDelta {μ : List ℕ} (hn : μ.sum = n) :
    ddw (k := k) (m := n) (parWord 0 μ) (xDelta n) = parG k μ := by
  rw [← parDelta_mul_parG hn, mul_comm,
    ddw_mul_of_forall (fun j hj h => rename_swap_of_mem_labelInvariants
      (parG_mem_labelInvariants μ) (parWord_mem_compD hj) h),
    ddw_parWord_parDelta (by omega), mul_one]

/-! ### Invariants of the Young subgroup are central in `NH_μ` -/

theorem mulPoly_commute_of_mem_labelInvariants {S : Set (Fin n)} {μ : List ℕ}
    {s : MvPolynomial (Fin n) k} (hs : s ∈ labelInvariants k (compLab (n := n) μ))
    {U : Module.End k (MvPolynomial (Fin n) k)} (hU : U ∈ nhSub k n S (compD μ)) :
    mulPoly k n s * U = U * mulPoly k n s := by
  have : nhSub k n S (compD μ) ≤ Subalgebra.centralizer k {mulPoly k n s} := by
    refine Algebra.adjoin_le ?_
    rintro _ (⟨a, -, rfl⟩ | ⟨j, hj, rfl⟩) <;>
      rw [SetLike.mem_coe, Subalgebra.mem_centralizer_iff] <;>
      rintro _ rfl
    · rw [← mulPoly_X, ← map_mul, ← map_mul, mul_comm]
    · refine LinearMap.ext fun f => ?_
      simp only [Module.End.mul_apply, mulPoly_apply]
      exact (dd_mul_of_mem_labelInvariants hs hj f).symm
  exact (Subalgebra.mem_centralizer_iff k).1 (this hU) _ rfl

/-- Elements of `NH_μ` are `Sym_μ`-linear; in particular `U (p g_μ) = U(p) g_μ`. -/
theorem nhSub_apply_mul_parG {S : Set (Fin n)} {μ : List ℕ}
    {U : Module.End k (MvPolynomial (Fin n) k)} (hU : U ∈ nhSub k n S (compD μ))
    (p : MvPolynomial (Fin n) k) : U (p * parG k μ) = U p * parG k μ := by
  have := congrArg (fun T => T p) (mulPoly_commute_of_mem_labelInvariants
    (parG_mem_labelInvariants (k := k) μ) hU)
  simp only [Module.End.mul_apply, mulPoly_apply] at this
  rw [mul_comm, ← this, mul_comm]

theorem NHSub.val_injective {S : Set (Fin n)} {D : Set ℕ} :
    Function.Injective (NHSub.val k n S D) := Subtype.val_injective

variable (k) in
/-- Multiplication by a polynomial, as an element of `NH_μ`. -/
noncomputable def parPoly (μ : List ℕ) : MvPolynomial (Fin n) k →ₐ[k] ParNH k n μ :=
  (mulPoly k n).codRestrict (nhSub k n Set.univ (compD μ)) mulPoly_mem_nhSub

@[simp] theorem val_parPoly {μ : List ℕ} (p : MvPolynomial (Fin n) k) :
    NHSub.val k n _ _ (parPoly k μ p) = mulPoly k n p := rfl

theorem parPoly_commute {μ : List ℕ} {s : MvPolynomial (Fin n) k}
    (hs : s ∈ labelInvariants k (compLab (n := n) μ)) (T : ParNH k n μ) :
    parPoly k μ s * T = T * parPoly k μ s :=
  NHSub.val_injective (by
    rw [map_mul, map_mul, val_parPoly]
    exact mulPoly_commute_of_mem_labelInvariants hs T.2)

/-! ### The socle of `Res^n_μ L_n` -/

/-- A polynomial without constant term kills `[x^δ]` in `L_n`. -/
theorem mul_xDelta_mem_coinvIdeal {s : MvPolynomial (Fin n) k} (hs0 : constantCoeff s = 0) :
    s * xDelta n ∈ coinvIdeal k n := by
  have hmem : s ∈ Ideal.span (X '' (Set.univ : Set (Fin n))) := by
    refine mem_ideal_span_X_image.2 fun m hm => ?_
    by_contra hcon
    push_neg at hcon
    have : m = 0 := Finsupp.ext fun i => hcon i trivial
    subst this
    rw [mem_support_iff, ← constantCoeff_eq] at hm
    exact hm hs0
  clear hs0
  induction hmem using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨a, -, rfl⟩ := hx
    have := coinvMul_X_xDelta (k := k) a
    rwa [coinvMul_mk, Submodule.Quotient.mk_eq_zero, mem_coinvSub] at this
  | zero => rw [zero_mul]; exact zero_mem _
  | add x y _ _ hx hy => rw [add_mul]; exact add_mem hx hy
  | smul r x _ hx => rw [smul_eq_mul, mul_assoc]; exact Ideal.mul_mem_left _ _ hx

/-- **Schur's lemma**: the invariants `s ∈ Sym_μ⁺` act by zero on the simple module
`soc(Res^n_μ L_n)`. -/
theorem parPoly_smul_eq_zero_of_mem_nhSocle {μ : List ℕ} {s : MvPolynomial (Fin n) k}
    (hs : s ∈ labelInvariants k (compLab (n := n) μ)) (hs0 : constantCoeff s = 0)
    {v : NHRep k n} (hv : v ∈ nhSocle k n Set.univ (compD μ)) : parPoly k μ s • v = 0 := by
  haveI := isSimpleModule_nhSocle (k := k) (n := n) (D := compD μ) univ_hS
  let f : nhSocle k n Set.univ (compD μ) →ₗ[ParNH k n μ] nhSocle k n Set.univ (compD μ) :=
    { toFun := fun w => ⟨parPoly k μ s • (w : NHRep k n), Submodule.smul_mem _ _ w.2⟩
      map_add' := fun w w' => Subtype.ext (smul_add _ _ _)
      map_smul' := fun T w => Subtype.ext (by
        simp only [SetLike.val_smul, RingHom.id_apply]
        rw [← mul_smul, ← mul_smul, parPoly_commute hs T]) }
  rcases LinearMap.bijective_or_eq_zero f with hf | hf
  · exfalso
    have h0 : f ⟨_, xDelta_mem_nhSocle⟩ = f 0 := by
      rw [map_zero]
      apply Subtype.ext
      show parPoly k μ s • NHRep.of k n (Submodule.Quotient.mk (xDelta n)) = 0
      rw [nhSub_smul_def, nhSubAct_mk, val_parPoly, mulPoly_apply]
      show (Submodule.Quotient.mk (s * xDelta n) : Coinv k n) = 0
      rw [Submodule.Quotient.mk_eq_zero, mem_coinvSub]
      exact mul_xDelta_mem_coinvIdeal hs0
    have := congrArg Subtype.val (hf.1 h0)
    exact mk_xDelta_ne_zero this
  · have := congrArg (fun g => ((g ⟨v, hv⟩ : nhSocle k n Set.univ (compD μ)) : NHRep k n)) hf
    exact this

/-- `[g_μ] = ∂_{w_0^μ} [x^δ]` lies in the socle. -/
theorem mk_parG_mem_nhSocle {μ : List ℕ} (hn : μ.sum = n) :
    NHRep.of k n (Submodule.Quotient.mk (parG k μ)) ∈ nhSocle k n Set.univ (compD μ) := by
  have := (nhSocle k n Set.univ (compD μ)).smul_mem
    (NHSub.mk (ddw_mem_nhSub (k := k) (S := Set.univ) fun j hj => parWord_mem_compD hj))
    xDelta_mem_nhSocle
  rwa [nhSub_smul_def, nhSubAct_mk, NHSub.val_mk, ddw_parWord_xDelta hn] at this

theorem mk_parG_ne_zero {μ : List ℕ} (hn : μ.sum = n) :
    (Submodule.Quotient.mk (parG k μ) : Coinv k n) ≠ 0 := by
  intro h
  apply mk_xDelta_ne_zero (k := k) (m := n)
  rw [← parDelta_mul_parG hn, Submodule.Quotient.mk_eq_zero, mem_coinvSub]
  rw [Submodule.Quotient.mk_eq_zero, mem_coinvSub] at h
  exact Ideal.mul_mem_left _ _ h

theorem mul_parG_mem_coinvSub {μ : List ℕ} (hn : μ.sum = n) {s : MvPolynomial (Fin n) k}
    (hs : s ∈ labelInvariants k (compLab (n := n) μ)) (hs0 : constantCoeff s = 0)
    (p : MvPolynomial (Fin n) k) : s * p * parG k μ ∈ coinvSub k n := by
  have := parPoly_smul_eq_zero_of_mem_nhSocle hs hs0 (mk_parG_mem_nhSocle (k := k) hn)
  rw [nhSub_smul_def, nhSubAct_mk, val_parPoly, mulPoly_apply] at this
  have h : s * parG k μ ∈ coinvIdeal k n := by
    rw [← mem_coinvSub, ← Submodule.Quotient.mk_eq_zero]; exact this
  rw [mem_coinvSub, mul_comm s, mul_assoc]
  exact Ideal.mul_mem_left _ _ h

/-! ### The map `L_μ → soc(Res^n_μ L_n)`, `[p] ↦ [p g_μ]` -/

variable (k) in
/-- The `k`-linear map `L_μ → L_n`, `[p] ↦ [p g_μ]`. -/
noncomputable def youngToCoinv {μ : List ℕ} (hn : μ.sum = n) : YoungCoinv k n μ →ₗ[k] Coinv k n :=
  (youngSub k n μ).liftQ ((coinvSub k n).mkQ ∘ₗ LinearMap.mulRight k (parG k μ)) (by
    intro p hp
    refine augSubmodule_induction (p := fun p => p ∈ LinearMap.ker _) hp ?_ ?_
    · intro r hr m
      rw [LinearMap.mem_ker, LinearMap.comp_apply, Submodule.mkQ_apply,
        Submodule.Quotient.mk_eq_zero]
      exact mul_parG_mem_coinvSub hn r.2 (by rw [← youngAug_apply]; exact hr) m
    · intro x y hx hy; exact add_mem hx hy)

@[simp] theorem youngToCoinv_mk {μ : List ℕ} (hn : μ.sum = n) (p : MvPolynomial (Fin n) k) :
    youngToCoinv k hn (Submodule.Quotient.mk p) = Submodule.Quotient.mk (p * parG k μ) := rfl

/-- Decreasing staircase monomials `∏_a x_a^{u_a}`, `u_a ≤ n - 1 - a`, are linearly independent
in `L_n` (Artin's theorem, transported along the reversal `x_a ↦ x_{n-1-a}`). -/
theorem linearIndependent_decStair {ι : Type*} {f : ι → Fin n → ℕ} (hf : Function.Injective f)
    (hle : ∀ i a, f i a ≤ n - 1 - a) :
    LinearIndependent k (fun i => (Submodule.Quotient.mk (monoX (f i)) : Coinv k n)) := by
  have hstab : coinvSub k n ≤ (coinvSub k n).comap
      (rename (Fin.revPerm : Perm (Fin n)) : MvPolynomial (Fin n) k →ₐ[k] _).toLinearMap := by
    intro p hp
    rw [Submodule.mem_comap, AlgHom.toLinearMap_apply, mem_coinvSub]
    rw [mem_coinvSub] at hp
    induction hp using Submodule.span_induction with
    | mem s hs => rw [hs.1 Fin.revPerm]; exact Ideal.subset_span hs
    | zero => rw [map_zero]; exact zero_mem _
    | add x y _ _ hx hy => rw [map_add]; exact add_mem hx hy
    | smul a x _ hx => rw [smul_eq_mul, map_mul]; exact Ideal.mul_mem_left _ _ hx
  let R := (coinvSub k n).mapQ (coinvSub k n) _ hstab
  let g : ι → Staircase n := fun i => ⟨fun a => f i (Fin.rev a), fun a => by
    show f i (Fin.rev a) ≤ a
    have := hle i (Fin.rev a); rw [Fin.val_rev] at this; have := a.2; omega⟩
  have hg : Function.Injective g := by
    intro i j hij
    apply hf
    funext b
    have := congrFun (congrArg Subtype.val hij) (Fin.rev b)
    simpa only [g, Fin.rev_rev] using this
  refine LinearIndependent.of_comp R ?_
  convert (coinvBasis k n).linearIndependent.comp g hg using 1
  funext i
  simp only [Function.comp_apply, coinvBasis_apply, R, Submodule.mapQ_apply,
    AlgHom.toLinearMap_apply, monoX, map_prod, map_pow, rename_X, g]
  congr 1
  exact Fintype.prod_equiv Fin.revPerm _ _ fun a => by simp

/-- `∏_{a ∈ s} (#{b ∈ s | a < b} + 1) = |s|!`. -/
theorem prod_card_filter_lt_add_one {α : Type*} [LinearOrder α] (s : Finset α) :
    ∏ a ∈ s, ((s.filter fun b => a < b).card + 1) = s.card.factorial := by
  classical
  refine Finset.induction_on_min s (by simp) ?_
  intro m s hm ih
  have hms : m ∉ s := fun h => lt_irrefl _ (hm m h)
  have h1 : (insert m s).filter (fun b => m < b) = s := by
    ext b
    simp only [Finset.mem_filter, Finset.mem_insert]
    constructor
    · rintro ⟨rfl | hb, h⟩
      · exact absurd h (lt_irrefl _)
      · exact hb
    · intro hb; exact ⟨Or.inr hb, hm b hb⟩
  have h2 : ∀ a ∈ s, (insert m s).filter (fun b => a < b) = s.filter (fun b => a < b) := by
    intro a ha
    ext b
    simp only [Finset.mem_filter, Finset.mem_insert]
    constructor
    · rintro ⟨rfl | hb, h⟩
      · exact absurd (hm a ha) (not_lt.2 h.le)
      · exact ⟨hb, h⟩
    · rintro ⟨hb, h⟩; exact ⟨Or.inr hb, h⟩
  rw [Finset.prod_insert hms, Finset.card_insert_of_not_mem hms, Nat.factorial_succ, h1,
    Finset.prod_congr rfl fun a ha => by rw [h2 a ha], ih]

/-- `∏_a (#{b > a | lab b = lab a} + 1) = ∏_c |lab⁻¹(c)|!`. -/
theorem prod_card_lt_label_add_one {J : Type*} [DecidableEq J] (lab : Fin n → J) :
    ∏ a : Fin n, ((Finset.univ.filter fun b => a < b ∧ lab b = lab a).card + 1) =
      ∏ i ∈ Finset.univ.image lab, (Fintype.card {a // lab a = i}).factorial := by
  rw [← Finset.prod_fiberwise_of_maps_to (g := lab) (t := Finset.univ.image lab)
    (fun a _ => Finset.mem_image_of_mem lab (Finset.mem_univ a))]
  refine Finset.prod_congr rfl fun i _ => ?_
  rw [Fintype.card_subtype, ← prod_card_filter_lt_add_one]
  refine Finset.prod_congr rfl fun a ha => ?_
  rw [Finset.mem_filter] at ha
  congr 2
  ext b
  simp only [Finset.mem_filter, Finset.mem_univ, true_and, ha.2]
  tauto

theorem card_filter_lt_blockEnd {μ : List ℕ} (hn : μ.sum = n) (a : Fin n) :
    (Finset.univ.filter fun b : Fin n => a < b ∧ compLab μ b = compLab μ a).card =
      blockEnd 0 μ a - 1 - a := by
  have hE := blockEnd_le (p := 0) (μ := μ) (a := a) (by omega)
  have : (Finset.univ.filter fun b : Fin n => a < b ∧ compLab μ b = compLab μ a).map
      Fin.valEmbedding = Finset.Ioo (a : ℕ) (blockEnd 0 μ a) := by
    ext x
    simp only [Finset.mem_map, Finset.mem_filter, Finset.mem_univ, true_and, Fin.valEmbedding_apply,
      Finset.mem_Ioo, compLab]
    constructor
    · rintro ⟨b, ⟨hab, hb⟩, rfl⟩
      exact ⟨hab, (blockEnd_eq_iff_lt hab).1 hb⟩
    · rintro ⟨h1, h2⟩
      refine ⟨⟨x, by omega⟩, ⟨h1, (blockEnd_eq_iff_lt (b := x) h1).2 h2⟩, rfl⟩
  rw [← Finset.card_map, this, Nat.card_Ioo]
  omega

/-- The number of block-staircase exponents is `|S_μ| = dim L_μ`. -/
theorem card_parStair {μ : List ℕ} (hn : μ.sum = n) :
    Fintype.card ((a : Fin n) → Fin (blockEnd 0 μ a - 1 - a + 1)) =
      Module.finrank k (YoungCoinv k n μ) := by
  rw [finrank_youngCoinv, DomMulAct.stabilizer_card', Fintype.card_pi, ← prod_card_lt_label_add_one]
  refine Finset.prod_congr rfl fun a _ => ?_
  rw [Fintype.card_fin, card_filter_lt_blockEnd hn]

theorem youngToCoinv_injective {μ : List ℕ} (hn : μ.sum = n) :
    Function.Injective (youngToCoinv k hn) := by
  let ι := (a : Fin n) → Fin (blockEnd 0 μ a - 1 - a + 1)
  let G : ι → YoungCoinv k n μ := fun v => Submodule.Quotient.mk (monoX fun a => (v a : ℕ))
  have hF : LinearIndependent k (youngToCoinv k hn ∘ G) := by
    have : youngToCoinv k hn ∘ G = fun v : ι => (Submodule.Quotient.mk
        (monoX fun a => (v a : ℕ) + (n - blockEnd 0 μ a)) : Coinv k n) := by
      funext v
      simp only [Function.comp_apply, G, youngToCoinv_mk, parG, monoX_mul]
    rw [this]
    refine linearIndependent_decStair (fun v w h => funext fun a => Fin.ext ?_) fun v a => ?_
    · have := congrFun h a; simp only at this; omega
    · have h1 := lt_blockEnd 0 μ a
      have h2 := blockEnd_le (p := 0) (μ := μ) (a := a) (by omega)
      have := (v a).2
      omega
  have hG := hF.of_comp
  haveI : Nonempty ι := ⟨fun _ => 0⟩
  let b := basisOfLinearIndependentOfCardEqFinrank hG (card_parStair hn)
  rw [← LinearMap.ker_eq_bot, eq_bot_iff]
  intro v hv
  rw [LinearMap.mem_ker, ← b.sum_repr v, map_sum] at hv
  simp only [map_smul, b, coe_basisOfLinearIndependentOfCardEqFinrank] at hv
  have h0 := Fintype.linearIndependent_iff.1 hF _ hv
  rw [Submodule.mem_bot, ← b.sum_repr v]
  exact Finset.sum_eq_zero fun i _ => by rw [h0 i, zero_smul]

variable (k) in
/-- The `NH_μ`-linear map `L_μ → Res^n_μ L_n`, `[p] ↦ [p g_μ]`. -/
noncomputable def youngHom {μ : List ℕ} (hn : μ.sum = n) :
    YoungRep k n μ →ₗ[ParNH k n μ] NHRep k n where
  toFun v := NHRep.of k n (youngToCoinv k hn ((YoungRep.of k n μ).symm v))
  map_add' v w := by simp only [map_add]
  map_smul' T v := by
    obtain ⟨p, rfl⟩ := Submodule.Quotient.mk_surjective _ ((YoungRep.of k n μ).symm v)
    show NHRep.of k n (youngToCoinv k hn (youngAct k n μ T (Submodule.Quotient.mk p))) =
      T • NHRep.of k n (youngToCoinv k hn (Submodule.Quotient.mk p))
    rw [youngAct_mk, youngToCoinv_mk, youngToCoinv_mk, nhSub_smul_def, nhSubAct_mk,
      nhSub_apply_mul_parG (NHSub.val_mem T)]

theorem youngHom_mk {μ : List ℕ} (hn : μ.sum = n) (p : MvPolynomial (Fin n) k) :
    youngHom k hn (YoungRep.of k n μ (Submodule.Quotient.mk p)) =
      NHRep.of k n (Submodule.Quotient.mk (p * parG k μ)) := rfl

theorem youngHom_mem_nhSocle {μ : List ℕ} (hn : μ.sum = n) (v : YoungRep k n μ) :
    youngHom k hn v ∈ nhSocle k n Set.univ (compD μ) := by
  obtain ⟨p, rfl⟩ := Submodule.Quotient.mk_surjective _ ((YoungRep.of k n μ).symm v)
  have := (nhSocle k n Set.univ (compD μ)).smul_mem (parPoly k μ p) (mk_parG_mem_nhSocle hn)
  rw [nhSub_smul_def, nhSubAct_mk, val_parPoly, mulPoly_apply] at this
  exact this

variable (k) in
/-- **KL I Proposition 3.11 (2), socle**: `soc(Res^n_μ L_n) ≅ L_μ = L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})`
as `NH_μ`-modules, via `[p] ↦ [p g_μ]` (a grading shift by `deg g_μ`). -/
noncomputable def youngSocleEquiv {μ : List ℕ} (hn : μ.sum = n) :
    YoungRep k n μ ≃ₗ[ParNH k n μ] nhSocle k n Set.univ (compD μ) := by
  haveI := isSimpleModule_nhSocle (k := k) (n := n) (D := compD μ) univ_hS
  let f := LinearMap.codRestrict _ (youngHom k hn) (youngHom_mem_nhSocle hn)
  refine LinearEquiv.ofBijective f ⟨fun v w h => youngToCoinv_injective hn
    (congrArg Subtype.val h), ?_⟩
  rw [← LinearMap.range_eq_top]
  refine (IsSimpleOrder.eq_bot_or_eq_top (LinearMap.range f)).resolve_left fun h => ?_
  rw [LinearMap.range_eq_bot] at h
  have := congrArg (fun g => ((g (YoungRep.of k n μ (Submodule.Quotient.mk 1)) :
    nhSocle k n Set.univ (compD μ)) : NHRep k n)) h
  simp only [LinearMap.zero_apply, ZeroMemClass.coe_zero] at this
  apply mk_parG_ne_zero (k := k) hn
  rw [← one_mul (parG k μ)]
  exact this

theorem youngSocleEquiv_mk {μ : List ℕ} (hn : μ.sum = n) (p : MvPolynomial (Fin n) k) :
    ((youngSocleEquiv k hn (YoungRep.of k n μ (Submodule.Quotient.mk p)) :
      nhSocle k n Set.univ (compD μ)) : NHRep k n) =
      NHRep.of k n (Submodule.Quotient.mk (p * parG k μ)) := rfl

/-- **`L_μ = L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})` is a simple `NH_μ`-module.** -/
theorem isSimpleModule_youngRep {μ : List ℕ} (hn : μ.sum = n) :
    IsSimpleModule (ParNH k n μ) (YoungRep k n μ) := by
  haveI := isSimpleModule_nhSocle (k := k) (n := n) (D := compD μ) univ_hS
  exact IsSimpleModule.congr (youngSocleEquiv k hn)

/-- **KL I Proposition 3.11 (2), socle part**: `soc(Res^n_μ L_n)` (the sum of all simple
`NH_μ`-submodules of `L_n`) is the submodule generated by `[x^δ]`; it is irreducible, and it is
isomorphic to `L_μ = L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})` (via `[p] ↦ [p g_μ]`, a shift by `deg g_μ`). -/
theorem parNH_socle {μ : List ℕ} (hn : μ.sum = n) :
    sSup {N : Submodule (ParNH k n μ) (NHRep k n) | IsSimpleModule (ParNH k n μ) N} =
      nhSocle k n Set.univ (compD μ) ∧
    IsSimpleModule (ParNH k n μ) (nhSocle k n Set.univ (compD μ)) ∧
    Nonempty (YoungRep k n μ ≃ₗ[ParNH k n μ] nhSocle k n Set.univ (compD μ)) :=
  ⟨sSup_simple_eq_nhSocle univ_hS, isSimpleModule_nhSocle univ_hS, ⟨youngSocleEquiv k hn⟩⟩

/-! ### Uniqueness of the simple `NH_μ`-module -/

/-- `∂_ρ = 0` for every word of length `> n(n-1)/2`. -/
theorem ddw_eq_zero_of_choose_lt_length {ρ : List ℕ} (h : n.choose 2 < ρ.length) :
    ddw (k := k) (m := n) ρ = 0 := by
  by_cases hv : ValidWord n ρ
  · apply ddw_eq_zero_of_not_isReduced hv
    intro hr
    have := length_le_choose n (wordProd n ρ)
    rw [← hr.2] at this
    omega
  · simp only [ValidWord, not_forall] at hv
    obtain ⟨j, hj, hj'⟩ := hv
    obtain ⟨α, β, rfl⟩ := List.append_of_mem hj
    rw [ddw_append, ddw_cons, dd_eq_zero (by omega), zero_mul, mul_zero]

theorem mem_span_X_of_constantCoeff_eq_zero {s : MvPolynomial (Fin n) k}
    (hs0 : constantCoeff s = 0) : s ∈ Ideal.span (X '' (Set.univ : Set (Fin n))) := by
  refine mem_ideal_span_X_image.2 fun m hm => ?_
  by_contra hcon
  push_neg at hcon
  have : m = 0 := Finsupp.ext fun i => hcon i trivial
  subst this
  rw [mem_support_iff, ← constantCoeff_eq] at hm
  exact hm hs0

/-- The Leibniz rule `∂_j p = (∂_j p) + (s_j p) ∂_j` in `NH_μ`. -/
theorem dd_mul_parPoly {μ : List ℕ} {j : ℕ} (hj : j ∈ compD μ) (p : MvPolynomial (Fin n) k) :
    NHSub.mk (dd_mem_nhSub (k := k) (n := n) (S := Set.univ) hj) * parPoly k μ p =
      parPoly k μ (dd k n j p) + (if h : j + 1 < n then
        parPoly k μ (rename (swap (⟨j, by omega⟩ : Fin n) ⟨j + 1, h⟩) p) else 0) *
        NHSub.mk (dd_mem_nhSub (k := k) (n := n) (S := Set.univ) hj) := by
  apply NHSub.val_injective
  rw [map_mul, map_add, map_mul, NHSub.val_mk, val_parPoly, val_parPoly]
  refine LinearMap.ext fun f => ?_
  by_cases h : j + 1 < n
  · rw [dif_pos h, val_parPoly]
    simp only [Module.End.mul_apply, mulPoly_apply, LinearMap.add_apply]
    rw [dd_of_lt h]
    exact ddiff_mul (by simp [Fin.ext_iff]) p f
  · rw [dif_neg h, map_zero, zero_mul, dd_eq_zero (by omega)]
    simp

/-- `NH_μ` acting on a module, as `k`-linear endomorphisms. -/
noncomputable def parSmulEnd {μ : List ℕ} {M : Type*} [AddCommGroup M] [Module (ParNH k n μ) M]
    [Module k M] [IsScalarTower k (ParNH k n μ) M] (T : ParNH k n μ) : Module.End k M :=
  DistribMulAction.toLinearMap k M T

theorem prod_map_parSmulEnd {μ : List ℕ} {M : Type*} [AddCommGroup M] [Module (ParNH k n μ) M]
    [Module k M] [IsScalarTower k (ParNH k n μ) M] {ι : Type*} (f : ι → ParNH k n μ)
    (ρ : List ι) : (ρ.map fun i => parSmulEnd (M := M) (f i)).prod =
      parSmulEnd (M := M) (ρ.map f).prod := by
  induction ρ with
  | nil => ext v; simp [parSmulEnd]
  | cons i ρ ih =>
    rw [List.map_cons, List.prod_cons, ih, List.map_cons, List.prod_cons]
    ext v
    simp [parSmulEnd, mul_smul]

/-- **Uniqueness of the simple `NH_μ`-module** (KL I Proposition 3.11 (1) for `NH_μ`; for
`μ = (n)` this is the ungraded content of (1)): every simple `NH_μ`-module on which products of
sufficiently many `x_a` vanish is isomorphic to `L_μ = L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})`. -/
theorem nonempty_linearEquiv_youngRep {μ : List ℕ} (hn : μ.sum = n) {M : Type*}
    [AddCommGroup M] [Module (ParNH k n μ) M] [Module k M] [IsScalarTower k (ParNH k n μ) M]
    [IsSimpleModule (ParNH k n μ) M]
    (hx : ∃ C : ℕ, ∀ ρ : List (Fin n), C < ρ.length → ∀ v : M,
      parPoly k μ (ρ.map fun a => (X a : MvPolynomial (Fin n) k)).prod • v = 0) :
    Nonempty (YoungRep k n μ ≃ₗ[ParNH k n μ] M) := by
  haveI := isSimpleModule_youngRep (k := k) hn
  haveI : Nontrivial M := IsSimpleModule.nontrivial (ParNH k n μ) M
  obtain ⟨C, hC⟩ := hx
  obtain ⟨v₀, hv₀⟩ := exists_ne (0 : M)
  -- a nonzero vector killed by the `∂_j`
  obtain ⟨u, -, hu0, hu⟩ := exists_ne_zero_forall_eq_zero
    (fun j : compD μ =>
      parSmulEnd (M := M) (NHSub.mk (dd_mem_nhSub (k := k) (n := n) (S := Set.univ) j.2)))
    (n.choose 2) (fun ρ hρ => by
      rw [prod_map_parSmulEnd]
      have h0 : (ρ.map fun j : compD μ =>
          NHSub.mk (dd_mem_nhSub (k := k) (n := n) (S := Set.univ) j.2)).prod
          = 0 := by
        apply NHSub.val_injective
        rw [map_list_prod, List.map_map, map_zero]
        have : (NHSub.val k n Set.univ (compD μ) ∘ fun j : compD μ =>
            NHSub.mk (dd_mem_nhSub (k := k) (n := n) (S := Set.univ) j.2)) =
            fun j => dd k n j.1 := rfl
        have h2 : (ρ.map fun j : compD μ => dd k n j.1) = (ρ.map Subtype.val).map (dd k n) := by
          rw [List.map_map]; rfl
        rw [this, h2]
        exact ddw_eq_zero_of_choose_lt_length (ρ := ρ.map Subtype.val)
          (by rw [List.length_map]; exact hρ)
      rw [h0]; ext v; simp [parSmulEnd])
    Set.univ (fun _ _ _ => trivial) (Set.mem_univ v₀) hv₀
  -- a nonzero vector killed by the `x_a`
  obtain ⟨v, -, hv0, hv⟩ := exists_ne_zero_forall_eq_zero
    (fun a : Fin n => parSmulEnd (M := M) (parPoly k μ (X a))) C (fun ρ hρ => by
      rw [prod_map_parSmulEnd]
      have : (ρ.map fun a => parPoly k μ (X a)) =
          (ρ.map fun a => (X a : MvPolynomial (Fin n) k)).map (parPoly k μ) := by
        rw [List.map_map]; rfl
      rw [this, ← map_list_prod]
      ext w
      exact hC ρ hρ w)
    Set.univ (fun _ _ _ => trivial) (Set.mem_univ v₀) hv₀
  have hv' : ∀ s : MvPolynomial (Fin n) k, constantCoeff s = 0 → parPoly k μ s • v = 0 := by
    intro s hs0
    have hmem := mem_span_X_of_constantCoeff_eq_zero hs0
    clear hs0
    induction hmem using Submodule.span_induction with
    | mem x hx => obtain ⟨a, -, rfl⟩ := hx; exact hv a
    | zero => rw [map_zero, zero_smul]
    | add x y _ _ hx hy => rw [map_add, add_smul, hx, hy, add_zero]
    | smul r x _ hx => rw [smul_eq_mul, map_mul, mul_smul, hx, smul_zero]
  -- Schur: `Sym_μ⁺` kills `u`
  have hsym : ∀ s ∈ labelInvariants k (compLab (n := n) μ), constantCoeff s = 0 →
      parPoly k μ s • u = 0 := by
    intro s hs hs0
    let f : M →ₗ[ParNH k n μ] M :=
      { toFun := fun w => parPoly k μ s • w
        map_add' := smul_add _
        map_smul' := fun T w => by
          simp only [RingHom.id_apply]
          rw [← mul_smul, ← mul_smul, parPoly_commute hs T] }
    rcases LinearMap.bijective_or_eq_zero f with hf | hf
    · exact absurd (hf.1 (show f v = f 0 by rw [map_zero]; exact hv' s hs0)) hv0
    · exact congrArg (fun g => g u) hf
  -- the map `L_μ → M`, `[p] ↦ p u`
  let ψ₀ : MvPolynomial (Fin n) k →ₗ[k] M :=
    { toFun := fun p => parPoly k μ p • u
      map_add' := fun p q => by rw [map_add, add_smul]
      map_smul' := fun c p => by rw [map_smul, smul_assoc]; rfl }
  have hker : youngSub k n μ ≤ LinearMap.ker ψ₀ := by
    intro p hp
    refine augSubmodule_induction (p := fun p => p ∈ LinearMap.ker ψ₀) hp ?_ ?_
    · intro r hr m
      rw [LinearMap.mem_ker]
      show parPoly k μ ((r : MvPolynomial (Fin n) k) * m) • u = 0
      rw [mul_comm, map_mul, mul_smul, hsym _ r.2 (by rw [← youngAug_apply]; exact hr),
        smul_zero]
    · intro x y hx hy; exact add_mem hx hy
  let ψ₁ := (youngSub k n μ).liftQ ψ₀ hker
  have hψ₁ : ∀ p, ψ₁ (Submodule.Quotient.mk p) = parPoly k μ p • u := fun p => rfl
  -- `NH_μ`-linearity
  have hlin : ∀ U (hU : U ∈ nhSub k n Set.univ (compD μ)) (p : MvPolynomial (Fin n) k),
      parPoly k μ (U p) • u = NHSub.mk hU • parPoly k μ p • u := by
    intro U hU
    induction hU using Algebra.adjoin_induction with
    | mem y hy =>
      intro p
      rcases hy with ⟨a, -, rfl⟩ | ⟨j, hj, rfl⟩
      · rw [← mul_smul]
        congr 1
        apply NHSub.val_injective
        rw [map_mul, val_parPoly, val_parPoly, NHSub.val_mk, mulX_apply, map_mul, mulPoly_X]
      · rw [← mul_smul, dd_mul_parPoly hj, add_smul, mul_smul]
        have : NHSub.mk (dd_mem_nhSub (k := k) (n := n) (S := Set.univ) hj) • u = 0 := hu ⟨j, hj⟩
        rw [this, smul_zero, add_zero]
    | algebraMap c =>
      intro p
      rw [Module.algebraMap_end_apply, map_smul, smul_assoc]
      have : (NHSub.mk (Subalgebra.algebraMap_mem (nhSub k n Set.univ (compD μ)) c) :
          ParNH k n μ) = algebraMap k (ParNH k n μ) c := rfl
      rw [this, algebraMap_smul]
    | add U V hU hV ihU ihV =>
      intro p
      rw [LinearMap.add_apply, map_add, add_smul, ihU, ihV, ← add_smul]
      rfl
    | mul U V hU hV ihU ihV =>
      intro p
      rw [Module.End.mul_apply, ihU, ihV, ← mul_smul]
      rfl
  let ψ : YoungRep k n μ →ₗ[ParNH k n μ] M :=
    { toFun := fun w => ψ₁ ((YoungRep.of k n μ).symm w)
      map_add' := fun w w' => map_add ψ₁ _ _
      map_smul' := fun T w => by
        obtain ⟨p, hp⟩ := Submodule.Quotient.mk_surjective _ ((YoungRep.of k n μ).symm w)
        show ψ₁ (youngAct k n μ T ((YoungRep.of k n μ).symm w)) = T • ψ₁ _
        rw [← hp, youngAct_mk, hψ₁, hψ₁]
        exact hlin _ (NHSub.val_mem T) p }
  have hψ0 : ψ ≠ 0 := by
    intro h
    apply hu0
    have h1 : ψ (YoungRep.of k n μ (Submodule.Quotient.mk 1)) = parPoly k μ 1 • u := hψ₁ 1
    rw [h, LinearMap.zero_apply, map_one, one_smul] at h1
    exact h1.symm
  exact ⟨LinearEquiv.ofBijective ψ (LinearMap.bijective_of_ne_zero hψ0)⟩

theorem parPoly_prod_smul_nhRep_eq_zero {μ : List ℕ} {ρ : List (Fin n)}
    (hρ : n.choose 2 < ρ.length) (v : NHRep k n) :
    parPoly k μ (ρ.map fun a => (X a : MvPolynomial (Fin n) k)).prod • v = 0 := by
  obtain ⟨q, rfl⟩ := Submodule.Quotient.mk_surjective _ ((NHRep.of k n).symm v)
  show parPoly k μ _ • NHRep.of k n (Submodule.Quotient.mk q) = 0
  rw [nhSub_smul_def, nhSubAct_mk, val_parPoly, mulPoly_apply]
  show (Submodule.Quotient.mk _ : Coinv k n) = 0
  rw [Submodule.Quotient.mk_eq_zero, mem_coinvSub]
  exact Ideal.mul_mem_right _ _ (mem_coinvIdeal_of_isHomogeneous (isHomogeneous_prod_map_X ρ) hρ)

/-- **KL I Proposition 3.11 (2), composition factors**: every simple subquotient `N / N'` of
`Res^n_μ L_n` is isomorphic to `L_μ = L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})`. -/
theorem nonempty_linearEquiv_youngRep_subquotient {μ : List ℕ} (hn : μ.sum = n)
    (N N' : Submodule (ParNH k n μ) (NHRep k n))
    [IsSimpleModule (ParNH k n μ) (N ⧸ N'.comap N.subtype)] :
    Nonempty (YoungRep k n μ ≃ₗ[ParNH k n μ] (N ⧸ N'.comap N.subtype)) := by
  refine nonempty_linearEquiv_youngRep hn ⟨n.choose 2, fun ρ hρ w => ?_⟩
  obtain ⟨w, rfl⟩ := Submodule.Quotient.mk_surjective _ w
  rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero]
  have : parPoly k μ (ρ.map fun a => (X a : MvPolynomial (Fin n) k)).prod • w = 0 :=
    Subtype.ext (parPoly_prod_smul_nhRep_eq_zero hρ (w : NHRep k n))
  rw [this]
  exact zero_mem _

/-! ### `Res^n_{n-1}` (Proposition 3.11 (3)) -/

/-- On `L_n`, `x_c = -∑_{a ≠ c} x_a`. -/
theorem coinvMul_X_eq_neg_sum (c : Fin n) (v : Coinv k n) :
    coinvMul k (X c) v = -∑ a ∈ Finset.univ.erase c, coinvMul k (X a) v := by
  obtain ⟨q, rfl⟩ := Submodule.Quotient.mk_surjective _ v
  rw [eq_neg_iff_add_eq_zero]
  simp only [coinvMul_mk]
  have hsum : (∑ a ∈ Finset.univ.erase c, (Submodule.Quotient.mk (X a * q) : Coinv k n)) =
      Submodule.Quotient.mk (∑ a ∈ Finset.univ.erase c, X a * q) := by
    rw [← Submodule.mkQ_apply, map_sum]; rfl
  rw [hsum, ← Submodule.Quotient.mk_add, Submodule.Quotient.mk_eq_zero, mem_coinvSub]
  have : X c * q + ∑ a ∈ Finset.univ.erase c, X a * q = esymm (Fin n) k 1 * q := by
    rw [esymm_one, Finset.sum_mul, ← Finset.add_sum_erase _ _ (Finset.mem_univ c)]
  rw [this]
  exact Ideal.mul_mem_right _ _ (esymm_succ_mem_coinvIdeal n 0)

theorem resD_subset_compD : {j : ℕ | j + 2 < n} ⊆ compD [n - 1, 1] := by
  intro j hj
  simp only [Set.mem_setOf_eq] at hj
  simp only [compD, Set.mem_setOf_eq, blockEnd]
  split_ifs <;> omega

theorem compD_subset_resD {j : ℕ} (hj : j ∈ compD [n - 1, 1]) (h : j + 1 < n) : j + 2 < n := by
  simp only [compD, Set.mem_setOf_eq, blockEnd] at hj
  split_ifs at hj <;> omega

theorem resNH_le_compD {S : Set (Fin n)} :
    nhSub k n S {j | j + 2 < n} ≤ nhSub k n S (compD [n - 1, 1]) :=
  Algebra.adjoin_mono (Set.union_subset_union le_rfl (Set.image_subset _ resD_subset_compD))

variable (k n) in
/-- The action of `NH_{n-1}` on `L_{(n-1,1)}`. -/
noncomputable def youngResAct : ResNH k n →ₐ[k] Module.End k (YoungCoinv k n [n - 1, 1]) where
  toFun T := (youngSub k n [n - 1, 1]).mapQ (youngSub k n [n - 1, 1]) (NHSub.val k n _ _ T)
    fun _ hp => nhSub_stable_youngSub (resNH_le_compD T.2) hp
  map_one' := by ext; simp
  map_mul' T T' := by ext; simp
  map_zero' := by ext; simp
  map_add' T T' := by ext; simp
  commutes' c := by ext; simp [Module.algebraMap_end_apply]

/-- `L_{(n-1,1)}` restricted to `NH_{n-1}`. -/
noncomputable instance : Module (ResNH k n) (YoungRep k n [n - 1, 1]) :=
  Module.compHom (YoungCoinv k n [n - 1, 1]) (youngResAct k n).toRingHom

theorem resNH_smul_youngRep_mk (T : ResNH k n) (p : MvPolynomial (Fin n) k) :
    T • YoungRep.of k n [n - 1, 1] (Submodule.Quotient.mk p) =
      YoungRep.of k n [n - 1, 1] (Submodule.Quotient.mk (NHSub.val k n _ _ T p)) := rfl

/-- The socle of `Res^n_{n-1} L_n` is stable under `NH_{(n-1,1)}` (as `x_{n-1} = -∑_{a < n-1} x_a`
on `L_n`). -/
theorem parNH_smul_mem_resSocle (T : ParNH k n [n - 1, 1]) {w : NHRep k n}
    (hw : w ∈ nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n}) :
    T • w ∈ nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n} := by
  set R := nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n}
  have key : ∀ U (hU : U ∈ nhSub k n Set.univ (compD [n - 1, 1])), ∀ w ∈ R,
      (NHSub.mk hU : ParNH k n [n - 1, 1]) • w ∈ R := by
    intro U hU
    induction hU using Algebra.adjoin_induction with
    | mem y hy =>
      intro w hw
      rcases hy with ⟨a, -, rfl⟩ | ⟨j, hj, rfl⟩
      · obtain ⟨v, rfl⟩ := (NHRep.of k n).surjective w
        rw [mulX_smul (D := compD [n - 1, 1]) (Set.mem_univ a)]
        by_cases ha : (a : ℕ) + 1 < n
        · rw [← mulX_smul (D := {j | j + 2 < n}) (show a ∈ {a : Fin n | (a : ℕ) + 1 < n} from ha)]
          exact R.smul_mem _ hw
        · rw [coinvMul_X_eq_neg_sum, map_neg, map_sum]
          refine R.neg_mem (R.sum_mem fun b hb => ?_)
          have hb' : (b : ℕ) + 1 < n := by
            have := (Finset.mem_erase.1 hb).1
            have : (b : ℕ) ≠ a := fun h => this (Fin.ext h)
            have := b.2
            omega
          rw [← mulX_smul (D := {j | j + 2 < n}) (show b ∈ {a : Fin n | (a : ℕ) + 1 < n} from hb')]
          exact R.smul_mem _ hw
      · by_cases h : j + 1 < n
        · have h' := compD_subset_resD hj h
          obtain ⟨v, rfl⟩ := (NHRep.of k n).surjective w
          obtain ⟨q, rfl⟩ := Submodule.Quotient.mk_surjective _ v
          have := R.smul_mem (NHSub.mk (dd_mem_nhSub (k := k) (n := n)
            (S := {a : Fin n | (a : ℕ) + 1 < n}) (show j ∈ {j | j + 2 < n} from h'))) hw
          rw [nhSub_smul_def, nhSubAct_mk, NHSub.val_mk] at this
          rw [nhSub_smul_def, nhSubAct_mk, NHSub.val_mk]
          exact this
        · have : (NHSub.mk (Algebra.subset_adjoin (Or.inr ⟨j, hj, rfl⟩)) : ParNH k n [n - 1, 1]) =
              0 := NHSub.val_injective (by rw [NHSub.val_mk, map_zero, dd_eq_zero (by omega)])
          rw [this, zero_smul]
          exact zero_mem _
    | algebraMap c =>
      intro w hw
      have : (NHSub.mk (Subalgebra.algebraMap_mem (nhSub k n Set.univ (compD [n - 1, 1])) c) :
          ParNH k n [n - 1, 1]) = algebraMap k (ParNH k n [n - 1, 1]) c :=
        NHSub.val_injective (by rw [NHSub.val_mk, AlgHom.commutes])
      rw [this, algebraMap_smul]
      exact R.smul_of_tower_mem c hw
    | add U V hU hV ihU ihV =>
      intro w hw
      have : (NHSub.mk (add_mem hU hV) : ParNH k n [n - 1, 1]) = NHSub.mk hU + NHSub.mk hV :=
        NHSub.val_injective (by rw [map_add, NHSub.val_mk, NHSub.val_mk, NHSub.val_mk])
      rw [this, add_smul]
      exact R.add_mem (ihU w hw) (ihV w hw)
    | mul U V hU hV ihU ihV =>
      intro w hw
      have : (NHSub.mk (mul_mem hU hV) : ParNH k n [n - 1, 1]) = NHSub.mk hU * NHSub.mk hV :=
        NHSub.val_injective (by rw [map_mul, NHSub.val_mk, NHSub.val_mk, NHSub.val_mk])
      rw [this, mul_smul]
      exact ihU _ (ihV w hw)
  exact key _ (NHSub.val_mem T) w hw

theorem nhSocle_parNH_le_resSocle {w : NHRep k n}
    (hw : w ∈ nhSocle k n Set.univ (compD [n - 1, 1])) :
    w ∈ nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n} := by
  induction hw using Submodule.span_induction with
  | mem x hx => rw [Set.mem_singleton_iff] at hx; subst hx; exact xDelta_mem_nhSocle
  | zero => exact zero_mem _
  | add x y _ _ hx hy => exact add_mem hx hy
  | smul T x _ hx => exact parNH_smul_mem_resSocle T hx

theorem sum_pred_one {n : ℕ} (hn : 1 ≤ n) : [n - 1, 1].sum = n := by
  simp only [List.sum_cons, List.sum_nil]; omega

variable (k) in
/-- **KL I Proposition 3.11 (3)**: `soc(Res^n_{n-1} L_n) ≅ L_{(n-1,1)}` as modules over
`NH_{n-1} ⊆ NH_n` (the subalgebra generated by `x_0, …, x_{n-2}` and `∂_0, …, ∂_{n-3}`), where
`L_{(n-1,1)} = k[x]/(Sym_{n-1}⁺, x_{n-1}) = L(i^{n-1}) ⊗ L(i)` (a grading shift by
`deg g_{(n-1,1)} = n - 1`). -/
noncomputable def resSocleEquiv (hn : 1 ≤ n) :
    YoungRep k n [n - 1, 1] ≃ₗ[ResNH k n]
      nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n} := by
  haveI := isSimpleModule_nhSocle (k := k) (n := n) (D := {j | j + 2 < n}) resNH_hS
  let f : YoungRep k n [n - 1, 1] →ₗ[ResNH k n]
      nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n} :=
    { toFun := fun v => ⟨youngHom k (sum_pred_one hn) v,
        nhSocle_parNH_le_resSocle (youngHom_mem_nhSocle _ v)⟩
      map_add' := fun v w => Subtype.ext (map_add _ v w)
      map_smul' := fun T v => Subtype.ext (by
        obtain ⟨p, hp⟩ := Submodule.Quotient.mk_surjective _ ((YoungRep.of k n [n - 1, 1]).symm v)
        rw [RingHom.id_apply, SetLike.val_smul]
        show youngHom k (sum_pred_one hn) (T • v) = T • youngHom k (sum_pred_one hn) v
        rw [← (YoungRep.of k n _).apply_symm_apply v, ← hp, resNH_smul_youngRep_mk, youngHom_mk,
          youngHom_mk, nhSub_smul_def, nhSubAct_mk,
          nhSub_apply_mul_parG (resNH_le_compD (NHSub.val_mem T))]) }
  refine LinearEquiv.ofBijective f ⟨fun v w h => youngToCoinv_injective (sum_pred_one hn)
    (congrArg Subtype.val h), ?_⟩
  rw [← LinearMap.range_eq_top]
  refine (IsSimpleOrder.eq_bot_or_eq_top (LinearMap.range f)).resolve_left fun h => ?_
  rw [LinearMap.range_eq_bot] at h
  have := congrArg (fun g => ((g (YoungRep.of k n _ (Submodule.Quotient.mk 1)) :
    nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n}) : NHRep k n)) h
  simp only [LinearMap.zero_apply, ZeroMemClass.coe_zero] at this
  apply mk_parG_ne_zero (k := k) (sum_pred_one hn)
  rw [← one_mul (parG k [n - 1, 1])]
  exact this

/-- **KL I Proposition 3.11 (3)**: the socle of `Res^n_{n-1} L_n` is irreducible, and it is
isomorphic to `L_{(n-1,1)} = L(i^{n-1}) ⊗ L(i)` as an `NH_{n-1}`-module. -/
theorem resNH_socle (hn : 1 ≤ n) :
    sSup {N : Submodule (ResNH k n) (NHRep k n) | IsSimpleModule (ResNH k n) N} =
      nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n} ∧
    IsSimpleModule (ResNH k n) (nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n}) ∧
    Nonempty (YoungRep k n [n - 1, 1] ≃ₗ[ResNH k n]
      nhSocle k n {a : Fin n | (a : ℕ) + 1 < n} {j | j + 2 < n}) :=
  ⟨sSup_simple_eq_nhSocle resNH_hS, isSimpleModule_nhSocle resNH_hS, ⟨resSocleEquiv k hn⟩⟩

end Categorification.NilHecke
