/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.NilHeckeSimple
import Categorification.Algebra.ParabolicSymmetricFree

/-!
# Parabolic nilHecke subalgebras and Young coinvariants

Khovanov–Lauda I (arXiv:0803.4121v2), §3.2, Proposition 3.11 (TeX lines 2168–2181): for a
composition `μ = (μ_1, …, μ_r)` of `n`, `Res^n_μ` is the restriction to the *parabolic nilHecke
subalgebra* `NH_μ ≅ NH_{μ_1} ⊗ ⋯ ⊗ NH_{μ_r}` of `NH_n`.

We realise `NH_μ` inside `NH_n = nilHecke k n ⊆ End_k(k[x_0, …, x_{n-1}])` as the subalgebra
generated by all `x_a` and by the divided differences `∂_j` for which the (zero-indexed)
positions `j` and `j + 1` lie in the same block of `μ`. More generally `nhSub k n S D` is the
subalgebra generated by the `x_a`, `a ∈ S`, and the `∂_j`, `j ∈ D`; the restriction
`Res^n_{n-1}` to `NH_{n-1} ⊆ NH_{n-1} ⊗ NH_1` is the case `S = {a | a + 1 < n}`,
`D = {j | j + 2 < n}` (`ResNH`).

The `NH_μ`-module `L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})` is realised as the *Young coinvariant algebra*
`L_μ = k[x] / (Sym_μ⁺)` (`YoungCoinv`), where `Sym_μ = k[x]^{S_μ}` is the ring of invariants of
the Young subgroup `S_μ = S_{μ_1} × ⋯ × S_{μ_r}` (`labelInvariants`) and `(Sym_μ⁺)` is the ideal
generated by the invariants without constant term: under `k[x] = ⊗_t k[x_{block t}]` this is
`⊗_t k[x_{block t}]/(Sym⁺_{block t}) = ⊗_t L_{μ_t}`.

## Blocks

A composition is a list `μ : List ℕ` (zero parts are allowed and harmless). The block of a
position `a` is recorded by its end `blockEnd 0 μ a` (the first position of the next block);
positions past `μ.sum` form singleton blocks. The Young subgroup is the stabiliser of the
labelling `compLab μ : Fin n → ℕ`, `a ↦ blockEnd 0 μ a`.

## Main definitions

* `NilHecke.nhSub k n S D` (as a type: `NilHecke.NHSub k n S D`), `NilHecke.ParNH k n μ`
  (`= NH_μ`), `NilHecke.ResNH k n` (`= NH_{n-1}`);
* the action of `nhSub k n S D` on `L_n` (`NHRep k n`);
* `NilHecke.YoungCoinv k n μ` (`= L_μ`) with its `NH_μ`-module structure (`YoungRep k n μ`).

## Main results

* `NilHecke.xDelta_mem_of_ne_bot` : if `S` omits at most one index, every nonzero
  `nhSub k n S D`-submodule of `L_n` contains `[x^δ]` (KL I Lemma 2.1: the common kernel of the
  `x_a` is the line `k [x^δ]`, and `x_c = -∑_{a ≠ c} x_a` on `L_n`).
* `NilHecke.isSimpleModule_nhSocle`, `NilHecke.isSimpleModule_iff_eq_nhSocle`,
  `NilHecke.sSup_simple_eq_nhSocle` : **the socle of `L_n` as a module over such a subalgebra is
  irreducible**; it is the submodule generated by `[x^δ]`, which is the unique simple submodule
  and is contained in every nonzero submodule. This covers `Res^n_μ L(i^n)` (`ParNH`) and
  `Res^n_{n-1} L(i^n)` (`ResNH`) of Proposition 3.11 (2), (3).
* `NilHecke.finrank_youngCoinv` : `dim L_μ = |S_μ|`.
-/

namespace Categorification.NilHecke

open MvPolynomial Equiv

/-! ### Blocks of a composition -/

/-- `blockEnd p μ a`: for the blocks `[p, p + μ_1), [p + μ_1, p + μ_1 + μ_2), …`, the end of the
block containing `a`; positions `a < p` or `a ≥ p + μ.sum` form singleton blocks `[a, a + 1)`. -/
def blockEnd : ℕ → List ℕ → ℕ → ℕ
  | _, [], a => a + 1
  | p, m :: μ, a => if a < p + m then (if p ≤ a then p + m else a + 1) else blockEnd (p + m) μ a

theorem lt_blockEnd (p : ℕ) (μ : List ℕ) (a : ℕ) : a < blockEnd p μ a := by
  induction μ generalizing p with
  | nil => simp [blockEnd]
  | cons m μ ih =>
    simp only [blockEnd]
    split_ifs <;> first | omega | exact ih _

theorem blockEnd_le {p : ℕ} {μ : List ℕ} {a : ℕ} (ha : a < p + μ.sum) :
    blockEnd p μ a ≤ p + μ.sum := by
  induction μ generalizing p with
  | nil => simp only [blockEnd, List.sum_nil] at ha ⊢; omega
  | cons m μ ih =>
    simp only [blockEnd, List.sum_cons] at ha ⊢
    split_ifs with h1 h2
    · omega
    · omega
    · have := ih (p := p + m) (by omega); omega

theorem blockEnd_eq_of_le_of_lt {p : ℕ} {μ : List ℕ} {a b : ℕ} (hab : a ≤ b)
    (hb : b < blockEnd p μ a) : blockEnd p μ b = blockEnd p μ a := by
  induction μ generalizing p with
  | nil => simp only [blockEnd] at hb ⊢; omega
  | cons m μ ih =>
    simp only [blockEnd] at hb ⊢
    by_cases h1 : a < p + m
    · rw [if_pos h1] at hb ⊢
      by_cases h2 : p ≤ a
      · rw [if_pos h2] at hb ⊢
        rw [if_pos hb, if_pos (by omega)]
      · rw [if_neg h2] at hb ⊢
        have : b = a := by omega
        subst this
        rw [if_pos h1, if_neg h2]
    · rw [if_neg h1] at hb ⊢
      rw [if_neg (by omega)]
      exact ih hb

/-- Two positions are in the same block iff their block ends agree; the block of `a` is
`[a₀, blockEnd p μ a)`, so `b > a` is in the block of `a` iff `b < blockEnd p μ a`. -/
theorem blockEnd_eq_iff_lt {p : ℕ} {μ : List ℕ} {a b : ℕ} (hab : a < b) :
    blockEnd p μ b = blockEnd p μ a ↔ b < blockEnd p μ a := by
  constructor
  · intro h
    have := lt_blockEnd p μ b
    omega
  · exact blockEnd_eq_of_le_of_lt hab.le

/-! ### Parabolic subalgebras -/

variable (k : Type*) [Field k] (n : ℕ)

/-- The subalgebra of `NH_n` generated by the `x_a`, `a ∈ S`, and the `∂_j`, `j ∈ D`. -/
noncomputable def nhSub (S : Set (Fin n)) (D : Set ℕ) :
    Subalgebra k (Module.End k (MvPolynomial (Fin n) k)) :=
  Algebra.adjoin k (mulX k n '' S ∪ dd k n '' D)

/-- The positions `j` such that `j` and `j + 1` lie in the same block of `μ`. -/
def compD (μ : List ℕ) : Set ℕ := {j | blockEnd 0 μ (j + 1) = blockEnd 0 μ j}

variable (S : Set (Fin n)) (D : Set ℕ)

/-- `nhSub k n S D` as a type (a type synonym, with its ring and algebra structures registered
directly, which keeps instance search for its modules and submodules fast). -/
def NHSub : Type _ := nhSub k n S D

noncomputable instance : Ring (NHSub k n S D) := Subalgebra.toRing _
noncomputable instance : Algebra k (NHSub k n S D) := Subalgebra.algebra _

/-- The inclusion `NHSub k n S D → End_k(k[x])`. -/
noncomputable def NHSub.val : NHSub k n S D →ₐ[k] Module.End k (MvPolynomial (Fin n) k) :=
  (nhSub k n S D).val

variable {k n S D} in
/-- An element of `nhSub k n S D`, as an element of `NHSub k n S D`. -/
def NHSub.mk {T : Module.End k (MvPolynomial (Fin n) k)} (hT : T ∈ nhSub k n S D) :
    NHSub k n S D := ⟨T, hT⟩

variable {k n S D} in
@[simp] theorem NHSub.val_mk {T : Module.End k (MvPolynomial (Fin n) k)}
    (hT : T ∈ nhSub k n S D) : NHSub.val k n S D (NHSub.mk hT) = T := rfl

variable {k n S D} in
theorem NHSub.val_mem (T : NHSub k n S D) : NHSub.val k n S D T ∈ nhSub k n S D := T.2

/-- **The parabolic nilHecke subalgebra** `NH_μ ⊆ NH_n` (KL I Proposition 3.11): generated by all
`x_a` and the `∂_j` with `j`, `j + 1` in the same block of `μ`. -/
abbrev ParNH (μ : List ℕ) : Type _ := NHSub k n Set.univ (compD μ)

/-- The subalgebra `NH_{n-1} ⊆ NH_n` generated by `x_0, …, x_{n-2}` and `∂_0, …, ∂_{n-3}`: the
restriction `Res^n_{n-1}` of KL I Proposition 3.11 (3). -/
abbrev ResNH : Type _ := NHSub k n {a | (a : ℕ) + 1 < n} {j | j + 2 < n}

variable {k n}

theorem nhSub_le {S : Set (Fin n)} {D : Set ℕ} : nhSub k n S D ≤ nilHecke k n :=
  Algebra.adjoin_mono (Set.union_subset_union (Set.image_subset_range _ _)
    (Set.image_subset_range _ _))

theorem mulX_mem_nhSub {S : Set (Fin n)} {D : Set ℕ} {a : Fin n} (ha : a ∈ S) :
    mulX k n a ∈ nhSub k n S D :=
  Algebra.subset_adjoin (Or.inl ⟨a, ha, rfl⟩)

theorem dd_mem_nhSub {S : Set (Fin n)} {D : Set ℕ} {j : ℕ} (hj : j ∈ D) :
    dd k n j ∈ nhSub k n S D :=
  Algebra.subset_adjoin (Or.inr ⟨j, hj, rfl⟩)

theorem ddw_mem_nhSub {S : Set (Fin n)} {D : Set ℕ} {ρ : List ℕ} (hρ : ∀ j ∈ ρ, j ∈ D) :
    ddw (k := k) (m := n) ρ ∈ nhSub k n S D := by
  induction ρ with
  | nil => exact one_mem _
  | cons j ρ ih =>
    rw [ddw_cons]
    exact mul_mem (dd_mem_nhSub (hρ j List.mem_cons_self))
      (ih fun l hl => hρ l (List.mem_cons_of_mem _ hl))

theorem mulPoly_mem_nhSub {D : Set ℕ} (p : MvPolynomial (Fin n) k) :
    mulPoly k n p ∈ nhSub k n Set.univ D := by
  induction p using MvPolynomial.induction_on with
  | C a => rw [algHom_C]; exact Subalgebra.algebraMap_mem _ a
  | add p q hp hq => rw [map_add]; exact add_mem hp hq
  | mul_X p a hp => rw [map_mul]; exact mul_mem hp (mulX_mem_nhSub (Set.mem_univ a))

/-! ### `L_n` as a module over `nhSub k n S D` -/

variable {S : Set (Fin n)} {D : Set ℕ}

variable (k n S D) in
/-- The action of `nhSub k n S D ⊆ NH_n` on `L_n`. -/
noncomputable def nhSubAct : NHSub k n S D →ₐ[k] Module.End k (Coinv k n) :=
  (nhAct k n).comp (Subalgebra.inclusion nhSub_le)

/-- `L_n` restricted to `nhSub k n S D`. -/
noncomputable instance instModuleNHSub : Module (NHSub k n S D) (NHRep k n) :=
  Module.compHom (Coinv k n) (nhSubAct k n S D).toRingHom

theorem nhSub_smul_def (T : NHSub k n S D) (v : Coinv k n) :
    T • NHRep.of k n v = NHRep.of k n (nhSubAct k n S D T v) := rfl

@[simp] theorem nhSubAct_mk (T : NHSub k n S D) (p : MvPolynomial (Fin n) k) :
    nhSubAct k n S D T (Submodule.Quotient.mk p) =
      Submodule.Quotient.mk (NHSub.val k n S D T p) := rfl

instance instIsScalarTowerNHSub : IsScalarTower k (NHSub k n S D) (NHRep k n) where
  smul_assoc c T v := by
    show nhSubAct k n S D (c • T) v = c • nhSubAct k n S D T v
    rw [show nhSubAct k n S D (c • T) = c • nhSubAct k n S D T from
      (nhSubAct k n S D).toLinearMap.map_smul c T, LinearMap.smul_apply]

theorem mulX_smul {a : Fin n} (ha : a ∈ S) (v : Coinv k n) :
    (NHSub.mk (mulX_mem_nhSub (k := k) (D := D) ha)) • NHRep.of k n v =
      NHRep.of k n (coinvMul k (X a) v) := by
  obtain ⟨p, rfl⟩ := Submodule.Quotient.mk_surjective _ v
  rfl

theorem mulPoly_smul (p : MvPolynomial (Fin n) k) (v : Coinv k n) :
    (NHSub.mk (mulPoly_mem_nhSub (k := k) (D := D) p)) • NHRep.of k n v =
      NHRep.of k n (coinvMul k p v) := by
  obtain ⟨q, rfl⟩ := Submodule.Quotient.mk_surjective _ v
  rfl

/-! ### The socle -/

/-- On `L_n`, `x_c = -∑_{a ≠ c} x_a` (as `e_1 ∈ Sym⁺`): a vector killed by all `x_a`, `a ≠ c`, is
killed by `x_c`. -/
theorem coinvMul_X_eq_zero_of_forall_ne {c : Fin n} {v : Coinv k n}
    (hv : ∀ a, a ≠ c → coinvMul k (X a) v = 0) : coinvMul k (X c) v = 0 := by
  obtain ⟨q, rfl⟩ := Submodule.Quotient.mk_surjective _ v
  simp only [coinvMul_mk, Submodule.Quotient.mk_eq_zero, mem_coinvSub] at hv ⊢
  have he : esymm (Fin n) k 1 * q ∈ coinvIdeal k n :=
    Ideal.mul_mem_right _ _ (esymm_succ_mem_coinvIdeal n 0)
  have hs : ∑ a ∈ Finset.univ.erase c, X a * q ∈ coinvIdeal k n :=
    Ideal.sum_mem _ fun a ha => hv a (Finset.mem_erase.1 ha).1
  have : X c * q = esymm (Fin n) k 1 * q - ∑ a ∈ Finset.univ.erase c, X a * q := by
    rw [esymm_one, Finset.sum_mul, ← Finset.add_sum_erase _ _ (Finset.mem_univ c)]
    ring
  rw [this]
  exact sub_mem he hs

/-- If `S` omits at most one index, a vector of `L_n` killed by the `x_a`, `a ∈ S`, is killed by
all `x_a`. -/
theorem forall_coinvMul_X_eq_zero (hS : ∀ a b : Fin n, a ≠ b → a ∈ S ∨ b ∈ S)
    {v : Coinv k n} (hv : ∀ a ∈ S, coinvMul k (X a) v = 0) (c : Fin n) :
    coinvMul k (X c) v = 0 := by
  by_cases hc : c ∈ S
  · exact hv c hc
  · exact coinvMul_X_eq_zero_of_forall_ne fun a hac =>
      hv a ((hS a c hac).resolve_right hc)

/-- **KL I Lemma 2.1, applied to `Res`**: if `S` omits at most one index, every nonzero
`nhSub k n S D`-submodule of `L_n` contains `[x^δ]`. -/
theorem xDelta_mem_of_ne_bot (hS : ∀ a b : Fin n, a ≠ b → a ∈ S ∨ b ∈ S)
    {N : Submodule (NHSub k n S D) (NHRep k n)} (hN : N ≠ ⊥) :
    NHRep.of k n (Submodule.Quotient.mk (xDelta n)) ∈ N := by
  obtain ⟨v₀, hv₀, hne⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hN
  obtain ⟨v, hv, hv0, hvx⟩ := exists_ne_zero_forall_eq_zero
    (fun a : S => coinvMul k (X (a : Fin n) : MvPolynomial (Fin n) k)) (n.choose 2)
    (fun ρ hρ => by
      have : (ρ.map fun a : S => coinvMul k (X (a : Fin n) : MvPolynomial (Fin n) k)) =
          ((ρ.map Subtype.val).map fun a => coinvMul k (X a : MvPolynomial (Fin n) k)) := by
        rw [List.map_map]; rfl
      rw [this]
      exact prod_map_coinvMul_eq_zero (by rw [List.length_map]; exact hρ))
    {w : Coinv k n | NHRep.of k n w ∈ N}
    (fun a w hw => by
      show NHRep.of k n (coinvMul k (X (a : Fin n)) w) ∈ N
      rw [← mulX_smul (D := D) a.2]
      exact N.smul_mem _ hw) hv₀ hne
  have hsoc : v ∈ coinvSocle k n :=
    mem_coinvSocle.2 (forall_coinvMul_X_eq_zero hS fun a ha => hvx ⟨a, ha⟩)
  rw [coinvSocle_eq_span_xDelta] at hsoc
  obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.1 hsoc
  have hc : c ≠ 0 := by rintro rfl; exact hv0 (zero_smul _ _)
  have := Submodule.smul_of_tower_mem N c⁻¹ (show NHRep.of k n (c • _) ∈ N from hv)
  rwa [← map_smul, smul_smul, inv_mul_cancel₀ hc, one_smul] at this

variable (k n S D) in
/-- The `nhSub k n S D`-submodule of `L_n` generated by `[x^δ]`; it is the socle of `L_n` when
`S` omits at most one index (`sSup_simple_eq_nhSocle`). -/
noncomputable def nhSocle : Submodule (NHSub k n S D) (NHRep k n) :=
  Submodule.span (NHSub k n S D) {NHRep.of k n (Submodule.Quotient.mk (xDelta n))}

theorem xDelta_mem_nhSocle :
    NHRep.of k n (Submodule.Quotient.mk (xDelta n)) ∈ nhSocle k n S D :=
  Submodule.subset_span rfl

theorem nhSocle_ne_bot : nhSocle k n S D ≠ ⊥ := by
  intro h
  have := h ▸ xDelta_mem_nhSocle (k := k) (n := n) (S := S) (D := D)
  rw [Submodule.mem_bot] at this
  exact mk_xDelta_ne_zero this

/-- The socle is contained in every nonzero submodule. -/
theorem nhSocle_le (hS : ∀ a b : Fin n, a ≠ b → a ∈ S ∨ b ∈ S)
    {N : Submodule (NHSub k n S D) (NHRep k n)} (hN : N ≠ ⊥) : nhSocle k n S D ≤ N := by
  rw [nhSocle, Submodule.span_le, Set.singleton_subset_iff]
  exact xDelta_mem_of_ne_bot hS hN

theorem isAtom_nhSocle (hS : ∀ a b : Fin n, a ≠ b → a ∈ S ∨ b ∈ S) :
    IsAtom (nhSocle k n S D) :=
  ⟨nhSocle_ne_bot, fun N hN => by
    by_contra h
    exact (lt_irrefl _) (lt_of_le_of_lt (nhSocle_le hS h) hN)⟩

/-- **KL I Proposition 3.11 (2), (3), socle part**: the submodule generated by `[x^δ]` is a simple
`nhSub k n S D`-module. -/
theorem isSimpleModule_nhSocle (hS : ∀ a b : Fin n, a ≠ b → a ∈ S ∨ b ∈ S) :
    IsSimpleModule (NHSub k n S D) (nhSocle k n S D) :=
  isSimpleModule_iff_isAtom.2 (isAtom_nhSocle hS)

/-- The socle is the unique simple submodule. -/
theorem isSimpleModule_iff_eq_nhSocle (hS : ∀ a b : Fin n, a ≠ b → a ∈ S ∨ b ∈ S)
    (N : Submodule (NHSub k n S D) (NHRep k n)) :
    IsSimpleModule (NHSub k n S D) N ↔ N = nhSocle k n S D := by
  rw [isSimpleModule_iff_isAtom]
  constructor
  · intro hN
    have hle := nhSocle_le hS hN.1
    exact ((hN.le_iff.1 hle).resolve_left nhSocle_ne_bot).symm
  · rintro rfl
    exact isAtom_nhSocle hS

/-- **KL I Proposition 3.11 (2), (3)**: `soc(Res L_n)`, the sum of all simple submodules, is the
simple module `nhSocle`. -/
theorem sSup_simple_eq_nhSocle (hS : ∀ a b : Fin n, a ≠ b → a ∈ S ∨ b ∈ S) :
    sSup {N : Submodule (NHSub k n S D) (NHRep k n) | IsSimpleModule (NHSub k n S D) N} =
      nhSocle k n S D := by
  have : {N : Submodule (NHSub k n S D) (NHRep k n) | IsSimpleModule (NHSub k n S D) N} =
      {nhSocle k n S D} := by
    ext N
    exact isSimpleModule_iff_eq_nhSocle hS N
  rw [this, sSup_singleton]

theorem univ_hS (a b : Fin n) (_ : a ≠ b) : a ∈ (Set.univ : Set (Fin n)) ∨ b ∈ Set.univ :=
  Or.inl trivial

theorem resNH_hS (a b : Fin n) (hab : a ≠ b) :
    a ∈ {a : Fin n | (a : ℕ) + 1 < n} ∨ b ∈ {a : Fin n | (a : ℕ) + 1 < n} := by
  simp only [Set.mem_setOf_eq]
  have := a.2; have := b.2
  have : (a : ℕ) ≠ b := fun h => hab (Fin.ext h)
  omega

/-! ### Young coinvariants `L_μ = k[x] / (Sym_μ⁺)` -/

/-- The block labelling of a composition; its stabiliser is the Young subgroup `S_μ`. -/
def compLab (μ : List ℕ) : Fin n → ℕ := fun a => blockEnd 0 μ a

variable (k n) in
/-- The augmentation (constant term) of the Young invariants `Sym_μ`. -/
noncomputable def youngAug (μ : List ℕ) : labelInvariants k (compLab (n := n) μ) →ₐ[k] k :=
  (MvPolynomial.aeval fun _ => (0 : k)).comp (labelInvariants k (compLab (n := n) μ)).val

theorem youngAug_apply {μ : List ℕ} (s : labelInvariants k (compLab (n := n) μ)) :
    youngAug k n μ s = constantCoeff (s : MvPolynomial (Fin n) k) := by
  simp [youngAug, MvPolynomial.coe_aeval_eq_eval, MvPolynomial.eval_zero]

variable (k n) in
/-- The subspace `(Sym_μ⁺) = Sym_μ⁺ · k[x]`. -/
noncomputable def youngSub (μ : List ℕ) : Submodule k (MvPolynomial (Fin n) k) :=
  augSubmodule (MvPolynomial (Fin n) k) (youngAug k n μ)

variable (k n) in
/-- **The Young coinvariant algebra** `L_μ = k[x] / (Sym_μ⁺)`, the `NH_μ`-module
`L(i^{μ_1}) ⊗ ⋯ ⊗ L(i^{μ_r})`. -/
abbrev YoungCoinv (μ : List ℕ) : Type _ := MvPolynomial (Fin n) k ⧸ youngSub k n μ

/-- **`dim L_μ = |S_μ|`** (parabolic Artin theorem). -/
theorem finrank_youngCoinv (μ : List ℕ) :
    Module.finrank k (YoungCoinv k n μ) =
      Fintype.card {g : Perm (Fin n) // compLab μ ∘ g = compLab μ} := by
  classical
  obtain ⟨ι, _, hcard, ⟨b⟩⟩ := exists_labelBasis k (compLab (n := n) μ)
  rw [← hcard]
  exact finrank_augQuot b (youngAug k n μ)

instance (μ : List ℕ) : FiniteDimensional k (YoungCoinv k n μ) := by
  classical
  obtain ⟨ι, _, -, ⟨b⟩⟩ := exists_labelBasis k (compLab (n := n) μ)
  exact finiteDimensional_augQuot b (youngAug k n μ)

theorem mul_mem_youngSub {μ : List ℕ} {s : MvPolynomial (Fin n) k}
    (hs : s ∈ labelInvariants k (compLab (n := n) μ)) (hs0 : constantCoeff s = 0)
    (p : MvPolynomial (Fin n) k) : s * p ∈ youngSub k n μ :=
  smul_mem_augSubmodule (r := (⟨s, hs⟩ : labelInvariants k (compLab (n := n) μ)))
    (by rw [youngAug_apply]; exact hs0) p

/-- Young invariants are invariant under `s_j` for `j ∈ compD μ`. -/
theorem rename_swap_of_mem_labelInvariants {μ : List ℕ} {s : MvPolynomial (Fin n) k}
    (hs : s ∈ labelInvariants k (compLab (n := n) μ)) {j : ℕ} (hj : j ∈ compD μ)
    (h : j + 1 < n) : rename (swap (⟨j, by omega⟩ : Fin n) ⟨j + 1, h⟩) s = s := by
  apply hs
  funext c
  simp only [Function.comp_apply, compLab]
  rcases eq_or_ne c ⟨j, by omega⟩ with rfl | h1
  · rw [swap_apply_left]; exact hj
  rcases eq_or_ne c ⟨j + 1, h⟩ with rfl | h2
  · rw [swap_apply_right]; exact hj.symm
  rw [swap_apply_of_ne_of_ne h1 h2]

theorem dd_mul_of_mem_labelInvariants {μ : List ℕ} {s : MvPolynomial (Fin n) k}
    (hs : s ∈ labelInvariants k (compLab (n := n) μ)) {j : ℕ} (hj : j ∈ compD μ)
    (p : MvPolynomial (Fin n) k) : dd k n j (s * p) = s * dd k n j p := by
  by_cases h : j + 1 < n
  · rw [dd_of_lt h]
    exact ddiff_mul_of_rename_eq (by simp [Fin.ext_iff])
      (rename_swap_of_mem_labelInvariants hs hj h) p
  · rw [dd_eq_zero (by omega)]; simp

/-- `NH_μ` preserves `(Sym_μ⁺)`. -/
theorem nhSub_stable_youngSub {μ : List ℕ} {T : Module.End k (MvPolynomial (Fin n) k)}
    (hT : T ∈ nhSub k n S (compD μ)) {p : MvPolynomial (Fin n) k} (hp : p ∈ youngSub k n μ) :
    T p ∈ youngSub k n μ := by
  induction hT using Algebra.adjoin_induction generalizing p with
  | mem y hy =>
    rcases hy with ⟨a, -, rfl⟩ | ⟨j, hj, rfl⟩
    · refine augSubmodule_induction (p := fun p => mulX k n a p ∈ youngSub k n μ) hp ?_ ?_
      · intro r hr m
        show X a * ((r : MvPolynomial (Fin n) k) * m) ∈ youngSub k n μ
        rw [mul_left_comm]
        exact smul_mem_augSubmodule hr _
      · intro x y hx hy
        rw [map_add]; exact add_mem hx hy
    · refine augSubmodule_induction (p := fun p => dd k n j p ∈ youngSub k n μ) hp ?_ ?_
      · intro r hr m
        show dd k n j ((r : MvPolynomial (Fin n) k) * m) ∈ youngSub k n μ
        rw [dd_mul_of_mem_labelInvariants r.2 hj]
        exact smul_mem_augSubmodule hr _
      · intro x y hx hy
        rw [map_add]; exact add_mem hx hy
  | algebraMap r =>
    rw [Module.algebraMap_end_apply]
    exact Submodule.smul_mem _ r hp
  | add x y _ _ hx hy => rw [LinearMap.add_apply]; exact add_mem (hx hp) (hy hp)
  | mul x y _ _ hx hy => rw [Module.End.mul_apply]; exact hx (hy hp)

variable (k n) in
/-- The action of `NH_μ` on `L_μ`. -/
noncomputable def youngAct (μ : List ℕ) : ParNH k n μ →ₐ[k] Module.End k (YoungCoinv k n μ) where
  toFun T := (youngSub k n μ).mapQ (youngSub k n μ) (NHSub.val k n _ _ T)
    fun _ hp => nhSub_stable_youngSub T.2 hp
  map_one' := by ext; simp
  map_mul' T T' := by ext; simp
  map_zero' := by ext; simp
  map_add' T T' := by ext; simp
  commutes' c := by ext; simp [Module.algebraMap_end_apply]

@[simp] theorem youngAct_mk {μ : List ℕ} (T : ParNH k n μ) (p : MvPolynomial (Fin n) k) :
    youngAct k n μ T (Submodule.Quotient.mk p) =
      Submodule.Quotient.mk (NHSub.val k n _ _ T p) := rfl

variable (k n) in
/-- `L_μ` regarded as a module over `NH_μ` (a type synonym for `YoungCoinv k n μ`). -/
def YoungRep (μ : List ℕ) : Type _ := YoungCoinv k n μ

noncomputable instance (μ : List ℕ) : AddCommGroup (YoungRep k n μ) :=
  inferInstanceAs (AddCommGroup (YoungCoinv k n μ))
noncomputable instance (μ : List ℕ) : Module k (YoungRep k n μ) :=
  inferInstanceAs (Module k (YoungCoinv k n μ))
instance (μ : List ℕ) : FiniteDimensional k (YoungRep k n μ) :=
  inferInstanceAs (FiniteDimensional k (YoungCoinv k n μ))

variable (k n) in
/-- The identification `L_μ = YoungRep k n μ`. -/
def YoungRep.of (μ : List ℕ) : YoungCoinv k n μ ≃ₗ[k] YoungRep k n μ := LinearEquiv.refl k _

/-- `L_μ` as a module over `NH_μ`. -/
noncomputable instance (μ : List ℕ) : Module (ParNH k n μ) (YoungRep k n μ) :=
  Module.compHom (YoungCoinv k n μ) (youngAct k n μ).toRingHom

theorem parNH_smul_youngRep {μ : List ℕ} (T : ParNH k n μ) (v : YoungCoinv k n μ) :
    T • YoungRep.of k n μ v = YoungRep.of k n μ (youngAct k n μ T v) := rfl

instance (μ : List ℕ) : IsScalarTower k (ParNH k n μ) (YoungRep k n μ) where
  smul_assoc c T v := by
    show youngAct k n μ (c • T) v = c • youngAct k n μ T v
    rw [show youngAct k n μ (c • T) = c • youngAct k n μ T from
      (youngAct k n μ).toLinearMap.map_smul c T, LinearMap.smul_apply]

end Categorification.NilHecke
