/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.CategoryTheory.Preadditive.Biproducts
import Mathlib.CategoryTheory.Preadditive.AdditiveFunctor
import Mathlib.CategoryTheory.Limits.Preserves.Shapes.Biproducts
import Mathlib.CategoryTheory.IsomorphismClasses
import Mathlib.Algebra.Polynomial.Laurent
import Mathlib.GroupTheory.FreeAbelianGroup

/-!
# The split Grothendieck group of an additive category

M. Khovanov, A. Lauda, *A categorification of quantum `sl(n)`*, arXiv:0807.3250v1, §3.6
(TeX `\subsection{$K_0(\dot{\cal{U}})$ and homomorphism $\gamma$}`): "The split Grothendieck group
`K_0(A)` of an additive category `A` has generators `[P]`, over all objects `P` of `A`, and
relations `[P] = [P'] + [P'']` whenever `P ≅ P' ⊕ P''`."

For a preadditive category `C` with binary biproducts, `SplitK0 C` is the free abelian group on
the isomorphism classes of objects modulo `[X ⊞ Y] = [X] + [Y]`.

## Main definitions and results

* `SplitK0 C`, `SplitK0.of X = [X]`; `of_iso` (isomorphic objects have the same class),
  `of_biprod` (`[X ⊞ Y] = [X] + [Y]`), `of_isZero` (`[0] = 0`), `of_biproduct`
  (`[⨁ f] = ∑ [f i]` for finite biproducts).
* `SplitK0.lift`: an additive invariant of objects (isomorphism invariant, additive on binary
  biproducts) induces an additive map on `K₀`; `SplitK0.lift₂` the same for invariants of pairs
  of objects, additive in each variable (bilinear maps `K₀ C × K₀ D → G`).
* `SplitK0.map F`: the additive map `K₀ C → K₀ D` induced by an additive functor.
* `SplitK0.ShiftData C`: a family of additive self-maps `X ↦ X{n}` on objects, compatible with
  isomorphisms and biproducts, with `X{0} ≅ X` and `X{m + n} ≅ X{m}{n}`; it makes `K₀ C` a
  `ℤ[q, q⁻¹]`-module with `q^n [X] = [X{n}]` (`SplitK0.module`, `SplitK0.T_smul_of`). This is
  KL III (3.65): "multiplication by `q` coming from the grading shift".
-/

noncomputable section

namespace Categorification

open CategoryTheory CategoryTheory.Limits

universe w v u v' u' v'' u''

section Defs

variable (C : Type u) [Category.{v} C] [Preadditive C] [HasBinaryBiproducts C]

namespace SplitK0

/-- Isomorphism classes of objects of `C`. -/
def IsoClass : Type u := Quotient (isIsomorphicSetoid C)

variable {C} in
/-- The isomorphism class of an object. -/
def isoClass (X : C) : IsoClass C := Quotient.mk (isIsomorphicSetoid C) X

/-- The defining relations `[X ⊞ Y] - [X] - [Y]`. -/
def relations : Set (FreeAbelianGroup (IsoClass C)) :=
  {x | ∃ X Y : C, x = .of (isoClass (X ⊞ Y)) - .of (isoClass X) - .of (isoClass Y)}

/-- The subgroup generated by the relations. -/
def relSubgroup : AddSubgroup (FreeAbelianGroup (IsoClass C)) :=
  AddSubgroup.closure (relations C)

end SplitK0

/-- **The split Grothendieck group** `K₀(C)` of a preadditive category with binary biproducts:
the free abelian group on isomorphism classes of objects modulo `[X ⊞ Y] = [X] + [Y]`. -/
def SplitK0 : Type u := FreeAbelianGroup (SplitK0.IsoClass C) ⧸ SplitK0.relSubgroup C

namespace SplitK0

instance : AddCommGroup (SplitK0 C) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup (IsoClass C) ⧸ relSubgroup C))

/-- The quotient map. -/
def mk : FreeAbelianGroup (IsoClass C) →+ SplitK0 C := QuotientAddGroup.mk' _

variable {C}

theorem mk_surjective : Function.Surjective (mk C) := QuotientAddGroup.mk'_surjective _

omit [Preadditive C] [HasBinaryBiproducts C] in
theorem isoClass_surjective : Function.Surjective (isoClass (C := C)) := Quotient.mk_surjective

/-- The class `[X] ∈ K₀(C)`. -/
def of (X : C) : SplitK0 C := mk C (FreeAbelianGroup.of (isoClass X))

omit [Preadditive C] [HasBinaryBiproducts C] in
theorem isoClass_eq {X Y : C} (e : X ≅ Y) : isoClass X = isoClass Y := Quotient.sound ⟨e⟩

/-- Isomorphic objects have the same class. -/
theorem of_iso {X Y : C} (e : X ≅ Y) : of X = of Y := by
  rw [of, of, isoClass_eq e]

theorem of_eq_of_nonempty {X Y : C} (e : Nonempty (X ≅ Y)) : of X = of Y :=
  of_iso e.some

/-- `[X ⊞ Y] = [X] + [Y]`. -/
theorem of_biprod (X Y : C) : of (X ⊞ Y) = of X + of Y := by
  have h : FreeAbelianGroup.of (isoClass (X ⊞ Y)) - FreeAbelianGroup.of (isoClass X) -
      FreeAbelianGroup.of (isoClass Y) ∈ relSubgroup C :=
    AddSubgroup.subset_closure ⟨X, Y, rfl⟩
  rw [← QuotientAddGroup.eq_zero_iff] at h
  change mk C _ = 0 at h
  rw [map_sub, map_sub, sub_sub, sub_eq_zero] at h
  exact h

/-- `[X] = [Y] + [Z]` whenever `X ≅ Y ⊞ Z` (KL III (3.63)–(3.64)). -/
theorem of_eq_add_of_iso {X Y Z : C} (e : X ≅ Y ⊞ Z) : of X = of Y + of Z := by
  rw [of_iso e, of_biprod]

/-- The class of a zero object is `0`. -/
theorem of_isZero {X : C} (h : IsZero X) : of X = 0 := by
  have := of_iso (isoBiprodZero (X := X) h)
  rw [of_biprod] at this
  exact (left_eq_add.1 this)

/-- Additive maps out of `K₀` are determined by their values on classes. -/
theorem hom_ext {G : Type*} [AddCommGroup G] {f g : SplitK0 C →+ G}
    (h : ∀ X : C, f (of X) = g (of X)) : f = g := by
  refine QuotientAddGroup.addMonoidHom_ext _ (FreeAbelianGroup.lift.ext _ _ fun c => ?_)
  obtain ⟨X, rfl⟩ := isoClass_surjective c
  exact h X

/-- Induction principle on `K₀`. -/
@[elab_as_elim]
theorem induction_on {motive : SplitK0 C → Prop} (x : SplitK0 C) (of : ∀ X, motive (of X))
    (zero : motive 0) (add : ∀ x y, motive x → motive y → motive (x + y))
    (neg : ∀ x, motive x → motive (-x)) : motive x := by
  obtain ⟨y, rfl⟩ := mk_surjective x
  induction y using FreeAbelianGroup.induction_on with
  | C0 => simpa using zero
  | C1 c =>
    obtain ⟨X, rfl⟩ := isoClass_surjective c
    exact of X
  | Cn c h => simpa using neg _ h
  | Cp y z hy hz => simpa using add _ _ hy hz

section Lift

variable {G : Type*} [AddCommGroup G]

/-- **The universal property of `K₀`**: an isomorphism-invariant function on objects which is
additive on binary biproducts induces an additive map `K₀(C) → G`. -/
def lift (f : C → G) (hf : ∀ X Y : C, (X ≅ Y) → f X = f Y)
    (hadd : ∀ X Y : C, f (X ⊞ Y) = f X + f Y) : SplitK0 C →+ G :=
  QuotientAddGroup.lift _ (FreeAbelianGroup.lift (Quotient.lift f fun _ _ ⟨e⟩ => hf _ _ e)) <| by
    rw [relSubgroup, AddSubgroup.closure_le]
    rintro _ ⟨X, Y, rfl⟩
    simp only [SetLike.mem_coe, AddMonoidHom.mem_ker, map_sub, FreeAbelianGroup.lift.of]
    change f (X ⊞ Y) - f X - f Y = 0
    rw [hadd, sub_sub, sub_self]

@[simp] theorem lift_of (f : C → G) (hf : ∀ X Y : C, (X ≅ Y) → f X = f Y)
    (hadd : ∀ X Y : C, f (X ⊞ Y) = f X + f Y) (X : C) : lift f hf hadd (of X) = f X := by
  change QuotientAddGroup.lift _ _ _ (QuotientAddGroup.mk _) = _
  rw [QuotientAddGroup.lift_mk, FreeAbelianGroup.lift.of]
  rfl

end Lift

section Lift₂

variable {D : Type u'} [Category.{v'} D] [Preadditive D] [HasBinaryBiproducts D]
  {G : Type*} [AddCommGroup G]

/-- An invariant of pairs of objects, isomorphism invariant and additive on binary biproducts in
each variable, induces a biadditive map `K₀(C) × K₀(D) → G`. -/
def lift₂ (f : C → D → G) (hf₁ : ∀ (X X' : C) (Y : D), (X ≅ X') → f X Y = f X' Y)
    (hf₂ : ∀ (X : C) (Y Y' : D), (Y ≅ Y') → f X Y = f X Y')
    (hadd₁ : ∀ (X X' : C) (Y : D), f (X ⊞ X') Y = f X Y + f X' Y)
    (hadd₂ : ∀ (X : C) (Y Y' : D), f X (Y ⊞ Y') = f X Y + f X Y') :
    SplitK0 C →+ SplitK0 D →+ G :=
  lift (fun X => lift (f X) (hf₂ X) (hadd₂ X))
    (fun X X' e => hom_ext fun Y => by rw [lift_of, lift_of, hf₁ X X' Y e])
    (fun X X' => hom_ext fun Y => by
      rw [AddMonoidHom.add_apply, lift_of, lift_of, lift_of, hadd₁])

@[simp] theorem lift₂_of (f : C → D → G) (hf₁ : ∀ (X X' : C) (Y : D), (X ≅ X') → f X Y = f X' Y)
    (hf₂ : ∀ (X : C) (Y Y' : D), (Y ≅ Y') → f X Y = f X Y')
    (hadd₁ : ∀ (X X' : C) (Y : D), f (X ⊞ X') Y = f X Y + f X' Y)
    (hadd₂ : ∀ (X : C) (Y Y' : D), f X (Y ⊞ Y') = f X Y + f X Y') (X : C) (Y : D) :
    lift₂ f hf₁ hf₂ hadd₁ hadd₂ (of X) (of Y) = f X Y := by
  rw [lift₂, lift_of, lift_of]

end Lift₂

section Map

variable {D : Type u'} [Category.{v'} D] [Preadditive D] [HasBinaryBiproducts D]

/-- The additive map `K₀(C) → K₀(D)`, `[X] ↦ [F X]`, induced by an additive functor. -/
def map (F : C ⥤ D) [F.Additive] : SplitK0 C →+ SplitK0 D :=
  lift (fun X => of (F.obj X)) (fun _ _ e => of_iso (F.mapIso e))
    (fun X Y => by
      haveI : PreservesBinaryBiproducts F := preservesBinaryBiproducts_of_preservesBiproducts F
      exact (of_iso (F.mapBiprod X Y)).trans (of_biprod _ _))

@[simp] theorem map_of (F : C ⥤ D) [F.Additive] (X : C) : map F (of X) = of (F.obj X) := by
  rw [map, lift_of]

end Map

section Biproduct

variable [HasFiniteBiproducts C]

/-- `⨁_j f_j ≅ f_a ⊞ ⨁_{j ≠ a} f_j`. -/
@[simps]
def biproductSplitIso {ι : Type} [Fintype ι] [DecidableEq ι] (f : ι → C) (a : ι) :
    ⨁ f ≅ f a ⊞ ⨁ (fun j : {j // j ≠ a} => f j) where
  hom := biprod.lift (biproduct.π f a) (biproduct.lift fun j => biproduct.π f j.1)
  inv := biprod.desc (biproduct.ι f a) (biproduct.desc fun j => biproduct.ι f j.1)
  hom_inv_id := by
    rw [biprod.lift_desc, biproduct.lift_desc, ← biproduct.total (f := f),
      ← Finset.add_sum_erase _ _ (Finset.mem_univ a)]
    congr 1
    exact (Finset.sum_subtype (p := fun x => x ≠ a) (Finset.univ.erase a) (fun x => by simp)
      (fun j => biproduct.π f j ≫ biproduct.ι f j)).symm
  inv_hom_id := by
    apply biprod.hom_ext'
    · rw [biprod.inl_desc_assoc, Category.comp_id]
      apply biprod.hom_ext
      · rw [Category.assoc, biprod.lift_fst, biprod.inl_fst, biproduct.ι_π_self]
      · rw [Category.assoc, biprod.lift_snd, biprod.inl_snd]
        apply biproduct.hom_ext
        intro j
        rw [Category.assoc, biproduct.lift_π, biproduct.ι_π_ne _ (Ne.symm j.2), zero_comp]
    · rw [biprod.inr_desc_assoc, Category.comp_id]
      apply biprod.hom_ext
      · rw [Category.assoc, biprod.lift_fst, biprod.inr_fst]
        apply biproduct.hom_ext'
        intro j
        rw [biproduct.ι_desc_assoc, biproduct.ι_π_ne _ j.2, comp_zero]
      · rw [Category.assoc, biprod.lift_snd, biprod.inr_snd]
        apply biproduct.hom_ext'
        intro j
        apply biproduct.hom_ext
        intro j'
        rw [biproduct.ι_desc_assoc, Category.assoc, biproduct.lift_π, Category.comp_id]
        by_cases h : j = j'
        · subst h
          rw [biproduct.ι_π_self, biproduct.ι_π_self]
        · rw [biproduct.ι_π_ne _ h, biproduct.ι_π_ne _ (fun h' => h (Subtype.ext h'))]

theorem of_biproduct_aux : ∀ (n : ℕ) (ι : Type) [Fintype ι] (f : ι → C),
    Fintype.card ι = n → of (⨁ f) = ∑ j, of (f j) := by
  intro n
  induction n with
  | zero =>
    intro ι _ f hn
    haveI : IsEmpty ι := Fintype.card_eq_zero_iff.1 hn
    rw [Finset.univ_eq_empty, Finset.sum_empty]
    refine of_isZero ?_
    rw [IsZero.iff_id_eq_zero, ← biproduct.total]
    simp
  | succ n ih =>
    intro ι _ f hn
    classical
    have hne : Nonempty ι := Fintype.card_pos_iff.1 (by omega)
    obtain ⟨a⟩ := hne
    have hc : Fintype.card {j // j ≠ a} = n := by
      rw [Fintype.card_subtype_compl, Fintype.card_subtype_eq, hn]
      rfl
    rw [of_iso (biproductSplitIso f a), of_biprod, ih _ _ hc,
      ← Finset.add_sum_erase _ _ (Finset.mem_univ a)]
    congr 1
    exact (Finset.sum_subtype (p := fun x => x ≠ a) (Finset.univ.erase a) (fun x => by simp)
      (fun j => of (f j))).symm

/-- **`[⨁_j f_j] = ∑_j [f_j]`** for finite biproducts. -/
theorem of_biproduct {ι : Type} [Fintype ι] (f : ι → C) : of (⨁ f) = ∑ j, of (f j) :=
  of_biproduct_aux _ ι f rfl

end Biproduct

/-! ### Grading shifts and the `ℤ[q, q⁻¹]`-module structure -/

/-- **Shift data** on `C`: self-maps `X ↦ X{n}` of objects (for instance the objects of a family of
additive shift functors) which respect isomorphisms and binary biproducts, with `X{0} ≅ X` and
`X{m + n} ≅ X{m}{n}`. -/
class K0Shift (C : Type u) [Category.{v} C] [Preadditive C] [HasBinaryBiproducts C] where
  /-- The shift `X ↦ X{n}`. -/
  sh : ℤ → C → C
  sh_iso : ∀ (n : ℤ) {X Y : C}, (X ≅ Y) → Nonempty (sh n X ≅ sh n Y)
  sh_biprod : ∀ (n : ℤ) (X Y : C), Nonempty (sh n (X ⊞ Y) ≅ sh n X ⊞ sh n Y)
  sh_zero : ∀ X : C, Nonempty (sh 0 X ≅ X)
  sh_add : ∀ (m n : ℤ) (X : C), Nonempty (sh (m + n) X ≅ sh n (sh m X))

section Shift

variable [K0Shift C]

open K0Shift

/-- The grading shift `{n}` on `K₀`. -/
def shiftHom (n : ℤ) : SplitK0 C →+ SplitK0 C :=
  lift (fun X => of (sh n X)) (fun _ _ e => of_eq_of_nonempty (sh_iso n e))
    (fun X Y => (of_eq_of_nonempty (sh_biprod n X Y)).trans (of_biprod _ _))

@[simp] theorem shiftHom_of (n : ℤ) (X : C) : shiftHom n (of X) = of (sh n X) := by
  rw [shiftHom, lift_of]

theorem shiftHom_zero : shiftHom (0 : ℤ) = AddMonoidHom.id (SplitK0 C) :=
  hom_ext fun X => by rw [shiftHom_of, AddMonoidHom.id_apply, of_eq_of_nonempty (sh_zero X)]

theorem shiftHom_add (m n : ℤ) : shiftHom (m + n) = (shiftHom n).comp (shiftHom (C := C) m) :=
  hom_ext fun X => by
    rw [AddMonoidHom.comp_apply, shiftHom_of, shiftHom_of, shiftHom_of,
      of_eq_of_nonempty (sh_add m n X)]

/-- The action of `q^n` as an element of `End(K₀)`. -/
def qPow : Multiplicative ℤ →* Module.End ℤ (SplitK0 C) where
  toFun a := (shiftHom (Multiplicative.toAdd a)).toIntLinearMap
  map_one' := by
    ext x
    simp [shiftHom_zero]
  map_mul' a b := by
    ext x
    simp only [toAdd_mul, AddMonoidHom.coe_toIntLinearMap, Module.End.mul_apply]
    rw [add_comm, shiftHom_add]
    rfl

/-- **`K₀(C)` is a `ℤ[q, q⁻¹]`-module**, `q` acting by the grading shift `{1}` (KL III (3.65)). -/
instance module : Module (LaurentPolynomial ℤ) (SplitK0 C) :=
  Module.compHom (SplitK0 C) (AddMonoidAlgebra.lift ℤ ℤ (Module.End ℤ (SplitK0 C)) qPow).toRingHom

theorem smul_def (p : LaurentPolynomial ℤ) (x : SplitK0 C) :
    p • x = AddMonoidAlgebra.lift ℤ ℤ (Module.End ℤ (SplitK0 C)) qPow p x := rfl

/-- `q^n • x = x{n}`. -/
theorem T_smul (n : ℤ) (x : SplitK0 C) :
    (LaurentPolynomial.T n : LaurentPolynomial ℤ) • x = shiftHom n x := by
  rw [smul_def, LaurentPolynomial.T, AddMonoidAlgebra.lift_single, one_smul]
  rfl

/-- `q^n [X] = [X{n}]`. -/
theorem T_smul_of (n : ℤ) (X : C) :
    (LaurentPolynomial.T n : LaurentPolynomial ℤ) • of X = of (sh n X) := by
  rw [T_smul, shiftHom_of]

/-- `(a q^n) • x = a • x{n}`. -/
theorem C_mul_T_smul (n a : ℤ) (x : SplitK0 C) :
    (LaurentPolynomial.C a * LaurentPolynomial.T n : LaurentPolynomial ℤ) • x =
      a • shiftHom n x := by
  rw [← LaurentPolynomial.single_eq_C_mul_T, smul_def]
  erw [AddMonoidAlgebra.lift_single]
  rfl

/-- `C a • x = a • x` for `a ∈ ℤ`. -/
theorem C_smul (a : ℤ) (x : SplitK0 C) : (LaurentPolynomial.C a : LaurentPolynomial ℤ) • x = a • x := by
  have := C_mul_T_smul 0 a x
  rwa [LaurentPolynomial.T_zero, mul_one, shiftHom_zero, AddMonoidHom.id_apply] at this

/-- An additive map between `K₀`-groups with shifts commuting with all shifts is
`ℤ[q, q⁻¹]`-linear. -/
def linearOfShift {D : Type u'} [Category.{v'} D] [Preadditive D] [HasBinaryBiproducts D]
    [K0Shift D] (f : SplitK0 C →+ SplitK0 D)
    (hf : ∀ (n : ℤ) (X : C), f (of (sh n X)) = shiftHom n (f (of X))) :
    SplitK0 C →ₗ[LaurentPolynomial ℤ] SplitK0 D where
  __ := f
  map_smul' p x := by
    have hc : ∀ n : ℤ, f.comp (shiftHom n) = (shiftHom (C := D) n).comp f := fun n =>
      hom_ext fun X => by
        rw [AddMonoidHom.comp_apply, AddMonoidHom.comp_apply, shiftHom_of, hf]
    induction p using LaurentPolynomial.induction_on' with
    | add p q hp hq =>
      simp only [AddMonoidHom.toFun_eq_coe, RingHom.id_apply, add_smul, map_add] at hp hq ⊢
      rw [hp, hq]
    | C_mul_T n a =>
      simp only [AddMonoidHom.toFun_eq_coe, RingHom.id_apply]
      rw [C_mul_T_smul, C_mul_T_smul, map_zsmul,
        ← AddMonoidHom.comp_apply, hc, AddMonoidHom.comp_apply]

@[simp] theorem linearOfShift_apply {D : Type u'} [Category.{v'} D] [Preadditive D]
    [HasBinaryBiproducts D] [K0Shift D] (f : SplitK0 C →+ SplitK0 D)
    (hf : ∀ (n : ℤ) (X : C), f (of (sh n X)) = shiftHom n (f (of X))) (x : SplitK0 C) :
    linearOfShift f hf x = f x := rfl

end Shift

end SplitK0

end Defs

end Categorification
