/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib

/-!
# Words in adjacent transpositions

Basic definitions for the symmetric group `Equiv.Perm (Fin m)` viewed through its
adjacent transpositions. Letters of words are natural numbers: the letter `k` stands
for the transposition `s_k` of the positions `k` and `k + 1` (zero-indexed), and is
*valid* for `Fin m` when `k + 1 < m`. Out-of-range letters act trivially.

Using `ℕ` as the letter type (rather than `Fin (m - 1)`) makes words for `S_m`
literally words for `S_{m+1}`, which is convenient for inductions on `m`.

## Main definitions

* `TypeA.sadj m k` : the adjacent transposition `s_k` of `Fin m`.
* `TypeA.wordProd m ρ` : the product `s_{ρ₀} * s_{ρ₁} * ⋯` of a word.
* `TypeA.ValidWord m ρ` : all letters are in range.
* `TypeA.length m w` : the Coxeter length (minimal length of a valid word).
* `TypeA.IsReduced m ρ` : `ρ` is a valid word whose length is `length m (wordProd m ρ)`.
* `TypeA.BraidStep`, `TypeA.BraidEquiv` : braid moves and the equivalence they generate.
* `TypeA.HasRepeat ρ` : `ρ` contains two equal adjacent letters.

## Main results

* `TypeA.sadj_mul_self`, `TypeA.sadj_comm`, `TypeA.sadj_braid` : the Coxeter relations
  (the braid relation needs `a + 2 < m`; it fails when only `a` is in range).
* `TypeA.wordProd_append`, `TypeA.sign_wordProd`, `TypeA.wordProd_repeat`.
* `TypeA.BraidEquiv.wordProd_eq`, `TypeA.BraidEquiv.length_eq`,
  `TypeA.BraidEquiv.validWord_iff` : invariants of braid equivalence.
* `TypeA.BraidEquiv.append` : braid equivalence is a congruence for concatenation;
  `TypeA.braidEquiv_comm`, `TypeA.braidEquiv_braid(_symm)` give the moves in both directions and
  `TypeA.braidEquiv_append_singleton_of_distant` moves a letter across a block of distant
  letters.

See `TypeA.Length`, `TypeA.Inversions`, `TypeA.NormalForm` and `TypeA.Matsumoto` for the
length function, inversions, canonical reduced words and Matsumoto's theorem.
-/

namespace Categorification.TypeA

open Equiv

/-- The adjacent transposition `s_k = (k, k+1)` of `Fin m`; the identity if `k + 1 ≥ m`. -/
def sadj (m k : ℕ) : Perm (Fin m) :=
  if h : k + 1 < m then swap ⟨k, by omega⟩ ⟨k + 1, h⟩ else 1

/-- The permutation `s_{ρ₀} * s_{ρ₁} * ⋯ * s_{ρ_{r-1}}` represented by a word `ρ`. -/
def wordProd (m : ℕ) (ρ : List ℕ) : Perm (Fin m) :=
  (ρ.map (sadj m)).prod

/-- A word is valid for `Fin m` if all its letters `k` satisfy `k + 1 < m`. -/
def ValidWord (m : ℕ) (ρ : List ℕ) : Prop :=
  ∀ k ∈ ρ, k + 1 < m

/-- One braid move: a commutation `ab ↔ ba` of distant letters (`a + 1 < b`), or a braid
relation `a(a+1)a ↔ (a+1)a(a+1)`, applied inside a word. Stated in one direction; see
`BraidEquiv` for the generated equivalence relation. -/
inductive BraidStep : List ℕ → List ℕ → Prop
  | comm (α β : List ℕ) {a b : ℕ} (h : a + 1 < b) :
      BraidStep (α ++ [a, b] ++ β) (α ++ [b, a] ++ β)
  | braid (α β : List ℕ) (a : ℕ) :
      BraidStep (α ++ [a, a + 1, a] ++ β) (α ++ [a + 1, a, a + 1] ++ β)

/-- Braid equivalence of words: the equivalence relation generated by braid moves. -/
def BraidEquiv : List ℕ → List ℕ → Prop :=
  Relation.EqvGen BraidStep

/-- A word contains two equal adjacent letters. -/
def HasRepeat (ρ : List ℕ) : Prop :=
  ∃ (α β : List ℕ) (a : ℕ), ρ = α ++ [a, a] ++ β

/-- Every permutation of `Fin m` is a product of adjacent transpositions. -/
theorem exists_validWord (m : ℕ) (w : Perm (Fin m)) :
    ∃ ρ, ValidWord m ρ ∧ wordProd m ρ = w := by
  rcases m with _ | n
  · exact ⟨[], by simp [ValidWord], Subsingleton.elim _ _⟩
  have hw : w ∈ Submonoid.closure (Set.range fun i : Fin n ↦ swap i.castSucc i.succ) := by
    rw [Perm.mclosure_swap_castSucc_succ]; trivial
  induction hw using Submonoid.closure_induction with
  | mem y hy =>
    obtain ⟨i, rfl⟩ := hy
    refine ⟨[i.val], by simp [ValidWord], ?_⟩
    simp only [wordProd, List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one,
      sadj, dif_pos (show i.val + 1 < n + 1 by omega)]
    rfl
  | one => exact ⟨[], by simp [ValidWord], rfl⟩
  | mul y z _ _ hy hz =>
    obtain ⟨ρ, hρ, rfl⟩ := hy
    obtain ⟨σ, hσ, rfl⟩ := hz
    refine ⟨ρ ++ σ, fun k hk => ?_, by simp [wordProd]⟩
    rcases List.mem_append.1 hk with h | h
    exacts [hρ k h, hσ k h]

open Classical in
/-- The Coxeter length of `w`: the minimal length of a valid word representing `w`. -/
noncomputable def length (m : ℕ) (w : Perm (Fin m)) : ℕ :=
  Nat.find (p := fun n => ∃ ρ, ValidWord m ρ ∧ wordProd m ρ = w ∧ ρ.length = n)
    (by obtain ⟨ρ, hv, hw⟩ := exists_validWord m w; exact ⟨_, ρ, hv, hw, rfl⟩)

/-- A reduced word: a valid word of minimal length for the permutation it represents. -/
def IsReduced (m : ℕ) (ρ : List ℕ) : Prop :=
  ValidWord m ρ ∧ ρ.length = length m (wordProd m ρ)

/-! ## Adjacent transpositions as permutations -/

/-- The transposition `k ↔ k + 1` of `ℕ`, as a plain function. It computes the values of
`sadj` (see `sadj_val`). -/
def swapNat (k x : ℕ) : ℕ := if x = k then k + 1 else if x = k + 1 then k else x

theorem swapNat_cases (k x : ℕ) :
    (x = k ∧ swapNat k x = k + 1) ∨ (x = k + 1 ∧ swapNat k x = k) ∨
      (x ≠ k ∧ x ≠ k + 1 ∧ swapNat k x = x) := by
  unfold swapNat; split_ifs <;> omega

theorem sadj_of_not_lt {m k : ℕ} (h : ¬ k + 1 < m) : sadj m k = 1 := by
  simp [sadj, h]

theorem sadj_val_of_lt {m k : ℕ} (h : k + 1 < m) (i : Fin m) :
    (sadj m k i : ℕ) = swapNat k i := by
  unfold sadj swapNat
  simp only [dif_pos h, swap_apply_def, Fin.ext_iff]
  split_ifs <;> simp_all

/-- The value of `sadj m k` at `i`, as a natural number. -/
theorem sadj_val (m k : ℕ) (i : Fin m) :
    (sadj m k i : ℕ) = if k + 1 < m then swapNat k i else i := by
  split_ifs with h
  · exact sadj_val_of_lt h i
  · simp [sadj_of_not_lt h]

/-- `sadj m k` fixes every point other than `k` and `k + 1`. -/
theorem sadj_apply_of_ne {m k : ℕ} (i : Fin m) (h1 : (i : ℕ) ≠ k) (h2 : (i : ℕ) ≠ k + 1) :
    sadj m k i = i := by
  ext; rw [sadj_val]; split_ifs <;> simp [swapNat, h1, h2]

theorem sadj_apply_left {m k : ℕ} (h : k + 1 < m) :
    sadj m k ⟨k, by omega⟩ = ⟨k + 1, h⟩ := by
  ext; rw [sadj_val_of_lt h]; simp [swapNat]

theorem sadj_apply_right {m k : ℕ} (h : k + 1 < m) :
    sadj m k ⟨k + 1, h⟩ = ⟨k, by omega⟩ := by
  ext; rw [sadj_val_of_lt h]; simp [swapNat]

/-- Adjacent transpositions are involutions. -/
@[simp] theorem sadj_mul_self (m k : ℕ) : sadj m k * sadj m k = 1 := by
  by_cases h : k + 1 < m
  · ext i
    simp only [Perm.mul_apply, sadj_val_of_lt h, Perm.one_apply]
    have h1 := swapNat_cases k i
    have h2 := swapNat_cases k (swapNat k i)
    generalize swapNat k (swapNat k i) = y at *
    generalize swapNat k i = x at *
    omega
  · simp [sadj_of_not_lt h]

@[simp] theorem sadj_inv (m k : ℕ) : (sadj m k)⁻¹ = sadj m k :=
  inv_eq_of_mul_eq_one_left (sadj_mul_self m k)

@[simp] theorem sadj_sadj_apply (m k : ℕ) (i : Fin m) : sadj m k (sadj m k i) = i := by
  rw [← Perm.mul_apply, sadj_mul_self, Perm.one_apply]

/-- Distant adjacent transpositions commute (this also holds when a letter is out of range). -/
theorem sadj_comm (m : ℕ) {a b : ℕ} (h : a + 1 < b ∨ b + 1 < a) :
    sadj m a * sadj m b = sadj m b * sadj m a := by
  by_cases ha : a + 1 < m
  · by_cases hb : b + 1 < m
    · ext i
      simp only [Perm.mul_apply, sadj_val_of_lt ha, sadj_val_of_lt hb]
      have h1 := swapNat_cases b i
      have h2 := swapNat_cases a (swapNat b i)
      have h3 := swapNat_cases a i
      have h4 := swapNat_cases b (swapNat a i)
      generalize swapNat a (swapNat b i) = y2 at *
      generalize swapNat b (swapNat a i) = z2 at *
      generalize swapNat b i = y1 at *
      generalize swapNat a i = z1 at *
      omega
    · simp [sadj_of_not_lt hb]
  · simp [sadj_of_not_lt ha]

/-- The braid relation `s_a s_{a+1} s_a = s_{a+1} s_a s_{a+1}` (for letters in range). -/
theorem sadj_braid {m a : ℕ} (h : a + 2 < m) :
    sadj m a * sadj m (a + 1) * sadj m a = sadj m (a + 1) * sadj m a * sadj m (a + 1) := by
  have ha : a + 1 < m := by omega
  have hb : a + 1 + 1 < m := by omega
  ext i
  simp only [Perm.mul_apply, sadj_val_of_lt ha, sadj_val_of_lt hb]
  have h1 := swapNat_cases a i
  have h2 := swapNat_cases (a + 1) (swapNat a i)
  have h3 := swapNat_cases a (swapNat (a + 1) (swapNat a i))
  have h4 := swapNat_cases (a + 1) i
  have h5 := swapNat_cases a (swapNat (a + 1) i)
  have h6 := swapNat_cases (a + 1) (swapNat a (swapNat (a + 1) i))
  generalize swapNat a (swapNat (a + 1) (swapNat a i)) = y3 at *
  generalize swapNat (a + 1) (swapNat a (swapNat (a + 1) i)) = z3 at *
  generalize swapNat (a + 1) (swapNat a i) = y2 at *
  generalize swapNat a (swapNat (a + 1) i) = z2 at *
  generalize swapNat a i = y1 at *
  generalize swapNat (a + 1) i = z1 at *
  omega

theorem sign_sadj {m k : ℕ} (h : k + 1 < m) : Perm.sign (sadj m k) = -1 := by
  rw [sadj, dif_pos h, Perm.sign_swap]
  simp [Fin.ext_iff]

/-! ## Words -/

@[simp] theorem wordProd_nil (m : ℕ) : wordProd m [] = 1 := rfl

@[simp] theorem wordProd_cons (m k : ℕ) (ρ : List ℕ) :
    wordProd m (k :: ρ) = sadj m k * wordProd m ρ := by
  simp [wordProd]

@[simp] theorem wordProd_append (m : ℕ) (ρ σ : List ℕ) :
    wordProd m (ρ ++ σ) = wordProd m ρ * wordProd m σ := by
  simp [wordProd]

theorem wordProd_singleton (m k : ℕ) : wordProd m [k] = sadj m k := by
  simp

theorem wordProd_reverse (m : ℕ) (ρ : List ℕ) : wordProd m ρ.reverse = (wordProd m ρ)⁻¹ := by
  induction ρ with
  | nil => simp
  | cons k ρ ih => simp [ih]

@[simp] theorem validWord_nil (m : ℕ) : ValidWord m [] := by
  simp [ValidWord]

@[simp] theorem validWord_cons {m k : ℕ} {ρ : List ℕ} :
    ValidWord m (k :: ρ) ↔ k + 1 < m ∧ ValidWord m ρ := by
  simp [ValidWord]

@[simp] theorem validWord_append {m : ℕ} {ρ σ : List ℕ} :
    ValidWord m (ρ ++ σ) ↔ ValidWord m ρ ∧ ValidWord m σ := by
  simp only [ValidWord, List.mem_append]
  exact ⟨fun h => ⟨fun k hk => h k (Or.inl hk), fun k hk => h k (Or.inr hk)⟩,
    fun h k hk => hk.elim (h.1 k) (h.2 k)⟩

theorem validWord_reverse {m : ℕ} {ρ : List ℕ} : ValidWord m ρ.reverse ↔ ValidWord m ρ := by
  simp [ValidWord]

/-- A valid word of length `r` represents a permutation of sign `(-1)^r`. -/
theorem sign_wordProd {m : ℕ} {ρ : List ℕ} (hv : ValidWord m ρ) :
    Perm.sign (wordProd m ρ) = (-1) ^ ρ.length := by
  induction ρ with
  | nil => simp
  | cons k ρ ih =>
    rw [validWord_cons] at hv
    rw [wordProd_cons, map_mul, sign_sadj hv.1, ih hv.2, List.length_cons, pow_succ']

/-! ## Braid moves -/

theorem BraidStep.append_left {ρ σ : List ℕ} (h : BraidStep ρ σ) (γ : List ℕ) :
    BraidStep (γ ++ ρ) (γ ++ σ) := by
  cases h with
  | comm α β h => simpa using BraidStep.comm (γ ++ α) β h
  | braid α β a => simpa using BraidStep.braid (γ ++ α) β a

theorem BraidStep.append_right {ρ σ : List ℕ} (h : BraidStep ρ σ) (γ : List ℕ) :
    BraidStep (ρ ++ γ) (σ ++ γ) := by
  cases h with
  | comm α β h => simpa using BraidStep.comm α (β ++ γ) h
  | braid α β a => simpa using BraidStep.braid α (β ++ γ) a

theorem BraidStep.length_eq {ρ σ : List ℕ} (h : BraidStep ρ σ) : ρ.length = σ.length := by
  cases h <;> simp

theorem BraidStep.mem_iff {ρ σ : List ℕ} (h : BraidStep ρ σ) (x : ℕ) : x ∈ ρ ↔ x ∈ σ := by
  cases h <;> simp only [List.mem_append, List.mem_cons, List.not_mem_nil] <;> tauto

theorem BraidStep.validWord_iff {m : ℕ} {ρ σ : List ℕ} (h : BraidStep ρ σ) :
    ValidWord m ρ ↔ ValidWord m σ := by
  simp only [ValidWord, h.mem_iff]

/-- Braid moves between valid words do not change the represented permutation. -/
theorem BraidStep.wordProd_eq {m : ℕ} {ρ σ : List ℕ} (h : BraidStep ρ σ) (hv : ValidWord m ρ) :
    wordProd m ρ = wordProd m σ := by
  cases h with
  | comm α β h =>
    simp only [wordProd_append, wordProd_cons, wordProd_nil, mul_one]
    rw [sadj_comm m (Or.inl h)]
  | braid α β a =>
    have ha : a + 2 < m := by
      have := hv (a + 1) (by simp)
      omega
    simp only [wordProd_append, wordProd_cons, wordProd_nil, mul_one]
    rw [← mul_assoc (sadj m a), ← mul_assoc (sadj m (a + 1)), sadj_braid ha]

theorem BraidEquiv.refl (ρ : List ℕ) : BraidEquiv ρ ρ := Relation.EqvGen.refl ρ

theorem BraidEquiv.symm {ρ σ : List ℕ} (h : BraidEquiv ρ σ) : BraidEquiv σ ρ :=
  Relation.EqvGen.symm _ _ h

theorem BraidEquiv.trans {ρ σ τ : List ℕ} (h₁ : BraidEquiv ρ σ) (h₂ : BraidEquiv σ τ) :
    BraidEquiv ρ τ :=
  Relation.EqvGen.trans _ _ _ h₁ h₂

theorem BraidEquiv.equivalence : Equivalence BraidEquiv :=
  Relation.EqvGen.is_equivalence _

theorem BraidStep.braidEquiv {ρ σ : List ℕ} (h : BraidStep ρ σ) : BraidEquiv ρ σ :=
  Relation.EqvGen.rel _ _ h

/-- A property of words invariant under single braid moves is invariant under `BraidEquiv`. -/
theorem BraidEquiv.eq_of_step {α : Sort*} {f : List ℕ → α}
    (hf : ∀ ρ σ, BraidStep ρ σ → f ρ = f σ) {ρ σ : List ℕ} (h : BraidEquiv ρ σ) : f ρ = f σ := by
  induction h with
  | rel _ _ h => exact hf _ _ h
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

theorem BraidEquiv.length_eq {ρ σ : List ℕ} (h : BraidEquiv ρ σ) : ρ.length = σ.length :=
  h.eq_of_step (f := List.length) fun _ _ h => h.length_eq

theorem BraidEquiv.mem_iff {ρ σ : List ℕ} (h : BraidEquiv ρ σ) (x : ℕ) : x ∈ ρ ↔ x ∈ σ := by
  have := h.eq_of_step (f := fun τ => x ∈ τ) fun _ _ h => propext (h.mem_iff x)
  exact Iff.of_eq this

theorem BraidEquiv.validWord_iff {m : ℕ} {ρ σ : List ℕ} (h : BraidEquiv ρ σ) :
    ValidWord m ρ ↔ ValidWord m σ := by
  simp only [ValidWord, h.mem_iff]

/-- Braid-equivalent valid words represent the same permutation. -/
theorem BraidEquiv.wordProd_eq {m : ℕ} {ρ σ : List ℕ} (h : BraidEquiv ρ σ)
    (hv : ValidWord m ρ) : wordProd m ρ = wordProd m σ := by
  induction h with
  | rel _ _ h => exact h.wordProd_eq hv
  | refl => rfl
  | symm _ _ h ih => exact (ih ((BraidEquiv.validWord_iff h).2 hv)).symm
  | trans _ _ _ h₁ _ ih₁ ih₂ => exact (ih₁ hv).trans (ih₂ ((BraidEquiv.validWord_iff h₁).1 hv))

/-- A word map sending braid moves to braid moves preserves braid equivalence. -/
theorem BraidEquiv.map {f : List ℕ → List ℕ} (hf : ∀ ρ σ, BraidStep ρ σ → BraidStep (f ρ) (f σ))
    {ρ σ : List ℕ} (h : BraidEquiv ρ σ) : BraidEquiv (f ρ) (f σ) := by
  induction h with
  | rel _ _ h => exact (hf _ _ h).braidEquiv
  | refl => exact BraidEquiv.refl _
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

theorem BraidEquiv.append_left {ρ σ : List ℕ} (h : BraidEquiv ρ σ) (γ : List ℕ) :
    BraidEquiv (γ ++ ρ) (γ ++ σ) :=
  h.map (f := (γ ++ ·)) fun _ _ h => h.append_left γ

theorem BraidEquiv.append_right {ρ σ : List ℕ} (h : BraidEquiv ρ σ) (γ : List ℕ) :
    BraidEquiv (ρ ++ γ) (σ ++ γ) :=
  h.map (f := (· ++ γ)) fun _ _ h => h.append_right γ

/-- Braid equivalence is a congruence for concatenation. -/
theorem BraidEquiv.append {ρ ρ' σ σ' : List ℕ} (h₁ : BraidEquiv ρ ρ') (h₂ : BraidEquiv σ σ') :
    BraidEquiv (ρ ++ σ) (ρ' ++ σ') :=
  (h₁.append_right σ).trans (h₂.append_left ρ')

theorem BraidEquiv.cons {ρ σ : List ℕ} (h : BraidEquiv ρ σ) (k : ℕ) :
    BraidEquiv (k :: ρ) (k :: σ) :=
  h.append_left [k]

/-- Commutation move `ab ↔ ba` for distant letters, in either order. -/
theorem braidEquiv_comm (α β : List ℕ) {a b : ℕ} (h : a + 1 < b ∨ b + 1 < a) :
    BraidEquiv (α ++ [a, b] ++ β) (α ++ [b, a] ++ β) := by
  rcases h with h | h
  · exact (BraidStep.comm α β h).braidEquiv
  · exact (BraidStep.comm α β h).braidEquiv.symm

/-- Braid move `a(a+1)a ↔ (a+1)a(a+1)`. -/
theorem braidEquiv_braid (α β : List ℕ) (a : ℕ) :
    BraidEquiv (α ++ [a, a + 1, a] ++ β) (α ++ [a + 1, a, a + 1] ++ β) :=
  (BraidStep.braid α β a).braidEquiv

/-- Braid move `(a+1)a(a+1) ↔ a(a+1)a`. -/
theorem braidEquiv_braid_symm (α β : List ℕ) (a : ℕ) :
    BraidEquiv (α ++ [a + 1, a, a + 1] ++ β) (α ++ [a, a + 1, a] ++ β) :=
  (braidEquiv_braid α β a).symm

/-- A letter `k` can be moved across a block of letters all distant from `k`. -/
theorem braidEquiv_append_singleton_of_distant {L : List ℕ} {k : ℕ}
    (h : ∀ x ∈ L, x + 1 < k ∨ k + 1 < x) : BraidEquiv (L ++ [k]) (k :: L) := by
  induction L with
  | nil => exact BraidEquiv.refl _
  | cons x L ih =>
    have hx := h x (by simp)
    have ih := (ih fun y hy => h y (by simp [hy])).cons x
    refine ih.trans ?_
    simpa using braidEquiv_comm [] L (a := x) (b := k) (by omega)

/-! ## Repeated letters -/

theorem HasRepeat.append_left {ρ : List ℕ} (h : HasRepeat ρ) (γ : List ℕ) :
    HasRepeat (γ ++ ρ) := by
  obtain ⟨α, β, a, rfl⟩ := h
  exact ⟨γ ++ α, β, a, by simp⟩

theorem HasRepeat.append_right {ρ : List ℕ} (h : HasRepeat ρ) (γ : List ℕ) :
    HasRepeat (ρ ++ γ) := by
  obtain ⟨α, β, a, rfl⟩ := h
  exact ⟨α, β ++ γ, a, by simp⟩

theorem hasRepeat_append_pair (α β : List ℕ) (a : ℕ) : HasRepeat (α ++ [a, a] ++ β) :=
  ⟨α, β, a, rfl⟩

theorem wordProd_repeat (m : ℕ) (α β : List ℕ) (a : ℕ) :
    wordProd m (α ++ [a, a] ++ β) = wordProd m (α ++ β) := by
  simp [← mul_assoc]

end Categorification.TypeA
