/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.Graded.K0
import Categorification.Algebra.Graded.Dimension

/-!
# The Grothendieck group `G₀` of finite-dimensional graded modules

Let `A` be an algebra over a field `k`, graded by `𝒜 : ℤ → Submodule k A`. Following
Khovanov–Lauda I (arXiv:0803.4121v2, §2.5), `G₀(A)` is the Grothendieck group of the abelian
category `A-fmod` of finite-dimensional graded left `A`-modules with degree-preserving morphisms:
the free abelian group on isomorphism classes modulo `[N] = [M] + [P]` for every short exact
sequence `0 → M → N → P → 0` of degree-preserving maps. It is a `ℤ[q, q⁻¹]`-module, `q` acting by
the grading shift `{1}`.

## Main definitions and results

* `GFin 𝒜` : bundled finite-dimensional graded modules (in the universe of `A`).
* `G0 𝒜`, `G0.of M`, `G0.of_eq_add_of_exact`, `G0.of_prod`, `G0.of_eq_of_iso`.
* `Module (LaurentPolynomial ℤ) (G0 𝒜)` with `T a • [M] = [M{a}]` (`G0.T_smul_of`).
* `G0.gdim : G0 𝒜 →+ ℤ[q, q⁻¹]`, `[M] ↦ gdim M` (`G0.gdim_of`), which is `ℤ[q, q⁻¹]`-linear
  (`G0.gdim_T_smul`). This shows in particular that the relations do not collapse `G₀`.

As for `K₀` (see `Categorification.Algebra.Graded.K0`), the modules live in the universe of `A`
and `G0 𝒜` lives one universe up.
-/

universe u v

noncomputable section

namespace Categorification.Graded

open DirectSum

variable {k : Type v} [Field k] {A : Type u} [Ring A] [Algebra k A] (𝒜 : ℤ → Submodule k A)

/-- A finite-dimensional graded left `A`-module (an object of KL I's `A-fmod`). -/
structure GFin extends GMod 𝒜 where
  [finiteDimensional : FiniteDimensional k carrier]

namespace GFin

attribute [instance] finiteDimensional

variable {𝒜}

/-- The grading shift `M{a}`. -/
def shift (M : GFin 𝒜) (a : ℤ) : GFin 𝒜 :=
  { toGMod := M.toGMod.shift a
    finiteDimensional := M.finiteDimensional }

/-- The direct sum `M ⊕ N`. -/
def prod (M N : GFin 𝒜) : GFin 𝒜 :=
  { toGMod := M.toGMod.prod N.toGMod
    finiteDimensional := inferInstanceAs (FiniteDimensional k (M.carrier × N.carrier)) }

/-- Degree-preserving isomorphisms. -/
abbrev Iso (M N : GFin 𝒜) : Type u := M.toGMod.Iso N.toGMod

/-- A short exact sequence `0 → M → N → P → 0` of degree-preserving `A`-linear maps. -/
structure ShortExact (M N P : GFin 𝒜) where
  /-- The first map. -/
  f : M.carrier →ₗ[A] N.carrier
  /-- The second map. -/
  g : N.carrier →ₗ[A] P.carrier
  preservesGrading_f : PreservesGrading M.grading N.grading f
  preservesGrading_g : PreservesGrading N.grading P.grading g
  injective : Function.Injective f
  surjective : Function.Surjective g
  exact : Function.Exact f g

/-- Shifting a short exact sequence. -/
def ShortExact.shift {M N P : GFin 𝒜} (S : ShortExact M N P) (a : ℤ) :
    ShortExact (M.shift a) (N.shift a) (P.shift a) where
  f := S.f
  g := S.g
  preservesGrading_f _ _ hx := S.preservesGrading_f hx
  preservesGrading_g _ _ hx := S.preservesGrading_g hx
  injective := S.injective
  surjective := S.surjective
  exact := S.exact

/-- The split short exact sequence `0 → M → M ⊕ N → N → 0`. -/
def ShortExact.prod (M N : GFin 𝒜) : ShortExact M (M.prod N) N where
  f := LinearMap.inl A M.carrier N.carrier
  g := LinearMap.snd A M.carrier N.carrier
  preservesGrading_f _ _ hx := ⟨hx, zero_mem _⟩
  preservesGrading_g _ _ hx := hx.2
  injective := LinearMap.inl_injective
  surjective := LinearMap.snd_surjective
  exact := Function.Exact.inl_snd

variable (𝒜) in
/-- The setoid of isomorphism classes. -/
def isoSetoid : Setoid (GFin 𝒜) where
  r M N := Nonempty (Iso M N)
  iseqv := ⟨fun _ => ⟨GradedEquiv.refl _⟩, fun ⟨e⟩ => ⟨e.symm⟩, fun ⟨e⟩ ⟨f⟩ => ⟨e.trans f⟩⟩

variable (𝒜) in
/-- Isomorphism classes of finite-dimensional graded modules. -/
def IsoClass : Type _ := Quotient (isoSetoid 𝒜)

/-- The isomorphism class of `M`. -/
def isoClass (M : GFin 𝒜) : IsoClass 𝒜 := Quotient.mk (isoSetoid 𝒜) M

theorem isoClass_eq {M N : GFin 𝒜} (e : Iso M N) : isoClass M = isoClass N :=
  Quotient.sound (s := isoSetoid 𝒜) ⟨e⟩

theorem isoClass_surjective : Function.Surjective (isoClass (𝒜 := 𝒜)) :=
  Quotient.mk_surjective

/-- Shifting is well defined on isomorphism classes. -/
def IsoClass.shift (a : ℤ) : IsoClass 𝒜 → IsoClass 𝒜 :=
  Quotient.map (fun M => M.shift a) fun _ _ ⟨e⟩ => ⟨e.shift a⟩

@[simp] theorem IsoClass.shift_isoClass (a : ℤ) (M : GFin 𝒜) :
    IsoClass.shift a (isoClass M) = isoClass (M.shift a) := rfl

end GFin

open GFin FreeAbelianGroup

/-- The defining relations `[N] - [M] - [P]` of `G₀`, one for each short exact sequence. -/
def G0.relations : Set (FreeAbelianGroup (GFin.IsoClass 𝒜)) :=
  {x | ∃ (M N P : GFin 𝒜) (_ : ShortExact M N P),
    x = of (isoClass N) - of (isoClass M) - of (isoClass P)}

/-- The subgroup generated by the relations of `G₀`. -/
def G0.relSubgroup : AddSubgroup (FreeAbelianGroup (GFin.IsoClass 𝒜)) :=
  AddSubgroup.closure (G0.relations 𝒜)

/-- The Grothendieck group `G₀(A)` of finite-dimensional graded `A`-modules. -/
def G0 : Type _ := FreeAbelianGroup (GFin.IsoClass 𝒜) ⧸ G0.relSubgroup 𝒜

namespace G0

instance : AddCommGroup (G0 𝒜) :=
  inferInstanceAs (AddCommGroup (FreeAbelianGroup (GFin.IsoClass 𝒜) ⧸ G0.relSubgroup 𝒜))

/-- The quotient map from the free abelian group on isomorphism classes. -/
def mk : FreeAbelianGroup (GFin.IsoClass 𝒜) →+ G0 𝒜 := QuotientAddGroup.mk' _

variable {𝒜}

theorem mk_surjective : Function.Surjective (mk 𝒜) := QuotientAddGroup.mk'_surjective _

/-- The class `[M] ∈ G₀(A)`. -/
def of (M : GFin 𝒜) : G0 𝒜 := mk 𝒜 (FreeAbelianGroup.of (isoClass M))

/-- Isomorphic modules have the same class. -/
theorem of_eq_of_iso {M N : GFin 𝒜} (e : M.Iso N) : of M = of N := by
  rw [of, of, isoClass_eq e]

/-- `[N] = [M] + [P]` for a short exact sequence `0 → M → N → P → 0`. -/
theorem of_eq_add_of_shortExact {M N P : GFin 𝒜} (S : ShortExact M N P) :
    of N = of M + of P := by
  have h : FreeAbelianGroup.of (isoClass N) - FreeAbelianGroup.of (isoClass M) -
      FreeAbelianGroup.of (isoClass P) ∈ relSubgroup 𝒜 :=
    AddSubgroup.subset_closure ⟨M, N, P, S, rfl⟩
  rw [← QuotientAddGroup.eq_zero_iff] at h
  change mk 𝒜 _ = 0 at h
  rw [map_sub, map_sub, sub_sub, sub_eq_zero] at h
  exact h

/-- `[M ⊕ N] = [M] + [N]`. -/
theorem of_prod (M N : GFin 𝒜) : of (M.prod N) = of M + of N :=
  of_eq_add_of_shortExact (ShortExact.prod M N)

/-- Additive maps out of `G₀` are determined by their values on classes `[M]`. -/
theorem hom_ext {G : Type*} [AddCommGroup G] {f g : G0 𝒜 →+ G}
    (h : ∀ M : GFin 𝒜, f (of M) = g (of M)) : f = g := by
  refine QuotientAddGroup.addMonoidHom_ext _ (FreeAbelianGroup.lift.ext _ _ fun c => ?_)
  obtain ⟨M, rfl⟩ := isoClass_surjective c
  exact h M

/-- Construct an additive map out of `G₀` from an isomorphism-invariant function which is
additive on short exact sequences. -/
def lift {G : Type*} [AddCommGroup G] (φ : GFin 𝒜 → G)
    (hiso : ∀ {M N : GFin 𝒜}, M.Iso N → φ M = φ N)
    (hses : ∀ {M N P : GFin 𝒜}, ShortExact M N P → φ N = φ M + φ P) : G0 𝒜 →+ G :=
  QuotientAddGroup.lift _
    (FreeAbelianGroup.lift (Quotient.lift (s := isoSetoid 𝒜) φ fun _ _ ⟨e⟩ => hiso e)) <| by
      rw [relSubgroup, AddSubgroup.closure_le]
      rintro _ ⟨M, N, P, S, rfl⟩
      simp only [SetLike.mem_coe, AddMonoidHom.mem_ker, map_sub, FreeAbelianGroup.lift.of]
      change φ N - φ M - φ P = 0
      rw [hses S]; abel

@[simp] theorem lift_of {G : Type*} [AddCommGroup G] (φ : GFin 𝒜 → G)
    (hiso : ∀ {M N : GFin 𝒜}, M.Iso N → φ M = φ N)
    (hses : ∀ {M N P : GFin 𝒜}, ShortExact M N P → φ N = φ M + φ P) (M : GFin 𝒜) :
    lift φ hiso hses (of M) = φ M :=
  FreeAbelianGroup.lift.of _ _

/-! ### The grading shift and the `ℤ[q, q⁻¹]`-module structure -/

/-- The grading shift `{a}` on `G₀`. -/
def shiftHom (a : ℤ) : G0 𝒜 →+ G0 𝒜 :=
  QuotientAddGroup.map _ _ (FreeAbelianGroup.map (GFin.IsoClass.shift a)) <| by
    rw [relSubgroup, AddSubgroup.closure_le]
    rintro _ ⟨M, N, P, S, rfl⟩
    apply AddSubgroup.subset_closure
    exact ⟨M.shift a, N.shift a, P.shift a, S.shift a, rfl⟩

@[simp] theorem shiftHom_of (a : ℤ) (M : GFin 𝒜) : shiftHom a (of M) = of (M.shift a) := rfl

theorem shiftHom_zero : shiftHom (0 : ℤ) = AddMonoidHom.id (G0 𝒜) :=
  hom_ext fun M => by
    rw [shiftHom_of, AddMonoidHom.id_apply]
    exact of_eq_of_iso (GMod.shiftZeroIso M.toGMod)

theorem shiftHom_add (a b : ℤ) : shiftHom (a + b) = (shiftHom b).comp (shiftHom (𝒜 := 𝒜) a) :=
  hom_ext fun M => by
    rw [AddMonoidHom.comp_apply, shiftHom_of, shiftHom_of, shiftHom_of]
    exact (of_eq_of_iso (GMod.shiftShiftIso M.toGMod a b)).symm

/-- The action of `q^a` as an element of `End(G₀)`. -/
def qPow : Multiplicative ℤ →* Module.End ℤ (G0 𝒜) where
  toFun a := (shiftHom (Multiplicative.toAdd a)).toIntLinearMap
  map_one' := by
    ext x
    simp [shiftHom_zero]
  map_mul' a b := by
    ext x
    simp only [toAdd_mul, AddMonoidHom.coe_toIntLinearMap, Module.End.mul_apply]
    rw [add_comm, shiftHom_add]
    rfl

/-- `G₀(A)` is a `ℤ[q, q⁻¹]`-module, `q` acting by the grading shift `{1}`. -/
instance : Module (LaurentPolynomial ℤ) (G0 𝒜) :=
  Module.compHom (G0 𝒜) (AddMonoidAlgebra.lift ℤ ℤ (Module.End ℤ (G0 𝒜)) qPow).toRingHom

/-- `q^a • x = x{a}`. -/
theorem T_smul (a : ℤ) (x : G0 𝒜) : (LaurentPolynomial.T a : LaurentPolynomial ℤ) • x =
    shiftHom a x := by
  change AddMonoidAlgebra.lift ℤ ℤ (Module.End ℤ (G0 𝒜)) qPow (LaurentPolynomial.T a) x = _
  rw [LaurentPolynomial.T, AddMonoidAlgebra.lift_single, one_smul]
  rfl

/-- `q^a [M] = [M{a}]`. -/
theorem T_smul_of (a : ℤ) (M : GFin 𝒜) :
    (LaurentPolynomial.T a : LaurentPolynomial ℤ) • of M = of (M.shift a) := by
  rw [T_smul, shiftHom_of]

/-! ### Graded dimension on `G₀` -/

/-- The graded dimension `G₀(A) → ℤ[q, q⁻¹]`, `[M] ↦ gdim M`. -/
def gdim : G0 𝒜 →+ LaurentPolynomial ℤ :=
  lift (fun M => gdimPoly M.grading) (fun e => gdimPoly_congr e) fun S =>
    gdimPoly_eq_add_of_exact_of_preservesGrading (f := S.f.restrictScalars k)
      (g := S.g.restrictScalars k) S.preservesGrading_f S.preservesGrading_g S.injective
      S.surjective S.exact

@[simp] theorem gdim_of (M : GFin 𝒜) : gdim (of M) = gdimPoly M.grading :=
  FreeAbelianGroup.lift.of _ _

/-- `gdim` is `ℤ[q, q⁻¹]`-linear: `gdim (q^a x) = q^a gdim x`. -/
theorem gdim_T_smul (a : ℤ) (x : G0 𝒜) :
    gdim ((LaurentPolynomial.T a : LaurentPolynomial ℤ) • x) =
      LaurentPolynomial.T a * gdim x := by
  rw [T_smul]
  have : gdim.comp (shiftHom a) =
      (AddMonoidHom.mulLeft (LaurentPolynomial.T a : LaurentPolynomial ℤ)).comp
        (gdim (𝒜 := 𝒜)) :=
    hom_ext fun M => by
      simp only [AddMonoidHom.comp_apply, shiftHom_of, gdim_of, AddMonoidHom.coe_mulLeft]
      exact gdimPoly_shift M.grading a
  exact DFunLike.congr_fun this x

end G0

end Categorification.Graded

end
