/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.Graded.Dimension

/-!
# Graded dimensions from homogeneous bases and homogeneous generators

Two general sources of graded dimensions (Khovanov–Lauda I, arXiv:0803.4121v2, §2.4–2.5):

* **Homogeneous bases.** If a `ℤ`-graded vector space `M = ⨁_d ℳ d` has a linearly independent
  family `b : ι → M` of homogeneous elements (`b x ∈ ℳ (deg x)`), then for every `S ⊆ ι` the
  degree-`d` part of the span of `b '' S` is spanned by the `b x`, `x ∈ S`, of degree `d`
  (`inf_span_eq`). If these fibres are finite and `deg` is bounded below on `S`, the graded
  dimension of `span (b '' S)` exists and its `q^d`-coefficient is the number of `x ∈ S` of
  degree `d` (`hasGdim_inf_span`, `coeff_gdim_inf_span`).
* **Homogeneous generators.** If `(A, 𝒜)` is a graded algebra over a field with a graded
  dimension (`HasGdim 𝒜`) and `M` is a graded `A`-module generated by finitely many
  homogeneous elements `m_t` of degrees `d_t`, then `M_d ⊆ ∑_t A_{d - d_t} m_t`
  (`grade_le_iSup`), so `M` has a graded dimension (`hasGdim_of_generators`). Every finitely
  generated graded module is generated by finitely many homogeneous elements (the homogeneous
  components of any finite generating set), so every finitely generated graded module has a
  graded dimension (`hasGdim_of_finite`). In KL I this is the statement that `gdim` is defined
  on `R(ν)-mod`.

We also record that `gdim` and `HasGdim` only depend on the pieces up to degree-wise linear
equivalence (`gdim_eq_of_finrank_eq`, `HasGdim.of_linearEquiv`), and the dimension of a
grading pulled back along an injective map (`finrank_comap`).
-/

namespace Categorification.Graded

open DirectSum Module Function

/-! ### Invariance -/

section Invariance

variable {k M N : Type*} [Field k] [AddCommGroup M] [Module k M] [AddCommGroup N] [Module k N]

/-- `gdim` only depends on the dimensions of the pieces. -/
theorem gdim_eq_of_finrank_eq {ℳ : ℤ → Submodule k M} {𝒩 : ℤ → Submodule k N}
    (h : ∀ d, finrank k (ℳ d) = finrank k (𝒩 d)) : gdim ℳ = gdim 𝒩 := by
  have h' : (fun d => (finrank k (ℳ d) : ℤ)) = fun d => (finrank k (𝒩 d) : ℤ) :=
    funext fun d => by rw [h d]
  unfold gdim
  rw [h']

/-- `HasGdim` transfers along degree-wise linear equivalences. -/
theorem HasGdim.of_linearEquiv {ℳ : ℤ → Submodule k M} {𝒩 : ℤ → Submodule k N} [HasGdim 𝒩]
    (e : ∀ d, ℳ d ≃ₗ[k] 𝒩 d) : HasGdim ℳ where
  finiteDimensional d := (e d).symm.finiteDimensional
  bddBelow := HasGdim.bddBelow (ℳ := 𝒩) |>.mono fun d (hd : ℳ d ≠ ⊥) (h : 𝒩 d = ⊥) => hd <| by
    rw [eq_bot_iff]
    intro x hx
    have h2 : e d ⟨x, hx⟩ = 0 :=
      Subtype.ext ((Submodule.eq_bot_iff _).1 h _ (e d ⟨x, hx⟩).2)
    rw [LinearEquiv.map_eq_zero_iff] at h2
    simpa using congrArg Subtype.val h2

/-- The linear equivalence `(comap ℳ f) d ≃ ℳ d ⊓ range f` for injective `f`. -/
noncomputable def comapEquiv (ℳ : ℤ → Submodule k M) {f : N →ₗ[k] M} (hf : Injective f)
    (d : ℤ) : comap ℳ f d ≃ₗ[k] ↥(ℳ d ⊓ LinearMap.range f : Submodule k M) :=
  ((comap ℳ f d).equivMapOfInjective f hf).trans
    (LinearEquiv.ofEq _ _ ((Submodule.map_comap_eq f (ℳ d)).trans (inf_comm _ _)))

/-- The pieces of a grading pulled back along an injective map `f` have the dimensions of the
pieces of `ℳ d ⊓ range f`. -/
theorem finrank_comap (ℳ : ℤ → Submodule k M) {f : N →ₗ[k] M} (hf : Injective f) (d : ℤ) :
    finrank k (comap ℳ f d) = finrank k ↥(ℳ d ⊓ LinearMap.range f : Submodule k M) :=
  (comapEquiv ℳ hf d).finrank_eq

end Invariance

/-! ### Homogeneous bases -/

section Basis

variable {k M ι : Type*} [Field k] [AddCommGroup M] [Module k M]
  (ℳ : ℤ → Submodule k M) [Decomposition ℳ] {b : ι → M} (deg : ι → ℤ)

/-- The homogeneous components of an element of the span of homogeneous elements `b x`,
`x ∈ S`, lie in the span of those of the right degree. -/
theorem decompose_mem_span (hdeg : ∀ x, b x ∈ ℳ (deg x)) (S : Set ι) {y : M}
    (hy : y ∈ Submodule.span k (b '' S)) (d : ℤ) :
    (decompose ℳ y d : M) ∈ Submodule.span k (b '' {x | x ∈ S ∧ deg x = d}) := by
  classical
  induction hy using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨x, hx, rfl⟩ := hy
    by_cases h : deg x = d
    · rw [decompose_of_mem_same _ (h ▸ hdeg x)]
      exact Submodule.subset_span ⟨x, ⟨hx, h⟩, rfl⟩
    · rw [decompose_of_mem_ne _ (hdeg x) h]
      exact zero_mem _
  | zero => simp
  | add y z _ _ hy hz =>
    rw [decompose_add, add_apply, Submodule.coe_add]
    exact add_mem hy hz
  | smul c y _ hy =>
    rw [decompose_smul, DFinsupp.smul_apply, Submodule.coe_smul]
    exact Submodule.smul_mem _ c hy

/-- The degree-`d` part of the span of homogeneous elements is spanned by those of degree
`d`. -/
theorem inf_span_eq (hdeg : ∀ x, b x ∈ ℳ (deg x)) (S : Set ι) (d : ℤ) :
    ℳ d ⊓ Submodule.span k (b '' S) = Submodule.span k (b '' {x | x ∈ S ∧ deg x = d}) := by
  classical
  apply le_antisymm
  · rintro y ⟨hyd, hyS⟩
    have := decompose_mem_span ℳ deg hdeg S hyS d
    rwa [decompose_of_mem_same _ hyd] at this
  · refine le_inf (Submodule.span_le.2 ?_) (Submodule.span_mono (Set.image_mono fun x hx => hx.1))
    rintro _ ⟨x, ⟨-, hx⟩, rfl⟩
    exact hx ▸ hdeg x

/-- The dimension of the degree-`d` part of the span of a linearly independent family of
homogeneous elements is the number of those of degree `d`. -/
theorem finrank_inf_span (hb : LinearIndependent k b) (hdeg : ∀ x, b x ∈ ℳ (deg x))
    (S : Set ι) (d : ℤ) (hfin : {x | x ∈ S ∧ deg x = d}.Finite) :
    finrank k ↥(ℳ d ⊓ Submodule.span k (b '' S) : Submodule k M) =
      Nat.card {x | x ∈ S ∧ deg x = d} := by
  rw [inf_span_eq ℳ deg hdeg S d]
  haveI := hfin.fintype
  rw [Set.image_eq_range]
  exact (finrank_span_eq_card (hb.comp _ Subtype.val_injective)).trans
    Nat.card_eq_fintype_card.symm

/-- A family of homogeneous linearly independent elements whose degree fibres (in `S`) are
finite and whose degrees are bounded below on `S` spans a graded subspace with a graded
dimension. -/
theorem hasGdim_inf_span (hdeg : ∀ x, b x ∈ ℳ (deg x)) (S : Set ι)
    (hfin : ∀ d, {x | x ∈ S ∧ deg x = d}.Finite) (hbdd : BddBelow (deg '' S)) :
    HasGdim fun d => (ℳ d ⊓ Submodule.span k (b '' S) : Submodule k M) where
  finiteDimensional d := by
    have h := inf_span_eq ℳ deg hdeg S d
    haveI := FiniteDimensional.span_of_finite k ((hfin d).image b)
    exact Submodule.finiteDimensional_of_le h.le
  bddBelow := hbdd.mono fun d (hd : ℳ d ⊓ _ ≠ ⊥) => by
    by_contra h
    apply hd
    rw [inf_span_eq ℳ deg hdeg S d]
    have : {x | x ∈ S ∧ deg x = d} = ∅ :=
      Set.eq_empty_iff_forall_not_mem.2 fun x hx => h ⟨x, hx.1, hx.2⟩
    rw [this, Set.image_empty, Submodule.span_empty]

/-- The coefficients of the graded dimension of the span of a homogeneous linearly independent
family count its elements of each degree. -/
theorem coeff_gdim_inf_span (hb : LinearIndependent k b) (hdeg : ∀ x, b x ∈ ℳ (deg x))
    (S : Set ι) (hfin : ∀ d, {x | x ∈ S ∧ deg x = d}.Finite) (hbdd : BddBelow (deg '' S))
    (d : ℤ) :
    (gdim fun d => (ℳ d ⊓ Submodule.span k (b '' S) : Submodule k M)).coeff d =
      Nat.card {x | x ∈ S ∧ deg x = d} := by
  haveI := hasGdim_inf_span ℳ deg hdeg S hfin hbdd
  rw [coeff_gdim, finrank_inf_span ℳ deg hb hdeg S d (hfin d)]

end Basis

/-! ### Homogeneous generators -/

section Generators

variable {k A M : Type*} [Field k] [Ring A] [Algebra k A] [AddCommGroup M] [Module A M]
  [Module k M] [IsScalarTower k A M]
  (𝒜 : ℤ → Submodule k A) [GradedAlgebra 𝒜] (ℳ : ℤ → Submodule k M) [Decomposition ℳ]
  [SetLike.GradedSMul 𝒜 ℳ]

omit [IsScalarTower k A M] in
/-- The degree-`d` component of `a • m`, for `m` homogeneous of degree `j`, is
`a_{d - j} • m`. -/
theorem decompose_smul_of_mem (a : A) {m : M} {j : ℤ} (hm : m ∈ ℳ j) (d : ℤ) :
    (decompose ℳ (a • m) d : M) = (decompose 𝒜 a (d - j) : A) • m := by
  classical
  induction a using Decomposition.inductionOn 𝒜 with
  | zero => simp
  | add a a' ha ha' =>
    rw [add_smul, decompose_add, add_apply, Submodule.coe_add, ha, ha', decompose_add, add_apply,
      Submodule.coe_add, add_smul]
  | @homogeneous i a =>
    have ham : (a : A) • m ∈ ℳ (i + j) := by
      simpa [vadd_eq_add] using SetLike.GradedSMul.smul_mem (A := 𝒜) (B := ℳ) a.2 hm
    by_cases h : i + j = d
    · rw [decompose_of_mem_same _ (h ▸ ham), decompose_of_mem_same _ (show (a : A) ∈ 𝒜 (d - j)
        by rw [← h, add_sub_cancel_right]; exact a.2)]
    · rw [decompose_of_mem_ne _ ham h, decompose_of_mem_ne _ a.2 (show i ≠ d - j by omega),
        zero_smul]

/-- The `k`-linear map `a ↦ a • m`. -/
def smulRightK (m : M) : A →ₗ[k] M :=
  (LinearMap.toSpanSingleton A M m).restrictScalars k

@[simp] theorem smulRightK_apply (m : M) (a : A) : smulRightK (k := k) m a = a • m := rfl

/-- If `M` is generated by homogeneous elements `m t ∈ ℳ (deg t)`, then
`M_d ⊆ ∑_t A_{d - deg t} m_t`. -/
theorem grade_le_iSup {ι : Type*} [Fintype ι] (m : ι → M) (deg : ι → ℤ)
    (hm : ∀ t, m t ∈ ℳ (deg t)) (hspan : Submodule.span A (Set.range m) = ⊤) (d : ℤ) :
    ℳ d ≤ ⨆ t, (𝒜 (d - deg t)).map (smulRightK (k := k) (m t)) := by
  classical
  intro y hy
  have hy' : y ∈ Submodule.span A (Set.range m) := hspan ▸ Submodule.mem_top
  obtain ⟨c, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun A).1 hy'
  rw [← decompose_of_mem_same ℳ hy, decompose_sum, DFinsupp.finset_sum_apply,
    Submodule.coe_sum]
  refine Submodule.sum_mem _ fun t _ => Submodule.mem_iSup_of_mem t ?_
  rw [decompose_smul_of_mem 𝒜 ℳ (c t) (hm t)]
  exact ⟨_, (decompose 𝒜 (c t) (d - deg t)).2, rfl⟩

/-- A graded module generated by finitely many homogeneous elements over a graded algebra with a
graded dimension has a graded dimension. -/
theorem hasGdim_of_generators [HasGdim 𝒜] {ι : Type*} [Fintype ι] (m : ι → M) (deg : ι → ℤ)
    (hm : ∀ t, m t ∈ ℳ (deg t)) (hspan : Submodule.span A (Set.range m) = ⊤) : HasGdim ℳ where
  finiteDimensional d := Submodule.finiteDimensional_of_le (grade_le_iSup 𝒜 ℳ m deg hm hspan d)
  bddBelow := by
    obtain ⟨B, hB⟩ := HasGdim.bddBelow (ℳ := 𝒜)
    obtain ⟨D, hD⟩ := (Set.finite_range deg).bddBelow
    refine ⟨B + D, fun d (hd : ℳ d ≠ ⊥) => ?_⟩
    by_contra hlt
    push_neg at hlt
    apply hd
    rw [eq_bot_iff]
    refine (grade_le_iSup 𝒜 ℳ m deg hm hspan d).trans (iSup_le fun t => ?_)
    have h1 : 𝒜 (d - deg t) = ⊥ := by
      by_contra h
      have := hB h
      have := hD ⟨t, rfl⟩
      simp only [Set.mem_setOf_eq] at *
      omega
    rw [h1, Submodule.map_bot]

omit [Algebra k A] [IsScalarTower k A M] in
/-- A finitely generated graded module is generated by finitely many homogeneous elements. -/
theorem exists_homogeneous_generators [Module.Finite A M] :
    ∃ (s : Finset (ℤ × M)), (∀ p ∈ s, p.2 ∈ ℳ p.1) ∧
      Submodule.span A ((fun p : s => (p : ℤ × M).2) '' Set.univ) = ⊤ := by
  classical
  obtain ⟨g, hg⟩ := Module.Finite.fg_top (R := A) (M := M)
  refine ⟨g.biUnion fun x => (decompose ℳ x).support.image fun d => (d, (decompose ℳ x d : M)),
    ?_, ?_⟩
  · intro p hp
    simp only [Finset.mem_biUnion, Finset.mem_image] at hp
    obtain ⟨x, -, d, -, rfl⟩ := hp
    exact (decompose ℳ x d).2
  · rw [eq_top_iff, ← hg, Submodule.span_le]
    intro x hx
    rw [← sum_support_decompose ℳ x]
    refine Submodule.sum_mem _ fun d hd => Submodule.subset_span ⟨⟨(d, _), ?_⟩, trivial, rfl⟩
    simp only [Finset.mem_biUnion, Finset.mem_image]
    exact ⟨x, hx, d, hd, rfl⟩

/-- **Finitely generated graded modules have graded dimensions**: if `A` has a graded dimension
(finite-dimensional pieces, bounded below), then so does every finitely generated graded
`A`-module. -/
theorem hasGdim_of_finite [HasGdim 𝒜] [Module.Finite A M] : HasGdim ℳ := by
  obtain ⟨s, hs, hspan⟩ := exists_homogeneous_generators (A := A) ℳ
  rw [Set.image_univ] at hspan
  exact hasGdim_of_generators 𝒜 ℳ (fun p : s => (p : ℤ × M).2) (fun p => (p : ℤ × M).1)
    (fun p => hs _ p.2) hspan

end Generators

end Categorification.Graded
