/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Algebra.Graded.HomogeneousBasis

/-!
# Graded simple modules

Let `A` be a `ℤ`-graded algebra over a field `k` and `(M, ℳ)` a graded `A`-module. Following
Khovanov–Lauda I (arXiv:0803.4121v2, §2.5, TeX lines 1489–1512), a *simple* graded module is a
simple object of the category of graded modules with degree-preserving maps: `M ≠ 0` and its only
homogeneous submodules are `0` and `M` (`Graded.IsGradedSimple`).

This file contains the general graded representation theory behind KL I, Proposition 2.12:

* `IsGradedSimple.span_singleton_eq_top` : a graded simple module is generated by any nonzero
  homogeneous element;
* `IsGradedSimple.smul_eq_zero_of_commute` : if `A` is bounded below (`𝒜 n = 0` for `n ≪ 0`),
  a central element all of whose homogeneous components have positive degree acts by zero on a
  graded simple module (graded Nakayama);
* `IsGradedSimple.finiteDimensional` : a graded simple module killed by a subspace `J ⊆ A` with
  `A / J` finite-dimensional is finite-dimensional;
* `IsGradedSimple.bijective_of_preservesGrading` : graded Schur lemma;
* `IsGradedSimple.eq_zero_of_preservesGrading_shift` : `Hom(M, M{a}) = 0` for `a ≠ 0` if `M` is
  finite-dimensional graded simple;
* `IsGradedSimple.isSimpleModule` : a finite-dimensional graded simple module is simple as an
  ungraded module;
* `IsGradedSimple.exists_gradedEquiv_shift_of_ne_zero` : graded simple modules with a nonzero
  (ungraded) homomorphism between them are isomorphic up to a grading shift;
* `card_le_finrank_of_isSimpleModule` : a finite-dimensional module has at most
  `dim` pairwise non-isomorphic simple quotients.
-/

namespace Categorification.Graded

open DirectSum

section Graded

variable {k A M N : Type*} [Field k] [Ring A] [Algebra k A]
  [AddCommGroup M] [Module A M] [Module k M] [IsScalarTower k A M]
  [AddCommGroup N] [Module A N] [Module k N] [IsScalarTower k A N]

/-- A graded module `(M, ℳ)` over the graded algebra `(A, 𝒜)` is *graded simple* (a simple object
of the category of graded `A`-modules, KL I §2.5) if `M ≠ 0` and its only homogeneous
`A`-submodules are `0` and `M`. (The grading `𝒜` of `A` is recorded for bookkeeping only.) -/
@[nolint unusedArguments]
structure IsGradedSimple (𝒜 : ℤ → Submodule k A) (ℳ : ℤ → Submodule k M) [Decomposition ℳ] :
    Prop where
  nontrivial : Nontrivial M
  eq_bot_or_eq_top : ∀ p : Submodule A M, p.IsHomogeneous ℳ → p = ⊥ ∨ p = ⊤

variable (𝒜 : ℤ → Submodule k A) [GradedAlgebra 𝒜]
  (ℳ : ℤ → Submodule k M) [Decomposition ℳ] [SetLike.GradedSMul 𝒜 ℳ]
  (𝒩 : ℤ → Submodule k N) [Decomposition 𝒩] [SetLike.GradedSMul 𝒜 𝒩]

omit [IsScalarTower k A M] [GradedAlgebra 𝒜] in
/-- The homogeneous component of `a • m` for homogeneous `a ∈ 𝒜 i`. -/
theorem decompose_smul_of_mem_left {a : A} {i : ℤ} (ha : a ∈ 𝒜 i) (m : M) (d : ℤ) :
    (decompose ℳ (a • m) d : M) = a • (decompose ℳ m (d - i) : M) := by
  induction m using Decomposition.inductionOn ℳ with
  | zero => simp
  | add x y hx hy => simp [smul_add, decompose_add, hx, hy]
  | @homogeneous j x =>
    have hax : a • (x : M) ∈ ℳ (i + j) := by
      simpa [vadd_eq_add] using SetLike.GradedSMul.smul_mem (A := 𝒜) (B := ℳ) ha x.2
    by_cases h : i + j = d
    · rw [decompose_of_mem_same _ (h ▸ hax), decompose_of_mem_same _
        (show (x : M) ∈ ℳ (d - i) by rw [← h, add_sub_cancel_left]; exact x.2)]
    · rw [decompose_of_mem_ne _ hax h, decompose_of_mem_ne _ x.2 (show j ≠ d - i by omega),
        smul_zero]

omit [IsScalarTower k A M] in
include 𝒜 in
/-- The `A`-span of a set of homogeneous elements is homogeneous. -/
theorem isHomogeneous_span {S : Set M} (hS : ∀ s ∈ S, ∃ j, s ∈ ℳ j) :
    (Submodule.span A S).IsHomogeneous ℳ := by
  classical
  suffices h : ∀ m ∈ Submodule.span A S, ∀ d, (decompose ℳ m d : M) ∈ Submodule.span A S from
    fun d m hm => h m hm d
  intro m hm
  induction hm using Submodule.span_induction with
  | mem x hx =>
    intro d
    obtain ⟨j, hj⟩ := hS x hx
    by_cases h : j = d
    · subst h; rw [decompose_of_mem_same _ hj]; exact Submodule.subset_span hx
    · rw [decompose_of_mem_ne _ hj h]; exact zero_mem _
  | zero => intro d; simp
  | add x y _ _ hx hy =>
    intro d
    rw [decompose_add, add_apply, Submodule.coe_add]
    exact add_mem (hx d) (hy d)
  | smul a x _ hx =>
    intro d
    have hsum : (decompose ℳ (a • x) d : M) = ∑ e ∈ (decompose ℳ x).support,
        (decompose ℳ (a • (decompose ℳ x e : M)) d : M) := by
      conv_lhs => rw [← sum_support_decompose ℳ x]
      rw [Finset.smul_sum, decompose_sum, DFinsupp.finset_sum_apply, Submodule.coe_sum]
    rw [hsum]
    refine Submodule.sum_mem _ fun e _ => ?_
    rw [decompose_smul_of_mem 𝒜 ℳ a (decompose ℳ x e).2 d]
    exact Submodule.smul_mem _ _ (hx e)

/-- A nonzero graded module has a nonzero homogeneous element. -/
theorem exists_mem_ne_zero [Nontrivial M] : ∃ j, ∃ v ∈ ℳ j, v ≠ 0 := by
  classical
  obtain ⟨m, hm⟩ := exists_ne (0 : M)
  by_contra h
  push_neg at h
  apply hm
  rw [← sum_support_decompose ℳ m]
  exact Finset.sum_eq_zero fun j _ => h j _ (decompose ℳ m j).2

namespace IsGradedSimple

variable {𝒜 ℳ 𝒩}

omit [IsScalarTower k A M] in
/-- A graded simple module is generated by any nonzero homogeneous element. -/
theorem span_singleton_eq_top (hM : IsGradedSimple 𝒜 ℳ) {v : M} {j : ℤ} (hv : v ∈ ℳ j)
    (hv0 : v ≠ 0) : Submodule.span A {v} = ⊤ := by
  rcases hM.eq_bot_or_eq_top _ (isHomogeneous_span 𝒜 ℳ (S := {v})
    (by simpa using ⟨j, hv⟩)) with h | h
  · exact absurd (Submodule.span_singleton_eq_bot.1 h) hv0
  · exact h

omit [IsScalarTower k A M] in
/-- In a graded simple module generated by `v ∈ ℳ j`, every `u ∈ ℳ i` is `a • v` with
`a ∈ 𝒜 (i - j)`. -/
theorem exists_eq_smul (hM : IsGradedSimple 𝒜 ℳ) {v : M} {j : ℤ} (hv : v ∈ ℳ j) (hv0 : v ≠ 0)
    {u : M} {i : ℤ} (hu : u ∈ ℳ i) : ∃ a ∈ 𝒜 (i - j), u = a • v := by
  have : u ∈ Submodule.span A {v} := by rw [hM.span_singleton_eq_top hv hv0]; trivial
  obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.1 this
  refine ⟨decompose 𝒜 a (i - j), (decompose 𝒜 a (i - j)).2, ?_⟩
  rw [← decompose_smul_of_mem 𝒜 ℳ a hv i, decompose_of_mem_same _ hu]

omit [IsScalarTower k A M] in
/-- If `𝒜` vanishes below degree `N`, a graded simple module generated in degree `j` vanishes
below degree `N + j`. -/
theorem grade_eq_bot_of_lt (hM : IsGradedSimple 𝒜 ℳ) {N : ℤ} (hA : ∀ n < N, 𝒜 n = ⊥)
    {v : M} {j : ℤ} (hv : v ∈ ℳ j) (hv0 : v ≠ 0) {i : ℤ} (hi : i < N + j) : ℳ i = ⊥ := by
  rw [eq_bot_iff]
  intro u hu
  obtain ⟨a, ha, rfl⟩ := hM.exists_eq_smul hv hv0 hu
  rw [hA (i - j) (by omega)] at ha
  rw [(Submodule.mem_bot k).1 ha, zero_smul]
  exact zero_mem _

omit [IsScalarTower k A M] in
/-- **Graded Nakayama.** If `𝒜` is bounded below, a central homogeneous element of positive
degree acts by zero on a graded simple module. -/
theorem smul_eq_zero_of_commute_of_mem (hM : IsGradedSimple 𝒜 ℳ) {N : ℤ}
    (hA : ∀ n < N, 𝒜 n = ⊥) {z : A} (hz : ∀ a : A, Commute z a) {d : ℤ} (hd : 0 < d)
    (hzd : z ∈ 𝒜 d) (m : M) : z • m = 0 := by
  let f : M →ₗ[A] M :=
    { toFun := fun m => z • m
      map_add' := smul_add z
      map_smul' := fun a m => by simp only [RingHom.id_apply, smul_smul, (hz a).eq] }
  have hhom : (LinearMap.range f).IsHomogeneous ℳ := by
    rintro i _ ⟨m, rfl⟩
    exact ⟨decompose ℳ m (i - d), by
      simp only [f, LinearMap.coe_mk, AddHom.coe_mk]
      rw [decompose_smul_of_mem_left 𝒜 ℳ hzd]⟩
  rcases hM.eq_bot_or_eq_top _ hhom with h | h
  · exact (LinearMap.range_eq_bot.1 h ▸ rfl : f m = 0)
  · exfalso
    haveI := hM.nontrivial
    obtain ⟨j, v, hv, hv0⟩ := exists_mem_ne_zero ℳ
    have key : ∀ i, ∀ u ∈ ℳ i, ∃ u' ∈ ℳ (i - d), u = z • u' := by
      intro i u hu
      obtain ⟨m, hm⟩ : u ∈ LinearMap.range f := h ▸ Submodule.mem_top
      refine ⟨decompose ℳ m (i - d), (decompose ℳ m (i - d)).2, ?_⟩
      rw [← decompose_smul_of_mem_left 𝒜 ℳ hzd, ← decompose_of_mem_same ℳ hu, ← hm]
      rfl
    have hn : ∀ n : ℕ, ∀ i, i < N + j + n * d → ∀ u ∈ ℳ i, u = 0 := by
      intro n
      induction n with
      | zero =>
        intro i hi u hu
        rw [hM.grade_eq_bot_of_lt hA hv hv0 (i := i) (by simpa using hi)] at hu
        exact (Submodule.mem_bot k).1 hu
      | succ n ih =>
        intro i hi u hu
        obtain ⟨u', hu', rfl⟩ := key i u hu
        rw [ih (i - d) (by push_cast at hi; linarith) u' hu', smul_zero]
    have h1 : ((Int.toNat (-N) + 1 : ℕ) : ℤ) ≤ (Int.toNat (-N) + 1 : ℕ) * d :=
      le_mul_of_one_le_right (by positivity) (by omega)
    have h2 : -N ≤ ((Int.toNat (-N) : ℕ) : ℤ) := Int.self_le_toNat (-N)
    exact hv0 (hn (Int.toNat (-N) + 1) j (by push_cast at h1 ⊢; linarith) v hv)

end IsGradedSimple

/-- The homogeneous components of a central element are central. -/
theorem commute_decompose {z : A} (hz : ∀ a : A, Commute z a) (d : ℤ) (a : A) :
    Commute (decompose 𝒜 z d : A) a := by
  induction a using Decomposition.inductionOn 𝒜 with
  | zero => exact Commute.zero_right _
  | add a b ha hb => exact ha.add_right hb
  | @homogeneous i a =>
    have h1 := coe_decompose_mul_add_of_right_mem 𝒜 (a := z) (i := d) a.2
    have h2 := coe_decompose_mul_add_of_left_mem 𝒜 (b := z) (j := d) a.2
    show _ * _ = _ * _
    rw [← h1, ← h2, (hz a).eq, add_comm]

namespace IsGradedSimple

variable {𝒜 ℳ 𝒩}

omit [IsScalarTower k A M] in
/-- **Graded Nakayama.** If `𝒜` is bounded below, a central element all of whose homogeneous
components have positive degree acts by zero on a graded simple module. -/
theorem smul_eq_zero_of_commute (hM : IsGradedSimple 𝒜 ℳ) {N : ℤ} (hA : ∀ n < N, 𝒜 n = ⊥)
    {z : A} (hz : ∀ a : A, Commute z a) (hpos : ∀ d ≤ 0, (decompose 𝒜 z d : A) = 0) (m : M) :
    z • m = 0 := by
  classical
  rw [← sum_support_decompose 𝒜 z, Finset.sum_smul]
  refine Finset.sum_eq_zero fun d _ => ?_
  by_cases hd : 0 < d
  · exact hM.smul_eq_zero_of_commute_of_mem hA (commute_decompose 𝒜 hz d) hd
      (decompose 𝒜 z d).2 m
  · rw [hpos d (not_lt.1 hd), zero_smul]

/-- A graded simple module killed by a subspace `J ⊆ A` with `A / J` finite-dimensional is
finite-dimensional (it is a quotient of `A / J`). -/
theorem finiteDimensional (hM : IsGradedSimple 𝒜 ℳ) (J : Submodule k A)
    (hJ : ∀ a ∈ J, ∀ m : M, a • m = 0) [FiniteDimensional k (A ⧸ J)] :
    FiniteDimensional k M := by
  haveI := hM.nontrivial
  obtain ⟨j, v, hv, hv0⟩ := exists_mem_ne_zero ℳ
  let f : A →ₗ[k] M := smulRightK v
  have hJf : J ≤ LinearMap.ker f := fun a ha => hJ a ha v
  refine Module.Finite.of_surjective (J.liftQ f hJf) fun m => ?_
  have : m ∈ Submodule.span A {v} := by rw [hM.span_singleton_eq_top hv hv0]; trivial
  obtain ⟨a, rfl⟩ := Submodule.mem_span_singleton.1 this
  exact ⟨Submodule.Quotient.mk a, rfl⟩

end IsGradedSimple

/-! ### Homogeneous kernels and images, shifts -/

section Maps

variable {𝒜 ℳ 𝒩}

omit [Algebra k A] [IsScalarTower k A M] [IsScalarTower k A N] [GradedAlgebra 𝒜]
  [SetLike.GradedSMul 𝒜 ℳ] [SetLike.GradedSMul 𝒜 𝒩] in
/-- A submodule is homogeneous for a shifted grading iff it is homogeneous for the grading. -/
theorem isHomogeneous_shift_iff (p : Submodule A M) (a : ℤ) :
    p.IsHomogeneous (shift ℳ a) ↔ p.IsHomogeneous ℳ := by
  constructor
  · intro hp d x hx
    rw [← decompose_shift ℳ a x d]
    exact hp (d + a) hx
  · intro hp d x hx
    have := decompose_shift ℳ a x (d - a)
    rw [sub_add_cancel] at this
    rw [this]
    exact hp (d - a) hx

omit [Algebra k A] [IsScalarTower k A M] [IsScalarTower k A N] [GradedAlgebra 𝒜]
  [SetLike.GradedSMul 𝒜 ℳ] [SetLike.GradedSMul 𝒜 𝒩] in
/-- The kernel of a degree-preserving map is homogeneous. -/
theorem isHomogeneous_ker {f : M →ₗ[A] N} (hf : PreservesGrading ℳ 𝒩 f) :
    (LinearMap.ker f).IsHomogeneous ℳ := by
  intro d x hx
  rw [LinearMap.mem_ker] at hx ⊢
  rw [← decompose_map hf, hx, decompose_zero, zero_apply, ZeroMemClass.coe_zero]

omit [Algebra k A] [IsScalarTower k A M] [IsScalarTower k A N] [GradedAlgebra 𝒜]
  [SetLike.GradedSMul 𝒜 ℳ] [SetLike.GradedSMul 𝒜 𝒩] in
/-- The image of a degree-preserving map is homogeneous. -/
theorem isHomogeneous_range {f : M →ₗ[A] N} (hf : PreservesGrading ℳ 𝒩 f) :
    (LinearMap.range f).IsHomogeneous 𝒩 := by
  rintro d _ ⟨x, rfl⟩
  exact decompose_mem_range hf x d

omit [IsScalarTower k A M] [IsScalarTower k A N] [GradedAlgebra 𝒜] [SetLike.GradedSMul 𝒜 ℳ]
  [SetLike.GradedSMul 𝒜 𝒩] in
/-- A bijective degree-preserving map is a graded isomorphism. -/
noncomputable def GradedEquiv.ofBijective {f : M →ₗ[A] N} (hf : PreservesGrading ℳ 𝒩 f)
    (hbij : Function.Bijective f) : ℳ ≃ᵍ[A] 𝒩 where
  toLinearEquiv := LinearEquiv.ofBijective f hbij
  map_mem' := hf
  symm_map_mem' d y hy := by
    set x := (LinearEquiv.ofBijective f hbij).symm y with hx
    have hfx : f x = y := (LinearEquiv.ofBijective f hbij).apply_symm_apply y
    have : f (decompose ℳ x d : M) = f x := by
      rw [← decompose_map hf, hfx, decompose_of_mem_same _ hy]
    rw [← hbij.1 this]
    exact (decompose ℳ x d).2

end Maps

namespace IsGradedSimple

variable {𝒜 ℳ 𝒩}

omit [IsScalarTower k A M] [GradedAlgebra 𝒜] [SetLike.GradedSMul 𝒜 ℳ] in
/-- Grading shifts of graded simple modules are graded simple. -/
theorem shift (hM : IsGradedSimple 𝒜 ℳ) (a : ℤ) : IsGradedSimple 𝒜 (Graded.shift ℳ a) :=
  ⟨hM.nontrivial, fun p hp => hM.eq_bot_or_eq_top p ((isHomogeneous_shift_iff p a).1 hp)⟩

omit [IsScalarTower k A M] [IsScalarTower k A N] [GradedAlgebra 𝒜] [SetLike.GradedSMul 𝒜 ℳ]
  [SetLike.GradedSMul 𝒜 𝒩] in
/-- **Graded Schur lemma**: a nonzero degree-preserving map between graded simple modules is
bijective. -/
theorem bijective_of_preservesGrading (hM : IsGradedSimple 𝒜 ℳ) (hN : IsGradedSimple 𝒜 𝒩)
    {f : M →ₗ[A] N} (hf : PreservesGrading ℳ 𝒩 f) (hf0 : f ≠ 0) : Function.Bijective f := by
  refine ⟨?_, ?_⟩
  · rcases hM.eq_bot_or_eq_top _ (isHomogeneous_ker hf) with h | h
    · exact LinearMap.ker_eq_bot.1 h
    · exact absurd (LinearMap.ker_eq_top.1 h) hf0
  · rcases hN.eq_bot_or_eq_top _ (isHomogeneous_range hf) with h | h
    · exact absurd (LinearMap.range_eq_bot.1 h) hf0
    · exact LinearMap.range_eq_top.1 h

omit [IsScalarTower k A M] [GradedAlgebra 𝒜] [SetLike.GradedSMul 𝒜 ℳ] in
/-- The degrees of a finite-dimensional graded module form a finite set. -/
theorem _root_.Categorification.Graded.finite_setOf_ne_bot [FiniteDimensional k M] :
    {d : ℤ | ℳ d ≠ ⊥}.Finite := by
  haveI := (Decomposition.isInternal ℳ).submodule_iSupIndep.fintypeNeBotOfFiniteDimensional
  show Finite {d // ℳ d ≠ ⊥}
  infer_instance

omit [IsScalarTower k A M] [GradedAlgebra 𝒜] [SetLike.GradedSMul 𝒜 ℳ] in
/-- A finite-dimensional graded module is bounded: `ℳ d = 0` outside `[L, U]`. -/
theorem _root_.Categorification.Graded.exists_bounds [FiniteDimensional k M] :
    ∃ L U : ℤ, ∀ d, (d < L ∨ U < d) → ℳ d = ⊥ := by
  obtain ⟨L, hL⟩ := (finite_setOf_ne_bot (ℳ := ℳ)).bddBelow
  obtain ⟨U, hU⟩ := (finite_setOf_ne_bot (ℳ := ℳ)).bddAbove
  refine ⟨L, U, fun d hd => ?_⟩
  by_contra h
  rcases hd with hd | hd
  · exact absurd (hL h) (not_le.2 hd)
  · exact absurd (hU h) (not_le.2 hd)

omit [IsScalarTower k A M] [GradedAlgebra 𝒜] [SetLike.GradedSMul 𝒜 ℳ] in
/-- **`Hom(M, M{a}) = 0` for `a ≠ 0`** (KL I, Proposition 2.12): a finite-dimensional graded simple
module has no nonzero `A`-linear endomorphism of nonzero degree. -/
theorem eq_zero_of_preservesGrading_shift [FiniteDimensional k M] (hM : IsGradedSimple 𝒜 ℳ)
    {a : ℤ} (ha : a ≠ 0) {f : M →ₗ[A] M} (hf : PreservesGrading ℳ (Graded.shift ℳ a) f) :
    f = 0 := by
  by_contra hf0
  have hinj : Function.Injective f := by
    rcases hM.eq_bot_or_eq_top _ (isHomogeneous_ker hf) with h | h
    · exact LinearMap.ker_eq_bot.1 h
    · exact absurd (LinearMap.ker_eq_top.1 h) hf0
  haveI := hM.nontrivial
  obtain ⟨j, v, hv, hv0⟩ := exists_mem_ne_zero ℳ
  have hiter : ∀ n : ℕ, f^[n] v ∈ ℳ (j - n * a) ∧ f^[n] v ≠ 0 := by
    intro n
    induction n with
    | zero => simpa using ⟨hv, hv0⟩
    | succ n ih =>
      rw [Function.iterate_succ_apply']
      refine ⟨?_, fun h => ih.2 (hinj (by rw [h, map_zero]))⟩
      have := hf ih.1
      rw [mem_shift] at this
      convert this using 2
      push_cast; ring
  refine Set.infinite_of_injective_forall_mem (f := fun n : ℕ => j - n * a) ?_ (fun n => ?_)
    (finite_setOf_ne_bot (ℳ := ℳ))
  · intro n n' h
    have : ((n : ℤ) - n') * a = 0 := by simp only at h; linarith
    rcases mul_eq_zero.1 this with h' | h'
    · exact_mod_cast sub_eq_zero.1 h'
    · exact absurd h' ha
  · intro h
    exact (hiter n).2 ((Submodule.mem_bot k).1 (h ▸ (hiter n).1))

/-- **A finite-dimensional graded simple module is simple as an ungraded module** (KL I,
Proposition 2.12). For a nonzero submodule `P`, the leading homogeneous components of the
elements of `P` span a nonzero homogeneous submodule, hence everything; an induction on the
degree then shows `P = M`. -/
theorem isSimpleModule [FiniteDimensional k M] (hM : IsGradedSimple 𝒜 ℳ) : IsSimpleModule A M := by
  classical
  haveI := hM.nontrivial
  obtain ⟨L, U, hLU⟩ := exists_bounds (ℳ := ℳ)
  have hcomp : ∀ (x : M) d, (d < L ∨ U < d) → (decompose ℳ x d : M) = 0 := fun x d hd =>
    (Submodule.mem_bot k).1 (by rw [← hLU d hd]; exact (decompose ℳ x d).2)
  refine { eq_bot_or_eq_top := fun P => ?_ }
  by_cases hP : P = ⊥
  · exact Or.inl hP
  right
  -- `T d`: the leading components in degree `d` of elements of `P`.
  let T : ℤ → Submodule k M := fun d =>
    { carrier := {y | ∃ n ∈ P, (∀ e, d < e → (decompose ℳ n e : M) = 0) ∧
        (decompose ℳ n d : M) = y}
      add_mem' := by
        rintro _ _ ⟨n, hn, hn1, rfl⟩ ⟨n', hn', hn1', rfl⟩
        exact ⟨n + n', P.add_mem hn hn', fun e he => by
          simp [decompose_add, hn1 e he, hn1' e he], by simp [decompose_add]⟩
      zero_mem' := ⟨0, P.zero_mem, fun e _ => by simp, by simp⟩
      smul_mem' := by
        rintro c _ ⟨n, hn, hn1, rfl⟩
        refine ⟨c • n, ?_, fun e he => by
          rw [decompose_smul, DirectSum.smul_apply, Submodule.coe_smul, hn1 e he, smul_zero], by
          rw [decompose_smul, DirectSum.smul_apply, Submodule.coe_smul]⟩
        rw [← algebraMap_smul A c n]
        exact P.smul_mem _ hn }
  have hTmem : ∀ d y, y ∈ T d → y ∈ ℳ d := by
    rintro d _ ⟨n, -, -, rfl⟩
    exact (decompose ℳ n d).2
  have hTsmul : ∀ i (a : A), a ∈ 𝒜 i → ∀ d y, y ∈ T d → a • y ∈ T (d + i) := by
    rintro i a ha d _ ⟨n, hn, hn1, rfl⟩
    refine ⟨a • n, P.smul_mem a hn, fun e he => ?_, ?_⟩
    · rw [decompose_smul_of_mem_left 𝒜 ℳ ha, hn1 (e - i) (by omega), smul_zero]
    · rw [decompose_smul_of_mem_left 𝒜 ℳ ha, add_sub_cancel_right]
  let W : Submodule k M := ⨆ d, T d
  have hWdec : ∀ w ∈ W, ∀ d, (decompose ℳ w d : M) ∈ T d := by
    intro w hw d
    refine Submodule.iSup_induction T (motive := fun w => (decompose ℳ w d : M) ∈ T d) hw
      ?_ ?_ ?_
    · intro e y hy
      by_cases h : e = d
      · subst h; rw [decompose_of_mem_same _ (hTmem _ _ hy)]; exact hy
      · rw [decompose_of_mem_ne _ (hTmem _ _ hy) h]; exact zero_mem _
    · simp only [decompose_zero, zero_apply, ZeroMemClass.coe_zero]; exact zero_mem _
    · intro x y hx hy
      simp only [decompose_add, add_apply, Submodule.coe_add]; exact add_mem hx hy
  have hWA : ∀ a : A, ∀ w ∈ W, a • w ∈ W := by
    intro a w hw
    refine Submodule.iSup_induction T (motive := fun w => a • w ∈ W) hw ?_ ?_ ?_
    · intro e y hy
      rw [← sum_support_decompose 𝒜 a, Finset.sum_smul]
      exact Submodule.sum_mem _ fun i _ =>
        Submodule.mem_iSup_of_mem (e + i) (hTsmul i _ (decompose 𝒜 a i).2 e y hy)
    · show a • (0 : M) ∈ W
      rw [smul_zero]; exact zero_mem _
    · intro x y hx hy
      show a • (x + y) ∈ W
      rw [smul_add]; exact add_mem hx hy
  let W' : Submodule A M :=
    { carrier := W
      add_mem' := W.add_mem
      zero_mem' := W.zero_mem
      smul_mem' := fun a w hw => hWA a w hw }
  have hW'hom : W'.IsHomogeneous ℳ := fun d w hw => Submodule.mem_iSup_of_mem d (hWdec w hw d)
  have hW'ne : W' ≠ ⊥ := by
    obtain ⟨n, hn, hn0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hP
    have hsupp : (decompose ℳ n).support.Nonempty := by
      rw [Finset.nonempty_iff_ne_empty]
      intro h
      apply hn0
      rw [← sum_support_decompose ℳ n, h, Finset.sum_empty]
    set D := (decompose ℳ n).support.max' hsupp
    have hD : (decompose ℳ n D : M) ≠ 0 := by
      have := (decompose ℳ n).support.max'_mem hsupp
      rw [DFinsupp.mem_support_iff] at this
      exact fun h => this (Subtype.ext h)
    have hT : (decompose ℳ n D : M) ∈ T D := ⟨n, hn, fun e he => by
      have : e ∉ (decompose ℳ n).support := fun h' =>
        absurd ((decompose ℳ n).support.le_max' e h') (not_le.2 he)
      rw [DFinsupp.not_mem_support_iff] at this
      rw [this, ZeroMemClass.coe_zero], rfl⟩
    intro h
    have : (decompose ℳ n D : M) ∈ W' := Submodule.mem_iSup_of_mem D hT
    rw [h] at this
    exact hD ((Submodule.mem_bot A).1 this)
  have hW'top : W' = ⊤ := (hM.eq_bot_or_eq_top W' hW'hom).resolve_left hW'ne
  have hTall : ∀ d, ∀ y ∈ ℳ d, y ∈ T d := by
    intro d y hy
    have hyW : y ∈ W := (show y ∈ W' from hW'top ▸ Submodule.mem_top)
    have := hWdec y hyW d
    rwa [decompose_of_mem_same _ hy] at this
  have hind : ∀ D, L - 1 ≤ D → ∀ x : M, (∀ e, D < e → (decompose ℳ x e : M) = 0) → x ∈ P := by
    intro D hD
    refine Int.le_induction (P := fun D => ∀ x : M, (∀ e, D < e → (decompose ℳ x e : M) = 0) →
      x ∈ P) ?_ ?_ D hD
    · intro x hx
      rw [← sum_support_decompose ℳ x]
      refine Submodule.sum_mem _ fun e _ => ?_
      by_cases he : e < L
      · rw [hcomp x e (Or.inl he)]; exact zero_mem _
      · rw [hx e (by omega)]; exact zero_mem _
    · intro D _ ih x hx
      obtain ⟨n, hn, hn1, hny⟩ := hTall (D + 1) _ (decompose ℳ x (D + 1)).2
      have hxn : x - n ∈ P := ih _ fun e he => by
        rw [decompose_sub, sub_apply, Submodule.coe_sub]
        rcases eq_or_lt_of_le (show D + 1 ≤ e by omega) with h | h
        · subst h; rw [hny, sub_self]
        · rw [hx e h, hn1 e h, sub_self]
      simpa using P.add_mem hxn hn
  rw [eq_top_iff]
  intro x _
  exact hind (max U (L - 1)) (le_max_right _ _) x fun e he =>
    hcomp x e (Or.inr (lt_of_le_of_lt (le_max_left _ _) he))

omit [IsScalarTower k A M] [IsScalarTower k A N] in
/-- Graded simple modules with a nonzero (not necessarily degree-preserving) `A`-linear map
between them are isomorphic up to a grading shift: `M ≅ N{c}` for some `c`. -/
theorem exists_gradedEquiv_shift_of_ne_zero (hM : IsGradedSimple 𝒜 ℳ)
    (hN : IsGradedSimple 𝒜 𝒩) {f : M →ₗ[A] N} (hf : f ≠ 0) :
    ∃ c : ℤ, Nonempty (ℳ ≃ᵍ[A] Graded.shift 𝒩 c) := by
  classical
  haveI := hM.nontrivial
  obtain ⟨j, v, hv, hv0⟩ := exists_mem_ne_zero ℳ
  have hspan := hM.span_singleton_eq_top hv hv0
  have hmem : ∀ m : M, ∃ a : A, a • v = m := fun m => by
    have : m ∈ Submodule.span A {v} := hspan ▸ Submodule.mem_top
    exact Submodule.mem_span_singleton.1 this
  have hfv : f v ≠ 0 := by
    intro h
    apply hf
    ext m
    obtain ⟨a, rfl⟩ := hmem m
    rw [map_smul, h, smul_zero, LinearMap.zero_apply]
  obtain ⟨e, he⟩ : ∃ e, (decompose 𝒩 (f v) e : N) ≠ 0 := by
    by_contra h
    push_neg at h
    apply hfv
    rw [← sum_support_decompose 𝒩 (f v)]
    exact Finset.sum_eq_zero fun e _ => h e
  set y := (decompose 𝒩 (f v) e : N) with hy_def
  have hy : y ∈ 𝒩 e := (decompose 𝒩 (f v) e).2
  have hann : ∀ a : A, a • v = 0 → a • y = 0 := by
    intro a ha
    rw [← sum_support_decompose 𝒜 a, Finset.sum_smul]
    refine Finset.sum_eq_zero fun i _ => ?_
    have h1 : (decompose 𝒜 a i : A) • v = 0 := by
      have := decompose_smul_of_mem 𝒜 ℳ a hv (i + j)
      rw [ha, decompose_zero, zero_apply, ZeroMemClass.coe_zero, add_sub_cancel_right] at this
      exact this.symm
    have h2 := decompose_smul_of_mem_left 𝒜 𝒩 (decompose 𝒜 a i).2 (f v) (i + e)
    rw [← map_smul, h1, map_zero, decompose_zero, zero_apply, ZeroMemClass.coe_zero,
      add_sub_cancel_left] at h2
    exact h2.symm
  let φ : A →ₗ[A] M := LinearMap.toSpanSingleton A M v
  have hφ : Function.Surjective φ := fun m => hmem m
  let χ : A →ₗ[A] N := LinearMap.toSpanSingleton A N y
  have hle : LinearMap.ker φ ≤ LinearMap.ker χ := fun a ha => hann a ha
  let g : M →ₗ[A] N :=
    ((LinearMap.ker φ).liftQ χ hle).comp (φ.quotKerEquivOfSurjective hφ).symm.toLinearMap
  have hg : ∀ a : A, g (a • v) = a • y := by
    intro a
    have : (φ.quotKerEquivOfSurjective hφ).symm (a • v) = Submodule.Quotient.mk a := by
      rw [LinearEquiv.symm_apply_eq]; rfl
    simp only [g, LinearMap.comp_apply, LinearEquiv.coe_coe, this, Submodule.liftQ_apply]
    rfl
  have hgr : PreservesGrading ℳ (Graded.shift 𝒩 (j - e)) g := by
    intro d x hx
    obtain ⟨a, ha, rfl⟩ := hM.exists_eq_smul hv hv0 hx
    rw [hg, mem_shift]
    have := SetLike.GradedSMul.smul_mem (A := 𝒜) (B := 𝒩) ha hy
    convert this using 2
    simp only [vadd_eq_add]
    ring
  have hg0 : g ≠ 0 := fun h => he (by
    have := hg 1
    rw [one_smul, one_smul, h, LinearMap.zero_apply] at this
    exact this.symm)
  exact ⟨j - e, ⟨GradedEquiv.ofBijective hgr
    (hM.bijective_of_preservesGrading (hN.shift _) hgr hg0)⟩⟩

omit [IsScalarTower k A M] [GradedAlgebra 𝒜] [SetLike.GradedSMul 𝒜 ℳ] in
/-- The grading shift of a finite-dimensional graded simple module is determined by its
isomorphism class: `M ≅ M{a}` only for `a = 0`. -/
theorem eq_zero_of_gradedEquiv_shift [FiniteDimensional k M] (hM : IsGradedSimple 𝒜 ℳ) {a : ℤ}
    (e : ℳ ≃ᵍ[A] Graded.shift ℳ a) : a = 0 := by
  by_contra ha
  haveI := hM.nontrivial
  have h0 := hM.eq_zero_of_preservesGrading_shift ha e.preservesGrading
  obtain ⟨m, hm⟩ := exists_ne (0 : M)
  apply hm
  have : e m = 0 := LinearMap.congr_fun h0 m
  exact e.toLinearEquiv.injective (by rw [map_zero]; exact this)

end IsGradedSimple

end Graded

/-! ### Counting simple quotients -/

section Count

variable {k A X : Type*} [Field k] [Ring A] [Algebra k A] [AddCommGroup X] [Module A X]
  [Module k X] [IsScalarTower k A X]

/-- **Finitely many simple quotients.** A finite-dimensional module `X` has at most
`dim_k X` pairwise non-isomorphic simple quotients: if `f_b : X ↠ T_b` (`b ∈ ι`) are surjections
onto pairwise non-isomorphic simple modules, then `ι` is finite with `|ι| ≤ dim_k X`. -/
theorem card_le_finrank_of_isSimpleModule [FiniteDimensional k X] {ι : Type*} (T : ι → Type*)
    [∀ b, AddCommGroup (T b)] [∀ b, Module A (T b)] [∀ b, IsSimpleModule A (T b)]
    (f : ∀ b, X →ₗ[A] T b) (hf : ∀ b, Function.Surjective (f b))
    (hT : ∀ b b', Nonempty (T b ≃ₗ[A] T b') → b = b') :
    Finite ι ∧ Nat.card ι ≤ Module.finrank k X := by
  classical
  have key : ∀ s : Finset ι, ∀ P : Submodule A X,
      (∀ b ∈ s, Function.Surjective ((f b).comp P.subtype)) →
        s.card ≤ Module.finrank k (P.restrictScalars k) := by
    intro s
    induction s using Finset.induction_on with
    | empty => intro P _; simp
    | @insert b₀ s hb₀ ih =>
      intro P hP
      set F₀ := (f b₀).comp P.subtype with hF₀
      have hs₀ : Function.Surjective F₀ := hP b₀ (Finset.mem_insert_self _ _)
      let K : Submodule A X := (LinearMap.ker F₀).map P.subtype
      have hKP : K ≤ P := by
        rintro _ ⟨p, -, rfl⟩
        exact p.2
      have hKs : ∀ b ∈ s, Function.Surjective ((f b).comp K.subtype) := by
        intro b hb
        have hsb : Function.Surjective ((f b).comp P.subtype) := hP b (Finset.mem_insert_of_mem hb)
        rcases IsSimpleOrder.eq_bot_or_eq_top (LinearMap.range ((f b).comp K.subtype)) with h | h
        · exfalso
          have hle : LinearMap.ker F₀ ≤ LinearMap.ker ((f b).comp P.subtype) := by
            intro p hp
            have : (f b).comp K.subtype ⟨p, ⟨p, hp, rfl⟩⟩ ∈ LinearMap.range ((f b).comp K.subtype) :=
              LinearMap.mem_range_self _ _
            rw [h] at this
            exact (Submodule.mem_bot A).1 this
          let g : T b₀ →ₗ[A] T b :=
            ((LinearMap.ker F₀).liftQ _ hle).comp (F₀.quotKerEquivOfSurjective hs₀).symm.toLinearMap
          have hg : ∀ p, g (F₀ p) = (f b).comp P.subtype p := by
            intro p
            have : (F₀.quotKerEquivOfSurjective hs₀).symm (F₀ p) = Submodule.Quotient.mk p := by
              rw [LinearEquiv.symm_apply_eq]; rfl
            simp only [g, LinearMap.comp_apply, LinearEquiv.coe_coe, this, Submodule.liftQ_apply]
          have hg0 : g ≠ 0 := by
            intro h0
            haveI := IsSimpleModule.nontrivial A (T b)
            obtain ⟨t, ht⟩ := exists_ne (0 : T b)
            obtain ⟨p, rfl⟩ := hsb t
            apply ht
            rw [← hg, h0, LinearMap.zero_apply]
          have := hT b₀ b ⟨LinearEquiv.ofBijective g (LinearMap.bijective_of_ne_zero hg0)⟩
          exact hb₀ (this ▸ hb)
        · exact LinearMap.range_eq_top.1 h
      have hlt : K.restrictScalars k < P.restrictScalars k := by
        refine lt_of_le_of_ne hKP fun h => ?_
        haveI := IsSimpleModule.nontrivial A (T b₀)
        obtain ⟨t, ht⟩ := exists_ne (0 : T b₀)
        obtain ⟨p, rfl⟩ := hs₀ t
        apply ht
        have : (p : X) ∈ K := by
          have : (p : X) ∈ K.restrictScalars k := h ▸ p.2
          exact this
        obtain ⟨p', hp', hpp'⟩ := this
        have : p' = p := Subtype.ext hpp'
        rw [← this]
        exact hp'
      have h1 := ih K hKs
      have h2 := Submodule.finrank_lt_finrank_of_lt hlt
      rw [Finset.card_insert_of_not_mem hb₀]
      omega
  have htop : Module.finrank k ((⊤ : Submodule A X).restrictScalars k) = Module.finrank k X := by
    rw [Submodule.restrictScalars_top, finrank_top]
  have hall : ∀ s : Finset ι, s.card ≤ Module.finrank k X := fun s => by
    rw [← htop]
    exact key s ⊤ fun b _ x => by
      obtain ⟨y, rfl⟩ := hf b x
      exact ⟨⟨y, Submodule.mem_top⟩, rfl⟩
  have hfin : Finite ι := by
    rcases finite_or_infinite ι with h | h
    · exact h
    exfalso
    obtain ⟨s, hs⟩ := Infinite.exists_subset_card_eq ι (Module.finrank k X + 1)
    have := hall s
    omega
  refine ⟨hfin, ?_⟩
  haveI := Fintype.ofFinite ι
  rw [Nat.card_eq_fintype_card, ← Finset.card_univ]
  exact hall _

end Count

end Categorification.Graded
