/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import StringDiagrams.Biadjunction.PivotalExtension
import StringDiagrams.Grading
import Categorification.QuantumGroup.UDotBlock

/-!
# The signature of the 2-category `U` of Khovanov–Lauda III

M. Khovanov, A. Lauda, *A categorification of quantum `sl(n)`*, arXiv:0807.3250v1, §3.1.1,
Definition 3.1 (TeX label `def_Ucat`).

Fix a root datum `RD` of type `(I, ·)` (`QuantumGroup.UDot.RootDatum`). The 2-category `U` has

* objects (regions) the weights `λ ∈ X`;
* 1-morphisms generated by the strands `E_{+i} 1_λ = 1_{λ+i_X} E_i 1_λ` (oriented up) and
  `E_{-i} 1_λ = 1_{λ-i_X} F_i 1_λ` (oriented down);
* generating 2-morphisms: upward and downward dots, upward and downward crossings, and the
  four cups and caps (KL III, Definition 3.1, item ii)).

## Conventions

A strand colour `Col` is a signed letter `l = (ε, i)` (`true = +`, `false = -`, as for the signed
sequences of `QuantumGroup.UDot`) together with the weight `r` of the region to its **right**;
the region to its left is `sh l + r` with `sh (ε, i) = ε i_X` (`sh`). So `⟨(true, i), λ⟩` is the
identity 1-morphism of `E_{+i} 1_λ` and `⟨(false, i), λ⟩` that of `E_{-i} 1_λ`.

The library reads words from left to right, starting in the leftmost region, and the presented
bicategory `P.Bicat` has 1-morphisms `l ⟶ m` from the left region `l` to the right region `m`.
KL III writes a 1-morphism `E_i 1_λ : λ → λ + i_X` with `λ` on the right. Hence a KL III
1-morphism `λ → λ'` is a library 1-morphism `⟨λ'⟩ ⟶ ⟨λ⟩`; composition of KL III 1-morphisms
(right to left) is concatenation of words, as in the library. 2-morphisms are read bottom to top
in both.

The cups and caps are not generators of the base signature `sig0`: `psig` is the *pivotal
extension* (`Signature.pivotal`) of `sig0` for the involution `c ↦ c*` (`inv`) exchanging
`E_{+i}` and `E_{-i}` (`⟨l, r⟩* = ⟨l*, sh l + r⟩`). For a colour `c` the pivotal extension adds
the cup `1 ⟶ c c*` in the left region of `c` and the cap `c* c ⟶ 1` in the right region of `c`.
With `λ` the outer region these are exactly the four cups and caps of Definition 3.1:

| KL III                            | library                                  | degree        |
|-----------------------------------|------------------------------------------|---------------|
| cup `1_λ → F E 1_λ` (`bbpef`)     | `cup ⟨(false, i), λ + i_X⟩`              | `c_{+i,λ}`    |
| cup `1_λ → E F 1_λ` (`bbpfe`)     | `cup ⟨(true, i), λ - i_X⟩`               | `c_{-i,λ}`    |
| cap `F E 1_λ → 1_λ` (`bbcef`)     | `cap ⟨(true, i), λ⟩`                     | `c_{+i,λ}`    |
| cap `E F 1_λ → 1_λ` (`bbcfe`)     | `cap ⟨(false, i), λ⟩`                    | `c_{-i,λ}`    |

with `c_{±i,λ} = (i·i/2)(1 ± ⟨i,λ⟩)` (KL III eq. (2.19), label `eq_cpm_lambda`); see `deg`.

## Normal forms

All regions of a diagram are determined by the signed letters of its boundary words and by the
weight `μ` of its rightmost region, which never changes. We therefore describe objects and layers
by signed sequences: `ob μ t` is the word of the signed sequence `t` with rightmost region `μ`
(its leftmost region is `wt μ t = μ + t_X`), and `lay μ u g v` is the layer with the generator
of shape `g` (`Shape`) between the strands `u` and `v`. Diagrams are given by lists of such
triples (`mkD`), with a typing condition on signed sequences only (`SChain`).

## Main definitions

* `sig0 RD`, `inv RD`, `psig RD`; `Shape`, `Shape.gen`; `ob`, `lay`, `lay_valid`, `lay_dom`,
  `lay_cod`, `SChain`, `mkD`.
* `deg RD : (psig RD).Gen → ℤ`: the degrees of Definition 3.1.
-/

noncomputable section

namespace Categorification.KL3.Diagram

open CategoryTheory StringDiagrams QuantumGroup UDot

universe u v

/-! ## Signed letters and weights -/

/-- A signed letter: `(true, i)` stands for `E_{+i} = E_i` and `(false, i)` for `E_{-i} = F_i`. -/
abbrev Letter (I : Type u) : Type u := Bool × I

/-- The dual letter `(ε, i)* = (-ε, i)`. -/
def Letter.dual {I : Type u} (l : Letter I) : Letter I := (!l.1, l.2)

@[simp] theorem Letter.dual_dual {I : Type u} (l : Letter I) : l.dual.dual = l := by
  simp [Letter.dual]

@[simp] theorem Letter.dual_mk {I : Type u} (b : Bool) (i : I) :
    Letter.dual (b, i) = (!b, i) := rfl

variable {I : Type u} {C : CartanDatum I} {X Y : Type v} [AddCommGroup X] [AddCommGroup Y]
  (RD : RootDatum C X Y)

/-- The weight `ε i_X` of the signed letter `(ε, i)`. -/
def sh (l : Letter I) : X := sgn l.1 • RD.iX l.2

theorem sh_dual (l : Letter I) : sh RD l.dual = -sh RD l := by
  simp [sh, Letter.dual, neg_smul]

theorem sh_add_sh_dual (l : Letter I) : sh RD l + sh RD l.dual = 0 := by
  rw [sh_dual, add_neg_cancel]

theorem sh_dual_add_sh (l : Letter I) : sh RD l.dual + sh RD l = 0 := by
  rw [sh_dual, neg_add_cancel]

/-- The weight `μ + t_X` of the region to the left of the signed sequence `t`, whose rightmost
region is `μ`. -/
def wt (μ : X) : List (Letter I) → X
  | [] => μ
  | l :: t => sh RD l + wt μ t

@[simp] theorem wt_nil (μ : X) : wt RD μ [] = μ := rfl

@[simp] theorem wt_cons (μ : X) (l : Letter I) (t : List (Letter I)) :
    wt RD μ (l :: t) = sh RD l + wt RD μ t := rfl

theorem wt_append (μ : X) (a b : List (Letter I)) : wt RD μ (a ++ b) = wt RD (wt RD μ b) a := by
  induction a with
  | nil => rfl
  | cons l a ih => simp [ih]

theorem wt_eq_add_wX (μ : X) (t : List (Letter I)) : wt RD μ t = RD.wX t + μ := by
  induction t with
  | nil => simp
  | cons l t ih => simp [ih, sh, add_assoc]

/-- A strand colour: a signed letter and the weight of the region to its right. -/
@[ext]
structure Col (I : Type u) (X : Type v) where
  /-- The signed letter. -/
  l : Letter I
  /-- The weight of the region to the right of the strand. -/
  r : X

/-- The colours of the signed sequence `t` with rightmost region `μ`. -/
def wd (μ : X) : List (Letter I) → List (Col I X)
  | [] => []
  | l :: t => ⟨l, wt RD μ t⟩ :: wd μ t

@[simp] theorem wd_nil (μ : X) : wd RD μ [] = [] := rfl

@[simp] theorem wd_cons (μ : X) (l : Letter I) (t : List (Letter I)) :
    wd RD μ (l :: t) = ⟨l, wt RD μ t⟩ :: wd RD μ t := rfl

theorem wd_append (μ : X) (a b : List (Letter I)) :
    wd RD μ (a ++ b) = wd RD (wt RD μ b) a ++ wd RD μ b := by
  induction a with
  | nil => rfl
  | cons l a ih => simp [ih, wt_append]

theorem wd_injective (μ : X) : Function.Injective (wd RD μ) := by
  intro a b h
  induction a generalizing b with
  | nil => cases b with
    | nil => rfl
    | cons _ _ => cases h
  | cons l a ih => cases b with
    | nil => cases h
    | cons l' b =>
      simp only [wd_cons, List.cons.injEq, Col.mk.injEq] at h
      rw [h.1.1, ih h.2]

/-! ## The base signature -/

/-- The generators of `U` other than cups and caps (KL III Definition 3.1 ii)):

* `dot c`: a dot on a strand of colour `c` (the upward dot of KL III if `c.l.1 = true`, the
  downward dot otherwise);
* `cross ε i j ν`: the crossing `E_{εi} E_{εj} 1_ν ⟶ E_{εj} E_{εi} 1_ν` of two upward strands
  (`ε = true`) or of two downward strands (`ε = false`), with rightmost region `ν`. -/
inductive Gen0 (I : Type u) (X : Type v)
  | dot (c : Col I X)
  | cross (ε : Bool) (i j : I) (ν : X)

/-- The base signature: regions `X`, colours `Col`, dots and crossings (all even). -/
def sig0 : Signature.{v, max u v, max u v} where
  Region := X
  Colour := Col I X
  colourSrc c := sh RD c.l + c.r
  colourTgt c := c.r
  Gen := Gen0 I X
  dom
    | .dot c => [c]
    | .cross ε i j ν => wd RD ν [(ε, i), (ε, j)]
  cod
    | .dot c => [c]
    | .cross ε i j ν => wd RD ν [(ε, j), (ε, i)]
  left
    | .dot c => sh RD c.l + c.r
    | .cross ε i j ν => wt RD ν [(ε, i), (ε, j)]
  right
    | .dot c => c.r
    | .cross _ _ _ ν => ν

instance : (sig0 RD).IsEven := ⟨fun _ => rfl⟩

/-- The involution `⟨l, r⟩* = ⟨l*, sh l + r⟩` on colours, exchanging `E_{+i} 1_λ` and
`E_{-i} 1_{λ+i_X}`. -/
def inv : (sig0 RD).ColourInvolution where
  dual c := ⟨c.l.dual, sh RD c.l + c.r⟩
  src_dual c := by
    show sh RD c.l.dual + (sh RD c.l + c.r) = c.r
    rw [← add_assoc, sh_dual_add_sh, zero_add]
  tgt_dual _ := rfl
  dual_dual c := by
    show (⟨c.l.dual.dual, sh RD c.l.dual + (sh RD c.l + c.r)⟩ : Col I X) = c
    rw [← add_assoc, sh_dual_add_sh, zero_add, Letter.dual_dual]
    rfl

/-- The signature of `U`: the pivotal extension of `sig0` for the involution `inv`, which adds a
cup `1 ⟶ c c*` and a cap `c* c ⟶ 1` for every colour `c`. -/
abbrev psig : Signature := (sig0 RD).pivotal (inv RD).toColourDuality

instance : (psig RD).IsEven := Signature.pivotal_isEven _

@[simp] theorem psig_colourSrc (c : Col I X) : (psig RD).colourSrc c = sh RD c.l + c.r := rfl
@[simp] theorem psig_colourTgt (c : Col I X) : (psig RD).colourTgt c = c.r := rfl

theorem inv_dual (c : Col I X) : (inv RD).dual c = ⟨c.l.dual, sh RD c.l + c.r⟩ := rfl

/-! ## Well-formed words -/

theorem ok_wd (μ : X) (t : List (Letter I)) : (psig RD).ok (wt RD μ t : X) (wd RD μ t) := by
  induction t with
  | nil => trivial
  | cons l t ih => exact ⟨rfl, ih⟩

theorem endR_wd (μ : X) (t : List (Letter I)) : (psig RD).endR (wt RD μ t : X) (wd RD μ t) = μ := by
  induction t with
  | nil => rfl
  | cons l t ih => exact ih

/-- The object given by the signed sequence `t` with rightmost region `μ`: the 1-morphism
`E_t 1_μ` (from `μ` to `μ + t_X` in KL III). -/
def ob (μ : X) (t : List (Letter I)) : Obj (psig RD) := ⟨(wt RD μ t : X), wd RD μ t⟩

@[simp] theorem ob_start (μ : X) (t : List (Letter I)) : (ob RD μ t).start = wt RD μ t := rfl
@[simp] theorem ob_word (μ : X) (t : List (Letter I)) : (ob RD μ t).word = wd RD μ t := rfl

theorem ob_wf (μ : X) (t : List (Letter I)) : (ob RD μ t).WF := ok_wd RD μ t

theorem ob_endR (μ : X) (t : List (Letter I)) : (ob RD μ t).endR = μ := endR_wd RD μ t

/-! ## Shapes of generators -/

/-- The shape of a generator of `psig`, without its weights. -/
inductive Shape (I : Type u)
  /-- A dot on the strand `l`. -/
  | dot (l : Letter I)
  /-- A crossing `(ε, i) (ε, j) ⟶ (ε, j) (ε, i)`. -/
  | cross (ε : Bool) (i j : I)
  /-- The cup `1 ⟶ l l*`. -/
  | cup (l : Letter I)
  /-- The cap `l* l ⟶ 1`. -/
  | cap (l : Letter I)

namespace Shape

/-- Bottom boundary of a shape. -/
def dom : Shape I → List (Letter I)
  | dot l => [l]
  | cross ε i j => [(ε, i), (ε, j)]
  | cup _ => []
  | cap l => [l.dual, l]

/-- Top boundary of a shape. -/
def cod : Shape I → List (Letter I)
  | dot l => [l]
  | cross ε i j => [(ε, j), (ε, i)]
  | cup l => [l, l.dual]
  | cap _ => []

@[simp] theorem dom_dot (l : Letter I) : (dot l).dom = [l] := rfl
@[simp] theorem dom_cross (ε : Bool) (i j : I) : (cross ε i j).dom = [(ε, i), (ε, j)] := rfl
@[simp] theorem dom_cup (l : Letter I) : (cup l).dom = [] := rfl
@[simp] theorem dom_cap (l : Letter I) : (cap l).dom = [l.dual, l] := rfl
@[simp] theorem cod_dot (l : Letter I) : (dot l).cod = [l] := rfl
@[simp] theorem cod_cross (ε : Bool) (i j : I) : (cross ε i j).cod = [(ε, j), (ε, i)] := rfl
@[simp] theorem cod_cup (l : Letter I) : (cup l).cod = [l, l.dual] := rfl
@[simp] theorem cod_cap (l : Letter I) : (cap l).cod = [] := rfl

variable {RD}

/-- The generator of `psig` of shape `g` whose rightmost region is `ν`. -/
def gen (RD : RootDatum C X Y) (ν : X) : Shape I → (psig RD).Gen
  | dot l => .gen (.dot ⟨l, ν⟩)
  | cross ε i j => .gen (.cross ε i j ν)
  | cup l => .cup ⟨l, sh RD l.dual + ν⟩
  | cap l => .cap ⟨l, ν⟩

theorem wt_dom_eq_wt_cod (ν : X) (g : Shape I) : wt RD ν g.dom = wt RD ν g.cod := by
  cases g with
  | dot l => rfl
  | cross ε i j => simp only [dom, cod, wt_cons, wt_nil]; abel
  | cup l => simp only [dom, cod, wt_cons, wt_nil]; rw [← add_assoc, sh_add_sh_dual, zero_add]
  | cap l => simp only [dom, cod, wt_cons, wt_nil]; rw [← add_assoc, sh_dual_add_sh, zero_add]

theorem dom_gen (ν : X) (g : Shape I) : (psig RD).dom (g.gen RD ν) = wd RD ν g.dom := by
  cases g <;> rfl

theorem cod_gen (ν : X) (g : Shape I) : (psig RD).cod (g.gen RD ν) = wd RD ν g.cod := by
  cases g with
  | dot l => rfl
  | cross ε i j => rfl
  | cap l => rfl
  | cup l =>
    show [(⟨l, sh RD l.dual + ν⟩ : Col I X), ⟨l.dual, sh RD l + (sh RD l.dual + ν)⟩] =
      [⟨l, sh RD l.dual + ν⟩, ⟨l.dual, ν⟩]
    rw [← add_assoc, sh_add_sh_dual, zero_add]

theorem left_gen (ν : X) (g : Shape I) : (psig RD).left (g.gen RD ν) = wt RD ν g.dom := by
  cases g with
  | dot l => rfl
  | cross ε i j => rfl
  | cup l =>
    show sh RD l + (sh RD l.dual + ν) = ν
    rw [← add_assoc, sh_add_sh_dual, zero_add]
  | cap l =>
    show ν = sh RD l.dual + (sh RD l + ν)
    rw [← add_assoc, sh_dual_add_sh, zero_add]

theorem right_gen (ν : X) (g : Shape I) : (psig RD).right (g.gen RD ν) = ν := by
  cases g with
  | dot l => rfl
  | cross ε i j => rfl
  | cap l => rfl
  | cup l =>
    show sh RD l + (sh RD l.dual + ν) = ν
    rw [← add_assoc, sh_add_sh_dual, zero_add]

end Shape

/-! ## Layers in normal form -/

/-- The layer `u ⊗ g ⊗ v` with rightmost region `μ`: the generator of shape `g` between the
strands of the signed sequences `u` and `v`. -/
def lay (μ : X) (u : List (Letter I)) (g : Shape I) (v : List (Letter I)) : Layer (psig RD) :=
  ⟨(wt RD μ (u ++ g.dom ++ v) : X), wd RD (wt RD μ (g.dom ++ v)) u, g.gen RD (wt RD μ v), wd RD μ v⟩

theorem wt_lay_dom (μ : X) (u : List (Letter I)) (g : Shape I) (v : List (Letter I)) :
    wt RD μ (u ++ g.dom ++ v) = wt RD μ (u ++ g.cod ++ v) := by
  simp only [List.append_assoc, wt_append, Shape.wt_dom_eq_wt_cod]

theorem lay_valid (μ : X) (u : List (Letter I)) (g : Shape I) (v : List (Letter I)) :
    (lay RD μ u g v).Valid := by
  have hl := Shape.left_gen (RD := RD) (wt RD μ v) g
  have hr := Shape.right_gen (RD := RD) (wt RD μ v) g
  have hd := Shape.dom_gen (RD := RD) (wt RD μ v) g
  have hc := Shape.cod_gen (RD := RD) (wt RD μ v) g
  have hw := Shape.wt_dom_eq_wt_cod (RD := RD) (wt RD μ v) g
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · show (psig RD).ok (wt RD μ (u ++ g.dom ++ v) : X) (wd RD (wt RD μ (g.dom ++ v)) u)
    rw [List.append_assoc, wt_append]; exact ok_wd RD _ u
  · show (psig RD).endR (wt RD μ (u ++ g.dom ++ v) : X) (wd RD (wt RD μ (g.dom ++ v)) u) =
      (psig RD).left (g.gen RD (wt RD μ v))
    rw [List.append_assoc, wt_append, endR_wd, hl, wt_append]
  · show (psig RD).ok ((psig RD).left (g.gen RD (wt RD μ v))) ((psig RD).dom (g.gen RD _))
    rw [hl, hd]; exact ok_wd RD _ _
  · show (psig RD).endR ((psig RD).left (g.gen RD (wt RD μ v))) ((psig RD).dom (g.gen RD _)) =
      (psig RD).right (g.gen RD (wt RD μ v))
    rw [hl, hd, endR_wd, hr]
  · show (psig RD).ok ((psig RD).left (g.gen RD (wt RD μ v))) ((psig RD).cod (g.gen RD _))
    rw [hl, hc, hw]; exact ok_wd RD _ _
  · show (psig RD).endR ((psig RD).left (g.gen RD (wt RD μ v))) ((psig RD).cod (g.gen RD _)) =
      (psig RD).right (g.gen RD (wt RD μ v))
    rw [hl, hc, hw, endR_wd, hr]
  · show (psig RD).ok ((psig RD).right (g.gen RD (wt RD μ v))) (wd RD μ v)
    rw [hr]; exact ok_wd RD _ _

theorem lay_dom (μ : X) (u : List (Letter I)) (g : Shape I) (v : List (Letter I)) :
    (lay RD μ u g v).dom = ob RD μ (u ++ g.dom ++ v) := by
  refine Obj.ext rfl ?_
  have h := Shape.dom_gen (RD := RD) (wt RD μ v) g
  simp only [Layer.dom_word, lay, ob_word]
  rw [h, List.append_assoc, List.append_assoc, wd_append RD μ u, wd_append RD μ g.dom]

theorem lay_cod (μ : X) (u : List (Letter I)) (g : Shape I) (v : List (Letter I)) :
    (lay RD μ u g v).cod = ob RD μ (u ++ g.cod ++ v) := by
  refine Obj.ext (wt_lay_dom RD μ u g v) ?_
  have h := Shape.cod_gen (RD := RD) (wt RD μ v) g
  simp only [Layer.cod_word, lay, ob_word]
  rw [h, List.append_assoc, List.append_assoc, wd_append RD μ u, wd_append RD μ g.cod,
    wt_append, wt_append, Shape.wt_dom_eq_wt_cod]

/-! ## Diagrams in normal form -/

/-- A layer in normal form: strands `u` to the left, a generator of shape `g`, strands `v` to
the right. -/
abbrev LayerData (I : Type u) : Type u := List (Letter I) × Shape I × List (Letter I)

/-- The layers `ls` form a diagram from the signed sequence `t` (bottom) to `t'` (top). -/
def SChain : List (Letter I) → List (LayerData I) → List (Letter I) → Prop
  | t, [], t' => t = t'
  | t, x :: ls, t' => t = x.1 ++ x.2.1.dom ++ x.2.2 ∧ SChain (x.1 ++ x.2.1.cod ++ x.2.2) ls t'

@[simp] theorem sChain_nil (t t' : List (Letter I)) : SChain t [] t' ↔ t = t' := Iff.rfl

@[simp] theorem sChain_cons (t t' : List (Letter I)) (x : LayerData I) (ls : List (LayerData I)) :
    SChain t (x :: ls) t' ↔ t = x.1 ++ x.2.1.dom ++ x.2.2 ∧ SChain (x.1 ++ x.2.1.cod ++ x.2.2) ls t' :=
  Iff.rfl

theorem SChain.append {t t' t'' : List (Letter I)} {ls ms : List (LayerData I)}
    (h₁ : SChain t ls t') (h₂ : SChain t' ms t'') : SChain t (ls ++ ms) t'' := by
  induction ls generalizing t with
  | nil => cases h₁; exact h₂
  | cons x ls ih => exact ⟨h₁.1, ih h₁.2⟩

theorem SChain.replicate (n : ℕ) (u : List (Letter I)) (l : Letter I) (v : List (Letter I)) :
    SChain (u ++ [l] ++ v) (List.replicate n (u, Shape.dot l, v)) (u ++ [l] ++ v) := by
  induction n with
  | zero => rfl
  | succ n ih => exact ⟨rfl, ih⟩

/-- The layers of a normal-form diagram. -/
def layList (μ : X) (ls : List (LayerData I)) : List (Layer (psig RD)) :=
  ls.map fun x => lay RD μ x.1 x.2.1 x.2.2

@[simp] theorem layList_nil (μ : X) : layList RD μ [] = [] := rfl

@[simp] theorem layList_cons (μ : X) (x : LayerData I) (ls : List (LayerData I)) :
    layList RD μ (x :: ls) = lay RD μ x.1 x.2.1 x.2.2 :: layList RD μ ls := rfl

@[simp] theorem layList_append (μ : X) (ls ms : List (LayerData I)) :
    layList RD μ (ls ++ ms) = layList RD μ ls ++ layList RD μ ms := List.map_append

theorem SChain.chain (μ : X) {t t' : List (Letter I)} {ls : List (LayerData I)}
    (h : SChain t ls t') : Chain (ob RD μ t) (layList RD μ ls) (ob RD μ t') := by
  induction ls generalizing t with
  | nil => cases h; rfl
  | cons x ls ih =>
    obtain ⟨rfl, h⟩ := h
    exact ⟨lay_valid RD μ _ _ _, lay_dom RD μ _ _ _, by rw [lay_cod RD]; exact ih h⟩

/-- The diagram with rightmost region `μ` given by the layers `ls`, from `E_t 1_μ` to
`E_{t'} 1_μ`. -/
def mkD (μ : X) {t t' : List (Letter I)} (ls : List (LayerData I)) (h : SChain t ls t') :
    ob RD μ t ⟶ ob RD μ t' :=
  Diagram.mk (layList RD μ ls) (h.chain RD μ)

@[simp] theorem layers_mkD (μ : X) {t t' : List (Letter I)} (ls : List (LayerData I))
    (h : SChain t ls t') : Diagram.layers (mkD RD μ ls h) = layList RD μ ls := rfl

theorem mkD_comp (μ : X) {t t' t'' : List (Letter I)} (ls ms : List (LayerData I))
    (h₁ : SChain t ls t') (h₂ : SChain t' ms t'') :
    mkD RD μ ls h₁ ≫ mkD RD μ ms h₂ = mkD RD μ (ls ++ ms) (h₁.append h₂) := by
  ext; simp

/-- `n` dots on the strand `l` between `u` and `v`. -/
def dots (μ : X) (u : List (Letter I)) (l : Letter I) (v : List (Letter I)) (n : ℕ) :
    ob RD μ (u ++ [l] ++ v) ⟶ ob RD μ (u ++ [l] ++ v) :=
  mkD RD μ _ (SChain.replicate n u l v)

/-! ## Degrees -/

/-- The degrees of the generators of `U` (KL III Definition 3.1 ii)): `i·i` for a dot on a strand
labelled `i`, `-i·j` for a crossing of strands labelled `i`, `j`, and for the cups and caps
(outer region `λ`) `c_{+i,λ}` for `1_λ → F E 1_λ` and `F E 1_λ → 1_λ`, `c_{-i,λ}` for
`1_λ → E F 1_λ` and `E F 1_λ → 1_λ`, where `c_{±i,λ} = (i·i/2)(1 ± ⟨i,λ⟩)` (eq. (2.19)).
The cup of a colour `c = ⟨(ε, i), r⟩` lies in the region `λ = sh (ε, i) + r` to the left of
`c`, its cap in the region `λ = r` to the right of `c`. -/
def deg : (psig RD).Gen → ℤ
  | .gen (.dot c) => C.dot c.l.2 c.l.2
  | .gen (.cross _ i j _) => -C.dot i j
  | .cup c => di C c.l.2 * (1 - sgn c.l.1 * RD.pair (RD.iY c.l.2) (sh RD c.l + c.r))
  | .cap c => di C c.l.2 * (1 + sgn c.l.1 * RD.pair (RD.iY c.l.2) c.r)

end Categorification.KL3.Diagram
