/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Diagrams.KL3.GammaIntegral

/-!
# The blocks `1_ρ (_𝒜 U̇) 1_λ` and the domain of the integral `γ`

M. Khovanov, A. Lauda, *A categorification of quantum `sl(n)`*, arXiv:0807.3250v1, §2.1.3:
"The algebra `_𝒜 U̇` is the `ℤ[q, q⁻¹]`-subalgebra of `U̇` generated by products of divided powers
`E_i^{(a)} 1_λ` and `F_i^{(a)} 1_λ`, and has a similar weight decomposition
`_𝒜 U̇ = ⊕_{λ, λ'} 1_{λ'} (_𝒜 U̇) 1_λ`", and §3.6 (after Proposition 3.27): "`γ` restricts to a
homomorphism of `ℤ[q, q⁻¹]`-modules `1_μ (_𝒜 U̇) 1_λ → K₀(U̇(λ, μ))`".

The integral `γ` of `Categorification.Diagrams.KL3.GammaIntegral` (`gammaUA`) is defined on the
`ℤ[q, q⁻¹]`-span of the generators `E_d 1_λ` with left weight `ρ` inside `U̇ 1_λ` (the range of
`dpComb λ ρ`). Here we identify this span with the block `1_ρ (_𝒜 U̇) 1_λ` of the integral form
`UDot.AUD` (the non-unital subring of `U̇` generated by the `q^n E_d 1_λ`):

* `AUD_le_spanGen`: `_𝒜 U̇` is contained in the additive subgroup generated by the `q^n E_d 1_λ`
  (the latter is closed under multiplication, `UDot.E1dp_mul_E1dp`);
* `block_mem_range`: every block `1_ρ x 1_λ` of an element of this subgroup is in the range of
  `dpComb λ ρ`;
* `ofB_dpComb_mem_AUD`: conversely every `∑_d c_d E_d 1_λ` (`c_d ∈ ℤ[q, q⁻¹]`) lies in `_𝒜 U̇`;
* `mem_AUD_block_iff`: **for `x ∈ 1_ρ U̇ 1_λ`, `x ∈ _𝒜 U̇` iff `x` is in the range of
  `dpComb λ ρ`**, i.e. `1_ρ (_𝒜 U̇) 1_λ = range (dpComb λ ρ)`, the domain of `gammaUA λ ρ`.
-/

noncomputable section

namespace Categorification.KL3.Diagram

open QuantumGroup UDot LaurentPolynomial

universe u v

variable {I : Type u} {C : CartanDatum I} {X Y : Type v} [AddCommGroup X] [AddCommGroup Y]
  {RD : RootDatum C X Y}

section Span

variable (RD) in
/-- The additive subgroup of `U̇` generated by the `q^n E_d 1_λ`. -/
def spanGen : AddSubgroup (UD RD vQ) := AddSubgroup.closure (AUDgen RD vQ)

theorem gen_mul_gen {x y : UD RD vQ} (hx : x ∈ AUDgen RD vQ) (hy : y ∈ AUDgen RD vQ) :
    x * y ∈ spanGen RD := by
  obtain ⟨n, d, mu, rfl⟩ := hx
  obtain ⟨m, d', lam, rfl⟩ := hy
  rw [smul_mul_assoc, mul_smul_comm, smul_smul, E1dp_mul_E1dp, ← qp_add]
  split_ifs
  · exact AddSubgroup.subset_closure ⟨n + m, d ++ d', lam, rfl⟩
  · rw [smul_zero]; exact zero_mem _

theorem spanGen_mul {x y : UD RD vQ} (hx : x ∈ spanGen RD) (hy : y ∈ spanGen RD) :
    x * y ∈ spanGen RD := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    induction hy using AddSubgroup.closure_induction with
    | mem y hy => exact gen_mul_gen hx hy
    | one => rw [mul_zero]; exact zero_mem _
    | mul y y' _ _ h h' => rw [mul_add]; exact add_mem h h'
    | inv y _ h => rw [mul_neg]; exact neg_mem h
  | one => rw [zero_mul]; exact zero_mem _
  | mul x x' _ _ h h' => rw [add_mul]; exact add_mem h h'
  | inv x _ h => rw [neg_mul]; exact neg_mem h

/-- `_𝒜 U̇` is contained in the additive span of the `q^n E_d 1_λ`. -/
theorem AUD_le_spanGen {x : UD RD vQ} (hx : x ∈ AUD RD vQ) : x ∈ spanGen RD := by
  induction hx using NonUnitalSubring.closure_induction with
  | mem x hx => exact AddSubgroup.subset_closure hx
  | zero => exact zero_mem _
  | add x y _ _ hx hy => exact add_mem hx hy
  | neg x _ hx => exact neg_mem hx
  | mul x y _ _ hx hy => exact spanGen_mul hx hy

end Span

section Block

attribute [local instance] KLR.KLGamma.vAlgebra

variable {lam ρ : X}

theorem dpComb_single (x : DpIdx (RD := RD) lam ρ) (c : LaurentPolynomial ℤ) :
    RestrictScalars.addEquiv (LaurentPolynomial ℤ) (RatFunc ℚ) (U1 RD vQ lam)
      (dpComb lam ρ (Finsupp.single x c)) = lpToQ c • UDot.mk RD vQ lam (dpW C vQ x.1) := by
  rw [dpComb_apply]
  by_cases hc : c = 0
  · subst hc; simp
  · rw [Finsupp.support_single_ne_zero _ hc, Finset.sum_singleton, Finsupp.single_eq_same]

open scoped Classical in
theorem oneL_mk_dpW (d : List (Bool × I × ℕ)) :
    oneL RD vQ lam ρ (UDot.mk RD vQ lam (dpW C vQ d)) =
      if lam + RD.wX (dpWord d) = ρ then UDot.mk RD vQ lam (dpW C vQ d) else 0 := by
  rw [dpW_eq_smul, map_smul, map_smul, oneL_mk_ew]
  split_ifs <;> simp

/-- Every block `1_ρ x 1_λ` of an element of the span of the `q^n E_d 1_λ` is a
`ℤ[q, q⁻¹]`-combination of the `E_d 1_λ` with left weight `ρ`. -/
theorem block_mem_range {x : UD RD vQ} (hx : x ∈ spanGen RD) :
    ∃ f : DpIdx (RD := RD) lam ρ →₀ LaurentPolynomial ℤ,
      RestrictScalars.addEquiv (LaurentPolynomial ℤ) (RatFunc ℚ) (U1 RD vQ lam) (dpComb lam ρ f) =
        oneL RD vQ lam ρ (compB RD vQ lam x) := by
  induction hx using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨n, d, lam', rfl⟩ := hx
    by_cases hl : lam' = lam
    · subst hl
      rw [map_smul, E1dp, compB_ofB_self, map_smul, oneL_mk_dpW]
      split_ifs with hw
      · refine ⟨Finsupp.single ⟨d, by rw [wt_eq_add_wX, add_comm, hw]⟩ (T n), ?_⟩
        rw [dpComb_single, lpToQ_T]
        rfl
      · exact ⟨0, by rw [map_zero, map_zero, smul_zero]⟩
    · refine ⟨0, ?_⟩
      rw [map_smul, E1dp, compB_ofB_ne RD vQ hl, smul_zero, map_zero, map_zero, map_zero]
  | one => exact ⟨0, by rw [map_zero, map_zero, map_zero, map_zero]⟩
  | mul x y _ _ hx hy =>
    obtain ⟨f, hf⟩ := hx
    obtain ⟨g, hg⟩ := hy
    exact ⟨f + g, by rw [map_add, map_add, hf, hg, map_add, map_add]⟩
  | inv x _ hx =>
    obtain ⟨f, hf⟩ := hx
    exact ⟨-f, by rw [map_neg, map_neg, hf, map_neg, map_neg]⟩

theorem lpToQ_smul_mem_AUD (c : LaurentPolynomial ℤ) {x : UD RD vQ} (hx : x ∈ AUD RD vQ) :
    lpToQ c • x ∈ AUD RD vQ := by
  induction c using LaurentPolynomial.induction_on' with
  | add p p' hp hp' => rw [map_add, add_smul]; exact add_mem hp hp'
  | C_mul_T n a =>
    rw [map_mul, lpToQ_T, mul_smul, lpToQ, eval₂_C, eq_intCast, Int.cast_smul_eq_zsmul]
    exact zsmul_mem (qpow_smul_mem_AUD RD vQ n hx) a

/-- Every `∑_d c_d E_d 1_λ` (`c_d ∈ ℤ[q, q⁻¹]`) lies in `_𝒜 U̇`. -/
theorem ofB_dpComb_mem_AUD (f : DpIdx (RD := RD) lam ρ →₀ LaurentPolynomial ℤ) :
    ofB RD vQ lam (RestrictScalars.addEquiv (LaurentPolynomial ℤ) (RatFunc ℚ) (U1 RD vQ lam)
      (dpComb lam ρ f)) ∈ AUD RD vQ := by
  rw [dpComb_apply, map_sum]
  refine sum_mem fun j _ => ?_
  rw [map_smul]
  exact lpToQ_smul_mem_AUD _ (E1dp_mem_AUD RD vQ j.1 lam)

/-- **`1_ρ (_𝒜 U̇) 1_λ` is the range of `dpComb λ ρ`**: an element `x ∈ 1_ρ U̇ 1_λ` lies in the
integral form `_𝒜 U̇` iff it is a `ℤ[q, q⁻¹]`-combination of the `E_d 1_λ` (`d` a dpss with
left weight `ρ`). Hence `gammaUA λ ρ` is defined on the whole block `1_ρ (_𝒜 U̇) 1_λ`. -/
theorem mem_AUD_block_iff (x : U1 RD vQ lam) (hx : oneL RD vQ lam ρ x = x) :
    ofB RD vQ lam x ∈ AUD RD vQ ↔
      ∃ f : DpIdx (RD := RD) lam ρ →₀ LaurentPolynomial ℤ,
        RestrictScalars.addEquiv (LaurentPolynomial ℤ) (RatFunc ℚ) (U1 RD vQ lam)
          (dpComb lam ρ f) = x := by
  constructor
  · intro h
    obtain ⟨f, hf⟩ := block_mem_range (lam := lam) (ρ := ρ) (AUD_le_spanGen h)
    exact ⟨f, by rw [hf, compB_ofB_self, hx]⟩
  · rintro ⟨f, rfl⟩
    exact ofB_dpComb_mem_AUD f

end Block

end Categorification.KL3.Diagram
