/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.Diagrams.KL3.TopSummand

/-!
# Local idempotents modulo an ideal, from a nilpotent filtration

M. Khovanov, A. Lauda, *A categorification of quantum `sl(n)`*, arXiv:0807.3250v1, §3.8.3
(the ideal `J = (R(ν) ⊗ R(ν') ⊗ Π_λ) Sym⁺` of (3.93) is virtually nilpotent, and
`K₀(R(ν) ⊗ R(ν') ⊗ Π_λ) ≅ K₀(R)` for `R = (R(ν) ⊗ R(ν') ⊗ Π_λ)/J`, (3.96)) and §3.8.4 (the
minimal idempotents `e_r ⊗ e'_{r'} ⊗ 1` map to `0` or to minimal idempotents of
`R_{ν,-ν',λ} = END_U(E_{ν,-ν'} 1_λ)/I_{ν,-ν',λ}`).

In degree zero the ideal generated by the bubbles of positive degree is nilpotent. We record the
resulting ring-theoretic statement, in the endomorphism ring of an object `W` of a
preadditive category, with composition `≫`:

* `localModT_of_filtration`: let `ε` be an idempotent of `W`, `S ⊆ ε (End W) ε` a set closed
  under composition, containing `ε`, all of whose elements are nilpotent or invertible in
  `S` (the image of a local ring), and `F_1 ⊇ F_2 ⊇ ⋯` a multiplicative filtration by
  submodules which is stable under composition with `S` and vanishes in some degree `K₀`. If every
  `y ∈ ε (End W) ε` is congruent modulo a two-sided ideal `T` to an element `s + n`, `s ∈ S`,
  `n ∈ F_1`, then `ε` is local modulo `T` (`LocalModT`).
-/

noncomputable section

namespace Categorification.KrullSchmidtCat

open CategoryTheory CategoryTheory.Limits

universe v u

variable {𝒞 : Type u} [Category.{v} 𝒞] [Preadditive 𝒞] {k : Type*} [Field k] [Linear k 𝒞]

section Pow

variable {W : 𝒞}

omit [Preadditive 𝒞] in
theorem compPow_zero (y : W ⟶ W) : compPow y 0 = 𝟙 W := rfl

omit [Preadditive 𝒞] in
theorem compPow_succ (y : W ⟶ W) (n : ℕ) : compPow y (n + 1) = compPow y n ≫ y := rfl

omit [Preadditive 𝒞] in
theorem compPow_one (y : W ⟶ W) : compPow y 1 = y := by simp [compPow]

omit [Preadditive 𝒞] in
theorem compPow_add (y : W ⟶ W) (a b : ℕ) : compPow y (a + b) = compPow y a ≫ compPow y b := by
  induction b with
  | zero => simp [compPow]
  | succ b ih => rw [← add_assoc, compPow_succ, ih, compPow_succ, Category.assoc]

omit [Preadditive 𝒞] in
theorem compPow_mul (y : W ⟶ W) (a b : ℕ) : compPow y (a * b) = compPow (compPow y a) b := by
  induction b with
  | zero => simp [compPow]
  | succ b ih => rw [Nat.mul_succ, compPow_add, ih, compPow_succ]

theorem compPow_sub_mem {T : Submodule k (W ⟶ W)} (hT : IsIdealEnd T) {y y' : W ⟶ W}
    (h : y - y' ∈ T) : ∀ n, compPow y n - compPow y' n ∈ T
  | 0 => by simp [compPow]
  | n + 1 => by
    have e : compPow y (n + 1) - compPow y' (n + 1) =
        (compPow y n - compPow y' n) ≫ y + compPow y' n ≫ (y - y') := by
      simp only [compPow_succ, Preadditive.sub_comp, Preadditive.comp_sub]; abel
    rw [e]
    exact T.add_mem (hT.comp_right _ _ (compPow_sub_mem hT h n)) (hT.comp_left _ _ h)

end Pow

/-- The powers `ε, x, x ≫ x, …` of an element of the corner `ε (End W) ε` (unit `ε`). -/
def cornerPow {W : 𝒞} (ε x : W ⟶ W) : ℕ → (W ⟶ W)
  | 0 => ε
  | n + 1 => cornerPow ε x n ≫ x

omit [Preadditive 𝒞] in
theorem cornerPow_left {W : 𝒞} {ε x : W ⟶ W} (hx : ε ≫ x = x) (hε : ε ≫ ε = ε) :
    ∀ n, ε ≫ cornerPow ε x n = cornerPow ε x n
  | 0 => hε
  | n + 1 => by rw [cornerPow, ← Category.assoc, cornerPow_left hx hε n]

omit [Preadditive 𝒞] in
theorem cornerPow_right {W : 𝒞} {ε x : W ⟶ W} (hx : x ≫ ε = x) (hε : ε ≫ ε = ε) :
    ∀ n, cornerPow ε x n ≫ ε = cornerPow ε x n
  | 0 => hε
  | n + 1 => by rw [cornerPow, Category.assoc, hx]

omit [Preadditive 𝒞] in
theorem cornerPow_succ' {W : 𝒞} {ε x : W ⟶ W} (hx : ε ≫ x = x) (hx' : x ≫ ε = x) :
    ∀ n, cornerPow ε x (n + 1) = x ≫ cornerPow ε x n
  | 0 => by
    show ε ≫ x = x ≫ ε
    rw [hx, hx']
  | n + 1 => by
    show cornerPow ε x (n + 1) ≫ x = x ≫ (cornerPow ε x n ≫ x)
    rw [cornerPow_succ' hx hx' n, Category.assoc]

/-- **Geometric series**: if `x ∈ ε (End W) ε` has `x^{K+1} = 0`, then `ε + x` is invertible in
the corner. -/
theorem exists_inv_one_add {W : 𝒞} {ε x : W ⟶ W} (hε : ε ≫ ε = ε) (hxl : ε ≫ x = x)
    (hxr : x ≫ ε = x) (K : ℕ) (hK : cornerPow ε x (K + 1) = 0) :
    ∃ v : W ⟶ W, ε ≫ v ≫ ε = v ∧ (ε + x) ≫ v = ε ∧ v ≫ (ε + x) = ε := by
  set v := ∑ i ∈ Finset.range (K + 1), ((-1 : ℤ) ^ i) • cornerPow ε x i
  have hvl : ε ≫ v = v := by
    simp only [v, Preadditive.comp_sum, Preadditive.comp_zsmul, cornerPow_left hxl hε]
  have hvr : v ≫ ε = v := by
    simp only [v, Preadditive.sum_comp, Preadditive.zsmul_comp, cornerPow_right hxr hε]
  -- telescoping
  have tel : ∀ n, ∑ i ∈ Finset.range (n + 1), ((-1 : ℤ) ^ i) • cornerPow ε x i +
      ∑ i ∈ Finset.range (n + 1), ((-1 : ℤ) ^ i) • cornerPow ε x (i + 1) =
        ε + ((-1 : ℤ) ^ n) • cornerPow ε x (n + 1) := by
    intro n
    induction n with
    | zero => simp [cornerPow]
    | succ n ih =>
      rw [Finset.sum_range_succ (fun i => ((-1 : ℤ) ^ i) • cornerPow ε x i) (n + 1),
        Finset.sum_range_succ (fun i => ((-1 : ℤ) ^ i) • cornerPow ε x (i + 1)) (n + 1)]
      have e : ∑ i ∈ Finset.range (n + 1), ((-1 : ℤ) ^ i) • cornerPow ε x i +
          ((-1 : ℤ) ^ (n + 1)) • cornerPow ε x (n + 1) +
          (∑ i ∈ Finset.range (n + 1), ((-1 : ℤ) ^ i) • cornerPow ε x (i + 1) +
            ((-1 : ℤ) ^ (n + 1)) • cornerPow ε x (n + 1 + 1)) =
          (∑ i ∈ Finset.range (n + 1), ((-1 : ℤ) ^ i) • cornerPow ε x i +
            ∑ i ∈ Finset.range (n + 1), ((-1 : ℤ) ^ i) • cornerPow ε x (i + 1)) +
          ((-1 : ℤ) ^ (n + 1)) • cornerPow ε x (n + 1) +
          ((-1 : ℤ) ^ (n + 1)) • cornerPow ε x (n + 1 + 1) := by abel
      rw [e, ih, pow_succ, mul_neg_one, neg_smul]
      abel
  refine ⟨v, by rw [hvr, hvl], ?_, ?_⟩
  · rw [Preadditive.add_comp, hvl]
    have hxv : x ≫ v = ∑ i ∈ Finset.range (K + 1), ((-1 : ℤ) ^ i) • cornerPow ε x (i + 1) := by
      simp only [v, Preadditive.comp_sum, Preadditive.comp_zsmul, ← cornerPow_succ' hxl hxr]
    rw [hxv, tel, hK, smul_zero, add_zero]
  · rw [Preadditive.comp_add, hvr]
    have hvx : v ≫ x = ∑ i ∈ Finset.range (K + 1), ((-1 : ℤ) ^ i) • cornerPow ε x (i + 1) := by
      simp only [v, Preadditive.sum_comp, Preadditive.zsmul_comp]
      rfl
    rw [hvx, tel, hK, smul_zero, add_zero]

omit [Preadditive 𝒞] in
theorem cornerPow_eq_compPow {W : 𝒞} {ε x : W ⟶ W} (hxl : ε ≫ x = x) :
    ∀ n, cornerPow ε x (n + 1) = compPow x (n + 1)
  | 0 => by simp only [cornerPow, compPow]; rw [hxl, Category.id_comp]
  | n + 1 => by
    show cornerPow ε x (n + 1) ≫ x = compPow x (n + 1) ≫ x
    rw [cornerPow_eq_compPow hxl n]

/-- **Idempotents local modulo an ideal, from a nilpotent filtration.** -/
theorem localModT_of_filtration {W : 𝒞} {T : Submodule k (W ⟶ W)} (hT : IsIdealEnd T)
    {ε : W ⟶ W} (hε : ε ≫ ε = ε) (S : Set (W ⟶ W)) (hεS : ε ∈ S)
    (hScorner : ∀ s ∈ S, ε ≫ s = s ∧ s ≫ ε = s)
    (hSmul : ∀ s ∈ S, ∀ s' ∈ S, s ≫ s' ∈ S)
    (hSloc : ∀ s ∈ S, (∃ N, compPow s (N + 1) = 0) ∨ ∃ z ∈ S, s ≫ z = ε ∧ z ≫ s = ε)
    (F : ℕ → Submodule k (W ⟶ W)) (K₀ : ℕ) (hFtop : F (K₀ + 1) = ⊥)
    (hFanti : ∀ K, F (K + 1) ≤ F K)
    (hFmul : ∀ K L (x y : W ⟶ W), x ∈ F K → y ∈ F L → x ≫ y ∈ F (K + L))
    (hSF : ∀ s ∈ S, ∀ K (x : W ⟶ W), x ∈ F K → s ≫ x ∈ F K ∧ x ≫ s ∈ F K)
    (hspan : ∀ y : W ⟶ W, ε ≫ y ≫ ε = y → ∃ s ∈ S, ∃ n ∈ F 1, y - s - n ∈ T) :
    LocalModT T ε := by
  intro y hy
  obtain ⟨s, hs, n, hn, hdiff⟩ := hspan y hy
  set n' := ε ≫ n ≫ ε with hn'def
  have hn' : n' ∈ F 1 := (hSF ε hεS 1 _ (hSF ε hεS 1 n hn).2).1
  have hn'l : ε ≫ n' = n' := by rw [hn'def, ← Category.assoc, hε]
  have hn'r : n' ≫ ε = n' := by rw [hn'def]; simp only [Category.assoc, hε]
  obtain ⟨hsl, hsr⟩ := hScorner s hs
  have hdiff' : y - (s + n') ∈ T := by
    have e : ε ≫ (y - s - n) ≫ ε = y - (s + n') := by
      rw [Preadditive.sub_comp, Preadditive.sub_comp, Preadditive.comp_sub, Preadditive.comp_sub,
        hy, hsr, hsl, sub_sub]
    rw [← e]
    exact hT.comp_left _ _ (hT.comp_right _ _ hdiff)
  -- the powers of elements of `S` stay in `S`
  have hpowS : ∀ j, compPow s (j + 1) ∈ S := by
    intro j
    induction j with
    | zero => rw [compPow_one]; exact hs
    | succ j ih => rw [compPow_succ]; exact hSmul _ ih _ hs
  -- powers of elements of `F 1`
  have hpowF : ∀ (x : W ⟶ W), x ∈ F 1 → ∀ j, compPow x (j + 1) ∈ F (j + 1) := by
    intro x hx j
    induction j with
    | zero => rw [compPow_one]; exact hx
    | succ j ih => rw [compPow_succ]; exact hFmul _ _ _ _ ih hx
  rcases hSloc s hs with ⟨N, hN⟩ | ⟨z₀, hz₀, hsz, hzs⟩
  · -- `s` nilpotent: `(s + n')^{(N+1)(K₀+1)} = 0`
    left
    have hA : ∀ j, compPow (s + n') (j + 1) - compPow s (j + 1) ∈ F 1 := by
      intro j
      induction j with
      | zero => rw [compPow_one, compPow_one, add_sub_cancel_left]; exact hn'
      | succ j ih =>
        have e : compPow (s + n') (j + 1 + 1) - compPow s (j + 1 + 1) =
            compPow s (j + 1) ≫ n' + (compPow (s + n') (j + 1) - compPow s (j + 1)) ≫ s +
              (compPow (s + n') (j + 1) - compPow s (j + 1)) ≫ n' := by
          rw [compPow_succ, compPow_succ (s + n')]
          simp only [Preadditive.comp_add, Preadditive.sub_comp]
          abel
        rw [e]
        refine (F 1).add_mem ((F 1).add_mem ((hSF _ (hpowS j) 1 n' hn').1)
          ((hSF s hs 1 _ ih).2)) ?_
        exact hFanti 1 (hFmul 1 1 _ _ ih hn')
    have h1 : compPow (s + n') (N + 1) ∈ F 1 := by
      have := hA N
      rwa [hN, sub_zero] at this
    have h2 := hpowF _ h1 K₀
    rw [hFtop, Submodule.mem_bot, ← compPow_mul] at h2
    refine ⟨(N + 1) * (K₀ + 1) - 1, ?_⟩
    have hM : (N + 1) * (K₀ + 1) - 1 + 1 = (N + 1) * (K₀ + 1) := by
      have : 1 ≤ (N + 1) * (K₀ + 1) := Nat.one_le_iff_ne_zero.2 (by positivity)
      omega
    rw [hM]
    have := compPow_sub_mem hT hdiff' ((N + 1) * (K₀ + 1))
    rwa [h2, sub_zero] at this
  · -- `s` invertible: so is `s + n'`
    right
    obtain ⟨hz₀l, hz₀r⟩ := hScorner z₀ hz₀
    -- right inverse
    set m := n' ≫ z₀ with hmdef
    have hm : m ∈ F 1 := (hSF z₀ hz₀ 1 n' hn').2
    have hml : ε ≫ m = m := by rw [hmdef, ← Category.assoc, hn'l]
    have hmr : m ≫ ε = m := by rw [hmdef, Category.assoc, hz₀r]
    have hmK : cornerPow ε m (K₀ + 1) = 0 := by
      rw [cornerPow_eq_compPow hml]
      have := hpowF m hm K₀
      rwa [hFtop, Submodule.mem_bot] at this
    obtain ⟨v, hvc, hv1, -⟩ := exists_inv_one_add hε hml hmr K₀ hmK
    -- left inverse
    set m' := z₀ ≫ n' with hm'def
    have hm' : m' ∈ F 1 := (hSF z₀ hz₀ 1 n' hn').1
    have hm'l : ε ≫ m' = m' := by rw [hm'def, ← Category.assoc, hz₀l]
    have hm'r : m' ≫ ε = m' := by rw [hm'def, Category.assoc, hn'r]
    have hm'K : cornerPow ε m' (K₀ + 1) = 0 := by
      rw [cornerPow_eq_compPow hm'l]
      have := hpowF m' hm' K₀
      rwa [hFtop, Submodule.mem_bot] at this
    obtain ⟨v', hv'c, -, hv'2⟩ := exists_inv_one_add hε hm'l hm'r K₀ hm'K
    set z := z₀ ≫ v
    have hright : (s + n') ≫ z = ε := by
      rw [← Category.assoc, Preadditive.add_comp, hsz]
      exact hv1
    have hleft' : (v' ≫ z₀) ≫ (s + n') = ε := by
      rw [Category.assoc, Preadditive.comp_add, hzs]
      exact hv'2
    have hzz : v' ≫ z₀ = z := by
      have hvl : ε ≫ z = z := by
        show ε ≫ z₀ ≫ v = z₀ ≫ v
        rw [← Category.assoc, hz₀l]
      have hv'r : (v' ≫ z₀) ≫ ε = v' ≫ z₀ := by rw [Category.assoc, hz₀r]
      calc v' ≫ z₀ = (v' ≫ z₀) ≫ ε := hv'r.symm
        _ = (v' ≫ z₀) ≫ (s + n') ≫ z := by rw [hright]
        _ = ε ≫ z := by rw [← Category.assoc, hleft']
        _ = z := hvl
    have hleft : z ≫ (s + n') = ε := by rw [← hzz]; exact hleft'
    refine ⟨z, ?_, ?_, ?_⟩
    · show ε ≫ (z₀ ≫ v) ≫ ε = z₀ ≫ v
      have hvr' : v ≫ ε = v := by rw [← hvc]; simp only [Category.assoc, hε]
      rw [Category.assoc, hvr', ← Category.assoc, hz₀l]
    · have e : y ≫ z - ε = (y - (s + n')) ≫ z := by rw [Preadditive.sub_comp, hright]
      rw [e]; exact hT.comp_right _ _ hdiff'
    · have e : z ≫ y - ε = z ≫ (y - (s + n')) := by rw [Preadditive.comp_sub, hleft]
      rw [e]; exact hT.comp_left _ _ hdiff'

end Categorification.KrullSchmidtCat
