/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.TensorKLRK0
import Categorification.KLR.Prop32Mult
import Categorification.KLR.Theorem11
import Categorification.QuantumGroup.Coproduct

/-!
# `K₀(R)` as a twisted bialgebra: the coproduct `[Res]` and KL I, Theorem 1.1

Khovanov–Lauda I (arXiv:0803.4121v2), §1 and §3.1 (TeX lines ~290–305 and ~1882–1960):
"`[Res]` is the sum of maps `K₀(R(ν + ν')) → K₀(R(ν)) ⊗ K₀(R(ν'))` over all `ν, ν'`";
**Proposition 3.1** (`[Res]` is coassociative), the algebra structure (3.1)
`(x₁ ⊗ x₂)(x₁' ⊗ x₂') = q^{-|x₂|·|x₁'|} x₁x₁' ⊗ x₂x₂'` on `K₀(R) ⊗ K₀(R)`, **Proposition 3.2**
("`[Res]` is an algebra homomorphism"), and **Theorem 1.1** ("`γ : _𝒜 f → K₀(R)` is an
isomorphism of `ℕ[I]`-graded twisted bialgebras").

All tensor products of `K₀`'s are over `ℤ[q, q⁻¹]`; `K₀(R) = G.K0R = ⨁_ν K₀(R(ν))`.

## Definitions (any grading datum `G` with dots of positive degree, `hPQ`, `hP`)

* `GradingDatum.coprod` : **`Δ = [Res] : K₀(R) → K₀(R) ⊗ K₀(R)`**, the sum over all `ν, ν'` of
  `[Res_{ν,ν'}] : K₀(R(ν + ν')) → K₀(R(ν) ⊗ R(ν')) ≅ K₀(R(ν)) ⊗ K₀(R(ν'))` (the identification is
  `GradingDatum.k0TensorEquiv`). It is characterised by `coprod_spec` / `eq_coprod_of_spec`.
* `GradingDatum.twMul` : the twisted multiplication (3.1),
  `(x₁ ⊗ x₂)(x₁' ⊗ x₂') = q^{|x₂| ⋄ |x₁'|} x₁x₁' ⊗ x₂x₂'`, `|x₂| ⋄ |x₁'| = ∑ degΨ(a, c)`
  (`= -|x₂|·|x₁'|` for the KL I grading); it is associative with unit `1 ⊗ 1` (`twMul_assoc`,
  `twMul_one_left`, `twMul_one_right`).
* `GradingDatum.gammaTT`, `GradingDatum.gammaTTT` : `γ ⊗ γ` and `γ ⊗ γ ⊗ γ` on the twisted tensor
  powers of `'f`.

## Main results

For every grading datum:

* `GradingDatum.coprod_gammaG` : **`Δ ∘ γ = (γ ⊗ γ) ∘ r`** on `'f_{ℤ[q,q⁻¹]}`;
* `GradingDatum.gammaTT_mul`, `GradingDatum.coprod_mul_gammaG`, `GradingDatum.coprod_one` :
  Proposition 3.2 on the image of `γ`, and `Δ(1) = 1 ⊗ 1`;
* `GradingDatum.coassoc_gammaG` : coassociativity on the image of `γ` (from that of `r`).

For the KL I grading (`KLGamma`; Lusztig's normalisation: Cartan pairing, `v = q⁻¹`):

* `KLGamma.exists_smul_mem_range_gammaZ` : every `x ∈ K₀(R)` has a nonzero multiple `p x` in
  `γ('f_{ℤ[q,q⁻¹]})` (via KL I, Proposition 3.20); `K₀(R) ⊗ K₀(R)` is torsion-free;
* `KLGamma.coprod_mul` : **KL I, Proposition 3.2** on all of `K₀(R)`;
* `KLGamma.coassoc` : **KL I, Proposition 3.1** (coassociativity of `[Res]`);
* `KLGamma.coprod_gammaZ` : `[Res] ∘ γ = (γ ⊗ γ) ∘ r` for Lusztig's `r`;
* `KLGamma.map_gammaF_rbar` : over `ℚ(v)`, `(γ ⊗ γ) ∘ r̄ = Δ_{ℚ(v)} ∘ γ` on `f`, for Lusztig's
  `r̄ : f → f ⊗ f` (`PreF.rbar`); `KLGamma.map_gammaF_rbar_Af` : the same on `_𝒜 f`, with the
  integral `Δ`; `KLGamma.toK0QTT_injective`;
* `KLGamma.theorem_1_1_bialgebra` : **KL I, Theorem 1.1 in full** (bijectivity, gradings,
  twisted algebra structure, multiplicativity and coassociativity of `Δ`, compatibility with `r̄`).

## Hypotheses

The quantum Gabber–Kac hypothesis `hGK` (the radical of Lusztig's form is generated by the Serre
relations) is needed to define `f`, `_𝒜 f` and `γ : _𝒜 f → K₀(R)`; it is an explicit hypothesis
of the `f`-level statements, as in `Categorification.KLR.Theorem11`. The counit of `[Res]` is not
formalized.
-/

noncomputable section

namespace Categorification.KLR

open Graded GProj QuantumGroup PreF LaurentPolynomial
open scoped TensorProduct

variable {I : Type*} [DecidableEq I] {k : Type*} [Field k] {Q : I → I → MvPolynomial (Fin 2) k}
  {P : I → I → MvPolynomial (Fin 2) k}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * MvPolynomial.rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0) (G : GradingDatum Q) (hG : ∀ a, 0 < G.degX a)

local notation "LP" => LaurentPolynomial ℤ

namespace GradingDatum

/-! ### Components of `K₀(R) ⊗ K₀(R)` -/

section Components

/-- The component map `K₀(R) ⊗ K₀(R) → K₀(R(ν)) ⊗ K₀(R(ν'))`. -/
def compTT (ν ν' : Multiset I) :
    G.K0R ⊗[LP] G.K0R →ₗ[LP] K0 (G.grade ν) ⊗[LP] K0 (G.grade ν') :=
  TensorProduct.map (DirectSum.component LP (Multiset I) G.K0fam ν)
    (DirectSum.component LP (Multiset I) G.K0fam ν')

/-- The inclusion `K₀(R(ν)) ⊗ K₀(R(ν')) → K₀(R) ⊗ K₀(R)`. -/
def inclTT (ν ν' : Multiset I) :
    K0 (G.grade ν) ⊗[LP] K0 (G.grade ν') →ₗ[LP] G.K0R ⊗[LP] G.K0R :=
  TensorProduct.map (DirectSum.lof LP (Multiset I) G.K0fam ν)
    (DirectSum.lof LP (Multiset I) G.K0fam ν')

theorem compTT_tmul (ν ν' : Multiset I) (x y : G.K0R) :
    G.compTT ν ν' (x ⊗ₜ y) = DirectSum.component LP (Multiset I) G.K0fam ν x ⊗ₜ
      DirectSum.component LP (Multiset I) G.K0fam ν' y := rfl

theorem compTT_inclTT_self (ν ν' : Multiset I) (z : K0 (G.grade ν) ⊗[LP] K0 (G.grade ν')) :
    G.compTT ν ν' (G.inclTT ν ν' z) = z := by
  induction z using TensorProduct.induction_on with
  | zero => simp
  | tmul a b =>
    simp [compTT, inclTT, DirectSum.component.lof_self]
  | add z z' hz hz' => rw [map_add, map_add, hz, hz']

theorem compTT_inclTT_of_ne {ν ν' μ μ' : Multiset I} (h : (ν, ν') ≠ (μ, μ'))
    (z : K0 (G.grade ν) ⊗[LP] K0 (G.grade ν')) : G.compTT μ μ' (G.inclTT ν ν' z) = 0 := by
  induction z using TensorProduct.induction_on with
  | zero => simp
  | tmul a b =>
    simp only [compTT, inclTT, TensorProduct.map_tmul, DirectSum.component.of]
    by_cases h1 : ν = μ
    · have h2 : ν' ≠ μ' := fun h2 => h (by rw [h1, h2])
      rw [dif_neg h2, TensorProduct.tmul_zero]
    · rw [dif_neg h1, TensorProduct.zero_tmul]
  | add z z' hz hz' => rw [map_add, map_add, hz, hz', add_zero]

theorem inclTT_of_tmul_of (i j : Multiset I) (a : K0 (G.grade i)) (b : K0 (G.grade j)) :
    (DirectSum.of G.K0fam i a ⊗ₜ[LP] DirectSum.of G.K0fam j b : G.K0R ⊗[LP] G.K0R) =
      G.inclTT i j (a ⊗ₜ b) := by
  rw [inclTT, TensorProduct.map_tmul, DirectSum.lof_eq_of, DirectSum.lof_eq_of]

/-- Every element of `K₀(R) ⊗ K₀(R)` is the finite sum of its components. -/
theorem exists_finset_eq_sum (Z : G.K0R ⊗[LP] G.K0R) :
    ∃ S : Finset (Multiset I × Multiset I), (∀ p ∉ S, G.compTT p.1 p.2 Z = 0) ∧
      Z = ∑ p ∈ S, G.inclTT p.1 p.2 (G.compTT p.1 p.2 Z) := by
  classical
  let Pr : G.K0R ⊗[LP] G.K0R → Prop := fun Z => ∃ S : Finset (Multiset I × Multiset I),
    (∀ p ∉ S, G.compTT p.1 p.2 Z = 0) ∧ Z = ∑ p ∈ S, G.inclTT p.1 p.2 (G.compTT p.1 p.2 Z)
  have h0 : Pr 0 := ⟨∅, fun _ _ => map_zero _, by simp⟩
  have hadd : ∀ Z Z', Pr Z → Pr Z' → Pr (Z + Z') := by
    rintro Z Z' ⟨S, hS, hZ⟩ ⟨S', hS', hZ'⟩
    refine ⟨S ∪ S', fun p hp => ?_, ?_⟩
    · rw [Finset.mem_union, not_or] at hp
      rw [map_add, hS p hp.1, hS' p hp.2, add_zero]
    · have e1 : ∑ p ∈ S ∪ S', G.inclTT p.1 p.2 (G.compTT p.1 p.2 Z) = Z := by
        rw [← Finset.sum_subset Finset.subset_union_left (fun p _ hp => by
          rw [hS p hp, map_zero]), ← hZ]
      have e2 : ∑ p ∈ S ∪ S', G.inclTT p.1 p.2 (G.compTT p.1 p.2 Z') = Z' := by
        rw [← Finset.sum_subset Finset.subset_union_right (fun p _ hp => by
          rw [hS' p hp, map_zero]), ← hZ']
      simp only [map_add, Finset.sum_add_distrib, e1, e2]
  have hof : ∀ (i j : Multiset I) (a : K0 (G.grade i)) (b : K0 (G.grade j)),
      Pr (G.inclTT i j (a ⊗ₜ b)) := by
    intro i j a b
    refine ⟨{(i, j)}, fun p hp => ?_, ?_⟩
    · refine G.compTT_inclTT_of_ne (fun h => hp ?_) _
      rw [Finset.mem_singleton, h]
    · rw [Finset.sum_singleton, compTT_inclTT_self]
  induction Z using TensorProduct.induction_on with
  | zero => exact h0
  | add Z Z' hZ hZ' => exact hadd Z Z' hZ hZ'
  | tmul x y =>
    induction x using DirectSum.induction_on with
    | zero => rw [TensorProduct.zero_tmul]; exact h0
    | add x x' hx hx' => rw [TensorProduct.add_tmul]; exact hadd _ _ hx hx'
    | of i a =>
      induction y using DirectSum.induction_on with
      | zero => rw [TensorProduct.tmul_zero]; exact h0
      | add y y' hy hy' => rw [TensorProduct.tmul_add]; exact hadd _ _ hy hy'
      | of j b => rw [inclTT_of_tmul_of]; exact hof i j a b

/-- The components `compTT ν ν'` jointly detect elements of `K₀(R) ⊗ K₀(R)`. -/
theorem ext_compTT {X Y : G.K0R ⊗[LP] G.K0R} (h : ∀ ν ν', G.compTT ν ν' X = G.compTT ν ν' Y) :
    X = Y := by
  obtain ⟨S, -, hS⟩ := G.exists_finset_eq_sum (X - Y)
  have : X - Y = 0 := by
    rw [hS]
    exact Finset.sum_eq_zero fun p _ => by rw [map_sub, h, sub_self, map_zero]
  exact sub_eq_zero.1 this

end Components

/-! ### The coproduct `Δ = [Res]` -/

section Coprod

/-- **`Δ = [Res] : K₀(R) → K₀(R) ⊗ K₀(R)`** (KL I, §3.1): on `K₀(R(μ))`, the sum over the
decompositions `μ = ν + ν'` of `[Res_{ν,ν'}]`, followed by
`K₀(R(ν) ⊗ R(ν')) ≅ K₀(R(ν)) ⊗ K₀(R(ν'))`. -/
def coprod : G.K0R →ₗ[LP] G.K0R ⊗[LP] G.K0R :=
  DirectSum.toModule LP (Multiset I) _ fun μ =>
    ∑ p ∈ (Multiset.antidiagonal μ).toFinset,
      G.inclTT p.1 p.2 ∘ₗ (G.k0TensorEquiv hPQ hP hG p.1 p.2).symm.toLinearMap ∘ₗ
        G.resComp p.1 p.2 hPQ hP ∘ₗ DirectSum.lof LP (Multiset I) G.K0fam μ

/-- **`Δ` is `[Res]`**: the `(ν, ν')`-component of `Δ x` is `[Res_{ν,ν'}] x_{ν+ν'}` under
`K₀(R(ν)) ⊗ K₀(R(ν')) ≅ K₀(R(ν) ⊗ R(ν'))`. -/
theorem coprod_spec (ν ν' : Multiset I) (x : G.K0R) :
    G.k0TensorEquiv hPQ hP hG ν ν' (G.compTT ν ν' (G.coprod hPQ hP hG x)) =
      G.resComp ν ν' hPQ hP x := by
  classical
  rw [← LinearEquiv.eq_symm_apply]
  induction x using DirectSum.induction_on with
  | zero => simp
  | add x y hx hy => rw [map_add, map_add, hx, hy, map_add, map_add]
  | of μ y =>
    rw [coprod, ← DirectSum.lof_eq_of LP, DirectSum.toModule_lof, LinearMap.sum_apply, map_sum]
    by_cases hμ : ν + ν' = μ
    · rw [Finset.sum_eq_single (ν, ν')]
      · simp only [LinearMap.comp_apply, LinearEquiv.coe_coe]
        rw [compTT_inclTT_self]
      · intro p _ hp
        simp only [LinearMap.comp_apply]
        exact G.compTT_inclTT_of_ne hp _
      · intro h
        exact absurd (Multiset.mem_toFinset.2 (Multiset.mem_antidiagonal.2 hμ)) h
    · have h0 : G.resComp ν ν' hPQ hP (DirectSum.lof LP (Multiset I) G.K0fam μ y) = 0 := by
        rw [resComp, LinearMap.comp_apply, DirectSum.component.of, dif_neg (Ne.symm hμ),
          map_zero]
      rw [h0, map_zero]
      refine Finset.sum_eq_zero fun p hp => ?_
      simp only [LinearMap.comp_apply]
      refine G.compTT_inclTT_of_ne ?_ _
      intro h
      obtain ⟨h1, h2⟩ := Prod.mk_inj.1 h
      apply hμ
      rw [← h1, ← h2]
      exact Multiset.mem_antidiagonal.1 (Multiset.mem_toFinset.1 hp)

theorem compTT_coprod (ν ν' : Multiset I) (x : G.K0R) :
    G.compTT ν ν' (G.coprod hPQ hP hG x) =
      (G.k0TensorEquiv hPQ hP hG ν ν').symm (G.resComp ν ν' hPQ hP x) := by
  rw [LinearEquiv.eq_symm_apply, coprod_spec]

/-- `Δ` is the unique map whose components are `[Res_{ν,ν'}]`. -/
theorem eq_coprod_of_spec (D : G.K0R →ₗ[LP] G.K0R ⊗[LP] G.K0R)
    (hD : ∀ ν ν' x, G.k0TensorEquiv hPQ hP hG ν ν' (G.compTT ν ν' (D x)) =
      G.resComp ν ν' hPQ hP x) : D = G.coprod hPQ hP hG :=
  LinearMap.ext fun x => G.ext_compTT fun ν ν' =>
    (G.k0TensorEquiv hPQ hP hG ν ν').injective (by rw [hD, coprod_spec])

end Coprod

/-! ### The twisted multiplication (3.1) -/

section TwMul

/-- Multiplication by `q^{λ ⋄ |x|}` on homogeneous `x`:
`x ↦ q^{∑_{a ∈ λ, c ∈ |x|} degΨ(a, c)} x`. -/
def twistOp (l : Multiset I) : G.K0R →ₗ[LP] G.K0R :=
  DirectSum.toModule LP (Multiset I) _ fun μ =>
    (T (wdot G.degΨ l μ) : LP) • DirectSum.lof LP (Multiset I) G.K0fam μ

theorem twistOp_of (l μ : Multiset I) (y : K0 (G.grade μ)) :
    G.twistOp l (DirectSum.of G.K0fam μ y) =
      (T (wdot G.degΨ l μ) : LP) • DirectSum.of G.K0fam μ y := by
  rw [twistOp, ← DirectSum.lof_eq_of LP, DirectSum.toModule_lof, LinearMap.smul_apply]

/-- The bilinear map behind `twMul`: `x₁ ↦ x₂ ↦ (y₁ ⊗ y₂ ↦ x₁ τ_{|x₂|}(y₁) ⊗ x₂ y₂)`. -/
def twMulAux : G.K0R →ₗ[LP] G.K0R →ₗ[LP] Module.End LP (G.K0R ⊗[LP] G.K0R) :=
  (DirectSum.toModule LP (Multiset I) _ fun μ₂ =>
    ((TensorProduct.mapBilinear LP G.K0R G.K0R G.K0R G.K0R ∘ₗ
        LinearMap.lcomp LP G.K0R (G.twistOp μ₂) ∘ₗ LinearMap.mul LP G.K0R).compl₂
      (LinearMap.mul LP G.K0R ∘ₗ DirectSum.lof LP (Multiset I) G.K0fam μ₂)).flip).flip

/-- **The twisted multiplication (3.1) on `K₀(R) ⊗ K₀(R)`**:
`(x₁ ⊗ x₂)(x₁' ⊗ x₂') = q^{|x₂| ⋄ |x₁'|} x₁x₁' ⊗ x₂x₂'` for homogeneous `x₂`, `x₁'`, where
`μ ⋄ μ' = ∑_{a ∈ μ, c ∈ μ'} degΨ(a, c)` (for the KL I grading, `q^{-|x₂|·|x₁'|}`). -/
def twMul : G.K0R ⊗[LP] G.K0R →ₗ[LP] G.K0R ⊗[LP] G.K0R →ₗ[LP] G.K0R ⊗[LP] G.K0R :=
  TensorProduct.lift G.twMulAux

theorem twMul_tmul_of (x₁ : G.K0R) (μ₂ : Multiset I) (b : K0 (G.grade μ₂)) (y₁ y₂ : G.K0R) :
    G.twMul (x₁ ⊗ₜ DirectSum.of G.K0fam μ₂ b) (y₁ ⊗ₜ y₂) =
      (x₁ * G.twistOp μ₂ y₁) ⊗ₜ (DirectSum.of G.K0fam μ₂ b * y₂) := by
  rw [twMul, TensorProduct.lift.tmul, twMulAux, LinearMap.flip_apply, ← DirectSum.lof_eq_of LP,
    DirectSum.toModule_lof]
  rfl

/-- `(x₁ ⊗ x₂)(x₁' ⊗ x₂') = q^{|x₂| ⋄ |x₁'|} x₁x₁' ⊗ x₂x₂'` for homogeneous `x₂`, `x₁'`. -/
theorem twMul_tmul (x₁ : G.K0R) {μ₂ μ₁' : Multiset I} (b : K0 (G.grade μ₂))
    (a' : K0 (G.grade μ₁')) (y₂ : G.K0R) :
    G.twMul (x₁ ⊗ₜ DirectSum.of G.K0fam μ₂ b) (DirectSum.of G.K0fam μ₁' a' ⊗ₜ y₂) =
      (T (wdot G.degΨ μ₂ μ₁') : LP) •
        ((x₁ * DirectSum.of G.K0fam μ₁' a') ⊗ₜ (DirectSum.of G.K0fam μ₂ b * y₂)) := by
  rw [twMul_tmul_of, twistOp_of, mul_smul_comm, TensorProduct.smul_tmul']

/-- Induction on `K₀(R) ⊗ K₀(R)` through homogeneous pure tensors. -/
theorem induction_homog {motive : G.K0R ⊗[LP] G.K0R → Prop} (Z : G.K0R ⊗[LP] G.K0R)
    (zero : motive 0) (add : ∀ Z Z', motive Z → motive Z' → motive (Z + Z'))
    (of : ∀ (μ μ' : Multiset I) (a : K0 (G.grade μ)) (b : K0 (G.grade μ')),
      motive (DirectSum.of G.K0fam μ a ⊗ₜ DirectSum.of G.K0fam μ' b)) : motive Z := by
  induction Z using TensorProduct.induction_on with
  | zero => exact zero
  | add Z Z' hZ hZ' => exact add Z Z' hZ hZ'
  | tmul x y =>
    induction x using DirectSum.induction_on with
    | zero => rw [TensorProduct.zero_tmul]; exact zero
    | add x x' hx hx' => rw [TensorProduct.add_tmul]; exact add _ _ hx hx'
    | of i a =>
      induction y using DirectSum.induction_on with
      | zero => rw [TensorProduct.tmul_zero]; exact zero
      | add y y' hy hy' => rw [TensorProduct.tmul_add]; exact add _ _ hy hy'
      | of j b => exact of i j a b

theorem twistOp_zero : G.twistOp 0 = LinearMap.id :=
  DirectSum.linearMap_ext LP fun μ => LinearMap.ext fun y => by
    rw [LinearMap.comp_apply, DirectSum.lof_eq_of, twistOp_of, wdot_zero_left, T_zero, one_smul]
    rfl

theorem twistOp_one (l : Multiset I) : G.twistOp l 1 = 1 := by
  rw [K0R_one, twistOp_of, wdot_zero_right, T_zero, one_smul]

set_option synthInstance.maxHeartbeats 400000 in
/-- `1 ⊗ 1` is a left unit for the twisted multiplication. -/
theorem twMul_one_left (X : G.K0R ⊗[LP] G.K0R) : G.twMul (1 ⊗ₜ 1) X = X := by
  induction X using TensorProduct.induction_on with
  | zero => rw [LinearMap.map_zero]
  | add X X' hX hX' => rw [LinearMap.map_add, hX, hX']
  | tmul y₁ y₂ =>
    rw [show (1 : G.K0R) ⊗ₜ[LP] (1 : G.K0R) =
        1 ⊗ₜ DirectSum.of G.K0fam 0 (K0.of (GProj.regular (G.grade 0))) from rfl, twMul_tmul_of,
      ← K0R_one, twistOp_zero, LinearMap.id_apply, one_mul, one_mul]

set_option synthInstance.maxHeartbeats 400000 in
/-- `1 ⊗ 1` is a right unit for the twisted multiplication. -/
theorem twMul_one_right (X : G.K0R ⊗[LP] G.K0R) : G.twMul X (1 ⊗ₜ 1) = X := by
  induction X using G.induction_homog with
  | zero => rw [LinearMap.map_zero, LinearMap.zero_apply]
  | add X X' hX hX' => rw [LinearMap.map_add, LinearMap.add_apply, hX, hX']
  | of μ μ' a b => rw [twMul_tmul_of, twistOp_one, mul_one, mul_one]

set_option synthInstance.maxHeartbeats 400000 in
/-- **The twisted multiplication (3.1) is associative.** -/
theorem twMul_assoc (X Y Z : G.K0R ⊗[LP] G.K0R) :
    G.twMul (G.twMul X Y) Z = G.twMul X (G.twMul Y Z) := by
  induction X using G.induction_homog with
  | zero => simp only [LinearMap.map_zero, LinearMap.zero_apply]
  | add X X' hX hX' => simp only [LinearMap.map_add, LinearMap.add_apply, hX, hX']
  | of μ₁ μ₂ a₁ a₂ =>
    induction Y using G.induction_homog with
    | zero => simp only [LinearMap.map_zero, LinearMap.zero_apply]
    | add Y Y' hY hY' => simp only [LinearMap.map_add, LinearMap.add_apply, hY, hY']
    | of μ₃ μ₄ a₃ a₄ =>
      induction Z using G.induction_homog with
      | zero => simp only [LinearMap.map_zero, LinearMap.zero_apply]
      | add Z Z' hZ hZ' => simp only [LinearMap.map_add, LinearMap.add_apply, hZ, hZ']
      | of μ₅ μ₆ a₅ a₆ =>
        rw [twMul_tmul, K0R_of_mul_of G a₂ a₄, LinearMap.map_smul, LinearMap.smul_apply,
          twMul_tmul, twMul_tmul, K0R_of_mul_of G a₃ a₅, LinearMap.map_smul, twMul_tmul,
          ← K0R_of_mul_of G a₂ a₄, ← K0R_of_mul_of G a₃ a₅, smul_smul, smul_smul, ← T_add,
          ← T_add, mul_assoc, mul_assoc]
        congr 2
        rw [wdot_add_left, wdot_add_right]
        ring

end TwMul

/-! ### `γ ⊗ γ` and Proposition 3.2 on the image of `γ` -/

section Gamma

/-- `γ ⊗ γ` on the twisted tensor square `'f ⊗ 'f` (twisted by `degΨ`, `v = q`):
`x ⊗ y ↦ γ(x) ⊗ γ(y)` on words. -/
def gammaTT : TwSq LP I G.degΨ qUnitLP →ₗ[LP] G.K0R ⊗[LP] G.K0R :=
  TwistedMonoidAlgebra.lift fun p => G.gammaG (word p.1) ⊗ₜ G.gammaG (word p.2)

theorem gammaTT_single (u w : FreeMonoid I) (c : LP) :
    G.gammaTT (TwistedMonoidAlgebra.single (u, w) c) =
      c • (G.gammaG (word u) ⊗ₜ G.gammaG (word w)) :=
  TwistedMonoidAlgebra.lift_single _ _ _

theorem gammaG_word_eq_of (w : FreeMonoid I) :
    G.gammaG (word w) = DirectSum.of G.K0fam (wt w)
      (K0.of (G.projP (KLRAlgebra.Seq.ofList (FreeMonoid.toList w) rfl))) := by
  rw [gammaG_word, clsW]
  rfl

/-- The components of `(γ ⊗ γ)(Z)` are the realisations of `Z` (`GradingDatum.realize`). -/
theorem compTT_gammaTT (ν ν' : Multiset I) (Z : TwSq LP I G.degΨ qUnitLP) :
    G.k0TensorEquiv hPQ hP hG ν ν' (G.compTT ν ν' (G.gammaTT Z)) = G.realize ν ν' Z := by
  induction Z using TwistedMonoidAlgebra.induction_linear with
  | zero => simp
  | add Z Z' hZ hZ' => rw [map_add, map_add, map_add, hZ, hZ', map_add]
  | single p c =>
    obtain ⟨u, w⟩ := p
    rw [gammaTT_single, map_smul, map_smul, compTT_tmul, k0TensorEquiv_tmul,
      TwistedMonoidAlgebra.single_eq_smul, map_smul, ← tw_word (dot := G.degΨ) (v := qUnitLP),
      realize_tw]

/-- **`Δ ∘ γ = (γ ⊗ γ) ∘ r`** (KL I, Proposition 3.2 and its proof; Lusztig's `r` for the pairing
`degΨ` and `v = q`). -/
theorem coprod_gammaG (x : PreF LP I) :
    G.coprod hPQ hP hG (G.gammaG x) = G.gammaTT (r G.degΨ qUnitLP x) :=
  G.ext_compTT fun ν ν' => (G.k0TensorEquiv hPQ hP hG ν ν').injective (by
    rw [coprod_spec, compTT_gammaTT, resComp_gammaG])

/-- `γ ⊗ γ` is multiplicative for the twisted products of `'f ⊗ 'f` and of `K₀(R) ⊗ K₀(R)`. -/
theorem gammaTT_mul (Z Z' : TwSq LP I G.degΨ qUnitLP) :
    G.gammaTT (Z * Z') = G.twMul (G.gammaTT Z) (G.gammaTT Z') := by
  induction Z using TwistedMonoidAlgebra.induction_linear with
  | zero => simp
  | add Z₁ Z₂ h₁ h₂ => rw [add_mul, map_add, h₁, h₂, map_add, map_add, LinearMap.add_apply]
  | single p c =>
    induction Z' using TwistedMonoidAlgebra.induction_linear with
    | zero => simp
    | add Z₁ Z₂ h₁ h₂ => rw [mul_add, map_add, h₁, h₂, map_add, map_add]
    | single p' c' =>
      obtain ⟨u, w⟩ := p
      obtain ⟨u', w'⟩ := p'
      rw [twSq_single_mul_single, gammaTT_single, gammaTT_single, gammaTT_single, map_smul,
        map_smul, LinearMap.smul_apply, gammaG_word_eq_of G w, gammaG_word_eq_of G u',
        twMul_tmul, ← gammaG_word_eq_of G w, ← gammaG_word_eq_of G u', ← map_mul, ← map_mul,
        Prod.fst_mul, Prod.snd_mul, word_mul, word_mul, val_qUnitLP_zpow, smul_smul, smul_smul]
      congr 1
      ring

/-- **KL I, Proposition 3.2 on the image of `γ`**: `Δ(γ(x) γ(y)) = Δ(γ x) Δ(γ y)` for the
twisted multiplication (3.1). -/
theorem coprod_mul_gammaG (x y : PreF LP I) :
    G.coprod hPQ hP hG (G.gammaG x * G.gammaG y) =
      G.twMul (G.coprod hPQ hP hG (G.gammaG x)) (G.coprod hPQ hP hG (G.gammaG y)) := by
  rw [← map_mul, coprod_gammaG, coprod_gammaG, coprod_gammaG, map_mul, gammaTT_mul]

/-- `Δ(1) = 1 ⊗ 1`. -/
theorem coprod_one : G.coprod hPQ hP hG 1 = 1 ⊗ₜ 1 := by
  rw [← map_one G.gammaG, coprod_gammaG, map_one, TwistedMonoidAlgebra.one_def, gammaTT_single,
    one_smul]
  change G.gammaG (word 1) ⊗ₜ G.gammaG (word 1) = _
  rw [show (word 1 : PreF LP I) = 1 from rfl, map_one]

end Gamma

/-! ### Coassociativity on the image of `γ` -/

section Coassoc

/-- `γ ⊗ γ ⊗ γ` on the twisted triple tensor product, `x ⊗ y ⊗ z ↦ (γx ⊗ γy) ⊗ γz` on words. -/
def gammaTTT : TwCube LP I G.degΨ qUnitLP →ₗ[LP] (G.K0R ⊗[LP] G.K0R) ⊗[LP] G.K0R :=
  TwistedMonoidAlgebra.lift fun p =>
    (G.gammaG (word p.1) ⊗ₜ G.gammaG (word p.2.1)) ⊗ₜ G.gammaG (word p.2.2)

theorem gammaTTT_single (a : FreeMonoid I × FreeMonoid I × FreeMonoid I) (c : LP) :
    G.gammaTTT (TwistedMonoidAlgebra.single a c) =
      c • ((G.gammaG (word a.1) ⊗ₜ G.gammaG (word a.2.1)) ⊗ₜ G.gammaG (word a.2.2)) :=
  TwistedMonoidAlgebra.lift_single _ _ _

set_option synthInstance.maxHeartbeats 400000 in
theorem gammaTTT_inclL_mul_in3 (X : TwSq LP I G.degΨ qUnitLP) (e : FreeMonoid I) :
    G.gammaTTT (inclL G.degΨ qUnitLP X * in3 G.degΨ qUnitLP (word e)) =
      G.gammaTT X ⊗ₜ G.gammaG (word e) := by
  induction X using TwistedMonoidAlgebra.induction_linear with
  | zero =>
    rw [_root_.map_zero (inclL G.degΨ qUnitLP), zero_mul, LinearMap.map_zero, LinearMap.map_zero,
      TensorProduct.zero_tmul]
  | add X X' hX hX' =>
    rw [_root_.map_add (inclL G.degΨ qUnitLP), add_mul, LinearMap.map_add, hX, hX',
      LinearMap.map_add, TensorProduct.add_tmul]
  | single p s =>
    obtain ⟨u, w⟩ := p
    rw [inclL_single, in3_word, twCube_single_mul_single,
      show ((u, w, (1 : FreeMonoid I)) * ((1 : FreeMonoid I), (1 : FreeMonoid I), e)) =
        (u, w, e) by simp,
      gammaTTT_single, gammaTT_single, TensorProduct.smul_tmul']
    congr 1
    simp

set_option synthInstance.maxHeartbeats 400000 in
theorem gammaTTT_in1_mul_inclR (c : FreeMonoid I) (Y : TwSq LP I G.degΨ qUnitLP) :
    G.gammaTTT (in1 G.degΨ qUnitLP (word c) * inclR G.degΨ qUnitLP Y) =
      (TensorProduct.assoc LP G.K0R G.K0R G.K0R).symm (G.gammaG (word c) ⊗ₜ G.gammaTT Y) := by
  induction Y using TwistedMonoidAlgebra.induction_linear with
  | zero =>
    rw [_root_.map_zero (inclR G.degΨ qUnitLP), mul_zero, LinearMap.map_zero, LinearMap.map_zero,
      TensorProduct.tmul_zero, LinearEquiv.map_zero]
  | add Y Y' hY hY' =>
    rw [_root_.map_add (inclR G.degΨ qUnitLP), mul_add, LinearMap.map_add, hY, hY',
      LinearMap.map_add, TensorProduct.tmul_add, LinearEquiv.map_add]
  | single p s =>
    obtain ⟨u, w⟩ := p
    rw [inclR_single, in1_word, twCube_single_mul_single,
      show ((c, (1 : FreeMonoid I), (1 : FreeMonoid I)) * ((1 : FreeMonoid I), u, w)) =
        (c, u, w) by simp,
      gammaTTT_single, gammaTT_single, TensorProduct.tmul_smul, LinearEquiv.map_smul,
      TensorProduct.assoc_symm_tmul]
    congr 1
    simp

set_option synthInstance.maxHeartbeats 400000 in
theorem rTensor_coprod_gammaTT (Z : TwSq LP I G.degΨ qUnitLP) :
    (G.coprod hPQ hP hG).rTensor G.K0R (G.gammaTT Z) =
      G.gammaTTT (rTensorId G.degΨ qUnitLP Z) := by
  induction Z using TwistedMonoidAlgebra.induction_linear with
  | zero =>
    rw [LinearMap.map_zero, LinearMap.map_zero, LinearMap.map_zero, LinearMap.map_zero]
  | add Z Z' hZ hZ' =>
    rw [LinearMap.map_add, LinearMap.map_add, hZ, hZ', LinearMap.map_add, LinearMap.map_add]
  | single p s =>
    obtain ⟨c, e⟩ := p
    rw [gammaTT_single, LinearMap.map_smul, LinearMap.rTensor_tmul, coprod_gammaG,
      rTensorId_single, LinearMap.map_smul, gammaTTT_inclL_mul_in3]

set_option synthInstance.maxHeartbeats 400000 in
theorem lTensor_coprod_gammaTT (Z : TwSq LP I G.degΨ qUnitLP) :
    (TensorProduct.assoc LP G.K0R G.K0R G.K0R).symm
        ((G.coprod hPQ hP hG).lTensor G.K0R (G.gammaTT Z)) =
      G.gammaTTT (idTensorR G.degΨ qUnitLP Z) := by
  induction Z using TwistedMonoidAlgebra.induction_linear with
  | zero =>
    rw [LinearMap.map_zero, LinearMap.map_zero, LinearEquiv.map_zero, LinearMap.map_zero,
      LinearMap.map_zero]
  | add Z Z' hZ hZ' =>
    rw [LinearMap.map_add, LinearMap.map_add, LinearEquiv.map_add, hZ, hZ', LinearMap.map_add,
      LinearMap.map_add]
  | single p s =>
    obtain ⟨c, e⟩ := p
    rw [gammaTT_single, LinearMap.map_smul, LinearEquiv.map_smul, LinearMap.lTensor_tmul,
      coprod_gammaG, idTensorR_single, LinearMap.map_smul, gammaTTT_in1_mul_inclR]

set_option synthInstance.maxHeartbeats 400000 in
/-- **Coassociativity of `Δ` on the image of `γ`** (from the coassociativity of `r`):
`(Δ ⊗ 1) Δ (γ x) = (1 ⊗ Δ) Δ (γ x)`. -/
theorem coassoc_gammaG (x : PreF LP I) :
    (G.coprod hPQ hP hG).rTensor G.K0R (G.coprod hPQ hP hG (G.gammaG x)) =
      (TensorProduct.assoc LP G.K0R G.K0R G.K0R).symm
        ((G.coprod hPQ hP hG).lTensor G.K0R (G.coprod hPQ hP hG (G.gammaG x))) := by
  rw [coprod_gammaG, rTensor_coprod_gammaTT, lTensor_coprod_gammaTT, PreF.coassoc]

end Coassoc

end GradingDatum

/-! ### The KL I grading: Propositions 3.1 and 3.2 on all of `K₀(R)` -/

namespace KLGamma

open KLRAlgebra

variable (k) (Γ : SimpleGraph I) [DecidableRel Γ.Adj]

local notation "Gkl" => klGradingDatum k Γ

/-- `Δ = [Res]` for the rings `R` of KL I. -/
abbrev coprodKL : (Gkl).K0R →ₗ[LP] (Gkl).K0R ⊗[LP] (Gkl).K0R :=
  (Gkl).coprod (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec) (fun a b _ => KL1.klP_ne_zero _ a b)
    KL1.klGradingDatum_degX_pos

/-- **Every class is a `ℤ[q, q⁻¹]`-torsion multiple of an element of `γ('f_{ℤ[q,q⁻¹]})`**: for
`x ∈ K₀(R)` there is `p ≠ 0` with `p x = γ(y)`. (The divided-power classes span `K₀(R)`, KL I
Proposition 3.20, and `[P_î] = î! [P_i]`.) -/
theorem exists_smul_mem_range_gammaZ (x : (Gkl).K0R) :
    ∃ p : LP, p ≠ 0 ∧ ∃ y : PreF LP I, gammaZ k Γ y = p • x := by
  classical
  let S : Submodule LP (Gkl).K0R :=
    { carrier := {x | ∃ p : LP, p ≠ 0 ∧ ∃ y : PreF LP I, gammaZ k Γ y = p • x}
      add_mem' := by
        rintro x x' ⟨p, hp, y, hy⟩ ⟨p', hp', y', hy'⟩
        refine ⟨p * p', mul_ne_zero hp hp', p' • y + p • y', ?_⟩
        rw [map_add, map_smul, map_smul, hy, hy', smul_smul, smul_smul, smul_add, mul_comm p' p]
      zero_mem' := ⟨1, one_ne_zero, 0, by rw [map_zero, smul_zero]⟩
      smul_mem' := by
        rintro c x ⟨p, hp, y, hy⟩
        exact ⟨p, hp, c • y, by rw [map_smul, hy, smul_comm]⟩ }
  have hdiv : ∀ (ν : Multiset I) (d : List (I × ℕ)) (h : (expandDiv d : Multiset I) = ν),
      DirectSum.of (Gkl).K0fam ν (K0.of (projDiv k Γ d h)) ∈ S := by
    intro ν d h
    refine ⟨divQFactLP d, fun h0 => qToV_divQFactLP_ne_zero d (by rw [h0, map_zero]),
      word (FreeMonoid.ofList (expandDiv d)), ?_⟩
    rw [gammaZ_word, FreeMonoid.toList_ofList, clsSeq_expandDiv, clsDiv_eq k Γ d h]
  have hb : ∀ (ν : Multiset I) (b : GProj.IndecClass ((Gkl).grade ν)),
      DirectSum.of (Gkl).K0fam ν (k0B k Γ ν b) ∈ S := by
    intro ν b
    have hle : Submodule.span LP
        {z | ∃ (d : List (I × ℕ)) (h : (expandDiv d : Multiset I) = ν),
          z = K0.of (projDiv k Γ d h)} ≤
        S.comap (DirectSum.lof LP (Multiset I) (Gkl).K0fam ν) := by
      rw [Submodule.span_le]
      rintro _ ⟨d, h, rfl⟩
      show DirectSum.lof LP (Multiset I) (Gkl).K0fam ν _ ∈ S
      rw [DirectSum.lof_eq_of]
      exact hdiv ν d h
    have := hle (k0B_mem_span_projDiv k Γ ν b)
    rwa [Submodule.mem_comap, DirectSum.lof_eq_of] at this
  have htop : S = ⊤ := by
    refine Submodule.eq_top_iff'.2 fun z => ?_
    induction z using DirectSum.induction_on with
    | zero => exact S.zero_mem
    | of ν x =>
      haveI := ((Gkl).finite_and_card_indecClass_le (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec)
        (fun a b _ => KL1.klP_ne_zero _ a b) KL1.klGradingDatum_degX_pos ν).1
      haveI := Fintype.ofFinite (GProj.IndecClass ((Gkl).grade ν))
      rw [← (k0B k Γ ν).sum_repr x, map_sum]
      refine S.sum_mem fun b _ => ?_
      rw [K0R_of_smul]
      exact S.smul_mem _ (hb ν b)
    | add x y hx hy => exact S.add_mem hx hy
  exact (htop ▸ Submodule.mem_top : x ∈ S)

set_option synthInstance.maxHeartbeats 400000 in
instance : NoZeroSMulDivisors LP ((Gkl).K0R ⊗[LP] (Gkl).K0R) := by
  haveI := K0R_free k Γ
  infer_instance

set_option synthInstance.maxHeartbeats 400000 in
instance : NoZeroSMulDivisors LP (((Gkl).K0R ⊗[LP] (Gkl).K0R) ⊗[LP] (Gkl).K0R) := by
  haveI := K0R_free k Γ
  infer_instance

set_option synthInstance.maxHeartbeats 400000 in
/-- **KL I, Proposition 3.2**: `[Res]` is an algebra homomorphism for the twisted multiplication
(3.1) on `K₀(R) ⊗ K₀(R)`: `Δ(xy) = Δ(x) Δ(y)` for all `x, y ∈ K₀(R)`, and `Δ(1) = 1 ⊗ 1`. -/
theorem coprod_mul (x y : (Gkl).K0R) :
    coprodKL k Γ (x * y) = (Gkl).twMul (coprodKL k Γ x) (coprodKL k Γ y) := by
  obtain ⟨p, hp, a, ha⟩ := exists_smul_mem_range_gammaZ k Γ x
  obtain ⟨p', hp', b, hb⟩ := exists_smul_mem_range_gammaZ k Γ y
  have key := (Gkl).coprod_mul_gammaG (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec)
    (fun a b _ => KL1.klP_ne_zero _ a b) KL1.klGradingDatum_degX_pos a b
  rw [gammaG_klGradingDatum, ha, hb, smul_mul_smul_comm, map_smul, map_smul, map_smul,
    map_smul, LinearMap.smul_apply, map_smul, smul_smul] at key
  exact smul_right_injective _ (mul_ne_zero hp hp') key

theorem coprod_one : coprodKL k Γ 1 = 1 ⊗ₜ 1 :=
  (Gkl).coprod_one _ _ _

set_option synthInstance.maxHeartbeats 400000 in
/-- **KL I, Proposition 3.1 (coassociativity of `[Res]`)**: `(Δ ⊗ 1) ∘ Δ = (1 ⊗ Δ) ∘ Δ` on
`K₀(R)`, up to the associativity of `⊗`. -/
theorem coassoc (x : (Gkl).K0R) :
    (coprodKL k Γ).rTensor (Gkl).K0R (coprodKL k Γ x) =
      (TensorProduct.assoc LP (Gkl).K0R (Gkl).K0R (Gkl).K0R).symm
        ((coprodKL k Γ).lTensor (Gkl).K0R (coprodKL k Γ x)) := by
  obtain ⟨p, hp, a, ha⟩ := exists_smul_mem_range_gammaZ k Γ x
  have key := (Gkl).coassoc_gammaG (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec)
    (fun a b _ => KL1.klP_ne_zero _ a b) KL1.klGradingDatum_degX_pos a
  rw [gammaG_klGradingDatum, ha, map_smul, map_smul, map_smul, map_smul] at key
  exact smul_right_injective _ hp key

/-- `γ ⊗ γ` on Lusztig's twisted tensor square (Cartan pairing, `v = q⁻¹`). -/
def gammaZTT : TwSq LP I (KL.C Γ).dot qUnitLP⁻¹ →ₗ[LP] (Gkl).K0R ⊗[LP] (Gkl).K0R :=
  TwistedMonoidAlgebra.lift fun p => gammaZ k Γ (word p.1) ⊗ₜ gammaZ k Γ (word p.2)

theorem gammaZTT_single (u w : FreeMonoid I) (c : LP) :
    gammaZTT k Γ (TwistedMonoidAlgebra.single (u, w) c) =
      c • (gammaZ k Γ (word u) ⊗ₜ gammaZ k Γ (word w)) :=
  TwistedMonoidAlgebra.lift_single _ _ _

/-- **KL I, Theorem 1.1 (compatibility of `γ` with the comultiplications), on
`'f_{ℤ[q,q⁻¹]}`**: `[Res] ∘ γ = (γ ⊗ γ) ∘ r` for Lusztig's `r` (Cartan pairing `i · j`,
`v = q⁻¹`: "our `q` is Lusztig's `v⁻¹`"). -/
theorem coprod_gammaZ (x : PreF LP I) :
    coprodKL k Γ (gammaZ k Γ x) = gammaZTT k Γ (r (KL.C Γ).dot qUnitLP⁻¹ x) := by
  have key : ∀ Z : TwSq LP I (Gkl).degΨ qUnitLP,
      (Gkl).gammaTT Z = gammaZTT k Γ (TwistedMonoidAlgebra.recast _ _ Z) := by
    intro Z
    induction Z using TwistedMonoidAlgebra.induction_linear with
    | zero => rw [map_zero, map_zero, map_zero]
    | add Z Z' hZ hZ' => rw [LinearMap.map_add, hZ, hZ', LinearMap.map_add, LinearMap.map_add]
    | single p c =>
      obtain ⟨u, w⟩ := p
      rw [GradingDatum.gammaTT_single, TwistedMonoidAlgebra.recast_single, gammaZTT_single,
        gammaG_klGradingDatum]
  rw [← gammaG_klGradingDatum, GradingDatum.coprod_gammaG, key]
  exact congrArg _ (recast_r_neg (dot := (KL.C Γ).dot) (v := qUnitLP) x)

/-! ### Over `ℚ(v)`: `γ` intertwines Lusztig's `r̄ : f → f ⊗ f` with `[Res]` -/

section Rational

attribute [local instance] qToVAlgebra

set_option synthInstance.maxHeartbeats 400000 in
/-- `K₀(R) ⊗ K₀(R) → K₀(R)_{ℚ(v)} ⊗_{ℚ(v)} K₀(R)_{ℚ(v)}`, `x ⊗ y ↦ x ⊗ y` (additive, and
semilinear along `q ↦ v⁻¹`, `toK0QTT_smul`). -/
def toK0QTT : (Gkl).K0R ⊗[LP] (Gkl).K0R →+ K0Q k Γ ⊗[RatFunc ℚ] K0Q k Γ :=
  TensorProduct.liftAddHom
    { toFun := fun x =>
        { toFun := fun y => toK0Q k Γ x ⊗ₜ[RatFunc ℚ] toK0Q k Γ y
          map_zero' := by rw [map_zero, TensorProduct.tmul_zero]
          map_add' := fun y y' => by rw [map_add, TensorProduct.tmul_add] }
      map_zero' := by ext y; simp
      map_add' := fun x x' => by ext y; simp [TensorProduct.add_tmul] }
    (fun p x y => by
      simp only [AddMonoidHom.coe_mk, ZeroHom.coe_mk, toK0Q_smul]
      exact TensorProduct.smul_tmul _ _ _)

set_option synthInstance.maxHeartbeats 400000 in
theorem toK0QTT_tmul (x y : (Gkl).K0R) :
    toK0QTT k Γ (x ⊗ₜ y) = toK0Q k Γ x ⊗ₜ[RatFunc ℚ] toK0Q k Γ y :=
  TensorProduct.liftAddHom_tmul _ _ _ _

set_option synthInstance.maxHeartbeats 400000 in
theorem toK0QTT_smul (p : LP) (Z : (Gkl).K0R ⊗[LP] (Gkl).K0R) :
    toK0QTT k Γ (p • Z) = qToV p • toK0QTT k Γ Z := by
  induction Z using TensorProduct.induction_on with
  | zero => rw [smul_zero, map_zero, smul_zero]
  | tmul x y =>
    rw [TensorProduct.smul_tmul', toK0QTT_tmul, toK0QTT_tmul, toK0Q_smul,
      TensorProduct.smul_tmul']
  | add Z Z' hZ hZ' => rw [smul_add, map_add, map_add, hZ, hZ', smul_add]

set_option synthInstance.maxHeartbeats 400000 in
/-- `[Res]` over `ℚ(v)`: the base change of `Δ` along `q ↦ v⁻¹`,
`K₀(R)_{ℚ(v)} → K₀(R)_{ℚ(v)} ⊗_{ℚ(v)} K₀(R)_{ℚ(v)}`. -/
def coprodQ : K0Q k Γ →ₗ[RatFunc ℚ] K0Q k Γ ⊗[RatFunc ℚ] K0Q k Γ :=
  (TensorProduct.AlgebraTensorModule.distribBaseChange LP (RatFunc ℚ) (Gkl).K0R
      (Gkl).K0R).toLinearMap ∘ₗ (coprodKL k Γ).baseChange (RatFunc ℚ)

set_option synthInstance.maxHeartbeats 400000 in
theorem distribBaseChange_one_tmul (Z : (Gkl).K0R ⊗[LP] (Gkl).K0R) :
    TensorProduct.AlgebraTensorModule.distribBaseChange LP (RatFunc ℚ) (Gkl).K0R (Gkl).K0R
      ((1 : RatFunc ℚ) ⊗ₜ Z) = toK0QTT k Γ Z := by
  induction Z using TensorProduct.induction_on with
  | zero => rw [TensorProduct.tmul_zero, LinearEquiv.map_zero, AddMonoidHom.map_zero]
  | tmul x y =>
    rw [toK0QTT_tmul]
    rw [TensorProduct.AlgebraTensorModule.distribBaseChange, LinearEquiv.symm_apply_eq,
      LinearEquiv.trans_apply]
    change _ = TensorProduct.AlgebraTensorModule.assoc LP LP (RatFunc ℚ) (RatFunc ℚ) (Gkl).K0R
      (Gkl).K0R (TensorProduct.AlgebraTensorModule.cancelBaseChange LP (RatFunc ℚ) (RatFunc ℚ)
        (RatFunc ℚ ⊗[LP] (Gkl).K0R) (Gkl).K0R
        (((1 : RatFunc ℚ) ⊗ₜ[LP] x) ⊗ₜ[RatFunc ℚ] ((1 : RatFunc ℚ) ⊗ₜ[LP] y)))
    rw [TensorProduct.AlgebraTensorModule.cancelBaseChange_tmul, one_smul,
      TensorProduct.AlgebraTensorModule.assoc_tmul]
  | add Z Z' hZ hZ' =>
    rw [TensorProduct.tmul_add, LinearEquiv.map_add, hZ, hZ', AddMonoidHom.map_add]

set_option synthInstance.maxHeartbeats 400000 in
/-- `Δ_{ℚ(v)}` extends `Δ`: `Δ_{ℚ(v)}(x) = Δ(x)` for `x ∈ K₀(R)`. -/
theorem coprodQ_toK0Q (y : (Gkl).K0R) :
    coprodQ k Γ (toK0Q k Γ y) = toK0QTT k Γ (coprodKL k Γ y) := by
  change coprodQ k Γ ((1 : RatFunc ℚ) ⊗ₜ y) = _
  rw [coprodQ, LinearMap.comp_apply]
  erw [LinearMap.baseChange_tmul]
  exact distribBaseChange_one_tmul k Γ (coprodKL k Γ y)

omit [DecidableEq I] in
theorem qToV_qUnitLP_inv_zpow (n : ℤ) :
    qToV (((qUnitLP⁻¹ : LPˣ) ^ n : LPˣ) : LP) = ((vQ ^ n : (RatFunc ℚ)ˣ) : RatFunc ℚ) := by
  have h : Units.map qToV.toMonoidHom (qUnitLP⁻¹ : LPˣ) = vQ := Units.ext qToV_qUnitLP_inv
  rw [← h, ← map_zpow]
  rfl

variable (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c)

set_option synthInstance.maxHeartbeats 400000 in
/-- `(γ ⊗ γ)(r̄ θ_w) = Δ(γ θ_w)` on words `θ_w = θ_{w_1} ⋯ θ_{w_m}`. -/
theorem map_gammaF_rbar_word (w : FreeMonoid I) :
    TensorProduct.map (gammaF k Γ hGK).toLinearMap (gammaF k Γ hGK).toLinearMap
        (twSqFEquiv _ _ _ (rbar _ _ _ (KL.C Γ).symm (KL.π Γ (word w)))) =
      toK0QTT k Γ (gammaZTT k Γ (r (KL.C Γ).dot qUnitLP⁻¹ (word w))) := by
  obtain ⟨m, f, rfl⟩ : ∃ (m : ℕ) (f : Fin m → I), FreeMonoid.ofList (List.ofFn f) = w :=
    ⟨_, (FreeMonoid.toList w).get, by rw [List.ofFn_get]; rfl⟩
  rw [twSqFEquiv_rbar_π, r_ofFn, r_ofFn, map_sum, map_sum, map_sum, map_sum]
  refine Finset.sum_congr rfl fun b _ => ?_
  rw [toTensorF_single, LinearMap.map_smul, TensorProduct.map_tmul, gammaZTT_single,
    toK0QTT_smul, toK0QTT_tmul, qToV_qUnitLP_inv_zpow]
  simp only [AlgHom.toLinearMap_apply]
  rw [gammaF_π, gammaF_π, gammaQ_word_eq, gammaQ_word_eq]

set_option synthInstance.maxHeartbeats 400000 in
/-- **KL I, Theorem 1.1 (coalgebra part) over `ℚ(v)`**: `γ ⊗ γ` intertwines Lusztig's
comultiplication `r̄ : f → f ⊗ f` with `[Res]`: `(γ ⊗ γ)(r̄ x) = Δ_{ℚ(v)}(γ x)` for all `x ∈ f`
(`f` defined under the quantum Gabber–Kac hypothesis `hGK`). -/
theorem map_gammaF_rbar (x : KL.F Γ) :
    TensorProduct.map (gammaF k Γ hGK).toLinearMap (gammaF k Γ hGK).toLinearMap
        (twSqFEquiv _ _ _ (rbar _ _ _ (KL.C Γ).symm x)) =
      coprodQ k Γ (gammaF k Γ hGK x) := by
  obtain ⟨y, rfl⟩ := PreF.π_surjective x
  induction y using PreF.induction_linear with
  | zero => simp
  | add y y' hy hy' => rw [map_add, map_add, map_add, map_add, hy, hy', map_add, map_add]
  | smul_word w c =>
    rw [map_smul, map_smul, LinearEquiv.map_smul, LinearMap.map_smul, map_smul,
      LinearMap.map_smul, map_gammaF_rbar_word]
    congr 1
    change _ = coprodQ k Γ (gammaF k Γ hGK (KL.π Γ (word w)))
    rw [gammaF_π, gammaQ_word_eq, coprodQ_toK0Q, coprod_gammaZ]

set_option synthInstance.maxHeartbeats 400000 in
/-- **KL I, Theorem 1.1 (coalgebra part) on `_𝒜 f`**: for `x ∈ _𝒜 f`,
`(γ ⊗ γ)(r̄ x) = Δ(γ x)`, the right-hand side computed integrally in `K₀(R) ⊗ K₀(R)` (with
`γ : _𝒜 f ≅ K₀(R)`, `KLGamma.gammaIntEquiv`). -/
theorem map_gammaF_rbar_Af (x : KL.Af Γ) :
    TensorProduct.map (gammaF k Γ hGK).toLinearMap (gammaF k Γ hGK).toLinearMap
        (twSqFEquiv _ _ _ (rbar _ _ _ (KL.C Γ).symm x)) =
      toK0QTT k Γ (coprodKL k Γ (gammaIntEquiv k Γ hGK x)) := by
  rw [map_gammaF_rbar, gammaIntEquiv_apply, gammaInt', ← coprodQ_toK0Q, toK0Q_gammaInt]

set_option synthInstance.maxHeartbeats 400000 in
/-- `K₀(R) ⊗ K₀(R) → K₀(R)_{ℚ(v)} ⊗ K₀(R)_{ℚ(v)}` is injective (`K₀(R) ⊗ K₀(R)` is free over
`ℤ[q, q⁻¹]`, and `q ↦ v⁻¹` is injective); so `r̄` determines `Δ` on `_𝒜 f`. -/
theorem toK0QTT_injective : Function.Injective (toK0QTT k Γ) := by
  haveI := K0R_free k Γ
  have h1 : Function.Injective fun Z : (Gkl).K0R ⊗[LP] (Gkl).K0R =>
      ((1 : RatFunc ℚ) ⊗ₜ[LP] Z : RatFunc ℚ ⊗[LP] ((Gkl).K0R ⊗[LP] (Gkl).K0R)) :=
    Algebra.TensorProduct.includeRight_injective (A := RatFunc ℚ) (qToV_injective)
  intro Z Z' h
  apply h1
  apply (TensorProduct.AlgebraTensorModule.distribBaseChange LP (RatFunc ℚ) (Gkl).K0R
    (Gkl).K0R).injective
  simp only
  rw [distribBaseChange_one_tmul, distribBaseChange_one_tmul, h]

set_option synthInstance.maxHeartbeats 400000 in
/-- **KL I, Theorem 1.1 in full: `γ : _𝒜 f → K₀(R)` is an isomorphism of `ℕ[I]`-graded twisted
bialgebras** (under the quantum Gabber–Kac hypothesis `hGK` used to define `f`):

1. `γ` is a ring isomorphism (`KLGamma.theorem_1_1`);
2. it respects the `ℕ[I]`-gradings (`KLGamma.gammaInt_mem_grade`);
3. `Δ = [Res]` is an algebra homomorphism for the twisted multiplication (3.1), which is
   associative and unital (KL I, Proposition 3.2);
4. `Δ` is coassociative (KL I, Proposition 3.1);
5. `γ` intertwines Lusztig's `r̄` with `Δ`: for `x ∈ _𝒜 f`, `(γ ⊗ γ)(r̄ x) = Δ(γ x)` (compared in
   `K₀(R)_{ℚ(v)} ⊗ K₀(R)_{ℚ(v)}`, into which `K₀(R) ⊗ K₀(R)` embeds). -/
theorem theorem_1_1_bialgebra :
    Function.Bijective (gammaInt' k Γ hGK) ∧
    (∀ {ν : Multiset I} (x : KL.Af Γ) {y : PreF (RatFunc ℚ) I},
      y ∈ PreF.grade (RatFunc ℚ) ν → (x : KL.F Γ) = KL.π Γ y →
        gammaInt' k Γ hGK x ∈
          LinearMap.range (DirectSum.lof LP (Multiset I) (Gkl).K0fam ν)) ∧
    (∀ x y : (Gkl).K0R, coprodKL k Γ (x * y) = (Gkl).twMul (coprodKL k Γ x) (coprodKL k Γ y)) ∧
    coprodKL k Γ 1 = 1 ⊗ₜ 1 ∧
    (∀ X Y Z : (Gkl).K0R ⊗[LP] (Gkl).K0R,
      (Gkl).twMul ((Gkl).twMul X Y) Z = (Gkl).twMul X ((Gkl).twMul Y Z)) ∧
    (∀ X, (Gkl).twMul (1 ⊗ₜ 1) X = X ∧ (Gkl).twMul X (1 ⊗ₜ 1) = X) ∧
    (∀ x : (Gkl).K0R, (coprodKL k Γ).rTensor (Gkl).K0R (coprodKL k Γ x) =
      (TensorProduct.assoc LP (Gkl).K0R (Gkl).K0R (Gkl).K0R).symm
        ((coprodKL k Γ).lTensor (Gkl).K0R (coprodKL k Γ x))) ∧
    (∀ x : KL.Af Γ,
      TensorProduct.map (gammaF k Γ hGK).toLinearMap (gammaF k Γ hGK).toLinearMap
          (twSqFEquiv _ _ _ (rbar _ _ _ (KL.C Γ).symm x)) =
        toK0QTT k Γ (coprodKL k Γ (gammaIntEquiv k Γ hGK x))) ∧
    Function.Injective (toK0QTT k Γ) :=
  ⟨theorem_1_1 k Γ hGK, fun x _ hy hxy => gammaInt_mem_grade k Γ hGK _ x hy hxy,
    coprod_mul k Γ, coprod_one k Γ, (Gkl).twMul_assoc,
    fun X => ⟨(Gkl).twMul_one_left X, (Gkl).twMul_one_right X⟩, coassoc k Γ,
    map_gammaF_rbar_Af k Γ hGK, toK0QTT_injective k Γ⟩

end Rational

end KLGamma

end Categorification.KLR
