/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.Intertwiner
import Categorification.KLR.CyclotomicFinite

/-!
# The composite `Q ∘ P` of Kang–Kashiwara's maps: Theorem 4.15

S.-J. Kang, M. Kashiwara, *Categorification of highest weight modules via
Khovanov–Lauda–Rouquier algebras*, arXiv:1102.4677v4, §4.2: Theorem 4.15, the key computation in
the proof of the exact sequence (Theorem 4.7) and of projectivity (Theorem 4.5).

Fix a weight `ν` with `m = card ν` strands and a cyclotomic datum `a : I → k[X]`. Write
`Ψ_r = ψ_0 ψ_1 ⋯ ψ_{r-1}` and `G_r = g_{r-1} ⋯ g_1 g_0` (zero-indexed; `g_j = gInt j`, KK (4.7)).
For `r = card ν - 1 = n` and the sequence `𝐢 = (i, ν')`, right multiplication by
`a^Λ(x_1) Ψ_n` is KK's map `P : K_1 → K_0` and right multiplication by `G_n` is KK's
`Q : K_0 → K_1`. Theorem 4.15 says that `Q ∘ P` is right multiplication by
`A_{ν'} = a_i^Λ(x_1) ∏_{ν'_b ≠ i} Q_{i, ν'_b}(x_1, x_{b+1})` on
`K_1 = R e(i, β) / R a^Λ(x_2) R^1(β) e(i, β)`.

Here `K_1`'s denominator is the left ideal `cycL1 a` of `R(ν)` generated by
`a^Λ(x_2) w` for `w` in the subalgebra generated by the dots, the idempotents and the crossings
`ψ_j` with `j ≥ 1` (the image of `k[x_1] ⊗ R^1(β)` summed over the first colour), and the
statement is `cyc_tau_g`:

`a_{i_1}(x_1) Ψ_r G_r e(𝐢) ≡ a_{i_1}(x_1) F_r(𝐢) e(𝐢)  (mod cycL1 a)`, where
`F_r(𝐢) = ∏_{b = 1}^{r} (−1 if i_b = i_1, else Q_{i_1 i_b}(x_1, x_b))`.

**Sign.** The crossings of this library satisfy `ψ_j x_j − x_{j+1} ψ_j = e` on equal labels, the
opposite sign to KK's `τ_j`; with `τ ↦ −ψ` on equal labels (and `τ = ψ` otherwise) KK's
`τ_1 ⋯ τ_n e(i, ν') = (−1)^{β_i} Ψ_n e(i, ν')`, `β_i` the number of entries of `ν'` equal to
`i`, while `g_j` is literally KK's element. So `F_n = (−1)^{β_i} ∏ Q`, which is exactly
KK's `A_ν` once the sign of `P` is accounted for.

The proof follows KK's induction on `r`; every step not involving the cyclotomic relation is an
identity in `R(ν)` (`tau_g_succ_of_eq`, `tau_g_succ_of_ne`, `tau_g_two_of_ne`,
`tau_g_two_of_eq`). It works over any commutative ring for symmetric `Q`.
-/

namespace Categorification.KLR

open MvPolynomial TypeA Equiv PolyRep NilHecke

variable {I : Type*} [DecidableEq I] {k : Type*} [CommRing k]

namespace KLRAlgebra

variable {Q : I → I → MvPolynomial (Fin 2) k} {ν : Multiset I}

local notation "m" => Multiset.card ν
local notation "A" => KLRAlgebra k Q ν

/-! ### Moving idempotents -/

/-- If `y e(t) = e(w t) y e(t)` for all `t`, then `e(w t) y = y e(t)`. -/
theorem e_mul_of_mul_e (y : A) (w : Perm (Fin m)) (hy : ∀ t, y * e t = e (w • t) * y * e t)
    (t : Seq ν) : e (w • t) * y = y * e t := by
  calc e (w • t) * y = ∑ u, e (w • t) * (y * e u) := by
          rw [← Finset.mul_sum, ← Finset.mul_sum, sum_e, mul_one]
    _ = ∑ u, if u = t then y * e t else 0 := by
          refine Finset.sum_congr rfl fun u _ => ?_
          rw [hy u, ← mul_assoc, ← mul_assoc, e_mul_e]
          by_cases hu : u = t
          · subst hu; simp only [↓reduceIte]; exact (hy u).symm
          · have : w • t ≠ w • u := fun h => hu (MulAction.injective w h).symm
            simp only [this, hu, ↓reduceIte, zero_mul]
    _ = y * e t := by simp

omit [DecidableEq I] in
theorem sadj_eq_swap {j : ℕ} (h : j + 1 < m) :
    sadj m j = swap (⟨j, by omega⟩ : Fin m) ⟨j + 1, h⟩ := dite_eq_left h

theorem commute_e_x (t : Seq ν) (b : Fin m) : Commute (e t : A) (x b) := (x_mul_e b t).symm

theorem commute_e_pol (t : Seq ν) (f : MvPolynomial (Fin m) k) : Commute (e t : A) (pol f) :=
  e_commute_pol t f

theorem commute_e_ψ {j : ℕ} (h : j + 1 < m) {t : Seq ν}
    (ht : t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩) : Commute (e t : A) (ψ j) :=
  (ψ_mul_e_comm j h ht).symm

/-! ### `g_j` on idempotents -/

theorem gInt_mul_e (j : ℕ) (h : j + 1 < m) (t : Seq ν) :
    (gInt j h * e t : A) = (if t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩ then
      (x ⟨j + 1, h⟩ - x ⟨j, by omega⟩) + (x ⟨j + 1, h⟩ - x ⟨j, by omega⟩) ^ 2 * ψ j
    else ψ j) * e t := by
  rw [gInt, Finset.sum_mul, Finset.sum_eq_single t]
  · rw [mul_assoc, e_mul_self]
  · intro i _ hi; rw [mul_assoc, e_mul_e]; simp only [hi, ↓reduceIte, mul_zero]
  · simp

theorem gInt_mul_e_of_ne (j : ℕ) (h : j + 1 < m) {t : Seq ν}
    (ht : t.1 ⟨j, by omega⟩ ≠ t.1 ⟨j + 1, h⟩) : (gInt j h * e t : A) = ψ j * e t := by
  rw [gInt_mul_e]; simp only [ht, ↓reduceIte]

theorem gInt_mul_e_of_eq (j : ℕ) (h : j + 1 < m) {t : Seq ν}
    (ht : t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩) : (gInt j h * e t : A) =
      ((x ⟨j + 1, h⟩ - x ⟨j, by omega⟩) + (x ⟨j + 1, h⟩ - x ⟨j, by omega⟩) ^ 2 * ψ j) * e t := by
  rw [gInt_mul_e]; simp only [ht, ↓reduceIte]

theorem gInt_mul_e_eq_e_mul (j : ℕ) (h : j + 1 < m) (t : Seq ν) :
    (gInt j h * e t : A) = e (sadj m j • t) * gInt j h * e t := by
  rw [mul_assoc, gInt_mul_e]
  split_ifs with hc
  · rw [sadj_smul_eq_self h hc]
    have hcomm : Commute (e t : A)
        ((x ⟨j + 1, h⟩ - x ⟨j, by omega⟩) + (x ⟨j + 1, h⟩ - x ⟨j, by omega⟩) ^ 2 * ψ j) :=
      ((commute_e_x t _).sub_right (commute_e_x t _)).add_right
        ((((commute_e_x t _).sub_right (commute_e_x t _)).pow_right 2).mul_right
          (commute_e_ψ h hc))
    rw [← mul_assoc, hcomm.eq, mul_assoc, e_mul_self]
  · rw [ψ_mul_e, ← mul_assoc, e_mul_self]

theorem e_mul_gInt (j : ℕ) (h : j + 1 < m) (t : Seq ν) :
    (e (sadj m j • t) * gInt j h : A) = gInt j h * e t :=
  e_mul_of_mul_e _ _ (gInt_mul_e_eq_e_mul j h) t

theorem gInt_mul_e_comm (j : ℕ) (h : j + 1 < m) (t : Seq ν) :
    (gInt j h * e t : A) = e (sadj m j • t) * gInt j h :=
  (e_mul_gInt j h t).symm

/-! ### The products `G_r = g_{r-1} ⋯ g_0` and `Ψ_r = ψ_0 ⋯ ψ_{r-1}` -/

/-- `g_j`, extended by zero out of range. -/
noncomputable def gI (j : ℕ) : A := if h : j + 1 < m then gInt j h else 0

theorem gI_of_lt {j : ℕ} (h : j + 1 < m) : (gI j : A) = gInt j h := dite_eq_left h

/-- `G_r = g_{r-1} ⋯ g_1 g_0`. -/
noncomputable def gProd (r : ℕ) : A := ((List.range r).reverse.map gI).prod

@[simp] theorem gProd_zero : (gProd 0 : A) = 1 := by simp [gProd]

theorem gProd_succ (r : ℕ) : (gProd (r + 1) : A) = gI r * gProd r := by
  simp [gProd, List.range_succ]

/-- The permutation `c_r = s_{r-1} ⋯ s_0` of `Fin n` carried by `G_r`. -/
def cP (n r : ℕ) : Perm (Fin n) := ((List.range r).reverse.map (sadj n)).prod

omit [DecidableEq I] in
theorem cP_zero (n : ℕ) : cP n 0 = 1 := by simp [cP]

omit [DecidableEq I] in
theorem cP_succ (n r : ℕ) : cP n (r + 1) = sadj n r * cP n r := by
  simp [cP, List.range_succ]

theorem gProd_mul_e (r : ℕ) (hr : r < m) (t : Seq ν) :
    (gProd r * e t : A) = e (cP m r • t) * gProd r := by
  induction r generalizing t with
  | zero => simp [cP_zero m]
  | succ r ih =>
    rw [gProd_succ, cP_succ m, mul_assoc, ih (by omega), ← mul_assoc, gI_of_lt (by omega),
      gInt_mul_e_comm, mul_assoc, mul_smul]

omit [DecidableEq I] in
/-- `c_r⁻¹` sends `b < r` to `b + 1`, `r` to `0`, and fixes `b > r`. -/
theorem cP_symm_val (n r : ℕ) (hr : r < n) (b : Fin n) :
    ((cP n r).symm b).val = if b.val < r then b.val + 1 else if b.val = r then 0 else b.val := by
  induction r generalizing b with
  | zero =>
    rw [cP_zero]
    show b.val = _
    split_ifs <;> omega
  | succ r ih =>
    have e1 : (cP n (r + 1)).symm b = (cP n r).symm (sadj n r b) := by
      rw [cP_succ]; show (cP n r).symm ((sadj n r).symm b) = _; rw [sadj_symm]
    rw [e1, ih (by omega), sadj_apply_val (by omega)]
    split_ifs <;> omega

omit [DecidableEq I] in
theorem cP_smul_apply (r : ℕ) (t : Seq ν) (b : Fin m) :
    (cP m r • t).1 b = t.1 ((cP m r).symm b) := Seq.smul_apply _ _ _

omit [DecidableEq I] in
theorem cP_smul_apply_self (r : ℕ) (hr : r < m) (t : Seq ν) :
    (cP m r • t).1 ⟨r, hr⟩ = t.1 ⟨0, by omega⟩ := by
  rw [cP_smul_apply]; apply lbl_congr; rw [cP_symm_val m r hr]; simp

omit [DecidableEq I] in
theorem cP_smul_apply_of_lt (r : ℕ) (hr : r < m) (t : Seq ν) (b : Fin m) (hb : r < b.val) :
    (cP m r • t).1 b = t.1 b := by
  rw [cP_smul_apply]; apply lbl_congr; rw [cP_symm_val m r hr]
  split_ifs <;> omega

/-- `Ψ_r = ψ_0 ψ_1 ⋯ ψ_{r-1}`. -/
noncomputable abbrev tauProd (r : ℕ) : A := ψw (List.range r)

theorem tauProd_succ (r : ℕ) : (tauProd (r + 1) : A) = tauProd r * ψ r := by
  simp [tauProd, ψw, List.range_succ]

@[simp] theorem tauProd_zero : (tauProd 0 : A) = 1 := by simp [tauProd, ψw]

theorem ψ_mul_tauProd (j r : ℕ) (hj : r + 1 ≤ j) :
    (ψ j * tauProd r : A) = tauProd r * ψ j := by
  induction r with
  | zero => simp [tauProd, ψw]
  | succ r ih =>
    rw [tauProd_succ, ← mul_assoc, ih (by omega), mul_assoc, ← ψ_mul_ψ r j (by omega), mul_assoc]

/-! ### Polynomials past `g_j` and `G_r` -/

section hsym

variable (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b))
include hsym

theorem x_mul_gInt' (j : ℕ) (h : j + 1 < m) (b : Fin m) :
    (x b * gInt j h : A) = gInt j h * x (swap (⟨j, by omega⟩ : Fin m) ⟨j + 1, h⟩ b) := by
  have := x_mul_gInt hsym j h (swap (⟨j, by omega⟩ : Fin m) ⟨j + 1, h⟩ b)
  rwa [swap_apply_self] at this

theorem pol_mul_gInt (j : ℕ) (h : j + 1 < m) (f : MvPolynomial (Fin m) k) :
    (pol f * gInt j h : A) = gInt j h * pol (swapPol j h f) := by
  induction f using MvPolynomial.induction_on with
  | C c => rw [algHom_C, swapPol, rename_C, algHom_C, Algebra.commutes]
  | add f g hf hg => rw [map_add, map_add, map_add, add_mul, mul_add, hf, hg]
  | mul_X f b hf =>
    rw [map_mul, map_mul, pol_X, mul_assoc, x_mul_gInt' hsym, ← mul_assoc, hf, mul_assoc, map_mul,
      swapPol, rename_X, pol_X]

theorem pol_mul_gProd (r : ℕ) (hr : r < m) (f : MvPolynomial (Fin m) k) :
    (pol f * gProd r : A) = gProd r * pol (rename (cP m r).symm f) := by
  induction r generalizing f with
  | zero =>
    rw [gProd_zero, mul_one, one_mul, cP_zero]
    exact congrArg pol (rename_id_apply f).symm
  | succ r ih =>
    have key : (⇑(cP m r).symm ∘ ⇑(swap (⟨r, by omega⟩ : Fin m) ⟨r + 1, hr⟩)) =
        ⇑(cP m (r + 1)).symm := by
      funext b
      rw [cP_succ, Function.comp_apply, ← sadj_eq_swap (by omega)]
      show _ = (cP m r).symm ((sadj m r).symm b)
      rw [sadj_symm]
    rw [gProd_succ, ← mul_assoc, gI_of_lt (by omega), pol_mul_gInt hsym, mul_assoc,
      ih (by omega), ← mul_assoc, swapPol, rename_rename, key]

end hsym

/-! ### Crossings past `g_l` and `G_r` -/

theorem ψ_mul_gInt_far (j l : ℕ) (hl : l + 1 < m) (hjl : l + 2 ≤ j ∨ j + 2 ≤ l) :
    (ψ j * gInt l hl : A) = gInt l hl * ψ j := by
  have hxp : ∀ b : Fin m, (b.val = l ∨ b.val = l + 1) → Commute (ψ j : A) (x b) := fun b hb =>
    (x_mul_ψ b j (by omega) (by omega)).symm
  have hψ : Commute (ψ j : A) (ψ l) := by
    rcases hjl with h | h
    · exact (ψ_mul_ψ l j (by omega)).symm
    · exact ψ_mul_ψ j l (by omega)
  apply ext_e
  intro t
  have hl1 : (sadj m j • t).1 ⟨l, by omega⟩ = t.1 ⟨l, by omega⟩ := by
    rw [sadj_smul_apply, sadj_apply_of_ne _ (by simp; omega) (by simp; omega)]
  have hl2 : (sadj m j • t).1 ⟨l + 1, hl⟩ = t.1 ⟨l + 1, hl⟩ := by
    rw [sadj_smul_apply, sadj_apply_of_ne _ (by simp; omega) (by simp; omega)]
  obtain ⟨c, hcomm, hct, hcst⟩ : ∃ c : A, Commute (ψ j) c ∧ gInt l hl * e t = c * e t ∧
      gInt l hl * e (sadj m j • t) = c * e (sadj m j • t) := by
    refine ⟨_, ?_, gInt_mul_e l hl t, by rw [gInt_mul_e, hl1, hl2]⟩
    split_ifs
    · exact ((hxp _ (Or.inr rfl)).sub_right (hxp _ (Or.inl rfl))).add_right
        ((((hxp _ (Or.inr rfl)).sub_right (hxp _ (Or.inl rfl))).pow_right 2).mul_right hψ)
    · exact hψ
  calc ψ j * gInt l hl * e t = ψ j * (gInt l hl * e t) := mul_assoc _ _ _
    _ = c * (ψ j * e t) := by rw [hct, ← mul_assoc, hcomm.eq, mul_assoc]
    _ = gInt l hl * ψ j * e t := by
      rw [ψ_mul_e, ← mul_assoc, ← hcst, mul_assoc, mul_assoc, ← ψ_mul_e, ← mul_assoc]

theorem ψ_mul_gProd (j r : ℕ) (hr : r < m) (hj : r + 1 ≤ j) :
    (ψ j * gProd r : A) = gProd r * ψ j := by
  induction r with
  | zero => simp
  | succ r ih =>
    rw [gProd_succ, ← mul_assoc, gI_of_lt (by omega), ψ_mul_gInt_far j r _ (Or.inl (by omega)),
      mul_assoc, ih (by omega) (by omega), mul_assoc]

/-! ### Crossings past polynomials -/

theorem ψ_mul_pol_mul_e_of_ne (j : ℕ) (h : j + 1 < m) {t : Seq ν}
    (ht : t.1 ⟨j, by omega⟩ ≠ t.1 ⟨j + 1, h⟩) (f : MvPolynomial (Fin m) k) :
    (ψ j * pol f * e t : A) = pol (swapPol j h f) * ψ j * e t := by
  rw [ψ_mul_pol_mul_e j h t f]; simp only [ht, ↓reduceIte, add_zero]

theorem ψ_mul_pol_mul_e_of_eq (j : ℕ) (h : j + 1 < m) {t : Seq ν}
    (ht : t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩) (f : MvPolynomial (Fin m) k) :
    (ψ j * pol f * e t : A) = pol (swapPol j h f) * ψ j * e t + pol (dd k m j f) * e t := by
  rw [ψ_mul_pol_mul_e j h t f]; simp only [ht, ↓reduceIte]

theorem ψ_mul_pol_of_symm (j : ℕ) (h : j + 1 < m) {f : MvPolynomial (Fin m) k}
    (hf : swapPol j h f = f) : (ψ j * pol f : A) = pol f * ψ j := by
  have hne : (⟨j, by omega⟩ : Fin m) ≠ ⟨j + 1, h⟩ := fun e => by simp [Fin.ext_iff] at e
  apply ext_e
  intro t
  rw [ψ_mul_pol_mul_e j h t f, hf, dd_of_lt h, ddiff_eq_zero_of_rename_eq hne hf, map_zero,
    zero_mul, ite_self, add_zero]

/-! ### The left ideal `R a^Λ(x_2) R^1(β)` -/

section cyc

variable (a : I → Polynomial k)

/-- `a^Λ(x_p) = ∑_𝐢 a_{i_p}(x_p) e(𝐢)`. -/
noncomputable def cycAt (p : Fin m) : A :=
  ∑ t : Seq ν, pol (Polynomial.aeval (X p) (a (t.1 p))) * e t

theorem cycAt_mul_e (p : Fin m) (s : Seq ν) :
    (cycAt a p * e s : A) = pol (Polynomial.aeval (X p) (a (s.1 p))) * e s := by
  rw [cycAt, Finset.sum_mul, Finset.sum_eq_single s]
  · rw [mul_assoc, e_mul_self]
  · intro i _ hi; rw [mul_assoc, e_mul_e]; simp only [hi, ↓reduceIte, mul_zero]
  · simp

variable (ν) in
/-- The subalgebra generated by all dots, all idempotents and the crossings `ψ_j`, `j ≥ 1`
(the image of `k[x_1] ⊗ R^1(β)`, summed over the colour of the first strand). -/
noncomputable def subR1 : Subalgebra k A :=
  Algebra.adjoin k (Set.range x ∪ Set.range e ∪ {y | ∃ j, 1 ≤ j ∧ y = ψ j})

theorem x_mem_subR1 (b : Fin m) : (x b : A) ∈ subR1 (k := k) (Q := Q) ν :=
  Algebra.subset_adjoin (Or.inl (Or.inl ⟨b, rfl⟩))

theorem e_mem_subR1 (t : Seq ν) : (e t : A) ∈ subR1 (k := k) (Q := Q) ν :=
  Algebra.subset_adjoin (Or.inl (Or.inr ⟨t, rfl⟩))

theorem ψ_mem_subR1 {j : ℕ} (hj : 1 ≤ j) : (ψ j : A) ∈ subR1 (k := k) (Q := Q) ν :=
  Algebra.subset_adjoin (Or.inr ⟨j, hj, rfl⟩)

theorem pol_mem_subR1 (f : MvPolynomial (Fin m) k) : (pol f : A) ∈ subR1 (k := k) (Q := Q) ν :=
  (Algebra.adjoin_mono (fun _ hy => Or.inl (Or.inl hy)) : dotSubalgebra ≤ _)
    (pol_mem_dotSubalgebra f)

/-- **The left ideal `R(ν) a^Λ(x_2) R^1(β)`**, the denominator of KK's `K_1` (summed over the
colour `i` of the first strand). -/
noncomputable def cycL1 (h1 : 1 < m) : Submodule A A :=
  Submodule.span A {z | ∃ w ∈ subR1 (k := k) (Q := Q) ν, z = cycAt a ⟨1, h1⟩ * w}

theorem mul_mem_cycL1 {h1 : 1 < m} {z w : A} (hz : z ∈ cycL1 a h1)
    (hw : w ∈ subR1 (k := k) (Q := Q) ν) : z * w ∈ cycL1 a h1 := by
  induction hz using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w', hw', rfl⟩ := hy
    exact Submodule.subset_span ⟨w' * w, Subalgebra.mul_mem _ hw' hw, by rw [mul_assoc]⟩
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add y z _ _ hy hz => rw [add_mul]; exact Submodule.add_mem _ hy hz
  | smul r y _ hy => rw [smul_eq_mul, mul_assoc]; exact Submodule.smul_mem _ r hy

theorem left_mul_mem_cycL1 {h1 : 1 < m} (r : A) {z : A} (hz : z ∈ cycL1 a h1) :
    r * z ∈ cycL1 a h1 :=
  Submodule.smul_mem _ r hz

theorem cyc_one_mul_e_mem (h1 : 1 < m) (s : Seq ν) :
    (pol (Polynomial.aeval (X ⟨1, h1⟩) (a (s.1 ⟨1, h1⟩))) * e s : A) ∈ cycL1 a h1 := by
  rw [← cycAt_mul_e]
  exact Submodule.subset_span ⟨e s, e_mem_subR1 s, rfl⟩

end cyc

/-! ### Exact identities for `Ψ_r G_r` (KK, proof of Theorem 4.15) -/

section exact

omit [DecidableEq I] in
theorem cP_symm_self (r : ℕ) (hr : r < m) : (cP m r).symm ⟨r, hr⟩ = ⟨0, by omega⟩ :=
  Fin.ext (by rw [cP_symm_val m r hr]; simp)

omit [DecidableEq I] in
theorem cP_symm_of_lt (r : ℕ) (hr : r < m) (b : Fin m) (hb : r < b.val) :
    (cP m r).symm b = b :=
  Fin.ext (by rw [cP_symm_val m r hr]; split_ifs <;> omega)

theorem ψ_gInt_e_of_eq (j : ℕ) (h : j + 1 < m) {t : Seq ν}
    (ht : t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩) :
    (ψ j * gInt j h * e t : A) = ψ j * pol (X ⟨j + 1, h⟩ - X ⟨j, by omega⟩) * e t := by
  have hsq : swapPol j h ((X ⟨j + 1, h⟩ - X ⟨j, by omega⟩) ^ 2 : MvPolynomial (Fin m) k) =
      (X ⟨j + 1, h⟩ - X ⟨j, by omega⟩) ^ 2 := by
    simp only [swapPol, map_pow, map_sub, rename_X, swap_apply_left, swap_apply_right]; ring
  have hx : (x ⟨j + 1, h⟩ - x ⟨j, by omega⟩ : A) = pol (X ⟨j + 1, h⟩ - X ⟨j, by omega⟩) := by
    rw [map_sub, pol_X, pol_X]
  have h0 : (ψ j * (pol ((X ⟨j + 1, h⟩ - X ⟨j, by omega⟩) ^ 2) * ψ j * e t) : A) = 0 := by
    rw [← mul_assoc, ← mul_assoc, ψ_mul_pol_of_symm j h hsq]
    simp only [mul_assoc]
    rw [← mul_assoc (ψ j) (ψ j), ψ_mul_ψ_mul_e_same j h ht, mul_zero]
  rw [mul_assoc, gInt_mul_e_of_eq j h ht, hx, ← map_pow, add_mul, mul_add, h0, add_zero,
    ← mul_assoc]

theorem ψ_gInt_e_of_ne (j : ℕ) (h : j + 1 < m) {t : Seq ν}
    (ht : t.1 ⟨j, by omega⟩ ≠ t.1 ⟨j + 1, h⟩) :
    (ψ j * gInt j h * e t : A) =
      pol (rename ![⟨j, by omega⟩, ⟨j + 1, h⟩] (Q (t.1 ⟨j, by omega⟩) (t.1 ⟨j + 1, h⟩))) * e t := by
  rw [mul_assoc, gInt_mul_e_of_ne j h ht, ← mul_assoc, ψ_sq j h t, ite_eq_right_of_eq_false _ _ (eq_false ht),
    ncEval_x₂]

theorem gProd_succ_mul_e (r : ℕ) (hr : r + 1 < m) (s : Seq ν) :
    (gProd (r + 1) * e s : A) = gInt r hr * (e (cP m r • s) * gProd r) := by
  rw [gProd_succ, gI_of_lt hr, mul_assoc, gProd_mul_e r (by omega) s]

theorem tauProd_two (r : ℕ) : (tauProd (r + 2) : A) = tauProd r * (ψ r * ψ (r + 1)) := by
  rw [show r + 2 = r + 1 + 1 from rfl, tauProd_succ, tauProd_succ, mul_assoc]

theorem e_mul_gProd_assoc (r : ℕ) (hr : r < m) (s : Seq ν) (y : A) :
    e (cP m r • s) * (gProd r * y) = gProd r * (e s * y) := by
  rw [← mul_assoc, ← gProd_mul_e r hr s, mul_assoc]

theorem pol_e_comm_assoc (f : MvPolynomial (Fin m) k) (s : Seq ν) (y : A) :
    pol f * (e s * y) = e s * (pol f * y) := by
  rw [← mul_assoc, ← (commute_e_pol s f).eq, mul_assoc]

theorem pol_mul_pol_assoc (f g : MvPolynomial (Fin m) k) (y : A) :
    pol f * (pol g * y) = pol (f * g) * y := by
  rw [← mul_assoc, map_mul]

section hsym

variable (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b))
include hsym

theorem pol_mul_gProd_assoc (r : ℕ) (hr : r < m) (f : MvPolynomial (Fin m) k) (y : A) :
    pol f * (gProd r * y) = gProd r * (pol (rename (cP m r).symm f) * y) := by
  rw [← mul_assoc, pol_mul_gProd hsym r hr, mul_assoc]

/-- KK (4.15), the identity before case (a): if `i_{r+1} = i_1` then
`Ψ_{r+1} G_{r+1} e(𝐢) = Ψ_{r+1} G_r (x_{r+1} − x_0) e(𝐢)` (zero-indexed). -/
theorem tau_g_succ_of_eq (r : ℕ) (hr : r + 1 < m) {s : Seq ν}
    (hs : s.1 ⟨r + 1, hr⟩ = s.1 ⟨0, by omega⟩) :
    (tauProd (r + 1) * gProd (r + 1) * e s : A) =
      tauProd (r + 1) * gProd r * pol (X ⟨r + 1, hr⟩ - X ⟨0, by omega⟩) * e s := by
  have ht : (cP m r • s).1 ⟨r, by omega⟩ = (cP m r • s).1 ⟨r + 1, hr⟩ := by
    rw [cP_smul_apply_self r (by omega), cP_smul_apply_of_lt r (by omega) s _ (by simp)]
    exact hs.symm
  calc (tauProd (r + 1) * gProd (r + 1) * e s : A)
      = tauProd r * ((ψ r * gInt r hr * e (cP m r • s)) * gProd r) := by
        rw [mul_assoc, gProd_succ_mul_e r hr, tauProd_succ]; simp only [mul_assoc]
    _ = tauProd (r + 1) *
          (pol (X ⟨r + 1, hr⟩ - X ⟨r, by omega⟩) * (e (cP m r • s) * gProd r)) := by
        rw [ψ_gInt_e_of_eq r hr ht, tauProd_succ]; simp only [mul_assoc]
    _ = tauProd (r + 1) * gProd r * pol (X ⟨r + 1, hr⟩ - X ⟨0, by omega⟩) * e s := by
        rw [← gProd_mul_e r (by omega) s, ← mul_assoc (pol _), pol_mul_gProd hsym r (by omega),
          map_sub, rename_X, rename_X, cP_symm_self r (by omega),
          cP_symm_of_lt r (by omega) _ (by simp)]
        simp only [mul_assoc]

/-- KK (4.15), case (i): if `i_{r+1} ≠ i_1` then
`Ψ_{r+1} G_{r+1} e(𝐢) = Ψ_r G_r e(𝐢) Q_{i_1 i_{r+1}}(x_0, x_{r+1})`. -/
theorem tau_g_succ_of_ne (r : ℕ) (hr : r + 1 < m) {s : Seq ν}
    (hs : s.1 ⟨r + 1, hr⟩ ≠ s.1 ⟨0, by omega⟩) :
    (tauProd (r + 1) * gProd (r + 1) * e s : A) =
      tauProd r * gProd r * e s *
        pol (rename ![⟨0, by omega⟩, ⟨r + 1, hr⟩] (Q (s.1 ⟨0, by omega⟩) (s.1 ⟨r + 1, hr⟩))) := by
  have h0 : (cP m r • s).1 ⟨r, by omega⟩ = s.1 ⟨0, by omega⟩ := cP_smul_apply_self r (by omega) s
  have h1 : (cP m r • s).1 ⟨r + 1, hr⟩ = s.1 ⟨r + 1, hr⟩ :=
    cP_smul_apply_of_lt r (by omega) s _ (by simp)
  have ht : (cP m r • s).1 ⟨r, by omega⟩ ≠ (cP m r • s).1 ⟨r + 1, hr⟩ := by
    rw [h0, h1]; exact fun h => hs h.symm
  calc (tauProd (r + 1) * gProd (r + 1) * e s : A)
      = tauProd r * ((ψ r * gInt r hr * e (cP m r • s)) * gProd r) := by
        rw [mul_assoc, gProd_succ_mul_e r hr, tauProd_succ]; simp only [mul_assoc]
    _ = tauProd r * (pol (rename ![⟨r, by omega⟩, ⟨r + 1, hr⟩]
          (Q (s.1 ⟨0, by omega⟩) (s.1 ⟨r + 1, hr⟩))) * (e (cP m r • s) * gProd r)) := by
        rw [ψ_gInt_e_of_ne r hr ht, h0, h1]; simp only [mul_assoc]
    _ = _ := by
        rw [← gProd_mul_e r (by omega) s, ← mul_assoc (pol _), pol_mul_gProd hsym r (by omega),
          rename_rename_vec2, cP_symm_self r (by omega), cP_symm_of_lt r (by omega) _ (by simp),
          mul_assoc (gProd r), ← (commute_e_pol s _).eq]
        simp only [mul_assoc]

theorem tau_g_succ_of_eq_two (r : ℕ) (hr : r + 2 < m) {s : Seq ν}
    (hs : s.1 ⟨r + 2, hr⟩ = s.1 ⟨0, by omega⟩) :
    (tauProd (r + 2) * gProd (r + 2) * e s : A) =
      tauProd (r + 2) * gProd (r + 1) * pol (X ⟨r + 2, hr⟩ - X ⟨0, by omega⟩) * e s :=
  tau_g_succ_of_eq hsym (r + 1) hr hs

theorem tau_g_succ_of_ne_two (r : ℕ) (hr : r + 2 < m) {s : Seq ν}
    (hs : s.1 ⟨r + 2, hr⟩ ≠ s.1 ⟨0, by omega⟩) :
    (tauProd (r + 2) * gProd (r + 2) * e s : A) =
      tauProd (r + 1) * gProd (r + 1) * e s *
        pol (rename ![⟨0, by omega⟩, ⟨r + 2, hr⟩] (Q (s.1 ⟨0, by omega⟩) (s.1 ⟨r + 2, hr⟩))) :=
  tau_g_succ_of_ne hsym (r + 1) hr hs

omit [DecidableEq I] hsym in
theorem rename_rename_vec3 {n n' : ℕ} (g : Fin n → Fin n') (a b c : Fin n)
    (F : MvPolynomial (Fin 3) k) :
    rename g (rename ![a, b, c] F) = rename ![g a, g b, g c] F := by
  have : g ∘ ![a, b, c] = ![g a, g b, g c] := by funext t; fin_cases t <;> rfl
  rw [rename_rename, this]

/-- KK (4.15), case (ii)(a) (zero-indexed): if `i_{r+2} = i_1 ≠ i_{r+1}`, then `Ψ_{r+2} G_{r+2} e(𝐢)`
is `ψ_{r+1} Ψ_{r+1} G_{r+1} e(s_{r+1} 𝐢) ψ_{r+1}` plus
`Ψ_r G_r e(𝐢) Q̄_{i_1 i_{r+1}}(x_0, x_{r+1}, x_{r+2}) (x_{r+2} − x_0)`. -/
theorem tau_g_two_of_ne (r : ℕ) (hr : r + 2 < m) {s : Seq ν}
    (hs2 : s.1 ⟨r + 2, hr⟩ = s.1 ⟨0, by omega⟩)
    (hs1 : s.1 ⟨r + 1, by omega⟩ ≠ s.1 ⟨0, by omega⟩) :
    (tauProd (r + 2) * gProd (r + 2) * e s : A) =
      ψ (r + 1) * (tauProd (r + 1) * gProd (r + 1) * e (sadj m (r + 1) • s)) * ψ (r + 1) +
      tauProd r * gProd r * e s *
        pol (rename ![⟨0, by omega⟩, ⟨r + 1, by omega⟩, ⟨r + 2, hr⟩]
          (qbar (Q (s.1 ⟨0, by omega⟩) (s.1 ⟨r + 1, by omega⟩))) *
            (X ⟨r + 2, hr⟩ - X ⟨0, by omega⟩)) := by
  have hm0 : 0 < m := by omega
  have hrm : r < m := by omega
  have hr1 : r + 1 < m := by omega
  have h0 : (cP m r • s).1 ⟨r, hrm⟩ = s.1 ⟨0, hm0⟩ := cP_smul_apply_self r hrm s
  have h1 : (cP m r • s).1 ⟨r + 1, hr1⟩ = s.1 ⟨r + 1, hr1⟩ :=
    cP_smul_apply_of_lt r hrm s _ (by simp)
  have h2 : (cP m r • s).1 ⟨r + 2, hr⟩ = s.1 ⟨r + 2, hr⟩ :=
    cP_smul_apply_of_lt r hrm s _ (by simp)
  have ht01 : (cP m r • s).1 ⟨r, hrm⟩ ≠ (cP m r • s).1 ⟨r + 1, hr1⟩ := by
    rw [h0, h1]; exact fun h => hs1 h.symm
  have ht02 : (cP m r • s).1 ⟨r, hrm⟩ = (cP m r • s).1 ⟨r + 2, hr⟩ := by
    rw [h0, h2, hs2]
  have hs12 : s.1 ⟨r + 1, hr1⟩ ≠ s.1 ⟨r + 2, hr⟩ := by rw [hs2]; exact hs1
  have hs' : (sadj m (r + 1) • s).1 ⟨r + 1, hr1⟩ = (sadj m (r + 1) • s).1 ⟨0, hm0⟩ := by
    rw [sadj_smul_apply, sadj_smul_apply, sadj_apply_left hr,
      sadj_apply_of_ne _ (by simp) (by simp)]
    exact hs2
  -- the braid relation on `e(c_r 𝐢)`
  have hbr : (ψ r * ψ (r + 1) * ψ r * e (cP m r • s) : A) =
      ψ (r + 1) * ψ r * ψ (r + 1) * e (cP m r • s) +
      pol (rename ![⟨r, hrm⟩, ⟨r + 1, hr1⟩, ⟨r + 2, hr⟩]
        (qbar (Q ((cP m r • s).1 ⟨r, hrm⟩) ((cP m r • s).1 ⟨r + 1, hr1⟩)))) *
        e (cP m r • s) := by
    have hb := braid (Q := Q) r hr (cP m r • s)
    rw [ite_eq_left_of_eq_true _ _ (eq_true ⟨ht02, ht01⟩), ncEval_x₃, sub_mul] at hb
    exact sub_eq_iff_eq_add'.mp hb
  rw [h0, h1] at hbr
  have hbr' : ∀ z : A, ψ r * (ψ (r + 1) * (ψ r * (e (cP m r • s) * z))) =
      ψ (r + 1) * (ψ r * (ψ (r + 1) * (e (cP m r • s) * z))) +
      pol (rename ![⟨r, hrm⟩, ⟨r + 1, hr1⟩, ⟨r + 2, hr⟩]
        (qbar (Q (s.1 ⟨0, hm0⟩) (s.1 ⟨r + 1, hr1⟩)))) * (e (cP m r • s) * z) :=
    fun z => by
      have := congrArg (· * z) hbr
      simp only [add_mul, mul_assoc] at this
      exact this
  -- `ψ_{r+1}` past `(x_{r+2} - x_0) e(𝐢)`
  have hk : swapPol (r + 1) hr
      (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩ : MvPolynomial (Fin m) k) =
      X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩ := by
    simp only [swapPol, map_sub, rename_X, swap_apply_right]
    rw [swap_apply_of_ne_of_ne (by simp [Fin.ext_iff]) (by simp [Fin.ext_iff])]
  have hψg : (ψ (r + 1) * (e s * pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩)) : A) =
      pol (X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) * (e (sadj m (r + 1) • s) * ψ (r + 1)) := by
    have hψ := ψ_mul_pol_mul_e_of_ne (Q := Q) (r + 1) hr hs12
      (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩ : MvPolynomial (Fin m) k)
    rewrite [hk] at hψ
    rewrite [(commute_e_pol s _).eq, ← mul_assoc, hψ, mul_assoc _ (ψ _), ψ_mul_e]
    rfl
  have hcomm1 : Commute (tauProd r : A) (ψ (r + 1)) := (ψ_mul_tauProd (r + 1) r le_rfl).symm
  have hcomm2 : Commute (ψ (r + 1) : A) (gProd r) := ψ_mul_gProd (r + 1) r hrm le_rfl
  rewrite [tau_g_succ_of_eq_two hsym r hr hs2]
  calc _ = tauProd r * (ψ r * (ψ (r + 1) * ((gInt r hr1 * e (cP m r • s)) *
          (gProd r * pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩))))) := by
        rewrite [mul_assoc _ (pol _) (e s), ← (commute_e_pol s _).eq, tauProd_two]
        simp only [mul_assoc]
        rewrite [← mul_assoc (gProd (r + 1)), gProd_succ_mul_e r hr1 s]
        simp only [mul_assoc]
    _ = tauProd r * (ψ r * (ψ (r + 1) * (ψ r * (e (cP m r • s) *
          (gProd r * pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩)))))) := by
        rewrite [gInt_mul_e_of_ne r hr1 ht01]; simp only [mul_assoc]
    _ = _ := by
        rewrite [hbr', mul_add]
        refine congrArg₂ (· + ·) ?_ ?_
        · rewrite [tau_g_succ_of_eq hsym r hr1 hs', tauProd_succ, hcomm1.left_comm,
            e_mul_gProd_assoc r hrm, hcomm2.left_comm, hψg]
          simp only [mul_assoc]
        · rewrite [e_mul_gProd_assoc r hrm, pol_mul_gProd_assoc hsym r hrm,
            pol_e_comm_assoc, ← map_mul, rename_rename_vec3, cP_symm_self r hrm,
            cP_symm_of_lt r hrm _ (by simp), cP_symm_of_lt r hrm _ (by simp)]
          simp only [mul_assoc]

/-- KK (4.15), case (ii)(b) (zero-indexed): if `i_{r+2} = i_{r+1} = i_1`, then
`Ψ_{r+2} G_{r+2} e(𝐢) = Φ (x_{r+2} − x_0) ψ_{r+1} + ψ_{r+1} Φ (x_{r+2} − x_0) ψ_{r+1} (x_{r+1} − x_0) e(𝐢)`
with `Φ = Ψ_{r+1} G_{r+1} e(𝐢)`. -/
theorem tau_g_two_of_eq (r : ℕ) (hr : r + 2 < m) {s : Seq ν}
    (hs2 : s.1 ⟨r + 2, hr⟩ = s.1 ⟨0, by omega⟩)
    (hs1 : s.1 ⟨r + 1, by omega⟩ = s.1 ⟨0, by omega⟩) :
    (tauProd (r + 2) * gProd (r + 2) * e s : A) =
      tauProd (r + 1) * gProd (r + 1) * e s * pol (X ⟨r + 2, hr⟩ - X ⟨0, by omega⟩) *
        ψ (r + 1) +
      ψ (r + 1) * (tauProd (r + 1) * gProd (r + 1) * e s) *
        pol (X ⟨r + 2, hr⟩ - X ⟨0, by omega⟩) * ψ (r + 1) *
        pol (X ⟨r + 1, by omega⟩ - X ⟨0, by omega⟩) * e s := by
  have hm0 : 0 < m := by omega
  have hrm : r < m := by omega
  have hr1 : r + 1 < m := by omega
  have h0 : (cP m r • s).1 ⟨r, hrm⟩ = s.1 ⟨0, hm0⟩ := cP_smul_apply_self r hrm s
  have h1 : (cP m r • s).1 ⟨r + 1, hr1⟩ = s.1 ⟨r + 1, hr1⟩ :=
    cP_smul_apply_of_lt r hrm s _ (by simp)
  have ht01 : (cP m r • s).1 ⟨r, hrm⟩ = (cP m r • s).1 ⟨r + 1, hr1⟩ := by
    rw [h0, h1, hs1]
  have hs12 : s.1 ⟨r + 1, hr1⟩ = s.1 ⟨r + 2, hr⟩ := by rw [hs2, hs1]
  have hsym_kg : swapPol (r + 1) hr ((X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) *
      (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩) : MvPolynomial (Fin m) k) =
      (X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) * (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩) := by
    simp only [swapPol, map_mul, map_sub, rename_X, swap_apply_left, swap_apply_right]
    rw [swap_apply_of_ne_of_ne (by simp [Fin.ext_iff]) (by simp [Fin.ext_iff])]
    ring
  have hsq : swapPol r hr1 ((X ⟨r + 1, hr1⟩ - X ⟨r, hrm⟩) ^ 2 :
      MvPolynomial (Fin m) k) = (X ⟨r + 1, hr1⟩ - X ⟨r, hrm⟩) ^ 2 := by
    simp only [swapPol, map_pow, map_sub, rename_X, swap_apply_left, swap_apply_right]
    ring
  have hx : (x ⟨r + 1, hr1⟩ - x ⟨r, hrm⟩ : A) =
      pol (X ⟨r + 1, hr1⟩ - X ⟨r, hrm⟩) := by
    rw [map_sub, pol_X, pol_X]
  have hrdX : rename (cP m r).symm (X ⟨r + 1, hr1⟩ - X ⟨r, hrm⟩ :
      MvPolynomial (Fin m) k) = X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩ := by
    rw [map_sub, rename_X, rename_X, cP_symm_self r hrm,
      cP_symm_of_lt r hrm _ (by simp)]
  have hbr : ∀ z : A, ψ r * (ψ (r + 1) * (ψ r * (e (cP m r • s) * z))) =
      ψ (r + 1) * (ψ r * (ψ (r + 1) * (e (cP m r • s) * z))) := fun z => by
    have hb := braid (Q := Q) r hr (cP m r • s)
    rw [ite_eq_right_of_eq_false _ _ (eq_false (fun h => h.2 ht01)), sub_mul,
      sub_eq_zero] at hb
    have := congrArg (· * z) hb
    simp only [mul_assoc] at this
    exact this
  have hcomm1 : Commute (tauProd r : A) (ψ (r + 1)) := (ψ_mul_tauProd (r + 1) r le_rfl).symm
  have hcomm2 : Commute (ψ (r + 1) : A) (gProd r) := ψ_mul_gProd (r + 1) r hrm le_rfl
  have hes : Commute (e s : A) (ψ (r + 1)) := commute_e_ψ hr hs12
  have hψkg := ψ_mul_pol_of_symm (Q := Q) (r + 1) hr hsym_kg
  have hψd := ψ_mul_pol_of_symm (Q := Q) r hr1 hsq
  -- the two local computations
  have hT1 : (ψ (r + 1) * (pol (X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) *
      (e s * pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩))) : A) =
      pol (X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) *
        (e s * (pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩) * ψ (r + 1))) := by
    rw [(commute_e_pol s _).eq, ← mul_assoc (pol _), ← map_mul, ← mul_assoc, hψkg, mul_assoc,
      ← hes.eq, map_mul, mul_assoc, pol_e_comm_assoc]
  have hT2 : (ψ (r + 1) * (e s * (pol ((X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) ^ 2) *
      pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩))) : A) =
      pol (X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) * (e s * (pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩) *
        (ψ (r + 1) * (pol (X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) * e s)))) := by
    rw [← map_mul, (commute_e_pol s _).eq,
      show ((X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) ^ 2 * (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩) :
        MvPolynomial (Fin m) k) = ((X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) *
          (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩)) * (X ⟨r + 1, hr1⟩ - X ⟨0, hm0⟩) by ring,
      map_mul, mul_assoc, ← mul_assoc (ψ _), hψkg, mul_assoc, ← pol_e_comm_assoc,
      pol_mul_pol_assoc, hes.left_comm, ← pol_e_comm_assoc, e_mul_self]
  rewrite [tau_g_succ_of_eq_two hsym r hr hs2]
  calc _ = tauProd r * (ψ r * (ψ (r + 1) * ((gInt r hr1 * e (cP m r • s)) *
          (gProd r * pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩))))) := by
        rewrite [mul_assoc _ (pol _) (e s), ← (commute_e_pol s _).eq, tauProd_two]
        simp only [mul_assoc]
        rewrite [← mul_assoc (gProd (r + 1)), gProd_succ_mul_e r hr1 s]
        simp only [mul_assoc]
    _ = tauProd r * (ψ r * (ψ (r + 1) * (pol (X ⟨r + 1, hr1⟩ - X ⟨r, hrm⟩) *
          (e (cP m r • s) * (gProd r * pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩)))))) +
        tauProd r * (ψ r * (ψ (r + 1) * (pol ((X ⟨r + 1, hr1⟩ - X ⟨r, hrm⟩) ^ 2) *
          (ψ r * (e (cP m r • s) * (gProd r * pol (X ⟨r + 2, hr⟩ - X ⟨0, hm0⟩))))))) := by
        rewrite [gInt_mul_e_of_eq r hr1 ht01, hx, ← map_pow]
        simp only [add_mul, mul_add, mul_assoc]
    _ = _ := by
        refine congrArg₂ (· + ·) ?_ ?_
        · rewrite [tau_g_succ_of_eq hsym r hr1 hs1, tauProd_succ, e_mul_gProd_assoc r hrm,
            pol_mul_gProd_assoc hsym r hrm, hrdX, hcomm2.left_comm, hT1]
          simp only [mul_assoc]
        · rewrite [tau_g_succ_of_eq hsym r hr1 hs1, tauProd_succ, ← mul_assoc (pol _) (ψ r),
            ← hψd, mul_assoc, pol_e_comm_assoc, hbr, pol_mul_gProd_assoc hsym r hrm,
            map_pow, hrdX, e_mul_gProd_assoc r hrm, hcomm2.left_comm, hcomm1.left_comm,
            hT2]
          simp only [mul_assoc]

end hsym

end exact

/-! ### Kang–Kashiwara Theorem 4.15 -/

omit [DecidableEq I] in
theorem qbar_spec_rename {n : ℕ} (a b c : Fin n) (P : MvPolynomial (Fin 2) k) :
    (X a - X c) * rename ![a, b, c] (qbar P) = rename ![a, b] P - rename ![c, b] P := by
  have h := congrArg (rename ![a, b, c]) (qbar_spec P)
  rw [map_mul, map_sub, map_sub, rename_X, rename_X, rename_vec3_rename_vec2,
    rename_vec3_rename_vec2] at h
  simpa using h

section main

variable (a : I → Polynomial k)

variable (Q) in
/-- The factor of `F_r(𝐢)` at position `b`: `−1` if `i_b = i_1`, `Q_{i_1 i_b}(x_1, x_b)` otherwise
(and `1` at `b = 0`). -/
noncomputable def cycFac (s : Seq ν) (b : ℕ) : MvPolynomial (Fin m) k :=
  if h : b < m then
    if 1 ≤ b then
      if s.1 ⟨b, h⟩ = s.1 ⟨0, by omega⟩ then -1
      else rename ![⟨0, by omega⟩, ⟨b, h⟩] (Q (s.1 ⟨0, by omega⟩) (s.1 ⟨b, h⟩))
    else 1
  else 1

variable (Q) in
/-- `F_r(𝐢) = ∏_{b=1}^{r} (−1 if i_b = i_1, else Q_{i_1 i_b}(x_1, x_b))` (zero-indexed positions). -/
noncomputable def cycF (s : Seq ν) (r : ℕ) : MvPolynomial (Fin m) k :=
  ∏ b ∈ Finset.range (r + 1), cycFac Q s b

/-- `a_{i_1}(x_1)`. -/
noncomputable def cycA (h0 : 0 < m) (s : Seq ν) : MvPolynomial (Fin m) k :=
  Polynomial.aeval (X ⟨0, h0⟩) (a (s.1 ⟨0, h0⟩))

theorem cycF_zero (s : Seq ν) : cycF Q s 0 = 1 := by
  simp [cycF, cycFac]

theorem cycF_succ (s : Seq ν) (r : ℕ) : cycF Q s (r + 1) = cycF Q s r * cycFac Q s (r + 1) :=
  Finset.prod_range_succ _ _

theorem cycFac_of_eq (s : Seq ν) {b : ℕ} (hb : b < m) (h1 : 1 ≤ b)
    (hs : s.1 ⟨b, hb⟩ = s.1 ⟨0, by omega⟩) : cycFac Q s b = -1 := by
  simp [cycFac, hb, h1, hs]

theorem cycFac_of_ne (s : Seq ν) {b : ℕ} (hb : b < m) (h1 : 1 ≤ b)
    (hs : s.1 ⟨b, hb⟩ ≠ s.1 ⟨0, by omega⟩) :
    cycFac Q s b = rename ![⟨0, by omega⟩, ⟨b, hb⟩] (Q (s.1 ⟨0, by omega⟩) (s.1 ⟨b, hb⟩)) := by
  simp [cycFac, hb, h1, hs]

theorem cycF_congr {s s' : Seq ν} (r : ℕ) (h0 : ∀ hm : 0 < m, s'.1 ⟨0, hm⟩ = s.1 ⟨0, hm⟩)
    (h : ∀ b (hb : b < m), b ≤ r → s'.1 ⟨b, hb⟩ = s.1 ⟨b, hb⟩) : cycF Q s' r = cycF Q s r := by
  refine Finset.prod_congr rfl fun b hb => ?_
  have hbr : b ≤ r := by simp at hb; omega
  unfold cycFac
  by_cases hbm : b < m
  · simp only [hbm, ↓reduceDIte, h b hbm hbr, h0 (by omega)]
  · simp only [hbm, ↓reduceDIte]

theorem swapPol_cycF (s : Seq ν) (j : ℕ) (hj : j + 1 < m) (r : ℕ) (hr : r < j) :
    swapPol j hj (cycF Q s r) = cycF Q s r := by
  rw [cycF, map_prod]
  refine Finset.prod_congr rfl fun b hb => ?_
  have hbr : b ≤ r := by simp at hb; omega
  unfold cycFac
  by_cases hbm : b < m
  · simp only [hbm, ↓reduceDIte]
    split_ifs
    · simp
    · rw [swapPol, rename_rename_vec2, swap_apply_of_ne_of_ne (Fin.ne_of_val_ne (by dsimp only; omega))
        (Fin.ne_of_val_ne (by dsimp only; omega)), swap_apply_of_ne_of_ne (Fin.ne_of_val_ne (by dsimp only; omega))
        (Fin.ne_of_val_ne (by dsimp only; omega))]
    · simp
  · simp only [hbm, ↓reduceDIte, map_one]

omit [DecidableEq I] in
theorem swapPol_cycA (h0 : 0 < m) (s : Seq ν) (j : ℕ) (hj : j + 1 < m) (hj1 : 1 ≤ j) :
    swapPol j hj (cycA a h0 s) = cycA a h0 s := by
  rw [cycA, swapPol, rename_aeval_X, swap_apply_of_ne_of_ne (Fin.ne_of_val_ne (by dsimp only; omega))
    (Fin.ne_of_val_ne (by dsimp only; omega))]

/-- The local identity closing case (ii)(b) of KK's proof of Theorem 4.15:
`e(𝐢) g ψ_j + ψ_j e(𝐢) g ψ_j k e(𝐢) = −e(𝐢)` for `g = x_{j+1} − x_0`, `k = x_j − x_0`,
`i_j = i_{j+1}`, `j ≥ 1`. -/
theorem bracket_two (j : ℕ) (hj : j + 1 < m) (hj1 : 1 ≤ j) {s : Seq ν}
    (hs : s.1 ⟨j, by omega⟩ = s.1 ⟨j + 1, hj⟩) :
    (e s * pol (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩) * ψ j +
      ψ j * e s * pol (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩) * ψ j *
        pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * e s : A) = -e s := by
  have hne : (⟨j, by omega⟩ : Fin m) ≠ ⟨j + 1, hj⟩ := fun h => by simp [Fin.ext_iff] at h
  have h0j : (⟨0, by omega⟩ : Fin m) ≠ ⟨j, by omega⟩ := Fin.ne_of_val_ne (by dsimp only; omega)
  have h0j1 : (⟨0, by omega⟩ : Fin m) ≠ ⟨j + 1, hj⟩ := Fin.ne_of_val_ne (by dsimp only; omega)
  have hes : Commute (e s : A) (ψ j) := commute_e_ψ hj hs
  have hswk : swapPol j hj (X ⟨j, by omega⟩ - X ⟨0, by omega⟩ : MvPolynomial (Fin m) k) =
      X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩ := by
    rw [swapPol, map_sub, rename_X, rename_X, swap_apply_left, swap_apply_of_ne_of_ne h0j h0j1]
  have hswg : swapPol j hj (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩ : MvPolynomial (Fin m) k) =
      X ⟨j, by omega⟩ - X ⟨0, by omega⟩ := by
    rw [swapPol, map_sub, rename_X, rename_X, swap_apply_right, swap_apply_of_ne_of_ne h0j h0j1]
  have hddk : dd k m j (X ⟨j, by omega⟩ - X ⟨0, by omega⟩ : MvPolynomial (Fin m) k) = 1 := by
    rw [dd_of_lt hj, map_sub, ddiff_X_left hne, ddiff_X_of_ne hne h0j h0j1, sub_zero]
  have hddg : dd k m j (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩ : MvPolynomial (Fin m) k) = -1 := by
    rw [dd_of_lt hj, map_sub, ddiff_X_right hne, ddiff_X_of_ne hne h0j h0j1, sub_zero]
  -- `ψ k e = g ψ e + e`
  have hX : (ψ j * pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * e s : A) =
      pol (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩) * ψ j * e s + e s := by
    rw [ψ_mul_pol_mul_e_of_eq j hj hs, hswk, hddk, map_one, one_mul]
  -- `ψ g e = k ψ e − e`
  have hY : (ψ j * pol (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩) * e s : A) =
      pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * ψ j * e s - e s := by
    rw [ψ_mul_pol_mul_e_of_eq j hj hs, hswg, hddg, map_neg, map_one, neg_one_mul, ← sub_eq_add_neg]
  have hψψ : (ψ j * ψ j * e s : A) = 0 := ψ_mul_ψ_mul_e_same j hj hs
  -- `e` is absorbed
  have hXe : (e s * (ψ j * pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * e s) : A) =
      ψ j * pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * e s := by
    rw [← mul_assoc, ← mul_assoc, hes.eq, mul_assoc (ψ j), (commute_e_pol s _).eq, mul_assoc,
      mul_assoc, e_mul_self, ← mul_assoc]
  have hψX : (ψ j * (ψ j * pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * e s) : A) = 0 := by
    rw [mul_assoc (ψ j) (pol _) (e s), ← (commute_e_pol s _).eq, ← mul_assoc, ← mul_assoc, hψψ,
      zero_mul]
  have hA : (ψ j * e s * pol (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩) * ψ j *
      pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * e s : A) =
      (ψ j * pol (X ⟨j + 1, hj⟩ - X ⟨0, by omega⟩) * e s) *
        (ψ j * pol (X ⟨j, by omega⟩ - X ⟨0, by omega⟩) * e s) := by
    rw [mul_assoc (ψ j) (e s), (commute_e_pol s _).eq]
    simp only [mul_assoc]
  rw [hA, hY, sub_mul, mul_assoc _ (e s), hXe, mul_assoc (pol _) (ψ j), hψX, mul_zero, zero_sub,
    hX, (commute_e_pol s _).eq, mul_assoc (pol _) (e s) (ψ j), hes.eq, ← mul_assoc]
  abel

section hsym

variable (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b))
include hsym

/-- **Kang–Kashiwara, Theorem 4.15** (arXiv:1102.4677v4), in the form of an identity modulo the
left ideal `R(ν) a^Λ(x_2) R^1(β)`: for `r < card ν`,
`a_{i_1}(x_1) Ψ_r G_r e(𝐢) ≡ a_{i_1}(x_1) F_r(𝐢) e(𝐢)`. With `r = card ν − 1` this says that
`Q ∘ P` is right multiplication by `A_ν` on `K_1` (see the module docstring for the sign). Over any
commutative ring, for symmetric `Q`. -/
theorem cyc_tau_g (h1 : 1 < m) (r : ℕ) (hr : r < m) (s : Seq ν) :
    (pol (cycA a (by omega) s) * (tauProd r * gProd r) * e s : A) -
      pol (cycA a (by omega) s * cycF Q s r) * e s ∈ cycL1 a h1 := by
  have h0 : 0 < m := by omega
  induction r using Nat.strong_induction_on generalizing s with
  | _ r ih =>
  obtain _ | _ | r := r
  · -- `r = 0`
    simp only [tauProd, ψw, List.range_zero, List.map_nil, List.prod_nil, gProd_zero, mul_one,
      cycF_zero, sub_self]
    exact Submodule.zero_mem _
  · -- `r = 1`
    by_cases hs : s.1 ⟨0 + 1, h1⟩ = s.1 ⟨0, h0⟩
    · have hE := tau_g_succ_of_eq hsym 0 h1 hs
      have hne : (⟨0, h0⟩ : Fin m) ≠ ⟨0 + 1, h1⟩ := Fin.ne_of_val_ne (by dsimp only; omega)
      have hsw : swapPol 0 h1 (X ⟨0 + 1, h1⟩ - X ⟨0, h0⟩ : MvPolynomial (Fin m) k) =
          X ⟨0, h0⟩ - X ⟨0 + 1, h1⟩ := by
        rw [swapPol, map_sub, rename_X, rename_X, swap_apply_left, swap_apply_right]
      have hdd : dd k m 0 (X ⟨0 + 1, h1⟩ - X ⟨0, h0⟩ : MvPolynomial (Fin m) k) = -2 := by
        rw [dd_of_lt h1, map_sub, ddiff_X_right hne, ddiff_X_left hne]; ring
      have hF1 := ψ_mul_pol_mul_e_of_eq (Q := Q) 0 h1 hs.symm
        (X ⟨0 + 1, h1⟩ - X ⟨0, h0⟩ : MvPolynomial (Fin m) k)
      rw [hsw, hdd] at hF1
      have hβ : swapPol 0 h1 (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k)
          (a (s.1 ⟨0 + 1, h1⟩))) = cycA a h0 s := by
        rw [swapPol, rename_aeval_X, swap_apply_right, cycA, hs]
      have hF2 := ψ_mul_pol_mul_e_of_eq (Q := Q) 0 h1 hs.symm
        (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k) (a (s.1 ⟨0 + 1, h1⟩)))
      rw [hβ] at hF2
      have hF3 := pol_sub_mul_pol_dd (Q := Q) (ν := ν) 0 h1
        (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k) (a (s.1 ⟨0 + 1, h1⟩)))
      rw [hβ] at hF3
      have hF3' : ∀ y : A, pol (X ⟨0, h0⟩ - X ⟨0 + 1, h1⟩) * (pol (dd k m 0
          (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k) (a (s.1 ⟨0 + 1, h1⟩)))) * y) =
          (pol (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k) (a (s.1 ⟨0 + 1, h1⟩))) -
            pol (cycA a h0 s)) * y := fun y => by rw [← mul_assoc, hF3]
      have hβmem : (pol (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k)
          (a (s.1 ⟨0 + 1, h1⟩))) * e s : A) ∈ cycL1 a h1 := cyc_one_mul_e_mem a h1 s
      have hc : ∀ f g : MvPolynomial (Fin m) k, ∀ y : A, pol f * (pol g * y) = pol g * (pol f * y) :=
        fun f g y => by rw [← mul_assoc, ← mul_assoc, ← map_mul, mul_comm, map_mul]
      have key : (pol (cycA a h0 s) * (tauProd (0 + 1) * gProd (0 + 1)) * e s : A) -
          pol (cycA a h0 s * cycF Q s (0 + 1)) * e s =
          pol (X ⟨0, h0⟩ - X ⟨0 + 1, h1⟩) * ψ 0 *
            (pol (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k)
              (a (s.1 ⟨0 + 1, h1⟩))) * e s) -
          pol (Polynomial.aeval (X ⟨0 + 1, h1⟩ : MvPolynomial (Fin m) k)
            (a (s.1 ⟨0 + 1, h1⟩))) * e s := by
        rw [mul_assoc (pol _) (_ * _) (e s), hE, tauProd_succ, tauProd_zero, one_mul, gProd_zero,
          mul_one, hF1, cycF_succ, cycF_zero, one_mul, cycFac_of_eq s h1 le_rfl hs]
        conv_rhs => rw [mul_assoc (pol _) (ψ 0), ← mul_assoc (ψ 0), hF2, mul_add,
          hF3']
        rw [mul_neg, mul_one, map_neg, map_neg,
          show (pol (2 : MvPolynomial (Fin m) k) : A) = 2 from map_ofNat _ _]
        simp only [mul_add, mul_assoc, sub_mul]
        rw [hc (X (⟨0, h0⟩ : Fin m) - X (⟨0 + 1, h1⟩ : Fin m)) (cycA a h0 s)]
        noncomm_ring
      rw [key]
      exact Submodule.sub_mem _ (left_mul_mem_cycL1 a _ hβmem) hβmem
    · have hE := tau_g_succ_of_ne hsym 0 h1 hs
      have hzero : (pol (cycA a h0 s) * (tauProd (0 + 1) * gProd (0 + 1)) * e s : A) -
          pol (cycA a h0 s * cycF Q s (0 + 1)) * e s = 0 := by
        rw [mul_assoc (pol _) (_ * _) (e s), hE, tauProd_zero, gProd_zero, one_mul, one_mul,
          cycF_succ, cycF_zero, one_mul, cycFac_of_ne s h1 le_rfl hs, map_mul, mul_assoc,
          (commute_e_pol s _).eq, sub_self]
      rw [hzero]
      exact Submodule.zero_mem _
  · -- `r + 2`
    have hr2 : r + 2 < m := hr
    have hrm : r < m := by omega
    have hr1 : r + 1 < m := by omega
    show (pol (cycA a h0 s) * (tauProd (r + 2) * gProd (r + 2)) * e s : A) -
      pol (cycA a h0 s * cycF Q s (r + 2)) * e s ∈ cycL1 a h1
    have h1r : 1 ≤ r + 1 := Nat.le_add_left 1 r
    have h2r : 1 ≤ r + 1 + 1 := Nat.le_add_left 1 (r + 1)
    have hr_lt : r < r + 1 := Nat.lt_succ_self r
    have hαψ : Commute (pol (cycA a h0 s) : A) (ψ (r + 1)) :=
      (ψ_mul_pol_of_symm (r + 1) hr2 (swapPol_cycA a h0 s (r + 1) hr2 h1r)).symm
    by_cases hs2 : s.1 ⟨r + 2, hr2⟩ = s.1 ⟨0, h0⟩
    · by_cases hs1 : s.1 ⟨r + 1, hr1⟩ = s.1 ⟨0, h0⟩
      · -- case (ii)(b)
        have hT := tau_g_two_of_eq hsym r hr2 hs2 hs1
        have hD := ih (r + 1) (by omega) hr1 s
        have hb : (e s * pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) * ψ (r + 1) +
            ψ (r + 1) * e s * pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) * ψ (r + 1) *
              pol (X ⟨r + 1, hr1⟩ - X ⟨0, h0⟩) * e s : A) = -e s :=
          bracket_two (Q := Q) (r + 1) hr2 h1r (hs1.trans hs2.symm)
        have hF2 : cycF Q s (r + 2) = cycF Q s (r + 1) * -1 := by
          rw [show r + 2 = r + 1 + 1 from rfl, cycF_succ, cycFac_of_eq s hr h2r hs2]
        have hF' : cycF Q s (r + 1) = cycF Q s r * -1 := by
          rw [cycF_succ, cycFac_of_eq s hr1 h1r hs1]
        have hFψ : Commute (ψ (r + 1) : A) (pol (cycA a h0 s * cycF Q s (r + 1))) := by
          refine ψ_mul_pol_of_symm (r + 1) hr2 ?_
          rw [hF', map_mul, map_mul, swapPol_cycA a h0 s (r + 1) hr2 h1r,
            swapPol_cycF s (r + 1) hr2 r hr_lt, map_neg, map_one]
        have hL : (pol (cycA a h0 s) * (tauProd (r + 2) * gProd (r + 2)) * e s : A) =
            (pol (cycA a h0 s) * (tauProd (r + 1) * gProd (r + 1)) * e s) *
              (pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) * ψ (r + 1)) +
            ψ (r + 1) * ((pol (cycA a h0 s) * (tauProd (r + 1) * gProd (r + 1)) * e s) *
              (pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) *
                (ψ (r + 1) * (pol (X ⟨r + 1, hr1⟩ - X ⟨0, h0⟩) * e s)))) := by
          rw [mul_assoc (pol _) (_ * _) (e s), hT, mul_add]
          refine congrArg₂ (· + ·) ?_ ?_
          · simp only [mul_assoc]
          · simp only [mul_assoc]; rw [hαψ.left_comm]
        have hR : (pol (cycA a h0 s * cycF Q s (r + 2)) * e s : A) =
            (pol (cycA a h0 s * cycF Q s (r + 1)) * e s) *
              (pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) * ψ (r + 1)) +
            ψ (r + 1) * ((pol (cycA a h0 s * cycF Q s (r + 1)) * e s) *
              (pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) *
                (ψ (r + 1) * (pol (X ⟨r + 1, hr1⟩ - X ⟨0, h0⟩) * e s)))) := by
          rw [hF2, ← mul_assoc, mul_neg, mul_one, map_neg, neg_mul, ← mul_neg, ← hb, mul_add]
          refine congrArg₂ (· + ·) ?_ ?_
          · simp only [mul_assoc]
          · simp only [mul_assoc]; rw [hFψ.left_comm]
        have key : (pol (cycA a h0 s) * (tauProd (r + 2) * gProd (r + 2)) * e s : A) -
            pol (cycA a h0 s * cycF Q s (r + 2)) * e s =
            (pol (cycA a h0 s) * (tauProd (r + 1) * gProd (r + 1)) * e s -
                pol (cycA a h0 s * cycF Q s (r + 1)) * e s) *
              (pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) * ψ (r + 1)) +
            ψ (r + 1) * ((pol (cycA a h0 s) * (tauProd (r + 1) * gProd (r + 1)) * e s -
                pol (cycA a h0 s * cycF Q s (r + 1)) * e s) *
              (pol (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩) *
                (ψ (r + 1) * (pol (X ⟨r + 1, hr1⟩ - X ⟨0, h0⟩) * e s)))) := by
          rw [hL, hR]; noncomm_ring
        rw [key]
        refine Submodule.add_mem _ (mul_mem_cycL1 a hD ?_)
          (left_mul_mem_cycL1 a _ (mul_mem_cycL1 a hD ?_))
        · exact Subalgebra.mul_mem _ (pol_mem_subR1 _) (ψ_mem_subR1 h1r)
        · exact Subalgebra.mul_mem _ (pol_mem_subR1 _) (Subalgebra.mul_mem _ (ψ_mem_subR1 h1r)
            (Subalgebra.mul_mem _ (pol_mem_subR1 _) (e_mem_subR1 _)))
      · -- case (ii)(a)
        have hT := tau_g_two_of_ne hsym r hr2 hs2 hs1
        have hs'0 : (sadj m (r + 1) • s).1 ⟨0, h0⟩ = s.1 ⟨0, h0⟩ := by
          rw [sadj_smul_apply, sadj_apply_of_ne _ (by simp) (by simp)]
        have hα' : cycA a h0 (sadj m (r + 1) • s) = cycA a h0 s := by rw [cycA, cycA, hs'0]
        have hD1 := ih (r + 1) (by omega) hr1 (sadj m (r + 1) • s)
        rw [hα'] at hD1
        have hD0 := ih r (by omega) hrm s
        have hF'' : cycF Q (sadj m (r + 1) • s) (r + 1) = cycF Q s r * -1 := by
          rw [cycF_succ, cycF_congr r (fun _ => hs'0) ?_, cycFac_of_eq _ hr1 h1r ?_]
          · rw [sadj_smul_apply, sadj_smul_apply, sadj_apply_left hr2,
              sadj_apply_of_ne _ (by simp) (by simp)]
            exact hs2
          · intro b hb hbr
            rw [sadj_smul_apply, sadj_apply_of_ne _ (Nat.ne_of_lt (Nat.lt_succ_of_le hbr))
              (Nat.ne_of_lt (Nat.lt_succ_of_lt (Nat.lt_succ_of_le hbr)))]
        have hF2 : cycF Q s (r + 2) = cycF Q s r * cycFac Q s (r + 1) * -1 := by
          rw [show r + 2 = r + 1 + 1 from rfl, cycF_succ, cycF_succ, cycFac_of_eq s hr h2r hs2]
        have hfac1 : cycFac Q s (r + 1) =
            rename ![⟨0, h0⟩, ⟨r + 1, hr1⟩] (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 1, hr1⟩)) :=
          cycFac_of_ne s hr1 h1r hs1
        have hF''ψ : Commute (ψ (r + 1) : A)
            (pol (cycA a h0 s * cycF Q (sadj m (r + 1) • s) (r + 1))) := by
          refine ψ_mul_pol_of_symm (r + 1) hr2 ?_
          rw [hF'', map_mul, map_mul, swapPol_cycA a h0 s (r + 1) hr2 h1r,
            swapPol_cycF s (r + 1) hr2 r hr_lt, map_neg, map_one]
        have hs12 : s.1 ⟨r + 1, hr1⟩ ≠ s.1 ⟨r + 2, hr2⟩ := by rw [hs2]; exact hs1
        have hψψ : (ψ (r + 1) * ψ (r + 1) * e s : A) =
            pol (rename ![⟨r + 1, hr1⟩, ⟨r + 2, hr2⟩] (Q (s.1 ⟨r + 1, hr1⟩) (s.1 ⟨r + 2, hr2⟩))) *
              e s := by
          rw [ψ_sq (r + 1) hr2 s, ite_eq_right_of_eq_false _ _ (eq_false hs12), ncEval_x₂]
        have hpoly : cycA a h0 s * cycF Q s (r + 2) =
            cycA a h0 s * cycF Q (sadj m (r + 1) • s) (r + 1) *
              rename ![⟨r + 1, hr1⟩, ⟨r + 2, hr2⟩] (Q (s.1 ⟨r + 1, hr1⟩) (s.1 ⟨r + 2, hr2⟩)) +
            cycA a h0 s * cycF Q s r *
              (rename ![⟨0, h0⟩, ⟨r + 1, hr1⟩, ⟨r + 2, hr2⟩]
                (qbar (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 1, hr1⟩))) * (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩)) := by
          have hq := qbar_spec_rename (⟨0, h0⟩ : Fin m) ⟨r + 1, hr1⟩ ⟨r + 2, hr2⟩
            (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 1, hr1⟩))
          rw [hF'', hF2, hfac1, hs2, hsym _ _ (Ne.symm hs1), rename_vec2_rename_swap]
          linear_combination (cycA a h0 s * cycF Q s r) * hq
        have hL : (pol (cycA a h0 s) * (tauProd (r + 2) * gProd (r + 2)) * e s : A) =
            ψ (r + 1) * ((pol (cycA a h0 s) * (tauProd (r + 1) * gProd (r + 1)) *
              e (sadj m (r + 1) • s)) * ψ (r + 1)) +
            (pol (cycA a h0 s) * (tauProd r * gProd r) * e s) *
              pol (rename ![⟨0, h0⟩, ⟨r + 1, hr1⟩, ⟨r + 2, hr2⟩]
                (qbar (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 1, hr1⟩))) * (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩)) := by
          rw [mul_assoc (pol _) (_ * _) (e s), hT, mul_add]
          refine congrArg₂ (· + ·) ?_ ?_
          · simp only [mul_assoc]; rw [hαψ.left_comm]
          · simp only [mul_assoc]
        have hR : (pol (cycA a h0 s * cycF Q s (r + 2)) * e s : A) =
            ψ (r + 1) * ((pol (cycA a h0 s * cycF Q (sadj m (r + 1) • s) (r + 1)) *
              e (sadj m (r + 1) • s)) * ψ (r + 1)) +
            (pol (cycA a h0 s * cycF Q s r) * e s) *
              pol (rename ![⟨0, h0⟩, ⟨r + 1, hr1⟩, ⟨r + 2, hr2⟩]
                (qbar (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 1, hr1⟩))) * (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩)) := by
          rw [hpoly, map_add, add_mul]
          refine congrArg₂ (· + ·) ?_ ?_
          · rw [mul_assoc (pol _) (e _) (ψ _), ← ψ_mul_e, hF''ψ.left_comm, ← mul_assoc (ψ _) (ψ _),
              hψψ, map_mul, mul_assoc]
          · rw [map_mul, mul_assoc, ← (commute_e_pol s _).eq, ← mul_assoc]
        have key : (pol (cycA a h0 s) * (tauProd (r + 2) * gProd (r + 2)) * e s : A) -
            pol (cycA a h0 s * cycF Q s (r + 2)) * e s =
            ψ (r + 1) * ((pol (cycA a h0 s) * (tauProd (r + 1) * gProd (r + 1)) *
                e (sadj m (r + 1) • s) -
              pol (cycA a h0 s * cycF Q (sadj m (r + 1) • s) (r + 1)) * e (sadj m (r + 1) • s)) *
                ψ (r + 1)) +
            (pol (cycA a h0 s) * (tauProd r * gProd r) * e s - pol (cycA a h0 s * cycF Q s r) * e s) *
              pol (rename ![⟨0, h0⟩, ⟨r + 1, hr1⟩, ⟨r + 2, hr2⟩]
                (qbar (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 1, hr1⟩))) * (X ⟨r + 2, hr2⟩ - X ⟨0, h0⟩)) := by
          rw [hL, hR]; noncomm_ring
        rw [key]
        exact Submodule.add_mem _ (left_mul_mem_cycL1 a _ (mul_mem_cycL1 a hD1 (ψ_mem_subR1 h1r)))
          (mul_mem_cycL1 a hD0 (pol_mem_subR1 _))
    · -- case (i)
      have hT := tau_g_succ_of_ne_two hsym r hr2 hs2
      have hD := ih (r + 1) (by omega) hr1 s
      have hL : (pol (cycA a h0 s) * (tauProd (r + 2) * gProd (r + 2)) * e s : A) =
          (pol (cycA a h0 s) * (tauProd (r + 1) * gProd (r + 1)) * e s) *
            pol (rename ![⟨0, h0⟩, ⟨r + 2, hr2⟩] (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 2, hr2⟩))) := by
        rw [mul_assoc (pol _) (_ * _) (e s), hT]; simp only [mul_assoc]
      have hR : (pol (cycA a h0 s * cycF Q s (r + 2)) * e s : A) =
          (pol (cycA a h0 s * cycF Q s (r + 1)) * e s) *
            pol (rename ![⟨0, h0⟩, ⟨r + 2, hr2⟩] (Q (s.1 ⟨0, h0⟩) (s.1 ⟨r + 2, hr2⟩))) := by
        rw [cycF_succ, cycFac_of_ne s hr2 (by omega) hs2, ← mul_assoc, map_mul, mul_assoc,
          ← (commute_e_pol s _).eq, ← mul_assoc]
      rw [hL, hR, ← sub_mul]
      exact mul_mem_cycL1 a hD (pol_mem_subR1 _)

end hsym

end main

end KLRAlgebra

end Categorification.KLR
