/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.CyclotomicExact

/-!
# Kang–Kashiwara's maps `P : K_1 → K_0` and `Q : K_0 → K_1`

S.-J. Kang, M. Kashiwara, *Categorification of highest weight modules via
Khovanov–Lauda–Rouquier algebras*, arXiv:1102.4677v4, §4.2 (4.5)–(4.11): Lemma 4.10 and
Propositions 4.13, 4.14, and the module form of Theorem 4.15.

Fix a weight `ν` with `m = n + 1` strands, a colour `i` and cyclotomic data `a`. Write `β` for the
weight `ν − α_i` of the first `n` (resp. last `n`) strands. KK's bimodules are
`K_0 = R(ν) e(β, i) / R(ν) a^Λ(x_1) R(β) e(β, i)` and
`K_1 = R(ν) e(i, β) / R(ν) a^Λ(x_2) R^1(β) e(i, β)`; here they are the quotients
`R(ν) / (L + R(ν)(1 − e))` of the regular left module by the left ideals `cycL0 a + R(ν)(1 − e(β, i))`
and `cycL1 a + R(ν)(1 − e(i, β))` (`KZero`, `KOne`), which are canonically `R(ν) e / L e`.

* `pMap` (KK's `P`, Lemma 4.10 and (4.6)): right multiplication by
  `a^Λ(x_1) ψ_0 ⋯ ψ_{n-1} e(β, i)`; well defined because `R(ν) a^Λ(x_2) R^1(β)` is carried into
  `R(ν) a^Λ(x_1) R(β)` (`mul_tauW_mem`).
* `qMap` (KK's `Q`, Props. 4.13, 4.14): right multiplication by `e(β, i) g_{n-1} ⋯ g_0`; well
  defined by Lemma 4.12 (`gProd` intertwines `R(β)` with `R^1(β)` exactly).
* `qMap_comp_pMap` (KK Thm. 4.15): `Q ∘ P` is right multiplication by
  `∑_{i_1 = i} a_i(x_1) F_n(𝐢) e(𝐢)` (see `Categorification.KLR.CyclotomicExact` for `F_n` and the sign).

Everything holds over any commutative ring, for symmetric `Q`.
-/

namespace Categorification.KLR

open MvPolynomial TypeA Equiv PolyRep NilHecke

variable {I : Type*} [DecidableEq I] {k : Type*} [CommRing k]

namespace KLRAlgebra

variable {Q : I → I → MvPolynomial (Fin 2) k} {ν : Multiset I}

local notation "m" => Multiset.card ν
local notation "A" => KLRAlgebra k Q ν

/-! ### Idempotent sums -/

variable (ν) in
/-- The subalgebra generated by the idempotents. -/
noncomputable def eSub : Subalgebra k A := Algebra.adjoin k (Set.range e)

theorem e_mem_eSub (t : Seq ν) : (e t : A) ∈ eSub (k := k) (Q := Q) ν :=
  Algebra.subset_adjoin ⟨t, rfl⟩

/-- Idempotent sums move past a crossing. -/
theorem exists_eSub_mul_ψ {δ : A} (hδ : δ ∈ eSub (k := k) (Q := Q) ν) (j : ℕ) :
    ∃ δ' ∈ eSub (k := k) (Q := Q) ν, δ * ψ j = ψ j * δ' := by
  induction hδ using Algebra.adjoin_induction with
  | mem y hy =>
    obtain ⟨t, rfl⟩ := hy
    refine ⟨e (sadj m j • t), e_mem_eSub _, ?_⟩
    rw [ψ_mul_e, sadj_smul_smul]
  | algebraMap c => exact ⟨algebraMap k A c, Subalgebra.algebraMap_mem _ c, Algebra.commutes c _⟩
  | add y z _ _ hy hz =>
    obtain ⟨y', hy', hy⟩ := hy
    obtain ⟨z', hz', hz⟩ := hz
    exact ⟨y' + z', Subalgebra.add_mem _ hy' hz', by rw [add_mul, mul_add, hy, hz]⟩
  | mul y z _ _ hy hz =>
    obtain ⟨y', hy', hy⟩ := hy
    obtain ⟨z', hz', hz⟩ := hz
    exact ⟨y' * z', Subalgebra.mul_mem _ hy' hz', by rw [mul_assoc, hz, ← mul_assoc, hy, mul_assoc]⟩

/-- The idempotents with equal labels at `j, j + 1`. -/
noncomputable def eqIdem (j : ℕ) (h : j + 1 < m) : A :=
  ∑ t : Seq ν, if t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩ then e t else 0

theorem eqIdem_mem (j : ℕ) (h : j + 1 < m) : (eqIdem j h : A) ∈ eSub (k := k) (Q := Q) ν :=
  Subalgebra.sum_mem _ fun t _ => by
    split_ifs
    · exact e_mem_eSub t
    · exact Subalgebra.zero_mem _

/-- Moving a polynomial to the right past a crossing:
`f ψ_j = ψ_j (s_j f) − ∂_j(s_j f) [i_j = i_{j+1}]`. -/
theorem pol_mul_ψ (j : ℕ) (h : j + 1 < m) (f : MvPolynomial (Fin m) k) :
    (pol f * ψ j : A) = ψ j * pol (swapPol j h f) - pol (dd k m j (swapPol j h f)) * eqIdem j h := by
  have hss : swapPol j h (swapPol j h f) = f := by
    simp only [swapPol, rename_rename]
    rw [show (⇑(swap (⟨j, by omega⟩ : Fin m) ⟨j + 1, h⟩) ∘ ⇑(swap (⟨j, by omega⟩ : Fin m)
      ⟨j + 1, h⟩)) = id from funext fun b => swap_apply_self _ _ b, rename_id_apply]
  apply ext_e
  intro t
  have := ψ_mul_pol_mul_e (Q := Q) j h t (swapPol j h f)
  rw [hss] at this
  have he : (eqIdem j h * e t : A) =
      if t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩ then e t else 0 := by
    rw [eqIdem, Finset.sum_mul, Finset.sum_eq_single t]
    · split_ifs <;> simp [e_mul_self]
    · intro u _ hu; split_ifs <;> simp [e_mul_e, hu]
    · simp
  rw [sub_mul, mul_assoc (pol _) (eqIdem _ _), he, this]
  split_ifs <;> simp only [mul_zero, sub_zero, add_zero, add_sub_cancel_right]

/-! ### The left ideal `R(ν) a^Λ(x_1) R(β)` -/

section cyc

variable (a : I → Polynomial k)

variable (ν) in
/-- The subalgebra generated by all dots, all idempotents and the crossings `ψ_j`, `j + 2 < m`
(the image of `R(β) ⊗ k[x_m]`, summed over the colour of the last strand). -/
noncomputable def subR0 : Subalgebra k A :=
  Algebra.adjoin k (Set.range x ∪ Set.range e ∪ {y | ∃ j, j + 2 < m ∧ y = ψ j})

theorem x_mem_subR0 (b : Fin m) : (x b : A) ∈ subR0 (k := k) (Q := Q) ν :=
  Algebra.subset_adjoin (Or.inl (Or.inl ⟨b, rfl⟩))

theorem e_mem_subR0 (t : Seq ν) : (e t : A) ∈ subR0 (k := k) (Q := Q) ν :=
  Algebra.subset_adjoin (Or.inl (Or.inr ⟨t, rfl⟩))

theorem ψ_mem_subR0 {j : ℕ} (hj : j + 2 < m) : (ψ j : A) ∈ subR0 (k := k) (Q := Q) ν :=
  Algebra.subset_adjoin (Or.inr ⟨j, hj, rfl⟩)

theorem pol_mem_subR0 (f : MvPolynomial (Fin m) k) : (pol f : A) ∈ subR0 (k := k) (Q := Q) ν :=
  (Algebra.adjoin_mono (fun _ hy => Or.inl (Or.inl hy)) : dotSubalgebra ≤ _)
    (pol_mem_dotSubalgebra f)

theorem eSub_le_subR0 : eSub (k := k) (Q := Q) ν ≤ subR0 ν :=
  Algebra.adjoin_mono fun _ hy => Or.inl (Or.inr hy)

theorem tauProd_mem_subR0 (p : ℕ) (hp : p + 1 < m) : (tauProd p : A) ∈ subR0 (k := k) (Q := Q) ν := by
  induction p with
  | zero => rw [tauProd_zero]; exact Subalgebra.one_mem _
  | succ p ih =>
    rw [tauProd_succ]; exact Subalgebra.mul_mem _ (ih (by omega)) (ψ_mem_subR0 (by omega))

/-- **The left ideal `R(ν) a^Λ(x_1) R(β)`**, the denominator of KK's `K_0` (summed over the colour
of the last strand). -/
noncomputable def cycL0 (h0 : 0 < m) : Submodule A A :=
  Submodule.span A {z | ∃ w ∈ subR0 (k := k) (Q := Q) ν, z = cycAt a ⟨0, h0⟩ * w}

theorem mul_mem_cycL0 {h0 : 0 < m} {z w : A} (hz : z ∈ cycL0 a h0)
    (hw : w ∈ subR0 (k := k) (Q := Q) ν) : z * w ∈ cycL0 a h0 := by
  induction hz using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w', hw', rfl⟩ := hy
    exact Submodule.subset_span ⟨w' * w, Subalgebra.mul_mem _ hw' hw, by rw [mul_assoc]⟩
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add y z _ _ hy hz => rw [add_mul]; exact Submodule.add_mem _ hy hz
  | smul r y _ hy => rw [smul_eq_mul, mul_assoc]; exact Submodule.smul_mem _ r hy

theorem cycAt_mul_mem_cycL0 (h0 : 0 < m) {w : A} (hw : w ∈ subR0 (k := k) (Q := Q) ν) :
    cycAt a ⟨0, h0⟩ * w ∈ cycL0 a h0 :=
  Submodule.subset_span ⟨w, hw, rfl⟩

/-- `a^Λ(x_p)` commutes with the crossings away from `p`. -/
theorem cycAt_mul_ψ (p : Fin m) (j : ℕ) (hj : p.val ≠ j ∧ p.val ≠ j + 1) :
    (cycAt a p * ψ j : A) = ψ j * cycAt a p := by
  by_cases h : j + 1 < m
  · have hsym : ∀ t : Seq ν, swapPol j h (Polynomial.aeval (X p) (a (t.1 p))) =
        Polynomial.aeval (X p) (a (t.1 p)) := fun t => by
      simp only [swapPol]
      rw [rename_aeval_X, swap_apply_of_ne_of_ne (fun e => hj.1 (by rw [e]))
        (fun e => hj.2 (by rw [e]))]
    apply ext_e
    intro s
    have hl : (cycAt a p * ψ j * e s : A) =
        pol (Polynomial.aeval (X p) (a (s.1 p))) * e (sadj m j • s) * ψ j := by
      rw [mul_assoc, ψ_mul_e, ← mul_assoc, cycAt_mul_e, sadj_smul_apply,
        sadj_apply_of_ne _ hj.1 hj.2]
    have hr : (ψ j * cycAt a p * e s : A) =
        pol (Polynomial.aeval (X p) (a (s.1 p))) * e (sadj m j • s) * ψ j := by
      rw [mul_assoc, cycAt_mul_e, ← mul_assoc, ψ_mul_pol_of_symm j h (hsym _), mul_assoc,
        ψ_mul_e, ← mul_assoc]
    rw [hl, hr]
  · rw [ψ_eq_zero j (by omega), mul_zero, zero_mul]

theorem cycAt_mul_x (p b : Fin m) : (cycAt a p * x b : A) = x b * cycAt a p := by
  rw [cycAt, Finset.sum_mul, Finset.mul_sum]
  refine Finset.sum_congr rfl fun t _ => ?_
  rw [mul_assoc, ← x_mul_e, ← mul_assoc, ← pol_X, ← map_mul, mul_comm, map_mul, mul_assoc]

theorem cycAt_mul_e' (p : Fin m) (s : Seq ν) : (cycAt a p * e s : A) = e s * cycAt a p := by
  rw [cycAt_mul_e, cycAt, Finset.mul_sum, Finset.sum_eq_single s]
  · rw [← mul_assoc, (commute_e_pol s _).eq, mul_assoc, e_mul_self]
  · intro t _ ht
    rw [← mul_assoc, (commute_e_pol s _).eq, mul_assoc, e_mul_e]; simp [Ne.symm ht]
  · simp

/-- `a^Λ(x_1)` commutes with `R^1(β)` (and `k[x_1]`). -/
theorem cycAt_zero_comm {h0 : 0 < m} {u : A} (hu : u ∈ subR1 (k := k) (Q := Q) ν) :
    cycAt a ⟨0, h0⟩ * u = u * cycAt a ⟨0, h0⟩ := by
  induction hu using Algebra.adjoin_induction with
  | mem y hy =>
    rcases hy with (⟨b, rfl⟩ | ⟨t, rfl⟩) | ⟨j, hj, rfl⟩
    · exact cycAt_mul_x a _ b
    · exact cycAt_mul_e' a _ t
    · exact cycAt_mul_ψ a _ j ⟨by simp; omega, by simp⟩
  | algebraMap c => exact (Algebra.commutes c _).symm
  | add y z _ _ hy hz => rw [mul_add, add_mul, hy, hz]
  | mul y z _ _ hy hz => rw [← mul_assoc, hy, mul_assoc, hz, mul_assoc]

theorem left_mul_mem_cycL0_of_subR1 {h0 : 0 < m} {u y : A}
    (hu : u ∈ subR1 (k := k) (Q := Q) ν) (hy : cycAt a ⟨0, h0⟩ * y ∈ cycL0 a h0) :
    cycAt a ⟨0, h0⟩ * (u * y) ∈ cycL0 a h0 := by
  rw [← mul_assoc, cycAt_zero_comm a hu, mul_assoc]
  exact Submodule.smul_mem _ u hy

end cyc

/-! ### Crossing products -/

theorem tauProd_eq (p n : ℕ) (hp : p ≤ n) :
    (tauProd n : A) = tauProd p * ψw (List.range' p (n - p)) := by
  have h := @List.range'_append_1 0 p (n - p)
  simp only [Nat.zero_add, Nat.add_sub_cancel' hp] at h
  rw [tauProd, tauProd, List.range_eq_range', List.range_eq_range', ← ψw_append, h]

theorem e_mul_tauProd (r : ℕ) (t : Seq ν) : (e t * tauProd r : A) = tauProd r * e (cP m r • t) := by
  induction r generalizing t with
  | zero => simp [cP_zero]
  | succ r ih =>
    have h1 : (e (cP m r • t) * ψ r : A) = ψ r * e (sadj m r • cP m r • t) := by
      rw [ψ_mul_e, sadj_smul_smul]
    rw [tauProd_succ, ← mul_assoc, ih, mul_assoc, h1, ← mul_assoc, cP_succ, mul_smul]

theorem x_mul_ψw (b : Fin m) (ρ : List ℕ) (hρ : ∀ j ∈ ρ, b.val ≠ j ∧ b.val ≠ j + 1) :
    (x b * ψw ρ : A) = ψw ρ * x b := by
  induction ρ with
  | nil => simp [ψw]
  | cons j ρ ih =>
    rw [ψw_cons, ← mul_assoc, x_mul_ψ b j (hρ j (by simp)).1 (hρ j (by simp)).2, mul_assoc,
      ih (fun l hl => hρ l (by simp [hl])), mul_assoc]

theorem x_mul_tauProd (b : Fin m) (p : ℕ) (hp : p + 1 ≤ b.val) :
    (x b * tauProd p : A) = tauProd p * x b :=
  x_mul_ψw b _ fun j hj => by simp at hj; omega

theorem ψ_mul_ψw (j : ℕ) (ρ : List ℕ) (hρ : ∀ l ∈ ρ, l + 2 ≤ j ∨ j + 2 ≤ l) :
    (ψ j * ψw ρ : A) = ψw ρ * ψ j := by
  induction ρ with
  | nil => simp [ψw]
  | cons l ρ ih =>
    have hc : (ψ j * ψ l : A) = ψ l * ψ j := by
      rcases hρ l (by simp) with h | h
      · exact (ψ_mul_ψ l j (by omega)).symm
      · exact ψ_mul_ψ j l (by omega)
    rw [ψw_cons, ← mul_assoc, hc, mul_assoc, ih (fun l' hl' => hρ l' (by simp [hl'])), mul_assoc]

/-- `ψ_j x_j − x_{j+1} ψ_j` is the sum of the idempotents with equal labels at `j, j + 1`. -/
theorem x_succ_mul_ψ (j : ℕ) (h : j + 1 < m) :
    (x ⟨j + 1, h⟩ * ψ j : A) = ψ j * x ⟨j, by omega⟩ - eqIdem j h := by
  apply ext_e
  intro t
  have := dot_cross_right (Q := Q) j h t
  have he : (eqIdem j h * e t : A) = if t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩ then e t else 0 := by
    rw [eqIdem, Finset.sum_mul, Finset.sum_eq_single t]
    · split_ifs <;> simp [e_mul_self]
    · intro u _ hu; split_ifs <;> simp [e_mul_e, hu]
    · simp
  rw [sub_mul, he, ← this, sub_mul, sub_sub_cancel]

theorem x_mul_ψ_self (j : ℕ) (h : j + 1 < m) :
    (x ⟨j, by omega⟩ * ψ j : A) = ψ j * x ⟨j + 1, h⟩ + eqIdem j h := by
  apply ext_e
  intro t
  have := dot_cross_left (Q := Q) j h t
  have he : (eqIdem j h * e t : A) = if t.1 ⟨j, by omega⟩ = t.1 ⟨j + 1, h⟩ then e t else 0 := by
    rw [eqIdem, Finset.sum_mul, Finset.sum_eq_single t]
    · split_ifs <;> simp [e_mul_self]
    · intro u _ hu; split_ifs <;> simp [e_mul_e, hu]
    · simp
  rw [add_mul, he, ← this, sub_mul]
  abel

/-! ### KK Lemma 4.10: right multiplication by `a^Λ(x_1) ψ_0 ⋯ ψ_{n-1}` -/

section lemma410

variable (a : I → Polynomial k)

/-- The key estimate behind KK Lemma 4.10: elements `a^Λ(x_1) Ψ_p f δ ψ_ρ` with all letters of
`ρ` at least `p + 1` lie in `R(ν) a^Λ(x_1) R(β)`. -/
theorem cycAt_tau_pol_word_mem (h0 : 0 < m) (p : ℕ) (hp : p + 2 ≤ m) :
    ∀ (ρ : List ℕ), (∀ r ∈ ρ, p + 1 ≤ r ∧ r + 1 < m) →
      ∀ (f : MvPolynomial (Fin m) k) (δ : A), δ ∈ eSub (k := k) (Q := Q) ν →
        cycAt a ⟨0, h0⟩ * (tauProd p * pol f * δ * ψw ρ) ∈ cycL0 a h0 := by
  intro ρ
  induction ρ with
  | nil =>
    intro _ f δ hδ
    rw [ψw, List.map_nil, List.prod_nil, mul_one]
    exact cycAt_mul_mem_cycL0 a h0 (Subalgebra.mul_mem _ (Subalgebra.mul_mem _
      (tauProd_mem_subR0 p (by omega)) (pol_mem_subR0 f)) (eSub_le_subR0 hδ))
  | cons r ρ ih =>
    intro hρ f δ hδ
    obtain ⟨hr1, hr2⟩ := hρ r (by simp)
    have hρ' : ∀ r' ∈ ρ, p + 1 ≤ r' ∧ r' + 1 < m := fun r' h => hρ r' (by simp [h])
    obtain ⟨δ', hδ', hδψ⟩ := exists_eSub_mul_ψ hδ r
    have key : (tauProd p * pol f * δ * ψw (r :: ρ) : A) =
        ψ r * (tauProd p * pol (swapPol r hr2 f) * δ' * ψw ρ) -
          tauProd p * pol (dd k m r (swapPol r hr2 f)) * (eqIdem r hr2 * δ') * ψw ρ := by
      rw [ψw_cons, ← mul_assoc, mul_assoc _ δ, hδψ, ← mul_assoc, mul_assoc (tauProd p),
        pol_mul_ψ r hr2, mul_sub, sub_mul, sub_mul, ← mul_assoc, ← ψ_mul_tauProd r p hr1]
      simp only [mul_assoc]
    rw [key, mul_sub]
    refine Submodule.sub_mem _ ?_ (ih hρ' _ _ (Subalgebra.mul_mem _ (eqIdem_mem r hr2) hδ'))
    exact left_mul_mem_cycL0_of_subR1 a (ψ_mem_subR1 (by omega)) (ih hρ' _ _ hδ')

/-- KK's `P̃`: right multiplication by `a^Λ(x_1) Ψ_n` (zero-indexed, `n + 1 = m`). -/
noncomputable def tauW (h0 : 0 < m) (n : ℕ) : A := cycAt a ⟨0, h0⟩ * tauProd n

/-- KK Lemma 4.10, dots `x_{b}`, `b ≥ 1` (zero-indexed): `x_b P̃ ≡ P̃ x_{b-1}`. -/
theorem x_mul_tauW (h0 : 0 < m) (n : ℕ) (hn : n + 1 = m) (b : ℕ) (hb1 : 1 ≤ b) (hbn : b ≤ n) :
    (x ⟨b, by omega⟩ * tauW a h0 n - tauW a h0 n * x ⟨b - 1, by omega⟩ : A) ∈ cycL0 a h0 := by
  have hsplit := tauProd_eq (k := k) (Q := Q) (ν := ν) (b - 1) n (by omega)
  have hsplit' : List.range' (b - 1) (n - (b - 1)) = (b - 1) :: List.range' b (n - b) := by
    rw [show n - (b - 1) = (n - b) + 1 by omega, List.range'_succ, show b - 1 + 1 = b by omega]
  rw [hsplit', ψw_cons] at hsplit
  have hxb : (x ⟨b, by omega⟩ * ψ (b - 1) : A) =
      ψ (b - 1) * x ⟨b - 1, by omega⟩ - eqIdem (b - 1) (by omega) := by
    have := x_succ_mul_ψ (Q := Q) (ν := ν) (b - 1) (by omega)
    simp only [show b - 1 + 1 = b by omega] at this
    exact this
  have key : (x ⟨b, by omega⟩ * tauW a h0 n - tauW a h0 n * x ⟨b - 1, by omega⟩ : A) =
      -(cycAt a ⟨0, h0⟩ * (tauProd (b - 1) * pol 1 * eqIdem (b - 1) (by omega) *
        ψw (List.range' b (n - b)))) := by
    rw [tauW, ← mul_assoc, ← cycAt_mul_x, mul_assoc, mul_assoc, ← mul_sub, ← mul_neg, hsplit,
      ← mul_assoc, x_mul_tauProd _ _ (by simp; omega), mul_assoc, ← mul_assoc (x _), hxb,
      sub_mul, mul_sub, mul_assoc (ψ _), x_mul_ψw _ _ (fun j hj => by simp at hj; simp; omega),
      map_one, mul_one]
    noncomm_ring
  rw [key]
  exact Submodule.neg_mem _ (cycAt_tau_pol_word_mem a h0 (b - 1) (by omega) _
    (fun r hr => by simp at hr; omega) _ _ (eqIdem_mem _ _))

/-- KK Lemma 4.10, the first dot: `x_0 P̃ ≡ P̃ x_n`. -/
theorem x_zero_mul_tauW (h0 : 0 < m) (n : ℕ) (hn : n + 1 = m) :
    (x ⟨0, h0⟩ * tauW a h0 n - tauW a h0 n * x ⟨n, by omega⟩ : A) ∈ cycL0 a h0 := by
  have claim : ∀ p (hp : p ≤ n), (cycAt a ⟨0, h0⟩ * (x ⟨0, h0⟩ * tauProd n -
      tauProd p * x ⟨p, by omega⟩ * ψw (List.range' p (n - p))) : A) ∈ cycL0 a h0 := by
    intro p
    induction p with
    | zero =>
      intro _
      rw [tauProd_zero, one_mul, Nat.sub_zero, tauProd, List.range_eq_range', sub_self, mul_zero]
      exact Submodule.zero_mem _
    | succ p ih =>
      intro hp
      have hsplit : List.range' p (n - p) = p :: List.range' (p + 1) (n - (p + 1)) := by
        rw [show n - p = (n - (p + 1)) + 1 by omega, List.range'_succ]
      have hstep : (tauProd p * x ⟨p, by omega⟩ * ψw (List.range' p (n - p)) : A) =
          tauProd (p + 1) * x ⟨p + 1, by omega⟩ * ψw (List.range' (p + 1) (n - (p + 1))) +
          tauProd p * pol 1 * eqIdem p (by omega) * ψw (List.range' (p + 1) (n - (p + 1))) := by
        rw [hsplit, ψw_cons, ← mul_assoc, mul_assoc (tauProd p), x_mul_ψ_self p (by omega),
          tauProd_succ, map_one, mul_one]
        noncomm_ring
      have := Submodule.add_mem _ (ih (by omega)) (cycAt_tau_pol_word_mem a h0 p (by omega)
        (List.range' (p + 1) (n - (p + 1))) (fun r hr => by simp at hr; omega) 1
        (eqIdem p (by omega)) (eqIdem_mem _ _))
      rw [hstep] at this
      convert this using 1
      noncomm_ring
  have h := claim n le_rfl
  rw [Nat.sub_self, List.range'_zero, ψw_nil, mul_one] at h
  have key : (x ⟨0, h0⟩ * tauW a h0 n - tauW a h0 n * x ⟨n, by omega⟩ : A) =
      cycAt a ⟨0, h0⟩ * (x ⟨0, h0⟩ * tauProd n - tauProd n * x ⟨n, by omega⟩) := by
    rw [tauW, ← mul_assoc, ← cycAt_mul_x, mul_sub, mul_assoc, mul_assoc]
  rw [key]; exact h

/-- KK Lemma 4.10, idempotents: `e(𝐢) P̃ = P̃ e(c_n 𝐢)`. -/
theorem e_mul_tauW (h0 : 0 < m) (n : ℕ) (t : Seq ν) :
    (e t * tauW a h0 n : A) = tauW a h0 n * e (cP m n • t) := by
  rw [tauW, ← mul_assoc, ← cycAt_mul_e', mul_assoc, e_mul_tauProd, ← mul_assoc]

/-- KK Lemma 4.10, crossings: `ψ_j P̃ ≡ P̃ ψ_{j-1}` for `1 ≤ j < n`. -/
theorem ψ_mul_tauW (h0 : 0 < m) (n : ℕ) (hn : n + 1 = m) (j : ℕ) (hj1 : 1 ≤ j)
    (hjn : j + 1 ≤ n) :
    (ψ j * tauW a h0 n - tauW a h0 n * ψ (j - 1) : A) ∈ cycL0 a h0 := by
  obtain ⟨j, rfl⟩ : ∃ j', j = j' + 1 := ⟨j - 1, by omega⟩
  rw [Nat.add_sub_cancel]
  have hsplit := tauProd_eq (k := k) (Q := Q) (ν := ν) j n (by omega)
  have hl : List.range' j (n - j) = j :: (j + 1) :: List.range' (j + 2) (n - (j + 2)) := by
    rw [show n - j = (n - (j + 2)) + 1 + 1 by omega, List.range'_succ, List.range'_succ]
  rw [hl, ψw_cons, ψw_cons] at hsplit
  have hj' : j + 2 < m := by omega
  have hBmem : (cycAt a ⟨0, h0⟩ * (tauProd j * (ψ j * ψ (j + 1) * ψ j - ψ (j + 1) * ψ j * ψ (j + 1)) *
      ψw (List.range' (j + 2) (n - (j + 2)))) : A) ∈ cycL0 a h0 := by
    rw [← mul_one (ψ j * ψ (j + 1) * ψ j - ψ (j + 1) * ψ j * ψ (j + 1)), ← sum_e, Finset.mul_sum,
      Finset.mul_sum, Finset.sum_mul, Finset.mul_sum]
    refine Submodule.sum_mem _ fun t _ => ?_
    rw [braid (Q := Q) j hj' t]
    split_ifs
    · rw [ncEval_x₃]
      simpa only [mul_assoc] using cycAt_tau_pol_word_mem a h0 j (by omega)
        (List.range' (j + 2) (n - (j + 2)))
        (fun r hr => by have := List.mem_range'_1.mp hr; omega) _ _ (e_mem_eSub t)
    · rw [mul_zero, zero_mul, mul_zero]; exact Submodule.zero_mem _
  have hcomm1 : (ψ (j + 1) * tauProd j : A) = tauProd j * ψ (j + 1) :=
    ψ_mul_tauProd (j + 1) j le_rfl
  have hcomm2 : (ψ j * ψw (List.range' (j + 2) (n - (j + 2))) : A) =
      ψw (List.range' (j + 2) (n - (j + 2))) * ψ j :=
    ψ_mul_ψw j _ (fun l hl => by simp at hl; omega)
  have key : (ψ (j + 1) * tauW a h0 n - tauW a h0 n * ψ j : A) =
      -(cycAt a ⟨0, h0⟩ * (tauProd j * (ψ j * ψ (j + 1) * ψ j - ψ (j + 1) * ψ j * ψ (j + 1)) *
        ψw (List.range' (j + 2) (n - (j + 2))))) := by
    rw [tauW, ← mul_assoc, ← cycAt_mul_ψ a ⟨0, h0⟩ (j + 1) ⟨by simp, by simp⟩, mul_assoc,
      mul_assoc, ← mul_sub, ← mul_neg, hsplit]
    congr 1
    have e1 : (ψ (j + 1) * (tauProd j * (ψ j * (ψ (j + 1) *
        ψw (List.range' (j + 2) (n - (j + 2)))))) : A) =
        tauProd j * (ψ (j + 1) * ψ j * ψ (j + 1)) * ψw (List.range' (j + 2) (n - (j + 2))) := by
      rw [← mul_assoc, hcomm1]; simp only [mul_assoc]
    have e2 : (tauProd j * (ψ j * (ψ (j + 1) * ψw (List.range' (j + 2) (n - (j + 2))))) * ψ j :
        A) = tauProd j * (ψ j * ψ (j + 1) * ψ j) * ψw (List.range' (j + 2) (n - (j + 2))) := by
      simp only [mul_assoc]; rw [← hcomm2]
    rw [e1, e2]
    noncomm_ring
  rw [key]; exact Submodule.neg_mem _ hBmem

omit [DecidableEq I] in
theorem cP_apply_zero (n : ℕ) (hn : n + 1 = m) (h0 : 0 < m) :
    cP m n ⟨0, h0⟩ = ⟨n, by omega⟩ :=
  (Equiv.eq_symm_apply _).mp (cP_symm_self (ν := ν) n (by omega)).symm

omit [DecidableEq I] in
theorem cP_apply_pos (n : ℕ) (hn : n + 1 = m) (b : ℕ) (hb1 : 1 ≤ b) (hbn : b ≤ n) :
    cP m n ⟨b, by omega⟩ = ⟨b - 1, by omega⟩ := by
  have h : (cP m n).symm ⟨b - 1, by omega⟩ = ⟨b, by omega⟩ := by
    apply Fin.ext; rw [cP_symm_val m n (by omega)]; dsimp only; split_ifs <;> omega
  exact (Equiv.eq_symm_apply _).mp h.symm

/-- KK Lemma 4.10 for every dot: `x_b P̃ ≡ P̃ x_{c_n(b)}`. -/
theorem x_mul_tauW' (h0 : 0 < m) (n : ℕ) (hn : n + 1 = m) (b : Fin m) :
    (x b * tauW a h0 n - tauW a h0 n * x (cP m n b) : A) ∈ cycL0 a h0 := by
  obtain ⟨b, hb⟩ := b
  by_cases hb0 : b = 0
  · subst hb0; rw [cP_apply_zero n hn h0]; exact x_zero_mul_tauW a h0 n hn
  · rw [cP_apply_pos n hn b (by omega) (by omega)]
    exact x_mul_tauW a h0 n hn b (by omega) (by omega)

/-- KK Lemma 4.10 for polynomials. -/
theorem pol_mul_tauW (h0 : 0 < m) (n : ℕ) (hn : n + 1 = m) (f : MvPolynomial (Fin m) k) :
    (pol f * tauW a h0 n - tauW a h0 n * pol (rename (cP m n) f) : A) ∈ cycL0 a h0 := by
  induction f using MvPolynomial.induction_on with
  | C c =>
    rw [algHom_C, rename_C, algHom_C, ← Algebra.commutes, sub_self]; exact Submodule.zero_mem _
  | add f g hf hg =>
    rw [map_add, map_add, map_add, add_mul, mul_add]
    convert Submodule.add_mem _ hf hg using 1; abel
  | mul_X f b hf =>
    have h1 := Submodule.smul_mem _ (pol f) (x_mul_tauW' (Q := Q) a h0 n hn b)
    have h2 := mul_mem_cycL0 a hf (x_mem_subR0 (cP m n b))
    rw [smul_eq_mul] at h1
    convert Submodule.add_mem _ h1 h2 using 1
    rw [map_mul, map_mul, rename_X, map_mul, pol_X, pol_X]
    noncomm_ring

/-- KK Lemma 4.10 (summary): every element of `k[x_1] ⊗ R^1(β)` passes through `P̃` modulo
`R(ν) a^Λ(x_1) R(β)`. -/
theorem exists_mul_tauW (h0 : 0 < m) (n : ℕ) (hn : n + 1 = m) {u : A}
    (hu : u ∈ subR1 (k := k) (Q := Q) ν) :
    ∃ u' ∈ subR0 (k := k) (Q := Q) ν, u * tauW a h0 n - tauW a h0 n * u' ∈ cycL0 a h0 := by
  induction hu using Algebra.adjoin_induction with
  | mem y hy =>
    rcases hy with (⟨b, rfl⟩ | ⟨t, rfl⟩) | ⟨j, hj, rfl⟩
    · exact ⟨_, x_mem_subR0 _, x_mul_tauW' a h0 n hn b⟩
    · refine ⟨_, e_mem_subR0 (cP m n • t), ?_⟩
      rw [e_mul_tauW, sub_self]; exact Submodule.zero_mem _
    · by_cases hjn : j + 1 ≤ n
      · exact ⟨_, ψ_mem_subR0 (by omega), ψ_mul_tauW a h0 n hn j hj hjn⟩
      · refine ⟨0, Subalgebra.zero_mem _, ?_⟩
        rw [ψ_eq_zero j (by omega), zero_mul, mul_zero, sub_self]; exact Submodule.zero_mem _
  | algebraMap c =>
    refine ⟨algebraMap k A c, Subalgebra.algebraMap_mem _ c, ?_⟩
    rw [Algebra.commutes, sub_self]; exact Submodule.zero_mem _
  | add y z _ _ hy hz =>
    obtain ⟨y', hy', hy⟩ := hy
    obtain ⟨z', hz', hz⟩ := hz
    refine ⟨y' + z', Subalgebra.add_mem _ hy' hz', ?_⟩
    convert Submodule.add_mem _ hy hz using 1; noncomm_ring
  | mul y z _ _ hy hz =>
    obtain ⟨y', hy', hy⟩ := hy
    obtain ⟨z', hz', hz⟩ := hz
    refine ⟨y' * z', Subalgebra.mul_mem _ hy' hz', ?_⟩
    have h1 := Submodule.smul_mem _ y hz
    have h2 := mul_mem_cycL0 a hy hz'
    rw [smul_eq_mul] at h1
    convert Submodule.add_mem _ h1 h2 using 1; noncomm_ring

omit [DecidableEq I] in
theorem cP_smul_apply_zero (n : ℕ) (hn : n + 1 = m) (h1 : 1 < m) (t : Seq ν) :
    (cP m n • t).1 ⟨0, by omega⟩ = t.1 ⟨1, h1⟩ := by
  rw [cP_smul_apply]; apply lbl_congr; rw [cP_symm_val m n (by omega)]; simp; omega

/-- `a^Λ(x_2) P̃ ≡ P̃ a^Λ(x_1)`. -/
theorem cycAt_one_mul_tauW (h0 : 0 < m) (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) :
    (cycAt a ⟨1, h1⟩ * tauW a h0 n - tauW a h0 n * cycAt a ⟨0, h0⟩ : A) ∈ cycL0 a h0 := by
  have hc1 : cP m n ⟨1, h1⟩ = ⟨0, h0⟩ := by
    have := cP_apply_pos (ν := ν) n hn 1 le_rfl (by omega); simpa using this
  have hre : ∀ t : Seq ν, rename (cP m n) (Polynomial.aeval (X ⟨1, h1⟩ : MvPolynomial (Fin m) k)
      (a (t.1 ⟨1, h1⟩))) = Polynomial.aeval (X ⟨0, h0⟩) (a ((cP m n • t).1 ⟨0, h0⟩)) := by
    intro t; rw [rename_aeval_X, hc1, cP_smul_apply_zero n hn h1]
  have hsum : (tauW a h0 n * cycAt a ⟨0, h0⟩ : A) = ∑ t : Seq ν, tauW a h0 n *
      (pol (Polynomial.aeval (X ⟨0, h0⟩) (a ((cP m n • t).1 ⟨0, h0⟩))) * e (cP m n • t)) := by
    rw [cycAt, Finset.mul_sum]
    exact (Fintype.sum_equiv (MulAction.toPerm (cP m n)) _ _ (fun t => rfl)).symm
  rw [hsum, cycAt, Finset.sum_mul, ← Finset.sum_sub_distrib]
  refine Submodule.sum_mem _ fun t _ => ?_
  have h := mul_mem_cycL0 a (pol_mul_tauW (Q := Q) a h0 n hn (Polynomial.aeval (X ⟨1, h1⟩)
    (a (t.1 ⟨1, h1⟩)))) (e_mem_subR0 (cP m n • t))
  rw [hre] at h
  convert h using 1
  rw [mul_assoc, e_mul_tauW, sub_mul]
  simp only [mul_assoc]

/-- **KK Lemma 4.10 and (4.6)**: right multiplication by `a^Λ(x_1) Ψ_n` carries
`R(ν) a^Λ(x_2) R^1(β)` into `R(ν) a^Λ(x_1) R(β)`. -/
theorem mul_tauW_mem (h0 : 0 < m) (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) {z : A}
    (hz : z ∈ cycL1 a h1) : z * tauW a h0 n ∈ cycL0 a h0 := by
  induction hz using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w, hw, rfl⟩ := hy
    obtain ⟨w', hw', hd⟩ := exists_mul_tauW a h0 n hn hw
    have e1 := Submodule.smul_mem _ (cycAt a ⟨1, h1⟩) hd
    have e2 := mul_mem_cycL0 a (cycAt_one_mul_tauW a h0 h1 n hn) hw'
    have e3 := Submodule.smul_mem _ (tauW a h0 n) (cycAt_mul_mem_cycL0 a h0 hw')
    rw [smul_eq_mul] at e1 e3
    convert Submodule.add_mem _ (Submodule.add_mem _ e1 e2) e3 using 1
    noncomm_ring
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add y z _ _ hy hz => rw [add_mul]; exact Submodule.add_mem _ hy hz
  | smul r y _ hy => rw [smul_eq_mul, mul_assoc]; exact Submodule.smul_mem _ r hy

end lemma410

/-! ### KK Propositions 4.13, 4.14: right multiplication by `G_n` -/

section prop413

variable (a : I → Polynomial k) (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b))
include hsym

/-- `ψ_j G_r = G_r ψ_{j+1}` for `j + 2 ≤ r` (from KK Lemma 4.12). -/
theorem ψ_mul_gProd_shift (j d : ℕ) (h : j + 2 + d < m) :
    (ψ j * gProd (j + 2 + d) : A) = gProd (j + 2 + d) * ψ (j + 1) := by
  induction d with
  | zero =>
    have h4 := ψ_mul_gInt_mul_gInt hsym (ν := ν) j (by omega)
    rw [show j + 2 + 0 = j + 1 + 1 from rfl, gProd_succ, gProd_succ, gI_of_lt (by omega),
      gI_of_lt (by omega), ← mul_assoc, ← mul_assoc, h4, mul_assoc,
      ψ_mul_gProd (j + 1) j (by omega) le_rfl]
    simp only [mul_assoc]
  | succ d ih =>
    rw [show j + 2 + (d + 1) = (j + 2 + d) + 1 by omega, gProd_succ, gI_of_lt (by omega),
      ← mul_assoc, ψ_mul_gInt_far j _ _ (Or.inr (by omega)), mul_assoc, ih (by omega),
      ← mul_assoc]

/-- KK Proposition 4.13: `R(β) ⊗ k[x_m]` passes through `G_n`, landing in `k[x_1] ⊗ R^1(β)`. -/
theorem exists_mul_gProd (n : ℕ) (hn : n + 1 = m) {u : A} (hu : u ∈ subR0 (k := k) (Q := Q) ν) :
    ∃ u' ∈ subR1 (k := k) (Q := Q) ν, u * gProd n = gProd n * u' := by
  induction hu using Algebra.adjoin_induction with
  | mem y hy =>
    rcases hy with (⟨b, rfl⟩ | ⟨t, rfl⟩) | ⟨j, hj, rfl⟩
    · refine ⟨_, x_mem_subR1 ((cP m n).symm b), ?_⟩
      rw [← pol_X, pol_mul_gProd hsym n (by omega), rename_X, pol_X]
    · refine ⟨_, e_mem_subR1 ((cP m n)⁻¹ • t), ?_⟩
      rw [gProd_mul_e n (by omega), smul_inv_smul]
    · refine ⟨_, ψ_mem_subR1 (by omega : 1 ≤ j + 1), ?_⟩
      have := ψ_mul_gProd_shift hsym (ν := ν) j (n - (j + 2)) (by omega)
      rwa [show j + 2 + (n - (j + 2)) = n by omega] at this
  | algebraMap c =>
    exact ⟨algebraMap k A c, Subalgebra.algebraMap_mem _ c, Algebra.commutes c _⟩
  | add y z _ _ hy hz =>
    obtain ⟨y', hy', hy⟩ := hy
    obtain ⟨z', hz', hz⟩ := hz
    exact ⟨y' + z', Subalgebra.add_mem _ hy' hz', by rw [add_mul, mul_add, hy, hz]⟩
  | mul y z _ _ hy hz =>
    obtain ⟨y', hy', hy⟩ := hy
    obtain ⟨z', hz', hz⟩ := hz
    exact ⟨y' * z', Subalgebra.mul_mem _ hy' hz', by rw [mul_assoc, hz, ← mul_assoc, hy, mul_assoc]⟩

omit hsym in
omit [DecidableEq I] in
theorem cP_apply_one (n : ℕ) (hn : n + 1 = m) (h0 : 0 < m) (h1 : 1 < m) :
    cP m n ⟨1, h1⟩ = ⟨0, h0⟩ := by
  have := cP_apply_pos (ν := ν) n hn 1 le_rfl (by omega); simpa using this

/-- `a^Λ(x_1) G_n = G_n a^Λ(x_2)`. -/
theorem cycAt_zero_mul_gProd (h0 : 0 < m) (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) :
    (cycAt a ⟨0, h0⟩ * gProd n : A) = gProd n * cycAt a ⟨1, h1⟩ := by
  have hlab : ∀ t : Seq ν, ((cP m n)⁻¹ • t).1 ⟨1, h1⟩ = t.1 ⟨0, h0⟩ := fun t => by
    rw [Seq.smul_apply]
    show t.1 ((cP m n) ⟨1, h1⟩) = t.1 ⟨0, h0⟩
    rw [cP_apply_one n hn h0 h1]
  have hs0 : (cP m n).symm ⟨0, h0⟩ = ⟨1, h1⟩ := by
    apply Fin.ext; rw [cP_symm_val m n (by omega)]; dsimp only; split_ifs <;> omega
  rw [cycAt, Finset.sum_mul]
  have : ∀ t : Seq ν, (pol (Polynomial.aeval (X ⟨0, h0⟩) (a (t.1 ⟨0, h0⟩))) * e t * gProd n : A) =
      gProd n * (pol (Polynomial.aeval (X ⟨1, h1⟩) (a (((cP m n)⁻¹ • t).1 ⟨1, h1⟩))) *
        e ((cP m n)⁻¹ • t)) := fun t => by
    rw [mul_assoc, ← smul_inv_smul (cP m n) t, ← gProd_mul_e n (by omega), inv_smul_smul,
      smul_inv_smul, ← mul_assoc, pol_mul_gProd hsym n (by omega), rename_aeval_X, hs0, hlab,
      mul_assoc]
  simp only [this]
  rw [← Finset.mul_sum, cycAt]
  congr 1
  exact Fintype.sum_equiv (MulAction.toPerm (cP m n)⁻¹) _ _ (fun t => rfl)

end prop413

/-! ### The maps `P : K_1 → K_0`, `Q : K_0 → K_1` and KK Theorem 4.15 -/

section maps

variable (a : I → Polynomial k)

variable (Q ν) in
/-- KK's `K_0 = R(ν) e(β, i) / R(ν) a^Λ(x_1) R(β) e(β, i)`, summed over the colour `i` of the last
strand. -/
abbrev KZero (h0 : 0 < m) : Type _ := A ⧸ cycL0 (Q := Q) a h0

variable (Q ν) in
/-- KK's `K_1 = R(ν) e(i, β) / R(ν) a^Λ(x_2) R^1(β) e(i, β)`, summed over the colour `i` of the
first strand. -/
abbrev KOne (h1 : 1 < m) : Type _ := A ⧸ cycL1 (Q := Q) a h1

/-- **KK Proposition 4.14**: right multiplication by `G_n` carries `R(ν) a^Λ(x_1) R(β)` into
`R(ν) a^Λ(x_2) R^1(β)`. -/
theorem mul_gProd_mem (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b)) (h0 : 0 < m)
    (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) {z : A} (hz : z ∈ cycL0 a h0) :
    z * gProd n ∈ cycL1 a h1 := by
  induction hz using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨w, hw, rfl⟩ := hy
    obtain ⟨w', hw', hww⟩ := exists_mul_gProd hsym n hn hw
    rw [mul_assoc, hww, ← mul_assoc, cycAt_zero_mul_gProd a hsym h0 h1 n hn, mul_assoc]
    exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨w', hw', rfl⟩)
  | zero => rw [zero_mul]; exact Submodule.zero_mem _
  | add y z _ _ hy hz => rw [add_mul]; exact Submodule.add_mem _ hy hz
  | smul r y _ hy => rw [smul_eq_mul, mul_assoc]; exact Submodule.smul_mem _ r hy

/-- **KK's map `P : K_1 → K_0`**: right multiplication by `a^Λ(x_1) ψ_0 ⋯ ψ_{n-1}`
(KK Lemma 4.10 and (4.6); KK's `τ_1 ⋯ τ_n` is `±ψ_0 ⋯ ψ_{n-1}` on each `e(i, ν')`). -/
noncomputable def pMap (h0 : 0 < m) (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) :
    KOne Q ν a h1 →ₗ[A] KZero Q ν a h0 :=
  (cycL1 a h1).liftQ ((cycL0 a h0).mkQ ∘ₗ LinearMap.toSpanSingleton A A (tauW a h0 n))
    (fun z hz => by
      rw [LinearMap.mem_ker, LinearMap.comp_apply, LinearMap.toSpanSingleton_apply, smul_eq_mul,
        Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
      exact mul_tauW_mem a h0 h1 n hn hz)

theorem pMap_mk (h0 : 0 < m) (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) (r : A) :
    pMap a h0 h1 n hn (Submodule.Quotient.mk r) = Submodule.Quotient.mk (r * tauW a h0 n) := by
  rw [pMap, Submodule.liftQ_apply, LinearMap.comp_apply, LinearMap.toSpanSingleton_apply,
    smul_eq_mul, Submodule.mkQ_apply]

/-- **KK's map `Q : K_0 → K_1`** (Props. 4.13, 4.14): right multiplication by `g_{n-1} ⋯ g_0`. -/
noncomputable def qMap (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b)) (h0 : 0 < m)
    (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) : KZero Q ν a h0 →ₗ[A] KOne Q ν a h1 :=
  (cycL0 a h0).liftQ ((cycL1 a h1).mkQ ∘ₗ LinearMap.toSpanSingleton A A (gProd n))
    (fun z hz => by
      rw [LinearMap.mem_ker, LinearMap.comp_apply, LinearMap.toSpanSingleton_apply, smul_eq_mul,
        Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
      exact mul_gProd_mem a hsym h0 h1 n hn hz)

theorem qMap_mk (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b)) (h0 : 0 < m)
    (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) (r : A) :
    qMap a hsym h0 h1 n hn (Submodule.Quotient.mk r) = Submodule.Quotient.mk (r * gProd n) := by
  rw [qMap, Submodule.liftQ_apply, LinearMap.comp_apply, LinearMap.toSpanSingleton_apply,
    smul_eq_mul, Submodule.mkQ_apply]

/-- KK's `A = ∑_𝐢 a_{i_1}(x_1) F_n(𝐢) e(𝐢)`, with `F_n` as in `cyc_tau_g`. -/
noncomputable def aElt (h0 : 0 < m) (n : ℕ) : A :=
  ∑ s : Seq ν, pol (cycA a h0 s * cycF Q s n) * e s

/-- **Kang–Kashiwara, Theorem 4.15**: `Q ∘ P` is right multiplication by
`A = ∑_𝐢 a_{i_1}(x_1) F_n(𝐢) e(𝐢)` on `K_1` (`F_n(𝐢) = (−1)^{β_{i_1}} ∏_{i_b ≠ i_1}
Q_{i_1 i_b}(x_1, x_b)`; the sign is the conversion between KK's `τ` and `ψ`). -/
theorem qMap_pMap (hsym : ∀ a b, a ≠ b → Q b a = rename ![1, 0] (Q a b)) (h0 : 0 < m)
    (h1 : 1 < m) (n : ℕ) (hn : n + 1 = m) (r : A) :
    qMap a hsym h0 h1 n hn (pMap a h0 h1 n hn (Submodule.Quotient.mk r)) =
      Submodule.Quotient.mk (r * aElt a h0 n) := by
  rw [pMap_mk, qMap_mk, Submodule.Quotient.eq, mul_assoc, ← mul_sub]
  refine Submodule.smul_mem _ r ?_
  have htop : ∀ s : Seq ν, (tauProd n * gProd n * e s : A) = e s * (tauProd n * gProd n) := by
    intro s
    rw [mul_assoc, gProd_mul_e n (by omega), ← mul_assoc, ← e_mul_tauProd, mul_assoc]
  have hterm : ∀ s : Seq ν, (tauW a h0 n * gProd n * e s : A) =
      pol (cycA a h0 s) * (tauProd n * gProd n) * e s := by
    intro s
    rw [tauW, mul_assoc (cycAt _ _), mul_assoc (cycAt _ _), htop, ← mul_assoc, cycAt_mul_e,
      mul_assoc, ← htop, ← mul_assoc]
    rfl
  rw [← mul_one (tauW a h0 n * gProd n), ← sum_e, Finset.mul_sum, aElt, ← Finset.sum_sub_distrib]
  refine Submodule.sum_mem _ fun s _ => ?_
  rw [hterm]
  exact cyc_tau_g a hsym h1 n (by omega) s

end maps

end KLRAlgebra

end Categorification.KLR
