/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.Basic
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Cyclotomic KLR algebras

The cyclotomic quotient `R^Λ(β)` of the KLR algebra `R(β)`, following

* S.-J. Kang, M. Kashiwara, *Categorification of highest weight modules via
  Khovanov–Lauda–Rouquier algebras*, arXiv:1102.4677v4, §4.1, Definition 4.1
  (`R^Λ(β) = R(β) / R(β) a^Λ(x_1) R(β)`), and
* M. Khovanov, A. Lauda, *A categorification of quantum `sl(n)`*, arXiv:0807.3250v1, §3.4
  (the undeformed case `a_i(u) = u^{⟨i, Λ⟩}`).

Kang–Kashiwara work over a graded commutative base ring `k` and allow an arbitrary monic
polynomial `a_i^Λ(u) = Σ_k c_{i;k} u^{⟨h_i, Λ⟩ - k}` for each colour `i` (with `c_{i;k}` of degree
`k (α_i | α_i)`); the cyclotomic ideal is the two-sided ideal generated by
`a^Λ(x_1) = Σ_𝐢 a_{i_1}^Λ(x_1) e(𝐢)`, equivalently by the elements `a_{i_1}^Λ(x_1) e(𝐢)` for all
sequences `𝐢`. Here the base ring is any commutative ring `k`, the index type `I` is arbitrary
(it need not be finite), and `a : I → k[X]` is any family of polynomials (monicity and the
grading are not needed for the definition). The deformed cyclotomic quotients (coefficients of
`a_i` in a polynomial base ring) are the case `k = MvPolynomial _ k₀`.

Positions are zero-indexed as in `Categorification.KLR.Basic`: the paper's `x_1` is `x 0`.

## Main definitions and results

* `KLRAlgebra.cycElt Q a 𝐢 = a_{i_1}(x_1) e(𝐢)`, `KLRAlgebra.cycIdeal Q a ν` (the cyclotomic
  ideal, a two-sided ideal);
* `CycKLR k Q a ν` (`R^Λ(ν)`), a `k`-algebra, with the quotient map `CycKLR.mk`;
* `CycKLR.mk_eq_zero_iff`: the kernel of `R(ν) → R^Λ(ν)` is the cyclotomic ideal;
* `CycKLR.lift`: the universal property;
* `CycKLR.mk_e_eq_zero_of_eq_one`: `e(𝐢) = 0` in `R^Λ(ν)` when `a_{i_1} = 1` (KK: `R^Λ(β) = 0`
  when `⟨h_{i_1}, Λ⟩ = 0`, at the level of idempotents).
-/

namespace Categorification.KLR

open Polynomial

variable {I : Type*} [DecidableEq I] {k : Type*} [CommRing k]

namespace KLRAlgebra

variable (Q : I → I → MvPolynomial (Fin 2) k) (a : I → k[X]) {ν : Multiset I}

/-- The cyclotomic element `a_{i_1}(x_1) e(𝐢)` attached to a sequence `𝐢` (zero if there are no
strands). -/
noncomputable def cycElt (i : Seq ν) : KLRAlgebra k Q ν :=
  if h : 0 < Multiset.card ν then
    aeval (x ⟨0, h⟩ : KLRAlgebra k Q ν) (a (i.lbl ⟨0, h⟩)) * e i
  else 0

theorem cycElt_of_pos (i : Seq ν) (h : 0 < Multiset.card ν) :
    cycElt Q a i = aeval (x ⟨0, h⟩ : KLRAlgebra k Q ν) (a (i.lbl ⟨0, h⟩)) * e i := by
  simp only [cycElt, h, ↓reduceDIte]

variable (ν) in
/-- **The cyclotomic ideal** of `R(ν)` (Kang–Kashiwara, §4.1): the two-sided ideal generated by
the elements `a_{i_1}(x_1) e(𝐢)`. -/
noncomputable def cycIdeal : TwoSidedIdeal (KLRAlgebra k Q ν) :=
  TwoSidedIdeal.span (Set.range (cycElt (ν := ν) Q a))

theorem cycElt_mem_cycIdeal (i : Seq ν) : cycElt Q a i ∈ cycIdeal Q a ν :=
  TwoSidedIdeal.subset_span ⟨i, rfl⟩

variable (ν) in
/-- The defining relation of the cyclotomic quotient: `a_{i_1}(x_1) e(𝐢) ~ 0`. -/
inductive CycRel : KLRAlgebra k Q ν → KLRAlgebra k Q ν → Prop
  | cyc (i : Seq ν) : CycRel (cycElt Q a i) 0

end KLRAlgebra

open KLRAlgebra

variable (k) in
/-- **The cyclotomic KLR algebra** `R^Λ(ν) = R(ν) / R(ν) a^Λ(x_1) R(ν)` (Kang–Kashiwara,
arXiv:1102.4677v4, §4.1), for KLR data `Q` and cyclotomic polynomials `a : I → k[X]`. -/
def CycKLR (Q : I → I → MvPolynomial (Fin 2) k) (a : I → k[X]) (ν : Multiset I) : Type _ :=
  RingQuot (CycRel Q a ν)

namespace CycKLR

variable {Q : I → I → MvPolynomial (Fin 2) k} {a : I → k[X]} {ν : Multiset I}

noncomputable instance : Ring (CycKLR k Q a ν) := inferInstanceAs (Ring (RingQuot _))
noncomputable instance : Algebra k (CycKLR k Q a ν) :=
  inferInstanceAs (Algebra k (RingQuot _))
noncomputable instance : Inhabited (CycKLR k Q a ν) := ⟨0⟩

variable (k Q a ν) in
/-- The quotient map `R(ν) → R^Λ(ν)`. -/
noncomputable def mk : KLRAlgebra k Q ν →ₐ[k] CycKLR k Q a ν :=
  RingQuot.mkAlgHom k (CycRel Q a ν)

theorem mk_surjective : Function.Surjective (mk k Q a ν) :=
  RingQuot.mkAlgHom_surjective _ _

/-- The cyclotomic relation `a_{i_1}(x_1) e(𝐢) = 0` holds in `R^Λ(ν)`. -/
@[simp]
theorem mk_cycElt (i : Seq ν) : mk k Q a ν (cycElt Q a i) = 0 := by
  rw [← map_zero (mk k Q a ν)]
  exact RingQuot.mkAlgHom_rel k (CycRel.cyc i)

/-- The cyclotomic relation on the first strand: `a_{i_1}(x_1) e(𝐢) = 0` in `R^Λ(ν)`. -/
theorem mk_aeval_x_mul_e (i : Seq ν) (h : 0 < Multiset.card ν) :
    mk k Q a ν (aeval (x ⟨0, h⟩ : KLRAlgebra k Q ν) (a (i.lbl ⟨0, h⟩)) * e i) = 0 := by
  rw [← cycElt_of_pos Q a i h]
  exact mk_cycElt i

/-- The congruence generated by the cyclotomic relation is that of the cyclotomic ideal. -/
theorem ringConGen_cycRel :
    ringConGen (CycRel Q a ν) = (cycIdeal Q a ν).ringCon := by
  apply le_antisymm
  · rw [RingCon.ringConGen_le]
    rintro _ _ ⟨i⟩
    exact (TwoSidedIdeal.mem_iff _ _).1 (cycElt_mem_cycIdeal Q a i)
  · change ringConGen _ ≤ _
    rw [RingCon.ringConGen_le]
    rintro u v ⟨i, hi⟩
    have h1 : ringConGen (CycRel Q a ν) (cycElt Q a i) 0 :=
      RingConGen.Rel.of _ _ (CycRel.cyc i)
    have h2 := (ringConGen (CycRel Q a ν)).add h1 ((ringConGen (CycRel Q a ν)).refl v)
    have hu : u = cycElt Q a i + v := by rw [hi]; abel
    rw [hu]
    simpa using h2

theorem mk_eq_mk_iff_rel (u v : KLRAlgebra k Q ν) :
    mk k Q a ν u = mk k Q a ν v ↔ RingConGen.Rel (CycRel Q a ν) u v := by
  rw [← RingQuot.eqvGen_rel_eq]
  simp only [mk, RingQuot.mkAlgHom_def, RingQuot.mkRingHom_def]
  constructor
  · intro h
    exact Quot.eqvGen_exact (RingQuot.mk.inj h)
  · intro h
    exact congrArg RingQuot.mk (Quot.eqvGen_sound h)

theorem mk_eq_mk_iff (u v : KLRAlgebra k Q ν) :
    mk k Q a ν u = mk k Q a ν v ↔ u - v ∈ cycIdeal Q a ν := by
  rw [mk_eq_mk_iff_rel, ← TwoSidedIdeal.rel_iff, ← ringConGen_cycRel]
  rfl

/-- **The kernel of `R(ν) → R^Λ(ν)` is the cyclotomic ideal.** -/
theorem mk_eq_zero_iff (u : KLRAlgebra k Q ν) :
    mk k Q a ν u = 0 ↔ u ∈ cycIdeal Q a ν := by
  rw [← map_zero (mk k Q a ν), mk_eq_mk_iff, sub_zero]

/-- The universal property of `R^Λ(ν)`: an algebra map out of `R(ν)` killing every
`a_{i_1}(x_1) e(𝐢)` factors through `R^Λ(ν)`. -/
noncomputable def lift {B : Type*} [Semiring B] [Algebra k B] (f : KLRAlgebra k Q ν →ₐ[k] B)
    (hf : ∀ i : Seq ν, f (cycElt Q a i) = 0) : CycKLR k Q a ν →ₐ[k] B :=
  RingQuot.liftAlgHom k ⟨f, fun _ _ h => by cases h; simp [hf]⟩

@[simp]
theorem lift_mk {B : Type*} [Semiring B] [Algebra k B] (f : KLRAlgebra k Q ν →ₐ[k] B)
    (hf : ∀ i : Seq ν, f (cycElt Q a i) = 0) (u : KLRAlgebra k Q ν) :
    lift f hf (mk k Q a ν u) = f u :=
  RingQuot.liftAlgHom_mkAlgHom_apply k f _ u

@[ext]
theorem algHom_ext {B : Type*} [Semiring B] [Algebra k B] {f g : CycKLR k Q a ν →ₐ[k] B}
    (h : f.comp (mk k Q a ν) = g.comp (mk k Q a ν)) : f = g :=
  RingQuot.ringQuot_ext' k f g h

/-- If `a_{i_1} = 1` (KK: `⟨h_{i_1}, Λ⟩ = 0`) then `e(𝐢) = 0` in `R^Λ(ν)`. -/
theorem mk_e_eq_zero_of_eq_one (i : Seq ν) (h : 0 < Multiset.card ν)
    (ha : a (i.lbl ⟨0, h⟩) = 1) : mk k Q a ν (e i) = 0 := by
  have := mk_aeval_x_mul_e (Q := Q) (a := a) i h
  rwa [ha, map_one, one_mul] at this

end CycKLR

end Categorification.KLR
