/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.Simple
import Categorification.KLR.Examples.NilHecke
import Categorification.Algebra.NilHeckeSimple
import Categorification.Algebra.CoinvariantGraded

/-!
# The simple module `L(i^m)` of `R(m i) ≅ NH_m`

Khovanov–Lauda I (arXiv:0803.4121v2), §2.2 (TeX lines 733–749): the quotient `L_m` of
`k[x_1, …, x_m]` by the ideal generated by symmetric polynomials without constant term is an
irreducible `NH_m`-module over a field `k`, and "any graded irreducible representation of `NH_m` is
isomorphic to `L_m`, up to a grading shift. We denote the corresponding irreducible representation
of `R(mi)` by `L(i^m)`."

We work with `R(ν)` for `ν` all of whose labels equal `i` (`hν : ∀ a ∈ ν, a = i`; e.g.
`ν = replicate m i`), acting on `L_n = Coinv k n` (`n = card ν`) through the isomorphism
`R(ν) ≅ NH_n` (`KLRAlgebra.nilHeckeEquivOfForall`).

## Main results

* `KLRAlgebra.KLRRep hν Q` : the `R(ν)`-module `L(i^n)`; the dot `x_a` acts as multiplication by
  `x_a` (`klrAct_x`), so KL I Lemma 2.1 (`NilHecke.coinvSocle_eq_span_xDelta`,
  `Categorification.ker_coinvMul_last`) describes the action of the dots on `L(i^n)`.
* `KLRAlgebra.isSimpleModule_klrRep` : `L(i^n)` is a simple `R(ν)`-module.
* `KLRAlgebra.nonempty_linearEquiv_klrRep` : **every simple graded `R(ν)`-module is isomorphic to
  `L(i^n)`** (as an ungraded module), for any grading datum with dots of positive degree;
* `KLRAlgebra.exists_gradedEquiv_of_isGradedSimple` : hence any two simple graded `R(ν)`-modules
  are isomorphic up to a grading shift: the graded irreducible is unique up to isomorphism and
  shift.
* `KLRAlgebra.klrGrading`, `KLRAlgebra.isGradedSimple_klrRep` : `L(i^n)` with `deg x_a = degX i`
  is a simple graded `R(ν)`-module; `KLRAlgebra.exists_gradedEquiv_klrRep` : every simple graded
  `R(ν)`-module is isomorphic to `L(i^n){c}` for some `c`.
-/

namespace Categorification.NilHecke

open TypeA

variable {k : Type*} [CommRing k] {m : ℕ}

/-- `∂_ρ = 0` for every word of length `> m(m-1)/2`. -/
theorem ddw_eq_zero_of_choose_lt {ρ : List ℕ} (h : m.choose 2 < ρ.length) :
    ddw (k := k) (m := m) ρ = 0 := by
  by_cases hv : ValidWord m ρ
  · apply ddw_eq_zero_of_not_isReduced hv
    intro hr
    have := length_le_choose m (wordProd m ρ)
    rw [← hr.2] at this
    omega
  · simp only [ValidWord, not_forall] at hv
    obtain ⟨j, hj, hj'⟩ := hv
    obtain ⟨α, β, rfl⟩ := List.append_of_mem hj
    rw [ddw_append, ddw_cons, dd_eq_zero (by omega), zero_mul, mul_zero]

end Categorification.NilHecke

namespace Categorification.KLR

open MvPolynomial Equiv TypeA Categorification.NilHecke Graded DirectSum PolyRep

variable {I : Type*} [DecidableEq I] {k : Type*} [Field k]

namespace KLRAlgebra

variable {ν : Multiset I} {i : I} (hν : ∀ a ∈ ν, a = i) (Q : I → I → MvPolynomial (Fin 2) k)

local notation "n" => Multiset.card ν

/-! ### Relations in `R(ν)` with all labels equal -/

include hν in
/-- Words of more than `n(n-1)/2` crossings vanish in `R(ν)` (all labels equal). -/
theorem ψw_eq_zero_of_choose_lt {ρ : List ℕ} (h : (Multiset.card ν).choose 2 < ρ.length) :
    (ψw ρ : KLRAlgebra k Q ν) = 0 :=
  toNH_injective hν Q (by rw [toNH_ψw, map_zero, ddw_eq_zero_of_choose_lt h])

include hν in
/-- The nilHecke commutation relation `ψ_j p = ∂_j(p) + s_j(p) ψ_j` in `R(ν)` (all labels
equal). -/
theorem exists_ψ_mul_pol (j : ℕ) (p : MvPolynomial (Fin n) k) :
    ∃ q : MvPolynomial (Fin n) k,
      (ψ j * pol p : KLRAlgebra k Q ν) = pol (dd k n j p) + pol q * ψ j := by
  by_cases h : j + 1 < n
  · refine ⟨rename (swap (⟨j, by omega⟩ : Fin n) ⟨j + 1, h⟩) p, toNH_injective hν Q ?_⟩
    rw [map_mul, map_add, map_mul, toNH_ψ, toNH_pol, toNH_pol, toNH_pol]
    refine LinearMap.ext fun f => ?_
    simp only [Module.End.mul_apply, LinearMap.add_apply, mulPoly_apply, dd_of_lt h]
    exact ddiff_mul (fun e => by simp [Fin.ext_iff] at e) p f
  · refine ⟨0, ?_⟩
    rw [ψ_eq_zero j (by omega), dd_eq_zero (by omega)]
    simp

include hν in
theorem e_eq_one_of_forall (t : Seq ν) : (e t : KLRAlgebra k Q ν) = 1 := by
  letI := Seq.uniqueOfForall hν
  exact e_eq_one t

/-! ### The module `L(i^n)` -/

/-- The action of `R(ν)` on `L_n = k[x_1, …, x_n] / (Sym⁺)`, through `R(ν) ≅ NH_n`. -/
noncomputable def klrAct : KLRAlgebra k Q ν →ₐ[k] Module.End k (Coinv k n) :=
  (nhAct k n).comp (nilHeckeEquivOfForall hν Q).toAlgHom

theorem klrAct_mk (r : KLRAlgebra k Q ν) (p : MvPolynomial (Fin n) k) :
    klrAct hν Q r (Submodule.Quotient.mk p) = Submodule.Quotient.mk (toNH hν Q r p) := rfl

theorem klrAct_x (a : Fin n) : klrAct hν Q (x a) = coinvMul k (X a) := by
  ext p
  simp only [LinearMap.coe_comp, Function.comp_apply, Submodule.mkQ_apply, klrAct_mk, toNH_x,
    mulX_apply, coinvMul_mk]

/-- **`L(i^n)`**: `L_n` as an `R(ν)`-module (a type synonym for `Coinv k n`). -/
@[nolint unusedArguments]
def KLRRep (_hν : ∀ a ∈ ν, a = i) (_Q : I → I → MvPolynomial (Fin 2) k) : Type _ := Coinv k n

noncomputable instance : AddCommGroup (KLRRep hν Q) := inferInstanceAs (AddCommGroup (Coinv k n))
noncomputable instance : Module k (KLRRep hν Q) := inferInstanceAs (Module k (Coinv k n))
instance : FiniteDimensional k (KLRRep hν Q) := inferInstanceAs (FiniteDimensional k (Coinv k n))

/-- The identification `L_n = KLRRep hν Q`. -/
def KLRRep.of : Coinv k n ≃ₗ[k] KLRRep hν Q := LinearEquiv.refl k _

noncomputable instance : Module (KLRAlgebra k Q ν) (KLRRep hν Q) :=
  Module.compHom (Coinv k n) (klrAct hν Q).toRingHom

theorem klr_smul_def (r : KLRAlgebra k Q ν) (v : Coinv k n) :
    r • KLRRep.of hν Q v = KLRRep.of hν Q (klrAct hν Q r v) := rfl

instance : IsScalarTower k (KLRAlgebra k Q ν) (KLRRep hν Q) where
  smul_assoc c r v := by
    show klrAct hν Q (c • r) v = c • klrAct hν Q r v
    rw [show klrAct hν Q (c • r) = c • klrAct hν Q r from (klrAct hν Q).toLinearMap.map_smul c r,
      LinearMap.smul_apply]

/-- **`L(i^n)` is a simple `R(ν)`-module** (from the irreducibility of `L_n` over `NH_n`). -/
theorem isSimpleModule_klrRep : IsSimpleModule (KLRAlgebra k Q ν) (KLRRep hν Q) := by
  haveI : Nontrivial (KLRRep hν Q) := inferInstanceAs (Nontrivial (Coinv k n))
  have hNH := isSimpleModule_coinv (k := k) (m := n)
  refine { eq_bot_or_eq_top := fun N => ?_ }
  let N' : Submodule (nilHecke k n) (NHRep k n) :=
    { carrier := {v | KLRRep.of hν Q ((NHRep.of k n).symm v) ∈ N}
      add_mem' := fun {a b} ha hb => N.add_mem ha hb
      zero_mem' := N.zero_mem
      smul_mem' := fun T v hv => by
        have h1 := N.smul_mem ((nilHeckeEquivOfForall hν Q).symm T) hv
        have e1 : ((nilHeckeEquivOfForall hν Q).symm T) •
            KLRRep.of hν Q ((NHRep.of k n).symm v) =
              KLRRep.of hν Q ((NHRep.of k n).symm (T • v)) := by
          rw [klr_smul_def]
          congr 1
          show nhAct k n (nilHeckeEquivOfForall hν Q ((nilHeckeEquivOfForall hν Q).symm T)) v =
            nhAct k n T v
          rw [AlgEquiv.apply_symm_apply]
        show KLRRep.of hν Q ((NHRep.of k n).symm (T • v)) ∈ N
        rw [← e1]
        exact h1 }
  rcases IsSimpleOrder.eq_bot_or_eq_top N' with h | h
  · left
    rw [eq_bot_iff]
    intro v hv
    have hv' : NHRep.of k n ((KLRRep.of hν Q).symm v) ∈ N' := hv
    rw [h, Submodule.mem_bot] at hv'
    rw [Submodule.mem_bot]
    exact hv'
  · right
    rw [eq_top_iff]
    intro v _
    have hv' : NHRep.of k n ((KLRRep.of hν Q).symm v) ∈ N' := h ▸ Submodule.mem_top
    exact hv'

/-! ### The grading of `L(i^n)` -/

section Graded

variable (G : GradingDatum Q)

/-- The grading of `L(i^n)`: `x_a` has degree `G.degX i` (`= 2` in KL I). -/
noncomputable def klrGrading : ℤ → Submodule k (KLRRep hν Q) := coinvGrading k n (G.degX i)

noncomputable instance : Decomposition (klrGrading hν Q G) :=
  inferInstanceAs (Decomposition (coinvGrading k n (G.degX i)))

omit [DecidableEq I] in
include hν in
theorem weight_eq_const (t : Seq ν) (u : Fin n →₀ ℕ) :
    Finsupp.weight (fun a => G.degX (t.lbl a)) u = Finsupp.weight (fun _ => G.degX i) u := by
  rw [show (fun a => G.degX (t.lbl a)) = fun _ => G.degX i from
    funext fun a => congrArg G.degX (hν _ (t.mem a))]

omit [DecidableEq I] in
include hν in
/-- `∂_ρ` shifts the `constGrade` degree by `degW ρ t` (all labels equal). -/
theorem ddw_mem_constGrade (t : Seq ν) (ρ : List ℕ) {e : ℤ} {p : MvPolynomial (Fin n) k}
    (hp : p ∈ constGrade k n (G.degX i) e) :
    ddw (k := k) (m := n) ρ p ∈ constGrade k n (G.degX i) (G.degW ρ t + e) := by
  induction ρ with
  | nil => simpa [GradingDatum.degW] using hp
  | cons j ρ ih =>
    rw [ddw_cons, Module.End.mul_apply, GradingDatum.degW]
    by_cases h : j + 1 < n
    · have := dd_mem_constGrade j ih
      convert this using 2
      have hl : ∀ a, (wordProd n ρ • t).lbl a = i := fun a => hν _ ((wordProd n ρ • t).mem a)
      rw [GradingDatum.dψ_of_lt _ h, hl, hl, G.degΨ_self]
      ring
    · rw [dd_eq_zero (by omega), LinearMap.zero_apply]
      exact zero_mem _

include hν in
/-- The standard basis elements `ψ_{ρ w} x^u e_t` act on `k[x]` with the degree they have in
`R(ν)`. -/
theorem toNH_stdElt_mem (ρ : Perm (Fin n) → List ℕ) (b : Seq ν × Perm (Fin n) × (Fin n →₀ ℕ))
    {e : ℤ} {p : MvPolynomial (Fin n) k} (hp : p ∈ constGrade k n (G.degX i) e) :
    toNH hν Q (stdElt (k := k) (Q := Q) ρ b) p ∈ constGrade k n (G.degX i)
      (G.degW (ρ b.2.1) b.1 + Finsupp.weight (fun a => G.degX (b.1.lbl a)) b.2.2 + e) := by
  rw [stdElt, map_mul, map_mul, toNH_e, toNH_ψw, toNH_pol, mul_one, Module.End.mul_apply,
    mulPoly_apply, add_assoc]
  refine ddw_mem_constGrade hν Q G b.1 _ (mul_mem_constGrade ?_ hp)
  rw [mem_constGrade]
  exact isWeightedHomogeneous_monomial _ _ _ (weight_eq_const hν Q G b.1 b.2.2).symm

/-- Elements of degree `d` of `R(ν)` are combinations of standard basis elements of degree `d`. -/
theorem mem_span_stdElt_of_mem_grade (ρ : Perm (Fin n) → List ℕ)
    (hρ : ∀ w, IsReduced n (ρ w) ∧ wordProd n (ρ w) = w) {d : ℤ} {r : KLRAlgebra k Q ν}
    (hr : r ∈ G.grade ν d) :
    r ∈ Submodule.span k (stdElt (k := k) (Q := Q) ρ ''
      {b | G.degW (ρ b.2.1) b.1 + Finsupp.weight (fun a => G.degX (b.1.lbl a)) b.2.2 = d}) := by
  classical
  have hr' : r ∈ Submodule.span k (Set.range (stdElt (k := k) (Q := Q) ρ)) := by
    rw [span_stdElt ρ hρ]; trivial
  rw [← decompose_of_mem_same (G.grade ν) hr]
  clear hr
  induction hr' using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨b, rfl⟩ := hy
    have hb : stdElt (k := k) (Q := Q) ρ b ∈ G.grade ν
        (G.degW (ρ b.2.1) b.1 + Finsupp.weight (fun a => G.degX (b.1.lbl a)) b.2.2) :=
      G.ψw_mul_pol_monomial_mul_e_mem_grade (ρ b.2.1) b.2.2 b.1
    by_cases h : G.degW (ρ b.2.1) b.1 + Finsupp.weight (fun a => G.degX (b.1.lbl a)) b.2.2 = d
    · rw [decompose_of_mem_same _ (h ▸ hb)]
      exact Submodule.subset_span ⟨b, h, rfl⟩
    · rw [decompose_of_mem_ne _ hb h]
      exact zero_mem _
  | zero => simp
  | add x y _ _ hx hy =>
    rw [decompose_add, add_apply, Submodule.coe_add]; exact add_mem hx hy
  | smul c x _ hx =>
    rw [decompose_smul, DirectSum.smul_apply, Submodule.coe_smul]; exact Submodule.smul_mem _ c hx

include hν in
theorem toNH_mem_constGrade {d e : ℤ} {r : KLRAlgebra k Q ν} (hr : r ∈ G.grade ν d)
    {p : MvPolynomial (Fin n) k} (hp : p ∈ constGrade k n (G.degX i) e) :
    toNH hν Q r p ∈ constGrade k n (G.degX i) (d + e) := by
  have hr' := mem_span_stdElt_of_mem_grade Q G (fun w => canWord n w)
    (fun w => ⟨isReduced_canWord n w, wordProd_canWord n w⟩) hr
  clear hr
  induction hr' using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨b, hb, rfl⟩ := hy
    have := toNH_stdElt_mem hν Q G (fun w => canWord n w) b hp
    rwa [hb] at this
  | zero => rw [map_zero, LinearMap.zero_apply]; exact zero_mem _
  | add x y _ _ hx hy => rw [map_add, LinearMap.add_apply]; exact add_mem hx hy
  | smul c x _ hx => rw [map_smul, LinearMap.smul_apply]; exact Submodule.smul_mem _ c hx

/-- `L(i^n)` is a graded `R(ν)`-module. -/
instance : SetLike.GradedSMul (G.grade ν) (klrGrading hν Q G) where
  smul_mem {d e} r v hr hv := by
    obtain ⟨p, hp, rfl⟩ := hv
    show KLRRep.of hν Q (klrAct hν Q r (Submodule.Quotient.mk p)) ∈ klrGrading hν Q G (d + e)
    rw [klrAct_mk]
    exact mk_mem_quotGrading _ _ (toNH_mem_constGrade hν Q G hr hp)

/-- **`L(i^n)` is a simple graded `R(ν)`-module** (for any grading datum). -/
theorem isGradedSimple_klrRep : IsGradedSimple (G.grade ν) (klrGrading hν Q G) := by
  haveI := isSimpleModule_klrRep hν Q
  exact ⟨inferInstanceAs (Nontrivial (Coinv k n)), fun p _ => IsSimpleOrder.eq_bot_or_eq_top p⟩

end Graded

/-! ### Uniqueness of the simple module -/

variable {P : I → I → MvPolynomial (Fin 2) k}
  (hPQ : ∀ a b, a ≠ b → Q a b = P b a * rename ![1, 0] (P a b))
  (hP : ∀ a b, a ≠ b → P a b ≠ 0)
  (G : GradingDatum Q) (hG : ∀ a, 0 < G.degX a)

/-- Left multiplication by `a ∈ R(ν)` as a `k`-linear endomorphism of an `R(ν)`-module. -/
def smulEnd {M : Type*} [AddCommGroup M] [Module (KLRAlgebra k Q ν) M] [Module k M]
    [IsScalarTower k (KLRAlgebra k Q ν) M] (a : KLRAlgebra k Q ν) : Module.End k M where
  toFun v := a • v
  map_add' := smul_add a
  map_smul' c v := by
    simp only [RingHom.id_apply]
    rw [← algebraMap_smul (KLRAlgebra k Q ν) c v, smul_smul, ← Algebra.commutes, ← smul_smul,
      algebraMap_smul]

include hν hPQ hP hG in
/-- **KL I §2.2**: every simple graded `R(ν)`-module (all labels equal) is isomorphic, as an
ungraded module, to `L(i^n)`. -/
theorem nonempty_linearEquiv_klrRep {M : Type*} [AddCommGroup M]
    [Module (KLRAlgebra k Q ν) M] [Module k M] [IsScalarTower k (KLRAlgebra k Q ν) M]
    (ℳ : ℤ → Submodule k M) [Decomposition ℳ] [SetLike.GradedSMul (G.grade ν) ℳ]
    (hS : IsGradedSimple (G.grade ν) ℳ) :
    Nonempty (KLRRep hν Q ≃ₗ[KLRAlgebra k Q ν] M) := by
  haveI := isSimpleModule_of_isGradedSimple hPQ hP G hG ℳ hS
  haveI := isSimpleModule_klrRep hν Q
  haveI := hS.nontrivial
  -- a nonzero vector killed by all crossings
  have hwords : ∀ ρ : List ℕ, (Multiset.card ν).choose 2 < ρ.length →
      (ρ.map fun j => smulEnd Q (M := M) (ψ j : KLRAlgebra k Q ν)).prod = 0 := by
    intro ρ hρ
    have : (ρ.map fun j => smulEnd Q (M := M) (ψ j : KLRAlgebra k Q ν)).prod =
        smulEnd Q (M := M) (ψw ρ : KLRAlgebra k Q ν) := by
      clear hρ
      induction ρ with
      | nil => ext v; simp [smulEnd, ψw]
      | cons j ρ ih =>
        rw [List.map_cons, List.prod_cons, ih, ψw_cons]
        ext v
        simp [smulEnd, mul_smul]
    rw [this, ψw_eq_zero_of_choose_lt hν Q hρ]
    ext v
    simp [smulEnd]
  obtain ⟨v₀, hv₀⟩ := exists_ne (0 : M)
  obtain ⟨u, -, hu0, hu⟩ := exists_ne_zero_forall_eq_zero
    (fun j : ℕ => smulEnd Q (M := M) (ψ j : KLRAlgebra k Q ν)) ((Multiset.card ν).choose 2)
    hwords Set.univ
    (fun _ _ _ => trivial) (Set.mem_univ v₀) hv₀
  have hψu : ∀ j, (ψ j : KLRAlgebra k Q ν) • u = 0 := hu
  -- the map `L_n → M`, `[p] ↦ p(x) u`
  let φ₀ : MvPolynomial (Fin n) k →ₗ[k] M :=
    (smulRightK (k := k) u).comp (pol : MvPolynomial (Fin n) k →ₐ[k] KLRAlgebra k Q ν).toLinearMap
  have hφ₀ : ∀ p, φ₀ p = (pol p : KLRAlgebra k Q ν) • u := fun p => rfl
  have hsym : ∀ s ∈ symPlusSet k n, (pol s : KLRAlgebra k Q ν) • u = 0 := by
    intro s hs
    have hpol : (pol s : KLRAlgebra k Q ν) = polNu (Function.const (Seq ν) s) := by
      rw [polNu_apply]
      simp only [Function.const_apply]
      rw [← Finset.mul_sum, sum_e, mul_one]
    let f : symNu k ν := ⟨_, const_mem_symNu hs.1⟩
    have hf : f ∈ symNuPlus k ν := (mem_symNuPlus_iff).2 fun _ => hs.2
    rw [hpol]
    exact smul_eq_zero_of_mem_symNuPlus hPQ hP G hG ℳ hS hf u
  have hker : coinvSub k n ≤ LinearMap.ker φ₀ := by
    intro p hp
    rw [LinearMap.mem_ker, hφ₀]
    induction hp using Submodule.span_induction with
    | mem s hs => exact hsym s hs
    | zero => rw [map_zero, zero_smul]
    | add x y _ _ hx hy => rw [map_add, add_smul, hx, hy, add_zero]
    | smul c y _ hy => rw [smul_eq_mul, map_mul, mul_smul, hy, smul_zero]
  let φ₁ : Coinv k n →ₗ[k] M := (coinvSub k n).liftQ φ₀ hker
  have hφ₁ : ∀ p, φ₁ (Submodule.Quotient.mk p) = (pol p : KLRAlgebra k Q ν) • u := fun p => rfl
  -- `R(ν)`-linearity, checked on generators
  have hlin : ∀ r : KLRAlgebra k Q ν, ∀ v : Coinv k n, φ₁ (klrAct hν Q r v) = r • φ₁ v := by
    intro r
    have hr : r ∈ Algebra.adjoin k (Set.range (e (k := k) (Q := Q) (ν := ν)) ∪ Set.range x ∪
        Set.range ψ) := by rw [adjoin_gens]; trivial
    induction hr using Algebra.adjoin_induction with
    | mem y hy =>
      intro v
      obtain ⟨p, rfl⟩ := Submodule.Quotient.mk_surjective _ v
      rcases hy with (⟨t, rfl⟩ | ⟨a, rfl⟩) | ⟨j, rfl⟩
      · rw [e_eq_one_of_forall hν Q t, map_one, Module.End.one_apply, one_smul]
      · rw [klrAct_mk, toNH_x, mulX_apply, hφ₁, hφ₁, map_mul, pol_X, mul_smul]
      · rw [klrAct_mk, toNH_ψ, hφ₁, hφ₁, ← mul_smul]
        obtain ⟨q, hq⟩ := exists_ψ_mul_pol hν Q j p
        rw [hq, add_smul, mul_smul, hψu, smul_zero, add_zero]
    | algebraMap c =>
      intro v
      rw [AlgHom.commutes, Module.algebraMap_end_apply, map_smul, algebraMap_smul]
    | add y z _ _ hy hz => intro v; rw [map_add, LinearMap.add_apply, map_add, hy, hz, add_smul]
    | mul y z _ _ hy hz => intro v; rw [map_mul, Module.End.mul_apply, hy, hz, mul_smul]
  let φ : KLRRep hν Q →ₗ[KLRAlgebra k Q ν] M :=
    { toFun := fun v => φ₁ ((KLRRep.of hν Q).symm v)
      map_add' := fun v w => map_add φ₁ _ _
      map_smul' := fun r v => hlin r ((KLRRep.of hν Q).symm v) }
  have hφ0 : φ ≠ 0 := by
    intro h
    have : φ (KLRRep.of hν Q (Submodule.Quotient.mk 1)) = 0 := by rw [h]; rfl
    apply hu0
    rw [← this]
    show u = φ₁ (Submodule.Quotient.mk 1)
    rw [hφ₁, map_one, one_smul]
  exact ⟨LinearEquiv.ofBijective φ (LinearMap.bijective_of_ne_zero hφ0)⟩

include hν hPQ hP hG in
/-- **KL I §2.2**: the simple graded `R(ν)`-module (all labels equal) is unique up to
isomorphism and grading shift. -/
theorem exists_gradedEquiv_of_isGradedSimple {M N : Type*}
    [AddCommGroup M] [Module (KLRAlgebra k Q ν) M] [Module k M]
    [IsScalarTower k (KLRAlgebra k Q ν) M] (ℳ : ℤ → Submodule k M) [Decomposition ℳ]
    [SetLike.GradedSMul (G.grade ν) ℳ]
    [AddCommGroup N] [Module (KLRAlgebra k Q ν) N] [Module k N]
    [IsScalarTower k (KLRAlgebra k Q ν) N] (𝒩 : ℤ → Submodule k N) [Decomposition 𝒩]
    [SetLike.GradedSMul (G.grade ν) 𝒩]
    (hM : IsGradedSimple (G.grade ν) ℳ) (hN : IsGradedSimple (G.grade ν) 𝒩) :
    ∃ c : ℤ, Nonempty (ℳ ≃ᵍ[KLRAlgebra k Q ν] Graded.shift 𝒩 c) := by
  obtain ⟨eM⟩ := nonempty_linearEquiv_klrRep hν Q hPQ hP G hG ℳ hM
  obtain ⟨eN⟩ := nonempty_linearEquiv_klrRep hν Q hPQ hP G hG 𝒩 hN
  exact exists_gradedEquiv_shift_of_linearEquiv G ℳ 𝒩 hM hN (eM.symm.trans eN)

include hν hPQ hP hG in
/-- **KL I §2.2**: every simple graded `R(ν)`-module (all labels equal to `i`, dots of positive
degree) is isomorphic to a grading shift of `L(i^n)`. -/
theorem exists_gradedEquiv_klrRep {M : Type*} [AddCommGroup M]
    [Module (KLRAlgebra k Q ν) M] [Module k M] [IsScalarTower k (KLRAlgebra k Q ν) M]
    (ℳ : ℤ → Submodule k M) [Decomposition ℳ] [SetLike.GradedSMul (G.grade ν) ℳ]
    (hS : IsGradedSimple (G.grade ν) ℳ) :
    ∃ c : ℤ, Nonempty (ℳ ≃ᵍ[KLRAlgebra k Q ν] Graded.shift (klrGrading hν Q G) c) :=
  exists_gradedEquiv_of_isGradedSimple hν Q hPQ hP G hG ℳ (klrGrading hν Q G) hS
    (isGradedSimple_klrRep hν Q G)

end KLRAlgebra

/-! ### The rings of KL I -/

namespace KL1

open KLRAlgebra

variable {Γ : SimpleGraph I} [DecidableRel Γ.Adj] {ν : Multiset I} {i : I} (hν : ∀ a ∈ ν, a = i)

include hν in
/-- **KL I §2.2** for the rings `R(ν)` of KL I (all labels of `ν` equal to `i`, e.g. `ν = m i`),
over a field: every simple graded `R(ν)`-module is isomorphic to `L(i^m)`. -/
theorem nonempty_linearEquiv_klrRep {M : Type*} [AddCommGroup M] [Module (R1 k Γ ν) M]
    [Module k M] [IsScalarTower k (R1 k Γ ν) M] (ℳ : ℤ → Submodule k M) [Decomposition ℳ]
    [SetLike.GradedSMul ((klGradingDatum k Γ).grade ν) ℳ]
    (hS : IsGradedSimple ((klGradingDatum k Γ).grade ν) ℳ) :
    Nonempty (KLRRep hν (klQ (k := k) Γ) ≃ₗ[R1 k Γ ν] M) :=
  KLRAlgebra.nonempty_linearEquiv_klrRep hν _ (klQ_eq_klP (Γ := Γ) stdOrient_spec)
    (fun a b _ => klP_ne_zero _ a b) (klGradingDatum k Γ) klGradingDatum_degX_pos ℳ hS

include hν in
/-- **KL I §2.2** for the rings of KL I: the simple graded `R(m i)`-module is unique up to
isomorphism and grading shift. -/
theorem exists_gradedEquiv_of_isGradedSimple {M N : Type*}
    [AddCommGroup M] [Module (R1 k Γ ν) M] [Module k M] [IsScalarTower k (R1 k Γ ν) M]
    (ℳ : ℤ → Submodule k M) [Decomposition ℳ] [SetLike.GradedSMul ((klGradingDatum k Γ).grade ν) ℳ]
    [AddCommGroup N] [Module (R1 k Γ ν) N] [Module k N] [IsScalarTower k (R1 k Γ ν) N]
    (𝒩 : ℤ → Submodule k N) [Decomposition 𝒩] [SetLike.GradedSMul ((klGradingDatum k Γ).grade ν) 𝒩]
    (hM : IsGradedSimple ((klGradingDatum k Γ).grade ν) ℳ)
    (hN : IsGradedSimple ((klGradingDatum k Γ).grade ν) 𝒩) :
    ∃ c : ℤ, Nonempty (ℳ ≃ᵍ[R1 k Γ ν] Graded.shift 𝒩 c) :=
  KLRAlgebra.exists_gradedEquiv_of_isGradedSimple hν _ (klQ_eq_klP (Γ := Γ) stdOrient_spec)
    (fun a b _ => klP_ne_zero _ a b) (klGradingDatum k Γ) klGradingDatum_degX_pos ℳ 𝒩 hM hN

include hν in
/-- **KL I §2.2** for the rings of KL I: `L(i^m)`, graded by `deg x_a = 2`, is a simple graded
`R(m i)`-module, and every simple graded `R(m i)`-module is isomorphic to `L(i^m){c}` for some
`c`. -/
theorem exists_gradedEquiv_klrRep {M : Type*} [AddCommGroup M] [Module (R1 k Γ ν) M]
    [Module k M] [IsScalarTower k (R1 k Γ ν) M] (ℳ : ℤ → Submodule k M) [Decomposition ℳ]
    [SetLike.GradedSMul ((klGradingDatum k Γ).grade ν) ℳ]
    (hS : IsGradedSimple ((klGradingDatum k Γ).grade ν) ℳ) :
    IsGradedSimple ((klGradingDatum k Γ).grade ν) (klrGrading hν _ (klGradingDatum k Γ)) ∧
      ∃ c : ℤ, Nonempty (ℳ ≃ᵍ[R1 k Γ ν]
        Graded.shift (klrGrading hν (klQ (k := k) Γ) (klGradingDatum k Γ)) c) :=
  ⟨isGradedSimple_klrRep hν _ _,
    KLRAlgebra.exists_gradedEquiv_klrRep hν _ (klQ_eq_klP (Γ := Γ) stdOrient_spec)
      (fun a b _ => klP_ne_zero _ a b) (klGradingDatum k Γ) klGradingDatum_degX_pos ℳ hS⟩

end KL1

end Categorification.KLR
