/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.Prop320

/-!
# KL I, Theorem 1.1: `γ : _𝒜 f → K₀(R)` is an isomorphism

M. Khovanov, A. Lauda, *A diagrammatic approach to categorification of quantum groups I*,
arXiv:0803.4121v2, **Theorem 1.1** (TeX lines ~290–305; proof completed at the end of §3.2,
TeX lines 2275–2303):

> `γ : _𝒜 f → K₀(R)` is an isomorphism of `ℤ[q, q⁻¹]`-algebras.

Here `Γ` is any graph (no loops, no multiple edges; the simply-laced Cartan datum of `Γ`), `R` is
the KL I algebra `⊕_ν R(ν)` over a field `𝕜`, `_𝒜 f` is Lusztig's integral form (generated by the
divided powers `θ_i^{(a)}`), and `γ` sends `θ_{i_1}^{(a_1)} ⋯ θ_{i_r}^{(a_r)}` to the class of the
divided-power projective `P_{i_1^{(a_1)} ⋯ i_r^{(a_r)}}`.

## Hypotheses

The only hypothesis is the **quantum Gabber–Kac theorem** for the Cartan datum of `Γ`,
`hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c` (the radical of Lusztig's form on `'f` is
generated by the quantum Serre elements), which the repository uses to identify `f = 'f/ℐ` with
the algebra presented by the Serre relations; it is needed to *define* `γ` on `f`. It is an
explicit hypothesis of the statements below, not an axiom. Everything else is proved:

* injectivity (KL I, Proposition 3.4): `KLGamma.gammaInt_injective`;
* torsion-freeness of `K₀(R)` over `ℤ[q, q⁻¹]` (so that `γ` takes values in `K₀(R)` itself):
  `KLGamma.toK0Q_injective`, giving `KLGamma.gammaInt'`;
* surjectivity: `KLGamma.k0B_mem_span_projDiv` (KL I, Proposition 3.20, which uses Theorem 3.17,
  Corollary 3.19 and the crystal Lemmas 3.5–3.8), and, over `ℚ(q)`,
  `KLGamma.gammaF_surjective` (Proposition 3.18).

The paper proves the surjectivity for finite `Γ` (with a fixed order of the vertices) and passes
to infinite `Γ` by a direct limit. The argument formalized here orders the letters by an arbitrary
injection into a linear order, so it applies to every `Γ` directly (for each weight `ν` only the
finitely many vertices in the support of `ν` occur).

## Main results

* `KLGamma.gammaInt_surjective`, `KLGamma.gammaInt'_surjective` : `γ` is surjective.
* `KLGamma.theorem_1_1` : **`γ : _𝒜 f → K₀(R)` is bijective**; `KLGamma.gammaIntEquiv` : the ring
  isomorphism `_𝒜 f ≃+* K₀(R)`, with `gammaIntEquiv_dpowMono`
  (`θ_{i_1}^{(a_1)} ⋯ θ_{i_r}^{(a_r)} ↦ [P_{i_1^{(a_1)} ⋯ i_r^{(a_r)}}]`) and `gammaIntEquiv_smul`
  (`ℤ[q, q⁻¹]`-linearity, `q` acting on `_𝒜 f` as `v⁻¹`).
* `KLGamma.gammaFEquiv` (Proposition 3.18): the `ℚ(q)`-algebra isomorphism `f ≅ K₀(R)_{ℚ(q)}`.
-/

noncomputable section

namespace Categorification.KLR.KLGamma

open Graded LaurentPolynomial QuantumGroup KLRAlgebra

variable {I : Type*} [DecidableEq I] (k : Type*) [Field k] (Γ : SimpleGraph I)
  [DecidableRel Γ.Adj]

local notation "Gkl" => klGradingDatum k Γ

/-- The image of `γ`, a `ℤ[q, q⁻¹]`-submodule of `K₀(R)` (`gammaInt_smul`). -/
def rangeGammaInt (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c)
    (hinj : Function.Injective (toK0Q k Γ)) :
    Submodule (LaurentPolynomial ℤ) (Gkl).K0R where
  carrier := Set.range (gammaInt k Γ hGK hinj)
  add_mem' := by
    rintro _ _ ⟨x, rfl⟩ ⟨y, rfl⟩
    exact ⟨x + y, map_add _ x y⟩
  zero_mem' := ⟨0, map_zero _⟩
  smul_mem' := by
    rintro p _ ⟨x, rfl⟩
    exact ⟨_, gammaInt_smul k Γ hGK hinj p x⟩

/-- **KL I, Theorem 1.1, surjectivity**: `γ : _𝒜 f → K₀(R)` is surjective. -/
theorem gammaInt_surjective (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c)
    (hinj : Function.Injective (toK0Q k Γ)) :
    Function.Surjective (gammaInt k Γ hGK hinj) := by
  classical
  set S := rangeGammaInt k Γ hGK hinj
  have hdiv : ∀ (ν : Multiset I) (d : List (I × ℕ)) (h : (expandDiv d : Multiset I) = ν),
      DirectSum.of (Gkl).K0fam ν (K0.of (projDiv k Γ d h)) ∈ S := fun ν d h =>
    ⟨⟨KL.π Γ (dpowMono Γ d), π_dpowMono_mem_Af Γ d⟩, by
      rw [gammaInt_dpowMono, clsDiv_eq k Γ d h]⟩
  have hb : ∀ (ν : Multiset I) (b : GProj.IndecClass ((Gkl).grade ν)),
      DirectSum.of (Gkl).K0fam ν (k0B k Γ ν b) ∈ S := by
    intro ν b
    have hle : Submodule.span (LaurentPolynomial ℤ)
        {z | ∃ (d : List (I × ℕ)) (h : (expandDiv d : Multiset I) = ν),
          z = K0.of (projDiv k Γ d h)} ≤
        S.comap (DirectSum.lof (LaurentPolynomial ℤ) (Multiset I) (Gkl).K0fam ν) := by
      rw [Submodule.span_le]
      rintro _ ⟨d, h, rfl⟩
      show DirectSum.lof (LaurentPolynomial ℤ) (Multiset I) (Gkl).K0fam ν _ ∈ S
      rw [DirectSum.lof_eq_of]
      exact hdiv ν d h
    have := hle (k0B_mem_span_projDiv k Γ ν b)
    rwa [Submodule.mem_comap, DirectSum.lof_eq_of] at this
  have htop : S = ⊤ := by
    refine Submodule.eq_top_iff'.2 fun z => ?_
    induction z using DirectSum.induction_on with
    | zero => exact S.zero_mem
    | of ν x =>
      haveI := ((Gkl).finite_and_card_indecClass_le (klQ_eq_klP (Γ := Γ) KL1.stdOrient_spec)
        (fun a b _ => KL1.klP_ne_zero _ a b) KL1.klGradingDatum_degX_pos ν).1
      haveI := Fintype.ofFinite (GProj.IndecClass ((Gkl).grade ν))
      rw [← (k0B k Γ ν).sum_repr x, map_sum]
      refine S.sum_mem fun b _ => ?_
      rw [K0R_of_smul]
      exact S.smul_mem _ (hb ν b)
    | add x y hx hy => exact S.add_mem hx hy
  intro z
  have : z ∈ S := htop ▸ Submodule.mem_top
  exact this

/-- `γ : _𝒜 f → K₀(R)` (`gammaInt'`, with the torsion-freeness of `K₀(R)` proved) is
surjective. -/
theorem gammaInt'_surjective (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c) :
    Function.Surjective (gammaInt' k Γ hGK) :=
  gammaInt_surjective k Γ hGK (toK0Q_injective k Γ)

/-- **KL I, Theorem 1.1**: for any graph `Γ` and any field `𝕜`, `γ : _𝒜 f → K₀(R)` is bijective
(under the quantum Gabber–Kac hypothesis `hGK` used to define `f`). -/
theorem theorem_1_1 (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c) :
    Function.Bijective (gammaInt' k Γ hGK) :=
  ⟨gammaInt_injective k Γ hGK (toK0Q_injective k Γ), gammaInt'_surjective k Γ hGK⟩

/-- **KL I, Theorem 1.1**: the isomorphism `γ : _𝒜 f ≅ K₀(R)`. -/
def gammaIntEquiv (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c) :
    KL.Af Γ ≃+* (Gkl).K0R :=
  RingEquiv.ofBijective (gammaInt' k Γ hGK) (theorem_1_1 k Γ hGK)

@[simp] theorem gammaIntEquiv_apply (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c)
    (x : KL.Af Γ) : gammaIntEquiv k Γ hGK x = gammaInt' k Γ hGK x := rfl

/-- `γ(θ_{i_1}^{(a_1)} ⋯ θ_{i_r}^{(a_r)}) = [P_{i_1^{(a_1)} ⋯ i_r^{(a_r)}}]`. -/
theorem gammaIntEquiv_dpowMono (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c)
    (d : List (I × ℕ)) :
    gammaIntEquiv k Γ hGK ⟨KL.π Γ (dpowMono Γ d), π_dpowMono_mem_Af Γ d⟩ = clsDiv k Γ d :=
  gammaInt_dpowMono k Γ hGK (toK0Q_injective k Γ) d

/-- `γ` is an isomorphism of `ℤ[q, q⁻¹]`-modules (`q` acting on `_𝒜 f` as `v⁻¹`, and on
`K₀(R)` by the grading shift). -/
theorem gammaIntEquiv_smul (hGK : PreF.GabberKac (KL.C Γ).dot vQ (KL.C Γ).c)
    (p : LaurentPolynomial ℤ) (x : KL.Af Γ) :
    gammaIntEquiv k Γ hGK
        ⟨algebraMap (RatFunc ℚ) (KL.F Γ) (qToV p) * x,
          Subring.mul_mem _ (algebraMap_qToV_mem_Af Γ p) x.2⟩ =
      p • gammaIntEquiv k Γ hGK x :=
  gammaInt_smul k Γ hGK (toK0Q_injective k Γ) p x

end Categorification.KLR.KLGamma
