/-
Copyright (c) 2026 Alex Ellis. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Categorification.KLR.KL2.Prop320KL2

/-!
# KL II, Theorem 8: `γ : _𝒜 f → K₀(R)` is an isomorphism for an arbitrary Cartan datum

M. Khovanov, A. Lauda, *A diagrammatic approach to categorification of quantum groups II*,
arXiv:0804.2080v1, §3, paragraph "Grothendieck group as the quantum group", **Theorem 8**:

> `γ : _𝒜 f → K₀(R)` is an isomorphism of `ℕ[I]`-graded twisted bialgebras.

("The proof of [KL I, Theorem 1.1] carries over to an arbitrary Cartan datum.") Here `C` is a
Cartan datum (`QuantumGroup.CartanDatum`: symmetric, `i · i ∈ 2ℤ_{>0}`,
`2 (i·j)/(i·i) ∈ ℤ_{≤0}`), `R = ⊕_ν R(ν)` the KL II rings over a field `𝕜` with
`deg x_{a,i} = i_a · i_a`, `_𝒜 f` Lusztig's integral form for `C` (generated by the divided
powers `θ_i^{(a)} = θ_i^a / [a]_{v_i}^!`, `v_i = v^{(i·i)/2}`), and `γ` sends
`θ_{i_1}^{(a_1)} ⋯ θ_{i_r}^{(a_r)}` to the class of the divided-power projective
`P_{i_1^{(a_1)} ⋯ i_r^{(a_r)}}` (`KL2Gamma.gammaInt2'`).

## Scope and hypotheses

This file proves the **isomorphism** part: `γ` is a bijective ring homomorphism, `ℤ[q, q⁻¹]`-linear
(`q` acting on `_𝒜 f` as `v⁻¹`), sending divided-power monomials to divided-power projectives. The
compatibility with the twisted coproducts (`[Res] ∘ γ = (γ ⊗ γ) ∘ r`) is not part of this file.

The only hypothesis is the **quantum Gabber–Kac theorem** for `C`, `hGK : C.GabberKac vQ C.c`
(the radical of Lusztig's form on `'f` is generated by the quantum Serre elements; Lusztig 33.1.3),
used to identify `f = 'f/ℐ` with the algebra presented by the Serre relations and hence to *define*
`γ` on `f`. It is an explicit hypothesis, not an axiom. Everything else is proved:

* injectivity (KL I, Proposition 3.4 for KL II): `KL2Gamma.gammaInt2_injective`;
* torsion-freeness of `K₀(R)` (`KL2Gamma.toK0Q2_injective`), giving `KL2Gamma.gammaInt2'`;
* surjectivity: `KL2Gamma.k0B2_mem_span_projDiv2` (KL I, Proposition 3.20 for KL II, via the
  general `GradingDatum.k0Basis_mem_span_of_div`), and over `ℚ(q)` `KL2Gamma.gammaF2_surjective`
  (Proposition 3.18 for KL II).

## Main results

* `KL2Gamma.gammaInt2_surjective`, `KL2Gamma.gammaInt2'_surjective` : `γ` is surjective.
* `KL2Gamma.theorem_8` : **`γ : _𝒜 f → K₀(R)` is bijective**; `KL2Gamma.gammaInt2Equiv` : the ring
  isomorphism `_𝒜 f ≃+* K₀(R)`, with `gammaInt2Equiv_dpowMono`
  (`θ_{i_1}^{(a_1)} ⋯ θ_{i_r}^{(a_r)} ↦ [P_{i_1^{(a_1)} ⋯ i_r^{(a_r)}}]`) and
  `gammaInt2Equiv_smul` (`ℤ[q, q⁻¹]`-linearity).
* `KL2Gamma.gammaF2Equiv` (in `Prop318KL2`): the `ℚ(q)`-algebra isomorphism `f ≅ K₀(R)_{ℚ(q)}`.
-/

noncomputable section

namespace Categorification.KLR.KL2Gamma

open Graded LaurentPolynomial QuantumGroup KLRAlgebra KLGamma KL2

variable {I : Type*} [DecidableEq I] (k : Type*) [Field k] (C : CartanDatum I)

local notation "G2" => klGradingDatum2 k C

/-- The image of `γ`, a `ℤ[q, q⁻¹]`-submodule of `K₀(R)` (`gammaInt2_smul`). -/
def rangeGammaInt2 (hGK : C.GabberKac vQ C.c) (hinj : Function.Injective (toK0Q2 k C)) :
    Submodule (LaurentPolynomial ℤ) (G2).K0R where
  carrier := Set.range (gammaInt2 k C hGK hinj)
  add_mem' := by
    rintro _ _ ⟨x, rfl⟩ ⟨y, rfl⟩
    exact ⟨x + y, map_add _ x y⟩
  zero_mem' := ⟨0, map_zero _⟩
  smul_mem' := by
    rintro p _ ⟨x, rfl⟩
    exact ⟨_, gammaInt2_smul k C hGK hinj p x⟩

/-- **KL II, Theorem 8, surjectivity**: `γ : _𝒜 f → K₀(R)` is surjective. -/
theorem gammaInt2_surjective (hGK : C.GabberKac vQ C.c)
    (hinj : Function.Injective (toK0Q2 k C)) :
    Function.Surjective (gammaInt2 k C hGK hinj) := by
  classical
  set S := rangeGammaInt2 k C hGK hinj
  have hdiv : ∀ (ν : Multiset I) (d : List (I × ℕ)) (h : (expandDiv d : Multiset I) = ν),
      DirectSum.of (G2).K0fam ν (K0.of (projDiv2 k C d h)) ∈ S := fun ν d h =>
    ⟨⟨PreF.π C.dot vQ C.c (dpowMono2 C d), π_dpowMono2_mem_Af C d⟩, by
      rw [gammaInt2_dpowMono, clsDiv2_eq k C d h]⟩
  have hb : ∀ (ν : Multiset I) (b : GProj.IndecClass ((G2).grade ν)),
      DirectSum.of (G2).K0fam ν (k0B2 k C ν b) ∈ S := by
    intro ν b
    have hle : Submodule.span (LaurentPolynomial ℤ)
        {z | ∃ (d : List (I × ℕ)) (h : (expandDiv d : Multiset I) = ν),
          z = K0.of (projDiv2 k C d h)} ≤
        S.comap (DirectSum.lof (LaurentPolynomial ℤ) (Multiset I) (G2).K0fam ν) := by
      rw [Submodule.span_le]
      rintro _ ⟨d, h, rfl⟩
      show DirectSum.lof (LaurentPolynomial ℤ) (Multiset I) (G2).K0fam ν _ ∈ S
      rw [DirectSum.lof_eq_of]
      exact hdiv ν d h
    have := hle (k0B2_mem_span_projDiv2 k C ν b)
    rwa [Submodule.mem_comap, DirectSum.lof_eq_of] at this
  have htop : S = ⊤ := by
    refine Submodule.eq_top_iff'.2 fun z => ?_
    induction z using DirectSum.induction_on with
    | zero => exact S.zero_mem
    | of ν x =>
      haveI := finite_indecClass2 k C ν
      haveI := Fintype.ofFinite (GProj.IndecClass ((G2).grade ν))
      rw [← (k0B2 k C ν).sum_repr x, map_sum]
      refine S.sum_mem fun b _ => ?_
      rw [K0R_of_smul2]
      exact S.smul_mem _ (hb ν b)
    | add x y hx hy => exact S.add_mem hx hy
  intro z
  have : z ∈ S := htop ▸ Submodule.mem_top
  exact this

/-- `γ : _𝒜 f → K₀(R)` (`gammaInt2'`, with the torsion-freeness of `K₀(R)` proved) is
surjective. -/
theorem gammaInt2'_surjective (hGK : C.GabberKac vQ C.c) :
    Function.Surjective (gammaInt2' k C hGK) :=
  gammaInt2_surjective k C hGK (toK0Q2_injective k C)

/-- **KL II, Theorem 8** (isomorphism part): for any Cartan datum `C` and any field `𝕜`,
`γ : _𝒜 f → K₀(R)` is bijective (under the quantum Gabber–Kac hypothesis `hGK` used to define
`f`). -/
theorem theorem_8 (hGK : C.GabberKac vQ C.c) : Function.Bijective (gammaInt2' k C hGK) :=
  ⟨gammaInt2'_injective k C hGK, gammaInt2'_surjective k C hGK⟩

/-- **KL II, Theorem 8**: the ring isomorphism `γ : _𝒜 f ≅ K₀(R)`. -/
def gammaInt2Equiv (hGK : C.GabberKac vQ C.c) : C.Af ≃+* (G2).K0R :=
  RingEquiv.ofBijective (gammaInt2' k C hGK) (theorem_8 k C hGK)

@[simp] theorem gammaInt2Equiv_apply (hGK : C.GabberKac vQ C.c) (x : C.Af) :
    gammaInt2Equiv k C hGK x = gammaInt2' k C hGK x := rfl

/-- `γ(θ_{i_1}^{(a_1)} ⋯ θ_{i_r}^{(a_r)}) = [P_{i_1^{(a_1)} ⋯ i_r^{(a_r)}}]`, divided powers in
`v_i = v^{(i·i)/2}`. -/
theorem gammaInt2Equiv_dpowMono (hGK : C.GabberKac vQ C.c) (d : List (I × ℕ)) :
    gammaInt2Equiv k C hGK ⟨PreF.π C.dot vQ C.c (dpowMono2 C d), π_dpowMono2_mem_Af C d⟩ =
      clsDiv2 k C d :=
  gammaInt2_dpowMono k C hGK (toK0Q2_injective k C) d

/-- `γ` is an isomorphism of `ℤ[q, q⁻¹]`-modules (`q` acting on `_𝒜 f` as `v⁻¹`, and on `K₀(R)`
by the grading shift). -/
theorem gammaInt2Equiv_smul (hGK : C.GabberKac vQ C.c) (p : LaurentPolynomial ℤ) (x : C.Af) :
    gammaInt2Equiv k C hGK
        ⟨algebraMap (RatFunc ℚ) C.F (qToV p) * x,
          Subring.mul_mem _ (algebraMap_qToV_mem_Af2 C p) x.2⟩ =
      p • gammaInt2Equiv k C hGK x :=
  gammaInt2_smul k C hGK (toK0Q2_injective k C) p x

end Categorification.KLR.KL2Gamma
